export const FE8SummoneditorEntries = [
  { label: 'Entry 0', value: 0 },
];

export const Classlist = [
  { label: 'Separator/Nothing', value: 0x00 },
  { label: 'Ephraim Lord', value: 0x01 },
  { label: 'Eirika Lord', value: 0x02 },
  { label: 'Ephraim Master Lord', value: 0x03 },
  { label: 'Eirika Master Lord', value: 0x04 },
  { label: 'Social Knight', value: 0x05 },
  { label: 'Social Knight (F)', value: 0x06 },
  { label: 'Paladin', value: 0x07 },
  { label: 'Paladin (F)', value: 0x08 },
  { label: 'Armour Knight', value: 0x09 },
  { label: 'Armour Knight (F)', value: 0x0A },
  { label: 'General', value: 0x0B },
  { label: 'General (F)', value: 0x0C },
  { label: 'Thief', value: 0x0D },
  { label: 'Mamkute', value: 0x0E },
  { label: 'Mercenary', value: 0x0F },
  { label: 'Mercenary (F)', value: 0x10 },
  { label: 'Hero', value: 0x11 },
  { label: 'Hero (F)', value: 0x12 },
  { label: 'Swordfighter', value: 0x13 },
  { label: 'Swordfighter (F)', value: 0x14 },
  { label: 'Swordmaster', value: 0x15 },
  { label: 'Swordmaster (F)', value: 0x16 },
  { label: 'Assassin', value: 0x17 },
  { label: 'Assassin (F)', value: 0x18 },
  { label: 'Archer', value: 0x19 },
  { label: 'Archer (F)', value: 0x1A },
  { label: 'Sniper', value: 0x1B },
  { label: 'Sniper (F)', value: 0x1C },
  { label: 'Forrest Knight', value: 0x1D },
  { label: 'Forrest Knight (F)', value: 0x1E },
  { label: 'Dragon Knight', value: 0x1F },
  { label: 'Dragon Knight (F)', value: 0x20 },
  { label: 'Dragon Master', value: 0x21 },
  { label: 'Dragon Master (F)', value: 0x22 },
  { label: 'Wyvern Knight', value: 0x23 },
  { label: 'Wyvern Knight (F)', value: 0x24 },
  { label: 'Mage', value: 0x25 },
  { label: 'Mage (F)', value: 0x26 },
  { label: 'Sage', value: 0x27 },
  { label: 'Sage (F)', value: 0x28 },
  { label: 'Mage Knight', value: 0x29 },
  { label: 'Mage Knight (F)', value: 0x2A },
  { label: 'Bishop', value: 0x2B },
  { label: 'Bishop (F)', value: 0x2C },
  { label: 'Shaman', value: 0x2D },
  { label: 'Shaman (F)', value: 0x2E },
  { label: 'Druid', value: 0x2F },
  { label: 'Druid (F)', value: 0x30 },
  { label: 'Summoner', value: 0x31 },
  { label: 'Summoner (F)', value: 0x32 },
  { label: 'Rogue', value: 0x33 },
  { label: 'Gorgon Egg', value: 0x34 },
  { label: 'Great Knight', value: 0x35 },
  { label: 'Great Knight (F)', value: 0x36 },
  { label: 'Trainee Soldier (2)', value: 0x37 },
  { label: 'Trainee Fighter (3)', value: 0x38 },
  { label: 'Trainee Mage (3)', value: 0x39 },
  { label: 'Trainee Soldier (3)', value: 0x3A },
  { label: 'Mamkute', value: 0x3B },
  { label: 'Mamkute (F)', value: 0x3C },
  { label: 'Trainee Fighter (1)', value: 0x3D },
  { label: 'Trainee Mage (1)', value: 0x3E },
  { label: 'Fighter', value: 0x3F },
  { label: 'Warrior', value: 0x40 },
  { label: 'Mountain Thief', value: 0x41 },
  { label: 'Pirate', value: 0x42 },
  { label: 'Berserker', value: 0x43 },
  { label: 'Monk', value: 0x44 },
  { label: 'Priest', value: 0x45 },
  { label: 'Bard', value: 0x46 },
  { label: 'Trainee Soldier (1)', value: 0x47 },
  { label: 'Pegasus Knight', value: 0x48 },
  { label: 'Falcon Knight', value: 0x49 },
  { label: 'Sister', value: 0x4A },
  { label: 'Troubadour', value: 0x4B },
  { label: 'Valkyrie', value: 0x4C },
  { label: 'Dancer', value: 0x4D },
  { label: 'Soldier', value: 0x4E },
  { label: 'Necromancer', value: 0x4F },
  { label: 'Fleet', value: 0x50 },
  { label: 'Ghost Fighter', value: 0x51 },
  { label: 'Zombie', value: 0x52 },
  { label: 'Mummy', value: 0x53 },
  { label: 'Skeleton', value: 0x54 },
  { label: 'Skeleton (Bow)', value: 0x55 },
  { label: 'Hellbone', value: 0x56 },
  { label: 'Hellbone (Bow)', value: 0x57 },
  { label: 'Bael', value: 0x58 },
  { label: 'Elder Bael', value: 0x59 },
  { label: 'Cyclops', value: 0x5A },
  { label: 'Mauthedoog', value: 0x5B },
  { label: 'Cerberus', value: 0x5C },
  { label: 'Tarvos', value: 0x5D },
  { label: 'Macdaire', value: 0x5E },
  { label: 'Bigl', value: 0x5F },
  { label: 'Arch Bigl', value: 0x60 },
  { label: 'Gorgon', value: 0x61 },
  { label: 'Gorgon Egg', value: 0x62 },
  { label: 'Gargoyle', value: 0x63 },
  { label: 'Death Gargoyle', value: 0x64 },
  { label: 'Dragon Zombie', value: 0x65 },
  { label: 'Demon King', value: 0x66 },
  { label: 'Archer on Ballista', value: 0x67 },
  { label: 'Archer on Iron Ballista', value: 0x68 },
  { label: 'Archer on Killer Ballista', value: 0x69 },
  { label: 'Ballista', value: 0x6A },
  { label: 'Iron Ballista', value: 0x6B },
  { label: 'Killer Ballista', value: 0x6C },
  { label: 'Civilian', value: 0x6D },
  { label: 'Civilian (F)', value: 0x6E },
  { label: 'Civilian', value: 0x6F },
  { label: 'Civilian (F)', value: 0x70 },
  { label: 'Civilian', value: 0x71 },
  { label: 'Civilian (F)', value: 0x72 },
  { label: 'Peer', value: 0x73 },
  { label: 'Queen', value: 0x74 },
  { label: 'Prince', value: 0x75 },
  { label: 'Queen', value: 0x76 },
  { label: '(empty)', value: 0x77 },
  { label: 'Fallen Prince', value: 0x78 },
  { label: 'Tent', value: 0x79 },
  { label: 'Pontifex', value: 0x7A },
  { label: 'Fallen Peer', value: 0x7B },
  { label: 'Cyclops', value: 0x7C },
  { label: 'Elder Bael', value: 0x7D },
  { label: 'Trainee Fighter (2)', value: 0x7E },
  { label: 'Trainee Mage (2)', value: 0x7F },
];
