export const Chapters = [
  { label: 'Prologue: A Girl from the Plains', value: 0 },
  { label: 'Ch. 1: Footsteps of Fate', value: 1 },
  { label: 'Ch. 2: Sword of Spirits', value: 2 },
  { label: 'Ch. 3: Band of Mercenaries', value: 3 },
  { label: 'Ch. 4: In Occupation\'s Shadow', value: 4 },
  { label: 'Ch. 5: Beyond the Borders', value: 5 },
  { label: 'Ch. 6: Blood of Pride', value: 6 },
  { label: 'Ch. 7: Siblings Abroad', value: 7 },
  { label: 'Ch. 7x: The Black Shadow', value: 8 },
  { label: 'Ch. 8: Vortex of Strategy', value: 9 },
  { label: 'Ch. 9: A Grim Reunion', value: 10 },
  { label: 'Ch. 10: The Distant Plains', value: 11 },
  { label: 'Ch. 11: Taking Leave (E)', value: 12 },
  { label: 'Ch. 11: Another Journey (H)', value: 13 },
  { label: 'Ch. 12: Birds of a Feather', value: 14 },
  { label: 'Ch. 13: In Search of Truth', value: 15 },
  { label: 'Ch. 13x: The Peddler Merlinus', value: 16 },
  { label: 'Ch. 14: False Friends', value: 17 },
  { label: 'Ch. 15: Talons Alight (H)', value: 18 },
  { label: 'Ch. 15/16: Noble Lady of Caelin', value: 19 },
  { label: 'Ch. 16/17: Whereabouts Unknown', value: 20 },
  { label: 'Ch. 16x/17x: The Port of Badon', value: 21 },
  { label: 'Ch. 17/18: Pirate Ship', value: 22 },
  { label: 'Ch. 18/19: The Dread Isle', value: 23 },
  { label: 'Ch. 18x/19x: Imprisoner of Magic', value: 24 },
  { label: 'Ch. 19x pt2: A Glimpse in Time (H)', value: 25 },
  { label: 'Ch. 19/20: Dragon\'s Gate', value: 26 },
  { label: 'Ch. 20/21: New Resolve', value: 27 },
  { label: 'Ch. 21/22: Kinship\'s Bond', value: 28 },
  { label: 'Ch. 22/23: Living Legend', value: 29 },
  { label: 'Ch. 22x/23x: Genesis', value: 30 },
  { label: 'Ch. 23/24: Four-Fanged Offense (Lloyd)', value: 31 },
  { label: 'Ch. 23/24: Four-Fanged Offense (Linus)', value: 32 },
  { label: 'Ch. 25: Crazed Beast (H)', value: 33 },
  { label: 'Ch. 24/26: Unfulfilled Heart', value: 34 },
  { label: 'Ch. 25/27: Pale Flower of Darkness (Kenneth)', value: 35 },
  { label: 'Ch. 25/27: Pale Flower of Darkness (Jerme)', value: 36 },
  { label: 'Ch. 26/28: Battle before Dawn', value: 37 },
  { label: 'Ch. 26x/28x: Night of Farewells', value: 38 },
  { label: 'Ch. 27/29: Cog of Destiny', value: 39 },
  { label: 'Ch. 28: Valorous Roland (E)', value: 40 },
  { label: 'Ch. 30: The Berserker (H)', value: 41 },
  { label: 'Ch. 29/31: Sands of Time', value: 42 },
  { label: 'Ch. 29x/31x: Battle Preparations', value: 43 },
  { label: 'Ch. 30/32: Victory or Death', value: 44 },
  { label: 'Ch. 32x: The Value of Life (H)', value: 45 },
  { label: 'Final Chapter: Light (pt1)', value: 46 },
  { label: 'Final Chapter: Light (pt2)', value: 47 },
  { label: 'Outside Araphen', value: 48 },
  { label: 'Outside fort', value: 49 },
  { label: 'Ostia', value: 50 },
  { label: 'Castle', value: 51 },
  { label: 'Laus', value: 52 },
  { label: 'Nergal and kids flashback', value: 53 },
  { label: 'Meeting with Uther', value: 54 },
  { label: 'Athos\' place (Sacred Shrine)', value: 55 },
  { label: 'Messed up building', value: 56 },
  { label: 'Town with Nino (talk w/Lloyd + Linus)', value: 57 },
  { label: 'Path to the HQ (Lyn uses tracking)', value: 58 },
  { label: 'Black Fang HQ', value: 59 },
  { label: 'Forests and stuff', value: 60 },
  { label: 'Nighttime village (Jaffar + Nino leave for Sonia)', value: 61 },
  { label: 'Cave with Ninian (Ch. 19xx Teodor n stuff)', value: 62 },
  { label: 'Ostia with Athos (Telling about history)', value: 63 },
  { label: 'Closed dragons gate', value: 64 },
  { label: 'Link Arena (Hm?)', value: 65 },
];

export default Chapters;
