export const ItemList = [
  { label: 'Iron Sword', value: 0 },
  { label: 'Steel Sword', value: 1 },
  { label: 'Silver Sword', value: 2 },
  { label: 'Killing Edge', value: 3 },
  { label: 'Levin Sword', value: 4 },
  { label: 'Devil Sword', value: 5 },
  { label: 'Wyrmslayer', value: 6 },
  { label: 'Armorslayer', value: 7 },
  { label: 'Mercurius', value: 8 },
  { label: 'Rapier', value: 9 },
  { label: 'Wo Dao', value: 10 },
  { label: 'Brave Sword', value: 11 },
  { label: 'Falchion (Fake)', value: 12 },
  { label: 'Falchion (Weak)', value: 13 },
  { label: 'Falchion', value: 14 },
  { label: 'Iron Lance', value: 15 },
  { label: 'Steel Lance', value: 16 },
  { label: 'Silver Lance', value: 17 },
  { label: 'Javelin', value: 18 },
  { label: 'Killer Lance', value: 19 },
  { label: 'Ridersbane', value: 20 },
  { label: 'Wing Spear', value: 21 },
  { label: 'Dragonpike', value: 22 },
  { label: 'Brave Lance', value: 23 },
  { label: 'Gradivus', value: 24 },
  { label: 'Iron Axe', value: 25 },
  { label: 'Steel Axe', value: 26 },
  { label: 'Silver Axe', value: 27 },
  { label: 'Hand Axe', value: 28 },
  { label: 'Killer Axe', value: 29 },
  { label: 'Hammer', value: 30 },
  { label: 'Poleax', value: 31 },
  { label: 'Devil Axe', value: 32 },
  { label: 'Brave Axe', value: 33 },
  { label: 'Hauteclere', value: 34 },
  { label: 'Iron Bow', value: 35 },
  { label: 'Steel Bow', value: 36 },
  { label: 'Silver Bow', value: 37 },
  { label: 'Killer Bow', value: 38 },
  { label: 'Longbow', value: 39 },
  { label: 'Brave Bow', value: 40 },
  { label: 'Parthia', value: 41 },
  { label: 'Arrowspate', value: 42 },
  { label: 'Stonehoist', value: 43 },
  { label: 'Hoistflamme', value: 44 },
  { label: 'Thunderbolt', value: 45 },
  { label: 'Pachyderm', value: 46 },
  { label: 'Firestone', value: 47 },
  { label: 'Earthstone', value: 48 },
  { label: 'Magestone', value: 49 },
  { label: 'Divinestone', value: 50 },
  { label: 'Fire', value: 51 },
  { label: 'Thunder', value: 52 },
  { label: 'Blizzard', value: 53 },
  { label: 'Elfire', value: 54 },
  { label: 'Imhullu (False)', value: 55 },
  { label: 'Bolganone', value: 56 },
  { label: 'Thoron', value: 57 },
  { label: 'Swarm', value: 58 },
  { label: 'Aura', value: 59 },
  { label: 'Excalibur', value: 60 },
  { label: 'Imhullu', value: 61 },
  { label: 'Starlight', value: 62 },
  { label: 'Heal', value: 63 },
  { label: 'Mend', value: 64 },
  { label: 'Recover', value: 65 },
  { label: 'Physic', value: 66 },
  { label: 'Fortify', value: 67 },
  { label: 'Warp', value: 68 },
  { label: 'Barrier', value: 69 },
  { label: 'Hammerne', value: 70 },
  { label: 'Aum', value: 71 },
  { label: 'Door Key', value: 72 },
  { label: 'Bridge Key', value: 73 },
  { label: 'Master Key', value: 74 },
  { label: 'Vulnerary', value: 75 },
  { label: 'Pure Water', value: 76 },
  { label: 'Energy Drop', value: 77 },
  { label: 'Spirit Dust', value: 78 },
  { label: 'Secret Book', value: 79 },
  { label: 'Speedwings', value: 80 },
  { label: 'Goddess Icon', value: 81 },
  { label: 'Dracoshield', value: 82 },
  { label: 'Talisman', value: 83 },
  { label: 'Seraph Robe', value: 84 },
  { label: 'Boots', value: 85 },
  { label: 'Arms Scroll', value: 86 },
  { label: 'Silver Card', value: 87 },
  { label: 'VIP Card', value: 88 },
  { label: 'Master Seal', value: 89 },
  { label: 'Elysian Whip', value: 90 },
  { label: 'Torch', value: 91 },
  { label: 'Iote\'s Shield', value: 92 },
  { label: 'Lightsphere', value: 93 },
  { label: 'Starsphere', value: 94 },
  { label: 'Geosphere', value: 95 },
  { label: 'Fire Emblem', value: 96 },
  { label: 'Door Key', value: 97 },
  { label: 'Bullion (S)', value: 98 },
  { label: 'Bullion (M)', value: 99 },
  { label: 'Bullion (L)', value: 100 },
  { label: 'Bullion (XL)', value: 101 },
  { label: 'All blanks beyond this point.', value: 102 },
  { label: 'This list was painstakingly created by Arch.', value: 103 },
  { label: 'Entry 104', value: 104 },
  { label: 'Entry 105', value: 105 },
  { label: 'Entry 106', value: 106 },
  { label: 'Entry 107', value: 107 },
  { label: 'Entry 108', value: 108 },
  { label: 'Entry 109', value: 109 },
  { label: 'Entry 110', value: 110 },
  { label: 'Entry 111', value: 111 },
  { label: 'Entry 112', value: 112 },
  { label: 'Entry 113', value: 113 },
  { label: 'Entry 114', value: 114 },
  { label: 'Entry 115', value: 115 },
  { label: 'Entry 116', value: 116 },
  { label: 'Entry 117', value: 117 },
  { label: 'Entry 118', value: 118 },
  { label: 'Entry 119', value: 119 },
  { label: 'Entry 120', value: 120 },
  { label: 'Entry 121', value: 121 },
  { label: 'Entry 122', value: 122 },
  { label: 'Entry 123', value: 123 },
  { label: 'Entry 124', value: 124 },
  { label: 'Entry 125', value: 125 },
  { label: 'Entry 126', value: 126 },
  { label: 'Entry 127', value: 127 },
  { label: 'Entry 128', value: 128 },
  { label: 'Entry 129', value: 129 },
  { label: 'Entry 130', value: 130 },
  { label: 'Entry 131', value: 131 },
  { label: 'Entry 132', value: 132 },
  { label: 'Entry 133', value: 133 },
  { label: 'Entry 134', value: 134 },
  { label: 'Entry 135', value: 135 },
  { label: 'Entry 136', value: 136 },
  { label: 'Entry 137', value: 137 },
  { label: 'Entry 138', value: 138 },
  { label: 'Entry 139', value: 139 },
  { label: 'Entry 140', value: 140 },
  { label: 'Entry 141', value: 141 },
  { label: 'Entry 142', value: 142 },
  { label: 'Entry 143', value: 143 },
  { label: 'Entry 144', value: 144 },
  { label: 'Entry 145', value: 145 },
  { label: 'Entry 146', value: 146 },
  { label: 'Entry 147', value: 147 },
  { label: 'Entry 148', value: 148 },
  { label: 'Entry 149', value: 149 },
  { label: 'Entry 150', value: 150 },
  { label: 'Entry 151', value: 151 },
  { label: 'Entry 152', value: 152 },
];

export const ItemTypes = [
  { label: 'Sword', value: 0 },
  { label: 'Lance', value: 1 },
  { label: 'Axe', value: 2 },
  { label: 'Bow', value: 3 },
  { label: 'Magic', value: 4 },
  { label: 'Staff', value: 5 },
  { label: 'Dragonstone', value: 6 },
  { label: 'Ballista', value: 7 },
  { label: 'Item', value: 8 },
];

export const WeaponLevels = [
  { label: 'None', value: 0x00 },
  { label: 'E', value: 0x01 },
  { label: 'D', value: 0x1F },
  { label: 'C', value: 0x4C },
  { label: 'B', value: 0x88 },
  { label: 'A', value: 0xC4 },
];
