export const Chapters = [
  { label: 'Prologue: A Girl from the Plains', value: 0 },
  { label: 'Ch. 1: Footsteps of Fate', value: 1 },
  { label: 'Ch. 2: Sword of Spirits', value: 2 },
  { label: 'Ch. 3: Band of Mercenaries', value: 3 },
  { label: 'Ch. 4: In Occupation\'s Shadow', value: 4 },
  { label: 'Ch. 5: Beyond the Borders', value: 5 },
  { label: 'Ch. 6: Blood of Pride', value: 6 },
  { label: 'Ch. 7: Siblings Abroad', value: 7 },
  { label: 'Ch. 7x: The Black Shadow', value: 8 },
  { label: 'Ch. 8: Vortex of Strategy', value: 9 },
  { label: 'Ch. 9: A Grim Reunion', value: 10 },
  { label: 'Ch. 10: The Distant Plains', value: 11 },
  { label: 'Ch. 11: Taking Leave (E)', value: 12 },
  { label: 'Ch. 11: Another Journey (H)', value: 13 },
  { label: 'Ch. 12: Birds of a Feather', value: 14 },
  { label: 'Ch. 13: In Search of Truth', value: 15 },
  { label: 'Ch. 13x: The Peddler Merlinus', value: 16 },
  { label: 'Ch. 14: False Friends', value: 17 },
  { label: 'Ch. 15: Talons Alight (H)', value: 18 },
  { label: 'Ch. 15/16: Noble Lady of Caelin', value: 19 },
  { label: 'Ch. 16/17: Whereabouts Unknown', value: 20 },
  { label: 'Ch. 16x/17x: The Port of Badon', value: 21 },
  { label: 'Ch. 17/18: Pirate Ship', value: 22 },
  { label: 'Ch. 18/19: The Dread Isle', value: 23 },
  { label: 'Ch. 18x/19x: Imprisoner of Magic', value: 24 },
  { label: 'Ch. 19x pt2: A Glimpse in Time (H)', value: 25 },
  { label: 'Ch. 19/20: Dragon\'s Gate', value: 26 },
  { label: 'Ch. 20/21: New Resolve', value: 27 },
  { label: 'Ch. 21/22: Kinship\'s Bond', value: 28 },
  { label: 'Ch. 22/23: Living Legend', value: 29 },
  { label: 'Ch. 22x/23x: Genesis', value: 30 },
  { label: 'Ch. 23/24: Four-Fanged Offense (Lloyd)', value: 31 },
  { label: 'Ch. 23/24: Four-Fanged Offense (Linus)', value: 32 },
  { label: 'Ch. 25: Crazed Beast (H)', value: 33 },
  { label: 'Ch. 24/26: Unfulfilled Heart', value: 34 },
  { label: 'Ch. 25/27: Pale Flower of Darkness (Kenneth)', value: 35 },
  { label: 'Ch. 25/27: Pale Flower of Darkness (Jerme)', value: 36 },
  { label: 'Ch. 26/28: Battle before Dawn', value: 37 },
  { label: 'Ch. 26x/28x: Night of Farewells', value: 38 },
  { label: 'Ch. 27/29: Cog of Destiny', value: 39 },
  { label: 'Ch. 28: Valorous Roland (E)', value: 40 },
  { label: 'Ch. 30: The Berserker (H)', value: 41 },
  { label: 'Ch. 29/31: Sands of Time', value: 42 },
  { label: 'Ch. 29x/31x: Battle Preparations', value: 43 },
  { label: 'Ch. 30/32: Victory or Death', value: 44 },
  { label: 'Ch. 32x: The Value of Life (H)', value: 45 },
  { label: 'Final Chapter: Light (pt1)', value: 46 },
  { label: 'Final Chapter: Light (pt2)', value: 47 },
  { label: 'Outside Araphen', value: 48 },
  { label: 'Outside fort', value: 49 },
  { label: 'Ostia', value: 50 },
  { label: 'Castle', value: 51 },
  { label: 'Laus', value: 52 },
  { label: 'Nergal and kids flashback', value: 53 },
  { label: 'Meeting with Uther', value: 54 },
  { label: 'Athos\' place (Sacred Shrine)', value: 55 },
  { label: 'Messed up building', value: 56 },
  { label: 'Town with Nino (talk w/Lloyd + Linus)', value: 57 },
  { label: 'Path to the HQ (Lyn uses tracking)', value: 58 },
  { label: 'Black Fang HQ', value: 59 },
  { label: 'Forests and stuff', value: 60 },
  { label: 'Nighttime village (Jaffar + Nino leave for Sonia)', value: 61 },
  { label: 'Cave with Ninian (Ch. 19xx Teodor n stuff)', value: 62 },
  { label: 'Ostia with Athos (Telling about history)', value: 63 },
  { label: 'Closed dragons gate', value: 64 },
  { label: 'Link Arena (Hm?)', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
];

export const ChapterRef = [
  { label: 'T01)00', value: 0x083B8CA4 },
  { label: 'T02)01', value: 0x083B8C9C },
  { label: 'T03)02', value: 0x083B8C94 },
  { label: 'T04)03', value: 0x083B8C8C },
  { label: 'T05)04', value: 0x083B8C84 },
  { label: 'T06)05', value: 0x083B8C7C },
  { label: 'T07)06', value: 0x083B8C74 },
  { label: 'T08)07', value: 0x083B8C6C },
  { label: 'T08x)07x', value: 0x083B8C60 },
  { label: 'T09)08', value: 0x083B8C58 },
  { label: 'T10)09', value: 0x083B8C50 },
  { label: 'T11)10', value: 0x083B8C48 },
  { label: '01)11', value: 0x083B8C40 },
  { label: '01)11h', value: 0x083B8C38 },
  { label: '02)12', value: 0x083B8C30 },
  { label: '03)13', value: 0x083B8C28 },
  { label: '03)13x', value: 0x083B8C20 },
  { label: '04)14', value: 0x083B8C18 },
  { label: '04)14h', value: 0x083B8C10 },
  { label: '05)15', value: 0x083B8C08 },
  { label: '06)16', value: 0x083B8C00 },
  { label: '06)16x', value: 0x083B8BF8 },
  { label: '07)17', value: 0x083B8BF0 },
  { label: '08)18', value: 0x083B8BE8 },
  { label: '08)18x', value: 0x083B8BE0 },
  { label: '08)18hx', value: 0x083B8BD8 },
  { label: '09)19', value: 0x083B8BD0 },
  { label: '10)20', value: 0x083B8BC8 },
  { label: '11)21', value: 0x083B8BC0 },
  { label: '12)22', value: 0x083B8BB8 },
  { label: '12)22xa', value: 0x083B8BB0 },
  { label: '13)23', value: 0x083B8BA8 },
  { label: '13)23b', value: 0x083B8BA0 },
  { label: '13)23h', value: 0x083B8B98 },
  { label: '14)24', value: 0x083B8B90 },
  { label: '15)25', value: 0x083B8B88 },
  { label: '15)25b', value: 0x083B8B80 },
  { label: '16)26', value: 0x083B8B78 },
  { label: '16)26x', value: 0x083B8B70 },
  { label: '17)27', value: 0x083B8B68 },
  { label: '18)28', value: 0x083B8B60 },
  { label: '18)28h', value: 0x083B8B58 },
  { label: '19)29', value: 0x083B8B50 },
  { label: '19)29x', value: 0x083B8B48 },
  { label: '20)30', value: 0x083B8B40 },
  { label: '20)30hx', value: 0x083B8B38 },
  { label: '21)31', value: 0x083B8B30 },
  { label: '22)32', value: 0x083B8B28 },
];

export const ObjectSets = [
  { label: 'None', value: 0x00 },
  { label: 'Sacae Plains', value: 0x01 },
  { label: 'Plains&Castle', value: 0x0A },
  { label: 'Town&Docks', value: 0x10 },
  { label: 'Fortress&Fields', value: 0x16 },
  { label: 'Fields 2', value: 0x1D },
  { label: 'Fields 1', value: 0x1C },
  { label: 'Ship', value: 0x5B },
  { label: 'Mountains&Shrine', value: 0x6A },
  { label: 'Desert', value: 0x7B },
  { label: 'Snow', value: 0x91 },
  { label: 'Lava Cave', value: 0xA7 },
  { label: 'Sand Cave', value: 0xAE },
  { label: 'Dragon\'s Gate', value: 0xC1 },
];

export const Palette1 = [
  { label: 'Sacae Plains: Light Sand', value: 0x02 },
  { label: 'Sacae Plains: Dark Sand', value: 0x07 },
  { label: 'Plains&Castle: Bright', value: 0x0B },
  { label: 'Plains&Castle: Castle Ostia/Laus', value: 0x3A },
  { label: 'Plains&Castle: Night', value: 0x9B },
  { label: 'Plains&Castle: Purple', value: 0x9F },
  { label: 'Plains&Castle: Neutral', value: 0x29 },
  { label: 'Plains&Castle: Castle Caelin', value: 0x52 },
  { label: 'Plains&Castle: Green&blue', value: 0x80 },
  { label: 'Fields: Sunny weather', value: 0x1E },
  { label: 'Fields: Darker; suitable for rain', value: 0x33 },
  { label: 'Fields: Night', value: 0x44 },
  { label: 'Fields: Darker; suitable for rain', value: 0x48 },
  { label: 'Fields: Dull; suitable for fog', value: 0x62 },
  { label: 'Fields: Sunny weather', value: 0x66 },
  { label: 'Fields: Neutral', value: 0x8A },
  { label: 'Town: Cliffs&stone road unusable', value: 0x11 },
  { label: 'Town: Cliffs&ship unusable', value: 0x22 },
  { label: 'Town: Ship&stone road unusable', value: 0x56 },
  { label: 'Town: Night', value: 0x73 },
  { label: 'Town: Ship&stone road unusable', value: 0xB7 },
  { label: 'Fortress&Fields: Dawn', value: 0x17 },
  { label: 'Fortress&Fields: Daytime', value: 0x77 },
  { label: 'Ship', value: 0x5C },
  { label: 'Mountains&Shrine: Neutral', value: 0x6B },
  { label: 'Mountains&Shrine: No plains', value: 0xBD },
  { label: 'Desert', value: 0x7C },
  { label: 'Snow', value: 0x92 },
  { label: 'Lava Cave', value: 0xA8 },
  { label: 'Sand Cave', value: 0xAF },
  { label: 'Dragon\'s Gate', value: 0xC2 },
];

export const SetConfig = [
  { label: 'Sacae Plains', value: 0x03 },
  { label: 'Plains&Castle', value: 0x0C },
  { label: 'Town&Docks', value: 0x12 },
  { label: 'Fortress&Fields', value: 0x18 },
  { label: 'Ship', value: 0x5D },
  { label: 'Mountains&Shrine', value: 0x6C },
  { label: 'Desert', value: 0x7D },
  { label: 'Snow', value: 0x93 },
  { label: 'Lava Cave', value: 0xA9 },
  { label: 'Sand Cave', value: 0xB0 },
  { label: 'Dragon\'s Gate', value: 0xC3 },
  { label: 'Fields', value: 0x1F },
];

export const Maps = [
  { label: 'Prologue Map', value: 0x04 },
  { label: 'Ch.1 Map', value: 0x08 },
  { label: 'Ch.2 Map', value: 0x0D },
  { label: 'Ch.3 Map', value: 0x13 },
  { label: 'Ch.4 Map', value: 0x19 },
  { label: 'Ch.5 Map', value: 0x20 },
  { label: 'Ch.6 Map', value: 0x23 },
  { label: 'Ch.7 Map', value: 0x26 },
  { label: 'Ch.7x Map', value: 0x2A },
  { label: 'Ch.8 Map', value: 0x2D },
  { label: 'Ch.9 Map', value: 0x30 },
  { label: 'Ch.10 Map', value: 0x34 },
  { label: 'Ch.11E Map', value: 0x37 },
  { label: 'Ch.11H Map', value: 0x3B },
  { label: 'Ch.12 Map', value: 0x3E },
  { label: 'Ch.13 Map', value: 0x41 },
  { label: 'Ch.13x Map', value: 0x45 },
  { label: 'Ch.14 Map', value: 0x49 },
  { label: 'Ch.15H Map', value: 0x4C },
  { label: 'Ch.15/16 Map', value: 0x4F },
  { label: 'Ch.16/17 Map', value: 0x53 },
  { label: 'Ch.16x/17x Map', value: 0x57 },
  { label: 'Ch.17/18 Map', value: 0x5E },
  { label: 'Ch.18/19 Map', value: 0x63 },
  { label: 'Ch.18x/19x Map', value: 0x67 },
  { label: 'Ch.19x pt2 Map', value: 0x6D },
  { label: 'Ch.19/20 Map', value: 0x70 },
  { label: 'Ch.20/21 Map', value: 0x74 },
  { label: 'Ch.21/22 Map', value: 0x78 },
  { label: 'Ch.22/23 Map', value: 0x7E },
  { label: 'Ch.22x/23x Map', value: 0x81 },
  { label: 'Ch.23/24 Map (Lloyd)', value: 0x84 },
  { label: 'Ch.23/24 Map (Linus)', value: 0x87 },
  { label: 'Ch.25H Map', value: 0x8B },
  { label: 'Ch.24/26 Map', value: 0x8E },
  { label: 'Ch.25/27 Map (Kenneth)', value: 0x94 },
  { label: 'Ch.25/27 Map (Jerme)', value: 0x97 },
  { label: 'Ch.26/28 Map', value: 0x9C },
  { label: 'Ch.26x/28x Map', value: 0xA0 },
  { label: 'Ch.27/29 Map', value: 0xA4 },
  { label: 'Ch.28E Map', value: 0xAA },
  { label: 'Ch.30H Map', value: 0xB1 },
  { label: 'Ch.29/31 Map', value: 0xB4 },
  { label: 'Ch.29x/31x Map', value: 0xB8 },
  { label: 'Ch.30/32 Map', value: 0xBA },
  { label: 'Ch.32x Map', value: 0xBE },
  { label: 'Final Ch. pt1 Map', value: 0xC4 },
  { label: 'Final Ch. pt2 Map', value: 0xC8 },
];

export const TileAnim = [
  { label: 'None', value: 0x0000 },
  { label: 'Water (Fields; Plains; M&S)', value: 0x0005 },
  { label: 'Water (Town&Docks)', value: 0x0058 },
  { label: 'Water (Ship)', value: 0x005F },
  { label: 'Shimmering ice (Snow)', value: 0x9800 },
  { label: 'Water (Plains&Castle)', value: 0x00A1 },
  { label: 'Lava (Lava Cave)', value: 0xAB00 },
  { label: 'Gate and flames (Dragon\'s Gate)', value: 0x00C5 },
];

export const TileChange = [
  { label: 'None', value: 0x00 },
  { label: 'Ch.2 Map', value: 0x0E },
  { label: 'Ch.3 Map', value: 0x14 },
  { label: 'Ch.4 Map', value: 0x1A },
  { label: 'Ch.6 Map', value: 0x24 },
  { label: 'Ch.7 Map', value: 0x27 },
  { label: 'Ch.7x Map', value: 0x2B },
  { label: 'Ch.8 Map', value: 0x2E },
  { label: 'Ch.9 Map', value: 0x31 },
  { label: 'Ch.10 Map', value: 0x35 },
  { label: 'Ch.11E Map', value: 0x38 },
  { label: 'Ch.11H Map', value: 0x3C },
  { label: 'Ch.12 Map', value: 0x3F },
  { label: 'Ch.13 Map', value: 0x42 },
  { label: 'Ch.13x Map', value: 0x46 },
  { label: 'Ch.14 Map', value: 0x4A },
  { label: 'Ch.15H Map', value: 0x4D },
  { label: 'Ch.15/16 Map', value: 0x50 },
  { label: 'Ch.16/17 Map', value: 0x54 },
  { label: 'Ch.16x/17x Map', value: 0x59 },
  { label: 'Ch.17/18 Map', value: 0x60 },
  { label: 'Ch.18/19 Map', value: 0x64 },
  { label: 'Ch.18x/19x Map', value: 0x68 },
  { label: 'Ch.19x pt2 Map', value: 0x6E },
  { label: 'Ch.19/20 Map', value: 0x71 },
  { label: 'Ch.20/21 Map', value: 0x75 },
  { label: 'Ch.21/22 Map', value: 0x79 },
  { label: 'Ch.22x/23x Map', value: 0x82 },
  { label: 'Ch.23/24 Map (Lloyd)', value: 0x85 },
  { label: 'Ch.23/24 Map (Linus)', value: 0x88 },
  { label: 'Ch.25H Map', value: 0x8C },
  { label: 'Ch.24/26 Map', value: 0x8F },
  { label: 'Ch.25/27 Map (Kenneth)', value: 0x95 },
  { label: 'Ch.25/27 Map (Jerme)', value: 0x99 },
  { label: 'Ch.26/28 Map', value: 0x9D },
  { label: 'Ch.26x/28x Map', value: 0xA2 },
  { label: 'Ch.27/29 Map', value: 0xA5 },
  { label: 'Ch.28E Map', value: 0xAC },
  { label: 'Ch.30H Map', value: 0xB2 },
  { label: 'Ch.29/31 Map', value: 0xB5 },
  { label: 'Ch.30/32 Map', value: 0xBB },
  { label: 'Ch.32x Map', value: 0xBF },
  { label: 'Final Ch. pt1 Map', value: 0xC6 },
  { label: 'Final Ch. pt2 Map', value: 0xC9 },
];

export const Preps = [
  { label: 'Disabled', value: 0x00 },
  { label: 'Enabled (if programmed)', value: 0x01 },
];

export const Weather = [
  { label: 'Normal', value: 0x00 },
  { label: 'Snow', value: 0x01 },
  { label: 'Snowstorm', value: 0x02 },
  { label: 'Blue Background', value: 0x03 },
  { label: 'Rain', value: 0x04 },
  { label: 'Fiery Glow', value: 0x05 },
  { label: 'Sandstorm', value: 0x06 },
  { label: 'Moving Clouds Background', value: 0x07 },
];

export const Battletileset = [
  { label: 'Normal??', value: 0x00 },
  { label: 'Snow', value: 0x01 },
  { label: 'Lava cave', value: 0x02 },
  { label: 'Sandy cave', value: 0x03 },
  { label: 'Plains', value: 0x04 },
  { label: 'Dusk', value: 0x05 },
  { label: 'Normal??', value: 0x06 },
  { label: 'Night', value: 0x07 },
  { label: 'Ship', value: 0x08 },
  { label: 'Desert', value: 0x09 },
  { label: 'Normal??', value: 0x0A },
  { label: 'Normal??', value: 0x0B },
  { label: 'Normal??', value: 0x0C },
  { label: 'Dread Isle', value: 0x0D },
  { label: 'Night', value: 0x0E },
];

export const Music = [
  { label: 'Not applicable', value: 0xFFFF },
  { label: 'Nothing', value: 0x0000 },
  { label: 'Precious Things', value: 0x0001 },
  { label: 'Companions', value: 0x0002 },
  { label: 'Friendship and Adventure', value: 0x0003 },
  { label: 'Dragon\'s Gate II', value: 0x0004 },
  { label: 'Scars of the Scouring', value: 0x0005 },
  { label: 'Raise Your Spirits', value: 0x0006 },
  { label: 'Shadow Approaches', value: 0x0007 },
  { label: 'Binding Ties', value: 0x0008 },
  { label: 'Winning Road', value: 0x0009 },
  { label: 'Distant Travels', value: 0x000A },
  { label: 'Inescapable Fate', value: 0x000B },
  { label: 'Enemies Appear', value: 0x000C },
  { label: 'The Messenger', value: 0x000D },
  { label: 'Darkness Comes', value: 0x000E },
  { label: 'Nabata\'s Wandering Messenger', value: 0x000F },
  { label: 'Dragon\'s Gate I', value: 0x0010 },
  { label: 'Legendary Inheritance', value: 0x0011 },
  { label: 'Raid!', value: 0x0012 },
  { label: 'Messenger from the Darkness', value: 0x0013 },
  { label: 'Victory Now!', value: 0x0014 },
  { label: 'Rise to the Challenge', value: 0x0015 },
  { label: 'Softly with Grace', value: 0x0016 },
  { label: 'Everything into the Dark', value: 0x0017 },
  { label: 'Campaign of Fire', value: 0x0018 },
  { label: 'Healing', value: 0x0019 },
  { label: 'Curing', value: 0x001A },
  { label: 'To the Heights', value: 0x001B },
  { label: 'Blessing of the 8 Generals I', value: 0x001C },
  { label: 'Receive the Blessings of Water', value: 0x001D },
  { label: 'Ride the Wind', value: 0x001E },
  { label: 'Strike', value: 0x001F },
  { label: 'Safeguard', value: 0x0020 },
  { label: 'Requiem', value: 0x0021 },
  { label: 'Land of Swirling Sands', value: 0x0022 },
  { label: 'The Kingdom of Bern', value: 0x0023 },
  { label: 'Bern - A Mother\'s Wish', value: 0x0024 },
  { label: 'A Hint of Things to Come', value: 0x0025 },
  { label: 'Road of Trials', value: 0x0026 },
  { label: 'Destiny Enlaced by Fear', value: 0x0027 },
  { label: 'Nothing', value: 0x0028 },
  { label: 'Results', value: 0x0029 },
  { label: 'Treasured Hope', value: 0x002A },
  { label: 'Game Over', value: 0x002B },
  { label: 'Within Sadness', value: 0x002C },
  { label: 'Arena Victory', value: 0x002D },
  { label: 'Arena Tactics', value: 0x002E },
  { label: 'Nothing', value: 0x002F },
  { label: 'Winds Across the Plains', value: 0x0030 },
  { label: 'Nothing', value: 0x0031 },
  { label: 'An Unexpected Caller', value: 0x0032 },
  { label: 'When the Rush Comes', value: 0x0033 },
  { label: 'The Cogs of Fate', value: 0x0034 },
  { label: 'Shocking Truth I', value: 0x0035 },
  { label: 'Shocking Truth II', value: 0x0036 },
  { label: 'The Eight Generals', value: 0x0037 },
  { label: 'Triumph', value: 0x0038 },
  { label: 'In the Shadow of Triumph', value: 0x0039 },
  { label: 'Reminiscence', value: 0x003A },
  { label: 'Nergal\'s Wrath', value: 0x003B },
  { label: 'The Archsage Athos', value: 0x003C },
  { label: 'One Heart: Eliwood\'s Theme', value: 0x003D },
  { label: 'Loyalty: Hector\'s Theme', value: 0x003E },
  { label: 'Girl of the Plains: Lyn\'s Theme', value: 0x003F },
  { label: 'Final Farewell', value: 0x0040 },
  { label: 'Going My Way', value: 0x0041 },
  { label: 'Together, We Ride!', value: 0x0042 },
  { label: 'A Knight\'s Oath', value: 0x0043 },
  { label: 'Happiness Abounds', value: 0x0044 },
  { label: 'Main Theme Arrangement', value: 0x0045 },
  { label: 'Shop', value: 0x0046 },
  { label: 'Arena Entrance', value: 0x0047 },
  { label: 'Arena Battle', value: 0x0048 },
  { label: 'Prepare to Charge', value: 0x0049 },
  { label: 'Calamity Bringer: Nergal\'s Theme', value: 0x004A },
  { label: 'Light to Tomorrow', value: 0x004B },
  { label: 'Merchant Merlinus', value: 0x004C },
  { label: 'Armory', value: 0x004D },
  { label: 'Ships and Homes', value: 0x004E },
  { label: 'Silent Ground', value: 0x004F },
  { label: 'Black Fang', value: 0x0050 },
  { label: 'Recollection of a Petal', value: 0x0051 },
  { label: 'What Comes from Darkness', value: 0x0052 },
  { label: 'Stratagem', value: 0x0053 },
  { label: 'Lyn\'s Desire', value: 0x0054 },
  { label: 'Nothing', value: 0x0055 },
  { label: 'Eyes of Sorrow', value: 0x0056 },
  { label: 'Unshakable Faith', value: 0x0057 },
  { label: 'The Grieving Heart', value: 0x0058 },
  { label: 'Nothing', value: 0x0059 },
  { label: 'Fire Emblem Theme', value: 0x005A },
  { label: 'Fire Emblem Theme (looped)', value: 0x005B },
  { label: 'Opening: History Unveiled', value: 0x005C },
  { label: 'Distant Utopia', value: 0x005D },
  { label: 'Fortune Telling', value: 0x005E },
  { label: 'Fire Emblem Theme (with intro)', value: 0x005F },
  { label: 'Chapter Display humming', value: 0x0060 },
  { label: 'Chapter Display', value: 0x0061 },
  { label: 'Water Droplet in the Opening', value: 0x0062 },
  { label: 'Sword Sound in the Opening', value: 0x0063 },
  { label: 'What Comes from Darkness', value: 0x0064 },
  { label: 'Black Fang', value: 0x0065 },
  { label: 'Going My Way', value: 0x0066 },
  { label: 'Safeguard', value: 0x0067 },
  { label: 'Shattered Life', value: 0x0068 },
  { label: 'Anguish', value: 0x0069 },
  { label: 'Respite in Battle', value: 0x006A },
  { label: 'The Inn', value: 0x006B },
  { label: 'Nothing', value: 0x006C },
  { label: 'Nothing', value: 0x006D },
  { label: 'Blessing of the 8 Generals II', value: 0x006E },
  { label: 'Campaign of Fire (no intro)', value: 0x006F },
  { label: 'Beneath a New Light', value: 0x0070 },
  { label: 'The Path to Greatness', value: 0x0071 },
  { label: 'In the Name of Bern', value: 0x0072 },
  { label: 'Legend of Athos', value: 0x0073 },
  { label: 'Avoided Fate', value: 0x0074 },
  { label: 'Legend of the God Dragon', value: 0x0075 },
  { label: 'Royal Palace of Silezha', value: 0x0076 },
  { label: '???', value: 0x0077 },
  { label: '??? (sounds like FE6\'s theme, but still unused there, too...)', value: 0x0078 },
  { label: 'Ominius', value: 0x0079 },
  { label: 'Nothing', value: 0x007A },
  { label: 'Nothing', value: 0x007B },
  { label: 'Nothing', value: 0x007C },
  { label: 'Nothing', value: 0x007D },
  { label: 'Nothing', value: 0x007E },
  { label: 'Nothing', value: 0x007F },
  { label: 'Droplet? sounds familiar', value: 0x0080 },
  { label: 'Crowd cheering', value: 0x0081 },
  { label: 'Rest staff (map)', value: 0x0082 },
  { label: 'Silence staff (map)', value: 0x0083 },
  { label: 'Nothing', value: 0x0084 },
  { label: 'Sleep staff (map)', value: 0x0085 },
  { label: 'Hammerne staff (map)', value: 0x0086 },
  { label: 'Berserk staff (map)', value: 0x0087 },
  { label: 'Weird sound (Watch staff?)', value: 0x0088 },
  { label: 'Live staff', value: 0x0089 },
  { label: 'Relive staff', value: 0x008A },
  { label: 'Recover staff', value: 0x008B },
  { label: 'Reserve staff', value: 0x008C },
  { label: 'Recovery from a status effect (longer)', value: 0x008D },
  { label: 'Crowd cheering (softer)', value: 0x008E },
  { label: 'Crowd cheering, then stops', value: 0x008F },
  { label: 'FE6 Chapter opening humming', value: 0x0090 },
  { label: 'FE6 Chapter opening', value: 0x0091 },
  { label: 'Nothing', value: 0x0092 },
  { label: 'Footsteps', value: 0x0093 },
  { label: 'Footsteps 2', value: 0x0094 },
  { label: 'Footsteps 3', value: 0x0095 },
  { label: 'Footsteps 4', value: 0x0096 },
  { label: 'Footsteps 5', value: 0x0097 },
  { label: 'Footsteps 6', value: 0x0098 },
  { label: 'Footsteps 7', value: 0x0099 },
  { label: 'Footsteps 8', value: 0x009A },
  { label: 'Horse trot', value: 0x009B },
  { label: 'Horse trot 2', value: 0x009C },
  { label: 'Horse trot 3', value: 0x009D },
  { label: 'Horse trot 4', value: 0x009E },
  { label: 'Horse trot 5', value: 0x009F },
  { label: 'Armour walk', value: 0x00A0 },
  { label: 'Armour walk 2', value: 0x00A1 },
  { label: 'Armour walk 3', value: 0x00A2 },
  { label: 'Armour walk 4', value: 0x00A3 },
  { label: 'Armour walk 5', value: 0x00A4 },
  { label: 'Armour walk 6', value: 0x00A5 },
  { label: 'Pegasus flying', value: 0x00A6 },
  { label: 'Pegasus flying 2', value: 0x00A7 },
  { label: 'Nothing', value: 0x00A8 },
  { label: 'Nothing', value: 0x00A9 },
  { label: 'Recovery from a status effect', value: 0x00AA },
  { label: 'Rock exploding?', value: 0x00AB },
  { label: 'Captive falling from dead holder', value: 0x00AC },
  { label: 'Nothing', value: 0x00AD },
  { label: 'Nothing', value: 0x00AE },
  { label: 'Destroyed wall/snag', value: 0x00AF },
  { label: 'Attacking wall/snag', value: 0x00B0 },
  { label: 'Unlocking door', value: 0x00B1 },
  { label: 'Nothing', value: 0x00B2 },
  { label: 'Torch', value: 0x00B3 },
  { label: 'Warping', value: 0x00B4 },
  { label: 'Warp end', value: 0x00B5 },
  { label: 'Pure Water', value: 0x00B6 },
  { label: 'Poison sound', value: 0x00B7 },
  { label: '???', value: 0x00B8 },
  { label: 'Gold changing', value: 0x00B9 },
  { label: 'Poison vent', value: 0x00BA },
  { label: 'Nothing', value: 0x00BB },
  { label: 'Nothing', value: 0x00BC },
  { label: 'Water tile going under', value: 0x00BD },
  { label: 'Water tile coming up', value: 0x00BE },
  { label: 'Fire tile', value: 0x00BF },
  { label: 'Nothing/Over9000', value: 0x00C0 },
  { label: 'Nothing/Wrrryyyy', value: 0x00C1 },
  { label: 'Nothing', value: 0x00C2 },
  { label: 'Nothing', value: 0x00C3 },
  { label: 'Nothing', value: 0x00C4 },
  { label: 'Nothing', value: 0x00C5 },
  { label: 'Nothing', value: 0x00C6 },
  { label: 'GBA version of Zelda:OoT future Hyrule Castle winds', value: 0x00C7 },
  { label: 'Small plunk?', value: 0x00C8 },
  { label: 'Light plunk?', value: 0x00C9 },
  { label: 'Large plunk?', value: 0x00CA },
  { label: 'Eliwood critical sword swing', value: 0x00CB },
  { label: 'Tap?', value: 0x00CC },
  { label: 'Low plunk?', value: 0x00CD },
  { label: 'Sword unsheathing', value: 0x00CE },
  { label: 'Sword unsheathing 2', value: 0x00CF },
  { label: 'Ballista fire', value: 0x00D0 },
  { label: 'Creaking', value: 0x00D1 },
  { label: 'Hit (map)', value: 0x00D2 },
  { label: 'Hit 2 (map)', value: 0x00D3 },
  { label: 'Hit 3 (map)', value: 0x00D4 },
  { label: 'Kill (map)', value: 0x00D5 },
  { label: 'Death (map)', value: 0x00D6 },
  { label: 'Miss (realtime)', value: 0x00D7 },
  { label: 'Crumbling?', value: 0x00D8 },
  { label: 'Nothing', value: 0x00D9 },
  { label: 'Nothing', value: 0x00DA },
  { label: 'Nothing', value: 0x00DB },
  { label: 'Mamkute transform', value: 0x00DC },
  { label: 'Mamkute de-transform', value: 0x00DD },
  { label: 'Mamkute yowl', value: 0x00DE },
  { label: 'Mamkute roar', value: 0x00DF },
  { label: 'Nothing', value: 0x00E0 },
  { label: 'Nothing', value: 0x00E1 },
  { label: 'Armour triangle, allies striking', value: 0x00E2 },
  { label: 'Idoun/Fire Dragon death roar', value: 0x00E3 },
  { label: 'Nothing', value: 0x00E4 },
  { label: 'Idoun/Fire Dragon death roar', value: 0x00E5 },
  { label: 'Mamkute transform growl', value: 0x00E6 },
  { label: 'Brigand battle cry', value: 0x00E7 },
  { label: 'Nothing', value: 0x00E8 },
  { label: 'Nothing', value: 0x00E9 },
  { label: 'Axe falling', value: 0x00EA },
  { label: 'Axe rising', value: 0x00EB },
  { label: 'Nothing', value: 0x00EC },
  { label: 'Nothing', value: 0x00ED },
  { label: 'Nothing', value: 0x00EE },
  { label: 'Dance/Play effect', value: 0x00EF },
  { label: 'Divine weapon shine', value: 0x00F0 },
  { label: 'Fire charge', value: 0x00F1 },
  { label: 'Fire shoot', value: 0x00F2 },
  { label: 'Nothing', value: 0x00F3 },
  { label: 'Thunderstorm static', value: 0x00F4 },
  { label: 'Thunderstorm strike', value: 0x00F5 },
  { label: 'Shaman charging', value: 0x00F6 },
  { label: 'Weird rumbling', value: 0x00F7 },
  { label: 'Weird rumbling 2', value: 0x00F8 },
  { label: 'Berserk staff (realtime)', value: 0x00F9 },
  { label: 'Silence staff charging (realtime)', value: 0x00FA },
  { label: 'Silence staff forming (realtime)', value: 0x00FB },
  { label: 'Nothing', value: 0x00FC },
  { label: 'Rest staff (realtime)', value: 0x00FD },
  { label: 'Purge flash', value: 0x00FE },
  { label: 'Purge flash 2', value: 0x00FF },
  { label: 'Purge charging', value: 0x0100 },
  { label: 'Purge strike', value: 0x0101 },
  { label: 'Aureola light explosion (short)', value: 0x0102 },
  { label: 'Hammerne staff (realtime)', value: 0x0103 },
  { label: 'Nothing', value: 0x0104 },
  { label: 'Nothing', value: 0x0105 },
  { label: 'Nothing', value: 0x0106 },
  { label: 'Nothing', value: 0x0107 },
  { label: 'Nothing', value: 0x0108 },
  { label: 'Nothing', value: 0x0109 },
  { label: 'Flux charging', value: 0x010A },
  { label: 'Nothing', value: 0x010B },
  { label: 'Nothing', value: 0x010C },
  { label: 'Nothing', value: 0x010D },
  { label: 'Live staff', value: 0x010E },
  { label: 'Live staff', value: 0x010F },
  { label: 'Relive staff', value: 0x0110 },
  { label: 'Relive staff', value: 0x0111 },
  { label: 'Recover staff', value: 0x0112 },
  { label: 'Recover staff', value: 0x0113 },
  { label: 'Reserve staff (realtime)', value: 0x0114 },
  { label: 'Nothing', value: 0x0115 },
  { label: 'Nothing', value: 0x0116 },
  { label: 'Nothing', value: 0x0117 },
  { label: 'Nothing', value: 0x0118 },
  { label: 'Thunderstorm sparks', value: 0x0119 },
  { label: 'Thunderstorm strike', value: 0x011A },
  { label: 'Sleep charging (realtime)', value: 0x011B },
  { label: 'Sleep activating (realtime)', value: 0x011C },
  { label: 'Rumbling?', value: 0x011D },
  { label: 'Some kind of wind', value: 0x011E },
  { label: 'Weird charging sound', value: 0x011F },
  { label: 'Lightning charging', value: 0x0120 },
  { label: 'Lightning strike', value: 0x0121 },
  { label: 'Fimbulvetr wind', value: 0x0122 },
  { label: 'Fimbulvetr ice', value: 0x0123 },
  { label: 'Nosferatu symbol', value: 0x0124 },
  { label: 'Nosferatu drain', value: 0x0125 },
  { label: 'Nosferatu heal', value: 0x0126 },
  { label: 'Divine charging', value: 0x0127 },
  { label: 'Divine falling', value: 0x0128 },
  { label: 'Divine strike', value: 0x0129 },
  { label: 'Divine strike 2', value: 0x012A },
  { label: 'Aureola light bomb falling', value: 0x012B },
  { label: 'Aureola light explosion', value: 0x012C },
  { label: 'Nothing', value: 0x012D },
  { label: 'Nothing', value: 0x012E },
  { label: 'Nothing', value: 0x012F },
  { label: 'Nothing', value: 0x0130 },
  { label: 'Nothing', value: 0x0131 },
  { label: 'Nothing', value: 0x0132 },
  { label: 'Nothing', value: 0x0133 },
  { label: 'Nothing', value: 0x0134 },
  { label: 'Nothing', value: 0x0135 },
  { label: 'Nothing', value: 0x0136 },
  { label: 'Nothing', value: 0x0137 },
  { label: 'Nothing', value: 0x0138 },
  { label: 'Nothing', value: 0x0139 },
  { label: 'Nothing', value: 0x013A },
  { label: 'Nothing', value: 0x013B },
  { label: 'Nothing', value: 0x013C },
  { label: 'Nothing', value: 0x013D },
  { label: 'Nothing', value: 0x013E },
  { label: 'Nothing', value: 0x013F },
  { label: 'Nothing', value: 0x0140 },
  { label: 'Nothing', value: 0x0141 },
  { label: 'Nothing', value: 0x0142 },
  { label: 'Nothing', value: 0x0143 },
  { label: 'Nothing', value: 0x0144 },
  { label: 'Nothing', value: 0x0145 },
  { label: 'Nothing', value: 0x0146 },
  { label: 'Nothing', value: 0x0147 },
  { label: 'Nothing', value: 0x0148 },
  { label: 'Nothing', value: 0x0149 },
  { label: 'Nothing', value: 0x014A },
  { label: 'Nothing', value: 0x014B },
  { label: 'Nothing', value: 0x014C },
  { label: 'Nothing', value: 0x014D },
  { label: 'Soft step', value: 0x014E },
  { label: 'Soft step 2', value: 0x014F },
  { label: 'Soft step 3', value: 0x0150 },
  { label: 'Soft step 4', value: 0x0151 },
  { label: 'Nothing', value: 0x0152 },
  { label: 'Nothing', value: 0x0153 },
  { label: 'Soft step', value: 0x0154 },
  { label: 'Soft step 2', value: 0x0155 },
  { label: 'Soft step 3', value: 0x0156 },
  { label: 'Soft step 4', value: 0x0157 },
  { label: 'Soft step 5', value: 0x0158 },
  { label: 'The rest of high 01 just seems to be soft steps...', value: 0x0159 },
  { label: 'Nothing', value: 0x02A0 },
  { label: 'Nothing', value: 0x02A8 },
  { label: 'Nothing', value: 0x02B0 },
  { label: 'Nothing', value: 0x02B1 },
  { label: 'Nothing', value: 0x02B2 },
  { label: 'Nothing', value: 0x02B5 },
  { label: 'Nothing', value: 0x02B6 },
  { label: 'Nothing', value: 0x02B9 },
  { label: 'Nothing', value: 0x02BB },
  { label: 'Shine attack', value: 0x02BC },
  { label: 'Luna symbol', value: 0x02BD },
  { label: 'Luna hitting', value: 0x02BE },
  { label: 'Excalibur forming', value: 0x02BF },
  { label: 'Excalibur cutting', value: 0x02C0 },
  { label: 'Aura flash', value: 0x02C1 },
  { label: 'Aura going up', value: 0x02C2 },
  { label: 'Aura strike', value: 0x02C3 },
  { label: 'Luce flash', value: 0x02C4 },
  { label: 'Luce charging', value: 0x02C5 },
  { label: 'Luce flowing', value: 0x02C6 },
  { label: 'Gespenst symbol', value: 0x02C7 },
  { label: 'Gespenst clouds', value: 0x02C8 },
  { label: 'Gespenst strike', value: 0x02C9 },
  { label: 'Forblaze charging', value: 0x02CA },
  { label: 'Forblaze rising', value: 0x02CB },
  { label: 'Weird charging', value: 0x02CC },
  { label: 'Weird glittery sound', value: 0x02CD },
  { label: 'No damage', value: 0x02CE },
  { label: 'Weird pat sound', value: 0x02CF },
  { label: 'Eliwood\'s sword shining', value: 0x02D0 },
  { label: 'Eliwood\'s horse neighing', value: 0x02D1 },
  { label: 'Weird flaming sound', value: 0x02D2 },
  { label: 'Dancing', value: 0x02D3 },
  { label: 'Playing', value: 0x02D4 },
  { label: 'Dancing (map)', value: 0x02D5 },
  { label: 'Playing (map)', value: 0x02D6 },
  { label: 'Snag falling', value: 0x02D7 },
  { label: 'Weird charging sound', value: 0x02D8 },
  { label: 'Thud', value: 0x02D9 },
  { label: 'Sword unsheathing', value: 0x02DA },
  { label: 'Bizarre three sound effects', value: 0x02DB },
  { label: 'A ref whistle, what\'s this doing here?', value: 0x02DC },
  { label: 'Glittery sound', value: 0x02DD },
  { label: 'Shine sound', value: 0x02DE },
  { label: 'Shine sound 2', value: 0x02DF },
  { label: 'Weird rumbling', value: 0x02E0 },
  { label: 'Eclipse striking', value: 0x02E1 },
  { label: 'Eclipse striking (shorter)', value: 0x02E2 },
  { label: 'Dark Druid charging', value: 0x02E3 },
  { label: 'Nothing', value: 0x02E4 },
  { label: 'Nothing', value: 0x02E5 },
  { label: 'Nothing', value: 0x02E6 },
  { label: 'Nothing', value: 0x02E7 },
  { label: 'Dark Druid charging, then critical', value: 0x02E8 },
  { label: 'Magic shine', value: 0x02E9 },
  { label: 'Magic shine, long', value: 0x02EA },
  { label: 'Magic shine, longer', value: 0x02EB },
  { label: 'Magic shine, longer still', value: 0x02EC },
  { label: 'Magic shine, longest', value: 0x02ED },
  { label: 'Quintessence gathering', value: 0x02EE },
  { label: 'Ninian ressurrection', value: 0x02EF },
  { label: 'Rumbling at the Dragon\'s Gate', value: 0x02F0 },
  { label: 'Dragons screaming', value: 0x02F1 },
  { label: 'Fire Dragon dying', value: 0x02F2 },
  { label: 'Fire Dragon dying 2', value: 0x02F3 },
  { label: 'No damage', value: 0x02F4 },
  { label: 'High-pitched dragon yell', value: 0x02F5 },
  { label: 'Soft step', value: 0x02F6 },
  { label: 'Druid critical charge', value: 0x02F7 },
  { label: 'Sage critical conjuration', value: 0x02F8 },
  { label: 'Swish sound', value: 0x02F9 },
  { label: 'Icy sound', value: 0x02FA },
  { label: 'Fire Dragon attacking', value: 0x02FB },
  { label: 'Dragons attacking Athos', value: 0x02FC },
  { label: 'Ereshkigal charging', value: 0x02FD },
  { label: 'Ereshkigal strike', value: 0x02FE },
  { label: 'Swoosh sound', value: 0x02FF },
  { label: '???', value: 0x0300 },
];

export const MEdata = [
  { label: 'Prologue Events', value: 0x06 },
  { label: 'Ch.1 Events', value: 0x09 },
  { label: 'Ch.2 Events', value: 0x0F },
  { label: 'Ch.3 Events', value: 0x15 },
  { label: 'Ch.4 Events', value: 0x1B },
  { label: 'Ch.5 Events', value: 0x21 },
  { label: 'Ch.6 Events', value: 0x25 },
  { label: 'Ch.7 Events', value: 0x28 },
  { label: 'Ch.7x Events', value: 0x2C },
  { label: 'Ch.8 Events', value: 0x2F },
  { label: 'Ch.9 Events', value: 0x32 },
  { label: 'Ch.10 Events', value: 0x36 },
  { label: 'Ch.11E Events', value: 0x39 },
  { label: 'Ch.11H Events', value: 0x3D },
  { label: 'Ch.12 Events', value: 0x40 },
  { label: 'Ch.13 Events', value: 0x43 },
  { label: 'Ch.13x Events', value: 0x47 },
  { label: 'Ch.14 Events', value: 0x4B },
  { label: 'Ch.15H Events', value: 0x4E },
  { label: 'Ch.15/16 Events', value: 0x51 },
  { label: 'Ch.16/17 Events', value: 0x55 },
  { label: 'Ch.16x/17x Events', value: 0x5A },
  { label: 'Ch.17/18 Events', value: 0x61 },
  { label: 'Ch.18/19 Events', value: 0x65 },
  { label: 'Ch.18x/19x Events', value: 0x69 },
  { label: 'Ch.19x pt2 Events', value: 0x6F },
  { label: 'Ch.19/20 Events', value: 0x72 },
  { label: 'Ch.20/21 Events', value: 0x76 },
  { label: 'Ch.21/22 Events', value: 0x7A },
  { label: 'Ch.22/23 Events', value: 0x7F },
  { label: 'Ch.22x/23x Events', value: 0x83 },
  { label: 'Ch.23/24 (Lloyd) Events', value: 0x86 },
  { label: 'Ch.23/24 (Linus) Events', value: 0x89 },
  { label: 'Ch.25H Events', value: 0x8D },
  { label: 'Ch.24/26 Events', value: 0x90 },
  { label: 'Ch.25/27 (Kenneth) Events', value: 0x96 },
  { label: 'Ch.25/27 (Jerme) Events', value: 0x9A },
  { label: 'Ch.26/28 Events', value: 0x9E },
  { label: 'Ch.26x/28x Events', value: 0xA3 },
  { label: 'Ch.27/29 Events', value: 0xA6 },
  { label: 'Ch.28E Events', value: 0xAD },
  { label: 'Ch.30H Events', value: 0xB3 },
  { label: 'Ch.29/31 Events', value: 0xB6 },
  { label: 'Ch.29x/31x Events', value: 0xB9 },
  { label: 'Ch.30/32 Events', value: 0xBC },
  { label: 'Ch.32x Events', value: 0xC0 },
  { label: 'Final Ch. pt1 Events', value: 0xC7 },
  { label: 'Final Ch. pt2 Events', value: 0xCA },
];

export const Prologues = [
  { label: 'None', value: 0x00 },
  { label: 'Prologue Prologue', value: 0x01 },
  { label: 'Ch.1 Prologue', value: 0x02 },
  { label: 'Ch.2 Prologue', value: 0x03 },
  { label: 'Ch.3 Prologue', value: 0x04 },
  { label: 'Ch.4 Prologue', value: 0x05 },
  { label: 'Ch.5 Prologue', value: 0x06 },
  { label: 'Ch.6 Prologue', value: 0x07 },
  { label: 'Ch.7 Prologue', value: 0x08 },
  { label: 'Ch.7x Prologue', value: 0x09 },
  { label: 'Ch.8 Prologue', value: 0x0A },
  { label: 'Ch.9 Prologue', value: 0x0B },
  { label: 'Ch.10 Prologue', value: 0x0C },
  { label: 'Ch.11E Prologue', value: 0x0D },
  { label: 'Ch.11H Prologue', value: 0x0E },
  { label: 'Ch.12 Prologue', value: 0x0F },
  { label: 'Ch.13 Prologue', value: 0x10 },
  { label: 'Ch.13x Prologue', value: 0x11 },
  { label: 'Ch.14 Prologue', value: 0x12 },
  { label: 'Ch.15H Prologue', value: 0x13 },
  { label: 'Ch.15/16 Prologue', value: 0x14 },
  { label: 'Ch.16/17 Prologue', value: 0x15 },
  { label: 'Ch.16x/17x Prologue', value: 0x16 },
  { label: 'Ch.17/18 Prologue', value: 0x17 },
  { label: 'Ch.18/19 Prologue', value: 0x18 },
  { label: 'Ch.18x/19x Prologue', value: 0x19 },
  { label: 'Ch.19x pt2 Prologue', value: 0x1A },
  { label: 'Ch.19/20 Prologue', value: 0x1B },
  { label: 'Ch.20/21 Prologue', value: 0x1C },
  { label: 'Ch.21/22 Prologue', value: 0x1D },
  { label: 'Ch.22/23 Prologue', value: 0x1E },
  { label: 'Ch.23/24 (Lloyd) Prologue', value: 0x1F },
  { label: 'Ch.23/24 (Linus) Prologue', value: 0x20 },
  { label: 'Ch.25H Prologue', value: 0x21 },
  { label: 'Ch.24/26 Prologue', value: 0x22 },
  { label: 'Ch.25/27 (Kenneth) Prologue', value: 0x23 },
  { label: 'Ch.25/27 (Jerme) Prologue', value: 0x24 },
  { label: 'Ch.26/28 Prologue', value: 0x25 },
  { label: 'Ch.26x/28x Prologue', value: 0x26 },
  { label: 'Ch.27/29 Prologue', value: 0x27 },
  { label: 'Ch.28E Prologue', value: 0x28 },
  { label: 'Ch.30H Prologue', value: 0x29 },
  { label: 'Ch.29/31 Prologue', value: 0x2A },
  { label: 'Ch.30/32 Prologue', value: 0x2B },
  { label: 'Ch.32x Prologue', value: 0x2C },
];

export const Portraits = [
  { label: 'None', value: 0x00 },
  { label: 'Question Mark', value: 0x01 },
  { label: 'Eliwood', value: 0x02 },
  { label: 'Eliwood (Angry)', value: 0x03 },
  { label: 'Eliwood (Sad)', value: 0x04 },
  { label: 'Eliwood (Disguised)', value: 0x05 },
  { label: 'Eliwood (Towards player)', value: 0x06 },
  { label: 'Eliwood (Disguised)(Towards player)', value: 0x07 },
  { label: 'Eliwood (Lordly Garb)', value: 0x08 },
  { label: 'Eliwood (Cheerful) (Lordly Garb)', value: 0x09 },
  { label: 'Eliwood (Cheerful)', value: 0x0A },
  { label: 'Eliwood (Older)', value: 0x0B },
  { label: 'Hector', value: 0x0C },
  { label: 'Hector (Angry)', value: 0x0D },
  { label: 'Hector (Sad)', value: 0x0E },
  { label: 'Hector (Disguised)', value: 0x0F },
  { label: 'Hector (Disguised)(Towards player)', value: 0x10 },
  { label: 'Hector (Angry)(Disguised)', value: 0x11 },
  { label: 'Hector (Lordly Garb)', value: 0x12 },
  { label: 'Hector (Lordly Garb)(Towards player)', value: 0x13 },
  { label: 'Hector (Towards player)', value: 0x14 },
  { label: 'Hector (Older)', value: 0x15 },
  { label: 'Lyn', value: 0x16 },
  { label: 'Lyn (Thinking)', value: 0x17 },
  { label: 'Lyn (Sad)', value: 0x18 },
  { label: 'Lyn (Disguised)', value: 0x19 },
  { label: 'Lyn (Towards player)', value: 0x1A },
  { label: 'Athos', value: 0x1B },
  { label: 'Ninian', value: 0x1C },
  { label: 'Ninian (Creepy eyes)', value: 0x1D },
  { label: 'Ninian (Sad)', value: 0x1E },
  { label: 'Hawkeye', value: 0x1F },
  { label: 'Matthew', value: 0x20 },
  { label: 'Jaffar', value: 0x21 },
  { label: 'Jaffar (Angry)', value: 0x22 },
  { label: 'Raven', value: 0x23 },
  { label: 'Geitz', value: 0x24 },
  { label: 'Legault', value: 0x25 },
  { label: 'Karel', value: 0x26 },
  { label: 'Dorcas', value: 0x27 },
  { label: 'Bartre', value: 0x28 },
  { label: 'Oswin', value: 0x29 },
  { label: 'Dart', value: 0x2A },
  { label: 'Wil', value: 0x2B },
  { label: 'Guy', value: 0x2C },
  { label: 'Karla', value: 0x2D },
  { label: 'Rath', value: 0x2E },
  { label: 'Kent', value: 0x2F },
  { label: 'Sain', value: 0x30 },
  { label: 'Lowen', value: 0x31 },
  { label: 'Marcus', value: 0x32 },
  { label: 'Florina', value: 0x33 },
  { label: 'Florina (Frightened)', value: 0x34 },
  { label: 'Fiora', value: 0x35 },
  { label: 'Heath', value: 0x36 },
  { label: 'Vaida', value: 0x37 },
  { label: 'Erk', value: 0x38 },
  { label: 'Nino', value: 0x39 },
  { label: 'Pent', value: 0x3A },
  { label: 'Louise', value: 0x3B },
  { label: 'Canas', value: 0x3C },
  { label: 'Lucius', value: 0x3D },
  { label: 'Serra', value: 0x3E },
  { label: 'Priscilla', value: 0x3F },
  { label: 'Farina', value: 0x40 },
  { label: 'Nils', value: 0x41 },
  { label: 'Nils (Sad)', value: 0x42 },
  { label: 'Nils (Creepy eyes)', value: 0x43 },
  { label: 'Nils (Thinking)', value: 0x44 },
  { label: 'Renault', value: 0x45 },
  { label: 'Isadora', value: 0x46 },
  { label: 'Harken', value: 0x47 },
  { label: 'Rebecca', value: 0x48 },
  { label: 'Wallace', value: 0x49 },
  { label: 'Merlinus', value: 0x4A },
  { label: 'Hannah', value: 0x4B },
  { label: 'Elenora', value: 0x4C },
  { label: 'Elenora (Serious)', value: 0x4D },
  { label: 'Uther', value: 0x4E },
  { label: 'Elbert', value: 0x4F },
  { label: 'Fargus', value: 0x50 },
  { label: 'Zephiel', value: 0x51 },
  { label: 'Guinevere', value: 0x52 },
  { label: 'Desmond', value: 0x53 },
  { label: 'Hellene', value: 0x54 },
  { label: 'Hellene (Cheerful)', value: 0x55 },
  { label: 'Murdock', value: 0x56 },
  { label: 'Leila', value: 0x57 },
  { label: 'Leila (Eyes shut)', value: 0x58 },
  { label: 'Lord Hausen', value: 0x59 },
  { label: 'Jan', value: 0x5A },
  { label: 'Natalie', value: 0x5B },
  { label: 'Bramimond', value: 0x5C },
  { label: 'Roland', value: 0x5D },
  { label: 'Durban', value: 0x5E },
  { label: 'Nergal (Creepy look)', value: 0x5F },
  { label: 'Nergal (Another creepy look)', value: 0x60 },
  { label: 'Nergal (Both eyes visible)', value: 0x61 },
  { label: 'Nergal (Both eyes visible)(Creepy)', value: 0x62 },
  { label: 'Sonia', value: 0x63 },
  { label: 'Brendan', value: 0x64 },
  { label: 'Lloyd', value: 0x65 },
  { label: 'Linus', value: 0x66 },
  { label: 'Limstella', value: 0x67 },
  { label: 'Ephidel', value: 0x68 },
  { label: 'Ephidel (Face hidden)', value: 0x69 },
  { label: 'Darin', value: 0x6A },
  { label: 'Erik', value: 0x6B },
  { label: 'Helman', value: 0x6C },
  { label: 'Marquess Araphen', value: 0x6D },
  { label: 'Groznyi', value: 0x6E },
  { label: 'Wire', value: 0x6F },
  { label: 'Zagan', value: 0x70 },
  { label: 'Boies', value: 0x71 },
  { label: 'Sealen', value: 0x72 },
  { label: 'Bauker', value: 0x73 },
  { label: 'Bernard', value: 0x74 },
  { label: 'Damian', value: 0x75 },
  { label: 'Zoldam', value: 0x76 },
  { label: 'Uhai', value: 0x77 },
  { label: 'Aion', value: 0x78 },
  { label: 'Georg', value: 0x79 },
  { label: 'Cameron', value: 0x7A },
  { label: 'Oleg', value: 0x7B },
  { label: 'Eubans', value: 0x7C },
  { label: 'Kishuna', value: 0x7D },
  { label: 'Paul', value: 0x7E },
  { label: 'Jasmine', value: 0x7F },
  { label: 'Pascal', value: 0x80 },
  { label: 'Kenneth', value: 0x81 },
  { label: 'Jerme', value: 0x82 },
  { label: 'Maxime', value: 0x83 },
  { label: 'Ursula', value: 0x84 },
  { label: 'Teodor', value: 0x85 },
  { label: 'Denning', value: 0x86 },
  { label: 'Kaim', value: 0x87 },
  { label: 'Batta', value: 0x88 },
  { label: 'Zugu', value: 0x89 },
  { label: 'Glass', value: 0x8A },
  { label: 'Migal', value: 0x8B },
  { label: 'Carjiga', value: 0x8C },
  { label: 'Bug', value: 0x8D },
  { label: 'Puzon', value: 0x8E },
  { label: 'Bool', value: 0x8F },
  { label: 'Heintz', value: 0x90 },
  { label: 'Beyard', value: 0x91 },
  { label: 'Yogi', value: 0x92 },
  { label: 'Eagler', value: 0x93 },
  { label: 'Lundgren', value: 0x94 },
  { label: 'Igor', value: 0x95 },
  { label: 'Lloyd (Morph)', value: 0x96 },
  { label: 'Linus (Morph)', value: 0x97 },
  { label: 'Brendan (Morph)', value: 0x98 },
  { label: 'Uhai (Morph)', value: 0x99 },
  { label: 'Ursula (Morph)', value: 0x9A },
  { label: 'Kenneth (Morph)', value: 0x9B },
  { label: 'Darin (Morph)', value: 0x9C },
  { label: 'Jerme (Morph)', value: 0x9D },
  { label: 'Roy', value: 0x9E },
  { label: 'Lilina', value: 0x9F },
  { label: 'Fa', value: 0xA0 },
  { label: 'Sophia', value: 0xA1 },
  { label: 'Bishop from ch. 2', value: 0xA2 },
  { label: 'Reissmann', value: 0xA3 },
  { label: 'Reissmann (Happy)', value: 0xA4 },
  { label: 'Soldier (Blue)', value: 0xA5 },
  { label: 'Soldier (Red)', value: 0xA6 },
  { label: 'Soldier (Grey)', value: 0xA7 },
  { label: 'Soldier (Gold)', value: 0xA8 },
  { label: 'Villager (Male)', value: 0xA9 },
  { label: 'Villager (Male)', value: 0xAA },
  { label: 'Villager (Male)', value: 0xAB },
  { label: 'Villager (Male)', value: 0xAC },
  { label: 'Villager (Female)', value: 0xAD },
  { label: 'Villager (Female)', value: 0xAE },
  { label: 'Villager (Female)', value: 0xAF },
  { label: 'Villager (Male)', value: 0xB0 },
  { label: 'Villager (Male)', value: 0xB1 },
  { label: 'Villager (Boy)', value: 0xB2 },
  { label: 'Villager (Boy)', value: 0xB3 },
  { label: 'Villager (Girl)', value: 0xB4 },
  { label: 'Villager (Female)', value: 0xB5 },
  { label: 'Villager (Male)', value: 0xB6 },
  { label: 'Villager (Female)', value: 0xB7 },
  { label: 'Villager (Female)', value: 0xB8 },
  { label: 'Villager (Male)', value: 0xB9 },
  { label: 'Black Fang', value: 0xBA },
  { label: 'Black Fang', value: 0xBB },
  { label: '"Ratface" (Brigand)', value: 0xBC },
  { label: 'Bandit (Ch.3)', value: 0xBD },
  { label: 'Anna', value: 0xDF },
  { label: 'Jake', value: 0xE0 },
  { label: 'Armory', value: 0xE1 },
  { label: 'Arena', value: 0xE2 },
  { label: 'Shop', value: 0xE3 },
  { label: 'Secret shop', value: 0xE4 },
];

export const PrepNumbers = [
  { label: '[None]', value: 0x00 },
  { label: 'Chapter 0x', value: 0x01 },
  { label: 'Chapter 1', value: 0x02 },
  { label: 'Chapter 1x', value: 0x03 },
  { label: 'Chapter 2', value: 0x04 },
  { label: 'Chapter 2x', value: 0x05 },
  { label: 'Chapter 3', value: 0x06 },
  { label: 'Chapter 3x', value: 0x07 },
  { label: 'Chapter 4', value: 0x08 },
  { label: 'Chapter 4x', value: 0x09 },
  { label: 'Chapter 5', value: 0x0A },
  { label: 'Chapter 5x', value: 0x0B },
  { label: 'Chapter 6', value: 0x0C },
  { label: 'Chapter 6x', value: 0x0D },
  { label: 'Chapter 7', value: 0x0E },
  { label: 'Chapter 7x', value: 0x0F },
  { label: 'Chapter 8', value: 0x10 },
  { label: 'Chapter 8x', value: 0x11 },
  { label: 'Chapter 9', value: 0x12 },
  { label: 'Chapter 9x', value: 0x13 },
  { label: 'Chapter 10', value: 0x14 },
  { label: 'Chapter 10x', value: 0x15 },
  { label: 'Chapter 11', value: 0x16 },
  { label: 'Chapter 11x', value: 0x17 },
  { label: 'Chapter 12', value: 0x18 },
  { label: 'Chapter 12x', value: 0x19 },
  { label: 'Chapter 13', value: 0x1A },
  { label: 'Chapter 13x', value: 0x1B },
  { label: 'Chapter 14', value: 0x1C },
  { label: 'Chapter 14x', value: 0x1D },
  { label: 'Chapter 15', value: 0x1E },
  { label: 'Chapter 15x', value: 0x1F },
  { label: 'Chapter 16', value: 0x20 },
  { label: 'Chapter 16x', value: 0x21 },
  { label: 'Chapter 17', value: 0x22 },
  { label: 'Chapter 17x', value: 0x23 },
  { label: 'Chapter 18', value: 0x24 },
  { label: 'Chapter 18x', value: 0x25 },
  { label: 'Chapter 19', value: 0x26 },
  { label: 'Chapter 19x', value: 0x27 },
  { label: 'Chapter 20', value: 0x28 },
  { label: 'Chapter 20x', value: 0x29 },
  { label: 'Chapter 21', value: 0x2A },
  { label: 'Chapter 21x', value: 0x2B },
  { label: 'Chapter 22', value: 0x2C },
  { label: 'Chapter 22x', value: 0x2D },
  { label: 'Chapter 23', value: 0x2E },
  { label: 'Chapter 23x', value: 0x2F },
  { label: 'Chapter 24', value: 0x30 },
  { label: 'Chapter 24x', value: 0x31 },
  { label: 'Chapter 25', value: 0x32 },
  { label: 'Chapter 25x', value: 0x33 },
  { label: 'Chapter 26', value: 0x34 },
  { label: 'Chapter 26x', value: 0x35 },
  { label: 'Chapter 27', value: 0x36 },
  { label: 'Chapter 27x', value: 0x37 },
  { label: 'Chapter 28', value: 0x38 },
  { label: 'Chapter 28x', value: 0x39 },
  { label: 'Chapter 29', value: 0x3A },
  { label: 'Chapter 29x', value: 0x3B },
  { label: 'Chapter 30', value: 0x3C },
  { label: 'Chapter 30x', value: 0x3D },
  { label: 'Chapter 31', value: 0x3E },
  { label: 'Chapter 31x', value: 0x3F },
  { label: 'Chapter 32', value: 0x40 },
  { label: 'Chapter 32x', value: 0x41 },
  { label: 'Chapter 33', value: 0x42 },
  { label: 'Chapter 33x', value: 0x43 },
  { label: 'Chapter 34', value: 0x44 },
  { label: 'Chapter 34x', value: 0x45 },
  { label: 'Chapter 35', value: 0x46 },
  { label: 'Chapter 35x', value: 0x47 },
  { label: 'Chapter 36', value: 0x48 },
  { label: 'Chapter 36x', value: 0x49 },
  { label: 'Chapter 37', value: 0x4A },
  { label: 'Chapter 37x', value: 0x4B },
  { label: 'Chapter 38', value: 0x4C },
  { label: 'Chapter 38x', value: 0x4D },
  { label: 'Chapter 39', value: 0x4E },
  { label: 'Chapter 39x', value: 0x4F },
  { label: 'Chapter 40', value: 0x50 },
  { label: 'Chapter 40x', value: 0x51 },
  { label: 'Chapter 41', value: 0x52 },
  { label: 'Chapter 41x', value: 0x53 },
  { label: 'Chapter 42', value: 0x54 },
  { label: 'Chapter 42x', value: 0x55 },
  { label: 'Chapter 43', value: 0x56 },
  { label: 'Chapter 43x', value: 0x57 },
  { label: 'Chapter 44', value: 0x58 },
  { label: 'Chapter 44x', value: 0x59 },
  { label: 'Chapter 45', value: 0x5A },
  { label: 'Chapter 45x', value: 0x5B },
  { label: 'Chapter 46', value: 0x5C },
  { label: 'Chapter 46x', value: 0x5D },
  { label: 'Chapter 47', value: 0x5E },
  { label: 'Chapter 47x', value: 0x5F },
  { label: 'Chapter 48', value: 0x60 },
  { label: 'Chapter 48x', value: 0x61 },
  { label: 'Chapter 49', value: 0x62 },
  { label: 'Chapter 49x', value: 0x63 },
  { label: 'Chapter 50', value: 0x64 },
  { label: 'Chapter 50x', value: 0x65 },
  { label: 'Chapter 51', value: 0x66 },
  { label: 'Chapter 51x', value: 0x67 },
  { label: 'Chapter 52', value: 0x68 },
  { label: 'Chapter 52x', value: 0x69 },
  { label: 'Chapter 53', value: 0x6A },
  { label: 'Chapter 53x', value: 0x6B },
  { label: 'Chapter 54', value: 0x6C },
  { label: 'Chapter 54x', value: 0x6D },
  { label: 'Chapter 55', value: 0x6E },
  { label: 'Chapter 55x', value: 0x6F },
  { label: 'Chapter 56', value: 0x70 },
  { label: 'Chapter 56x', value: 0x71 },
  { label: 'Chapter 57', value: 0x72 },
  { label: 'Chapter 57x', value: 0x73 },
  { label: 'Chapter 58', value: 0x74 },
  { label: 'Chapter 58x', value: 0x75 },
  { label: 'Chapter 59', value: 0x76 },
  { label: 'Chapter 59x', value: 0x77 },
  { label: 'Chapter 60', value: 0x78 },
  { label: 'Chapter 60x', value: 0x79 },
  { label: 'Chapter 61', value: 0x7A },
  { label: 'Chapter 61x', value: 0x7B },
  { label: 'Chapter 62', value: 0x7C },
  { label: 'Chapter 62x', value: 0x7D },
  { label: 'Chapter 63', value: 0x7E },
  { label: 'Chapter 63x', value: 0x7F },
  { label: 'Chapter 64', value: 0x80 },
  { label: 'Chapter 64x', value: 0x81 },
  { label: 'Chapter 65', value: 0x82 },
  { label: 'Chapter 65x', value: 0x83 },
  { label: 'Chapter 66', value: 0x84 },
  { label: 'Chapter 66x', value: 0x85 },
  { label: 'Chapter 67', value: 0x86 },
  { label: 'Chapter 67x', value: 0x87 },
  { label: 'Chapter 68', value: 0x88 },
  { label: 'Chapter 68x', value: 0x89 },
  { label: 'Chapter 69', value: 0x8A },
  { label: 'Chapter 69x', value: 0x8B },
  { label: 'Chapter 70', value: 0x8C },
  { label: 'Chapter 70x', value: 0x8D },
  { label: 'Chapter 71', value: 0x8E },
  { label: 'Chapter 71x', value: 0x8F },
  { label: 'Chapter 72', value: 0x90 },
  { label: 'Chapter 72x', value: 0x91 },
  { label: 'Chapter 73', value: 0x92 },
  { label: 'Chapter 73x', value: 0x93 },
  { label: 'Chapter 74', value: 0x94 },
  { label: 'Chapter 74x', value: 0x95 },
  { label: 'Chapter 75', value: 0x96 },
  { label: 'Chapter 75x', value: 0x97 },
  { label: 'Chapter 76', value: 0x98 },
  { label: 'Chapter 76x', value: 0x99 },
  { label: 'Chapter 77', value: 0x9A },
  { label: 'Chapter 77x', value: 0x9B },
  { label: 'Chapter 78', value: 0x9C },
  { label: 'Chapter 78x', value: 0x9D },
  { label: 'Chapter 79', value: 0x9E },
  { label: 'Chapter 79x', value: 0x9F },
  { label: 'Chapter 80', value: 0xA0 },
  { label: 'Chapter 80x', value: 0xA1 },
  { label: 'Chapter 81', value: 0xA2 },
  { label: 'Chapter 81x', value: 0xA3 },
  { label: 'Chapter 82', value: 0xA4 },
  { label: 'Chapter 82x', value: 0xA5 },
  { label: 'Chapter 83', value: 0xA6 },
  { label: 'Chapter 83x', value: 0xA7 },
  { label: 'Chapter 84', value: 0xA8 },
  { label: 'Chapter 84x', value: 0xA9 },
  { label: 'Chapter 85', value: 0xAA },
  { label: 'Chapter 85x', value: 0xAB },
  { label: 'Chapter 86', value: 0xAC },
  { label: 'Chapter 86x', value: 0xAD },
  { label: 'Chapter 87', value: 0xAE },
  { label: 'Chapter 87x', value: 0xAF },
  { label: 'Chapter 88', value: 0xB0 },
  { label: 'Chapter 88x', value: 0xB1 },
  { label: 'Chapter 89', value: 0xB2 },
  { label: 'Chapter 89x', value: 0xB3 },
  { label: 'Chapter 90', value: 0xB4 },
  { label: 'Chapter 90x', value: 0xB5 },
  { label: 'Chapter 91', value: 0xB6 },
  { label: 'Chapter 91x', value: 0xB7 },
  { label: 'Chapter 92', value: 0xB8 },
  { label: 'Chapter 92x', value: 0xB9 },
  { label: 'Chapter 93', value: 0xBA },
  { label: 'Chapter 93x', value: 0xBB },
  { label: 'Chapter 94', value: 0xBC },
  { label: 'Chapter 94x', value: 0xBD },
  { label: 'Chapter 95', value: 0xBE },
  { label: 'Chapter 95x', value: 0xBF },
  { label: 'Chapter 96', value: 0xC0 },
  { label: 'Chapter 96x', value: 0xC1 },
  { label: 'Chapter 97', value: 0xC2 },
  { label: 'Chapter 97x', value: 0xC3 },
  { label: 'Chapter 98', value: 0xC4 },
  { label: 'Chapter 98x', value: 0xC5 },
  { label: 'Chapter 99', value: 0xC6 },
  { label: 'Chapter 99x', value: 0xC7 },
];

export const TitleFade = [
  { label: 'Fade to map', value: 0x00 },
  { label: 'Fade to black', value: 0x01 },
];

export const GoalWindow = [
  { label: 'None (Seize goals)', value: 0x00 },
  { label: 'Number of enemies', value: 0x01 },
  { label: 'Turn number', value: 0x02 },
  { label: 'None (Defeat Boss goals)', value: 0x03 },
  { label: 'None (Special goals)', value: 0x04 },
];

export const Characters = [
  { label: 'None', value: 0x00 },
  { label: 'Eliwood', value: 0x01 },
  { label: 'Hector', value: 0x02 },
  { label: 'Lyn (Tutorial)', value: 0x03 },
  { label: 'Raven', value: 0x04 },
  { label: 'Geitz', value: 0x05 },
  { label: 'Guy', value: 0x06 },
  { label: 'Karel', value: 0x07 },
  { label: 'Dorcas', value: 0x08 },
  { label: 'Bartre', value: 0x09 },
  { label: 'Citizen', value: 0x0A },
  { label: 'Oswin', value: 0x0B },
  { label: 'Fargus', value: 0x0C },
  { label: 'Wil (Tutorial)', value: 0x0D },
  { label: 'Rebecca', value: 0x0E },
  { label: 'Louise', value: 0x0F },
  { label: 'Lucius', value: 0x10 },
  { label: 'Serra', value: 0x11 },
  { label: 'Renault', value: 0x12 },
  { label: 'Erk', value: 0x13 },
  { label: 'Nino', value: 0x14 },
  { label: 'Pent', value: 0x15 },
  { label: 'Canas', value: 0x16 },
  { label: 'Kent (Tutorial)', value: 0x17 },
  { label: 'Sain (Tutorial)', value: 0x18 },
  { label: 'Lowen', value: 0x19 },
  { label: 'Marcus', value: 0x1A },
  { label: 'Priscilla', value: 0x1B },
  { label: 'Rath (Tutorial)', value: 0x1C },
  { label: 'Florina (Tutorial)', value: 0x1D },
  { label: 'Fiora', value: 0x1E },
  { label: 'Farina', value: 0x1F },
  { label: 'Heath', value: 0x20 },
  { label: 'Vaida', value: 0x21 },
  { label: 'Hawkeye', value: 0x22 },
  { label: 'Matthew', value: 0x23 },
  { label: 'Jaffar', value: 0x24 },
  { label: 'Ninian', value: 0x25 },
  { label: 'Nils', value: 0x26 },
  { label: 'Athos', value: 0x27 },
  { label: 'Merlinus', value: 0x28 },
  { label: 'Nils', value: 0x29 },
  { label: 'Uther', value: 0x2A },
  { label: 'Boss Vaida', value: 0x2B },
  { label: 'Wallace', value: 0x2C },
  { label: 'Lyn', value: 0x2D },
  { label: 'Wil', value: 0x2E },
  { label: 'Kent', value: 0x2F },
  { label: 'Sain', value: 0x30 },
  { label: 'Florina', value: 0x31 },
  { label: 'Rath', value: 0x32 },
  { label: 'Dart', value: 0x33 },
  { label: 'Isadora', value: 0x34 },
  { label: 'Elenora', value: 0x35 },
  { label: 'Legault', value: 0x36 },
  { label: 'Karla', value: 0x37 },
  { label: 'Harken', value: 0x38 },
  { label: 'Leila', value: 0x39 },
  { label: 'Bramimond', value: 0x3A },
  { label: 'Kishuna', value: 0x3B },
  { label: 'Groznyi', value: 0x3C },
  { label: 'Wire', value: 0x3D },
  { label: 'Bandit', value: 0x3E },
  { label: 'Zagan', value: 0x3F },
  { label: 'Boies', value: 0x40 },
  { label: 'Puzon', value: 0x41 },
  { label: 'Bandit', value: 0x42 },
  { label: 'Santals', value: 0x43 },
  { label: 'Nergal', value: 0x44 },
  { label: 'Erik', value: 0x45 },
  { label: 'Sealen', value: 0x46 },
  { label: 'Bauker', value: 0x47 },
  { label: 'Bernard', value: 0x48 },
  { label: 'Damian', value: 0x49 },
  { label: 'Zoldam', value: 0x4A },
  { label: 'Uhai', value: 0x4B },
  { label: 'Aion', value: 0x4C },
  { label: 'Darin', value: 0x4D },
  { label: 'Cameron', value: 0x4E },
  { label: 'Oleg', value: 0x4F },
  { label: 'Eubans', value: 0x50 },
  { label: 'Ursula', value: 0x51 },
  { label: 'Black Fang', value: 0x52 },
  { label: 'Paul', value: 0x53 },
  { label: 'Jasmine', value: 0x54 },
  { label: 'Black Fang', value: 0x55 },
  { label: 'Morph Jerme', value: 0x56 },
  { label: 'Pascal', value: 0x57 },
  { label: 'Kenneth', value: 0x58 },
  { label: 'Jerme', value: 0x59 },
  { label: 'Maxime', value: 0x5A },
  { label: 'Sonia', value: 0x5B },
  { label: 'Teodor', value: 0x5C },
  { label: 'Georg', value: 0x5D },
  { label: 'Kaim', value: 0x5E },
  { label: 'Merc', value: 0x5F },
  { label: 'Denning', value: 0x60 },
  { label: 'Bern', value: 0x61 },
  { label: 'Morph', value: 0x62 },
  { label: 'Lloyd (Four-Fanged Offense)', value: 0x63 },
  { label: 'Linus (Four-Fanged Offense)', value: 0x64 },
  { label: 'Lloyd (Cog of Destiny)', value: 0x65 },
  { label: 'Linus (Cog of Destiny)', value: 0x66 },
  { label: 'Bandit', value: 0x67 },
  { label: 'Bandit', value: 0x68 },
  { label: 'Bandit', value: 0x69 },
  { label: 'Laus', value: 0x6A },
  { label: 'Laus', value: 0x6B },
  { label: 'Pirate', value: 0x6C },
  { label: 'Black Fang', value: 0x6D },
  { label: 'Black Fang', value: 0x6E },
  { label: 'Ostia', value: 0x6F },
  { label: 'Black Fang', value: 0x70 },
  { label: 'Guardian', value: 0x71 },
  { label: 'Morph', value: 0x72 },
  { label: 'Morph', value: 0x73 },
  { label: 'Morph', value: 0x74 },
  { label: 'Caelin', value: 0x75 },
  { label: 'Caelin', value: 0x76 },
  { label: 'Caelin', value: 0x77 },
  { label: 'Laus', value: 0x78 },
  { label: 'Laus', value: 0x79 },
  { label: 'Zephiel', value: 0x7A },
  { label: 'Elbert', value: 0x7B },
  { label: 'Black Fang', value: 0x7C },
  { label: 'Black Fang', value: 0x7D },
  { label: 'Black Fang', value: 0x7E },
  { label: 'Morph', value: 0x7F },
  { label: 'Morph', value: 0x80 },
  { label: 'Morph', value: 0x81 },
  { label: 'Morph', value: 0x82 },
  { label: 'Black Fang', value: 0x83 },
  { label: 'Brendan', value: 0x84 },
  { label: 'Limstella', value: 0x85 },
  { label: 'Dragon', value: 0x86 },
  { label: 'Batta', value: 0x87 },
  { label: 'Bandit', value: 0x88 },
  { label: 'Zugu', value: 0x89 },
  { label: 'Bandit', value: 0x8A },
  { label: 'Bandit', value: 0x8B },
  { label: 'Bandit', value: 0x8C },
  { label: 'Glass', value: 0x8D },
  { label: 'Migal', value: 0x8E },
  { label: 'Bandit', value: 0x8F },
  { label: 'Bandit', value: 0x90 },
  { label: 'Bandit', value: 0x91 },
  { label: 'Bandit', value: 0x92 },
  { label: 'Bandit', value: 0x93 },
  { label: 'Carjiga', value: 0x94 },
  { label: 'Bandit', value: 0x95 },
  { label: 'Bandit', value: 0x96 },
  { label: 'Bandit', value: 0x97 },
  { label: 'Bandit', value: 0x98 },
  { label: 'Bug', value: 0x99 },
  { label: 'Bandit', value: 0x9A },
  { label: 'Bandit', value: 0x9B },
  { label: 'Bandit', value: 0x9C },
  { label: 'Bandit', value: 0x9D },
  { label: 'Natalie', value: 0x9E },
  { label: 'Bool', value: 0x9F },
  { label: 'Bandit', value: 0xA0 },
  { label: 'Bandit', value: 0xA1 },
  { label: 'Bandit', value: 0xA2 },
  { label: 'Bandit', value: 0xA3 },
  { label: 'Bandit', value: 0xA4 },
  { label: 'Bandit', value: 0xA5 },
  { label: 'Heintz', value: 0xA6 },
  { label: 'Black Fang', value: 0xA7 },
  { label: 'Black Fang', value: 0xA8 },
  { label: 'Black Fang', value: 0xA9 },
  { label: 'Black Fang', value: 0xAA },
  { label: 'Black Fang', value: 0xAB },
  { label: 'Black Fang', value: 0xAC },
  { label: 'Beyard', value: 0xAD },
  { label: 'Black Fang', value: 0xAE },
  { label: 'Black Fang', value: 0xAF },
  { label: 'Black Fang', value: 0xB0 },
  { label: 'Black Fang', value: 0xB1 },
  { label: 'Black Fang', value: 0xB2 },
  { label: 'Black Fang', value: 0xB3 },
  { label: 'Black Fang', value: 0xB4 },
  { label: 'Black Fang', value: 0xB5 },
  { label: 'Yogi', value: 0xB6 },
  { label: 'Caelin', value: 0xB7 },
  { label: 'Caelin', value: 0xB8 },
  { label: 'Caelin', value: 0xB9 },
  { label: 'Caelin', value: 0xBA },
  { label: 'Caelin', value: 0xBB },
  { label: 'Caelin', value: 0xBC },
  { label: 'Caelin', value: 0xBD },
  { label: 'Eagler', value: 0xBE },
  { label: 'Caelin', value: 0xBF },
  { label: 'Caelin', value: 0xC0 },
  { label: 'Caelin', value: 0xC1 },
  { label: 'Caelin', value: 0xC2 },
  { label: 'Caelin', value: 0xC3 },
  { label: 'Caelin', value: 0xC4 },
  { label: 'Lundgren', value: 0xC5 },
  { label: 'Caelin', value: 0xC6 },
  { label: 'Caelin', value: 0xC7 },
  { label: 'Caelin', value: 0xC8 },
  { label: 'Caelin', value: 0xC9 },
  { label: 'Caelin', value: 0xCA },
  { label: 'Caelin', value: 0xCB },
  { label: 'Caelin', value: 0xCC },
  { label: 'Tactician', value: 0xCD },
  { label: 'Citizen', value: 0xCE },
  { label: 'Citizen', value: 0xCF },
  { label: 'Citizen', value: 0xD0 },
  { label: 'Citizen', value: 0xD1 },
  { label: 'Citizen', value: 0xD2 },
  { label: 'Citizen', value: 0xD3 },
  { label: 'Citizen', value: 0xD4 },
  { label: 'Citizen', value: 0xD5 },
  { label: 'Citizen', value: 0xD6 },
  { label: 'Merc', value: 0xD7 },
  { label: 'Pirate', value: 0xD8 },
  { label: 'Bandit', value: 0xD9 },
  { label: 'Citizen', value: 0xDA },
  { label: 'Citizen', value: 0xDB },
  { label: 'Citizen', value: 0xDC },
  { label: 'Black Fang', value: 0xDD },
  { label: 'Black Fang', value: 0xDE },
  { label: 'Bandit', value: 0xDF },
  { label: 'Black Fang', value: 0xE0 },
  { label: 'Morph', value: 0xE1 },
  { label: 'Black Fang', value: 0xE2 },
  { label: 'Black Fang', value: 0xE3 },
  { label: 'Bandit', value: 0xE4 },
  { label: 'Ostia', value: 0xE5 },
  { label: 'Rath\'s unit', value: 0xE6 },
  { label: 'Bandit', value: 0xE7 },
  { label: 'Bandit', value: 0xE8 },
  { label: 'Bern', value: 0xE9 },
  { label: 'Guardian', value: 0xEA },
  { label: 'Morph', value: 0xEB },
  { label: 'Laus', value: 0xEC },
  { label: 'Bandit', value: 0xED },
  { label: 'Bandit', value: 0xEE },
  { label: 'Bern', value: 0xEF },
  { label: 'Guardian', value: 0xF0 },
  { label: 'Morph', value: 0xF1 },
  { label: 'Guardian', value: 0xF2 },
  { label: 'Black Fang', value: 0xF3 },
  { label: 'Morph Lloyd', value: 0xF4 },
  { label: 'Morph Linus', value: 0xF5 },
  { label: 'Morph Brendan', value: 0xF6 },
  { label: 'Morph Uhai', value: 0xF7 },
  { label: 'Morph Ursula', value: 0xF8 },
  { label: 'Morph Kenneth', value: 0xF9 },
  { label: 'Morph Darin', value: 0xFA },
  { label: 'Enemy', value: 0xFB },
  { label: 'Wall', value: 0xFC },
  { label: 'Snag', value: 0xFD },
  { label: 'None', value: 0xFE },
  { label: 'None', value: 0xFF },
];
