export const FE6ItemEditorEntries = [
  { label: 'None', value: 0 },
  { label: 'Iron Sword', value: 1 },
  { label: 'Iron Blade', value: 2 },
  { label: 'Steel Sword', value: 3 },
  { label: 'Silver Sword', value: 4 },
  { label: 'Slim Sword', value: 5 },
  { label: 'Poison Sword', value: 6 },
  { label: 'Hero Sword', value: 7 },
  { label: 'Light Brand', value: 8 },
  { label: 'Durandal', value: 9 },
  { label: 'Armourslayer', value: 10 },
  { label: 'Rapier', value: 11 },
  { label: 'Killing Edge', value: 12 },
  { label: 'Lancereaver', value: 13 },
  { label: 'Wo Dao', value: 14 },
  { label: 'Sword of Seals', value: 15 },
  { label: 'Iron Lance', value: 16 },
  { label: 'Steel Lance', value: 17 },
  { label: 'Silver Lance', value: 18 },
  { label: 'Slim Lance', value: 19 },
  { label: 'Poison Lance', value: 20 },
  { label: 'Hero Lance', value: 21 },
  { label: 'Javelin', value: 22 },
  { label: 'Maltae', value: 23 },
  { label: 'Horseslayer', value: 24 },
  { label: 'Killer Lance', value: 25 },
  { label: 'Axereaver', value: 26 },
  { label: 'Iron Axe', value: 27 },
  { label: 'Steel Axe', value: 28 },
  { label: 'Silver Axe', value: 29 },
  { label: 'Poison Axe', value: 30 },
  { label: 'Hero Axe', value: 31 },
  { label: 'Hand Axe', value: 32 },
  { label: 'Armads', value: 33 },
  { label: 'Hammer', value: 34 },
  { label: 'Killer Axe', value: 35 },
  { label: 'Swordreaver', value: 36 },
  { label: 'Devil Axe', value: 37 },
  { label: 'Halberd', value: 38 },
  { label: 'Iron Bow', value: 39 },
  { label: 'Steel Bow', value: 40 },
  { label: 'Silver Bow', value: 41 },
  { label: 'Poison Bow', value: 42 },
  { label: 'Killer Bow', value: 43 },
  { label: 'Hero Bow', value: 44 },
  { label: 'Short Bow', value: 45 },
  { label: 'Longbow', value: 46 },
  { label: 'Miugre', value: 47 },
  { label: 'Ballista', value: 48 },
  { label: 'Iron Ballista', value: 49 },
  { label: 'Killer Ballista', value: 50 },
  { label: 'Fire', value: 51 },
  { label: 'Thunder', value: 52 },
  { label: 'Fimbulvetr', value: 53 },
  { label: 'Elfire', value: 54 },
  { label: 'Aircalibur', value: 55 },
  { label: 'Fenrir', value: 56 },
  { label: 'Thunderstorm', value: 57 },
  { label: 'Forblaze', value: 58 },
  { label: 'Lightning', value: 59 },
  { label: 'Divine', value: 60 },
  { label: 'Purge', value: 61 },
  { label: 'Aureola', value: 62 },
  { label: 'Flux', value: 63 },
  { label: 'Nosferatu', value: 64 },
  { label: 'Eclipse', value: 65 },
  { label: 'Apocalypse', value: 66 },
  { label: 'Heal', value: 67 },
  { label: 'Mend', value: 68 },
  { label: 'Recover', value: 69 },
  { label: 'Libro', value: 70 },
  { label: 'Reserve', value: 71 },
  { label: 'Warp', value: 72 },
  { label: 'Rescue', value: 73 },
  { label: 'Restore', value: 74 },
  { label: 'Silence', value: 75 },
  { label: 'Sleep', value: 76 },
  { label: 'Torch', value: 77 },
  { label: 'Hammerne', value: 78 },
  { label: 'Watch', value: 79 },
  { label: 'Berserk', value: 80 },
  { label: 'Unlock', value: 81 },
  { label: 'Shield', value: 82 },
  { label: 'Fire Dragon Stone', value: 83 },
  { label: 'Divine Dragon Stone', value: 84 },
  { label: 'Magic Dragon Stone', value: 85 },
  { label: 'Secret Book', value: 86 },
  { label: 'Goddess Icon', value: 87 },
  { label: 'Angelic Robe', value: 88 },
  { label: 'Dragon Shield', value: 89 },
  { label: 'Energy Ring', value: 90 },
  { label: 'Speedwing', value: 91 },
  { label: 'Talisman', value: 92 },
  { label: 'Boots', value: 93 },
  { label: 'Body Ring', value: 94 },
  { label: 'Hero\'s Proof', value: 95 },
  { label: 'Knight\'s Proof', value: 96 },
  { label: 'Orion\'s Bolt', value: 97 },
  { label: 'Elysian Whip', value: 98 },
  { label: 'Guiding Ring', value: 99 },
  { label: 'Chest Key (5)', value: 100 },
  { label: 'Door Key', value: 101 },
  { label: 'Bridge Key', value: 102 },
  { label: 'Lockpick', value: 103 },
  { label: 'Vulnerary', value: 104 },
  { label: 'Elixir', value: 105 },
  { label: 'Holy Water', value: 106 },
  { label: 'Torch', value: 107 },
  { label: 'Antitoxin', value: 108 },
  { label: 'Member Card', value: 109 },
  { label: 'Silver Card', value: 110 },
  { label: 'Gold', value: 111 },
  { label: 'Dark Breath', value: 112 },
  { label: 'Exaccus', value: 113 },
  { label: 'Steel Blade', value: 114 },
  { label: 'Silver Blade', value: 115 },
  { label: 'Al\'s Sword', value: 116 },
  { label: 'Gant\'s Lance', value: 117 },
  { label: 'Tina\'s Staff', value: 118 },
  { label: 'Holy Maiden', value: 119 },
  { label: 'Wyrmslayer', value: 120 },
  { label: 'White Gem', value: 121 },
  { label: 'Blue Gem', value: 122 },
  { label: 'Red Gem', value: 123 },
  { label: 'Delphi Shield', value: 124 },
  { label: 'Runesword', value: 125 },
  { label: 'Spear', value: 126 },
  { label: 'Tomahawk', value: 127 },
];

export const ItemList = [
  { label: '- None', value: 0x00 },
  { label: '- Iron Sword', value: 0x01 },
  { label: '- Iron Blade', value: 0x02 },
  { label: '- Steel Sword', value: 0x03 },
  { label: '- Silver Sword', value: 0x04 },
  { label: '- Slim Sword', value: 0x05 },
  { label: '- Poison Sword', value: 0x06 },
  { label: '- Hero Sword', value: 0x07 },
  { label: '- Light Brand', value: 0x08 },
  { label: '- Durandal', value: 0x09 },
  { label: '- Armourslayer', value: 0x0A },
  { label: '- Rapier', value: 0x0B },
  { label: '- Killing Edge', value: 0x0C },
  { label: '- Lancereaver', value: 0x0D },
  { label: '- Wo Dao', value: 0x0E },
  { label: '- Sword of Seals', value: 0x0F },
  { label: '- Iron Lance', value: 0x10 },
  { label: '- Steel Lance', value: 0x11 },
  { label: '- Silver Lance', value: 0x12 },
  { label: '- Slim Lance', value: 0x13 },
  { label: '- Poison Lance', value: 0x14 },
  { label: '- Hero Lance', value: 0x15 },
  { label: '- Javelin', value: 0x16 },
  { label: '- Maltae', value: 0x17 },
  { label: '- Horseslayer', value: 0x18 },
  { label: '- Killer Lance', value: 0x19 },
  { label: '- Axereaver', value: 0x1A },
  { label: '- Iron Axe', value: 0x1B },
  { label: '- Steel Axe', value: 0x1C },
  { label: '- Silver Axe', value: 0x1D },
  { label: '- Poison Axe', value: 0x1E },
  { label: '- Hero Axe', value: 0x1F },
  { label: '- Hand Axe', value: 0x20 },
  { label: '- Armads', value: 0x21 },
  { label: '- Hammer', value: 0x22 },
  { label: '- Killer Axe', value: 0x23 },
  { label: '- Swordreaver', value: 0x24 },
  { label: '- Devil Axe', value: 0x25 },
  { label: '- Halberd', value: 0x26 },
  { label: '- Iron Bow', value: 0x27 },
  { label: '- Steel Bow', value: 0x28 },
  { label: '- Silver Bow', value: 0x29 },
  { label: '- Poison Bow', value: 0x2A },
  { label: '- Killer Bow', value: 0x2B },
  { label: '- Hero Bow', value: 0x2C },
  { label: '- Short Bow', value: 0x2D },
  { label: '- Longbow', value: 0x2E },
  { label: '- Miugre', value: 0x2F },
  { label: '- Ballista', value: 0x30 },
  { label: '- Iron Ballista', value: 0x31 },
  { label: '- Killer Ballista', value: 0x32 },
  { label: '- Fire', value: 0x33 },
  { label: '- Thunder', value: 0x34 },
  { label: '- Fimbulvetr', value: 0x35 },
  { label: '- Elfire', value: 0x36 },
  { label: '- Aircalibur', value: 0x37 },
  { label: '- Fenrir', value: 0x38 },
  { label: '- Bolting', value: 0x39 },
  { label: '- Forblaze', value: 0x3A },
  { label: '- Lightning', value: 0x3B },
  { label: '- Divine', value: 0x3C },
  { label: '- Purge', value: 0x3D },
  { label: '- Aureola', value: 0x3E },
  { label: '- Flux', value: 0x3F },
  { label: '- Nosferatu', value: 0x40 },
  { label: '- Eclipse', value: 0x41 },
  { label: '- Apocalypse', value: 0x42 },
  { label: '- Heal', value: 0x43 },
  { label: '- Mend', value: 0x44 },
  { label: '- Recover', value: 0x45 },
  { label: '- Libro', value: 0x46 },
  { label: '- Reserve', value: 0x47 },
  { label: '- Warp', value: 0x48 },
  { label: '- Rescue', value: 0x49 },
  { label: '- Restore', value: 0x4A },
  { label: '- Silence', value: 0x4B },
  { label: '- Sleep', value: 0x4C },
  { label: '- Torch', value: 0x4D },
  { label: '- Hammerne', value: 0x4E },
  { label: '- Watch', value: 0x4F },
  { label: '- Berserk', value: 0x50 },
  { label: '- Unlock', value: 0x51 },
  { label: '- Shield', value: 0x52 },
  { label: '- Fire Dragon Stone', value: 0x53 },
  { label: '- Divine Dragon Stone', value: 0x54 },
  { label: '- Magic Dragon Stone', value: 0x55 },
  { label: '- Secret Book', value: 0x56 },
  { label: '- Goddess Icon', value: 0x57 },
  { label: '- Angelic Robe', value: 0x58 },
  { label: '- Dragon Shield', value: 0x59 },
  { label: '- Energy Ring', value: 0x5A },
  { label: '- Speedwing', value: 0x5B },
  { label: '- Talisman', value: 0x5C },
  { label: '- Boots', value: 0x5D },
  { label: '- Body Ring', value: 0x5E },
  { label: '- Hero\'s Proof', value: 0x5F },
  { label: '- Knight\'s Proof', value: 0x60 },
  { label: '- Orion\'s Bolt', value: 0x61 },
  { label: '- Elysian Whip', value: 0x62 },
  { label: '- Guiding Ring', value: 0x63 },
  { label: '- Chest Key (5)', value: 0x64 },
  { label: '- Door Key', value: 0x65 },
  { label: '- Bridge Key', value: 0x66 },
  { label: '- Lockpick', value: 0x67 },
  { label: '- Vulnerary', value: 0x68 },
  { label: '- Elixir', value: 0x69 },
  { label: '- Holy Water', value: 0x6A },
  { label: '- Torch', value: 0x6B },
  { label: '- Antitoxin', value: 0x6C },
  { label: '- Member Card', value: 0x6D },
  { label: '- Silver Card', value: 0x6E },
  { label: '- Gold', value: 0x6F },
  { label: '- Dark Breath', value: 0x70 },
  { label: '- Exaccus', value: 0x71 },
  { label: '- Steel Blade', value: 0x72 },
  { label: '- Silver Blade', value: 0x73 },
  { label: '- Al\'s Sword', value: 0x74 },
  { label: '- Gant\'s Lance', value: 0x75 },
  { label: '- Tina\'s Staff', value: 0x76 },
  { label: '- Holy Maiden', value: 0x77 },
  { label: '- Wyrmslayer', value: 0x78 },
  { label: '- White Gem', value: 0x79 },
  { label: '- Blue Gem', value: 0x7A },
  { label: '- Red Gem', value: 0x7B },
  { label: '- Delphi Shield', value: 0x7C },
  { label: '- Runesword', value: 0x7D },
  { label: '- Spear', value: 0x7E },
  { label: '- Tomahawk', value: 0x7F },
];

export const WeaponType = [
  { label: 'Sword', value: 0x00 },
  { label: 'Spear', value: 0x01 },
  { label: 'Axe', value: 0x02 },
  { label: 'Bow', value: 0x03 },
  { label: 'Staff', value: 0x04 },
  { label: 'Anima', value: 0x05 },
  { label: 'Light', value: 0x06 },
  { label: 'Dark', value: 0x07 },
  { label: 'Item', value: 0x09 },
  { label: 'Dragonstone', value: 0x0B },
];

export const WeaponAbility1 = [
  { label: 'None', value: 0x00 },
  { label: 'Weapon', value: 0x01 },
  { label: 'Magic', value: 0x02 },
  { label: 'Weapon/Magic', value: 0x03 },
  { label: 'Staff', value: 0x04 },
  { label: 'Indestructible', value: 0x08 },
  { label: 'Indestructible Weapon', value: 0x09 },
  { label: 'Indestructible Magic', value: 0x0B },
  { label: 'Unsellable', value: 0x10 },
  { label: 'Unsellable Weapon', value: 0x11 },
  { label: 'Unsellable Magic', value: 0x13 },
  { label: 'Unsellable Staff', value: 0x14 },
  { label: 'Unsellable Indestructible Weapon', value: 0x19 },
  { label: 'Hero Weapon', value: 0x21 },
  { label: 'Hero Magic', value: 0x23 },
  { label: 'Hero Staff', value: 0x24 },
  { label: 'Hero Indestructible Weapon', value: 0x29 },
  { label: 'Hero Indestructible Magic', value: 0x2B },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x39', value: 0x39 },
  { label: '0x3B', value: 0x3B },
  { label: 'Magic Damage', value: 0x40 },
  { label: 'Magic Weapon', value: 0x41 },
  { label: 'Magic', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: 'Magic Indestructible Weapon', value: 0x49 },
  { label: 'Indestructible Magic', value: 0x4B },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: 'Hero Magic', value: 0x60 },
  { label: 'Magic Hero Weapon', value: 0x61 },
  { label: 'Hero Magic', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: 'Hero Indestructible Magic Weapon', value: 0x69 },
  { label: 'Hero Indestructible Magic', value: 0x6B },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: 'Uncounterable', value: 0x80 },
  { label: 'Uncounterable Weapon', value: 0x81 },
  { label: 'Uncounterable Magic', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: 'Uncounterable Indestructible Weapon', value: 0x89 },
  { label: 'Uncounterable Indestructible Magic', value: 0x8B },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: 'Uncounterable Hero', value: 0xA0 },
  { label: 'Uncounterable Hero Weapon', value: 0xA1 },
  { label: 'Uncounterable Hero Magic', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: 'Uncounterable Hero Indestructible Weapon', value: 0xA9 },
  { label: 'Uncounterable Hero Indestructible Magic', value: 0xAB },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
];

export const WeaponAbility2 = [
  { label: 'None', value: 0x00 },
  { label: 'Reverse Weapon Triangle', value: 0x01 },
  { label: 'Hammerne Effect', value: 0x02 },
  { label: 'Locked to Dragons', value: 0x04 },
  { label: 'Reverse Triangle/Dragon Lock', value: 0x05 },
  { label: 'Locked to Lord', value: 0x08 },
  { label: 'Lord Lock/Reverse Triangle', value: 0x09 },
  { label: 'Lord + Dragon Lock', value: 0x0C },
  { label: 'Lord + Dragon Lock/Reverse Triangle', value: 0x0D },
  { label: 'Swordfighter/Swordmaster Lock', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: 'Locked to King', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: 'Negate Flying Effectiveness', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x58', value: 0x58 },
  { label: 'I\'m too lazy to type this out,', value: 0x59 },
  { label: 'figure it out for yourself!', value: 0x5C },
  { label: 'Just add them up by hex,', value: 0x5D },
  { label: 'to combine the abilities.', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '???', value: 0x80 },
  { label: 'All of the above', value: 0xFF },
];

export const WeaponRanges = [
  { label: 'No range', value: 0x00 },
  { label: '1 range', value: 0x11 },
  { label: '1-2 range', value: 0x12 },
  { label: '2 range', value: 0x22 },
  { label: '2-3 range', value: 0x23 },
  { label: '3-10', value: 0x3A },
  { label: '3-15', value: 0x3F },
  { label: 'All', value: 0xFF },
];

export const WeaponRank = [
  { label: 'None', value: 0x00 },
  { label: 'E', value: 0x01 },
  { label: 'D', value: 0x33 },
  { label: 'C', value: 0x65 },
  { label: 'B', value: 0x97 },
  { label: 'A', value: 0xC9 },
  { label: 'S', value: 0xFB },
];

export const IconList = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Iron Blade', value: 0x01 },
  { label: 'Steel Sword', value: 0x02 },
  { label: 'Silver Sword', value: 0x03 },
  { label: 'Slim Sword', value: 0x04 },
  { label: 'Poison Sword', value: 0x05 },
  { label: 'Hero Sword', value: 0x06 },
  { label: 'Light Sword', value: 0x07 },
  { label: 'Durandal', value: 0x08 },
  { label: 'Armorslayer', value: 0x09 },
  { label: 'Rapier', value: 0x0A },
  { label: 'Killing Edge', value: 0x0B },
  { label: 'Lancereaver', value: 0x0C },
  { label: 'Wo Dao', value: 0x0D },
  { label: 'Sword of Seals', value: 0x0E },
  { label: 'Iron Lance', value: 0x0F },
  { label: 'Steel Lance', value: 0x10 },
  { label: 'Silver Lance', value: 0x11 },
  { label: 'Slim Lance', value: 0x12 },
  { label: 'Poison Lance', value: 0x13 },
  { label: 'Hero Lance', value: 0x14 },
  { label: 'Javelin', value: 0x15 },
  { label: 'Maltae', value: 0x16 },
  { label: 'Horseslayer', value: 0x17 },
  { label: 'Killer Lance', value: 0x18 },
  { label: 'Axereaver', value: 0x19 },
  { label: 'Iron Axe', value: 0x1A },
  { label: 'Steel Axe', value: 0x1B },
  { label: 'Silver Axe', value: 0x1C },
  { label: 'Poison Axe', value: 0x1D },
  { label: 'Hero Axe', value: 0x1E },
  { label: 'Hand Axe', value: 0x1F },
  { label: 'Armads', value: 0x20 },
  { label: 'Hammer', value: 0x21 },
  { label: 'Killer Axe', value: 0x22 },
  { label: 'Swordreaver', value: 0x23 },
  { label: 'Devil Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Iron Bow', value: 0x26 },
  { label: 'Steel Bow', value: 0x27 },
  { label: 'Silver Bow', value: 0x28 },
  { label: 'Poison Bow', value: 0x29 },
  { label: 'Killer Bow', value: 0x2A },
  { label: 'Hero Bow', value: 0x2B },
  { label: 'Longbow', value: 0x2C },
  { label: 'Miugre', value: 0x2D },
  { label: 'Ballista', value: 0x2E },
  { label: 'Iron Ballista', value: 0x2F },
  { label: 'Killer Ballista', value: 0x30 },
  { label: 'Fire', value: 0x31 },
  { label: 'Thunder', value: 0x32 },
  { label: 'Fimbulvetr', value: 0x33 },
  { label: 'Elfire', value: 0x34 },
  { label: 'Aircalibur', value: 0x35 },
  { label: 'Fenrir', value: 0x36 },
  { label: 'Bolting', value: 0x37 },
  { label: 'Forblaze', value: 0x38 },
  { label: 'Lightning', value: 0x39 },
  { label: 'Divine', value: 0x3A },
  { label: 'Purge', value: 0x3B },
  { label: 'Aureola', value: 0x3C },
  { label: 'Flux', value: 0x3D },
  { label: 'Nosferatu', value: 0x3E },
  { label: 'Eclipse', value: 0x3F },
  { label: 'Apocalypse', value: 0x40 },
  { label: 'Heal', value: 0x41 },
  { label: 'Mend', value: 0x42 },
  { label: 'Recover', value: 0x43 },
  { label: 'Libro', value: 0x44 },
  { label: 'Reserve', value: 0x45 },
  { label: 'Warp', value: 0x46 },
  { label: 'Rescue', value: 0x47 },
  { label: 'Restore', value: 0x48 },
  { label: 'Silence', value: 0x49 },
  { label: 'Sleep', value: 0x4A },
  { label: 'Torch', value: 0x4B },
  { label: 'Hammerne', value: 0x4C },
  { label: 'Watch', value: 0x4D },
  { label: 'Berserk', value: 0x4E },
  { label: 'Unlock', value: 0x4F },
  { label: 'Shield', value: 0x50 },
  { label: 'Fire Dragon Stone', value: 0x51 },
  { label: 'Divine Dragon Stone', value: 0x52 },
  { label: 'Magic Dragon Stone', value: 0x53 },
  { label: 'Secret Book', value: 0x54 },
  { label: 'Goddess Icon', value: 0x55 },
  { label: 'Angelic Robe', value: 0x56 },
  { label: 'Dragon Shield', value: 0x57 },
  { label: 'Energy Ring', value: 0x58 },
  { label: 'Speedwing', value: 0x59 },
  { label: 'Talisman', value: 0x5A },
  { label: 'Boots', value: 0x5B },
  { label: 'Body Ring', value: 0x5C },
  { label: 'Hero\'s Crest', value: 0x5D },
  { label: 'Knight\'s Crest', value: 0x5E },
  { label: 'Orion\'s Bolt', value: 0x5F },
  { label: 'Elysian Whip', value: 0x60 },
  { label: 'Guiding Ring', value: 0x61 },
  { label: 'Chest Key (5)', value: 0x62 },
  { label: 'Door Key', value: 0x63 },
  { label: 'Bridge Key', value: 0x64 },
  { label: 'Lockpick', value: 0x65 },
  { label: 'Vulnerary', value: 0x66 },
  { label: 'Elixir', value: 0x67 },
  { label: 'Holy Water', value: 0x68 },
  { label: 'Torch', value: 0x69 },
  { label: 'Antitoxin', value: 0x6A },
  { label: 'Member Card', value: 0x6B },
  { label: 'Silver Card', value: 0x6C },
  { label: 'Gold', value: 0x6D },
  { label: 'Steel Blade', value: 0x6E },
  { label: 'Silver Blade', value: 0x6F },
  { label: 'Sword Icon', value: 0x70 },
  { label: 'Lance Icon', value: 0x71 },
  { label: 'Axe Icon', value: 0x72 },
  { label: 'Bow Icon', value: 0x73 },
  { label: 'Staff Icon', value: 0x74 },
  { label: 'Anima Icon', value: 0x75 },
  { label: 'Light Icon', value: 0x76 },
  { label: 'Dark Icon', value: 0x77 },
  { label: 'Exaccus', value: 0x78 },
  { label: 'Dark Breath', value: 0x79 },
  { label: 'Fire Icon', value: 0x7A },
  { label: 'Thunder Icon', value: 0x7B },
  { label: 'Wind Icon', value: 0x7C },
  { label: 'Water Icon', value: 0x7D },
  { label: 'Dark Icon (Affinity)', value: 0x7E },
  { label: 'Light Icon (affinity)', value: 0x7F },
  { label: 'Anima Icon (Affinity)', value: 0x80 },
  { label: 'Horse Icon', value: 0x81 },
  { label: 'Pegasus Icon', value: 0x82 },
  { label: 'Wyvern Icon', value: 0x83 },
  { label: 'Al\'s Sword', value: 0x84 },
  { label: 'Gant\'s Spear', value: 0x85 },
  { label: 'Tina\'s Staff', value: 0x86 },
  { label: 'Dragon Killer', value: 0x87 },
  { label: 'Holy Maiden', value: 0x88 },
  { label: 'Red Gem', value: 0x89 },
  { label: 'Blue Gem', value: 0x8A },
  { label: 'White Gem', value: 0x8B },
  { label: 'Delphi Shield', value: 0x8C },
  { label: 'Short Bow', value: 0x8D },
  { label: 'Runesword', value: 0x8E },
  { label: 'Tomahawk', value: 0x8F },
  { label: 'Spear', value: 0x90 },
  { label: 'Sleep (FE5)', value: 0x91 },
  { label: 'Torch (FE5)', value: 0x92 },
  { label: 'Rescue (FE5)', value: 0x93 },
  { label: 'Repair (FE5)', value: 0x94 },
  { label: 'Thief (FE5)', value: 0x95 },
  { label: '??? Staff (FE5)', value: 0x96 },
  { label: 'Kia (FE5)', value: 0x97 },
  { label: 'Unlock (FE5)', value: 0x98 },
  { label: 'Barrier (FE5)', value: 0x99 },
  { label: 'Rewarp (FE5)', value: 0x9A },
  { label: '??? Staff (FE5)', value: 0x9B },
  { label: 'Broken Staff', value: 0x9C },
  { label: 'Ring', value: 0x9D },
  { label: 'Another Ring', value: 0x9E },
  { label: 'Yet Another Ring', value: 0x9F },
  { label: 'All are glitched from here on out', value: 0xA0 },
];

export const WeaponEffect = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Poison', value: 0x01 },
  { label: 'Steals HP', value: 0x02 },
  { label: 'Halves HP', value: 0x03 },
  { label: 'Devil Reversal', value: 0x04 },
];
