export const FE7SpellAssociationEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
  { label: 'Entry 68', value: 68 },
  { label: 'Entry 69', value: 69 },
  { label: 'Entry 70', value: 70 },
  { label: 'Entry 71', value: 71 },
  { label: 'Entry 72', value: 72 },
  { label: 'Entry 73', value: 73 },
  { label: 'Entry 74', value: 74 },
  { label: 'Entry 75', value: 75 },
  { label: 'Entry 76', value: 76 },
  { label: 'Entry 77', value: 77 },
  { label: 'Entry 78', value: 78 },
  { label: 'Entry 79', value: 79 },
  { label: 'Entry 80', value: 80 },
  { label: 'Entry 81', value: 81 },
  { label: 'Entry 82', value: 82 },
  { label: 'Entry 83', value: 83 },
  { label: 'Entry 84', value: 84 },
  { label: 'Entry 85', value: 85 },
  { label: 'Entry 86', value: 86 },
  { label: 'Entry 87', value: 87 },
  { label: 'Entry 88', value: 88 },
  { label: 'Entry 89', value: 89 },
  { label: 'Entry 90', value: 90 },
  { label: 'Entry 91', value: 91 },
  { label: 'Entry 92', value: 92 },
  { label: 'Entry 93', value: 93 },
  { label: 'Entry 94', value: 94 },
  { label: 'Entry 95', value: 95 },
  { label: 'Entry 96', value: 96 },
  { label: 'Entry 97', value: 97 },
  { label: 'Entry 98', value: 98 },
  { label: 'Entry 99', value: 99 },
  { label: 'Entry 100', value: 100 },
  { label: 'Entry 101', value: 101 },
  { label: 'Entry 102', value: 102 },
  { label: 'Entry 103', value: 103 },
  { label: 'Entry 104', value: 104 },
  { label: 'Entry 105', value: 105 },
  { label: 'Entry 106', value: 106 },
  { label: 'Entry 107', value: 107 },
  { label: 'Entry 108', value: 108 },
  { label: 'Entry 109', value: 109 },
  { label: 'Entry 110', value: 110 },
  { label: 'Entry 111', value: 111 },
  { label: 'Entry 112', value: 112 },
  { label: 'Entry 113', value: 113 },
  { label: 'Entry 114', value: 114 },
  { label: 'Entry 115', value: 115 },
  { label: 'Entry 116', value: 116 },
  { label: 'Entry 117', value: 117 },
  { label: 'Entry 118', value: 118 },
  { label: 'Entry 119', value: 119 },
  { label: 'Entry 120', value: 120 },
  { label: 'Entry 121', value: 121 },
  { label: 'Entry 122', value: 122 },
  { label: 'Entry 123', value: 123 },
  { label: 'Entry 124', value: 124 },
  { label: 'Entry 125', value: 125 },
  { label: 'Entry 126', value: 126 },
];

export const ItemListTU = [
  { label: 'None', value: 0x00 },
  { label: 'Iron Sword', value: 0x01 },
  { label: 'Slim Sword', value: 0x02 },
  { label: 'Steel Sword', value: 0x03 },
  { label: 'Silver Sword', value: 0x04 },
  { label: 'Iron Blade', value: 0x05 },
  { label: 'Steel Blade', value: 0x06 },
  { label: 'Silver Blade', value: 0x07 },
  { label: 'Poison Sword', value: 0x08 },
  { label: 'Rapier', value: 0x09 },
  { label: 'Mani Katti', value: 0x0A },
  { label: 'Brave Sword', value: 0x0B },
  { label: 'Wo Dao', value: 0x0C },
  { label: 'Killing Edge', value: 0x0D },
  { label: 'Armourslayer', value: 0x0E },
  { label: 'Wyrmslayer', value: 0x0F },
  { label: 'Light Brand', value: 0x10 },
  { label: 'Rune Sword', value: 0x11 },
  { label: 'Lancereaver', value: 0x12 },
  { label: 'Long Sword', value: 0x13 },
  { label: 'Iron Lance', value: 0x14 },
  { label: 'Slim Lance', value: 0x15 },
  { label: 'Steel Lance', value: 0x16 },
  { label: 'Silver Lance', value: 0x17 },
  { label: 'Poison Lance', value: 0x18 },
  { label: 'Brave Spear', value: 0x19 },
  { label: 'Killer Lance', value: 0x1A },
  { label: 'Horseslayer', value: 0x1B },
  { label: 'Javelin', value: 0x1C },
  { label: 'Spear', value: 0x1D },
  { label: 'Axereaver', value: 0x1E },
  { label: 'Iron Axe', value: 0x1F },
  { label: 'Steel Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Poison Axe', value: 0x22 },
  { label: 'Brave Axe', value: 0x23 },
  { label: 'Killer Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Hammer', value: 0x26 },
  { label: 'Devil Axe', value: 0x27 },
  { label: 'Hand Axe', value: 0x28 },
  { label: 'Tomahawk', value: 0x29 },
  { label: 'Swordreaver', value: 0x2A },
  { label: 'Swordslayer', value: 0x2B },
  { label: 'Iron Bow', value: 0x2C },
  { label: 'Steel Bow', value: 0x2D },
  { label: 'Silver Bow', value: 0x2E },
  { label: 'Poison Bow', value: 0x2F },
  { label: 'Killer Bow', value: 0x30 },
  { label: 'Brave Bow', value: 0x31 },
  { label: 'Short Bow', value: 0x32 },
  { label: 'Longbow', value: 0x33 },
  { label: 'Ballista', value: 0x34 },
  { label: 'Iron Ballista', value: 0x35 },
  { label: 'Killer Ballista', value: 0x36 },
  { label: 'Fire', value: 0x37 },
  { label: 'Thunder', value: 0x38 },
  { label: 'Elfire', value: 0x39 },
  { label: 'Bolting', value: 0x3A },
  { label: 'Fimbulvetr', value: 0x3B },
  { label: 'Forblaze', value: 0x3C },
  { label: 'Excalibur', value: 0x3D },
  { label: 'Lightning', value: 0x3E },
  { label: 'Shine', value: 0x3F },
  { label: 'Divine', value: 0x40 },
  { label: 'Purge', value: 0x41 },
  { label: 'Aura', value: 0x42 },
  { label: 'Luce', value: 0x43 },
  { label: 'Flux', value: 0x44 },
  { label: 'Luna', value: 0x45 },
  { label: 'Nosferatu', value: 0x46 },
  { label: 'Eclipse', value: 0x47 },
  { label: 'Fenrir', value: 0x48 },
  { label: 'Gespenst', value: 0x49 },
  { label: 'Heal', value: 0x4A },
  { label: 'Mend', value: 0x4B },
  { label: 'Recover', value: 0x4C },
  { label: 'Physic', value: 0x4D },
  { label: 'Fortify', value: 0x4E },
  { label: 'Restore', value: 0x4F },
  { label: 'Silence', value: 0x50 },
  { label: 'Sleep', value: 0x51 },
  { label: 'Berserk', value: 0x52 },
  { label: 'Warp', value: 0x53 },
  { label: 'Rescue', value: 0x54 },
  { label: 'Torch', value: 0x55 },
  { label: 'Hammerne', value: 0x56 },
  { label: 'Unlock', value: 0x57 },
  { label: 'Barrier', value: 0x58 },
  { label: 'Dragon Axe', value: 0x59 },
  { label: 'Angelic Robe', value: 0x5A },
  { label: 'Energy Ring', value: 0x5B },
  { label: 'Secret Book', value: 0x5C },
  { label: 'Speedwings', value: 0x5D },
  { label: 'Goddess Icon', value: 0x5E },
  { label: 'Dragon Shield', value: 0x5F },
  { label: 'Talisman', value: 0x60 },
  { label: 'Boots', value: 0x61 },
  { label: 'Body Ring', value: 0x62 },
  { label: 'Hero\'s Crest', value: 0x63 },
  { label: 'Knight\'s Crest', value: 0x64 },
  { label: 'Orion\'s Bolt', value: 0x65 },
  { label: 'Elysian Whip', value: 0x66 },
  { label: 'Guiding Ring', value: 0x67 },
  { label: 'Chest Key', value: 0x68 },
  { label: 'Door Key', value: 0x69 },
  { label: 'Lockpick', value: 0x6A },
  { label: 'Vulnerary', value: 0x6B },
  { label: 'Elixir', value: 0x6C },
  { label: 'Pure Water', value: 0x6D },
  { label: 'Antitoxin', value: 0x6E },
  { label: 'Torch', value: 0x6F },
  { label: 'Delphi Shield', value: 0x70 },
  { label: 'Member Card', value: 0x71 },
  { label: 'Silver Card', value: 0x72 },
  { label: 'White Gem', value: 0x73 },
  { label: 'Blue Gem', value: 0x74 },
  { label: 'Red Gem', value: 0x75 },
  { label: 'Gold', value: 0x76 },
  { label: 'Uber Spear', value: 0x77 },
  { label: 'Chest Key (5)', value: 0x78 },
  { label: 'Mine', value: 0x79 },
  { label: 'Light Rune', value: 0x7A },
  { label: 'Iron Rune', value: 0x7B },
  { label: 'Filla\'s Might', value: 0x7C },
  { label: 'Ninis\'s Grace', value: 0x7D },
  { label: 'Thor\'s Ire', value: 0x7E },
  { label: 'Set\'s Litany', value: 0x7F },
  { label: 'Emblem Sword', value: 0x80 },
  { label: 'Emblem Spear', value: 0x81 },
  { label: 'Emblem Axe', value: 0x82 },
  { label: 'Emblem Bow', value: 0x83 },
  { label: 'Durandal', value: 0x84 },
  { label: 'Armads', value: 0x85 },
  { label: 'Aureola', value: 0x86 },
  { label: 'Earth Seal', value: 0x87 },
  { label: 'Afa\'s Drops', value: 0x88 },
  { label: 'Heaven Seal', value: 0x89 },
  { label: 'Emblem Seal', value: 0x8A },
  { label: 'Fell Contract', value: 0x8B },
  { label: 'Sol Katti', value: 0x8C },
  { label: 'Wolf Beil/Flamberge', value: 0x8D },
  { label: 'Ereshkigal', value: 0x8E },
  { label: 'Flametongue', value: 0x8F },
  { label: 'Regal Blade', value: 0x90 },
  { label: 'Rex Hasta', value: 0x91 },
  { label: 'Basilikos', value: 0x92 },
  { label: 'Rienfleche', value: 0x93 },
  { label: 'Heavy Spear', value: 0x94 },
  { label: 'Short Spear', value: 0x95 },
  { label: 'Ocean Seal', value: 0x96 },
  { label: '3000 G', value: 0x97 },
  { label: '5000 G', value: 0x98 },
  { label: 'Wind Sword', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: 'Mithril Blade', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: 'Mithril Lance', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: 'Winter Bow', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: 'Hero\'s Flare', value: 0xA8 },
  { label: 'Quake', value: 0xA9 },
];

export const SpellAnimations = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Throwing Axe', value: 0x01 },
  { label: 'Arrow', value: 0x02 },
  { label: 'Javelin #1', value: 0x03 },
  { label: 'Javelin #2', value: 0x04 },
  { label: 'Javelin #3', value: 0x05 },
  { label: 'Javelin #4', value: 0x06 },
  { label: 'Javelin #5', value: 0x07 },
  { label: 'Javelin #6', value: 0x08 },
  { label: 'Javelin #7', value: 0x09 },
  { label: 'Javelin #8', value: 0x0A },
  { label: 'Javelin #9', value: 0x0B },
  { label: 'Javelin #10', value: 0x0C },
  { label: 'Javelin #11', value: 0x0D },
  { label: 'Dance/Play (Regular)', value: 0x0E },
  { label: 'Dance/Play (Regular)', value: 0x0F },
  { label: 'Ballista Arrow', value: 0x10 },
  { label: 'Exaccus Wave (BGM-kill)', value: 0x11 },
  { label: 'Sword of Seals Fire (BGM-kill)', value: 0x12 },
  { label: 'Flametongue', value: 0x13 },
  { label: 'Fa\'s Holy Dragon Stone', value: 0x14 },
  { label: 'Idun\'s Dark Dragon Stone (Mirrored)', value: 0x15 },
  { label: 'Fire', value: 0x16 },
  { label: 'Elfire', value: 0x17 },
  { label: 'Forblaze', value: 0x18 },
  { label: 'Thunder', value: 0x19 },
  { label: 'Bolting', value: 0x1A },
  { label: 'Fimbulvetr', value: 0x1B },
  { label: 'Nothing (stalls battle screen)', value: 0x1C },
  { label: 'Flux', value: 0x1D },
  { label: 'Nosferatu', value: 0x1E },
  { label: 'Lightning', value: 0x1F },
  { label: 'Purge', value: 0x20 },
  { label: 'Aureola', value: 0x21 },
  { label: 'Divine', value: 0x22 },
  { label: 'Nothing (Stalls battle screen)', value: 0x23 },
  { label: 'Eclipse', value: 0x24 },
  { label: 'Fenrir', value: 0x25 },
  { label: 'Heal', value: 0x26 },
  { label: 'Mend', value: 0x27 },
  { label: 'Recover', value: 0x28 },
  { label: 'Physic', value: 0x29 },
  { label: 'Fortify (Stalls)', value: 0x2A },
  { label: 'Fortify (Green Palette) (Stalls)', value: 0x2B },
  { label: 'Restore', value: 0x2C },
  { label: 'Silence', value: 0x2D },
  { label: 'Sleep', value: 0x2E },
  { label: 'Hammerne', value: 0x2F },
  { label: 'Berserk', value: 0x30 },
  { label: 'Barrier', value: 0x31 },
  { label: '(Reserved for Promo/Boost items)', value: 0x32 },
  { label: 'Shine', value: 0x33 },
  { label: 'Luna', value: 0x34 },
  { label: 'Excalibur', value: 0x35 },
  { label: 'Gespenst', value: 0x36 },
  { label: 'Aura', value: 0x37 },
  { label: 'Luce', value: 0x38 },
  { label: 'Erishkigal', value: 0x39 },
  { label: 'Filla\'s Might', value: 0x3A },
  { label: 'Nini\'s Grace', value: 0x3B },
  { label: 'Thor\'s Ire', value: 0x3C },
  { label: 'Set\'s Litany', value: 0x3D },
  { label: 'Map Only', value: 0xFFFE },
  { label: 'None', value: 0xFFFF },
];

export const Returning = [
  { label: 'Off', value: 0x00 },
  { label: 'On', value: 0x01 },
];

export const Facing = [
  { label: 'Towards target', value: 0x00 },
  { label: 'Always right', value: 0x01 },
  { label: 'Always up', value: 0x02 },
  { label: 'Always selected', value: 0x03 },
];

export const Enemyflash = [
  { label: 'White', value: 0x00 },
  { label: 'Dark', value: 0x01 },
  { label: 'Red', value: 0x02 },
  { label: 'Green', value: 0x03 },
  { label: 'Blue', value: 0x04 },
  { label: 'Yellow', value: 0x05 },
];
