import React from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { Space } from 'antd';

export default function FE8HomePage() {
  const [buffer] = useOutletContext();

  return (
    <Space
      direction="vertical"
      align="center"
      style={{ width: '100%' }}
    >
      <Link to={{ pathname: 'BattlePreparations', state: { buffer } }}>Battle Preparations</Link>
      <Link to={{ pathname: 'BattlePreperations', state: { buffer } }}>Battle Preperations</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart1', state: { buffer } }}>Battle screen editor part 1</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart2', state: { buffer } }}>Battle screen editor part 2</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart3', state: { buffer } }}>Battle screen editor part 3</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart4', state: { buffer } }}>Battle screen editor part 4</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart5', state: { buffer } }}>Battle screen editor part 5</Link>
      <Link to={{ pathname: 'Chapter1UnitEditor', state: { buffer } }}>Chapter 1 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter10AUnitEditor', state: { buffer } }}>Chapter 10A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter10BArmouryEditor', state: { buffer } }}>Chapter 10B Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter10BCutsceneUnitEditor', state: { buffer } }}>Chapter 10B Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter10BShopEditor', state: { buffer } }}>Chapter 10B Shop Editor</Link>
      <Link to={{ pathname: 'Chapter10BUnitEditor', state: { buffer } }}>Chapter 10B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter11ACutsceneUnitEditor', state: { buffer } }}>Chapter 11A Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter11AUnitEditor', state: { buffer } }}>Chapter 11A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter11BUnitEditor', state: { buffer } }}>Chapter 11B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter12AShopEditor', state: { buffer } }}>Chapter 12A Shop Editor</Link>
      <Link to={{ pathname: 'Chapter12AUnitEditor', state: { buffer } }}>Chapter 12A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter12BShopEditor', state: { buffer } }}>Chapter 12B Shop Editor</Link>
      <Link to={{ pathname: 'Chapter12BUnitEditor', state: { buffer } }}>Chapter 12B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter13ACutsceneUnitEditor', state: { buffer } }}>Chapter 13A Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter13ACutscene2UnitEditor', state: { buffer } }}>Chapter 13A Cutscene2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter13AUnitEditor', state: { buffer } }}>Chapter 13A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter13BUnitEditor', state: { buffer } }}>Chapter 13B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14ACutsceneUnitEditor', state: { buffer } }}>Chapter 14A Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14ACutscene2UnitEditor', state: { buffer } }}>Chapter 14A Cutscene2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14ACutscene3UnitEditor', state: { buffer } }}>Chapter 14A Cutscene3 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14ASecretEditor', state: { buffer } }}>Chapter 14A Secret Editor</Link>
      <Link to={{ pathname: 'Chapter14AUnitEditor', state: { buffer } }}>Chapter 14A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14BCutsceneUnitEditor', state: { buffer } }}>Chapter 14B Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14BCutscene2UnitEditor', state: { buffer } }}>Chapter 14B Cutscene2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14BCutscene3UnitEditor', state: { buffer } }}>Chapter 14B Cutscene3 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14BSecretEditor', state: { buffer } }}>Chapter 14B Secret Editor</Link>
      <Link to={{ pathname: 'Chapter14BUnitEditor', state: { buffer } }}>Chapter 14B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter15AShopEditor', state: { buffer } }}>Chapter 15A Shop Editor</Link>
      <Link to={{ pathname: 'Chapter15AUnitEditor', state: { buffer } }}>Chapter 15A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter15BShopEditor', state: { buffer } }}>Chapter 15B Shop Editor</Link>
      <Link to={{ pathname: 'Chapter15BUnitEditor', state: { buffer } }}>Chapter 15B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter16ACutsceneUnitEditor', state: { buffer } }}>Chapter 16A Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter16ACutscene2UnitEditor', state: { buffer } }}>Chapter 16A Cutscene2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter16ACutscene3UnitEditor', state: { buffer } }}>Chapter 16A Cutscene3 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter16ACutscene4UnitEditor', state: { buffer } }}>Chapter 16A Cutscene4 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter16ACutscene5UnitEditor', state: { buffer } }}>Chapter 16A Cutscene5 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter16AUnitEditor', state: { buffer } }}>Chapter 16A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter16BUnitEditor', state: { buffer } }}>Chapter 16B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter17AArmouryEditor', state: { buffer } }}>Chapter 17A Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter17AShopEditor', state: { buffer } }}>Chapter 17A Shop Editor</Link>
      <Link to={{ pathname: 'Chapter17AUnitEditor', state: { buffer } }}>Chapter 17A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter17BArmouryEditor', state: { buffer } }}>Chapter 17B Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter17BShopEditor', state: { buffer } }}>Chapter 17B Shop Editor</Link>
      <Link to={{ pathname: 'Chapter17BUnitEditor', state: { buffer } }}>Chapter 17B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter18AUnitEditor', state: { buffer } }}>Chapter 18A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter18BUnitEditor', state: { buffer } }}>Chapter 18B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter19ACutsceneUnitEditor', state: { buffer } }}>Chapter 19A Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter19ASecretEditor', state: { buffer } }}>Chapter 19A Secret Editor</Link>
      <Link to={{ pathname: 'Chapter19AUnitEditor', state: { buffer } }}>Chapter 19A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter19BSecretEditor', state: { buffer } }}>Chapter 19B Secret Editor</Link>
      <Link to={{ pathname: 'Chapter19BUnitEditor', state: { buffer } }}>Chapter 19B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter2ArmouryEditor', state: { buffer } }}>Chapter 2 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter2UnitEditor', state: { buffer } }}>Chapter 2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter20ACutsceneUnitEditor', state: { buffer } }}>Chapter 20A Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter20AUnitEditor', state: { buffer } }}>Chapter 20A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter20BUnitEditor', state: { buffer } }}>Chapter 20B Unit Editor</Link>
      <Link to={{ pathname: 'Chapter3CutsceneUnitEditor', state: { buffer } }}>Chapter 3 Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter3UnitEditor', state: { buffer } }}>Chapter 3 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter4UnitEditor', state: { buffer } }}>Chapter 4 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter5ArmouryEditor', state: { buffer } }}>Chapter 5 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter5ShopEditor', state: { buffer } }}>Chapter 5 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter5UnitEditor', state: { buffer } }}>Chapter 5 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter5xCutsceneUnitEditor', state: { buffer } }}>Chapter 5x Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter5xCutscene2UnitEditor', state: { buffer } }}>Chapter 5x Cutscene2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter5xUnitEditor', state: { buffer } }}>Chapter 5x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter6UnitEditor', state: { buffer } }}>Chapter 6 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter7UnitEditor', state: { buffer } }}>Chapter 7 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter8Cutscene2UnitEditor', state: { buffer } }}>Chapter 8 Cutscene 2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter8CutsceneUnitEditor', state: { buffer } }}>Chapter 8 Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter8UnitEditor', state: { buffer } }}>Chapter 8 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter9AArmouryEditor', state: { buffer } }}>Chapter 9A Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter9ACutsceneUnitEditor', state: { buffer } }}>Chapter 9A Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter9AShopEditor', state: { buffer } }}>Chapter 9A Shop Editor</Link>
      <Link to={{ pathname: 'Chapter9AUnitEditor', state: { buffer } }}>Chapter 9A Unit Editor</Link>
      <Link to={{ pathname: 'Chapter9BCutsceneUnitEditor', state: { buffer } }}>Chapter 9B Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter9BCutscene2UnitEditor', state: { buffer } }}>Chapter 9B Cutscene2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter9BUnitEditor', state: { buffer } }}>Chapter 9B Unit Editor</Link>
      <Link to={{ pathname: 'ChapterFinalAUnitEditor', state: { buffer } }}>Chapter FinalA Unit Editor</Link>
      <Link to={{ pathname: 'ChapterFinalBTowerofValni1UnitEditor', state: { buffer } }}>Chapter FinalB & Tower of Valni 1 Unit Editor</Link>
      <Link to={{ pathname: 'ChapterFinalBossUnitEditor', state: { buffer } }}>Chapter FinalBoss Unit Editor</Link>
      <Link to={{ pathname: 'Critbonuseditor', state: { buffer } }}>FE 8 Crit bonus editor</Link>
      <Link to={{ pathname: 'Eventtableeditor', state: { buffer } }}>FE 8 Event table editor</Link>
      <Link to={{ pathname: 'Mapspritepointertableeditor', state: { buffer } }}>FE 8 Map sprite pointer table editor</Link>
      <Link to={{ pathname: 'BattlePaletteReference', state: { buffer } }}>FE8 Battle Palette Reference</Link>
      <Link to={{ pathname: 'BossQuoteEditor', state: { buffer } }}>FE8 Boss Quote Editor</Link>
      <Link to={{ pathname: 'SpecialDeathQuoteEditor', state: { buffer } }}>FE8 Boss/Special Death Quote Editor</Link>
      <Link to={{ pathname: 'Ch1EventTileEditor', state: { buffer } }}>FE8 Ch 1 Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch1ReinforcementEditor', state: { buffer } }}>FE8 Ch 1 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch10Ephraimrecruitmenteditor', state: { buffer } }}>FE8 Ch 10 Ephraim recruitment editor</Link>
      <Link to={{ pathname: 'Ch10irikarecruitmenteditor', state: { buffer } }}>FE8 Ch 10 irika recruitment editor</Link>
      <Link to={{ pathname: 'Ch10AEventTileEditor', state: { buffer } }}>FE8 Ch 10A Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch10AReinforcementEditor', state: { buffer } }}>FE8 Ch 10A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch10BEventTileEditor', state: { buffer } }}>FE8 Ch 10B Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch10BReinforcementEditor', state: { buffer } }}>FE8 Ch 10B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch11Eirikarecruitmenteditor', state: { buffer } }}>FE8 Ch 11 Eirika recruitment editor</Link>
      <Link to={{ pathname: 'Ch11Ephraimrecruitmenteditor', state: { buffer } }}>FE8 Ch 11 Ephraim recruitment editor</Link>
      <Link to={{ pathname: 'Ch11AChestEditor', state: { buffer } }}>FE8 Ch 11A Chest Editor</Link>
      <Link to={{ pathname: 'Ch11AReinforcementEditor', state: { buffer } }}>FE8 Ch 11A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch11BEventTileEditor', state: { buffer } }}>FE8 Ch 11B Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch11BReinforcementEditor', state: { buffer } }}>FE8 Ch 11B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch12Ephraimrecruitmenteditor', state: { buffer } }}>FE8 Ch 12 Ephraim recruitment editor</Link>
      <Link to={{ pathname: 'Ch12AEventTileEditor', state: { buffer } }}>FE8 Ch 12A Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch12AReinforcementEditor', state: { buffer } }}>FE8 Ch 12A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch12BEventTileEditor', state: { buffer } }}>FE8 Ch 12B Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch12BReinforcementEditor', state: { buffer } }}>FE8 Ch 12B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch13Eirikarecruitmenteditor', state: { buffer } }}>FE8 Ch 13 Eirika recruitment editor</Link>
      <Link to={{ pathname: 'Ch13AEventTileEditor', state: { buffer } }}>FE8 Ch 13A Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch13AReinforcementEditor', state: { buffer } }}>FE8 Ch 13A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch13BEventTileEditor', state: { buffer } }}>FE8 Ch 13B Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch13BReinforcementEditor', state: { buffer } }}>FE8 Ch 13B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch14Eirikarecruitmenteditor', state: { buffer } }}>FE8 Ch 14 Eirika recruitment editor</Link>
      <Link to={{ pathname: 'Ch14AChestEditor', state: { buffer } }}>FE8 Ch 14A Chest Editor</Link>
      <Link to={{ pathname: 'Ch14AReinforcementEditor', state: { buffer } }}>FE8 Ch 14A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch14BChestEditor', state: { buffer } }}>FE8 Ch 14B Chest Editor</Link>
      <Link to={{ pathname: 'Ch14BReinforcementEditor', state: { buffer } }}>FE8 Ch 14B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch15AEventTileEditor', state: { buffer } }}>FE8 Ch 15A Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch15AReinforcementEditor', state: { buffer } }}>FE8 Ch 15A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch15BEventTileEditor', state: { buffer } }}>FE8 Ch 15B Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch15BReinforcementEditor', state: { buffer } }}>FE8 Ch 15B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch16AChestEditor', state: { buffer } }}>FE8 Ch 16A Chest Editor</Link>
      <Link to={{ pathname: 'Ch16AReinforcementEditor', state: { buffer } }}>FE8 Ch 16A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch16BChestEditor', state: { buffer } }}>FE8 Ch 16B Chest Editor</Link>
      <Link to={{ pathname: 'Ch16BReinforcementEditor', state: { buffer } }}>FE8 Ch 16B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch17Eirikarecruitmenteditor', state: { buffer } }}>FE8 Ch 17 Eirika recruitment editor</Link>
      <Link to={{ pathname: 'Ch17AEventTileEditor', state: { buffer } }}>FE8 Ch 17A Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch17AReinforcementEditor', state: { buffer } }}>FE8 Ch 17A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch17BEventTileEditor', state: { buffer } }}>FE8 Ch 17B Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch17BReinforcementEditor', state: { buffer } }}>FE8 Ch 17B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch18AEventTileEditor', state: { buffer } }}>FE8 Ch 18A Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch18AReinforcementEditor', state: { buffer } }}>FE8 Ch 18A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch18BEventTileEditor', state: { buffer } }}>FE8 Ch 18B Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch18BReinforcementEditor', state: { buffer } }}>FE8 Ch 18B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch19AChestEditor', state: { buffer } }}>FE8 Ch 19A Chest Editor</Link>
      <Link to={{ pathname: 'Ch19AReinforcementEditor', state: { buffer } }}>FE8 Ch 19A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch19BChestEditor', state: { buffer } }}>FE8 Ch 19B Chest Editor</Link>
      <Link to={{ pathname: 'Ch19BReinforcementEditor', state: { buffer } }}>FE8 Ch 19B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch2EventTileEditor', state: { buffer } }}>FE8 Ch 2 Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch2recruitmenteditor', state: { buffer } }}>FE8 Ch 2 recruitment editor</Link>
      <Link to={{ pathname: 'Ch2ReinforcementEditor', state: { buffer } }}>FE8 Ch 2 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch20AEventTileEditor', state: { buffer } }}>FE8 Ch 20A Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch20AReinforcementEditor', state: { buffer } }}>FE8 Ch 20A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch20BEventTileEditor', state: { buffer } }}>FE8 Ch 20B Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch20BReinforcementEditor', state: { buffer } }}>FE8 Ch 20B Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch3ChestEditor', state: { buffer } }}>FE8 Ch 3 Chest Editor</Link>
      <Link to={{ pathname: 'Ch3recruitmenteditor', state: { buffer } }}>FE8 Ch 3 recruitment editor</Link>
      <Link to={{ pathname: 'Ch3ReinforcementEditor', state: { buffer } }}>FE8 Ch 3 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch4EventTileEditor', state: { buffer } }}>FE8 Ch 4 Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch4ReinforcementEditor', state: { buffer } }}>FE8 Ch 4 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch5ChestEditor', state: { buffer } }}>FE8 Ch 5 Chest Editor</Link>
      <Link to={{ pathname: 'Ch5recruitmenteditor', state: { buffer } }}>FE8 Ch 5 recruitment editor</Link>
      <Link to={{ pathname: 'Ch5ReinforcementEditor', state: { buffer } }}>FE8 Ch 5 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch5xChestEditor', state: { buffer } }}>FE8 Ch 5x Chest Editor</Link>
      <Link to={{ pathname: 'Ch6EventTileEditor', state: { buffer } }}>FE8 Ch 6 Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch6ReinforcementEditor', state: { buffer } }}>FE8 Ch 6 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch7EventTileEditor', state: { buffer } }}>FE8 Ch 7 Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch7ReinforcementEditor', state: { buffer } }}>FE8 Ch 7 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch8ChestEditor', state: { buffer } }}>FE8 Ch 8 Chest Editor</Link>
      <Link to={{ pathname: 'Ch8ReinforcementEditor', state: { buffer } }}>FE8 Ch 8 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch9Eirikarecruitmenteditor', state: { buffer } }}>FE8 Ch 9 Eirika recruitment editor</Link>
      <Link to={{ pathname: 'Ch9Ephraimrecruitmenteditor', state: { buffer } }}>FE8 Ch 9 Ephraim recruitment editor</Link>
      <Link to={{ pathname: 'Ch9AEventTileEditor', state: { buffer } }}>FE8 Ch 9A Event Tile Editor</Link>
      <Link to={{ pathname: 'Ch9AReinforcementEditor', state: { buffer } }}>FE8 Ch 9A Reinforcement Editor</Link>
      <Link to={{ pathname: 'Ch9BChestEditor', state: { buffer } }}>FE8 Ch 9B Chest Editor</Link>
      <Link to={{ pathname: 'Ch9BReinforcementEditor', state: { buffer } }}>FE8 Ch 9B Reinforcement Editor</Link>
      <Link to={{ pathname: 'ChFinalAChestEditor', state: { buffer } }}>FE8 Ch FinalA Chest Editor</Link>
      <Link to={{ pathname: 'ChFinalAReinforcementEditor', state: { buffer } }}>FE8 Ch FinalA Reinforcement Editor</Link>
      <Link to={{ pathname: 'ChFinalBChestEditor', state: { buffer } }}>FE8 Ch FinalB Chest Editor</Link>
      <Link to={{ pathname: 'ChFinalBReinforcementEditor', state: { buffer } }}>FE8 Ch FinalB Reinforcement Editor</Link>
      <Link to={{ pathname: 'ChFinalBossAEventTileEditor', state: { buffer } }}>FE8 Ch FinalBossA Event Tile Editor</Link>
      <Link to={{ pathname: 'ChFinalBossBEventTileEditor', state: { buffer } }}>FE8 Ch FinalBossB Event Tile Editor</Link>
      <Link to={{ pathname: 'ChapterDataEditor', state: { buffer } }}>FE8 Chapter Data Editor</Link>
      <Link to={{ pathname: 'CharacterEditor', state: { buffer } }}>FE8 Character Editor</Link>
      <Link to={{ pathname: 'ClassChangingTable', state: { buffer } }}>FE8 Class Changing Table</Link>
      <Link to={{ pathname: 'ClassEditor', state: { buffer } }}>FE8 Class Editor</Link>
      <Link to={{ pathname: 'CustomBattleAnimationEditor', state: { buffer } }}>FE8 Custom Battle Animation Editor</Link>
      <Link to={{ pathname: 'CustomItemAnimationList', state: { buffer } }}>FE8 Custom Item Animation List</Link>
      <Link to={{ pathname: 'CustomPromotionPointerEditor', state: { buffer } }}>FE8 Custom Promotion Pointer Editor</Link>
      <Link to={{ pathname: 'CustomSupportPointerEditor', state: { buffer } }}>FE8 Custom Support Pointer Editor</Link>
      <Link to={{ pathname: 'ItemEditor', state: { buffer } }}>FE8 Item Editor</Link>
      <Link to={{ pathname: 'ItemEffectPointerEditor', state: { buffer } }}>FE8 Item Effect Pointer Editor</Link>
      <Link to={{ pathname: 'ItemRandomizingTableEditor', state: { buffer } }}>FE8 Item Randomizing Table Editor</Link>
      <Link to={{ pathname: 'ItemTargetPointerEditor', state: { buffer } }}>FE8 Item Target Pointer Editor</Link>
      <Link to={{ pathname: 'ItemUsabilityPointerEditor', state: { buffer } }}>FE8 Item Usability Pointer Editor</Link>
      <Link to={{ pathname: 'OceanSealPromotionEditor', state: { buffer } }}>FE8 Ocean Seal Promotion Editor</Link>
      <Link to={{ pathname: 'PaletteAssociationEditor', state: { buffer } }}>FE8 Palette Association Editor</Link>
      <Link to={{ pathname: 'PortraitEditor', state: { buffer } }}>FE8 Portrait Editor</Link>
      <Link to={{ pathname: 'PrologueEventTileEditor', state: { buffer } }}>FE8 Prologue Event Tile Editor</Link>
      <Link to={{ pathname: 'PromotionBranchEditor', state: { buffer } }}>FE8 Promotion Branch Editor</Link>
      <Link to={{ pathname: 'PromotionItemEditor', state: { buffer } }}>FE8 Promotion Item Editor</Link>
      <Link to={{ pathname: 'Promotionleveleditor', state: { buffer } }}>FE8 Promotion level editor</Link>
      <Link to={{ pathname: 'RandomItemGroupsTable', state: { buffer } }}>FE8 Random Item Groups Table</Link>
      <Link to={{ pathname: 'RandomItemProbabilityGroupTable', state: { buffer } }}>FE8 Random Item Probability Group Table</Link>
      <Link to={{ pathname: 'SoundRoomEditor', state: { buffer } }}>FE8 Sound Room Editor</Link>
      <Link to={{ pathname: 'SpellAssociationEditor', state: { buffer } }}>FE8 Spell Association Editor</Link>
      <Link to={{ pathname: 'Standingmapspriteeditor', state: { buffer } }}>FE8 Standing map sprite editor</Link>
      <Link to={{ pathname: 'StatBonusesEditor', state: { buffer } }}>FE8 Stat Bonuses Editor</Link>
      <Link to={{ pathname: 'Summoneditor', state: { buffer } }}>FE8 Summon editor</Link>
      <Link to={{ pathname: 'SupportPointerEditor', state: { buffer } }}>FE8 Support Pointer Editor</Link>
      <Link to={{ pathname: 'TerrainStatEditor', state: { buffer } }}>FE8 Terrain Stat Editor</Link>
      <Link to={{ pathname: 'Unknown0EventTileEditor', state: { buffer } }}>FE8 Unknown0 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown1EventTileEditor', state: { buffer } }}>FE8 Unknown1 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown1ReinforcementEditor', state: { buffer } }}>FE8 Unknown1 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown10ChestEditor', state: { buffer } }}>FE8 Unknown10 Chest Editor</Link>
      <Link to={{ pathname: 'Unknown10ReinforcementEditor', state: { buffer } }}>FE8 Unknown10 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown11EventTileEditor', state: { buffer } }}>FE8 Unknown11 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown11ReinforcementEditor', state: { buffer } }}>FE8 Unknown11 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown12EventTileEditor', state: { buffer } }}>FE8 Unknown12 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown13EventTileEditor', state: { buffer } }}>FE8 Unknown13 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown13ReinforcementEditor', state: { buffer } }}>FE8 Unknown13 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown14EventTileEditor', state: { buffer } }}>FE8 Unknown14 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown14ReinforcementEditor', state: { buffer } }}>FE8 Unknown14 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown15EventTileEditor', state: { buffer } }}>FE8 Unknown15 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown15ReinforcementEditor', state: { buffer } }}>FE8 Unknown15 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown16EventTileEditor', state: { buffer } }}>FE8 Unknown16 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown16ReinforcementEditor', state: { buffer } }}>FE8 Unknown16 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown17EventTileEditor', state: { buffer } }}>FE8 Unknown17 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown18EventTileEditor', state: { buffer } }}>FE8 Unknown18 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown19EventTileEditor', state: { buffer } }}>FE8 Unknown19 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown2ChestEditor', state: { buffer } }}>FE8 Unknown2 Chest Editor</Link>
      <Link to={{ pathname: 'Unknown20EventTileEditor', state: { buffer } }}>FE8 Unknown20 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown20ReinforcementEditor', state: { buffer } }}>FE8 Unknown20 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown21EventTileEditor', state: { buffer } }}>FE8 Unknown21 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown3EventTileEditor', state: { buffer } }}>FE8 Unknown3 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown4EventTileEditor', state: { buffer } }}>FE8 Unknown4 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown4ReinforcementEditor', state: { buffer } }}>FE8 Unknown4 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown5ChestEditor', state: { buffer } }}>FE8 Unknown5 Chest Editor</Link>
      <Link to={{ pathname: 'Unknown6EventTileEditor', state: { buffer } }}>FE8 Unknown6 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown6ReinforcementEditor', state: { buffer } }}>FE8 Unknown6 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown7ChestEditor', state: { buffer } }}>FE8 Unknown7 Chest Editor</Link>
      <Link to={{ pathname: 'Unknown8EventTileEditor', state: { buffer } }}>FE8 Unknown8 Event Tile Editor</Link>
      <Link to={{ pathname: 'Unknown8ReinforcementEditor', state: { buffer } }}>FE8 Unknown8 Reinforcement Editor</Link>
      <Link to={{ pathname: 'Unknown9EventTileEditor', state: { buffer } }}>FE8 Unknown9 Event Tile Editor</Link>
      <Link to={{ pathname: 'FireEmblem8PairedEndingsEditor', state: { buffer } }}>Fire Emblem 8 (Paired) Endings Editor </Link>
      <Link to={{ pathname: 'FireEmblem8SupportcompatibilityEditor', state: { buffer } }}>Fire Emblem 8 Support compatibility Editor </Link>
      <Link to={{ pathname: 'FireEmblem8SupportConvoAvailabilityEditor', state: { buffer } }}>Fire Emblem 8 Support Convo Availability Editor </Link>
      <Link to={{ pathname: 'LagdouRuins2MelkaenCoastUnitEditor', state: { buffer } }}>Lagdou Ruins 2 & Melkaen Coast Unit Editor</Link>
      <Link to={{ pathname: 'LevelCapEditor', state: { buffer } }}>Level Cap Editor</Link>
      <Link to={{ pathname: 'MapBethroenArmouryEditor', state: { buffer } }}>Map - Bethroen Armoury Editor</Link>
      <Link to={{ pathname: 'MapBethroenShopEditor', state: { buffer } }}>Map - Bethroen Shop Editor</Link>
      <Link to={{ pathname: 'MapCaerPelynShopEditor', state: { buffer } }}>Map - Caer Pelyn Shop Editor</Link>
      <Link to={{ pathname: 'MapGradoKeepSecretEditor', state: { buffer } }}>Map - Grado Keep Secret Editor</Link>
      <Link to={{ pathname: 'MapIdeArmouryEditor', state: { buffer } }}>Map - Ide Armoury Editor</Link>
      <Link to={{ pathname: 'MapJehannaHallSecretEditor', state: { buffer } }}>Map - Jehanna Hall Secret Editor</Link>
      <Link to={{ pathname: 'MapJehannaHallShopEditor', state: { buffer } }}>Map - Jehanna Hall Shop Editor</Link>
      <Link to={{ pathname: 'MapNarubeRiverArmouryEditor', state: { buffer } }}>Map - Narube River Armoury Editor</Link>
      <Link to={{ pathname: 'MapNarubeRiverShopEditor', state: { buffer } }}>Map - Narube River Shop Editor</Link>
      <Link to={{ pathname: 'MapPortKirisArmouryEditor', state: { buffer } }}>Map - Port Kiris Armoury Editor</Link>
      <Link to={{ pathname: 'MapPortKirisShopEditor', state: { buffer } }}>Map - Port Kiris Shop Editor</Link>
      <Link to={{ pathname: 'MapRaustenCourtArmouryEditor', state: { buffer } }}>Map - Rausten Court Armoury Editor</Link>
      <Link to={{ pathname: 'MapRaustenCourtSecretEditor', state: { buffer } }}>Map - Rausten Court Secret Editor</Link>
      <Link to={{ pathname: 'MapRaustenCourtShopEditor', state: { buffer } }}>Map - Rausten Court Shop Editor</Link>
      <Link to={{ pathname: 'MapSerafewArmouryEditor', state: { buffer } }}>Map - Serafew Armoury Editor</Link>
      <Link to={{ pathname: 'MapSerafewShopEditor', state: { buffer } }}>Map - Serafew Shop Editor</Link>
      <Link to={{ pathname: 'MapTaizelShopEditor', state: { buffer } }}>Map - Taizel Shop Editor</Link>
      <Link to={{ pathname: 'PrologueCutsceneUnitEditor', state: { buffer } }}>Prologue Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'PrologueCutscene2UnitEditor', state: { buffer } }}>Prologue Cutscene2 Unit Editor</Link>
      <Link to={{ pathname: 'PrologueUnitEditor', state: { buffer } }}>Prologue Unit Editor</Link>
      <Link to={{ pathname: 'SRankBonusEditor', state: { buffer } }}>S-Rank Bonus Editor</Link>
      <Link to={{ pathname: 'Summoncharactereditor', state: { buffer } }}>Summon character editor</Link>
      <Link to={{ pathname: 'Supportbonuseditor', state: { buffer } }}>Support bonus editor</Link>
      <Link to={{ pathname: 'TowerofValni2UnitEditor', state: { buffer } }}>Tower of Valni 2 Unit Editor</Link>
      <Link to={{ pathname: 'TowerofValni3UnitEditor', state: { buffer } }}>Tower of Valni 3 Unit Editor</Link>
      <Link to={{ pathname: 'TowerofValni4LagdouRuins1UnitEditor', state: { buffer } }}>Tower of Valni 4 & Lagdou Ruins 1 Unit Editor</Link>
      <Link to={{ pathname: 'UnitMenutable', state: { buffer } }}>Unit Menu table</Link>
      <Link to={{ pathname: 'Unknown5UnitEditor', state: { buffer } }}>Unknown5 Unit Editor</Link>
      <Link to={{ pathname: 'Unknown6UnitEditor', state: { buffer } }}>Unknown6 Unit Editor</Link>
    </Space>
  );
}
