export const FE7ItemEditor = [
  { label: 'None', value: 0 },
  { label: 'Iron Sword', value: 1 },
  { label: 'Thin Sword', value: 2 },
  { label: 'Steel Sword', value: 3 },
  { label: 'Silver Sword', value: 4 },
  { label: 'Iron Blade', value: 5 },
  { label: 'Steel Blade', value: 6 },
  { label: 'Silver Blade', value: 7 },
  { label: 'Poison Sword', value: 8 },
  { label: 'Rapier', value: 9 },
  { label: 'Mani Katti', value: 10 },
  { label: 'Hero Sword', value: 11 },
  { label: 'Wo Dao', value: 12 },
  { label: 'Killer Sword', value: 13 },
  { label: 'Armour Killer', value: 14 },
  { label: 'Dragon Killer', value: 15 },
  { label: 'Light Sword', value: 16 },
  { label: 'Rune Sword', value: 17 },
  { label: 'Lancebuster', value: 18 },
  { label: 'Long Sword', value: 19 },
  { label: 'Iron Spear', value: 20 },
  { label: 'Thin Spear', value: 21 },
  { label: 'Steel Spear', value: 22 },
  { label: 'Silver Spear', value: 23 },
  { label: 'Poison Spear', value: 24 },
  { label: 'Hero Spear', value: 25 },
  { label: 'Killer Lance', value: 26 },
  { label: 'Horse Killer', value: 27 },
  { label: 'Javelin', value: 28 },
  { label: 'Slender Spear', value: 29 },
  { label: 'Axebuster', value: 30 },
  { label: 'Iron Axe', value: 31 },
  { label: 'Steel Axe', value: 32 },
  { label: 'Silver Axe', value: 33 },
  { label: 'Poison Axe', value: 34 },
  { label: 'Hero Axe', value: 35 },
  { label: 'Killer Axe', value: 36 },
  { label: 'Halberd', value: 37 },
  { label: 'Hammer', value: 38 },
  { label: 'Devil Axe', value: 39 },
  { label: 'Hand Axe', value: 40 },
  { label: 'Tomahawk', value: 41 },
  { label: 'Swordbuster', value: 42 },
  { label: 'Sword Killer', value: 43 },
  { label: 'Iron Bow', value: 44 },
  { label: 'Steel Bow', value: 45 },
  { label: 'Silver Bow', value: 46 },
  { label: 'Poison Bow', value: 47 },
  { label: 'Killer Bow', value: 48 },
  { label: 'Hero Bow', value: 49 },
  { label: 'Short Bow', value: 50 },
  { label: 'Longbow', value: 51 },
  { label: 'Ballista', value: 52 },
  { label: 'Iron Ballista', value: 53 },
  { label: 'Killer Ballista', value: 54 },
  { label: 'Fire', value: 55 },
  { label: 'Thunder', value: 56 },
  { label: 'Elfire', value: 57 },
  { label: 'Thunderstorm', value: 58 },
  { label: 'Fimbulvetr', value: 59 },
  { label: 'Forblaze', value: 60 },
  { label: 'Excalibur', value: 61 },
  { label: 'Lightning', value: 62 },
  { label: 'Shine', value: 63 },
  { label: 'Divine', value: 64 },
  { label: 'Purge', value: 65 },
  { label: 'Aura', value: 66 },
  { label: 'Luce', value: 67 },
  { label: 'Flux', value: 68 },
  { label: 'Luna', value: 69 },
  { label: 'Nosferatu', value: 70 },
  { label: 'Eclipse', value: 71 },
  { label: 'Fenrir', value: 72 },
  { label: 'Gespenst', value: 73 },
  { label: 'Live', value: 74 },
  { label: 'Relive', value: 75 },
  { label: 'Recover', value: 76 },
  { label: 'Libro', value: 77 },
  { label: 'Reserve', value: 78 },
  { label: 'Restore', value: 79 },
  { label: 'Silence', value: 80 },
  { label: 'Sleep', value: 81 },
  { label: 'Berserk', value: 82 },
  { label: 'Warp', value: 83 },
  { label: 'Rescue', value: 84 },
  { label: 'Torch', value: 85 },
  { label: 'Hammerne', value: 86 },
  { label: 'Unlock', value: 87 },
  { label: 'Barrier', value: 88 },
  { label: 'Dragon Axe', value: 89 },
  { label: 'Angelic Robe', value: 90 },
  { label: 'Energy Ring', value: 91 },
  { label: 'Secret Book', value: 92 },
  { label: 'Speedwings', value: 93 },
  { label: 'Goddess Icon', value: 94 },
  { label: 'Dragon Shield', value: 95 },
  { label: 'Talisman', value: 96 },
  { label: 'Boots', value: 97 },
  { label: 'Body Ring', value: 98 },
  { label: 'Hero\'s Crest', value: 99 },
  { label: 'Knight\'s Crest', value: 100 },
  { label: 'Orion\'s Bolt', value: 101 },
  { label: 'Elysian Whip', value: 102 },
  { label: 'Guiding Ring', value: 103 },
  { label: 'Chest Key', value: 104 },
  { label: 'Door Key', value: 105 },
  { label: 'Thief Key', value: 106 },
  { label: 'Vulnerary', value: 107 },
  { label: 'Elixir', value: 108 },
  { label: 'Pure Water', value: 109 },
  { label: 'Antitoxin', value: 110 },
  { label: 'Torch', value: 111 },
  { label: 'Delphi Shield', value: 112 },
  { label: 'Member Card', value: 113 },
  { label: 'Silver Card', value: 114 },
  { label: 'White Gem', value: 115 },
  { label: 'Blue Gem', value: 116 },
  { label: 'Red Gem', value: 117 },
  { label: 'Gold', value: 118 },
  { label: 'Uber Spear', value: 119 },
  { label: 'Chest Key (5)', value: 120 },
  { label: 'Mine', value: 121 },
  { label: 'Light Rune', value: 122 },
  { label: 'Iron Rune', value: 123 },
  { label: 'Filla\'s Might', value: 124 },
  { label: 'Ninis\'s Grace', value: 125 },
  { label: 'Thor\'s Ire', value: 126 },
  { label: 'Set\'s Litany', value: 127 },
  { label: 'Emblem Sword', value: 128 },
  { label: 'Emblem Spear', value: 129 },
  { label: 'Emblem Axe', value: 130 },
  { label: 'Emblem Bow', value: 131 },
  { label: 'Durandal', value: 132 },
  { label: 'Armads', value: 133 },
  { label: 'Aureola', value: 134 },
  { label: 'Earth Seal', value: 135 },
  { label: 'Afa\'s Drops', value: 136 },
  { label: 'Heaven Seal', value: 137 },
  { label: 'Emblem Seal', value: 138 },
  { label: 'Fell Contract', value: 139 },
  { label: 'Sol Katti', value: 140 },
  { label: 'Wolf Beil', value: 141 },
  { label: 'Ereshkigal', value: 142 },
  { label: 'Fire Dragon Stone', value: 143 },
  { label: 'Regal Blade', value: 144 },
  { label: 'Rex Hasta', value: 145 },
  { label: 'Basilikos', value: 146 },
  { label: 'Rienfleche', value: 147 },
  { label: 'Heavy Spear', value: 148 },
  { label: 'Short Spear', value: 149 },
  { label: 'Ocean Seal', value: 150 },
  { label: '3000 G', value: 151 },
  { label: '5000 G', value: 152 },
  { label: 'Wind Sword', value: 153 },
  { label: 'Entry 154', value: 154 },
  { label: 'Entry 155', value: 155 },
  { label: 'Entry 156', value: 156 },
  { label: 'Entry 157', value: 157 },
  { label: 'Entry 158', value: 158 },
];

export const ItemList = [
  { label: 'None', value: 0x00 },
  { label: 'Iron Sword', value: 0x01 },
  { label: 'Slim Sword', value: 0x02 },
  { label: 'Steel Sword', value: 0x03 },
  { label: 'Silver Sword', value: 0x04 },
  { label: 'Iron Blade', value: 0x05 },
  { label: 'Steel Blade', value: 0x06 },
  { label: 'Silver Blade', value: 0x07 },
  { label: 'Poison Sword', value: 0x08 },
  { label: 'Rapier', value: 0x09 },
  { label: 'Mani Katti', value: 0x0A },
  { label: 'Brave Sword', value: 0x0B },
  { label: 'Wo Dao', value: 0x0C },
  { label: 'Killing Edge', value: 0x0D },
  { label: 'Armourslayer', value: 0x0E },
  { label: 'Wyrmslayer', value: 0x0F },
  { label: 'Light Brand', value: 0x10 },
  { label: 'Rune Sword', value: 0x11 },
  { label: 'Lancereaver', value: 0x12 },
  { label: 'Long Sword', value: 0x13 },
  { label: 'Iron Lance', value: 0x14 },
  { label: 'Slim Lance', value: 0x15 },
  { label: 'Steel Lance', value: 0x16 },
  { label: 'Silver Lance', value: 0x17 },
  { label: 'Poison Lance', value: 0x18 },
  { label: 'Brave Spear', value: 0x19 },
  { label: 'Killer Lance', value: 0x1A },
  { label: 'Horseslayer', value: 0x1B },
  { label: 'Javelin', value: 0x1C },
  { label: 'Spear', value: 0x1D },
  { label: 'Axereaver', value: 0x1E },
  { label: 'Iron Axe', value: 0x1F },
  { label: 'Steel Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Poison Axe', value: 0x22 },
  { label: 'Brave Axe', value: 0x23 },
  { label: 'Killer Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Hammer', value: 0x26 },
  { label: 'Devil Axe', value: 0x27 },
  { label: 'Hand Axe', value: 0x28 },
  { label: 'Tomahawk', value: 0x29 },
  { label: 'Swordreaver', value: 0x2A },
  { label: 'Swordslayer', value: 0x2B },
  { label: 'Iron Bow', value: 0x2C },
  { label: 'Steel Bow', value: 0x2D },
  { label: 'Silver Bow', value: 0x2E },
  { label: 'Poison Bow', value: 0x2F },
  { label: 'Killer Bow', value: 0x30 },
  { label: 'Brave Bow', value: 0x31 },
  { label: 'Short Bow', value: 0x32 },
  { label: 'Longbow', value: 0x33 },
  { label: 'Ballista', value: 0x34 },
  { label: 'Iron Ballista', value: 0x35 },
  { label: 'Killer Ballista', value: 0x36 },
  { label: 'Fire', value: 0x37 },
  { label: 'Thunder', value: 0x38 },
  { label: 'Elfire', value: 0x39 },
  { label: 'Bolting', value: 0x3A },
  { label: 'Fimbulvetr', value: 0x3B },
  { label: 'Forblaze', value: 0x3C },
  { label: 'Excalibur', value: 0x3D },
  { label: 'Lightning', value: 0x3E },
  { label: 'Shine', value: 0x3F },
  { label: 'Divine', value: 0x40 },
  { label: 'Purge', value: 0x41 },
  { label: 'Aura', value: 0x42 },
  { label: 'Luce', value: 0x43 },
  { label: 'Flux', value: 0x44 },
  { label: 'Luna', value: 0x45 },
  { label: 'Nosferatu', value: 0x46 },
  { label: 'Eclipse', value: 0x47 },
  { label: 'Fenrir', value: 0x48 },
  { label: 'Gespenst', value: 0x49 },
  { label: 'Heal', value: 0x4A },
  { label: 'Mend', value: 0x4B },
  { label: 'Recover', value: 0x4C },
  { label: 'Physic', value: 0x4D },
  { label: 'Fortify', value: 0x4E },
  { label: 'Restore', value: 0x4F },
  { label: 'Silence', value: 0x50 },
  { label: 'Sleep', value: 0x51 },
  { label: 'Berserk', value: 0x52 },
  { label: 'Warp', value: 0x53 },
  { label: 'Rescue', value: 0x54 },
  { label: 'Torch', value: 0x55 },
  { label: 'Hammerne', value: 0x56 },
  { label: 'Unlock', value: 0x57 },
  { label: 'Barrier', value: 0x58 },
  { label: 'Dragon Axe', value: 0x59 },
  { label: 'Angelic Robe', value: 0x5A },
  { label: 'Energy Ring', value: 0x5B },
  { label: 'Secret Book', value: 0x5C },
  { label: 'Speedwings', value: 0x5D },
  { label: 'Goddess Icon', value: 0x5E },
  { label: 'Dragon Shield', value: 0x5F },
  { label: 'Talisman', value: 0x60 },
  { label: 'Boots', value: 0x61 },
  { label: 'Body Ring', value: 0x62 },
  { label: 'Hero\'s Crest', value: 0x63 },
  { label: 'Knight\'s Crest', value: 0x64 },
  { label: 'Orion\'s Bolt', value: 0x65 },
  { label: 'Elysian Whip', value: 0x66 },
  { label: 'Guiding Ring', value: 0x67 },
  { label: 'Chest Key', value: 0x68 },
  { label: 'Door Key', value: 0x69 },
  { label: 'Lockpick', value: 0x6A },
  { label: 'Vulnerary', value: 0x6B },
  { label: 'Elixir', value: 0x6C },
  { label: 'Pure Water', value: 0x6D },
  { label: 'Antitoxin', value: 0x6E },
  { label: 'Torch', value: 0x6F },
  { label: 'Delphi Shield', value: 0x70 },
  { label: 'Member Card', value: 0x71 },
  { label: 'Silver Card', value: 0x72 },
  { label: 'White Gem', value: 0x73 },
  { label: 'Blue Gem', value: 0x74 },
  { label: 'Red Gem', value: 0x75 },
  { label: 'Gold', value: 0x76 },
  { label: 'Uber Spear', value: 0x77 },
  { label: 'Chest Key (5)', value: 0x78 },
  { label: 'Mine', value: 0x79 },
  { label: 'Light Rune', value: 0x7A },
  { label: 'Iron Rune', value: 0x7B },
  { label: 'Filla\'s Might', value: 0x7C },
  { label: 'Ninis\'s Grace', value: 0x7D },
  { label: 'Thor\'s Ire', value: 0x7E },
  { label: 'Set\'s Litany', value: 0x7F },
  { label: 'Emblem Sword', value: 0x80 },
  { label: 'Emblem Spear', value: 0x81 },
  { label: 'Emblem Axe', value: 0x82 },
  { label: 'Emblem Bow', value: 0x83 },
  { label: 'Durandal', value: 0x84 },
  { label: 'Armads', value: 0x85 },
  { label: 'Aureola', value: 0x86 },
  { label: 'Earth Seal', value: 0x87 },
  { label: 'Afa\'s Drops', value: 0x88 },
  { label: 'Heaven Seal', value: 0x89 },
  { label: 'Emblem Seal', value: 0x8A },
  { label: 'Fell Contract', value: 0x8B },
  { label: 'Sol Katti', value: 0x8C },
  { label: 'Wolf Beil', value: 0x8D },
  { label: 'Ereshkigal', value: 0x8E },
  { label: 'Flametongue', value: 0x8F },
  { label: 'Regal Blade', value: 0x90 },
  { label: 'Rex Hasta', value: 0x91 },
  { label: 'Basilikos', value: 0x92 },
  { label: 'Rienfleche', value: 0x93 },
  { label: 'Heavy Spear', value: 0x94 },
  { label: 'Short Spear', value: 0x95 },
  { label: 'Ocean Seal', value: 0x96 },
  { label: '3000 G', value: 0x97 },
  { label: '5000 G', value: 0x98 },
  { label: 'Wind Sword', value: 0x99 },
];

export const WeaponType = [
  { label: 'Sword', value: 0x00 },
  { label: 'Spear', value: 0x01 },
  { label: 'Axe', value: 0x02 },
  { label: 'Bow', value: 0x03 },
  { label: 'Staff', value: 0x04 },
  { label: 'Anima', value: 0x05 },
  { label: 'Light', value: 0x06 },
  { label: 'Dark', value: 0x07 },
  { label: '0x08', value: 0x08 },
  { label: 'Item', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: 'Dragon Stone', value: 0x0B },
  { label: 'Dancing Ring', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: '0x10', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
];

export const WeaponAbility1 = [
  { label: 'None', value: 0x00 },
  { label: 'Weapon', value: 0x01 },
  { label: 'Magic', value: 0x02 },
  { label: 'Weapon/Magic', value: 0x03 },
  { label: 'Staff', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'Indestructible', value: 0x08 },
  { label: 'Indestructible Weapon', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: 'Indestructible Magic', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Unsellable', value: 0x10 },
  { label: 'Unsellable Weapon', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: 'Unsellable Magic', value: 0x13 },
  { label: 'Unsellable Staff', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: 'Unsellable Indestructible Weapon', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: 'Unsellable Indestructible Magic', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Hero', value: 0x20 },
  { label: 'Hero Weapon', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: 'Hero Magic', value: 0x23 },
  { label: 'Hero Staff', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: 'Hero Indestructible Weapon', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: 'Hero Indestructible Magic', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Magic Damage', value: 0x40 },
  { label: 'Magic Weapon', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: 'Magic', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: 'Magic Indestructible Weapon', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: 'Indestructible Magic', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: 'Hero Magic', value: 0x60 },
  { label: 'Magic Hero Weapon', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: 'Hero Magic', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: 'Hero Indestructible Magic Weapon', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: 'Hero Indestructible Magic', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Uncounterable', value: 0x80 },
  { label: 'Uncounterable Weapon', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: 'Uncounterable Magic', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: 'Uncounterable Indestructible Weapon', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: 'Uncounterable Indestructible Magic', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: 'Uncounterable Hero', value: 0xA0 },
  { label: 'Uncounterable Hero Weapon', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: 'Uncounterable Hero Magic', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: 'Uncounterable Hero Indestructible Weapon', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: 'Uncounterable Hero Indestructible Magic', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'All of the above', value: 0xFF },
];

export const WeaponAbility2 = [
  { label: 'None', value: 0x00 },
  { label: 'Reverse Weapon Triangle', value: 0x01 },
  { label: '???', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Dragon Stone Property', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: '???', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Swordfighter/Swordmaster/Lyn Lock', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: '???', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Negate Flying Effectiveness', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Negate Criticals', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'All of the above', value: 0xFF },
];

export const WeaponAbility3 = [
  { label: 'None', value: 0x00 },
  { label: '0x01', value: 0x01 },
  { label: 'Negate Target Defenses', value: 0x02 },
  { label: 'Locked to Eliwood', value: 0x04 },
  { label: 'Locked to Hector', value: 0x08 },
  { label: 'Locked to Lyn', value: 0x10 },
  { label: 'Locked to Athos', value: 0x20 },
  { label: '0x40', value: 0x40 },
  { label: '0x80', value: 0x80 },
];

export const WeaponAbility4 = [
  { label: '- None', value: 0x00 },
  { label: '- None', value: 0x01 },
  { label: '- None', value: 0x02 },
  { label: '- None', value: 0x04 },
  { label: '- None', value: 0x08 },
  { label: '0x10', value: 0x10 },
  { label: '0x20', value: 0x20 },
  { label: '0x40', value: 0x40 },
  { label: '0x80', value: 0x80 },
];

export const StatBoostPointers = [
  { label: '- No Stat boost', value: 0x00 },
  { label: '- Angelic Robe (+7 HP)', value: 0x8C98FA4 },
  { label: '- Energy Ring (+2 Str)', value: 0x8C98FB0 },
  { label: '- Skill Book (+2 Skill)', value: 0x8C98FBC },
  { label: '- Speedwings (+2 Spd)', value: 0x8C98FC8 },
  { label: '- Goddess Icon (+2 Luck)', value: 0x8C98FD4 },
  { label: '- Dragonshield (+2 Def)', value: 0x8C98FE0 },
  { label: '- Talisman (+2 Res)', value: 0x8C98FEC },
  { label: '- Move bonus', value: 0x8C98FF8 },
  { label: '- Constitution Bonus', value: 0x8C99004 },
  { label: '- Vaida\'s Spear', value: 0x8C99010 },
  { label: '- Durandal', value: 0x8C9901C },
  { label: '- Armads', value: 0x8C99028 },
  { label: '- Aureola', value: 0x8C99034 },
  { label: '- Dragon Stone', value: 0x8C9904C },
  { label: '- Forblaze (+5 Luck)', value: 0x8C98F98 },
  { label: '- +10 Luck', value: 0x8FFF2A0 },
  { label: '- Custom', value: 0x8FFF2A8 },
  { label: '- Custom', value: 0x8FFF2B0 },
  { label: '- Custom', value: 0x8FFF2B8 },
  { label: '- Custom', value: 0x8FFF2C0 },
  { label: '- Custom', value: 0x8FFF2C8 },
  { label: '- Custom', value: 0x8FFF2D0 },
  { label: '- Custom', value: 0x8FFF2D8 },
  { label: '- Custom', value: 0x8FFF2E0 },
  { label: '- Custom', value: 0x8FFF2E8 },
  { label: '- Custom', value: 0x8FFF2F0 },
  { label: '- Custom', value: 0x8FFF2F8 },
  { label: '- Custom', value: 0x8FFF300 },
  { label: '- Custom', value: 0x8FFF308 },
  { label: '- Custom', value: 0x8FFF310 },
  { label: '- Custom', value: 0x8FFF318 },
  { label: '- Custom', value: 0x8FFF320 },
  { label: '- Custom', value: 0x8FFF328 },
  { label: '- Custom', value: 0x8FFF330 },
  { label: '- Custom', value: 0x8FFF338 },
  { label: '- Custom', value: 0x8FFF340 },
  { label: '- Custom', value: 0x8FFF348 },
  { label: '- Custom', value: 0x8FFF350 },
  { label: '- Custom', value: 0x8FFF358 },
  { label: '- Custom', value: 0x8FFF360 },
  { label: '- Custom', value: 0x8FFF368 },
  { label: '- Custom', value: 0x8FFF370 },
  { label: '- Custom', value: 0x8FFF378 },
  { label: '- Custom', value: 0x8FFF380 },
  { label: '- Custom', value: 0x8FFF388 },
];

export const EffectivenessPointers = [
  { label: '- No effectiveness', value: 0x00 },
  { label: '- Knight/Cavalry', value: 0x8C97E9C },
  { label: '- Knights', value: 0x8C97E96 },
  { label: '- Dragons', value: 0x8C97EC5 },
  { label: '- Cavalry', value: 0x8C97EB7 },
  { label: '- Myrmidons', value: 0x8C97EAD },
  { label: '- All fliers', value: 0x8C97ED2 },
  { label: '- Dragons', value: 0x8C97EC5 },
  { label: '- Custom(all magic)', value: 0x8FFFA00 },
  { label: '- Custom', value: 0x8FFFA20 },
  { label: '- Custom', value: 0x8FFFA40 },
  { label: '- Custom', value: 0x8FFFA60 },
  { label: '- Custom', value: 0x8FFFA80 },
  { label: '- Custom', value: 0x8FFFAA0 },
  { label: '- Custom', value: 0x8FFFAC0 },
  { label: '- Custom', value: 0x8FFFAE0 },
  { label: '- Custom', value: 0x8FFFB00 },
  { label: '- Custom', value: 0x8FFFB20 },
  { label: '- Custom', value: 0x8FFFB40 },
  { label: '- Custom', value: 0x8FFFB60 },
  { label: '- Custom', value: 0x8FFFB80 },
  { label: '- Custom', value: 0x8FFFBA0 },
  { label: '- Custom', value: 0x8FFFBC0 },
  { label: '- Custom', value: 0x8FFFBE0 },
];

export const WeaponRank = [
  { label: 'None', value: 0x00 },
  { label: 'E', value: 0x01 },
  { label: 'D', value: 0x1F },
  { label: 'C', value: 0x47 },
  { label: 'B', value: 0x79 },
  { label: 'A', value: 0xB5 },
  { label: 'S', value: 0xFB },
];

export const ItemIcons = [
  { label: '- Iron Sword', value: 0x00 },
  { label: '- Slim Sword', value: 0x01 },
  { label: '- Steel Sword', value: 0x02 },
  { label: '- Silver Sword', value: 0x03 },
  { label: '- Iron Blade', value: 0x04 },
  { label: '- Steel Blade', value: 0x05 },
  { label: '- Silver Blade', value: 0x06 },
  { label: '- Poison Sword', value: 0x07 },
  { label: '- Rapier', value: 0x08 },
  { label: '- Mani Katti', value: 0x09 },
  { label: '- Hero Sword', value: 0x0A },
  { label: '- Wo Dao', value: 0x0B },
  { label: '- Killing Edge', value: 0x0C },
  { label: '- Armorcutter', value: 0x0D },
  { label: '- Wyrmslayer', value: 0x0E },
  { label: '- Light Brand', value: 0x0F },
  { label: '- Runesword', value: 0x10 },
  { label: '- Lancereaver', value: 0x11 },
  { label: '- Zanbato', value: 0x12 },
  { label: '- Iron Lance', value: 0x13 },
  { label: '- Slim Lance', value: 0x14 },
  { label: '- Steel Lance', value: 0x15 },
  { label: '- Silver Lance', value: 0x16 },
  { label: '- Poison Lance', value: 0x17 },
  { label: '- Hero Lance', value: 0x18 },
  { label: '- Killer Lance', value: 0x19 },
  { label: '- Horseslayer', value: 0x1A },
  { label: '- Javelin', value: 0x1B },
  { label: '- Spear', value: 0x1C },
  { label: '- Axereaver', value: 0x1D },
  { label: '- Iron Axe', value: 0x1E },
  { label: '- Steel Axe', value: 0x1F },
  { label: '- Silver Axe', value: 0x20 },
  { label: '- Poison Axe', value: 0x21 },
  { label: '- Hero Axe', value: 0x22 },
  { label: '- Killer Axe', value: 0x23 },
  { label: '- Halberd', value: 0x24 },
  { label: '- Hammer', value: 0x25 },
  { label: '- Devil Axe', value: 0x26 },
  { label: '- Hand Axe', value: 0x27 },
  { label: '- Tomahawk', value: 0x28 },
  { label: '- Swordreaver', value: 0x29 },
  { label: '- Swordslayer', value: 0x2A },
  { label: '- Iron Bow', value: 0x2B },
  { label: '- Steel Bow', value: 0x2C },
  { label: '- Silver Bow', value: 0x2D },
  { label: '- Poison Bow', value: 0x2E },
  { label: '- Killer Bow', value: 0x2F },
  { label: '- Hero Bow', value: 0x30 },
  { label: '- Shortbow', value: 0x31 },
  { label: '- Longbow', value: 0x32 },
  { label: '- Ballista', value: 0x33 },
  { label: '- Iron Ballista', value: 0x34 },
  { label: '- Killer Ballista', value: 0x35 },
  { label: '- Fire', value: 0x36 },
  { label: '- Thunder', value: 0x37 },
  { label: '- Elfire', value: 0x38 },
  { label: '- Bolting', value: 0x39 },
  { label: '- Fimbulvetr', value: 0x3A },
  { label: '- Forblaze', value: 0x3B },
  { label: '- Excalibur', value: 0x3C },
  { label: '- Lightning', value: 0x3D },
  { label: '- Shine', value: 0x3E },
  { label: '- Divine', value: 0x3F },
  { label: '- Purge', value: 0x40 },
  { label: '- Aura', value: 0x41 },
  { label: '- Luce', value: 0x42 },
  { label: '- Flux', value: 0x43 },
  { label: '- Luna', value: 0x44 },
  { label: '- Nosferatu', value: 0x45 },
  { label: '- Eclipse', value: 0x46 },
  { label: '- Fenrir', value: 0x47 },
  { label: '- Gespnest', value: 0x48 },
  { label: '- Heal', value: 0x49 },
  { label: '- Mend', value: 0x4A },
  { label: '- Recover', value: 0x4B },
  { label: '- Libro', value: 0x4C },
  { label: '- Reserve', value: 0x4D },
  { label: '- Restore', value: 0x4E },
  { label: '- Silence', value: 0x4F },
  { label: '- Sleep', value: 0x50 },
  { label: '- Berserk', value: 0x51 },
  { label: '- Warp', value: 0x52 },
  { label: '- Rescue', value: 0x53 },
  { label: '- Torch', value: 0x54 },
  { label: '- Hammerne', value: 0x55 },
  { label: '- Unlock', value: 0x56 },
  { label: '- Barrier', value: 0x57 },
  { label: '- Dragon Axe', value: 0x58 },
  { label: '- Angelic Robe', value: 0x59 },
  { label: '- Energy Ring', value: 0x5A },
  { label: '- Secret Book', value: 0x5B },
  { label: '- Speedwings', value: 0x5C },
  { label: '- Goddess Icon', value: 0x5D },
  { label: '- Dragonshield', value: 0x5E },
  { label: '- Talisman', value: 0x5F },
  { label: '- Boots', value: 0x60 },
  { label: '- Body Ring', value: 0x61 },
  { label: '- Hero\'s Crest', value: 0x62 },
  { label: '- Knight\'s Crest', value: 0x63 },
  { label: '- Orion\'s Bolt', value: 0x64 },
  { label: '- Elysian Whip', value: 0x65 },
  { label: '- Guiding Ring', value: 0x66 },
  { label: '- Chest Key', value: 0x67 },
  { label: '- Door Key', value: 0x68 },
  { label: '- Lockpick', value: 0x69 },
  { label: '- Vulnerary', value: 0x6A },
  { label: '- Elixir', value: 0x6B },
  { label: '- Pure Water', value: 0x6C },
  { label: '- Antitoxin', value: 0x6D },
  { label: '- Torch', value: 0x6E },
  { label: '- Delphi Shield', value: 0x6F },
  { label: '- Sword Icon', value: 0x70 },
  { label: '- Lance Icon', value: 0x71 },
  { label: '- Axe Icon', value: 0x72 },
  { label: '- Bow Icon', value: 0x73 },
  { label: '- Staff Icon', value: 0x74 },
  { label: '- Anima Icon', value: 0x75 },
  { label: '- Light Icon', value: 0x76 },
  { label: '- Dark Icon', value: 0x77 },
  { label: '- Exaccus', value: 0x78 },
  { label: '- Dark Breath', value: 0x79 },
  { label: '- Fire Icon', value: 0x7A },
  { label: '- Thunder Icon', value: 0x7B },
  { label: '- Wind Icon', value: 0x7C },
  { label: '- Ice Icon', value: 0x7D },
  { label: '- Dark Icon (Affinity)', value: 0x7E },
  { label: '- Light Icon (Affinity)', value: 0x7F },
  { label: '- Anima Icon (Affinity)', value: 0x80 },
  { label: '- Horse Icon', value: 0x81 },
  { label: '- Pegasus Icon', value: 0x82 },
  { label: '- Wyvern Icon', value: 0x83 },
  { label: '- Member Card', value: 0x84 },
  { label: '- Silver Card', value: 0x85 },
  { label: '- White Gem', value: 0x86 },
  { label: '- Blue Gem', value: 0x87 },
  { label: '- Red Gem', value: 0x88 },
  { label: '- Gold', value: 0x89 },
  { label: '- Spear', value: 0x8A },
  { label: '- Chest Key', value: 0x8B },
  { label: '- Mine', value: 0x8C },
  { label: '- Light Rune', value: 0x8D },
  { label: '- Iron Rune', value: 0x8E },
  { label: '- Fila\'s Might', value: 0x8F },
  { label: '- Ninis\' Grace', value: 0x90 },
  { label: '- Thor\'s Ire', value: 0x91 },
  { label: '- Set\'s Linity', value: 0x92 },
  { label: '- Emblem Sword', value: 0x93 },
  { label: '- Emblem Lance', value: 0x94 },
  { label: '- Emblem Axe', value: 0x95 },
  { label: '- Emblem Bow', value: 0x96 },
  { label: '- Durandal', value: 0x97 },
  { label: '- Armads', value: 0x98 },
  { label: '- Aureola', value: 0x99 },
  { label: '- Earth Seal', value: 0x9A },
  { label: '- Afa\'s Drops', value: 0x9B },
  { label: '- Heaven Seal', value: 0x9C },
  { label: '- Emblem Seal', value: 0x9D },
  { label: '- Fell Contract', value: 0x9E },
  { label: '- Sol Katti', value: 0x9F },
  { label: '- Wolf Beil', value: 0xA0 },
  { label: '- Ereshkigal', value: 0xA1 },
  { label: '- Dragon Stone', value: 0xA2 },
  { label: '- Regal Blade', value: 0xA3 },
  { label: '- Rex Hasta', value: 0xA4 },
  { label: '- Basilikos', value: 0xA5 },
  { label: '- Reinfleche', value: 0xA6 },
  { label: '- Heavy Spear', value: 0xA7 },
  { label: '- Short Spear', value: 0xA8 },
  { label: '- Ocean Seal', value: 0xA9 },
  { label: '- Wind Sword', value: 0xAA },
  { label: '- Green Musical Note', value: 0xAB },
  { label: '- Red Musical Note', value: 0xAC },
  { label: '- No Icon', value: 0xAD },
];

export const Staffuseeffect = [
  { label: 'None', value: 0x00 },
  { label: 'Heal', value: 0x01 },
  { label: 'Mend', value: 0x02 },
  { label: 'Recover', value: 0x03 },
  { label: 'Physic', value: 0x04 },
  { label: 'Fortify', value: 0x05 },
  { label: 'Restore', value: 0x06 },
  { label: 'Silence', value: 0x07 },
  { label: 'Sleep', value: 0x08 },
  { label: 'Berserk', value: 0x09 },
  { label: 'Warp', value: 0x0A },
  { label: 'Rescue', value: 0x0B },
  { label: 'Torch', value: 0x0C },
  { label: 'Hammerne', value: 0x0D },
  { label: 'Unlock', value: 0x0E },
  { label: 'Barrier', value: 0x0F },
  { label: 'Angelic robe', value: 0x10 },
  { label: 'Energy ring', value: 0x11 },
  { label: 'Secret book', value: 0x12 },
  { label: 'Speedwing', value: 0x13 },
  { label: 'Goddes Icon', value: 0x14 },
  { label: 'Dragonshield', value: 0x15 },
  { label: 'Talisman', value: 0x16 },
  { label: 'Boots', value: 0x17 },
  { label: 'Body Ring', value: 0x18 },
  { label: 'Hero\'s Crest', value: 0x19 },
  { label: 'Knight\'s Crest', value: 0x1A },
  { label: 'Orion\'s Bolt', value: 0x1B },
  { label: 'Elysian Whip', value: 0x1C },
  { label: 'Guiding ring', value: 0x1D },
  { label: 'Chest Key', value: 0x1E },
  { label: 'Door key', value: 0x1F },
  { label: 'Lockpick', value: 0x20 },
  { label: 'Vulnerary', value: 0x21 },
  { label: 'Elixir', value: 0x22 },
  { label: 'Pure Water', value: 0x23 },
  { label: 'Antitoxin', value: 0x24 },
  { label: 'Torch', value: 0x25 },
  { label: 'Chest Key(5)', value: 0x26 },
  { label: 'Mine', value: 0x27 },
  { label: 'Light Rune', value: 0x28 },
  { label: 'Iron Rune', value: 0x29 },
  { label: 'Fila\'s Might', value: 0x2A },
  { label: 'Ninis\' Grace', value: 0x2B },
  { label: 'Thor\'s Ire', value: 0x2C },
  { label: 'Set\'s Litany', value: 0x2D },
  { label: 'Earth Seal', value: 0x2E },
  { label: 'Afa\'s Drops', value: 0x2F },
  { label: 'Heaven Seal', value: 0x30 },
  { label: 'Fell Contract', value: 0x31 },
  { label: 'Ocean Seal', value: 0x32 },
];

export const WeaponEffect = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Poison', value: 0x01 },
  { label: 'Steals HP', value: 0x02 },
  { label: 'Halves HP', value: 0x03 },
  { label: 'Devil Reversal', value: 0x04 },
];
