export const FE7ClassEditor = [
  { label: 'None', value: 0 },
  { label: 'Eliwood Lord', value: 1 },
  { label: 'Lyn Lord', value: 2 },
  { label: 'Hector Lord', value: 3 },
  { label: 'Eliwood Lord Knight (only by class name)', value: 4 },
  { label: 'Lyn Blade Lord (only by class name)', value: 5 },
  { label: 'Hector Great Lord (only by class name)', value: 6 },
  { label: 'Eliwood Lord Knight', value: 7 },
  { label: 'Lyn Blade Lord', value: 8 },
  { label: 'Hector Great Lord', value: 9 },
  { label: 'Mercenary', value: 10 },
  { label: 'Mercenary (F)', value: 11 },
  { label: 'Hero', value: 12 },
  { label: 'Hero (F)', value: 13 },
  { label: 'Myrmidon', value: 14 },
  { label: 'Myrmidon (F)', value: 15 },
  { label: 'Swordmaster', value: 16 },
  { label: 'Swordmaster (F)', value: 17 },
  { label: 'Fighter', value: 18 },
  { label: 'Warrior', value: 19 },
  { label: 'Knight', value: 20 },
  { label: 'Knight (F)', value: 21 },
  { label: 'General', value: 22 },
  { label: 'General (F)', value: 23 },
  { label: 'Archer', value: 24 },
  { label: 'Archer (F)', value: 25 },
  { label: 'Sniper', value: 26 },
  { label: 'Sniper (F)', value: 27 },
  { label: 'Monk', value: 28 },
  { label: 'Cleric', value: 29 },
  { label: 'Bishop', value: 30 },
  { label: 'Bishop (F)', value: 31 },
  { label: 'Mage', value: 32 },
  { label: 'Mage (F)', value: 33 },
  { label: 'Sage', value: 34 },
  { label: 'Sage (F)', value: 35 },
  { label: 'Shaman', value: 36 },
  { label: 'Shaman (F)', value: 37 },
  { label: 'Druid', value: 38 },
  { label: 'Druid (F)', value: 39 },
  { label: 'Cavalier', value: 40 },
  { label: 'Cavalier (F)', value: 41 },
  { label: 'Paladin', value: 42 },
  { label: 'Paladin (F)', value: 43 },
  { label: 'Troubadour', value: 44 },
  { label: 'Valkyrie', value: 45 },
  { label: 'Nomad', value: 46 },
  { label: 'Nomad (F)', value: 47 },
  { label: 'Nomad Trooper', value: 48 },
  { label: 'Nomad Trooper (F)', value: 49 },
  { label: 'Pegasus Knight', value: 50 },
  { label: 'Falcon Knight', value: 51 },
  { label: 'Wywern Knight', value: 52 },
  { label: 'Wywern Knight (F)', value: 53 },
  { label: 'Wywern Lord', value: 54 },
  { label: 'Wywern Lord (F)', value: 55 },
  { label: 'Soldier', value: 56 },
  { label: 'Brigand', value: 57 },
  { label: 'Pirate', value: 58 },
  { label: 'Berserker', value: 59 },
  { label: 'Thief', value: 60 },
  { label: 'Thief (F)', value: 61 },
  { label: 'Assassin', value: 62 },
  { label: 'Civilian', value: 63 },
  { label: 'Dancer', value: 64 },
  { label: 'Bard', value: 65 },
  { label: 'Archsage', value: 66 },
  { label: 'Magic Seal', value: 67 },
  { label: 'Transporter Tent', value: 68 },
  { label: 'Dark Druid', value: 69 },
  { label: 'Fire Dragon', value: 70 },
  { label: 'Civilian', value: 71 },
  { label: 'Civilian (F)', value: 72 },
  { label: 'Child', value: 73 },
  { label: 'Brammimond', value: 74 },
  { label: 'Peer', value: 75 },
  { label: 'Peer (F)', value: 76 },
  { label: 'Prince', value: 77 },
  { label: 'Queen', value: 78 },
  { label: 'Hung Leila', value: 79 },
  { label: 'Corsair', value: 80 },
  { label: 'Prince (Tactician)', value: 81 },
  { label: 'Fallen Prince', value: 82 },
  { label: 'Prince facing upward', value: 83 },
  { label: 'Fallen Ninian', value: 84 },
  { label: 'Fallen Ice Dragon', value: 85 },
  { label: 'Fallen Warrior', value: 86 },
  { label: 'Child', value: 87 },
  { label: 'Child (F)', value: 88 },
  { label: 'Transporter w/ Horse', value: 89 },
  { label: 'Uber Sage', value: 90 },
  { label: 'Archer in Ballista', value: 91 },
  { label: 'Archer in Iron Ballista', value: 92 },
  { label: 'Archer in Killer Ballista', value: 93 },
  { label: 'Empty Ballista', value: 94 },
  { label: 'Empty Iron Ballista', value: 95 },
  { label: 'Empty Killer Ballista', value: 96 },
  { label: 'Empty (Make a custom class!)', value: 97 },
  { label: 'Empty (Make a custom class!)', value: 98 },
  { label: 'Empty (Make a custom class!)', value: 99 },
  { label: 'Empty (Make a custom class!)', value: 100 },
];

export const ClassList = [
  { label: 'None', value: 0x00 },
  { label: 'Eliwood Lord', value: 0x01 },
  { label: 'Lyn Lord', value: 0x02 },
  { label: 'Hector Lord', value: 0x03 },
  { label: 'Eliwood Lord Knight (only by class name)', value: 0x04 },
  { label: 'Lyn Blade Lord (only by class name)', value: 0x05 },
  { label: 'Hector Great Lord (only by class name)', value: 0x06 },
  { label: 'Eliwood Lord Knight', value: 0x07 },
  { label: 'Lyn Blade Lord', value: 0x08 },
  { label: 'Hector Great Lord', value: 0x09 },
  { label: 'Mercenary', value: 0x0A },
  { label: 'Mercenary', value: 0x0B },
  { label: 'Hero', value: 0x0C },
  { label: 'Hero', value: 0x0D },
  { label: 'Myrmidon', value: 0x0E },
  { label: 'Myrmidon', value: 0x0F },
  { label: 'Swordmaster', value: 0x10 },
  { label: 'Swordmaster', value: 0x11 },
  { label: 'Fighter', value: 0x12 },
  { label: 'Warrior', value: 0x13 },
  { label: 'Knight', value: 0x14 },
  { label: 'Knight', value: 0x15 },
  { label: 'General', value: 0x16 },
  { label: 'General', value: 0x17 },
  { label: 'Archer', value: 0x18 },
  { label: 'Archer', value: 0x19 },
  { label: 'Sniper', value: 0x1A },
  { label: 'Sniper', value: 0x1B },
  { label: 'Monk', value: 0x1C },
  { label: 'Cleric', value: 0x1D },
  { label: 'Bishop', value: 0x1E },
  { label: 'Bishop', value: 0x1F },
  { label: 'Mage', value: 0x20 },
  { label: 'Mage', value: 0x21 },
  { label: 'Sage', value: 0x22 },
  { label: 'Sage', value: 0x23 },
  { label: 'Shaman', value: 0x24 },
  { label: 'Shaman', value: 0x25 },
  { label: 'Druid', value: 0x26 },
  { label: 'Druid', value: 0x27 },
  { label: 'Cavalier', value: 0x28 },
  { label: 'Cavalier', value: 0x29 },
  { label: 'Paladin', value: 0x2A },
  { label: 'Paladin', value: 0x2B },
  { label: 'Troubadour', value: 0x2C },
  { label: 'Valkyrie', value: 0x2D },
  { label: 'Nomad', value: 0x2E },
  { label: 'Nomad', value: 0x2F },
  { label: 'Nomad Trooper', value: 0x30 },
  { label: 'Nomad Trooper', value: 0x31 },
  { label: 'Pegasus Knight', value: 0x32 },
  { label: 'Falcon Knight', value: 0x33 },
  { label: 'Wyvern Knight', value: 0x34 },
  { label: 'Wyvern Knight', value: 0x35 },
  { label: 'Wyvern Lord', value: 0x36 },
  { label: 'Wyvern Lord', value: 0x37 },
  { label: 'Soldier', value: 0x38 },
  { label: 'Bandit', value: 0x39 },
  { label: 'Pirate', value: 0x3A },
  { label: 'Berserker', value: 0x3B },
  { label: 'Thief', value: 0x3C },
  { label: 'Thief', value: 0x3D },
  { label: 'Assassin', value: 0x3E },
  { label: 'Civilian', value: 0x3F },
  { label: 'Dancer', value: 0x40 },
  { label: 'Bard', value: 0x41 },
  { label: 'Archsage', value: 0x42 },
  { label: 'Magic Seal', value: 0x43 },
  { label: 'Transporter', value: 0x44 },
  { label: 'Transporter', value: 0x45 },
  { label: 'Fire Dragon', value: 0x46 },
  { label: 'Civilian', value: 0x47 },
  { label: 'Civilian (F)', value: 0x48 },
  { label: 'Child', value: 0x49 },
  { label: 'Brammimond', value: 0x4A },
  { label: 'Peer', value: 0x4B },
  { label: 'Peer (F)', value: 0x4C },
  { label: 'Prince', value: 0x4D },
  { label: 'Queen', value: 0x4E },
  { label: 'Hung Leila', value: 0x4F },
  { label: 'Corsair', value: 0x50 },
  { label: 'Prince (Tactician)', value: 0x51 },
  { label: 'Fallen Prince', value: 0x52 },
  { label: 'Prince facing upward', value: 0x53 },
  { label: 'Fallen Ninian', value: 0x54 },
  { label: 'Fallen Ice Dragon', value: 0x55 },
  { label: 'Fallen Warrior', value: 0x56 },
  { label: 'Child', value: 0x57 },
  { label: 'Child (F)', value: 0x58 },
  { label: 'Transporter w/ Horse', value: 0x59 },
  { label: 'Uber Sage', value: 0x5A },
  { label: 'Archer in Ballista', value: 0x5B },
  { label: 'Archer in Iron Ballista', value: 0x5C },
  { label: 'Archer in Killer Ballista', value: 0x5D },
  { label: 'Empty Ballista', value: 0x5E },
  { label: 'Empty Iron Ballista', value: 0x5F },
  { label: 'Empty Killer Ballista', value: 0x60 },
  { label: 'Empty (Make a custom class!)', value: 0x61 },
  { label: 'Empty (Make a custom class!)', value: 0x62 },
  { label: 'Empty (Make a custom class!)', value: 0x63 },
];

export const MapSpritesStanding = [
  { label: '- Eliwood Lord', value: 0x00 },
  { label: '- Lyn Lord', value: 0x01 },
  { label: '- Hector Lord', value: 0x02 },
  { label: '- Knight Lord', value: 0x03 },
  { label: '- Blade Lord', value: 0x04 },
  { label: '- Great Lord', value: 0x05 },
  { label: '- Mercenary', value: 0x06 },
  { label: '- Mercenary (F)', value: 0x07 },
  { label: '- Hero', value: 0x08 },
  { label: '- Hero (F)', value: 0x09 },
  { label: '- Myrmidon', value: 0x0A },
  { label: '- Myrmidon (F)', value: 0x0B },
  { label: '- Swordmaster', value: 0x0C },
  { label: '- Swordmaster (F)', value: 0x0D },
  { label: '- Fighter', value: 0x0E },
  { label: '- Warrior', value: 0x0F },
  { label: '- Knight', value: 0x10 },
  { label: '- General', value: 0x11 },
  { label: '- Archer', value: 0x12 },
  { label: '- Archer (F)', value: 0x13 },
  { label: '- Sniper', value: 0x14 },
  { label: '- Sniper (F)', value: 0x15 },
  { label: '- Monk', value: 0x16 },
  { label: '- Cleric', value: 0x17 },
  { label: '- Bishop', value: 0x18 },
  { label: '- Bishop (F)', value: 0x19 },
  { label: '- Mage', value: 0x1A },
  { label: '- Mage (F)', value: 0x1B },
  { label: '- Sage', value: 0x1C },
  { label: '- Sage (F)', value: 0x1D },
  { label: '- Shaman', value: 0x1E },
  { label: '- Shaman (F)', value: 0x1F },
  { label: '- Druid', value: 0x20 },
  { label: '- Druid (F)', value: 0x21 },
  { label: '- Cavalier', value: 0x22 },
  { label: '- Paladin', value: 0x23 },
  { label: '- Troubador', value: 0x24 },
  { label: '- Valkyrie', value: 0x25 },
  { label: '- Nomad', value: 0x26 },
  { label: '- Nomad (F)', value: 0x27 },
  { label: '- Nomad Trooper', value: 0x28 },
  { label: '- Nomad Trooper (F)', value: 0x29 },
  { label: '- Pegasus Knight', value: 0x2A },
  { label: '- Falco Knight', value: 0x2B },
  { label: '- Wyvern Rider', value: 0x2C },
  { label: '- Wyvern Lord', value: 0x2D },
  { label: '- Soldier', value: 0x2E },
  { label: '- Brigand', value: 0x2F },
  { label: '- Pirate', value: 0x30 },
  { label: '- Berserker', value: 0x31 },
  { label: '- Thief', value: 0x32 },
  { label: '- Thief (Leila)', value: 0x33 },
  { label: '- Assassin', value: 0x34 },
  { label: '- Civilian', value: 0x35 },
  { label: '- Dancer', value: 0x36 },
  { label: '- Bard', value: 0x37 },
  { label: '- Archsage', value: 0x38 },
  { label: '- Magic Seal', value: 0x39 },
  { label: '- Transporter (Tent)', value: 0x3A },
  { label: '- Dark Druid', value: 0x3B },
  { label: '- Fire Dragon', value: 0x3C },
  { label: '- Civilian', value: 0x3D },
  { label: '- Civilian', value: 0x3E },
  { label: '- Child', value: 0x3F },
  { label: '- Brammimond', value: 0x40 },
  { label: '- Peer', value: 0x41 },
  { label: '- Peer (F)', value: 0x42 },
  { label: '- Prince', value: 0x43 },
  { label: '- Queen', value: 0x44 },
  { label: '- Unknown', value: 0x45 },
  { label: '- Tactician', value: 0x46 },
  { label: '- Fallen Prince', value: 0x47 },
  { label: '- Prince facing upwards', value: 0x48 },
  { label: '- Fallen Ninian', value: 0x49 },
  { label: '- Ice Dragon', value: 0x4A },
  { label: '- Fallen Warrior', value: 0x4B },
  { label: '- Child', value: 0x4C },
  { label: '- Child (F)', value: 0x4D },
  { label: '- Transporter (Wagon)', value: 0x4E },
  { label: '- Archer in Ballista', value: 0x4F },
  { label: '- Acher in Iron Ballista', value: 0x50 },
  { label: '- Archer in Killer Ballista', value: 0x51 },
  { label: '- Empty Ballista', value: 0x52 },
  { label: '- Empty Iron Ballista', value: 0x53 },
  { label: '- Empty Killer Ballista', value: 0x54 },
  { label: '- None', value: 0x55 },
];

export const WalkingSpeed = [
  { label: 'Normal', value: 0x00 },
  { label: 'Slow', value: 0x01 },
];

export const PortraitList = [
  { label: 'No portrait/Generic enemy', value: 0x00 },
  { label: 'Question mark circle on a shadowed box', value: 0x01 },
  { label: 'Eliwood', value: 0x02 },
  { label: 'Angry Eliwood', value: 0x03 },
  { label: 'Sad Eliwood', value: 0x04 },
  { label: 'Eliwood dressed as a commoner', value: 0x05 },
  { label: 'Eliwood (Looking at you)', value: 0x06 },
  { label: 'Eliwood dressed as a commoner (Looking at you)', value: 0x07 },
  { label: 'Eliwood in noble clothing', value: 0x08 },
  { label: 'Happy Eliwood in noble clothing', value: 0x09 },
  { label: 'Happy Eliwood', value: 0x0A },
  { label: 'Old Eliwood', value: 0x0B },
  { label: 'Hector', value: 0x0C },
  { label: 'Angry Hector', value: 0x0D },
  { label: 'Sad Hector', value: 0x0E },
  { label: 'Hector dressed as a commoner', value: 0x0F },
  { label: 'Hector dressed as a commoner (Looking at you)', value: 0x10 },
  { label: 'Angry Hector dressed as a commoner', value: 0x11 },
  { label: 'Hector in noble clothing', value: 0x12 },
  { label: 'Hector in noble clothing (Looking at you)', value: 0x13 },
  { label: 'Hector (Looking at you)', value: 0x14 },
  { label: 'Old Hector (beard included)', value: 0x15 },
  { label: 'Lyn', value: 0x16 },
  { label: 'Lyn in deep thought', value: 0x17 },
  { label: 'Sad Lyn', value: 0x18 },
  { label: 'Lyn dressed as a commoner', value: 0x19 },
  { label: 'Lyn (Looking at you)', value: 0x1A },
  { label: 'Athos', value: 0x1B },
  { label: 'Ninian', value: 0x1C },
  { label: 'Possessed Ninian', value: 0x1D },
  { label: 'Sad Ninian', value: 0x1E },
  { label: 'Hawkeye', value: 0x1F },
  { label: 'Matthew', value: 0x20 },
  { label: 'Jaffar', value: 0x21 },
  { label: 'Angry Jaffar', value: 0x22 },
  { label: 'Raven', value: 0x23 },
  { label: 'Geitz', value: 0x24 },
  { label: 'Legault', value: 0x25 },
  { label: 'Karel', value: 0x26 },
  { label: 'Dorcas', value: 0x27 },
  { label: 'Bartre', value: 0x28 },
  { label: 'Oswin', value: 0x29 },
  { label: 'Dart', value: 0x2A },
  { label: 'Wil', value: 0x2B },
  { label: 'Guy', value: 0x2C },
  { label: 'Karla', value: 0x2D },
  { label: 'Rath', value: 0x2E },
  { label: 'Kent', value: 0x2F },
  { label: 'Sain', value: 0x30 },
  { label: 'Lowen', value: 0x31 },
  { label: 'Marcus', value: 0x32 },
  { label: 'Florina', value: 0x33 },
  { label: 'Shy Florina', value: 0x34 },
  { label: 'Fiora', value: 0x35 },
  { label: 'Heath', value: 0x36 },
  { label: 'Vaida', value: 0x37 },
  { label: 'Erk', value: 0x38 },
  { label: 'Nino', value: 0x39 },
  { label: 'Pent', value: 0x3A },
  { label: 'Louise', value: 0x3B },
  { label: 'Canas', value: 0x3C },
  { label: 'Lucius', value: 0x3D },
  { label: 'Serra', value: 0x3E },
  { label: 'Priscilla', value: 0x3F },
  { label: 'Farina', value: 0x40 },
  { label: 'Nils', value: 0x41 },
  { label: 'Sad Nils', value: 0x42 },
  { label: 'Possessed Nils', value: 0x43 },
  { label: 'Nils deep in thought', value: 0x44 },
  { label: 'Renault', value: 0x45 },
  { label: 'Isadora', value: 0x46 },
  { label: 'Harken', value: 0x47 },
  { label: 'Rebecca', value: 0x48 },
  { label: 'Wallace', value: 0x49 },
  { label: 'Merlinus', value: 0x4A },
  { label: 'Hannah (Old fortune teller)', value: 0x4B },
  { label: 'Elenora', value: 0x4C },
  { label: 'Serious Elenora', value: 0x4D },
  { label: 'Uther', value: 0x4E },
  { label: 'Elbert', value: 0x4F },
  { label: 'Fargus', value: 0x50 },
  { label: 'Zephiel', value: 0x51 },
  { label: 'Guinevere', value: 0x52 },
  { label: 'Desmond', value: 0x53 },
  { label: 'Hellene', value: 0x54 },
  { label: 'Happy Hellene', value: 0x55 },
  { label: 'Murdock', value: 0x56 },
  { label: 'Leila', value: 0x57 },
  { label: 'Leila looking down with her eyes closed', value: 0x58 },
  { label: 'Hausen (Lyn\'s grandfather)', value: 0x59 },
  { label: 'Jan', value: 0x5A },
  { label: 'Natalie', value: 0x5B },
  { label: 'Bramimond', value: 0x5C },
  { label: 'Roland', value: 0x5D },
  { label: 'Durban', value: 0x5E },
  { label: 'Evil-faced Nergal (masked)', value: 0x5F },
  { label: 'Evil-faced Nergal #2 (masked)', value: 0x60 },
  { label: 'Nergal (Generic/unmasked)', value: 0x61 },
  { label: 'Eil Nergal (unmasked)', value: 0x62 },
  { label: 'Sonia', value: 0x63 },
  { label: 'Brendan', value: 0x64 },
  { label: 'Lloyd', value: 0x65 },
  { label: 'Linus', value: 0x66 },
  { label: 'Limstella', value: 0x67 },
  { label: 'Ephidel', value: 0x68 },
  { label: 'Ephidel (hooded)', value: 0x69 },
  { label: 'Darin', value: 0x6A },
  { label: 'Erik', value: 0x6B },
  { label: 'Helman', value: 0x6C },
  { label: 'Marquess Araphen', value: 0x6D },
  { label: 'Groznyi', value: 0x6E },
  { label: 'Wire', value: 0x6F },
  { label: 'Zagan', value: 0x70 },
  { label: 'Boies', value: 0x71 },
  { label: 'Sealen', value: 0x72 },
  { label: 'Bauker', value: 0x73 },
  { label: 'Bernard', value: 0x74 },
  { label: 'Damian', value: 0x75 },
  { label: 'Zoldam', value: 0x76 },
  { label: 'Uhai', value: 0x77 },
  { label: 'Aion', value: 0x78 },
  { label: 'Georg', value: 0x79 },
  { label: 'Cameron', value: 0x7A },
  { label: 'Oleg', value: 0x7B },
  { label: 'Eubans', value: 0x7C },
  { label: 'Kishuna', value: 0x7D },
  { label: 'Paul', value: 0x7E },
  { label: 'Jasmine', value: 0x7F },
  { label: 'Pascal', value: 0x80 },
  { label: 'Kenneth', value: 0x81 },
  { label: 'Jerme', value: 0x82 },
  { label: 'Maxime', value: 0x83 },
  { label: 'Ursula', value: 0x84 },
  { label: 'Teodor', value: 0x85 },
  { label: 'Denning', value: 0x86 },
  { label: 'Kaim', value: 0x87 },
  { label: 'Batta', value: 0x88 },
  { label: 'Zugu', value: 0x89 },
  { label: 'Glass', value: 0x8A },
  { label: 'Migal', value: 0x8B },
  { label: 'Carjiga', value: 0x8C },
  { label: 'Bug', value: 0x8D },
  { label: 'Puzon', value: 0x8E },
  { label: 'Bool', value: 0x8F },
  { label: 'Heintz', value: 0x90 },
  { label: 'Beyard', value: 0x91 },
  { label: 'Yogi', value: 0x92 },
  { label: 'Eagler', value: 0x93 },
  { label: 'Lundgren', value: 0x94 },
  { label: 'Unlisted (Looks like a blue haired generic mercenary boss)', value: 0x95 },
  { label: 'Lloyd (Morph)', value: 0x96 },
  { label: 'Linus (Morph)', value: 0x97 },
  { label: 'Brendan (Morph)', value: 0x98 },
  { label: 'Uhai (Morph)', value: 0x99 },
  { label: 'Ursula (Morph)', value: 0x9A },
  { label: 'Kenneth (Morph)', value: 0x9B },
  { label: 'Darin (Morph)', value: 0x9C },
  { label: 'Jerme (Morph)', value: 0x9D },
  { label: 'Roy (Young)', value: 0x9E },
  { label: 'Lilina (Young)', value: 0x9F },
  { label: 'Fa', value: 0xA0 },
  { label: 'Sophia', value: 0xA1 },
  { label: 'Bishop that gives Lyn the Mani Katti', value: 0xA2 },
  { label: 'Caelin servant that talks to you at the end of chapter 10', value: 0xA3 },
  { label: 'Caelin servant that talks to you at the end of chapter 10 looking relieved', value: 0xA4 },
  { label: 'Generic Blue Soldier', value: 0xA5 },
  { label: 'Generic Red Soldier', value: 0xA6 },
  { label: 'Generic Gray Soldier', value: 0xA7 },
  { label: 'Generic Bronze Soldier', value: 0xA8 },
  { label: 'Random male citizen (Balding man with moustache)', value: 0xA9 },
  { label: 'Random male citizen (Green hair and moustache)', value: 0xAA },
  { label: 'Random male citizen (The above, recolored with brown hair)', value: 0xAB },
  { label: 'Random male citizen (Scrawny, older man with a moustache)', value: 0xAC },
  { label: 'Random female citizen (Older lady with her hair in a bun)', value: 0xAD },
  { label: 'Random female citizen (Younger lady with freckles)', value: 0xAE },
  { label: 'Random female citizen (Younger lady with long hair)', value: 0xAF },
  { label: 'Random male citizen (Younger man with short hair)', value: 0xB0 },
  { label: 'Random male citizen (Younger man with freckles)', value: 0xB1 },
  { label: 'Random male citizen (Boy with short blond hair)', value: 0xB2 },
  { label: 'Random male citizen (Boy with short ruddy [Reddish orange] hair)', value: 0xB3 },
  { label: 'Random female citizen (Little girl with brown pigtails)', value: 0xB4 },
  { label: 'Random female citizen (Younger lady with long orange hair)', value: 0xB5 },
  { label: 'Random male citizen (Old man with a short beard)', value: 0xB6 },
  { label: 'Random female citizen (Old lady with a hood and grey hair)', value: 0xB7 },
  { label: 'Random female citizen (same as above, only recolored, and with brown hair)', value: 0xB8 },
  { label: 'Random male citizen (Younger with orange hair)', value: 0xB9 },
  { label: 'Random enemy assassin/Black fang member', value: 0xBA },
  { label: 'Random enemy hero/thug (looks like it could be a boss, but no name was attached to it)', value: 0xBB },
  { label: 'Random enemy brigand (headband and buckteeth)', value: 0xBC },
  { label: 'Random enemy brigand (Sideburns)', value: 0xBD },
  { label: 'Enemy Myrmidon card', value: 0xBE },
  { label: 'Enemy Swordmaster card', value: 0xBF },
  { label: 'Enemy Fighter card', value: 0xC0 },
  { label: 'Enemy Warrior card', value: 0xC1 },
  { label: 'Enemy Knight card', value: 0xC2 },
  { label: 'Enemy General card', value: 0xC3 },
  { label: 'Enemy Archer card', value: 0xC4 },
  { label: 'Enemy Sniper card', value: 0xC5 },
  { label: 'Enemy Cleric card', value: 0xC6 },
  { label: 'Enemy Bishop card', value: 0xC7 },
  { label: 'Enemy Mage card', value: 0xC8 },
  { label: 'Enemy Sage card', value: 0xC9 },
  { label: 'Enemy Shaman card', value: 0xCA },
  { label: 'Enemy Druid card', value: 0xCB },
  { label: 'Enemy Cavalier card', value: 0xCC },
  { label: 'Enemy Paladin card', value: 0xCD },
  { label: 'Enemy Troubadour card', value: 0xCE },
  { label: 'Enemy Valkyrie card', value: 0xCF },
  { label: 'Enemy Nomad card', value: 0xD0 },
  { label: 'Enemy Nomadic Trooper card', value: 0xD1 },
  { label: 'Enemy Pegasus card', value: 0xD2 },
  { label: 'Enemy Falcon Knight card', value: 0xD3 },
  { label: 'Enemy Wywern Knight card', value: 0xD4 },
  { label: 'Enemy Wywern Lord card', value: 0xD5 },
  { label: 'Enemy Soldier card', value: 0xD6 },
  { label: 'Enemy Brigand card', value: 0xD7 },
  { label: 'Enemy Pirate card', value: 0xD8 },
  { label: 'Enemy Berserker card', value: 0xD9 },
  { label: 'Enemy Thief card', value: 0xDA },
  { label: 'Enemy Mamkute card', value: 0xDB },
  { label: 'Enemy Mercenary card', value: 0xDC },
  { label: 'Enemy Hero card', value: 0xDD },
  { label: 'Enemy Fire Dragon card', value: 0xDE },
  { label: 'Anna', value: 0xDF },
  { label: 'Jake', value: 0xE0 },
  { label: 'Armory man (not a full sized portrait)', value: 0xE1 },
  { label: 'Arena man (not a full sized portrait)', value: 0xE2 },
  { label: 'Shop girl (not a full sized portrait)', value: 0xE3 },
  { label: 'Anna (Secret shop)', value: 0xE4 },
];

export const Ability1 = [
  { label: 'None', value: 0x00 },
  { label: '0x01', value: 0x01 },
  { label: 'Move Again', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Steal', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'Thief Key', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Dance', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Play', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Critical +15', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Ballistas', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'All of the above', value: 0xFF },
];

export const Ability2 = [
  { label: 'None', value: 0x00 },
  { label: 'Promoted', value: 0x01 },
  { label: 'Supply Depot', value: 0x02 },
  { label: 'Promoted Supply', value: 0x03 },
  { label: 'Mounted Unit', value: 0x04 },
  { label: 'Promoted Mounted', value: 0x05 },
  { label: 'Mounted Supply', value: 0x06 },
  { label: 'Promoted Mounted Supply', value: 0x07 },
  { label: 'Dragon Knight', value: 0x08 },
  { label: 'Promoted Dragon Knight', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Pegasus Knight', value: 0x10 },
  { label: 'Promoted Pegasus Knight', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Lord', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: 'Promoted Mounted Lord', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Female', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Boss', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'All of the above', value: 0xFF },
];

export const Ability3 = [
  { label: 'None', value: 0x00 },
  { label: '???', value: 0x01 },
  { label: 'Wo Dao Usable', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Dragonstone Usable', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'All Morphs, Boss Vaida', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Prevents controlling', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Triangle attack', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Different Triangle attack', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Qlitches, don\'t use', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: '0xFF', value: 0xFF },
];

export const Ability4 = [
  { label: 'None', value: 0x00 },
  { label: 'Dragon weapon lock', value: 0x01 },
  { label: 'Lethality', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Magic Sealing', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'Last item droppable', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Unlock Rapier/Durandal', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Unlock Wolf Beil/Armads', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Unlock Mani/Sol Katti', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Unlock Forblaze', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: '0xFF', value: 0xFF },
];

export const WeaponRank = [
  { label: 'None', value: 0x00 },
  { label: 'E', value: 0x01 },
  { label: 'D', value: 0x1F },
  { label: 'C', value: 0x47 },
  { label: 'B', value: 0x79 },
  { label: 'A', value: 0xB5 },
  { label: 'S', value: 0xFB },
];
