export const FE4PromotionEditorEntries = [
  { label: 'Sigurd - Noish - Alec', value: 0 },
  { label: 'Adan - Young Fin - Cuan', value: 1 },
  { label: 'Mideel - Levin - Holyn', value: 2 },
  { label: 'Azel - Jamuka - Claude', value: 3 },
  { label: 'Beowulf - Lex - Dew', value: 4 },
  { label: 'Diadora - Ethrin - Lachesis', value: 5 },
  { label: 'Ira - Fury - Tiltyu', value: 6 },
  { label: 'Sylvia - Edin - Bridget', value: 7 },
  { label: 'Celice - Shanan - Rodolban', value: 8 },
  { label: 'Asaello - Leaf - Johan', value: 9 },
  { label: 'Sharlow - Hawk - Tristan', value: 10 },
  { label: 'Adult Fin - Dimna - Hannibal', value: 11 },
  { label: 'Aless - Amid - Oifaye', value: 12 },
  { label: 'Daisy - Radney - Mana', value: 13 },
  { label: 'Julia - Altenna - Femina', value: 14 },
  { label: 'Linda - Laylea - Janne', value: 15 },
  { label: 'Johalva - Skasaher - Faval', value: 16 },
  { label: 'Corple - Sety - Delmud', value: 17 },
  { label: 'Lester - Arthur - Patty', value: 18 },
  { label: 'Lakche - Rana - Fee', value: 19 },
  { label: 'Tinny - Lynn - Nanna', value: 20 },
];

export const FE4PromotionClasses = [
  { label: 'Social Knight', value: 0x00 },
  { label: 'Lance Knight', value: 0x01 },
  { label: 'Arch Knight', value: 0x02 },
  { label: 'Axe Knight', value: 0x03 },
  { label: 'Free Knight', value: 0x04 },
  { label: 'Trobadour', value: 0x05 },
  { label: 'Lord Knight', value: 0x06 },
  { label: 'Duke Knight', value: 0x07 },
  { label: 'Master Knight', value: 0x08 },
  { label: 'Male Paladin', value: 0x09 },
  { label: 'Female Paladin', value: 0x0A },
  { label: 'Bow Knight', value: 0x0B },
  { label: 'Forrest Knight', value: 0x0C },
  { label: 'Mage Knight', value: 0x0D },
  { label: 'Great Knight', value: 0x0E },
  { label: 'Pegasus Rider', value: 0x0F },
  { label: 'Pegasus Knight', value: 0x10 },
  { label: 'Falcon Knight', value: 0x11 },
  { label: 'Dragon Rider', value: 0x12 },
  { label: 'Dragon Knight', value: 0x13 },
  { label: 'Dragon Master', value: 0x14 },
  { label: 'Bow Fighter', value: 0x15 },
  { label: 'Sword Fighter', value: 0x16 },
  { label: 'Sword Master', value: 0x17 },
  { label: 'Sniper', value: 0x18 },
  { label: 'Forrest', value: 0x19 },
  { label: 'General', value: 0x1A },
  { label: 'Emperor', value: 0x1B },
  { label: 'Baron', value: 0x1C },
  { label: 'Soldier', value: 0x1D },
  { label: 'Spear Soldier', value: 0x1E },
  { label: 'Axe Soldier', value: 0x1F },
  { label: 'Archer', value: 0x20 },
  { label: 'Sword Soldier', value: 0x21 },
  { label: 'Armor', value: 0x22 },
  { label: 'Axe Armor', value: 0x23 },
  { label: 'Bow Armor', value: 0x24 },
  { label: 'Sword Armor', value: 0x25 },
  { label: 'Barbarian', value: 0x26 },
  { label: 'Axe Fighter', value: 0x27 },
  { label: 'Mountain Thief', value: 0x28 },
  { label: 'Warrior', value: 0x29 },
  { label: 'Hunter', value: 0x2A },
  { label: 'Pirate', value: 0x2B },
  { label: 'Junior Lord', value: 0x2C },
  { label: 'Male Mage Fighter', value: 0x2D },
  { label: 'Prince', value: 0x2E },
  { label: 'Princess', value: 0x2F },
  { label: 'Female Mage Fighter', value: 0x30 },
  { label: 'Queen', value: 0x31 },
  { label: 'Dancer', value: 0x32 },
  { label: 'Priest', value: 0x33 },
  { label: 'Mage', value: 0x34 },
  { label: 'Fire Mage', value: 0x35 },
  { label: 'Thunder Mage', value: 0x36 },
  { label: 'Wind Mage', value: 0x37 },
  { label: 'High Priest', value: 0x38 },
  { label: 'Bishop', value: 0x39 },
  { label: 'Sage', value: 0x3A },
  { label: 'Bard', value: 0x3B },
  { label: 'Shaman', value: 0x3C },
  { label: 'Dark Mage', value: 0x3D },
  { label: 'Dark Bishop', value: 0x3E },
  { label: 'Thief', value: 0x3F },
  { label: 'Thief Fighter', value: 0x40 },
  { label: 'Civilian', value: 0x41 },
  { label: 'Child', value: 0x42 },
  { label: 'Long Arch', value: 0x43 },
  { label: 'Iron Arch', value: 0x44 },
  { label: 'Killer Arch', value: 0x45 },
  { label: 'Gold Arch', value: 0x46 },
  { label: 'Dark Prince', value: 0x47 },
  { label: 'None', value: 0xFF },
];
