export const FE6ClassEditorEntries = [
  { label: 'None', value: 0 },
  { label: 'Roy Lord', value: 1 },
  { label: 'Mercenary', value: 2 },
  { label: 'Mercenary (F)', value: 3 },
  { label: 'Hero', value: 4 },
  { label: 'Hero (F)', value: 5 },
  { label: 'Swordfighter', value: 6 },
  { label: 'Swordfighter (F)', value: 7 },
  { label: 'Swordmaster', value: 8 },
  { label: 'Swordmaster (F)', value: 9 },
  { label: 'Axefighter', value: 10 },
  { label: 'Warrior', value: 11 },
  { label: 'Armour Knight', value: 12 },
  { label: 'Armour Knight (F)', value: 13 },
  { label: 'General', value: 14 },
  { label: 'General (F)', value: 15 },
  { label: 'Archer', value: 16 },
  { label: 'Archer (F)', value: 17 },
  { label: 'Sniper', value: 18 },
  { label: 'Sniper (F)', value: 19 },
  { label: 'Priest', value: 20 },
  { label: 'Sister', value: 21 },
  { label: 'Bishop', value: 22 },
  { label: 'Bishop (F)', value: 23 },
  { label: 'Mage', value: 24 },
  { label: 'Mage (F)', value: 25 },
  { label: 'Sage', value: 26 },
  { label: 'Sage (F)', value: 27 },
  { label: 'Shaman', value: 28 },
  { label: 'Shaman (F)', value: 29 },
  { label: 'Druid', value: 30 },
  { label: 'Druid (F)', value: 31 },
  { label: 'Socialknight', value: 32 },
  { label: 'Socialknight (F) (messed up palette)', value: 33 },
  { label: 'Paladin', value: 34 },
  { label: 'Paladin (F) (messed up palette)', value: 35 },
  { label: 'Troubadour', value: 36 },
  { label: 'Valkyrie', value: 37 },
  { label: 'Nomad', value: 38 },
  { label: 'Nomad (F)', value: 39 },
  { label: 'Nomad Trooper', value: 40 },
  { label: 'Nomad Trooper (F)', value: 41 },
  { label: 'Pegasus Knight', value: 42 },
  { label: 'Falcon Knight', value: 43 },
  { label: 'Dragon Knight', value: 44 },
  { label: 'Dragon Knight (F)', value: 45 },
  { label: 'Dragon Master', value: 46 },
  { label: 'Dragon Master (F)', value: 47 },
  { label: 'Soldier', value: 48 },
  { label: 'Mountain Thief', value: 49 },
  { label: 'Pirate', value: 50 },
  { label: 'Berserker', value: 51 },
  { label: 'Thief', value: 52 },
  { label: 'Thief (F)', value: 53 },
  { label: 'Bard', value: 54 },
  { label: 'Dancer', value: 55 },
  { label: 'Mamkute', value: 56 },
  { label: 'Mamkute (F)', value: 57 },
  { label: 'Fire Dragon', value: 58 },
  { label: 'Divine Dragon', value: 59 },
  { label: 'Magic Dragon', value: 60 },
  { label: 'King', value: 61 },
  { label: 'Civilian', value: 62 },
  { label: 'Civilian (F)', value: 63 },
  { label: 'Child', value: 64 },
  { label: 'Child (F)', value: 65 },
  { label: 'Storage', value: 66 },
  { label: 'Roy Master Lord', value: 67 },
  { label: 'Archer on Long Arch', value: 68 },
  { label: 'Archer on Iron Arch', value: 69 },
  { label: 'Archer on Killer Arch', value: 70 },
  { label: 'Long Arch', value: 71 },
  { label: 'Iron Arch', value: 72 },
  { label: 'Killer Arch', value: 73 },
  { label: 'Disarmed Sniper (no standing sprites)', value: 74 },
  { label: 'Disarmed Sniper (F) (no standing sprites)', value: 75 },
];

export const ClassList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Roy Lord', value: 0x01 },
  { label: 'Mercenary', value: 0x02 },
  { label: 'Mercenary (F)', value: 0x03 },
  { label: 'Hero', value: 0x04 },
  { label: 'Hero (F)', value: 0x05 },
  { label: 'Swordfighter', value: 0x06 },
  { label: 'Swordfighter (F)', value: 0x07 },
  { label: 'Swordmaster', value: 0x08 },
  { label: 'Swordmaster (F)', value: 0x09 },
  { label: 'Axefighter', value: 0x0A },
  { label: 'Warrior', value: 0x0B },
  { label: 'Armour Knight', value: 0x0C },
  { label: 'Armour Knight (F)', value: 0x0D },
  { label: 'General', value: 0x0E },
  { label: 'General (F)', value: 0x0F },
  { label: 'Archer', value: 0x10 },
  { label: 'Archer (F)', value: 0x11 },
  { label: 'Sniper', value: 0x12 },
  { label: 'Sniper (F)', value: 0x13 },
  { label: 'Priest', value: 0x14 },
  { label: 'Sister', value: 0x15 },
  { label: 'Bishop', value: 0x16 },
  { label: 'Bishop (F)', value: 0x17 },
  { label: 'Mage', value: 0x18 },
  { label: 'Mage (F)', value: 0x19 },
  { label: 'Sage', value: 0x1A },
  { label: 'Sage (F)', value: 0x1B },
  { label: 'Shaman', value: 0x1C },
  { label: 'Shaman (F)', value: 0x1D },
  { label: 'Druid', value: 0x1E },
  { label: 'Druid (F)', value: 0x1F },
  { label: 'Socialknight', value: 0x20 },
  { label: 'Socialknight (F) (messed up palette)', value: 0x21 },
  { label: 'Paladin', value: 0x22 },
  { label: 'Paladin (F) (messed up palette)', value: 0x23 },
  { label: 'Troubadour', value: 0x24 },
  { label: 'Valkyrie', value: 0x25 },
  { label: 'Nomad', value: 0x26 },
  { label: 'Nomad (F)', value: 0x27 },
  { label: 'Nomad Trooper', value: 0x28 },
  { label: 'Nomad Trooper (F)', value: 0x29 },
  { label: 'Pegasus Knight', value: 0x2A },
  { label: 'Falcon Knight', value: 0x2B },
  { label: 'Dragon Knight', value: 0x2C },
  { label: 'Dragon Knight (F)', value: 0x2D },
  { label: 'Dragon Master', value: 0x2E },
  { label: 'Dragon Master (F)', value: 0x2F },
  { label: 'Soldier', value: 0x30 },
  { label: 'Mountain Thief', value: 0x31 },
  { label: 'Pirate', value: 0x32 },
  { label: 'Berserker', value: 0x33 },
  { label: 'Thief', value: 0x34 },
  { label: 'Thief (F)', value: 0x35 },
  { label: 'Bard', value: 0x36 },
  { label: 'Dancer', value: 0x37 },
  { label: 'Mamkute', value: 0x38 },
  { label: 'Mamkute (F)', value: 0x39 },
  { label: 'Fire Dragon', value: 0x3A },
  { label: 'Divine Dragon', value: 0x3B },
  { label: 'Magic Dragon', value: 0x3C },
  { label: 'King', value: 0x3D },
  { label: 'Civilian', value: 0x3E },
  { label: 'Civilian (F)', value: 0x3F },
  { label: 'Child', value: 0x40 },
  { label: 'Child (F)', value: 0x41 },
  { label: 'Storage', value: 0x42 },
  { label: 'Roy Master Lord', value: 0x43 },
  { label: 'Archer on Long Arch', value: 0x44 },
  { label: 'Archer on Iron Arch', value: 0x45 },
  { label: 'Archer on Killer Arch', value: 0x46 },
  { label: 'Long Arch', value: 0x47 },
  { label: 'Iron Arch', value: 0x48 },
  { label: 'Killer Arch', value: 0x49 },
  { label: 'Disarmed Sniper (no standing sprites)', value: 0x4A },
  { label: 'Disarmed Sniper (F) (no standing sprites)', value: 0x4B },
];

export const MapSpritesStanding = [
  { label: 'Roy Lord', value: 0x00 },
  { label: 'Mercenary', value: 0x01 },
  { label: 'Mercenary (F)', value: 0x02 },
  { label: 'Hero', value: 0x03 },
  { label: 'Hero (F)', value: 0x04 },
  { label: 'Myrmidon', value: 0x05 },
  { label: 'Myrmidon (F)', value: 0x06 },
  { label: 'Swordmaster', value: 0x07 },
  { label: 'Swordmaster (F)', value: 0x08 },
  { label: 'Fighter', value: 0x09 },
  { label: 'Warrior', value: 0x0A },
  { label: 'Knight', value: 0x0B },
  { label: 'General', value: 0x0C },
  { label: 'Archer', value: 0x0D },
  { label: 'Archer (F)', value: 0x0E },
  { label: 'Sniper', value: 0x0F },
  { label: 'Sniper (F)', value: 0x10 },
  { label: 'Priest', value: 0x11 },
  { label: 'Cleric', value: 0x12 },
  { label: 'Bishop', value: 0x13 },
  { label: 'Bishop (F)', value: 0x14 },
  { label: 'Mage', value: 0x15 },
  { label: 'Mage (F)', value: 0x16 },
  { label: 'Sage', value: 0x17 },
  { label: 'Sage (F)', value: 0x18 },
  { label: 'Shaman', value: 0x19 },
  { label: 'Shaman (F)', value: 0x1A },
  { label: 'Druid', value: 0x1B },
  { label: 'Druid (F)', value: 0x1C },
  { label: 'Cavalier', value: 0x1D },
  { label: 'Cavalier (F)', value: 0x1E },
  { label: 'Paladin', value: 0x1F },
  { label: 'Paladin (F)', value: 0x20 },
  { label: 'Troubador', value: 0x21 },
  { label: 'Valkiery', value: 0x22 },
  { label: 'Nomad', value: 0x23 },
  { label: 'Nomad (F)', value: 0x24 },
  { label: 'Nomad Trooper', value: 0x25 },
  { label: 'Nomad Trooper (F)', value: 0x26 },
  { label: 'Pegasus Knight', value: 0x27 },
  { label: 'Falco Knight', value: 0x28 },
  { label: 'Wyvern Rider', value: 0x29 },
  { label: 'Wyvern Lord', value: 0x2A },
  { label: 'Soldier', value: 0x2B },
  { label: 'Brigand', value: 0x2C },
  { label: 'Pirate', value: 0x2D },
  { label: 'Berserker', value: 0x2E },
  { label: 'Thief', value: 0x2F },
  { label: 'Thief (F)', value: 0x30 },
  { label: 'Bard', value: 0x31 },
  { label: 'Dancer', value: 0x32 },
  { label: 'Mamkute', value: 0x33 },
  { label: 'Mamkute (F)', value: 0x34 },
  { label: 'Fire Dragon', value: 0x35 },
  { label: 'Divine Dragon', value: 0x36 },
  { label: 'Magic Dragon', value: 0x37 },
  { label: 'King', value: 0x38 },
  { label: 'Civilian', value: 0x39 },
  { label: 'Civilian (F)', value: 0x3A },
  { label: 'Child', value: 0x3B },
  { label: 'Child (F)', value: 0x3C },
  { label: 'Transporter', value: 0x3D },
  { label: 'Roy Master Lord', value: 0x3E },
  { label: 'Archer on Long Arch', value: 0x3F },
  { label: 'Archer on Iron Arch', value: 0x40 },
  { label: 'Archer on Killer Arch', value: 0x41 },
  { label: 'Long Arch', value: 0x42 },
  { label: 'Iron Arch', value: 0x43 },
  { label: 'Killer Arch', value: 0x44 },
  { label: 'Disamred Sniper', value: 0x45 },
  { label: 'Disarmed Sniper (F)', value: 0x46 },
];

export const WalkingSpeed = [
  { label: 'Normal', value: 0x00 },
  { label: 'Slow', value: 0x01 },
];

export const PortraitList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Weird two-colour portrait', value: 0x01 },
  { label: 'Roy', value: 0x02 },
  { label: 'Clarine', value: 0x03 },
  { label: 'Fa', value: 0x04 },
  { label: 'Shin', value: 0x05 },
  { label: 'Sue', value: 0x06 },
  { label: 'Dayan', value: 0x07 },
  { label: 'Barth', value: 0x08 },
  { label: 'Bors', value: 0x09 },
  { label: 'Douglas', value: 0x0A },
  { label: 'Wolt', value: 0x0B },
  { label: 'Dorothy', value: 0x0C },
  { label: 'Klein', value: 0x0D },
  { label: 'Saul', value: 0x0E },
  { label: 'Elen', value: 0x0F },
  { label: 'Yodel', value: 0x10 },
  { label: 'Chad', value: 0x11 },
  { label: 'Karel', value: 0x12 },
  { label: 'Fir', value: 0x13 },
  { label: 'Rutger', value: 0x14 },
  { label: 'Dieck', value: 0x15 },
  { label: 'Oujay', value: 0x16 },
  { label: 'Garet', value: 0x17 },
  { label: 'Alan', value: 0x18 },
  { label: 'Lance', value: 0x19 },
  { label: 'Percival', value: 0x1A },
  { label: 'Igrene', value: 0x1B },
  { label: 'Marcus', value: 0x1C },
  { label: 'Astol', value: 0x1D },
  { label: 'Ward', value: 0x1E },
  { label: 'Lot', value: 0x1F },
  { label: 'Bartre', value: 0x20 },
  { label: 'Lugh', value: 0x21 },
  { label: 'Lilina', value: 0x22 },
  { label: 'Hugh', value: 0x23 },
  { label: 'Niime', value: 0x24 },
  { label: 'Rei', value: 0x25 },
  { label: 'Lalam', value: 0x26 },
  { label: 'Yunno', value: 0x27 },
  { label: 'Thito', value: 0x28 },
  { label: 'Thany', value: 0x29 },
  { label: 'Zeiss', value: 0x2A },
  { label: 'Elfin', value: 0x2B },
  { label: 'Cass', value: 0x2C },
  { label: 'Sophia', value: 0x2D },
  { label: 'Miledy', value: 0x2E },
  { label: 'Gonzales', value: 0x2F },
  { label: 'Noah', value: 0x30 },
  { label: 'Treck', value: 0x31 },
  { label: 'Zealot', value: 0x32 },
  { label: 'Echidna', value: 0x33 },
  { label: 'Cecilia', value: 0x34 },
  { label: 'Geese', value: 0x35 },
  { label: 'Gale', value: 0x36 },
  { label: 'Damas', value: 0x37 },
  { label: 'Rude', value: 0x38 },
  { label: 'Slater', value: 0x39 },
  { label: 'Erik', value: 0x3A },
  { label: 'Dory', value: 0x3B },
  { label: 'Devias', value: 0x3C },
  { label: 'Roartz', value: 0x3D },
  { label: 'Scott', value: 0x3E },
  { label: 'Flaer', value: 0x3F },
  { label: 'Oro', value: 0x40 },
  { label: 'Aine', value: 0x41 },
  { label: 'Narshen', value: 0x42 },
  { label: 'Raeth', value: 0x43 },
  { label: 'Legylance', value: 0x44 },
  { label: 'Sigune', value: 0x45 },
  { label: 'Arcard', value: 0x46 },
  { label: 'Murdock', value: 0x47 },
  { label: 'Brunya', value: 0x48 },
  { label: 'Zephiel', value: 0x49 },
  { label: 'Idoun (no hood)', value: 0x4A },
  { label: 'Idoun (w/ hood)', value: 0x4B },
  { label: 'Yahn', value: 0x4C },
  { label: 'Zinc', value: 0x4D },
  { label: 'Gel', value: 0x4E },
  { label: 'William/Robarts', value: 0x4F },
  { label: 'Bucktoothed bandit', value: 0x50 },
  { label: 'Generic bandit', value: 0x51 },
  { label: 'Generic soldier', value: 0x52 },
  { label: 'Generic peggyknight', value: 0x53 },
  { label: 'Merlinus', value: 0x54 },
  { label: 'Merlinus (smaller)', value: 0x55 },
  { label: 'Eliwood', value: 0x56 },
  { label: 'Guinevere', value: 0x57 },
  { label: 'Hector', value: 0x58 },
  { label: 'Really old-looking king', value: 0x59 },
  { label: 'Villager', value: 0x5A },
  { label: 'Villager', value: 0x5B },
  { label: 'Villager', value: 0x5C },
  { label: 'Villager', value: 0x5D },
  { label: 'Villager', value: 0x5E },
  { label: 'Villager', value: 0x5F },
  { label: 'Villager', value: 0x60 },
  { label: 'Villager', value: 0x61 },
  { label: 'Villager', value: 0x62 },
  { label: 'Villager', value: 0x63 },
  { label: 'Villager', value: 0x64 },
  { label: 'Villager', value: 0x65 },
  { label: 'Villager', value: 0x66 },
  { label: 'Villager', value: 0x67 },
  { label: 'Villager', value: 0x68 },
  { label: 'Villager', value: 0x69 },
  { label: 'Villager', value: 0x6A },
  { label: 'Villager', value: 0x6B },
  { label: 'Villager', value: 0x6C },
  { label: 'Villager', value: 0x6D },
  { label: 'Villager', value: 0x6E },
  { label: 'Villager', value: 0x6F },
  { label: 'Villager', value: 0x70 },
  { label: 'Villager', value: 0x71 },
  { label: 'Villager', value: 0x72 },
  { label: 'Villager', value: 0x73 },
  { label: 'Villager', value: 0x74 },
  { label: 'Villager', value: 0x75 },
  { label: 'Villager', value: 0x76 },
  { label: 'Villager', value: 0x77 },
  { label: 'Villager', value: 0x78 },
  { label: 'Villager', value: 0x79 },
  { label: 'Villager', value: 0x7A },
  { label: 'Villager', value: 0x7B },
  { label: 'Villager', value: 0x7C },
  { label: 'Villager', value: 0x7D },
  { label: 'Villager', value: 0x7E },
  { label: 'Villager', value: 0x7F },
  { label: 'Villager', value: 0x80 },
  { label: 'Villager', value: 0x81 },
  { label: 'Villager', value: 0x82 },
  { label: 'Villager', value: 0x83 },
  { label: 'Villager', value: 0x84 },
  { label: 'Villager', value: 0x85 },
  { label: 'Villager', value: 0x86 },
  { label: 'Villager', value: 0x87 },
  { label: 'Villager', value: 0x88 },
  { label: 'Villager', value: 0x89 },
  { label: 'Villager', value: 0x8A },
  { label: 'Villager', value: 0x8B },
  { label: 'Villager', value: 0x8C },
  { label: 'Villager', value: 0x8D },
  { label: 'Villager', value: 0x8E },
  { label: 'Villager', value: 0x8F },
  { label: 'Villager', value: 0x90 },
  { label: 'Villager', value: 0x91 },
  { label: 'Villager', value: 0x92 },
  { label: 'Villager', value: 0x93 },
  { label: 'Villager', value: 0x94 },
  { label: 'Villager', value: 0x95 },
  { label: 'Villager', value: 0x96 },
  { label: 'Villager', value: 0x97 },
  { label: 'Villager', value: 0x98 },
  { label: 'Swordfighter enemy card', value: 0x99 },
  { label: 'Swordmaster enemy card', value: 0x9A },
  { label: 'Axefighter enemy card', value: 0x9B },
  { label: 'Warrior enemy card', value: 0x9C },
  { label: 'Armour Knight enemy card', value: 0x9D },
  { label: 'General enemy card', value: 0x9E },
  { label: 'Archer enemy card', value: 0x9F },
  { label: 'Sniper enemy card', value: 0xA0 },
  { label: 'Priest enemy card', value: 0xA1 },
  { label: 'Bishop enemy card', value: 0xA2 },
  { label: 'Mage enemy card', value: 0xA3 },
  { label: 'Sage enemy card', value: 0xA4 },
  { label: 'Shaman enemy card', value: 0xA5 },
  { label: 'Druid enemy card', value: 0xA6 },
  { label: 'Socialknight enemy card', value: 0xA7 },
  { label: 'Paladin enemy card', value: 0xA8 },
  { label: 'Troubadour enemy card', value: 0xA9 },
  { label: 'Valkyrie enemy card', value: 0xAA },
  { label: 'Nomad enemy card', value: 0xAB },
  { label: 'Nomad Trooper enemy card', value: 0xAC },
  { label: 'Pegasus Knight enemy card', value: 0xAD },
  { label: 'Falcon Knight enemy card', value: 0xAE },
  { label: 'Dragon Knight enemy card', value: 0xAF },
  { label: 'Dragon Master enemy card', value: 0xB0 },
  { label: 'Soldier enemy card', value: 0xB1 },
  { label: 'Mountain Thief enemy card', value: 0xB2 },
  { label: 'Pirate enemy card', value: 0xB3 },
  { label: 'Berserker enemy card', value: 0xB4 },
  { label: 'Thief enemy card', value: 0xB5 },
  { label: 'Mamkute enemy card', value: 0xB6 },
  { label: '(destroys background)', value: 0xB7 },
  { label: '(destroys background)', value: 0xB8 },
  { label: 'Armoury guy', value: 0xB9 },
  { label: 'Arena guy', value: 0xBA },
  { label: 'Shop girl', value: 0xBB },
  { label: 'Anna shopkeeper', value: 0xBC },
  { label: 'Wendy', value: 0xBD },
  { label: 'Idoun (dragon form)', value: 0xBE },
  { label: 'Hector (bloody)', value: 0xBF },
  { label: 'Anna', value: 0xC0 },
  { label: 'Bishop from the orphanage', value: 0xC1 },
  { label: 'Bishop from the orphanage (shadow)', value: 0xC2 },
  { label: 'Bishop from the orphanage (shadow)', value: 0xC3 },
  { label: 'Bishop from the orphanage (shadow)', value: 0xC4 },
  { label: 'Green Old Sage', value: 0xC5 },
  { label: 'Ohtz', value: 0xC6 },
  { label: 'Pereth', value: 0xC7 },
  { label: 'Orange Old Sage', value: 0xC8 },
  { label: 'Randy', value: 0xC9 },
  { label: 'Grey Hero', value: 0xCA },
  { label: 'Henning', value: 0xCB },
  { label: 'Green Hero', value: 0xCC },
  { label: 'Monke', value: 0xCD },
  { label: 'Djute Survivors', value: 0xCE },
  { label: 'Brown Nomad', value: 0xCF },
  { label: 'Another Nomad', value: 0xD0 },
  { label: 'Rose', value: 0xD1 },
  { label: 'Maggie', value: 0xD2 },
  { label: 'Grero', value: 0xD3 },
  { label: 'Martel', value: 0xD4 },
  { label: 'Windam', value: 0xD5 },
  { label: 'Bishop', value: 0xD6 },
  { label: 'Red Soldier', value: 0xD7 },
  { label: 'Grey Soldier', value: 0xD8 },
  { label: 'Green Soldier', value: 0xD9 },
  { label: 'Bronze Soldier', value: 0xDA },
  { label: 'Really Red Soldier', value: 0xDB },
  { label: 'Lighter Green Soldier', value: 0xDC },
  { label: 'Morgan', value: 0xDD },
  { label: 'Grey-Haired General', value: 0xDE },
  { label: 'Brown-Haired General', value: 0xDF },
  { label: 'Teck', value: 0xE0 },
  { label: 'Green-Haired Paladin', value: 0xE1 },
  { label: 'Blonde-Haired Paladin', value: 0xE2 },
  { label: 'Wagner', value: 0xE3 },
  { label: 'Nord', value: 0xE4 },
  { label: 'Green Shaman', value: 0xE5 },
  { label: 'Olive-Green Shaman', value: 0xE6 },
];

export const Ability1 = [
  { label: 'None', value: 0x00 },
  { label: 'Mounted Aid system', value: 0x01 },
  { label: 'Move Again', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Steal', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'Thief Key', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Dance', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Play', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Critical +30', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Ballistas', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'All of the above', value: 0xFF },
];

export const Ability2 = [
  { label: 'None', value: 0x00 },
  { label: 'Already Promoted', value: 0x01 },
  { label: 'Supply Depot', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Horse icon', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'Wywern icon', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Pegasus icon', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Lord', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Female', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Boss', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: 'Female Boss', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'All of the above', value: 0xFF },
];

export const Ability3 = [
  { label: 'None', value: 0x00 },
  { label: 'Rapier/Sword of Seals weapon lock', value: 0x01 },
  { label: 'Wo dao weapon lock', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Dragon stone weapon lock', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: '???', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: '???', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Pegasus Knight triangle attack', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Armor knights triangle attack', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Starts as NPC', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: '0xFF', value: 0xFF },
];

export const WeaponRank = [
  { label: 'None', value: 0x00 },
  { label: 'E', value: 0x01 },
  { label: 'D', value: 0x33 },
  { label: 'C', value: 0x65 },
  { label: 'B', value: 0x97 },
  { label: 'A', value: 0xC9 },
  { label: 'S', value: 0xFB },
];
