export const FE7SoundRoomEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
];

export const Music = [
  { label: 'Not applicable', value: 0xFFFF },
  { label: 'Nothing', value: 0x0000 },
  { label: 'Precious Things', value: 0x0001 },
  { label: 'Companions', value: 0x0002 },
  { label: 'Friendship and Adventure', value: 0x0003 },
  { label: 'Dragon\'s Gate II', value: 0x0004 },
  { label: 'Scars of the Scouring', value: 0x0005 },
  { label: 'Raise Your Spirits', value: 0x0006 },
  { label: 'Shadow Approaches', value: 0x0007 },
  { label: 'Binding Ties', value: 0x0008 },
  { label: 'Winning Road', value: 0x0009 },
  { label: 'Distant Travels', value: 0x000A },
  { label: 'Inescapable Fate', value: 0x000B },
  { label: 'Enemies Appear', value: 0x000C },
  { label: 'The Messenger', value: 0x000D },
  { label: 'Darkness Comes', value: 0x000E },
  { label: 'Nabata\'s Wandering Messenger', value: 0x000F },
  { label: 'Dragon\'s Gate I', value: 0x0010 },
  { label: 'Legendary Inheritance', value: 0x0011 },
  { label: 'Raid!', value: 0x0012 },
  { label: 'Messenger from the Darkness', value: 0x0013 },
  { label: 'Victory Now!', value: 0x0014 },
  { label: 'Rise to the Challenge', value: 0x0015 },
  { label: 'Softly with Grace', value: 0x0016 },
  { label: 'Everything into the Dark', value: 0x0017 },
  { label: 'Campaign of Fire', value: 0x0018 },
  { label: 'Healing', value: 0x0019 },
  { label: 'Curing', value: 0x001A },
  { label: 'To the Heights', value: 0x001B },
  { label: 'Blessing of the 8 Generals I', value: 0x001C },
  { label: 'Receive the Blessings of Water', value: 0x001D },
  { label: 'Ride the Wind', value: 0x001E },
  { label: 'Strike', value: 0x001F },
  { label: 'Safeguard', value: 0x0020 },
  { label: 'Requiem', value: 0x0021 },
  { label: 'Land of Swirling Sands', value: 0x0022 },
  { label: 'The Kingdom of Bern', value: 0x0023 },
  { label: 'Bern - A Mother\'s Wish', value: 0x0024 },
  { label: 'A Hint of Things to Come', value: 0x0025 },
  { label: 'Road of Trials', value: 0x0026 },
  { label: 'Destiny Enlaced by Fear', value: 0x0027 },
  { label: 'Nothing', value: 0x0028 },
  { label: 'Results', value: 0x0029 },
  { label: 'Treasured Hope', value: 0x002A },
  { label: 'Game Over', value: 0x002B },
  { label: 'Within Sadness', value: 0x002C },
  { label: 'Arena Victory', value: 0x002D },
  { label: 'Arena Tactics', value: 0x002E },
  { label: 'Nothing', value: 0x002F },
  { label: 'Winds Across the Plains', value: 0x0030 },
  { label: 'Nothing', value: 0x0031 },
  { label: 'An Unexpected Caller', value: 0x0032 },
  { label: 'When the Rush Comes', value: 0x0033 },
  { label: 'The Cogs of Fate', value: 0x0034 },
  { label: 'Shocking Truth I', value: 0x0035 },
  { label: 'Shocking Truth II', value: 0x0036 },
  { label: 'The Eight Generals', value: 0x0037 },
  { label: 'Triumph', value: 0x0038 },
  { label: 'In the Shadow of Triumph', value: 0x0039 },
  { label: 'Reminiscence', value: 0x003A },
  { label: 'Nergal\'s Wrath', value: 0x003B },
  { label: 'The Archsage Athos', value: 0x003C },
  { label: 'One Heart: Eliwood\'s Theme', value: 0x003D },
  { label: 'Loyalty: Hector\'s Theme', value: 0x003E },
  { label: 'Girl of the Plains: Lyn\'s Theme', value: 0x003F },
  { label: 'Final Farewell', value: 0x0040 },
  { label: 'Going My Way', value: 0x0041 },
  { label: 'Together, We Ride!', value: 0x0042 },
  { label: 'A Knight\'s Oath', value: 0x0043 },
  { label: 'Happiness Abounds', value: 0x0044 },
  { label: 'Main Theme Arrangement', value: 0x0045 },
  { label: 'Shop', value: 0x0046 },
  { label: 'Arena Entrance', value: 0x0047 },
  { label: 'Arena Battle', value: 0x0048 },
  { label: 'Prepare to Charge', value: 0x0049 },
  { label: 'Calamity Bringer: Nergal\'s Theme', value: 0x004A },
  { label: 'Light to Tomorrow', value: 0x004B },
  { label: 'Merchant Merlinus', value: 0x004C },
  { label: 'Armory', value: 0x004D },
  { label: 'Ships and Homes', value: 0x004E },
  { label: 'Silent Ground', value: 0x004F },
  { label: 'Black Fang', value: 0x0050 },
  { label: 'Recollection of a Petal', value: 0x0051 },
  { label: 'What Comes from Darkness', value: 0x0052 },
  { label: 'Stratagem', value: 0x0053 },
  { label: 'Lyn\'s Desire', value: 0x0054 },
  { label: 'Nothing', value: 0x0055 },
  { label: 'Eyes of Sorrow', value: 0x0056 },
  { label: 'Unshakable Faith', value: 0x0057 },
  { label: 'The Grieving Heart', value: 0x0058 },
  { label: 'Nothing', value: 0x0059 },
  { label: 'Fire Emblem Theme', value: 0x005A },
  { label: 'Fire Emblem Theme (looped)', value: 0x005B },
  { label: 'Opening: History Unveiled', value: 0x005C },
  { label: 'Distant Utopia', value: 0x005D },
  { label: 'Fortune Telling', value: 0x005E },
  { label: 'Fire Emblem Theme (with intro)', value: 0x005F },
  { label: 'Chapter Display humming', value: 0x0060 },
  { label: 'Chapter Display', value: 0x0061 },
  { label: 'Water Droplet in the Opening', value: 0x0062 },
  { label: 'Sword Sound in the Opening', value: 0x0063 },
  { label: 'What Comes from Darkness', value: 0x0064 },
  { label: 'Black Fang', value: 0x0065 },
  { label: 'Going My Way', value: 0x0066 },
  { label: 'Safeguard', value: 0x0067 },
  { label: 'Shattered Life', value: 0x0068 },
  { label: 'Anguish', value: 0x0069 },
  { label: 'Respite in Battle', value: 0x006A },
  { label: 'The Inn', value: 0x006B },
  { label: 'Nothing', value: 0x006C },
  { label: 'Nothing', value: 0x006D },
  { label: 'Blessing of the 8 Generals II', value: 0x006E },
  { label: 'Campaign of Fire (no intro)', value: 0x006F },
  { label: 'Beneath a New Light', value: 0x0070 },
  { label: 'The Path to Greatness', value: 0x0071 },
  { label: 'In the Name of Bern', value: 0x0072 },
  { label: 'Legend of Athos', value: 0x0073 },
  { label: 'Avoided Fate', value: 0x0074 },
  { label: 'Legend of the God Dragon', value: 0x0075 },
  { label: 'Royal Palace of Silezha', value: 0x0076 },
  { label: '???', value: 0x0077 },
  { label: '??? (sounds like FE6\'s theme, but still unused there, too...)', value: 0x0078 },
  { label: 'Ominius', value: 0x0079 },
  { label: 'Nothing', value: 0x007A },
  { label: 'Nothing', value: 0x007B },
  { label: 'Nothing', value: 0x007C },
  { label: 'Nothing', value: 0x007D },
  { label: 'Nothing', value: 0x007E },
  { label: 'Nothing', value: 0x007F },
  { label: 'Droplet? sounds familiar', value: 0x0080 },
  { label: 'Crowd cheering', value: 0x0081 },
  { label: 'Rest staff (map)', value: 0x0082 },
  { label: 'Silence staff (map)', value: 0x0083 },
  { label: 'Nothing', value: 0x0084 },
  { label: 'Sleep staff (map)', value: 0x0085 },
  { label: 'Hammerne staff (map)', value: 0x0086 },
  { label: 'Berserk staff (map)', value: 0x0087 },
  { label: 'Weird sound (Watch staff?)', value: 0x0088 },
  { label: 'Live staff', value: 0x0089 },
  { label: 'Relive staff', value: 0x008A },
  { label: 'Recover staff', value: 0x008B },
  { label: 'Reserve staff', value: 0x008C },
  { label: 'Recovery from a status effect (longer)', value: 0x008D },
  { label: 'Crowd cheering (softer)', value: 0x008E },
  { label: 'Crowd cheering, then stops', value: 0x008F },
  { label: 'FE6 Chapter opening humming', value: 0x0090 },
  { label: 'FE6 Chapter opening', value: 0x0091 },
  { label: 'Nothing', value: 0x0092 },
  { label: 'Footsteps', value: 0x0093 },
  { label: 'Footsteps 2', value: 0x0094 },
  { label: 'Footsteps 3', value: 0x0095 },
  { label: 'Footsteps 4', value: 0x0096 },
  { label: 'Footsteps 5', value: 0x0097 },
  { label: 'Footsteps 6', value: 0x0098 },
  { label: 'Footsteps 7', value: 0x0099 },
  { label: 'Footsteps 8', value: 0x009A },
  { label: 'Horse trot', value: 0x009B },
  { label: 'Horse trot 2', value: 0x009C },
  { label: 'Horse trot 3', value: 0x009D },
  { label: 'Horse trot 4', value: 0x009E },
  { label: 'Horse trot 5', value: 0x009F },
  { label: 'Armour walk', value: 0x00A0 },
  { label: 'Armour walk 2', value: 0x00A1 },
  { label: 'Armour walk 3', value: 0x00A2 },
  { label: 'Armour walk 4', value: 0x00A3 },
  { label: 'Armour walk 5', value: 0x00A4 },
  { label: 'Armour walk 6', value: 0x00A5 },
  { label: 'Pegasus flying', value: 0x00A6 },
  { label: 'Pegasus flying 2', value: 0x00A7 },
  { label: 'Nothing', value: 0x00A8 },
  { label: 'Nothing', value: 0x00A9 },
  { label: 'Recovery from a status effect', value: 0x00AA },
  { label: 'Rock exploding?', value: 0x00AB },
  { label: 'Captive falling from dead holder', value: 0x00AC },
  { label: 'Nothing', value: 0x00AD },
  { label: 'Nothing', value: 0x00AE },
  { label: 'Destroyed wall/snag', value: 0x00AF },
  { label: 'Attacking wall/snag', value: 0x00B0 },
  { label: 'Unlocking door', value: 0x00B1 },
  { label: 'Nothing', value: 0x00B2 },
  { label: 'Torch', value: 0x00B3 },
  { label: 'Warping', value: 0x00B4 },
  { label: 'Warp end', value: 0x00B5 },
  { label: 'Pure Water', value: 0x00B6 },
  { label: 'Poison sound', value: 0x00B7 },
  { label: '???', value: 0x00B8 },
  { label: 'Gold changing', value: 0x00B9 },
  { label: 'Poison vent', value: 0x00BA },
  { label: 'Nothing', value: 0x00BB },
  { label: 'Nothing', value: 0x00BC },
  { label: 'Water tile going under', value: 0x00BD },
  { label: 'Water tile coming up', value: 0x00BE },
  { label: 'Fire tile', value: 0x00BF },
  { label: 'Nothing', value: 0x00C0 },
  { label: 'Nothing', value: 0x00C1 },
  { label: 'Nothing', value: 0x00C2 },
  { label: 'Nothing', value: 0x00C3 },
  { label: 'Nothing', value: 0x00C4 },
  { label: 'Nothing', value: 0x00C5 },
  { label: 'Nothing', value: 0x00C6 },
  { label: 'GBA version of Zelda:OoT future Hyrule Castle winds', value: 0x00C7 },
  { label: 'Small plunk?', value: 0x00C8 },
  { label: 'Light plunk?', value: 0x00C9 },
  { label: 'Large plunk?', value: 0x00CA },
  { label: 'Eliwood critical sword swing', value: 0x00CB },
  { label: 'Tap?', value: 0x00CC },
  { label: 'Low plunk?', value: 0x00CD },
  { label: 'Sword unsheathing', value: 0x00CE },
  { label: 'Sword unsheathing 2', value: 0x00CF },
  { label: 'Ballista fire', value: 0x00D0 },
  { label: 'Creaking', value: 0x00D1 },
  { label: 'Hit (map)', value: 0x00D2 },
  { label: 'Hit 2 (map)', value: 0x00D3 },
  { label: 'Hit 3 (map)', value: 0x00D4 },
  { label: 'Kill (map)', value: 0x00D5 },
  { label: 'Death (map)', value: 0x00D6 },
  { label: 'Miss (realtime)', value: 0x00D7 },
  { label: 'Crumbling?', value: 0x00D8 },
  { label: 'Nothing', value: 0x00D9 },
  { label: 'Nothing', value: 0x00DA },
  { label: 'Nothing', value: 0x00DB },
  { label: 'Mamkute transform', value: 0x00DC },
  { label: 'Mamkute de-transform', value: 0x00DD },
  { label: 'Mamkute yowl', value: 0x00DE },
  { label: 'Mamkute roar', value: 0x00DF },
  { label: 'Nothing', value: 0x00E0 },
  { label: 'Nothing', value: 0x00E1 },
  { label: 'Armour triangle, allies striking', value: 0x00E2 },
  { label: 'Idoun/Fire Dragon death roar', value: 0x00E3 },
  { label: 'Nothing', value: 0x00E4 },
  { label: 'Idoun/Fire Dragon death roar', value: 0x00E5 },
  { label: 'Mamkute transform growl', value: 0x00E6 },
  { label: 'Brigand battle cry', value: 0x00E7 },
  { label: 'Nothing', value: 0x00E8 },
  { label: 'Nothing', value: 0x00E9 },
  { label: 'Axe falling', value: 0x00EA },
  { label: 'Axe rising', value: 0x00EB },
  { label: 'Nothing', value: 0x00EC },
  { label: 'Nothing', value: 0x00ED },
  { label: 'Nothing', value: 0x00EE },
  { label: 'Dance/Play effect', value: 0x00EF },
  { label: 'Divine weapon shine', value: 0x00F0 },
  { label: 'Fire charge', value: 0x00F1 },
  { label: 'Fire shoot', value: 0x00F2 },
  { label: 'Nothing', value: 0x00F3 },
  { label: 'Thunderstorm static', value: 0x00F4 },
  { label: 'Thunderstorm strike', value: 0x00F5 },
  { label: 'Shaman charging', value: 0x00F6 },
  { label: 'Weird rumbling', value: 0x00F7 },
  { label: 'Weird rumbling 2', value: 0x00F8 },
  { label: 'Berserk staff (realtime)', value: 0x00F9 },
  { label: 'Silence staff charging (realtime)', value: 0x00FA },
  { label: 'Silence staff forming (realtime)', value: 0x00FB },
  { label: 'Nothing', value: 0x00FC },
  { label: 'Rest staff (realtime)', value: 0x00FD },
  { label: 'Purge flash', value: 0x00FE },
  { label: 'Purge flash 2', value: 0x00FF },
  { label: 'Purge charging', value: 0x0100 },
  { label: 'Purge strike', value: 0x0101 },
  { label: 'Aureola light explosion (short)', value: 0x0102 },
  { label: 'Hammerne staff (realtime)', value: 0x0103 },
  { label: 'Nothing', value: 0x0104 },
  { label: 'Nothing', value: 0x0105 },
  { label: 'Nothing', value: 0x0106 },
  { label: 'Nothing', value: 0x0107 },
  { label: 'Nothing', value: 0x0108 },
  { label: 'Nothing', value: 0x0109 },
  { label: 'Flux charging', value: 0x010A },
  { label: 'Nothing', value: 0x010B },
  { label: 'Nothing', value: 0x010C },
  { label: 'Nothing', value: 0x010D },
  { label: 'Live staff', value: 0x010E },
  { label: 'Live staff', value: 0x010F },
  { label: 'Relive staff', value: 0x0110 },
  { label: 'Relive staff', value: 0x0111 },
  { label: 'Recover staff', value: 0x0112 },
  { label: 'Recover staff', value: 0x0113 },
  { label: 'Reserve staff (realtime)', value: 0x0114 },
  { label: 'Nothing', value: 0x0115 },
  { label: 'Nothing', value: 0x0116 },
  { label: 'Nothing', value: 0x0117 },
  { label: 'Nothing', value: 0x0118 },
  { label: 'Thunderstorm sparks', value: 0x0119 },
  { label: 'Thunderstorm strike', value: 0x011A },
  { label: 'Sleep charging (realtime)', value: 0x011B },
  { label: 'Sleep activating (realtime)', value: 0x011C },
  { label: 'Rumbling?', value: 0x011D },
  { label: 'Some kind of wind', value: 0x011E },
  { label: 'Weird charging sound', value: 0x011F },
  { label: 'Lightning charging', value: 0x0120 },
  { label: 'Lightning strike', value: 0x0121 },
  { label: 'Fimbulvetr wind', value: 0x0122 },
  { label: 'Fimbulvetr ice', value: 0x0123 },
  { label: 'Nosferatu symbol', value: 0x0124 },
  { label: 'Nosferatu drain', value: 0x0125 },
  { label: 'Nosferatu heal', value: 0x0126 },
  { label: 'Divine charging', value: 0x0127 },
  { label: 'Divine falling', value: 0x0128 },
  { label: 'Divine strike', value: 0x0129 },
  { label: 'Divine strike 2', value: 0x012A },
  { label: 'Aureola light bomb falling', value: 0x012B },
  { label: 'Aureola light explosion', value: 0x012C },
  { label: 'Nothing', value: 0x012D },
  { label: 'Nothing', value: 0x012E },
  { label: 'Nothing', value: 0x012F },
  { label: 'Nothing', value: 0x0130 },
  { label: 'Nothing', value: 0x0131 },
  { label: 'Nothing', value: 0x0132 },
  { label: 'Nothing', value: 0x0133 },
  { label: 'Nothing', value: 0x0134 },
  { label: 'Nothing', value: 0x0135 },
  { label: 'Nothing', value: 0x0136 },
  { label: 'Nothing', value: 0x0137 },
  { label: 'Nothing', value: 0x0138 },
  { label: 'Nothing', value: 0x0139 },
  { label: 'Nothing', value: 0x013A },
  { label: 'Nothing', value: 0x013B },
  { label: 'Nothing', value: 0x013C },
  { label: 'Nothing', value: 0x013D },
  { label: 'Nothing', value: 0x013E },
  { label: 'Nothing', value: 0x013F },
  { label: 'Nothing', value: 0x0140 },
  { label: 'Nothing', value: 0x0141 },
  { label: 'Nothing', value: 0x0142 },
  { label: 'Nothing', value: 0x0143 },
  { label: 'Nothing', value: 0x0144 },
  { label: 'Nothing', value: 0x0145 },
  { label: 'Nothing', value: 0x0146 },
  { label: 'Nothing', value: 0x0147 },
  { label: 'Nothing', value: 0x0148 },
  { label: 'Nothing', value: 0x0149 },
  { label: 'Nothing', value: 0x014A },
  { label: 'Nothing', value: 0x014B },
  { label: 'Nothing', value: 0x014C },
  { label: 'Nothing', value: 0x014D },
  { label: 'Soft step', value: 0x014E },
  { label: 'Soft step 2', value: 0x014F },
  { label: 'Soft step 3', value: 0x0150 },
  { label: 'Soft step 4', value: 0x0151 },
  { label: 'Nothing', value: 0x0152 },
  { label: 'Nothing', value: 0x0153 },
  { label: 'Soft step', value: 0x0154 },
  { label: 'Soft step 2', value: 0x0155 },
  { label: 'Soft step 3', value: 0x0156 },
  { label: 'Soft step 4', value: 0x0157 },
  { label: 'Soft step 5', value: 0x0158 },
  { label: 'The rest of high 01 just seems to be soft steps...', value: 0x0159 },
  { label: 'Nothing', value: 0x02A0 },
  { label: 'Nothing', value: 0x02A8 },
  { label: 'Nothing', value: 0x02B0 },
  { label: 'Nothing', value: 0x02B1 },
  { label: 'Nothing', value: 0x02B2 },
  { label: 'Nothing', value: 0x02B5 },
  { label: 'Nothing', value: 0x02B6 },
  { label: 'Nothing', value: 0x02B9 },
  { label: 'Nothing', value: 0x02BB },
  { label: 'Shine attack', value: 0x02BC },
  { label: 'Luna symbol', value: 0x02BD },
  { label: 'Luna hitting', value: 0x02BE },
  { label: 'Excalibur forming', value: 0x02BF },
  { label: 'Excalibur cutting', value: 0x02C0 },
  { label: 'Aura flash', value: 0x02C1 },
  { label: 'Aura going up', value: 0x02C2 },
  { label: 'Aura strike', value: 0x02C3 },
  { label: 'Luce flash', value: 0x02C4 },
  { label: 'Luce charging', value: 0x02C5 },
  { label: 'Luce flowing', value: 0x02C6 },
  { label: 'Gespenst symbol', value: 0x02C7 },
  { label: 'Gespenst clouds', value: 0x02C8 },
  { label: 'Gespenst strike', value: 0x02C9 },
  { label: 'Forblaze charging', value: 0x02CA },
  { label: 'Forblaze rising', value: 0x02CB },
  { label: 'Weird charging', value: 0x02CC },
  { label: 'Weird glittery sound', value: 0x02CD },
  { label: 'No damage', value: 0x02CE },
  { label: 'Weird pat sound', value: 0x02CF },
  { label: 'Eliwood\'s sword shining', value: 0x02D0 },
  { label: 'Eliwood\'s horse neighing', value: 0x02D1 },
  { label: 'Weird flaming sound', value: 0x02D2 },
  { label: 'Dancing', value: 0x02D3 },
  { label: 'Playing', value: 0x02D4 },
  { label: 'Dancing (map)', value: 0x02D5 },
  { label: 'Playing (map)', value: 0x02D6 },
  { label: 'Snag falling', value: 0x02D7 },
  { label: 'Weird charging sound', value: 0x02D8 },
  { label: 'Thud', value: 0x02D9 },
  { label: 'Sword unsheathing', value: 0x02DA },
  { label: 'Bizarre three sound effects', value: 0x02DB },
  { label: 'A ref whistle, what\'s this doing here?', value: 0x02DC },
  { label: 'Glittery sound', value: 0x02DD },
  { label: 'Shine sound', value: 0x02DE },
  { label: 'Shine sound 2', value: 0x02DF },
  { label: 'Weird rumbling', value: 0x02E0 },
  { label: 'Eclipse striking', value: 0x02E1 },
  { label: 'Eclipse striking (shorter)', value: 0x02E2 },
  { label: 'Dark Druid charging', value: 0x02E3 },
  { label: 'Nothing', value: 0x02E4 },
  { label: 'Nothing', value: 0x02E5 },
  { label: 'Nothing', value: 0x02E6 },
  { label: 'Nothing', value: 0x02E7 },
  { label: 'Dark Druid charging, then critical', value: 0x02E8 },
  { label: 'Magic shine', value: 0x02E9 },
  { label: 'Magic shine, long', value: 0x02EA },
  { label: 'Magic shine, longer', value: 0x02EB },
  { label: 'Magic shine, longer still', value: 0x02EC },
  { label: 'Magic shine, longest', value: 0x02ED },
  { label: 'Quintessence gathering', value: 0x02EE },
  { label: 'Ninian ressurrection', value: 0x02EF },
  { label: 'Rumbling at the Dragon\'s Gate', value: 0x02F0 },
  { label: 'Dragons screaming', value: 0x02F1 },
  { label: 'Fire Dragon dying', value: 0x02F2 },
  { label: 'Fire Dragon dying 2', value: 0x02F3 },
  { label: 'No damage', value: 0x02F4 },
  { label: 'High-pitched dragon yell', value: 0x02F5 },
  { label: 'Soft step', value: 0x02F6 },
  { label: 'Druid critical charge', value: 0x02F7 },
  { label: 'Sage critical conjuration', value: 0x02F8 },
  { label: 'Swish sound', value: 0x02F9 },
  { label: 'Icy sound', value: 0x02FA },
  { label: 'Fire Dragon attacking', value: 0x02FB },
  { label: 'Dragons attacking Athos', value: 0x02FC },
  { label: 'Ereshkigal charging', value: 0x02FD },
  { label: 'Ereshkigal strike', value: 0x02FE },
  { label: 'Swoosh sound', value: 0x02FF },
  { label: '???', value: 0x0300 },
];
