export const PromotionPointers = [
  { label: '0x8818300', value: 0 },
  { label: '0x8818320', value: 1 },
  { label: '0x8818340', value: 2 },
  { label: '0x8818360', value: 3 },
  { label: '0x8818380', value: 4 },
  { label: '0x88183A0', value: 5 },
  { label: '0x88183C0', value: 6 },
  { label: '0x88183E0', value: 7 },
  { label: '0x8818400', value: 8 },
  { label: '0x8818420', value: 9 },
  { label: '0x8818440', value: 10 },
  { label: '0x8818460', value: 11 },
  { label: '0x8818480', value: 12 },
  { label: '0x88184A0', value: 13 },
  { label: '0x88184C0', value: 14 },
  { label: '0x88184E0', value: 15 },
];

export const ClassList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Roy Lord', value: 0x01 },
  { label: 'Mercenary', value: 0x02 },
  { label: 'Mercenary (F)', value: 0x03 },
  { label: 'Hero', value: 0x04 },
  { label: 'Hero (F)', value: 0x05 },
  { label: 'Swordfighter', value: 0x06 },
  { label: 'Swordfighter (F)', value: 0x07 },
  { label: 'Swordmaster', value: 0x08 },
  { label: 'Swordmaster (F)', value: 0x09 },
  { label: 'Axefighter', value: 0x0A },
  { label: 'Warrior', value: 0x0B },
  { label: 'Armour Knight', value: 0x0C },
  { label: 'Armour Knight (F)', value: 0x0D },
  { label: 'General', value: 0x0E },
  { label: 'General (F)', value: 0x0F },
  { label: 'Archer', value: 0x10 },
  { label: 'Archer (F)', value: 0x11 },
  { label: 'Sniper', value: 0x12 },
  { label: 'Sniper (F)', value: 0x13 },
  { label: 'Priest', value: 0x14 },
  { label: 'Sister', value: 0x15 },
  { label: 'Bishop', value: 0x16 },
  { label: 'Bishop (F)', value: 0x17 },
  { label: 'Mage', value: 0x18 },
  { label: 'Mage (F)', value: 0x19 },
  { label: 'Sage', value: 0x1A },
  { label: 'Sage (F)', value: 0x1B },
  { label: 'Shaman', value: 0x1C },
  { label: 'Shaman (F)', value: 0x1D },
  { label: 'Druid', value: 0x1E },
  { label: 'Druid (F)', value: 0x1F },
  { label: 'Socialknight', value: 0x20 },
  { label: 'Socialknight (F) (messed up palette)', value: 0x21 },
  { label: 'Paladin', value: 0x22 },
  { label: 'Paladin (F) (messed up palette)', value: 0x23 },
  { label: 'Troubadour', value: 0x24 },
  { label: 'Valkyrie', value: 0x25 },
  { label: 'Nomad', value: 0x26 },
  { label: 'Nomad (F)', value: 0x27 },
  { label: 'Nomad Trooper', value: 0x28 },
  { label: 'Nomad Trooper (F)', value: 0x29 },
  { label: 'Pegasus Knight', value: 0x2A },
  { label: 'Falcon Knight', value: 0x2B },
  { label: 'Dragon Knight', value: 0x2C },
  { label: 'Dragon Knight (F)', value: 0x2D },
  { label: 'Dragon Master', value: 0x2E },
  { label: 'Dragon Master (F)', value: 0x2F },
  { label: 'Soldier', value: 0x30 },
  { label: 'Mountain Thief', value: 0x31 },
  { label: 'Pirate', value: 0x32 },
  { label: 'Berserker', value: 0x33 },
  { label: 'Thief', value: 0x34 },
  { label: 'Thief (F)', value: 0x35 },
  { label: 'Bard', value: 0x36 },
  { label: 'Dancer', value: 0x37 },
  { label: 'Mamkute', value: 0x38 },
  { label: 'Mamkute (F)', value: 0x39 },
  { label: 'Fire Dragon', value: 0x3A },
  { label: 'Divine Dragon', value: 0x3B },
  { label: 'Magic Dragon', value: 0x3C },
  { label: 'King', value: 0x3D },
  { label: 'Civilian', value: 0x3E },
  { label: 'Civilian (F)', value: 0x3F },
  { label: 'Child', value: 0x40 },
  { label: 'Child (F)', value: 0x41 },
  { label: 'Storage', value: 0x42 },
  { label: 'Roy Master Lord', value: 0x43 },
  { label: 'Archer on Long Arch', value: 0x44 },
  { label: 'Archer on Iron Arch', value: 0x45 },
  { label: 'Archer on Killer Arch', value: 0x46 },
  { label: 'Long Arch', value: 0x47 },
  { label: 'Iron Arch', value: 0x48 },
  { label: 'Killer Arch', value: 0x49 },
  { label: 'Disarmed Sniper (no standing sprites)', value: 0x4A },
  { label: 'Disarmed Sniper (F) (no standing sprites)', value: 0x4B },
];
