import React from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { Space } from 'antd';

export default function FE4HomePage() {
  const [buffer] = useOutletContext();

  return (
    <Space
      direction="vertical"
      align="center"
      style={{ width: '100%' }}
    >
      <Link to={{ pathname: '1stGenEditor', state: { buffer } }}>FE4 1st Gen Editor</Link>
      <Link to={{ pathname: '2ndGenerationStaticCharacterEditor1', state: { buffer } }}>FE4 2nd Generation Static Character Editor 1</Link>
      <Link to={{ pathname: '2ndGenerationStaticCharacterEditor2', state: { buffer } }}>FE4 2nd Generation Static Character Editor 2</Link>
      <Link to={{ pathname: '2ndGenerationStaticCharacterEditor3', state: { buffer } }}>FE4 2nd Generation Static Character Editor 3</Link>
      <Link to={{ pathname: 'ArmyEditor', state: { buffer } }}>FE4 Army Editor</Link>
      <Link to={{ pathname: 'ArmyPointerEditor', state: { buffer } }}>FE4 Army Pointer Editor</Link>
      <Link to={{ pathname: 'BattleMusicEditor', state: { buffer } }}>FE4 Battle Music Editor</Link>
      <Link to={{ pathname: 'BattleSpriteEditor', state: { buffer } }}>FE4 Battle Sprite Editor</Link>
      <Link to={{ pathname: 'BattleSpritePositionEditor', state: { buffer } }}>FE4 Battle Sprite Position Editor</Link>
      <Link to={{ pathname: 'BattleSpritePositionEditor2', state: { buffer } }}>FE4 Battle Sprite Position Editor 2</Link>
      <Link to={{ pathname: 'BrokenWeaponEditor', state: { buffer } }}>FE4 Broken Weapon Editor</Link>
      <Link to={{ pathname: 'ChapterIntroMusicEditor', state: { buffer } }}>FE4 Chapter Intro Music Editor</Link>
      <Link to={{ pathname: 'ChapterMusicEditor', state: { buffer } }}>FE4 Chapter Music Editor</Link>
      <Link to={{ pathname: 'ChapterMusicEditor2', state: { buffer } }}>FE4 Chapter Music Editor 2</Link>
      <Link to={{ pathname: 'CharNameEditorbase39C59', state: { buffer } }}>FE4 Char Name Editor (base $39C59)</Link>
      <Link to={{ pathname: 'CharPortraitEditor', state: { buffer } }}>FE4 Char Portrait Editor</Link>
      <Link to={{ pathname: 'CharacterSkillTableEditor', state: { buffer } }}>FE4 Character Skill Table Editor</Link>
      <Link to={{ pathname: 'ChildrenDefinition', state: { buffer } }}>FE4 Children Definition</Link>
      <Link to={{ pathname: 'Leaf', state: { buffer } }}>FE4 Children Editor 1 (Celice/Leaf)</Link>
      <Link to={{ pathname: 'ChildrenEditor2Altenna', state: { buffer } }}>FE4 Children Editor 2 (Altenna)</Link>
      <Link to={{ pathname: 'ChildrenEditor3', state: { buffer } }}>FE4 Children Editor 3</Link>
      <Link to={{ pathname: 'CircletEditor', state: { buffer } }}>FE4 Circlet Editor</Link>
      <Link to={{ pathname: 'ClassEditor', state: { buffer } }}>FE4 Class Editor</Link>
      <Link to={{ pathname: 'ClassNameEditorbase38CB3', state: { buffer } }}>FE4 Class Name Editor (base $38CB3)</Link>
      <Link to={{ pathname: 'ClassSkillTableEditor', state: { buffer } }}>FE4 Class Skill Table Editor</Link>
      <Link to={{ pathname: 'ClassesPortraitEditor', state: { buffer } }}>FE4 Classes Portrait Editor</Link>
      <Link to={{ pathname: 'CustomBattlePaletteEditor', state: { buffer } }}>FE4 Custom Battle Palette Editor</Link>
      <Link to={{ pathname: 'EnemyEditor1', state: { buffer } }}>FE4 Enemy Editor 1</Link>
      <Link to={{ pathname: 'EnemyEditor10', state: { buffer } }}>FE4 Enemy Editor 10</Link>
      <Link to={{ pathname: 'EnemyEditor11', state: { buffer } }}>FE4 Enemy Editor 11</Link>
      <Link to={{ pathname: 'EnemyEditor12', state: { buffer } }}>FE4 Enemy Editor 12</Link>
      <Link to={{ pathname: 'EnemyEditor13', state: { buffer } }}>FE4 Enemy Editor 13</Link>
      <Link to={{ pathname: 'EnemyEditor14', state: { buffer } }}>FE4 Enemy Editor 14</Link>
      <Link to={{ pathname: 'EnemyEditor15', state: { buffer } }}>FE4 Enemy Editor 15</Link>
      <Link to={{ pathname: 'EnemyEditor16', state: { buffer } }}>FE4 Enemy Editor 16</Link>
      <Link to={{ pathname: 'EnemyEditor17', state: { buffer } }}>FE4 Enemy Editor 17</Link>
      <Link to={{ pathname: 'EnemyEditor18', state: { buffer } }}>FE4 Enemy Editor 18</Link>
      <Link to={{ pathname: 'EnemyEditor19', state: { buffer } }}>FE4 Enemy Editor 19</Link>
      <Link to={{ pathname: 'EnemyEditor2', state: { buffer } }}>FE4 Enemy Editor 2</Link>
      <Link to={{ pathname: 'EnemyEditor20', state: { buffer } }}>FE4 Enemy Editor 20</Link>
      <Link to={{ pathname: 'EnemyEditor21', state: { buffer } }}>FE4 Enemy Editor 21</Link>
      <Link to={{ pathname: 'EnemyEditor22', state: { buffer } }}>FE4 Enemy Editor 22</Link>
      <Link to={{ pathname: 'EnemyEditor23', state: { buffer } }}>FE4 Enemy Editor 23</Link>
      <Link to={{ pathname: 'EnemyEditor24', state: { buffer } }}>FE4 Enemy Editor 24</Link>
      <Link to={{ pathname: 'EnemyEditor25', state: { buffer } }}>FE4 Enemy Editor 25</Link>
      <Link to={{ pathname: 'EnemyEditor26', state: { buffer } }}>FE4 Enemy Editor 26</Link>
      <Link to={{ pathname: 'EnemyEditor27', state: { buffer } }}>FE4 Enemy Editor 27</Link>
      <Link to={{ pathname: 'EnemyEditor28', state: { buffer } }}>FE4 Enemy Editor 28</Link>
      <Link to={{ pathname: 'EnemyEditor29', state: { buffer } }}>FE4 Enemy Editor 29</Link>
      <Link to={{ pathname: 'EnemyEditor3', state: { buffer } }}>FE4 Enemy Editor 3</Link>
      <Link to={{ pathname: 'EnemyEditor4', state: { buffer } }}>FE4 Enemy Editor 4</Link>
      <Link to={{ pathname: 'EnemyEditor5', state: { buffer } }}>FE4 Enemy Editor 5</Link>
      <Link to={{ pathname: 'EnemyEditor6', state: { buffer } }}>FE4 Enemy Editor 6</Link>
      <Link to={{ pathname: 'EnemyEditor7', state: { buffer } }}>FE4 Enemy Editor 7</Link>
      <Link to={{ pathname: 'EnemyEditor8', state: { buffer } }}>FE4 Enemy Editor 8</Link>
      <Link to={{ pathname: 'EnemyEditor9', state: { buffer } }}>FE4 Enemy Editor 9</Link>
      <Link to={{ pathname: 'HairColorEditor', state: { buffer } }}>FE4 Hair Color Editor</Link>
      <Link to={{ pathname: 'HolyBloodEditor', state: { buffer } }}>FE4 Holy Blood Editor</Link>
      <Link to={{ pathname: 'HolyCharacterEditor1', state: { buffer } }}>FE4 Holy Character Editor 1</Link>
      <Link to={{ pathname: 'HolyCharacterEditor10', state: { buffer } }}>FE4 Holy Character Editor 10</Link>
      <Link to={{ pathname: 'HolyCharacterEditor11', state: { buffer } }}>FE4 Holy Character Editor 11</Link>
      <Link to={{ pathname: 'HolyCharacterEditor12', state: { buffer } }}>FE4 Holy Character Editor 12</Link>
      <Link to={{ pathname: 'HolyCharacterEditor13', state: { buffer } }}>FE4 Holy Character Editor 13</Link>
      <Link to={{ pathname: 'HolyCharacterEditor14', state: { buffer } }}>FE4 Holy Character Editor 14</Link>
      <Link to={{ pathname: 'HolyCharacterEditor15', state: { buffer } }}>FE4 Holy Character Editor 15</Link>
      <Link to={{ pathname: 'HolyCharacterEditor16', state: { buffer } }}>FE4 Holy Character Editor 16</Link>
      <Link to={{ pathname: 'HolyCharacterEditor17', state: { buffer } }}>FE4 Holy Character Editor 17</Link>
      <Link to={{ pathname: 'HolyCharacterEditor18', state: { buffer } }}>FE4 Holy Character Editor 18</Link>
      <Link to={{ pathname: 'HolyCharacterEditor19', state: { buffer } }}>FE4 Holy Character Editor 19</Link>
      <Link to={{ pathname: 'HolyCharacterEditor2', state: { buffer } }}>FE4 Holy Character Editor 2</Link>
      <Link to={{ pathname: 'HolyCharacterEditor3', state: { buffer } }}>FE4 Holy Character Editor 3</Link>
      <Link to={{ pathname: 'HolyCharacterEditor4', state: { buffer } }}>FE4 Holy Character Editor 4</Link>
      <Link to={{ pathname: 'HolyCharacterEditor5', state: { buffer } }}>FE4 Holy Character Editor 5</Link>
      <Link to={{ pathname: 'HolyCharacterEditor6', state: { buffer } }}>FE4 Holy Character Editor 6</Link>
      <Link to={{ pathname: 'HolyCharacterEditor7', state: { buffer } }}>FE4 Holy Character Editor 7</Link>
      <Link to={{ pathname: 'HolyCharacterEditor8', state: { buffer } }}>FE4 Holy Character Editor 8</Link>
      <Link to={{ pathname: 'HolyCharacterEditor9', state: { buffer } }}>FE4 Holy Character Editor 9</Link>
      <Link to={{ pathname: 'HolyCharacterLeptor', state: { buffer } }}>FE4 Holy Character Leptor</Link>
      <Link to={{ pathname: 'HolyWeaponFlashEditor', state: { buffer } }}>FE4 Holy Weapon Flash Editor</Link>
      <Link to={{ pathname: 'HolyWeaponFlashEditorModified', state: { buffer } }}>FE4 Holy Weapon Flash Editor (Modified)</Link>
      <Link to={{ pathname: 'ItemEditor', state: { buffer } }}>FE4 Item Editor</Link>
      <Link to={{ pathname: 'ItemNameEditorbase3DE12', state: { buffer } }}>FE4 Item Name Editor (base $3DE12)</Link>
      <Link to={{ pathname: 'ItemSkillTableEditor', state: { buffer } }}>FE4 Item Skill Table Editor</Link>
      <Link to={{ pathname: 'ItemSpriteEditor', state: { buffer } }}>FE4 Item Sprite Editor</Link>
      <Link to={{ pathname: 'LoveBases1stGeneration', state: { buffer } }}>FE4 Love Bases - 1st Generation</Link>
      <Link to={{ pathname: 'LoveConversations', state: { buffer } }}>FE4 Love Conversations</Link>
      <Link to={{ pathname: 'LoveGrowths2ndGeneration', state: { buffer } }}>FE4 Love Growths -  2nd Generation</Link>
      <Link to={{ pathname: 'LoveGrowths1stGeneration', state: { buffer } }}>FE4 Love Growths - 1st Generation</Link>
      <Link to={{ pathname: 'LovesBases2ndGeneration', state: { buffer } }}>FE4 Loves Bases -  2nd Generation</Link>
      <Link to={{ pathname: 'MagicAnimationEditor', state: { buffer } }}>FE4 Magic Animation Editor</Link>
      <Link to={{ pathname: 'MagicAnimationPointerEditorbase17917Dupto0x4C', state: { buffer } }}>FE4 Magic Animation Pointer Editor (base 17917D, up to 0x4C)</Link>
      <Link to={{ pathname: 'Fe4MapSpriteEditor', state: { buffer } }}>Fe4 Map Sprite Editor</Link>
      <Link to={{ pathname: 'PlayerWeaponEditor', state: { buffer } }}>FE4 Player Weapon Editor</Link>
      <Link to={{ pathname: 'PromotionEditor', state: { buffer } }}>FE4 Promotion Editor</Link>
      <Link to={{ pathname: 'RingEditor', state: { buffer } }}>FE4 Ring Editor</Link>
      <Link to={{ pathname: 'ShieldDefinitionEditor', state: { buffer } }}>FE4 Shield Definition Editor</Link>
      <Link to={{ pathname: 'ShieldSpriteEditor', state: { buffer } }}>FE4 Shield Sprite Editor</Link>
      <Link to={{ pathname: 'ShopEditorChapter12', state: { buffer } }}>FE4 Shop Editor - Chapter 1 & 2</Link>
      <Link to={{ pathname: 'ShopEditorChapter10', state: { buffer } }}>FE4 Shop Editor - Chapter 10</Link>
      <Link to={{ pathname: 'ShopEditorChapter3', state: { buffer } }}>FE4 Shop Editor - Chapter 3</Link>
      <Link to={{ pathname: 'ShopEditorChapter4', state: { buffer } }}>FE4 Shop Editor - Chapter 4</Link>
      <Link to={{ pathname: 'ShopEditorChapter6', state: { buffer } }}>FE4 Shop Editor - Chapter 6</Link>
      <Link to={{ pathname: 'ShopEditorChapter7', state: { buffer } }}>FE4 Shop Editor - Chapter 7</Link>
      <Link to={{ pathname: 'ShopEditorChapter8', state: { buffer } }}>FE4 Shop Editor - Chapter 8</Link>
      <Link to={{ pathname: 'ShopEditorChapter9', state: { buffer } }}>FE4 Shop Editor - Chapter 9</Link>
      <Link to={{ pathname: 'SiblingBonusEditor', state: { buffer } }}>FE4 Sibling Bonus Editor</Link>
      <Link to={{ pathname: 'SkillDisplayEditor1StatScreen', state: { buffer } }}>FE4 Skill Display Editor 1 (Stat Screen)</Link>
      <Link to={{ pathname: 'SkillDisplayEditor2StatScreenDescription', state: { buffer } }}>FE4 Skill Display Editor 2 (Stat Screen Description)</Link>
      <Link to={{ pathname: 'SkillDisplayEditor3SkillListDescription', state: { buffer } }}>FE4 Skill Display Editor 3 (Skill List Description)</Link>
      <Link to={{ pathname: 'TerrainMovementCostEditor', state: { buffer } }}>FE4 Terrain Movement Cost Editor</Link>
      <Link to={{ pathname: 'TriangleAttackEditor', state: { buffer } }}>FE4 Triangle Attack Editor</Link>
      <Link to={{ pathname: 'WeaponBonusEditor', state: { buffer } }}>FE4 Weapon Bonus Editor</Link>
      <Link to={{ pathname: 'StaffEditor1', state: { buffer } }}>FE4 Weapon/Staff Editor 1</Link>
      <Link to={{ pathname: 'StaffEditor2', state: { buffer } }}>FE4 Weapon/Staff Editor 2</Link>
    </Space>
  );
}
