export const FE4SiblingBonusEditorEntries = [
  { label: 'Consecutive characters have a bonus, end a group with 0x00', value: 0 },
];

export const FE4SiblingNumbers = [
  { label: 'None / End', value: 0x00 },
  { label: 'Sigurd', value: 0x01 },
  { label: 'Noish', value: 0x02 },
  { label: 'Alec', value: 0x03 },
  { label: 'Arden', value: 0x04 },
  { label: 'Young Fin', value: 0x05 },
  { label: 'Cuan', value: 0x06 },
  { label: 'Mideel', value: 0x07 },
  { label: 'Levin', value: 0x08 },
  { label: 'Holyn', value: 0x09 },
  { label: 'Azel', value: 0x0A },
  { label: 'Jamuka', value: 0x0B },
  { label: 'Claud', value: 0x0C },
  { label: 'Beowulf', value: 0x0D },
  { label: 'Lex', value: 0x0E },
  { label: 'Dew', value: 0x0F },
  { label: 'Diadora', value: 0x10 },
  { label: 'Ethlin', value: 0x11 },
  { label: 'Lachesis', value: 0x12 },
  { label: 'Ira', value: 0x13 },
  { label: 'Fury', value: 0x14 },
  { label: 'Tiltyu', value: 0x15 },
  { label: 'Sylvia', value: 0x16 },
  { label: 'Edin', value: 0x17 },
  { label: 'Bridget', value: 0x18 },
  { label: 'Celice', value: 0x19 },
  { label: 'Shanan', value: 0x1A },
  { label: 'Rodolban', value: 0x1B },
  { label: 'Asaello', value: 0x1C },
  { label: 'Leaf', value: 0x1D },
  { label: 'Johan', value: 0x1E },
  { label: 'Sharlow', value: 0x1F },
  { label: 'Hawk', value: 0x20 },
  { label: 'Tristan', value: 0x21 },
  { label: 'Adult Fin', value: 0x22 },
  { label: 'Dimna', value: 0x23 },
  { label: 'Hannibal', value: 0x24 },
  { label: 'Aless', value: 0x25 },
  { label: 'Amid', value: 0x26 },
  { label: 'Oifaye', value: 0x27 },
  { label: 'Daisy', value: 0x28 },
  { label: 'Radney', value: 0x29 },
  { label: 'Mana', value: 0x2A },
  { label: 'Julia', value: 0x2B },
  { label: 'Altenna', value: 0x2C },
  { label: 'Femina', value: 0x2D },
  { label: 'Linda', value: 0x2E },
  { label: 'Laylea', value: 0x2F },
  { label: 'Janne', value: 0x30 },
  { label: 'Johalva', value: 0x31 },
  { label: 'Skasaher', value: 0x32 },
  { label: 'Faval', value: 0x33 },
  { label: 'Corple', value: 0x34 },
  { label: 'Sety', value: 0x35 },
  { label: 'Delmud', value: 0x36 },
  { label: 'Lester', value: 0x37 },
  { label: 'Arthur', value: 0x38 },
  { label: 'Patty', value: 0x39 },
  { label: 'Lakche', value: 0x3A },
  { label: 'Rana', value: 0x3B },
  { label: 'Fee', value: 0x3C },
  { label: 'Tinny', value: 0x3D },
  { label: 'Lynn', value: 0x3E },
  { label: 'Nanna', value: 0x3F },
];
