import React from 'react';
import { useOutletContext, useSearchParams } from 'react-router-dom';
import { Space, Alert, BackTop } from 'antd';
import { ToTopOutlined } from '@ant-design/icons';
import {
  FE4ArmyPointerEditorEntries,
} from './options';
import InputSelect from '../../../Input/InputSelect';
import InputHexArray from '../../../Input/InputHexArray';

export default function FE4ArmyPointerEditor() {
  const [buffer] = useOutletContext();
  const [searchParams, setSearchParams] = useSearchParams();

  const id = searchParams.get('id');
  const address = 0x1C200;
  const size = 144;
  let view = null;

  try {
    view = new DataView(buffer, address + size * id, size);
  } catch (error) {
    view = null;
  }

  return (
    <Space
      direction="vertical"
      align="center"
      style={{ width: '100%' }}
    >
      <Alert
        message="FE4 Army Pointer Editor"
        type="info"
      />
      <div key={id}>
        <InputSelect
          disabled={view == null}
          defaultValue={FE4ArmyPointerEditorEntries.find(
            (entry) => entry.value.toString() === id,
          ) ?? id}
          onSelect={(value) => setSearchParams({ id: value })}
          options={FE4ArmyPointerEditorEntries}
        />
      </div>
      <InputHexArray
        length={2}
        view={view}
        name="00"
        offset={0}
      />
      <InputHexArray
        length={2}
        view={view}
        name="01"
        offset={2}
      />
      <InputHexArray
        length={2}
        view={view}
        name="02"
        offset={4}
      />
      <InputHexArray
        length={2}
        view={view}
        name="03"
        offset={6}
      />
      <InputHexArray
        length={2}
        view={view}
        name="04"
        offset={8}
      />
      <InputHexArray
        length={2}
        view={view}
        name="05"
        offset={10}
      />
      <InputHexArray
        length={2}
        view={view}
        name="06"
        offset={12}
      />
      <InputHexArray
        length={2}
        view={view}
        name="07"
        offset={14}
      />
      <InputHexArray
        length={2}
        view={view}
        name="08"
        offset={16}
      />
      <InputHexArray
        length={2}
        view={view}
        name="09"
        offset={18}
      />
      <InputHexArray
        length={2}
        view={view}
        name="0A"
        offset={20}
      />
      <InputHexArray
        length={2}
        view={view}
        name="0B"
        offset={22}
      />
      <InputHexArray
        length={2}
        view={view}
        name="0C"
        offset={24}
      />
      <InputHexArray
        length={2}
        view={view}
        name="0D"
        offset={26}
      />
      <InputHexArray
        length={2}
        view={view}
        name="0E"
        offset={28}
      />
      <InputHexArray
        length={2}
        view={view}
        name="0F"
        offset={30}
      />
      <InputHexArray
        length={2}
        view={view}
        name="10"
        offset={32}
      />
      <InputHexArray
        length={2}
        view={view}
        name="11"
        offset={34}
      />
      <InputHexArray
        length={2}
        view={view}
        name="12"
        offset={36}
      />
      <InputHexArray
        length={2}
        view={view}
        name="13"
        offset={38}
      />
      <InputHexArray
        length={2}
        view={view}
        name="14"
        offset={40}
      />
      <InputHexArray
        length={2}
        view={view}
        name="15"
        offset={42}
      />
      <InputHexArray
        length={2}
        view={view}
        name="16"
        offset={44}
      />
      <InputHexArray
        length={2}
        view={view}
        name="17"
        offset={46}
      />
      <InputHexArray
        length={2}
        view={view}
        name="18"
        offset={48}
      />
      <InputHexArray
        length={2}
        view={view}
        name="19"
        offset={50}
      />
      <InputHexArray
        length={2}
        view={view}
        name="1A"
        offset={52}
      />
      <InputHexArray
        length={2}
        view={view}
        name="1B"
        offset={54}
      />
      <InputHexArray
        length={2}
        view={view}
        name="1C"
        offset={56}
      />
      <InputHexArray
        length={2}
        view={view}
        name="1D"
        offset={58}
      />
      <InputHexArray
        length={2}
        view={view}
        name="1E"
        offset={60}
      />
      <InputHexArray
        length={2}
        view={view}
        name="1F"
        offset={62}
      />
      <InputHexArray
        length={2}
        view={view}
        name="20"
        offset={64}
      />
      <InputHexArray
        length={2}
        view={view}
        name="21"
        offset={66}
      />
      <InputHexArray
        length={2}
        view={view}
        name="22"
        offset={68}
      />
      <InputHexArray
        length={2}
        view={view}
        name="23"
        offset={70}
      />
      <InputHexArray
        length={2}
        view={view}
        name="24"
        offset={72}
      />
      <InputHexArray
        length={2}
        view={view}
        name="25"
        offset={74}
      />
      <InputHexArray
        length={2}
        view={view}
        name="26"
        offset={76}
      />
      <InputHexArray
        length={2}
        view={view}
        name="27"
        offset={78}
      />
      <InputHexArray
        length={2}
        view={view}
        name="28"
        offset={80}
      />
      <InputHexArray
        length={2}
        view={view}
        name="29"
        offset={82}
      />
      <InputHexArray
        length={2}
        view={view}
        name="2A"
        offset={84}
      />
      <InputHexArray
        length={2}
        view={view}
        name="2B"
        offset={86}
      />
      <InputHexArray
        length={2}
        view={view}
        name="2C"
        offset={88}
      />
      <InputHexArray
        length={2}
        view={view}
        name="2D"
        offset={90}
      />
      <InputHexArray
        length={2}
        view={view}
        name="2E"
        offset={92}
      />
      <InputHexArray
        length={2}
        view={view}
        name="2F"
        offset={94}
      />
      <InputHexArray
        length={2}
        view={view}
        name="30"
        offset={96}
      />
      <InputHexArray
        length={2}
        view={view}
        name="31"
        offset={98}
      />
      <InputHexArray
        length={2}
        view={view}
        name="32"
        offset={100}
      />
      <InputHexArray
        length={2}
        view={view}
        name="33"
        offset={102}
      />
      <InputHexArray
        length={2}
        view={view}
        name="34"
        offset={104}
      />
      <InputHexArray
        length={2}
        view={view}
        name="35"
        offset={106}
      />
      <InputHexArray
        length={2}
        view={view}
        name="36"
        offset={108}
      />
      <InputHexArray
        length={2}
        view={view}
        name="37"
        offset={110}
      />
      <InputHexArray
        length={2}
        view={view}
        name="38"
        offset={112}
      />
      <InputHexArray
        length={2}
        view={view}
        name="39"
        offset={114}
      />
      <InputHexArray
        length={2}
        view={view}
        name="3A"
        offset={116}
      />
      <InputHexArray
        length={2}
        view={view}
        name="3B"
        offset={118}
      />
      <InputHexArray
        length={2}
        view={view}
        name="3C"
        offset={120}
      />
      <InputHexArray
        length={2}
        view={view}
        name="3D"
        offset={122}
      />
      <InputHexArray
        length={2}
        view={view}
        name="3E"
        offset={124}
      />
      <InputHexArray
        length={2}
        view={view}
        name="3F"
        offset={126}
      />
      <InputHexArray
        length={2}
        view={view}
        name="40"
        offset={128}
      />
      <InputHexArray
        length={2}
        view={view}
        name="41"
        offset={130}
      />
      <InputHexArray
        length={2}
        view={view}
        name="42"
        offset={132}
      />
      <InputHexArray
        length={2}
        view={view}
        name="43"
        offset={134}
      />
      <InputHexArray
        length={2}
        view={view}
        name="44"
        offset={136}
      />
      <InputHexArray
        length={2}
        view={view}
        name="45"
        offset={138}
      />
      <InputHexArray
        length={2}
        view={view}
        name="46"
        offset={140}
      />
      <InputHexArray
        length={2}
        view={view}
        name="47"
        offset={142}
      />

      <BackTop>
        <ToTopOutlined />
      </BackTop>
    </Space>
  );
}
