export const FE8RandomItemGroupsTableEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
];

export const ItemList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Iron Sword', value: 0x01 },
  { label: 'Slim Sword', value: 0x02 },
  { label: 'Steel Sword', value: 0x03 },
  { label: 'Silver Sword', value: 0x04 },
  { label: 'Iron Blade', value: 0x05 },
  { label: 'Steel Blade', value: 0x06 },
  { label: 'Silver Blade', value: 0x07 },
  { label: 'Poison Sword', value: 0x08 },
  { label: 'Rapier', value: 0x09 },
  { label: 'Mani Katti (DUMMY)', value: 0x0A },
  { label: 'Brave Sword', value: 0x0B },
  { label: 'Shamshir', value: 0x0C },
  { label: 'Killing Edge', value: 0x0D },
  { label: 'Armorslayer', value: 0x0E },
  { label: 'Wyrmslayer', value: 0x0F },
  { label: 'Light Brand', value: 0x10 },
  { label: 'Runesword', value: 0x11 },
  { label: 'Lancereaver', value: 0x12 },
  { label: 'Zanbato', value: 0x13 },
  { label: 'Iron Lance', value: 0x14 },
  { label: 'Slim Lance', value: 0x15 },
  { label: 'Steel Lance', value: 0x16 },
  { label: 'Silver Lance', value: 0x17 },
  { label: 'Toxin Lance', value: 0x18 },
  { label: 'Brave Lance', value: 0x19 },
  { label: 'Killer Lance', value: 0x1A },
  { label: 'Horseslayer', value: 0x1B },
  { label: 'Javelin', value: 0x1C },
  { label: 'Spear', value: 0x1D },
  { label: 'Axereaver', value: 0x1E },
  { label: 'Iron Axe', value: 0x1F },
  { label: 'Steel Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Poison Axe', value: 0x22 },
  { label: 'Brave Axe', value: 0x23 },
  { label: 'Killer Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Hammer', value: 0x26 },
  { label: 'Devil Axe', value: 0x27 },
  { label: 'Hand Axe', value: 0x28 },
  { label: 'Tomahawk', value: 0x29 },
  { label: 'Swordreaver', value: 0x2A },
  { label: 'Swordslayer', value: 0x2B },
  { label: 'Hatchet', value: 0x2C },
  { label: 'Iron Bow', value: 0x2D },
  { label: 'Steel Bow', value: 0x2E },
  { label: 'Silver Bow', value: 0x2F },
  { label: 'Poison Bow', value: 0x30 },
  { label: 'Killer Bow', value: 0x31 },
  { label: 'Brave Bow', value: 0x32 },
  { label: 'Short Bow', value: 0x33 },
  { label: 'Longbow', value: 0x34 },
  { label: 'Ballista', value: 0x35 },
  { label: 'Iron Ballista', value: 0x36 },
  { label: 'Killer Ballista', value: 0x37 },
  { label: 'Fire', value: 0x38 },
  { label: 'Thunder', value: 0x39 },
  { label: 'Elfire', value: 0x3A },
  { label: 'Bolting', value: 0x3B },
  { label: 'Fimbulvetr', value: 0x3C },
  { label: 'Forblaze (DUMMY)', value: 0x3D },
  { label: 'Excalibur', value: 0x3E },
  { label: 'Lightning', value: 0x3F },
  { label: 'Shine', value: 0x40 },
  { label: 'Divine', value: 0x41 },
  { label: 'Purge', value: 0x42 },
  { label: 'Aura', value: 0x43 },
  { label: 'Luce (DUMMY)', value: 0x44 },
  { label: 'Flux', value: 0x45 },
  { label: 'Luna', value: 0x46 },
  { label: 'Nosferatu', value: 0x47 },
  { label: 'Eclipse', value: 0x48 },
  { label: 'Fenrir', value: 0x49 },
  { label: 'Gleipnir', value: 0x4A },
  { label: 'Heal', value: 0x4B },
  { label: 'Mend', value: 0x4C },
  { label: 'Recover', value: 0x4D },
  { label: 'Physic', value: 0x4E },
  { label: 'Fortify', value: 0x4F },
  { label: 'Restore', value: 0x50 },
  { label: 'Silence', value: 0x51 },
  { label: 'Sleep', value: 0x52 },
  { label: 'Berserk', value: 0x53 },
  { label: 'Warp', value: 0x54 },
  { label: 'Rescue', value: 0x55 },
  { label: 'Torch', value: 0x56 },
  { label: 'Hammerne', value: 0x57 },
  { label: 'Unlock', value: 0x58 },
  { label: 'Barrier', value: 0x59 },
  { label: 'Dragon Axe', value: 0x5A },
  { label: 'Angelic Robe', value: 0x5B },
  { label: 'Energy Ring', value: 0x5C },
  { label: 'Secret Book', value: 0x5D },
  { label: 'Speedwings', value: 0x5E },
  { label: 'Goddess Icon', value: 0x5F },
  { label: 'Dragonshield', value: 0x60 },
  { label: 'Talisman', value: 0x61 },
  { label: 'Swiftsoles', value: 0x62 },
  { label: 'Body Ring', value: 0x63 },
  { label: 'Hero Crest', value: 0x64 },
  { label: 'Knight Crest', value: 0x65 },
  { label: 'Orion\'s Bolt', value: 0x66 },
  { label: 'Elysian Whip', value: 0x67 },
  { label: 'Guiding Ring', value: 0x68 },
  { label: 'Chest Key', value: 0x69 },
  { label: 'Door Key', value: 0x6A },
  { label: 'Lockpick', value: 0x6B },
  { label: 'Vulnerary', value: 0x6C },
  { label: 'Elixir', value: 0x6D },
  { label: 'Pure Water', value: 0x6E },
  { label: 'Antidote', value: 0x6F },
  { label: 'Torch', value: 0x70 },
  { label: 'Filli Shield', value: 0x71 },
  { label: 'Member Card', value: 0x72 },
  { label: 'Silver Card', value: 0x73 },
  { label: 'White Gem', value: 0x74 },
  { label: 'Blue Gem', value: 0x75 },
  { label: 'Red Gem', value: 0x76 },
  { label: '1G', value: 0x77 },
  { label: 'Reginleif', value: 0x78 },
  { label: 'Chest Key (5)', value: 0x79 },
  { label: 'Mine (DUMMY)', value: 0x7A },
  { label: 'Light Rune (DUMMY)', value: 0x7B },
  { label: 'Hoplon Guard', value: 0x7C },
  { label: 'Filla\'s Might (DUMMY)', value: 0x7D },
  { label: 'Ninis\'s Grace (DUMMY)', value: 0x7E },
  { label: 'Thor\'s Ire (DUMMY)', value: 0x7F },
  { label: 'Set\'s Litany (DUMMY)', value: 0x80 },
  { label: 'Shadow Killer', value: 0x81 },
  { label: 'Bright Lance', value: 0x82 },
  { label: 'Fiend Cleaver', value: 0x83 },
  { label: 'Beacon Bow', value: 0x84 },
  { label: 'Sieglinde', value: 0x85 },
  { label: 'Battle Axe', value: 0x86 },
  { label: 'Ivaldi', value: 0x87 },
  { label: 'Master Seal', value: 0x88 },
  { label: 'Metis\'s Tome', value: 0x89 },
  { label: 'Heaven Seal (DUMMY)', value: 0x8A },
  { label: 'Sharp Claw', value: 0x8B },
  { label: 'Latona', value: 0x8C },
  { label: 'Dragonspear', value: 0x8D },
  { label: 'Vidofnir', value: 0x8E },
  { label: 'Naglfar', value: 0x8F },
  { label: 'Wretched Air', value: 0x90 },
  { label: 'Audhulma', value: 0x91 },
  { label: 'Siegmund', value: 0x92 },
  { label: 'Garm', value: 0x93 },
  { label: 'Nidhogg', value: 0x94 },
  { label: 'Heavy Spear', value: 0x95 },
  { label: 'Short Spear', value: 0x96 },
  { label: 'Ocean Seal', value: 0x97 },
  { label: 'Lunar Brace', value: 0x98 },
  { label: 'Solar Brace', value: 0x99 },
  { label: '1G', value: 0x9A },
  { label: '5G', value: 0x9B },
  { label: '10G', value: 0x9C },
  { label: '50G', value: 0x9D },
  { label: '100G', value: 0x9E },
  { label: '3000G', value: 0x9F },
  { label: '5000G', value: 0xA0 },
  { label: 'Wind Sword', value: 0xA1 },
  { label: 'Vulnerary', value: 0xA2 },
  { label: 'Vulnerary (green note)', value: 0xA3 },
  { label: 'Vulnerary (red note)', value: 0xA4 },
  { label: 'Dance', value: 0xA5 },
  { label: 'Nightmare', value: 0xA6 },
  { label: '[Demon Shard]', value: 0xA7 },
  { label: 'Demon Light', value: 0xA8 },
  { label: 'Ravager', value: 0xA9 },
  { label: 'Dragonstone', value: 0xAA },
  { label: 'Demon Surge', value: 0xAB },
  { label: 'Shadowshot', value: 0xAC },
  { label: 'Rotten Claw', value: 0xAD },
  { label: 'Fetid Claw', value: 0xAE },
  { label: 'Poison Claw', value: 0xAF },
  { label: 'Lethal Talon', value: 0xB0 },
  { label: 'Fiery Fang', value: 0xB1 },
  { label: 'Hellfang', value: 0xB2 },
  { label: 'Evil Eye', value: 0xB3 },
  { label: 'Crimson Eye', value: 0xB4 },
  { label: 'Stone', value: 0xB5 },
  { label: 'Aircalibur', value: 0xB6 },
  { label: 'Juna Fruit', value: 0xB7 },
  { label: '150G', value: 0xB8 },
  { label: '200G', value: 0xB9 },
  { label: 'Black Gem', value: 0xBA },
  { label: 'Gold Gem', value: 0xBB },
  { label: '-', value: 0xBC },
  { label: '-', value: 0xBD },
  { label: '-', value: 0xBE },
  { label: '-', value: 0xBF },
  { label: '-', value: 0xC0 },
  { label: '-', value: 0xC1 },
  { label: '-', value: 0xC2 },
  { label: '-', value: 0xC3 },
  { label: '-', value: 0xC4 },
  { label: '-', value: 0xC5 },
  { label: '-', value: 0xC6 },
  { label: '-', value: 0xC7 },
  { label: '-', value: 0xC8 },
  { label: '-', value: 0xC9 },
  { label: '-', value: 0xCA },
  { label: '-', value: 0xCB },
  { label: '-', value: 0xCC },
  { label: '-', value: 0xCD },
  { label: '-', value: 0xCE },
  { label: '-', value: 0xCF },
  { label: '-', value: 0xD0 },
  { label: '-', value: 0xD1 },
  { label: '-', value: 0xD2 },
  { label: '-', value: 0xD3 },
  { label: '-', value: 0xD4 },
  { label: '-', value: 0xD5 },
  { label: '-', value: 0xD6 },
  { label: '-', value: 0xD7 },
  { label: '-', value: 0xD8 },
  { label: '-', value: 0xD9 },
  { label: '-', value: 0xDA },
  { label: '-', value: 0xDB },
  { label: '-', value: 0xDC },
  { label: '-', value: 0xDD },
  { label: '-', value: 0xDE },
  { label: '-', value: 0xDF },
  { label: '-', value: 0xE0 },
  { label: '-', value: 0xE1 },
  { label: '-', value: 0xE2 },
  { label: '-', value: 0xE3 },
  { label: '-', value: 0xE4 },
  { label: '-', value: 0xE5 },
  { label: '-', value: 0xE6 },
  { label: '-', value: 0xE7 },
  { label: '-', value: 0xE8 },
  { label: '-', value: 0xE9 },
  { label: '-', value: 0xEA },
  { label: '-', value: 0xEB },
  { label: '-', value: 0xEC },
  { label: '-', value: 0xED },
  { label: '-', value: 0xEE },
  { label: '-', value: 0xEF },
  { label: '-', value: 0xF0 },
  { label: '-', value: 0xF1 },
  { label: '-', value: 0xF2 },
  { label: '-', value: 0xF3 },
  { label: '-', value: 0xF4 },
  { label: '-', value: 0xF5 },
  { label: '-', value: 0xF6 },
  { label: '-', value: 0xF7 },
  { label: '-', value: 0xF8 },
  { label: '-', value: 0xF9 },
  { label: '-', value: 0xFA },
  { label: '-', value: 0xFB },
  { label: '-', value: 0xFC },
  { label: '-', value: 0xFD },
  { label: '-', value: 0xFE },
  { label: '-', value: 0xFF },
];
