export const ClassSlotsEditor = [
  { label: 'Chapter 1', value: 0 },
  { label: 'Chapter 2', value: 1 },
  { label: 'Chapter 3', value: 2 },
  { label: 'Chapter 4', value: 3 },
  { label: 'Chapter 5', value: 4 },
  { label: 'Chapter 6', value: 5 },
  { label: 'Chapter 7', value: 6 },
  { label: 'Chapter 8', value: 7 },
  { label: 'Chapter 9', value: 8 },
  { label: 'Chapter 10', value: 9 },
  { label: 'Chapter 11', value: 10 },
  { label: 'Chapter 12', value: 11 },
  { label: 'Chapter 13', value: 12 },
  { label: 'Chapter 14', value: 13 },
  { label: 'Chapter 15', value: 14 },
  { label: 'Chapter 16', value: 15 },
  { label: 'Chapter 17', value: 16 },
  { label: 'Chapter 18', value: 17 },
  { label: 'Chapter 19', value: 18 },
  { label: 'Chapter 20', value: 19 },
  { label: 'Chapter 21', value: 20 },
  { label: 'Chapter 22', value: 21 },
  { label: 'Chapter 23', value: 22 },
  { label: 'Chapter 24', value: 23 },
  { label: 'Chapter 3x', value: 24 },
  { label: 'Chapter 6x', value: 25 },
  { label: 'Chapter 10x', value: 26 },
  { label: 'Chapter 13x', value: 27 },
  { label: 'Chapter 16x', value: 28 },
  { label: 'Chapter 20x', value: 29 },
];

export default ClassSlotsEditor;
