import React from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { Space } from 'antd';

export default function FE3HomePage() {
  const [buffer] = useOutletContext();

  return (
    <Space
      direction="vertical"
      align="center"
      style={{ width: '100%' }}
    >
      <Link to={{ pathname: '11MarthEmbarksHidden', state: { buffer } }}>1-1: Marth Embarks (Hidden)</Link>
      <Link to={{ pathname: '110TheAgelessPalaceHidden', state: { buffer } }}>1-10: The Ageless Palace (Hidden)</Link>
      <Link to={{ pathname: '110TheAgelessPalaceStart', state: { buffer } }}>1-10: The Ageless Palace (Start)</Link>
      <Link to={{ pathname: '111LandofSorrowHidden', state: { buffer } }}>1-11: Land of Sorrow (Hidden)</Link>
      <Link to={{ pathname: '111LandofSorrowStart', state: { buffer } }}>1-11: Land of Sorrow (Start)</Link>
      <Link to={{ pathname: '112AnOasisofMagicStart', state: { buffer } }}>1-12: An Oasis of Magic (Start)</Link>
      <Link to={{ pathname: '113TheBattleforAlteaHidden', state: { buffer } }}>1-13: The Battle for Altea (Hidden)</Link>
      <Link to={{ pathname: '113TheBattleforAlteaStart', state: { buffer } }}>1-13: The Battle for Altea (Start)</Link>
      <Link to={{ pathname: '114StarandSaviorHidden', state: { buffer } }}>1-14: Star and Savior (Hidden)</Link>
      <Link to={{ pathname: '114StarandSaviorStart', state: { buffer } }}>1-14: Star and Savior (Start)</Link>
      <Link to={{ pathname: '115ManaketePrincessHidden', state: { buffer } }}>1-15: Manakete Princess (Hidden)</Link>
      <Link to={{ pathname: '115ManaketePrincessStart', state: { buffer } }}>1-15: Manakete Princess (Start)</Link>
      <Link to={{ pathname: '116CamustheSableHidden', state: { buffer } }}>1-16: Camus the Sable (Hidden)</Link>
      <Link to={{ pathname: '116CamustheSableStart', state: { buffer } }}>1-16: Camus the Sable (Start)</Link>
      <Link to={{ pathname: '117AKnightFilledSkyHidden', state: { buffer } }}>1-17: A Knight-Filled Sky (Hidden)</Link>
      <Link to={{ pathname: '117AKnightFilledSkyStart', state: { buffer } }}>1-17: A Knight-Filled Sky (Start)</Link>
      <Link to={{ pathname: '118DarkPontifexHidden', state: { buffer } }}>1-18: Dark Pontifex (Hidden)</Link>
      <Link to={{ pathname: '118DarkPontifexStart', state: { buffer } }}>1-18: Dark Pontifex (Start)</Link>
      <Link to={{ pathname: '119TheDragonkinRealmHidden', state: { buffer } }}>1-19: The Dragonkin Realm (Hidden)</Link>
      <Link to={{ pathname: '119TheDragonkinRealmStart', state: { buffer } }}>1-19: The Dragonkin Realm (Start)</Link>
      <Link to={{ pathname: '12ThePiratesofGalderHidden', state: { buffer } }}>1-2: The Pirates of Galder (Hidden)</Link>
      <Link to={{ pathname: '12ThePiratesofGalderStart', state: { buffer } }}>1-2: The Pirates of Galder (Start)</Link>
      <Link to={{ pathname: '120Chosen', state: { buffer } }}>1-20: Chosen</Link>
      <Link to={{ pathname: '13ABrushinTheTeethHidden', state: { buffer } }}>1-3: A Brush in The Teeth (Hidden)</Link>
      <Link to={{ pathname: '13ABrushinTheTeethStart', state: { buffer } }}>1-3: A Brush in The Teeth (Start)</Link>
      <Link to={{ pathname: '14ChampionofAurelisHidden', state: { buffer } }}>1-4: Champion of Aurelis (Hidden)</Link>
      <Link to={{ pathname: '14ChampionofAurelisStart', state: { buffer } }}>1-4: Champion of Aurelis (Start)</Link>
      <Link to={{ pathname: '15FireEmblemHidden', state: { buffer } }}>1-5: Fire Emblem (Hidden)</Link>
      <Link to={{ pathname: '15FireEmblemStart', state: { buffer } }}>1-5: Fire Emblem (Start)</Link>
      <Link to={{ pathname: '16LefcandithGauntletHidden', state: { buffer } }}>1-6: Lefcandith Gauntlet (Hidden)</Link>
      <Link to={{ pathname: '16LefcandithGauntletStart', state: { buffer } }}>1-6: Lefcandith Gauntlet (Start)</Link>
      <Link to={{ pathname: '17PortWarrenHidden', state: { buffer } }}>1-7: Port Warren (Hidden)</Link>
      <Link to={{ pathname: '17PortWarrenStart', state: { buffer } }}>1-7: Port Warren (Start)</Link>
      <Link to={{ pathname: '18PrincessMinervaHidden', state: { buffer } }}>1-8: Princess Minerva (Hidden)</Link>
      <Link to={{ pathname: '18PrincessMinervaStart', state: { buffer } }}>1-8: Princess Minerva (Start)</Link>
      <Link to={{ pathname: '19KnordaSlaveMarketHidden', state: { buffer } }}>1-9: Knorda Slave Market (Hidden)</Link>
      <Link to={{ pathname: '19KnordaSlaveMarketStart', state: { buffer } }}>1-9: Knorda Slave Market (Start)</Link>
      <Link to={{ pathname: '21TheGrustianExpeditionHidden', state: { buffer } }}>2-1: The Grustian Expedition (Hidden)</Link>
      <Link to={{ pathname: '21TheGrustianExpeditionStart', state: { buffer } }}>2-1: The Grustian Expedition (Start)</Link>
      <Link to={{ pathname: '210TwoSorcerersHidden', state: { buffer } }}>2-10: Two Sorcerers (Hidden)</Link>
      <Link to={{ pathname: '210TwoSorcerersStart', state: { buffer } }}>2-10: Two Sorcerers (Start)</Link>
      <Link to={{ pathname: '211AnrisWayStart', state: { buffer } }}>2-11: Anri&apos;s Way (Start)</Link>
      <Link to={{ pathname: '212GraveyardofFireDragonsStart', state: { buffer } }}>2-12: Graveyard of Fire Dragons (Start)</Link>
      <Link to={{ pathname: '213FrozenLandStart', state: { buffer } }}>2-13: Frozen Land (Start)</Link>
      <Link to={{ pathname: '214AMysteryRevealedHidden', state: { buffer } }}>2-14: A Mystery Revealed (Hidden)</Link>
      <Link to={{ pathname: '214AMysteryRevealedStart', state: { buffer } }}>2-14: A Mystery Revealed (Start)</Link>
      <Link to={{ pathname: '215ReturnofthePrinceHidden', state: { buffer } }}>2-15: Return of the Prince (Hidden)</Link>
      <Link to={{ pathname: '215ReturnofthePrinceStart', state: { buffer } }}>2-15: Return of the Prince (Start)</Link>
      <Link to={{ pathname: '216RegainingtheCapitalHidden', state: { buffer } }}>2-16: Regaining the Capital (Hidden)</Link>
      <Link to={{ pathname: '216RegainingtheCapitalStart', state: { buffer } }}>2-16: Regaining the Capital (Start)</Link>
      <Link to={{ pathname: '217GrasSunSetsHidden', state: { buffer } }}>2-17: Gra&apos;s Sun Sets (Hidden)</Link>
      <Link to={{ pathname: '217GrasSunSetsStart', state: { buffer } }}>2-17: Gra&apos;s Sun Sets (Start)</Link>
      <Link to={{ pathname: '218BattleofthePassStart', state: { buffer } }}>2-18: Battle of the Pass (Start)</Link>
      <Link to={{ pathname: '219TheLastDecisiveBattleHidden', state: { buffer } }}>2-19: The Last Decisive Battle (Hidden)</Link>
      <Link to={{ pathname: '219TheLastDecisiveBattleStart', state: { buffer } }}>2-19: The Last Decisive Battle (Start)</Link>
      <Link to={{ pathname: '22RebellionatMacedonHidden', state: { buffer } }}>2-2: Rebellion at Macedon (Hidden)</Link>
      <Link to={{ pathname: '22RebellionatMacedonStart', state: { buffer } }}>2-2: Rebellion at Macedon (Start)</Link>
      <Link to={{ pathname: '220DarkEmperorHidden', state: { buffer } }}>2-20: Dark Emperor (Hidden)</Link>
      <Link to={{ pathname: '220DarkEmperorStart', state: { buffer } }}>2-20: Dark Emperor (Start)</Link>
      <Link to={{ pathname: '221TheWyvernsDaleStart', state: { buffer } }}>2-21: The Wyvern&apos;s Dale (Start)</Link>
      <Link to={{ pathname: '23AbductedPrincessHidden', state: { buffer } }}>2-3: Abducted Princess (Hidden)</Link>
      <Link to={{ pathname: '23AbductedPrincessStart', state: { buffer } }}>2-3: Abducted Princess (Start)</Link>
      <Link to={{ pathname: '24JoyandSorrowHidden', state: { buffer } }}>2-4: Joy and Sorrow (Hidden)</Link>
      <Link to={{ pathname: '24JoyandSorrowStart', state: { buffer } }}>2-4: Joy and Sorrow (Start)</Link>
      <Link to={{ pathname: '25LiberationofGrustHidden', state: { buffer } }}>2-5: Liberation of Grust (Hidden)</Link>
      <Link to={{ pathname: '25LiberationofGrustStart', state: { buffer } }}>2-5: Liberation of Grust (Start)</Link>
      <Link to={{ pathname: '26TheNestofEvilHidden', state: { buffer } }}>2-6: The Nest of Evil (Hidden)</Link>
      <Link to={{ pathname: '26TheNestofEvilStart', state: { buffer } }}>2-6: The Nest of Evil (Start)</Link>
      <Link to={{ pathname: '27TheScarletSwordsmanHidden', state: { buffer } }}>2-7: The Scarlet Swordsman (Hidden)</Link>
      <Link to={{ pathname: '27TheScarletSwordsmanStart', state: { buffer } }}>2-7: The Scarlet Swordsman (Start)</Link>
      <Link to={{ pathname: '28SoulfulBridgeHidden', state: { buffer } }}>2-8: Soulful Bridge (Hidden)</Link>
      <Link to={{ pathname: '28SoulfulBridgeStart', state: { buffer } }}>2-8: Soulful Bridge (Start)</Link>
      <Link to={{ pathname: '29SanctuaryofSorceryHidden', state: { buffer } }}>2-9: Sanctuary of Sorcery (Hidden)</Link>
      <Link to={{ pathname: '29SanctuaryofSorceryStart', state: { buffer } }}>2-9: Sanctuary of Sorcery (Start)</Link>
      <Link to={{ pathname: 'ArenaWeaponEditor', state: { buffer } }}>Arena Weapon Editor</Link>
      <Link to={{ pathname: 'BuriedTreasureEditor', state: { buffer } }}>Buried Treasure Editor</Link>
      <Link to={{ pathname: 'ChestItemEditor', state: { buffer } }}>Chest Item Editor</Link>
      <Link to={{ pathname: 'ChestItemEditor2', state: { buffer } }}>Chest Item Editor 2</Link>
      <Link to={{ pathname: 'ChestItemEditor3', state: { buffer } }}>Chest Item Editor 3</Link>
      <Link to={{ pathname: 'ChestItemEditor4', state: { buffer } }}>Chest Item Editor 4</Link>
      <Link to={{ pathname: 'DeathQuoteEditor', state: { buffer } }}>Death Quote Editor</Link>
      <Link to={{ pathname: 'DebugMapStart', state: { buffer } }}>Debug Map (Start)</Link>
      <Link to={{ pathname: 'DragonsTablePart1Start', state: { buffer } }}>Dragon&apos;s Table: Part 1 (Start)</Link>
      <Link to={{ pathname: 'DragonsTablePart2Start', state: { buffer } }}>Dragon&apos;s Table: Part 2 (Start)</Link>
      <Link to={{ pathname: 'DragonsTablePart3Hidden', state: { buffer } }}>Dragon&apos;s Table: Part 3 (Hidden)</Link>
      <Link to={{ pathname: 'DragonsTablePart3Start', state: { buffer } }}>Dragon&apos;s Table: Part 3 (Start)</Link>
      <Link to={{ pathname: 'EnemyRecrutableCharacterEditor', state: { buffer } }}>Enemy Recrutable Character Editor</Link>
      <Link to={{ pathname: 'EventTileEditor', state: { buffer } }}>Event Tile Editor</Link>
      <Link to={{ pathname: 'ArmyEditor', state: { buffer } }}>FE3 Army Editor</Link>
      <Link to={{ pathname: 'AstralShardEditor', state: { buffer } }}>FE3 Astral Shard Editor</Link>
      <Link to={{ pathname: 'AxeLockEditor', state: { buffer } }}>FE3 Axe Lock Editor</Link>
      <Link to={{ pathname: 'BowLockEditor', state: { buffer } }}>FE3 Bow Lock Editor</Link>
      <Link to={{ pathname: 'ChapterEnemySpriteEditor', state: { buffer } }}>FE3 Chapter Enemy Sprite Editor</Link>
      <Link to={{ pathname: 'CharacterGrowthBaseEditor', state: { buffer } }}>FE3 Character Growth & Base Editor</Link>
      <Link to={{ pathname: 'ClassBasesEditor', state: { buffer } }}>FE3 Class Bases Editor</Link>
      <Link to={{ pathname: 'ClassGrowthEditor', state: { buffer } }}>FE3 Class Growth Editor</Link>
      <Link to={{ pathname: 'DragonWhipCheckEditor', state: { buffer } }}>FE3 Dragon Whip Check Editor</Link>
      <Link to={{ pathname: 'DragonstoneLockEditor', state: { buffer } }}>FE3 Dragonstone Lock Editor</Link>
      <Link to={{ pathname: 'ItemEditor', state: { buffer } }}>FE3 Item Editor</Link>
      <Link to={{ pathname: 'KnightCrestCheckEditor', state: { buffer } }}>FE3 Knight Crest Check Editor</Link>
      <Link to={{ pathname: 'LadySwordLockEditor', state: { buffer } }}>FE3 Lady Sword Lock Editor</Link>
      <Link to={{ pathname: 'LanceLockEditor', state: { buffer } }}>FE3 Lance Lock Editor</Link>
      <Link to={{ pathname: 'OrbFragmentEditor', state: { buffer } }}>FE3 Orb Fragment Editor</Link>
      <Link to={{ pathname: 'PromotionEditor', state: { buffer } }}>FE3 Promotion Editor</Link>
      <Link to={{ pathname: 'PromotionItemsEditor', state: { buffer } }}>FE3 Promotion Items Editor</Link>
      <Link to={{ pathname: 'ResireLockEditor', state: { buffer } }}>FE3 Resire Lock Editor</Link>
      <Link to={{ pathname: 'ShopContentsEditor', state: { buffer } }}>FE3 Shop Contents Editor</Link>
      <Link to={{ pathname: 'ShopEditor', state: { buffer } }}>FE3 Shop Editor</Link>
      <Link to={{ pathname: 'StaveLockEditor', state: { buffer } }}>FE3 Stave Lock Editor</Link>
      <Link to={{ pathname: 'SwordLockEditor', state: { buffer } }}>FE3 Sword Lock Editor</Link>
      <Link to={{ pathname: 'TomeLockEditor', state: { buffer } }}>FE3 Tome Lock Editor</Link>
      <Link to={{ pathname: 'MapDataEditor', state: { buffer } }}>Map Data Editor</Link>
      <Link to={{ pathname: 'SupportEditor', state: { buffer } }}>Support Editor</Link>
      <Link to={{ pathname: 'UniversalReinforcements', state: { buffer } }}>Universal Reinforcements</Link>
    </Space>
  );
}
