export const FE3ChestItemEditor4Entries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
];

export const FE3Items = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Steel Sword', value: 0x01 },
  { label: 'Silver Sword', value: 0x02 },
  { label: 'Rapier', value: 0x03 },
  { label: 'Killer Sword', value: 0x04 },
  { label: 'Devil Sword', value: 0x05 },
  { label: 'Broken Sword', value: 0x06 },
  { label: 'Master Sword', value: 0x07 },
  { label: 'Lady Sword', value: 0x08 },
  { label: 'Thunder Sword', value: 0x09 },
  { label: 'Mercurius', value: 0x0A },
  { label: 'Falchion', value: 0x0B },
  { label: 'Armor Killer', value: 0x0C },
  { label: 'Dragon Killer', value: 0x0D },
  { label: 'Sword Killer', value: 0x0E },
  { label: 'Iron Lance', value: 0x0F },
  { label: 'Steel Lance', value: 0x10 },
  { label: 'Silver Lance', value: 0x11 },
  { label: 'Knight Killer', value: 0x12 },
  { label: 'Javelin', value: 0x13 },
  { label: 'Broken Lance', value: 0x14 },
  { label: 'Killer Lance', value: 0x15 },
  { label: 'Thin Lance', value: 0x16 },
  { label: 'Gradivus', value: 0x17 },
  { label: 'Iron Bow', value: 0x18 },
  { label: 'Broken Bow', value: 0x19 },
  { label: 'Steel Bow', value: 0x1A },
  { label: 'Silver Bow', value: 0x1B },
  { label: 'Killer Bow', value: 0x1C },
  { label: 'Parthia', value: 0x1D },
  { label: 'Iron Axe', value: 0x1E },
  { label: 'Steel Axe', value: 0x1F },
  { label: 'Hand Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Devil Axe', value: 0x22 },
  { label: 'Broken Axe', value: 0x23 },
  { label: 'Thunderbolt', value: 0x24 },
  { label: 'Quick Rain', value: 0x25 },
  { label: 'Stone Hedge', value: 0x26 },
  { label: 'Fire Gun', value: 0x27 },
  { label: 'Elephant', value: 0x28 },
  { label: 'Fire Breath', value: 0x29 },
  { label: 'Ice Breath', value: 0x2A },
  { label: 'Dark Breath', value: 0x2B },
  { label: 'Mist Breath', value: 0x2C },
  { label: 'Fire', value: 0x2D },
  { label: 'Thunder', value: 0x2E },
  { label: 'Blizzard', value: 0x2F },
  { label: 'Shaver', value: 0x30 },
  { label: 'Elfire', value: 0x31 },
  { label: 'Thoron', value: 0x32 },
  { label: 'Bolganone', value: 0x33 },
  { label: 'Excalibur', value: 0x34 },
  { label: 'Aura', value: 0x35 },
  { label: 'Starlight', value: 0x36 },
  { label: 'Imhullu', value: 0x37 },
  { label: 'Dulam', value: 0x38 },
  { label: 'Resire', value: 0x39 },
  { label: 'Meteor', value: 0x3A },
  { label: 'Worm', value: 0x3B },
  { label: 'Earth Orb', value: 0x3C },
  { label: 'Shield of Seals', value: 0x3D },
  { label: 'Dark Orb', value: 0x3E },
  { label: 'Fire Emblem', value: 0x3F },
  { label: 'Heal', value: 0x40 },
  { label: 'Recover', value: 0x41 },
  { label: 'Physic', value: 0x42 },
  { label: 'Mend', value: 0x43 },
  { label: 'Warp', value: 0x44 },
  { label: 'Magic Shield', value: 0x45 },
  { label: 'Hammerne', value: 0x46 },
  { label: 'Fortify', value: 0x47 },
  { label: 'Silence', value: 0x48 },
  { label: 'Rescue', value: 0x49 },
  { label: 'Aum', value: 0x4A },
  { label: 'Unlock', value: 0x4B },
  { label: 'Thief Staff', value: 0x4C },
  { label: 'Watch Staff', value: 0x4D },
  { label: 'Again Staff', value: 0x4E },
  { label: 'Fire Dragon Stone', value: 0x4F },
  { label: 'Aum', value: 0x50 },
  { label: 'Ice Dragon Stone', value: 0x51 },
  { label: 'Flying Dragon Stone', value: 0x52 },
  { label: 'Earth Dragon Stone', value: 0x53 },
  { label: 'Dark Dragon Stone', value: 0x54 },
  { label: 'Divine Dragon Stone', value: 0x55 },
  { label: 'Demon Dragon Stone', value: 0x56 },
  { label: 'Vulnerary', value: 0x57 },
  { label: 'Door Key', value: 0x58 },
  { label: 'Silver Key', value: 0x59 },
  { label: 'Bridge Key', value: 0x5A },
  { label: 'Treasure Key', value: 0x5B },
  { label: 'Energy Ring', value: 0x5C },
  { label: 'Shield Ring', value: 0x5D },
  { label: 'Secret Book', value: 0x5E },
  { label: 'Speed Ring', value: 0x5F },
  { label: 'Amulet', value: 0x60 },
  { label: 'Angelic Robe', value: 0x61 },
  { label: 'Goddess Icon', value: 0x62 },
  { label: 'Manual', value: 0x63 },
  { label: 'Boots', value: 0x64 },
  { label: 'Pure Water', value: 0x65 },
  { label: 'Knight Crest', value: 0x66 },
  { label: 'Hero Crest', value: 0x67 },
  { label: 'Guiding Ring', value: 0x68 },
  { label: 'Elysian Whip', value: 0x69 },
  { label: 'Orion\'s Bolt', value: 0x6A },
  { label: 'Earth Orb', value: 0x6B },
  { label: 'Life Orb', value: 0x6C },
  { label: 'Iote Shield', value: 0x6D },
  { label: 'Aquarius Orb', value: 0x6E },
  { label: 'Pisces Orb', value: 0x6F },
  { label: 'Aries Orb', value: 0x70 },
  { label: 'Taurus Orb', value: 0x71 },
  { label: 'Gemini Orb', value: 0x72 },
  { label: 'Cancer Orb', value: 0x73 },
  { label: 'Leo Orb', value: 0x74 },
  { label: 'Virgo Orb', value: 0x75 },
  { label: 'Libra Orb', value: 0x76 },
  { label: 'Scorpio Orb', value: 0x77 },
  { label: 'Sagittarius Orb', value: 0x78 },
  { label: 'Capricorn Orb', value: 0x79 },
  { label: 'Aum Fragment', value: 0x7A },
  { label: 'Silver Card', value: 0x7B },
  { label: 'Member Card', value: 0x7C },
  { label: 'Light Orb', value: 0x7D },
  { label: 'Star Orb', value: 0x7E },
  { label: 'Nothing', value: 0xFF },
];
