export const FE1BossMusicEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
];

export const Chardata = [
  { label: 'Marth', value: 0x01 },
  { label: 'Sheeda', value: 0x02 },
  { label: 'Jeigan', value: 0x03 },
  { label: 'Kain', value: 0x04 },
  { label: 'Abel', value: 0x05 },
  { label: 'Doga', value: 0x06 },
  { label: 'Gordon', value: 0x07 },
  { label: 'Ricardo', value: 0x08 },
  { label: 'Riff', value: 0x09 },
  { label: 'Saji', value: 0x0A },
  { label: 'Maji', value: 0x0B },
  { label: 'Barts', value: 0x0C },
  { label: 'Kashim', value: 0x0D },
  { label: 'Oguma', value: 0x0E },
  { label: 'Daros', value: 0x0F },
  { label: 'Julian', value: 0x10 },
  { label: 'Rena', value: 0x11 },
  { label: 'Marich', value: 0x12 },
  { label: 'Navarre', value: 0x13 },
  { label: 'Hardin', value: 0x14 },
  { label: 'Wolf', value: 0x15 },
  { label: 'Zagaro', value: 0x16 },
  { label: 'Roshe', value: 0x17 },
  { label: 'Biraku', value: 0x18 },
  { label: 'Banutu', value: 0x19 },
  { label: 'Caesar', value: 0x1A },
  { label: 'Raddy', value: 0x1B },
  { label: 'Midia', value: 0x1C },
  { label: 'Katua', value: 0x1D },
  { label: 'Maria', value: 0x1E },
  { label: 'Minerva', value: 0x1F },
  { label: 'Linda', value: 0x20 },
  { label: 'George', value: 0x21 },
  { label: 'Tomth', value: 0x22 },
  { label: 'Mishelan', value: 0x23 },
  { label: 'Thomas', value: 0x24 },
  { label: 'Boa', value: 0x25 },
  { label: 'Alan', value: 0x26 },
  { label: 'Samson', value: 0x27 },
  { label: 'Beck', value: 0x28 },
  { label: 'Chainy', value: 0x29 },
  { label: 'Wendel', value: 0x2A },
  { label: 'Est', value: 0x2B },
  { label: 'Astria', value: 0x2C },
  { label: 'Machis', value: 0x2D },
  { label: 'Roger', value: 0x2E },
  { label: 'Jake', value: 0x2F },
  { label: 'Paola', value: 0x30 },
  { label: 'Chiki', value: 0x31 },
  { label: 'Lawrence', value: 0x32 },
  { label: 'Ellis', value: 0x33 },
  { label: 'Saber', value: 0x34 },
  { label: 'Gato', value: 0x35 },
  { label: 'Gazack', value: 0x81 },
  { label: 'Wylar', value: 0x82 },
  { label: 'Grunia Soldier', value: 0x83 },
  { label: 'Gomes', value: 0x84 },
  { label: 'Garda Soldier', value: 0x85 },
  { label: 'Samsian', value: 0x86 },
  { label: 'Navarre', value: 0x87 },
  { label: 'Merak', value: 0x88 },
  { label: 'Hermine', value: 0x89 },
  { label: 'Mariones', value: 0x8A },
  { label: 'Benson', value: 0x8B },
  { label: 'Canaris', value: 0x8C },
  { label: 'Manuu', value: 0x8D },
  { label: 'Zhukov', value: 0x8E },
  { label: 'Shozen', value: 0x8F },
  { label: 'Heimler', value: 0x90 },
  { label: 'Gigash', value: 0x91 },
  { label: 'Jiol', value: 0x92 },
  { label: 'Bozen', value: 0x93 },
  { label: 'Holstat', value: 0x94 },
  { label: 'Stallone', value: 0x95 },
  { label: 'Hyman', value: 0x96 },
  { label: 'Zemcel', value: 0x97 },
  { label: 'Ordyne', value: 0x98 },
  { label: 'Camus', value: 0x99 },
  { label: 'Misheil', value: 0x9A },
  { label: 'Moses', value: 0x9B },
  { label: 'Garnef', value: 0x9C },
  { label: 'Mediuth', value: 0x9D },
  { label: 'Maria', value: 0x9E },
  { label: 'Durhua Soldier', value: 0x9F },
  { label: 'Gra Soldier', value: 0xA0 },
  { label: 'Peraty Soldier', value: 0xA1 },
  { label: 'Cashmere Soldier', value: 0xA2 },
  { label: 'Black Knight', value: 0xA3 },
  { label: 'Khadein Mage', value: 0xA4 },
  { label: 'Minerva', value: 0xA5 },
  { label: 'Basilisk', value: 0xA6 },
  { label: 'Salamander', value: 0xA7 },
  { label: 'Narga', value: 0xA8 },
  { label: 'Gaia', value: 0xA9 },
  { label: 'Iron Knight', value: 0xAA },
  { label: 'Dragon Knight', value: 0xAB },
  { label: 'Enemy', value: 0xAC },
  { label: 'Daros', value: 0xAD },
  { label: 'Ricardo', value: 0xAE },
  { label: 'Macedonia Soldier', value: 0xAF },
  { label: 'Katua', value: 0xB0 },
  { label: 'Paola', value: 0xB1 },
  { label: 'Est', value: 0xB2 },
  { label: 'White Knight', value: 0xB3 },
  { label: 'Gra Soldier', value: 0xB4 },
  { label: 'Rogue', value: 0xB5 },
  { label: 'Wendel', value: 0xB6 },
  { label: 'Raman Soldier', value: 0xB7 },
  { label: 'Thebes Mage', value: 0xB8 },
  { label: 'Priest Army', value: 0xB9 },
  { label: 'Chiki', value: 0xBA },
  { label: 'King Grunia', value: 0xBB },
  { label: 'Reinforcements', value: 0xBC },
  { label: 'Kashim', value: 0xBD },
  { label: 'Saber', value: 0xBE },
  { label: 'Jake', value: 0xBF },
  { label: 'Lawrence', value: 0xC0 },
  { label: 'Chainy', value: 0xC1 },
  { label: 'Garnef', value: 0xC2 },
  { label: 'Roger', value: 0xC3 },
  { label: 'Machis', value: 0xC4 },
  { label: 'Astria', value: 0xC5 },
];
