export const Coordinates2 = [
  { label: 'Y 13', value: 0 },
  { label: 'Y 14', value: 1 },
  { label: 'Y 15', value: 2 },
  { label: 'Y 16', value: 3 },
  { label: 'Y 17', value: 4 },
  { label: 'Y 18', value: 5 },
  { label: 'Y 19', value: 6 },
];

export const Block = [
  { label: 'Empty', value: 0x00 },
  { label: 'Name box upper edge 1', value: 0x01 },
  { label: 'Name box upper edge 2', value: 0x02 },
  { label: 'Name box corner(unused)', value: 0x03 },
  { label: 'Name box vertical edge', value: 0x04 },
  { label: 'HP box middle', value: 0x05 },
  { label: 'name box dragon 1(head)', value: 0x06 },
  { label: 'name box dragon 2', value: 0x07 },
  { label: 'name box dragon 3', value: 0x08 },
  { label: 'name box dragon 4(tail)', value: 0x09 },
  { label: 'name box dragon 5(claw)', value: 0x0A },
  { label: 'name box corner', value: 0x0B },
  { label: 'name box bottom edge 1', value: 0x0C },
  { label: 'name box bottom edge 2', value: 0x0D },
  { label: 'name box bottom edge 3', value: 0x0E },
  { label: 'Name box corner(unused)', value: 0x0F },
  { label: 'Name box edge(unused)', value: 0x10 },
  { label: 'Name box edge(unused)', value: 0x11 },
  { label: 'hit box upper edge', value: 0x12 },
  { label: 'hit box corner', value: 0x13 },
  { label: 'hit box middle', value: 0x14 },
  { label: 'hit and weapon box edge corner', value: 0x15 },
  { label: 'weapon box upper edge 1(darker)', value: 0x16 },
  { label: 'weapon box upper edge 2', value: 0x17 },
  { label: 'weapon box upper edge 3(lighter)', value: 0x18 },
  { label: 'weapon box upper edge decoration(edge)', value: 0x19 },
  { label: 'weapon box upper edge decoration(middle)', value: 0x1A },
  { label: 'weapon and hit box transition 1(upper)', value: 0x1B },
  { label: 'weapon box below upper edge', value: 0x1C },
  { label: 'weapon box corner(unused)', value: 0x1D },
  { label: 'weapon and hit box transition 2(lower)', value: 0x1E },
  { label: 'weapon box middle', value: 0x1F },
  { label: 'weapon box vertical edge(unused)', value: 0x20 },
  { label: 'weapon box upper edge(unused)', value: 0x21 },
  { label: 'hit box vertical edge', value: 0x22 },
  { label: 'hit box vertical edge(unused)', value: 0x23 },
  { label: 'hit box vertical edge(unused)', value: 0x24 },
  { label: 'hit and HP box transition', value: 0x25 },
  { label: 'hit and HP box transition', value: 0x26 },
  { label: 'hit and HP box transition', value: 0x27 },
  { label: 'hit and HP box transition', value: 0x28 },
  { label: 'hit and HP box transition', value: 0x29 },
  { label: 'hit and HP box transition edge', value: 0x2A },
  { label: 'weapon and hp box transition', value: 0x2B },
  { label: 'weapon and hp box transition', value: 0x2C },
  { label: 'weapon and hp box transition', value: 0x2D },
  { label: 'HP box upper middle edge', value: 0x2E },
  { label: 'HP box "desing"', value: 0x2F },
  { label: 'HP box "desing"', value: 0x30 },
  { label: 'HP box "desing"', value: 0x31 },
  { label: 'HP box "desing"', value: 0x32 },
  { label: 'HP box "desing"', value: 0x33 },
  { label: 'HP box "desing"', value: 0x34 },
  { label: 'HP vertical edge', value: 0x35 },
  { label: 'HP box lower edge', value: 0x36 },
  { label: 'HP box lower edge', value: 0x37 },
  { label: 'HP box lower edge', value: 0x38 },
  { label: 'HP box lower edge', value: 0x39 },
  { label: 'HP box lower edge', value: 0x3A },
  { label: 'HP box lower edge', value: 0x3B },
  { label: 'HP box lower edge', value: 0x3C },
  { label: 'HP box lower edge', value: 0x3D },
  { label: 'HP box lower edge', value: 0x3E },
  { label: 'HP box lower edge', value: 0x3F },
  { label: 'HP box lower edge', value: 0x40 },
  { label: 'HP box lower edge', value: 0x41 },
  { label: 'HP box lower edge', value: 0x42 },
  { label: 'HP box lower edge', value: 0x43 },
  { label: 'enemy name 1,1', value: 0x44 },
  { label: 'enemy name 1,2', value: 0x45 },
  { label: 'enemy name 2,1', value: 0x46 },
  { label: 'enemy name 2,2', value: 0x47 },
  { label: 'enemy name 3,1', value: 0x48 },
  { label: 'enemy name 3,2', value: 0x49 },
  { label: 'enemy name 4,1', value: 0x4A },
  { label: 'enemy name 4,2', value: 0x4B },
  { label: 'enemy name 5,1', value: 0x4C },
  { label: 'enemy name 5,2', value: 0x4D },
  { label: 'enemy name 6,1', value: 0x4E },
  { label: 'enemy name 6,2', value: 0x4F },
  { label: 'enemy name 7,1', value: 0x50 },
  { label: 'enemy name 7,2', value: 0x51 },
  { label: 'enemy weapon name 1,1', value: 0x52 },
  { label: 'enemy weapon name 1,2', value: 0x53 },
  { label: 'enemy weapon name 2,1', value: 0x54 },
  { label: 'enemy weapon name 2,2', value: 0x55 },
  { label: 'enemy weapon name 3,1', value: 0x56 },
  { label: 'enemy weapon name 3,2', value: 0x57 },
  { label: 'enemy weapon name 4,1', value: 0x58 },
  { label: 'enemy weapon name 4,2', value: 0x59 },
  { label: 'enemy weapon name 5,1', value: 0x5A },
  { label: 'enemy weapon name 5,2', value: 0x5B },
  { label: 'enemy weapon name 6,1', value: 0x5C },
  { label: 'enemy weapon name 6,2', value: 0x5D },
  { label: 'enemy weapon name 7,1', value: 0x5E },
  { label: 'enemy weapon name 7,2', value: 0x5F },
  { label: 'enemy weapon name 8,1', value: 0x60 },
  { label: 'enemy weapon name 8,2', value: 0x61 },
  { label: 'player name 1,1', value: 0x62 },
  { label: 'player name 1,2', value: 0x63 },
  { label: 'player name 2,1', value: 0x64 },
  { label: 'player name 2,2', value: 0x65 },
  { label: 'player name 3,1', value: 0x66 },
  { label: 'player name 3,2', value: 0x67 },
  { label: 'player name 4,1', value: 0x68 },
  { label: 'player name 4,2', value: 0x69 },
  { label: 'player name 5,1', value: 0x6A },
  { label: 'player name 5,2', value: 0x6B },
  { label: 'player name 6,1', value: 0x6C },
  { label: 'player name 6,2', value: 0x6D },
  { label: 'player name 7,1', value: 0x6E },
  { label: 'player name 7,2', value: 0x6F },
  { label: 'player weapon name 1,1', value: 0x70 },
  { label: 'player weapon name 1,2', value: 0x71 },
  { label: 'player weapon name 2,1', value: 0x72 },
  { label: 'player weapon name 2,2', value: 0x73 },
  { label: 'player weapon name 3,1', value: 0x74 },
  { label: 'player weapon name 3,2', value: 0x75 },
  { label: 'player weapon name 4,1', value: 0x76 },
  { label: 'player weapon name 4,2', value: 0x77 },
  { label: 'player weapon name 5,1', value: 0x78 },
  { label: 'player weapon name 5,2', value: 0x79 },
  { label: 'player weapon name 6,1', value: 0X7A },
  { label: 'player weapon name 6,2', value: 0X7B },
  { label: 'player weapon name 7,1', value: 0X7C },
  { label: 'player weapon name 7,2', value: 0X7D },
  { label: 'player weapon name 8,1', value: 0X7E },
  { label: 'player weapon name 8,2', value: 0X7F },
];

export const PaletteFlip = [
  { label: 'player, none', value: 0x00 },
  { label: 'player, vertical', value: 0x04 },
  { label: 'player, horizontical', value: 0x08 },
  { label: 'player, both', value: 0x0C },
  { label: 'enemy, none', value: 0x10 },
  { label: 'enemy, vertical', value: 0x14 },
  { label: 'enemy, horizontical', value: 0x18 },
  { label: 'enemy, both', value: 0x1C },
];
