export const FE3ShopList = [
  { label: '0x00 B1 Chapter 1 Armory', value: 0 },
  { label: '0x01 B1 Chapter 2/3 Armory', value: 1 },
  { label: '0x02 B1 Chapter 4 Armory', value: 2 },
  { label: '0x03 B1 Chapter 6 Armory', value: 3 },
  { label: '0x04 B1 Chapter 7 Armory', value: 4 },
  { label: '0x05 B1 Chapter 7/8/11 Vendor', value: 5 },
  { label: '0x06 B1 Chapter 8 Armory', value: 6 },
  { label: '0x07 B1 Chapter 9 Armory', value: 7 },
  { label: '0x08 B1 Chapter 9 Vendor', value: 8 },
  { label: '0x09 B1 Chapter 11 Vendor', value: 9 },
  { label: '0x0A B1 Chapter 12 Armory', value: 10 },
  { label: '0x0B B1 Chapter 12/13 Magic/Staff Vendor, B2 Chapter 9/15/21 Magic/Staff Vendor', value: 11 },
  { label: '0x0C B1 Chapter 12/13, B2 Chapter 9/15/21 Item Vendor', value: 12 },
  { label: '0x0D B1 Chapter 13/B2 Chapter 15 South Armory', value: 13 },
  { label: '0x0E B1 Chapter 13 North Armory', value: 14 },
  { label: '0x0F B1 Chapter 14 Secret Shop', value: 15 },
  { label: '0x10 B1 Chapter 16 Sword/Lance/Bow Armory', value: 16 },
  { label: '0x11 B1 Chapter 16 BEST WEAPON TYPE Armory', value: 17 },
  { label: '0x12 B1 Chapter 16 Vendor', value: 18 },
  { label: '0x13 B1 Chapter 17 Specialty Armory', value: 19 },
  { label: '0x14 B1 Chapter 17 Budget Armory', value: 20 },
  { label: '0x15 B1 Chapter 17, B2 Chapter 5/18 Secret Shop', value: 21 },
  { label: '0x16 B1 Chapter 19 Armory', value: 22 },
  { label: '0x17 B1 Chapter 19 Vendor', value: 23 },
  { label: '0x18 B1 Chapter 19, B2 Chapter 22-1 Secret Shop', value: 24 },
  { label: '0x19 B2 Chapter 1 Armory', value: 25 },
  { label: '0x1A B2 Chapter 3 Armory', value: 26 },
  { label: '0x1B B2 Chapter 5 Armory', value: 27 },
  { label: '0x1C B2 Chapter 5 Vendor', value: 28 },
  { label: '0x1D B2 Chapter 7/15(North) Armory', value: 29 },
  { label: '0x1E B2 Chapter 8 Armory', value: 30 },
  { label: '0x1F B2 Chapter 9 Armory', value: 31 },
  { label: '0x20 B2 Chapter 11 Secret Shop', value: 32 },
  { label: '0x21 B2 Chapter 13 Secret Shop', value: 33 },
  { label: '0x22 B2 Chapter 14 Secret Shop', value: 34 },
  { label: '0x23 B2 Chapter 17/21(Right) Armory', value: 35 },
  { label: '0x24 B2 Chapter 17/19 Vendor', value: 36 },
  { label: '0x25 B2 Chapter 19 Armory', value: 37 },
  { label: '0x26 B2 Chapter 21 Left Armory', value: 38 },
];

export const FE3Items = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Steel Sword', value: 0x01 },
  { label: 'Silver Sword', value: 0x02 },
  { label: 'Rapier', value: 0x03 },
  { label: 'Killer Sword', value: 0x04 },
  { label: 'Devil Sword', value: 0x05 },
  { label: 'Broken Sword', value: 0x06 },
  { label: 'Master Sword', value: 0x07 },
  { label: 'Lady Sword', value: 0x08 },
  { label: 'Thunder Sword', value: 0x09 },
  { label: 'Miracle Sword', value: 0x0A },
  { label: 'Falchion', value: 0x0B },
  { label: 'Armor Killer', value: 0x0C },
  { label: 'Dragon Killer', value: 0x0D },
  { label: 'Sword Killer', value: 0x0E },
  { label: 'Iron Lance', value: 0x0F },
  { label: 'Steel Lance', value: 0x10 },
  { label: 'Silver Lance', value: 0x11 },
  { label: 'Knight Killer', value: 0x12 },
  { label: 'Hand Spear', value: 0x13 },
  { label: 'Broken Lance', value: 0x14 },
  { label: 'Killer Lance', value: 0x15 },
  { label: 'Thin Lance', value: 0x16 },
  { label: 'Gradivus', value: 0x17 },
  { label: 'Iron Bow', value: 0x18 },
  { label: 'Broken Bow', value: 0x19 },
  { label: 'Steel Bow', value: 0x1A },
  { label: 'Silver Bow', value: 0x1B },
  { label: 'Killer Bow', value: 0x1C },
  { label: 'Parthia', value: 0x1D },
  { label: 'Iron Axe', value: 0x1E },
  { label: 'Steel Axe', value: 0x1F },
  { label: 'Hand Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Devil Axe', value: 0x22 },
  { label: 'Broken Axe', value: 0x23 },
  { label: 'Thunderbolt', value: 0x24 },
  { label: 'Quick Rain', value: 0x25 },
  { label: 'Stone Hedge', value: 0x26 },
  { label: 'Fire Gun', value: 0x27 },
  { label: 'Elephant', value: 0x28 },
  { label: 'Fire Breath', value: 0x29 },
  { label: 'Ice Breath', value: 0x2A },
  { label: 'Dark Breath', value: 0x2B },
  { label: 'Mist Breath', value: 0x2C },
  { label: 'Fire', value: 0x2D },
  { label: 'Thunder', value: 0x2E },
  { label: 'Blizzard', value: 0x2F },
  { label: 'Shaver', value: 0x30 },
  { label: 'Elfire', value: 0x31 },
  { label: 'Thoron', value: 0x32 },
  { label: 'Bolganone', value: 0x33 },
  { label: 'Excalibur', value: 0x34 },
  { label: 'Aura', value: 0x35 },
  { label: 'Starlight', value: 0x36 },
  { label: 'Imhullu', value: 0x37 },
  { label: 'Dulam', value: 0x38 },
  { label: 'Resire', value: 0x39 },
  { label: 'Meteor', value: 0x3A },
  { label: 'Worm', value: 0x3B },
  { label: 'Earth Orb', value: 0x3C },
  { label: 'Shield of Seals', value: 0x3D },
  { label: 'Dark Orb', value: 0x3E },
  { label: 'Fire Emblem', value: 0x3F },
  { label: 'Heal', value: 0x40 },
  { label: 'Recover', value: 0x41 },
  { label: 'Physic', value: 0x42 },
  { label: 'Mend', value: 0x43 },
  { label: 'Warp', value: 0x44 },
  { label: 'Magic Shield', value: 0x45 },
  { label: 'Hammerne', value: 0x46 },
  { label: 'Fortify', value: 0x47 },
  { label: 'Silence', value: 0x48 },
  { label: 'Rescue', value: 0x49 },
  { label: 'Aum', value: 0x4A },
  { label: 'Unlock', value: 0x4B },
  { label: 'Thief Staff', value: 0x4C },
  { label: 'Watch Staff', value: 0x4D },
  { label: 'Again Staff', value: 0x4E },
  { label: 'Fire Dragon Stone', value: 0x4F },
  { label: 'Aum', value: 0x50 },
  { label: 'Ice Dragon Stone', value: 0x51 },
  { label: 'Flying Dragon Stone', value: 0x52 },
  { label: 'Earth Dragon Stone', value: 0x53 },
  { label: 'Dark Dragon Stone', value: 0x54 },
  { label: 'Divine Dragon Stone', value: 0x55 },
  { label: 'Demon Dragon Stone', value: 0x56 },
  { label: 'Vulnerary', value: 0x57 },
  { label: 'Door Key', value: 0x58 },
  { label: 'Silver Key', value: 0x59 },
  { label: 'Bridge Key', value: 0x5A },
  { label: 'Treasure Key', value: 0x5B },
  { label: 'Energy Ring', value: 0x5C },
  { label: 'Shield Ring', value: 0x5D },
  { label: 'Secret Book', value: 0x5E },
  { label: 'Speed Ring', value: 0x5F },
  { label: 'Amulet', value: 0x60 },
  { label: 'Angelic Robe', value: 0x61 },
  { label: 'Goddess Icon', value: 0x62 },
  { label: 'Manual', value: 0x63 },
  { label: 'Boots', value: 0x64 },
  { label: 'Pure Water', value: 0x65 },
  { label: 'Knight Crest', value: 0x66 },
  { label: 'Hero Crest', value: 0x67 },
  { label: 'Guiding Ring', value: 0x68 },
  { label: 'Elysian Whip', value: 0x69 },
  { label: 'Orion\'s Bolt', value: 0x6A },
  { label: 'Earth Orb', value: 0x6B },
  { label: 'Life Orb', value: 0x6C },
  { label: 'Iote Shield', value: 0x6D },
  { label: 'Aquarius Orb', value: 0x6E },
  { label: 'Pisces Orb', value: 0x6F },
  { label: 'Aries Orb', value: 0x70 },
  { label: 'Taurus Orb', value: 0x71 },
  { label: 'Gemini Orb', value: 0x72 },
  { label: 'Cancer Orb', value: 0x73 },
  { label: 'Leo Orb', value: 0x74 },
  { label: 'Virgo Orb', value: 0x75 },
  { label: 'Libra Orb', value: 0x76 },
  { label: 'Scorpio Orb', value: 0x77 },
  { label: 'Sagittarius Orb', value: 0x78 },
  { label: 'Capricorn Orb', value: 0x79 },
  { label: 'Aum Fragment', value: 0x7A },
  { label: 'Silver Card', value: 0x7B },
  { label: 'Member Card', value: 0x7C },
  { label: 'Light Orb', value: 0x7D },
  { label: 'Star Orb', value: 0x7E },
  { label: 'Shop Nothing', value: 0xFE },
  { label: 'Nothing', value: 0xFF },
];
