export const Classes = [
  { label: 'Revenant', value: 0 },
  { label: 'Entombed', value: 1 },
  { label: 'Bonewalker', value: 2 },
  { label: 'Bonewalker (Bow)', value: 3 },
  { label: 'Wight', value: 4 },
  { label: 'Wight (Bow)', value: 5 },
  { label: 'Bael', value: 6 },
  { label: 'Elder Bael', value: 7 },
  { label: 'Cyclops', value: 8 },
  { label: 'Mauthe Doog', value: 9 },
  { label: 'Gwyllgi', value: 10 },
  { label: 'Tarvos', value: 11 },
  { label: 'Maelduin', value: 12 },
  { label: 'Mogall', value: 13 },
  { label: 'Arch Mogall', value: 14 },
  { label: 'Gorgon', value: 15 },
  { label: 'Gargoyle', value: 16 },
  { label: 'Deathgoyle', value: 17 },
  { label: 'Dracozombie', value: 18 },
  { label: 'Cyclops (Special)', value: 19 },
  { label: 'Elder Bael (Special)', value: 20 },
];

export const ClassList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Ephraim Lord', value: 0x01 },
  { label: 'Eirika Lord', value: 0x02 },
  { label: 'Ephraim Great Lord', value: 0x03 },
  { label: 'Eirika Great Lord', value: 0x04 },
  { label: 'Cavalier', value: 0x05 },
  { label: 'Cavalier (F)', value: 0x06 },
  { label: 'Paladin', value: 0x07 },
  { label: 'Paladin (F)', value: 0x08 },
  { label: 'Armour Knight', value: 0x09 },
  { label: 'Armour Knight (F)', value: 0x0A },
  { label: 'General', value: 0x0B },
  { label: 'General (F)', value: 0x0C },
  { label: 'Thief', value: 0x0D },
  { label: 'Manakete', value: 0x0E },
  { label: 'Mercenary', value: 0x0F },
  { label: 'Mercenary (F)', value: 0x10 },
  { label: 'Hero', value: 0x11 },
  { label: 'Hero (F)', value: 0x12 },
  { label: 'Myrmidon', value: 0x13 },
  { label: 'Myrmidon (F)', value: 0x14 },
  { label: 'Swordmaster', value: 0x15 },
  { label: 'Swordmaster (F)', value: 0x16 },
  { label: 'Assassin', value: 0x17 },
  { label: 'Assassin (F)', value: 0x18 },
  { label: 'Archer', value: 0x19 },
  { label: 'Archer (F)', value: 0x1A },
  { label: 'Sniper', value: 0x1B },
  { label: 'Sniper (F)', value: 0x1C },
  { label: 'Ranger', value: 0x1D },
  { label: 'Ranger (F)', value: 0x1E },
  { label: 'Wyvern Rider', value: 0x1F },
  { label: 'Wyvern Rider (F)', value: 0x20 },
  { label: 'Wyvern Lord', value: 0x21 },
  { label: 'Wyvern Lord (F)', value: 0x22 },
  { label: 'Wyvern Knight', value: 0x23 },
  { label: 'Wyvern Knight (F)', value: 0x24 },
  { label: 'Mage', value: 0x25 },
  { label: 'Mage (F)', value: 0x26 },
  { label: 'Sage', value: 0x27 },
  { label: 'Sage (F)', value: 0x28 },
  { label: 'Mage Knight', value: 0x29 },
  { label: 'Mage Knight (F)', value: 0x2A },
  { label: 'Bishop', value: 0x2B },
  { label: 'Bishop (F)', value: 0x2C },
  { label: 'Shaman', value: 0x2D },
  { label: 'Shaman (F)', value: 0x2E },
  { label: 'Druid', value: 0x2F },
  { label: 'Druid (F)', value: 0x30 },
  { label: 'Summoner', value: 0x31 },
  { label: 'Summoner (F)', value: 0x32 },
  { label: 'Rogue', value: 0x33 },
  { label: 'Gorgon Egg', value: 0x34 },
  { label: 'Great Knight', value: 0x35 },
  { label: 'Great Knight (F)', value: 0x36 },
  { label: 'Recruit (2)', value: 0x37 },
  { label: 'Journeyman (3)', value: 0x38 },
  { label: 'Pupil (3)', value: 0x39 },
  { label: 'Recruit (3)', value: 0x3A },
  { label: 'Manakete', value: 0x3B },
  { label: 'Manakete (F)', value: 0x3C },
  { label: 'Journeyman (1)', value: 0x3D },
  { label: 'Pupil (1)', value: 0x3E },
  { label: 'Fighter', value: 0x3F },
  { label: 'Warrior', value: 0x40 },
  { label: 'Brigand', value: 0x41 },
  { label: 'Pirate', value: 0x42 },
  { label: 'Berserker', value: 0x43 },
  { label: 'Monk', value: 0x44 },
  { label: 'Priest', value: 0x45 },
  { label: 'Bard', value: 0x46 },
  { label: 'Recruit (1)', value: 0x47 },
  { label: 'Pegasus Knight', value: 0x48 },
  { label: 'Falcon Knight', value: 0x49 },
  { label: 'Cleric', value: 0x4A },
  { label: 'Troubadour', value: 0x4B },
  { label: 'Valkyrie', value: 0x4C },
  { label: 'Dancer', value: 0x4D },
  { label: 'Soldier', value: 0x4E },
  { label: 'Necromancer', value: 0x4F },
  { label: 'Fleet', value: 0x50 },
  { label: 'Phantom', value: 0x51 },
  { label: 'Revenant', value: 0x52 },
  { label: 'Entombed', value: 0x53 },
  { label: 'Bonewalker', value: 0x54 },
  { label: 'Bonewalker (Bow)', value: 0x55 },
  { label: 'Wight', value: 0x56 },
  { label: 'Wight (Bow)', value: 0x57 },
  { label: 'Bael', value: 0x58 },
  { label: 'Elder Bael', value: 0x59 },
  { label: 'Cyclops', value: 0x5A },
  { label: 'Mauthe Doog', value: 0x5B },
  { label: 'Gwyllgi', value: 0x5C },
  { label: 'Tarvos', value: 0x5D },
  { label: 'Maelduin', value: 0x5E },
  { label: 'Mogall', value: 0x5F },
  { label: 'Arch Mogall', value: 0x60 },
  { label: 'Gorgon', value: 0x61 },
  { label: 'Gorgon Egg', value: 0x62 },
  { label: 'Gargoyle', value: 0x63 },
  { label: 'Deathgoyle', value: 0x64 },
  { label: 'Dracozombie', value: 0x65 },
  { label: 'Demon King', value: 0x66 },
  { label: 'Archer on Ballista', value: 0x67 },
  { label: 'Archer on Iron Ballista', value: 0x68 },
  { label: 'Archer on Killer Ballista', value: 0x69 },
  { label: 'Ballista', value: 0x6A },
  { label: 'Iron Ballista', value: 0x6B },
  { label: 'Killer Ballista', value: 0x6C },
  { label: 'Civilian', value: 0x6D },
  { label: 'Civilian (F)', value: 0x6E },
  { label: 'Civilian', value: 0x6F },
  { label: 'Civilian (F)', value: 0x70 },
  { label: 'Civilian', value: 0x71 },
  { label: 'Civilian (F)', value: 0x72 },
  { label: 'Peer', value: 0x73 },
  { label: 'Queen', value: 0x74 },
  { label: 'Prince', value: 0x75 },
  { label: 'Queen', value: 0x76 },
  { label: '(empty)', value: 0x77 },
  { label: 'Fallen Prince', value: 0x78 },
  { label: 'Tent', value: 0x79 },
  { label: 'Pontifex', value: 0x7A },
  { label: 'Fallen Peer', value: 0x7B },
  { label: 'Cyclops 2', value: 0x7C },
  { label: 'Elder Bael 2', value: 0x7D },
  { label: 'Journeyman (2)', value: 0x7E },
  { label: 'Pupil (2)', value: 0x7F },
];
