export const FE8CustomItemAnimationListEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
  { label: 'Entry 68', value: 68 },
  { label: 'Entry 69', value: 69 },
  { label: 'Entry 70', value: 70 },
  { label: 'Entry 71', value: 71 },
  { label: 'Entry 72', value: 72 },
  { label: 'Entry 73', value: 73 },
  { label: 'Entry 74', value: 74 },
  { label: 'Entry 75', value: 75 },
  { label: 'Entry 76', value: 76 },
  { label: 'Entry 77', value: 77 },
  { label: 'Entry 78', value: 78 },
  { label: 'Entry 79', value: 79 },
  { label: 'Entry 80', value: 80 },
  { label: 'Entry 81', value: 81 },
  { label: 'Entry 82', value: 82 },
  { label: 'Entry 83', value: 83 },
  { label: 'Entry 84', value: 84 },
  { label: 'Entry 85', value: 85 },
  { label: 'Entry 86', value: 86 },
  { label: 'Entry 87', value: 87 },
  { label: 'Entry 88', value: 88 },
  { label: 'Entry 89', value: 89 },
  { label: 'Entry 90', value: 90 },
  { label: 'Entry 91', value: 91 },
  { label: 'Entry 92', value: 92 },
  { label: 'Entry 93', value: 93 },
  { label: 'Entry 94', value: 94 },
  { label: 'Entry 95', value: 95 },
  { label: 'Entry 96', value: 96 },
  { label: 'Entry 97', value: 97 },
  { label: 'Entry 98', value: 98 },
  { label: 'Entry 99', value: 99 },
  { label: 'Entry 100', value: 100 },
  { label: 'Entry 101', value: 101 },
  { label: 'Entry 102', value: 102 },
  { label: 'Entry 103', value: 103 },
  { label: 'Entry 104', value: 104 },
  { label: 'Entry 105', value: 105 },
  { label: 'Entry 106', value: 106 },
  { label: 'Entry 107', value: 107 },
  { label: 'Entry 108', value: 108 },
  { label: 'Entry 109', value: 109 },
  { label: 'Entry 110', value: 110 },
  { label: 'Entry 111', value: 111 },
  { label: 'Entry 112', value: 112 },
  { label: 'Entry 113', value: 113 },
  { label: 'Entry 114', value: 114 },
  { label: 'Entry 115', value: 115 },
  { label: 'Entry 116', value: 116 },
  { label: 'Entry 117', value: 117 },
  { label: 'Entry 118', value: 118 },
  { label: 'Entry 119', value: 119 },
  { label: 'Entry 120', value: 120 },
  { label: 'Entry 121', value: 121 },
  { label: 'Entry 122', value: 122 },
  { label: 'Entry 123', value: 123 },
  { label: 'Entry 124', value: 124 },
  { label: 'Entry 125', value: 125 },
  { label: 'Entry 126', value: 126 },
  { label: 'Entry 127', value: 127 },
  { label: 'Entry 128', value: 128 },
  { label: 'Entry 129', value: 129 },
  { label: 'Entry 130', value: 130 },
  { label: 'Entry 131', value: 131 },
  { label: 'Entry 132', value: 132 },
  { label: 'Entry 133', value: 133 },
  { label: 'Entry 134', value: 134 },
  { label: 'Entry 135', value: 135 },
  { label: 'Entry 136', value: 136 },
  { label: 'Entry 137', value: 137 },
  { label: 'Entry 138', value: 138 },
  { label: 'Entry 139', value: 139 },
  { label: 'Entry 140', value: 140 },
  { label: 'Entry 141', value: 141 },
  { label: 'Entry 142', value: 142 },
  { label: 'Entry 143', value: 143 },
  { label: 'Entry 144', value: 144 },
  { label: 'Entry 145', value: 145 },
  { label: 'Entry 146', value: 146 },
  { label: 'Entry 147', value: 147 },
  { label: 'Entry 148', value: 148 },
  { label: 'Entry 149', value: 149 },
  { label: 'Entry 150', value: 150 },
  { label: 'Entry 151', value: 151 },
  { label: 'Entry 152', value: 152 },
  { label: 'Entry 153', value: 153 },
  { label: 'Entry 154', value: 154 },
  { label: 'Entry 155', value: 155 },
  { label: 'Entry 156', value: 156 },
  { label: 'Entry 157', value: 157 },
  { label: 'Entry 158', value: 158 },
  { label: 'Entry 159', value: 159 },
  { label: 'Entry 160', value: 160 },
  { label: 'Entry 161', value: 161 },
  { label: 'Entry 162', value: 162 },
  { label: 'Entry 163', value: 163 },
  { label: 'Entry 164', value: 164 },
  { label: 'Entry 165', value: 165 },
  { label: 'Entry 166', value: 166 },
  { label: 'Entry 167', value: 167 },
  { label: 'Entry 168', value: 168 },
  { label: 'Entry 169', value: 169 },
  { label: 'Entry 170', value: 170 },
  { label: 'Entry 171', value: 171 },
  { label: 'Entry 172', value: 172 },
  { label: 'Entry 173', value: 173 },
  { label: 'Entry 174', value: 174 },
  { label: 'Entry 175', value: 175 },
  { label: 'Entry 176', value: 176 },
  { label: 'Entry 177', value: 177 },
  { label: 'Entry 178', value: 178 },
  { label: 'Entry 179', value: 179 },
  { label: 'Entry 180', value: 180 },
  { label: 'Entry 181', value: 181 },
  { label: 'Entry 182', value: 182 },
  { label: 'Entry 183', value: 183 },
  { label: 'Entry 184', value: 184 },
  { label: 'Entry 185', value: 185 },
  { label: 'Entry 186', value: 186 },
  { label: 'Entry 187', value: 187 },
  { label: 'Entry 188', value: 188 },
  { label: 'Entry 189', value: 189 },
  { label: 'Entry 190', value: 190 },
  { label: 'Entry 191', value: 191 },
  { label: 'Entry 192', value: 192 },
  { label: 'Entry 193', value: 193 },
  { label: 'Entry 194', value: 194 },
  { label: 'Entry 195', value: 195 },
  { label: 'Entry 196', value: 196 },
  { label: 'Entry 197', value: 197 },
  { label: 'Entry 198', value: 198 },
  { label: 'Entry 199', value: 199 },
  { label: 'Entry 200', value: 200 },
  { label: 'Entry 201', value: 201 },
  { label: 'Entry 202', value: 202 },
  { label: 'Entry 203', value: 203 },
  { label: 'Entry 204', value: 204 },
  { label: 'Entry 205', value: 205 },
  { label: 'Entry 206', value: 206 },
  { label: 'Entry 207', value: 207 },
  { label: 'Entry 208', value: 208 },
  { label: 'Entry 209', value: 209 },
  { label: 'Entry 210', value: 210 },
  { label: 'Entry 211', value: 211 },
  { label: 'Entry 212', value: 212 },
  { label: 'Entry 213', value: 213 },
  { label: 'Entry 214', value: 214 },
  { label: 'Entry 215', value: 215 },
  { label: 'Entry 216', value: 216 },
  { label: 'Entry 217', value: 217 },
  { label: 'Entry 218', value: 218 },
  { label: 'Entry 219', value: 219 },
  { label: 'Entry 220', value: 220 },
  { label: 'Entry 221', value: 221 },
  { label: 'Entry 222', value: 222 },
  { label: 'Entry 223', value: 223 },
  { label: 'Entry 224', value: 224 },
  { label: 'Entry 225', value: 225 },
  { label: 'Entry 226', value: 226 },
  { label: 'Entry 227', value: 227 },
  { label: 'Entry 228', value: 228 },
  { label: 'Entry 229', value: 229 },
  { label: 'Entry 230', value: 230 },
  { label: 'Entry 231', value: 231 },
  { label: 'Entry 232', value: 232 },
  { label: 'Entry 233', value: 233 },
  { label: 'Entry 234', value: 234 },
  { label: 'Entry 235', value: 235 },
  { label: 'Entry 236', value: 236 },
  { label: 'Entry 237', value: 237 },
  { label: 'Entry 238', value: 238 },
  { label: 'Entry 239', value: 239 },
  { label: 'Entry 240', value: 240 },
  { label: 'Entry 241', value: 241 },
  { label: 'Entry 242', value: 242 },
  { label: 'Entry 243', value: 243 },
  { label: 'Entry 244', value: 244 },
  { label: 'Entry 245', value: 245 },
  { label: 'Entry 246', value: 246 },
  { label: 'Entry 247', value: 247 },
  { label: 'Entry 248', value: 248 },
  { label: 'Entry 249', value: 249 },
  { label: 'Entry 250', value: 250 },
  { label: 'Entry 251', value: 251 },
  { label: 'Entry 252', value: 252 },
  { label: 'Entry 253', value: 253 },
  { label: 'Entry 254', value: 254 },
];

export const ItemList = [
  { label: 'All Swords/   Separator', value: 0x00 },
  { label: 'All Spears/   Iron Sword', value: 0x01 },
  { label: 'All Axes/   Thin Sword', value: 0x02 },
  { label: 'All Bows/   Steel Sword', value: 0x03 },
  { label: 'All Staves/   Silver Sword', value: 0x04 },
  { label: 'All Anima/   Iron Blade', value: 0x05 },
  { label: 'All Light/   Steel Blade', value: 0x06 },
  { label: 'All Dark/   Silver Blade', value: 0x07 },
  { label: 'Poison Sword', value: 0x08 },
  { label: 'Disarmed(required)/   Rapier', value: 0x09 },
  { label: 'Mani Katti (DUMMY)', value: 0x0A },
  { label: 'Hero Sword', value: 0x0B },
  { label: 'Shamshir', value: 0x0C },
  { label: 'Killer Sword', value: 0x0D },
  { label: 'Armour Killer', value: 0x0E },
  { label: 'Dragon Killer', value: 0x0F },
  { label: 'Light Sword', value: 0x10 },
  { label: 'Rune Sword', value: 0x11 },
  { label: 'Lancebuster', value: 0x12 },
  { label: 'Long Sword', value: 0x13 },
  { label: 'Iron Spear', value: 0x14 },
  { label: 'Thin Spear', value: 0x15 },
  { label: 'Steel Spear', value: 0x16 },
  { label: 'Silver Spear', value: 0x17 },
  { label: 'Poison Spear', value: 0x18 },
  { label: 'Hero Spear', value: 0x19 },
  { label: 'Killer Spear', value: 0x1A },
  { label: 'Horse Killer', value: 0x1B },
  { label: 'Javelin', value: 0x1C },
  { label: 'Slender Spear', value: 0x1D },
  { label: 'Axebuster', value: 0x1E },
  { label: 'Iron Axe', value: 0x1F },
  { label: 'Steel Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Poison Axe', value: 0x22 },
  { label: 'Hero Axe', value: 0x23 },
  { label: 'Killer Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Hammer', value: 0x26 },
  { label: 'Devil Axe', value: 0x27 },
  { label: 'Hand Axe', value: 0x28 },
  { label: 'Tomahawk', value: 0x29 },
  { label: 'Swordbuster', value: 0x2A },
  { label: 'Swordkiller', value: 0x2B },
  { label: 'Trainee Axe', value: 0x2C },
  { label: 'Iron Bow', value: 0x2D },
  { label: 'Steel Bow', value: 0x2E },
  { label: 'Silver Bow', value: 0x2F },
  { label: 'Poison Bow', value: 0x30 },
  { label: 'Killer Bow', value: 0x31 },
  { label: 'Hero Bow', value: 0x32 },
  { label: 'Short Bow', value: 0x33 },
  { label: 'Long Bow', value: 0x34 },
  { label: 'Iron Ballista', value: 0x35 },
  { label: 'Killer Ballista', value: 0x36 },
  { label: 'Ballista', value: 0x37 },
  { label: 'Fire', value: 0x38 },
  { label: 'Thunder', value: 0x39 },
  { label: 'Elfire', value: 0x3A },
  { label: 'Thunderstorm', value: 0x3B },
  { label: 'Fimbulvetr', value: 0x3C },
  { label: 'Forblaze (DUMMY)', value: 0x3D },
  { label: 'Excalibur', value: 0x3E },
  { label: 'Lightning', value: 0x3F },
  { label: 'Shine', value: 0x40 },
  { label: 'Divine', value: 0x41 },
  { label: 'Purge', value: 0x42 },
  { label: 'Aura', value: 0x43 },
  { label: 'Luce (DUMMY)', value: 0x44 },
  { label: 'Flux', value: 0x45 },
  { label: 'Luna', value: 0x46 },
  { label: 'Nosferatu', value: 0x47 },
  { label: 'Eclipse', value: 0x48 },
  { label: 'Fenrir', value: 0x49 },
  { label: 'Gleipnir', value: 0x4A },
  { label: 'Live', value: 0x4B },
  { label: 'Relive', value: 0x4C },
  { label: 'Recover', value: 0x4D },
  { label: 'Libro', value: 0x4E },
  { label: 'Reserve', value: 0x4F },
  { label: 'Rest', value: 0x50 },
  { label: 'Silence', value: 0x51 },
  { label: 'Sleep', value: 0x52 },
  { label: 'Berserk', value: 0x53 },
  { label: 'Warp', value: 0x54 },
  { label: 'Rescue', value: 0x55 },
  { label: 'Torch', value: 0x56 },
  { label: 'Hammerne', value: 0x57 },
  { label: 'Unlock', value: 0x58 },
  { label: 'Magic Shield', value: 0x59 },
  { label: 'Dragon Axe', value: 0x5A },
  { label: 'Angelic Robe', value: 0x5B },
  { label: 'Energy Ring', value: 0x5C },
  { label: 'Secret Book', value: 0x5D },
  { label: 'Speedwings', value: 0x5E },
  { label: 'Goddess Icon', value: 0x5F },
  { label: 'Dragonshield', value: 0x60 },
  { label: 'Talisman', value: 0x61 },
  { label: 'Boots', value: 0x62 },
  { label: 'Body Ring', value: 0x63 },
  { label: 'Hero\'s Proof', value: 0x64 },
  { label: 'Knight\'s Proof', value: 0x65 },
  { label: 'Orion\'s Bolt', value: 0x66 },
  { label: 'Elysian Whip', value: 0x67 },
  { label: 'Guiding Ring', value: 0x68 },
  { label: 'Chest Key', value: 0x69 },
  { label: 'Door Key', value: 0x6A },
  { label: 'Thief Key', value: 0x6B },
  { label: 'Vulnerary', value: 0x6C },
  { label: 'Elixir', value: 0x6D },
  { label: 'Holy Water', value: 0x6E },
  { label: 'Antidote', value: 0x6F },
  { label: 'Torch', value: 0x70 },
  { label: 'Free Shield', value: 0x71 },
  { label: 'Member Card', value: 0x72 },
  { label: 'Silver Card', value: 0x73 },
  { label: 'White Gem', value: 0x74 },
  { label: 'Blue Gem', value: 0x75 },
  { label: 'Red Gem', value: 0x76 },
  { label: '1G', value: 0x77 },
  { label: 'Reginleif', value: 0x78 },
  { label: 'Chest Key (5)', value: 0x79 },
  { label: 'Mine (DUMMY)', value: 0x7A },
  { label: 'Light Rune (DUMMY)', value: 0x7B },
  { label: 'Hopron Shield', value: 0x7C },
  { label: 'Filla\'s Might (DUMMY)', value: 0x7D },
  { label: 'Ninis\'s Grace (DUMMY)', value: 0x7E },
  { label: 'Thor\'s Ire (DUMMY)', value: 0x7F },
  { label: 'Set\'s Litany (DUMMY)', value: 0x80 },
  { label: 'Shadow Killer', value: 0x81 },
  { label: 'Bright Lance', value: 0x82 },
  { label: 'Fiend Cleaver', value: 0x83 },
  { label: 'Beacon Bow', value: 0x84 },
  { label: 'Sieglind', value: 0x85 },
  { label: 'Battle Axe', value: 0x86 },
  { label: 'Ivaldi', value: 0x87 },
  { label: 'Master Proof', value: 0x88 },
  { label: 'Metis\'s Tome', value: 0x89 },
  { label: 'Heaven Seal (DUMMY)', value: 0x8A },
  { label: 'Sharp Claw', value: 0x8B },
  { label: 'Latona', value: 0x8C },
  { label: 'Dragon Spear', value: 0x8D },
  { label: 'Vidofnir', value: 0x8E },
  { label: 'Naglfal', value: 0x8F },
  { label: 'Decaying Breath', value: 0x90 },
  { label: 'Audomra', value: 0x91 },
  { label: 'Siegmund', value: 0x92 },
  { label: 'Garm', value: 0x93 },
  { label: 'Nidhogg', value: 0x94 },
  { label: 'Heavy Spear', value: 0x95 },
  { label: 'Short Spear', value: 0x96 },
  { label: 'Conqueror\'s Proof', value: 0x97 },
  { label: 'Moon Bracelet', value: 0x98 },
  { label: 'Sun Bracelet', value: 0x99 },
  { label: '1G', value: 0x9A },
  { label: '5G', value: 0x9B },
  { label: '10G', value: 0x9C },
  { label: '50G', value: 0x9D },
  { label: '100G', value: 0x9E },
  { label: '3000G', value: 0x9F },
  { label: '5000G', value: 0xA0 },
  { label: 'Wind Sword', value: 0xA1 },
  { label: 'Vulnerary', value: 0xA2 },
  { label: 'Vulnerary (green note)', value: 0xA3 },
  { label: 'Vulnerary (red note)', value: 0xA4 },
  { label: 'Dance', value: 0xA5 },
  { label: 'Nightmare', value: 0xA6 },
  { label: 'Demon Shard', value: 0xA7 },
  { label: 'Demon Light', value: 0xA8 },
  { label: 'Ravager', value: 0xA9 },
  { label: 'Holy Dragon Stone', value: 0xAA },
  { label: 'Demon Surge', value: 0xAB },
  { label: 'Shadowshot', value: 0xAC },
  { label: 'Rotten Claw', value: 0xAD },
  { label: 'Fetid Claw', value: 0xAE },
  { label: 'Poison Claw', value: 0xAF },
  { label: 'Long Poison Claw', value: 0xB0 },
  { label: 'Fire Fang', value: 0xB1 },
  { label: 'Hell Fang', value: 0xB2 },
  { label: 'Evil Eye', value: 0xB3 },
  { label: 'Bloody Eye', value: 0xB4 },
  { label: 'Stone', value: 0xB5 },
  { label: 'Aircalibur', value: 0xB6 },
  { label: 'Juna Fruit', value: 0xB7 },
  { label: '150G', value: 0xB8 },
  { label: '200G', value: 0xB9 },
  { label: 'Black Gem', value: 0xBA },
  { label: 'Gold Gem', value: 0xBB },
  { label: '-', value: 0xBC },
  { label: '-', value: 0xBD },
  { label: '-', value: 0xBE },
  { label: '-', value: 0xBF },
  { label: '-', value: 0xC0 },
  { label: '-', value: 0xC1 },
  { label: '-', value: 0xC2 },
  { label: '-', value: 0xC3 },
  { label: '-', value: 0xC4 },
  { label: '-', value: 0xC5 },
  { label: '-', value: 0xC6 },
  { label: '-', value: 0xC7 },
  { label: '-', value: 0xC8 },
  { label: '-', value: 0xC9 },
  { label: '-', value: 0xCA },
  { label: '-', value: 0xCB },
  { label: '-', value: 0xCC },
  { label: '-', value: 0xCD },
  { label: '-', value: 0xCE },
  { label: '-', value: 0xCF },
  { label: '-', value: 0xD0 },
  { label: '-', value: 0xD1 },
  { label: '-', value: 0xD2 },
  { label: '-', value: 0xD3 },
  { label: '-', value: 0xD4 },
  { label: '-', value: 0xD5 },
  { label: '-', value: 0xD6 },
  { label: '-', value: 0xD7 },
  { label: '-', value: 0xD8 },
  { label: '-', value: 0xD9 },
  { label: '-', value: 0xDA },
  { label: '-', value: 0xDB },
  { label: '-', value: 0xDC },
  { label: '-', value: 0xDD },
  { label: '-', value: 0xDE },
  { label: '-', value: 0xDF },
  { label: '-', value: 0xE0 },
  { label: '-', value: 0xE1 },
  { label: '-', value: 0xE2 },
  { label: '-', value: 0xE3 },
  { label: '-', value: 0xE4 },
  { label: '-', value: 0xE5 },
  { label: '-', value: 0xE6 },
  { label: '-', value: 0xE7 },
  { label: '-', value: 0xE8 },
  { label: '-', value: 0xE9 },
  { label: '-', value: 0xEA },
  { label: '-', value: 0xEB },
  { label: '-', value: 0xEC },
  { label: '-', value: 0xED },
  { label: '-', value: 0xEE },
  { label: '-', value: 0xEF },
  { label: '-', value: 0xF0 },
  { label: '-', value: 0xF1 },
  { label: '-', value: 0xF2 },
  { label: '-', value: 0xF3 },
  { label: '-', value: 0xF4 },
  { label: '-', value: 0xF5 },
  { label: '-', value: 0xF6 },
  { label: '-', value: 0xF7 },
  { label: '-', value: 0xF8 },
  { label: '-', value: 0xF9 },
  { label: '-', value: 0xFA },
  { label: '-', value: 0xFB },
  { label: '-', value: 0xFC },
  { label: '-', value: 0xFD },
  { label: '-', value: 0xFE },
  { label: '-', value: 0xFF },
];

export const FE8RangedAttackAnimations = [
  { label: '- Nothing', value: 0x00 },
  { label: '- Hand Axe', value: 0x01 },
  { label: '- Arrow', value: 0x02 },
  { label: '- Javelin #1', value: 0x03 },
  { label: '- Javelin #2', value: 0x04 },
  { label: '- Javelin #3', value: 0x05 },
  { label: '- Javelin #4', value: 0x06 },
  { label: '- Javelin #5', value: 0x07 },
  { label: '- Javelin #6', value: 0x08 },
  { label: '- Javelin #7', value: 0x09 },
  { label: '- Javelin #8', value: 0x0A },
  { label: '- Javelin #9', value: 0x0B },
  { label: '- Javelin #10', value: 0x0C },
  { label: '- Javelin #11', value: 0x0D },
  { label: '- Dance/Play (Regular)', value: 0x0E },
  { label: '- Dance/Play (Regular)', value: 0x0F },
  { label: '- Ballista (Glitchy Arrow)', value: 0x10 },
  { label: '- Nothing (Stalls Battle Screen)', value: 0x11 },
  { label: '- Sword of Seals Fire', value: 0x12 },
  { label: '- Flametongue', value: 0x13 },
  { label: '- Fa\'s Holy Dragon Stone (BGM/SFX-kill)', value: 0x14 },
  { label: '- Iodun\'s Dark Dragon Stone (Mirrored)', value: 0x15 },
  { label: '- Fire', value: 0x16 },
  { label: '- Elfire', value: 0x17 },
  { label: '- Nothing', value: 0x18 },
  { label: '- Thunder', value: 0x19 },
  { label: '- Bolting', value: 0x1A },
  { label: '- Fimbulvetr', value: 0x1B },
  { label: '- Aircalibur (BGM-kill)', value: 0x1C },
  { label: '- Flux', value: 0x1D },
  { label: '- Nosferatu', value: 0x1E },
  { label: '- Lightning', value: 0x1F },
  { label: '- Purge', value: 0x20 },
  { label: '- Nothing (Stalls Battle Screen)', value: 0x21 },
  { label: '- Divine', value: 0x22 },
  { label: '- Nothing (Stalls Battle Screen)', value: 0x23 },
  { label: '- Eclipse', value: 0x24 },
  { label: '- Fenrir', value: 0x25 },
  { label: '- Heal', value: 0x26 },
  { label: '- Mend', value: 0x27 },
  { label: '- Recover', value: 0x28 },
  { label: '- Physic', value: 0x29 },
  { label: '- Fortify (Stalls Batle Screen)', value: 0x2A },
  { label: '- Latona (Stalls Battle Screen)', value: 0x2B },
  { label: '- Restore', value: 0x2C },
  { label: '- Silence', value: 0x2D },
  { label: '- Sleep', value: 0x2E },
  { label: '- Hammerne (Unused)', value: 0x2F },
  { label: '- Beserk', value: 0x30 },
  { label: '- Barrier', value: 0x31 },
  { label: '- Nothing (Restarts Game)', value: 0x32 },
  { label: '- Shine', value: 0x33 },
  { label: '- Luna', value: 0x34 },
  { label: '- Excalibur', value: 0x35 },
  { label: '- Nothing (Stalls Battle Screen)', value: 0x36 },
  { label: '- Aura', value: 0x37 },
  { label: '- Nothing (Stalls Battle Screen)', value: 0x38 },
  { label: '- Nothing (Stalls Battle Screen)', value: 0x39 },
  { label: '- Filla\'s Might', value: 0x3A },
  { label: '- Thor\'s Ire', value: 0x3B },
  { label: '- Nini\'s Grace', value: 0x3C },
  { label: '- Set\'s Litany', value: 0x3D },
  { label: '- Stone', value: 0x3E },
  { label: '- Ivaldi', value: 0x3F },
  { label: '- Demon Light', value: 0x40 },
  { label: '- Gleipnir', value: 0x41 },
  { label: '- Crimson Eye', value: 0x42 },
  { label: '- Evil Eye', value: 0x43 },
  { label: '- Shadowshot', value: 0x44 },
  { label: '- Demon Surge', value: 0x45 },
  { label: '- Naglfar', value: 0x46 },
  { label: '- Wretched Breath', value: 0x47 },
  { label: '- Map Only', value: 0xFE },
  { label: '- None', value: 0xFF },
];

export const OnOff = [
  { label: '- Animation Enabled', value: 0x00 },
  { label: '- Animation Disabled', value: 0xFF },
];
