export const FE3ClassList = [
  { label: 'Lord', value: 0 },
  { label: 'Fighter', value: 1 },
  { label: 'Soldier', value: 2 },
  { label: 'Cavalier', value: 3 },
  { label: 'Paladin', value: 4 },
  { label: 'Dismounted Knight (Male)', value: 5 },
  { label: 'Dismounted Knight (Female)', value: 6 },
  { label: 'Armor Knight', value: 7 },
  { label: 'General', value: 8 },
  { label: 'Pegasus Knight', value: 9 },
  { label: 'Dracoknight', value: 10 },
  { label: 'Hunter', value: 11 },
  { label: 'Sniper', value: 12 },
  { label: 'Archer', value: 13 },
  { label: 'Horseman', value: 14 },
  { label: 'Mamkute (Male)', value: 15 },
  { label: 'Fire Dragon', value: 16 },
  { label: 'Mercenary', value: 17 },
  { label: 'Hero', value: 18 },
  { label: 'Thief', value: 19 },
  { label: 'Commando', value: 20 },
  { label: 'Dancer', value: 21 },
  { label: 'Sister', value: 22 },
  { label: 'Mage (Female)', value: 23 },
  { label: 'Priest (Female)', value: 24 },
  { label: 'Mage (Male)', value: 25 },
  { label: 'Priest (Male)', value: 26 },
  { label: 'Sage', value: 27 },
  { label: 'Mamkute (Female)', value: 28 },
  { label: 'Bandit', value: 29 },
  { label: 'Pirate', value: 30 },
  { label: 'Barbarian', value: 31 },
  { label: 'Berserker', value: 32 },
  { label: 'Dark Knight', value: 33 },
  { label: 'Dark Mage', value: 34 },
  { label: 'Shooter', value: 35 },
  { label: 'Emperor', value: 36 },
  { label: 'Guardian', value: 37 },
  { label: 'Ice Dragon', value: 38 },
  { label: 'Sea Dragon', value: 39 },
  { label: 'Flying Dragon', value: 40 },
  { label: 'Earth Dragon', value: 41 },
  { label: 'Dark Dragon', value: 42 },
  { label: 'Divine Dragon', value: 43 },
  { label: 'Demon Dragon', value: 44 },
];

export default FE3ClassList;
