export const TerrainCostData = [
  { label: 'Dancer/Lord', value: 0 },
  { label: 'Knight', value: 1 },
  { label: 'General', value: 2 },
  { label: 'Cavalier', value: 3 },
  { label: 'Paladin', value: 4 },
  { label: 'Merc/Myrm', value: 5 },
  { label: 'Hero/Swordmaster', value: 6 },
  { label: 'Fighter/Barbarian', value: 7 },
  { label: 'Warrior', value: 8 },
  { label: 'Pirate', value: 9 },
  { label: 'Berserker', value: 10 },
  { label: 'Thief', value: 11 },
  { label: 'Archer', value: 12 },
  { label: 'Sniper', value: 13 },
  { label: 'Hunter', value: 14 },
  { label: 'Horseman', value: 15 },
  { label: 'Freelancer', value: 16 },
  { label: 'Manakete', value: 17 },
  { label: 'Magic Users', value: 18 },
  { label: 'Unused', value: 19 },
  { label: 'Promoted Magic Users', value: 20 },
  { label: 'Flying', value: 21 },
  { label: 'Dragons', value: 22 },
  { label: 'Soldier/Emperor', value: 23 },
  { label: 'Ballistician', value: 24 },
  { label: 'Ice Dragon', value: 25 },
];

export default TerrainCostData;
