export const FE5ScrollsEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
];

export const FE5ItemData = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Iron Sword', value: 0x01 },
  { label: 'Steel Sword', value: 0x02 },
  { label: 'Silver Sword', value: 0x03 },
  { label: 'Thin Sword', value: 0x04 },
  { label: 'Iron Broadsword', value: 0x05 },
  { label: 'Killer Sword', value: 0x06 },
  { label: 'Poison Sword', value: 0x07 },
  { label: 'Berserk Sword', value: 0x08 },
  { label: 'Sleep Sword', value: 0x09 },
  { label: 'Beosword', value: 0x0A },
  { label: 'Holy Sword', value: 0x0B },
  { label: 'Loputous Sword', value: 0x0C },
  { label: 'Blagi Sword', value: 0x0D },
  { label: 'Light Sword', value: 0x0E },
  { label: 'Hero Sword', value: 0x0F },
  { label: 'King Sword', value: 0x10 },
  { label: 'Earth Sword', value: 0x11 },
  { label: 'Wind Sword', value: 0x12 },
  { label: 'Fire Sword', value: 0x13 },
  { label: 'Thunder Sword', value: 0x14 },
  { label: 'Elite Sword', value: 0x15 },
  { label: 'Armour Killer', value: 0x16 },
  { label: 'Rapier', value: 0x17 },
  { label: 'Short Sword', value: 0x18 },
  { label: 'Long Sword', value: 0x19 },
  { label: 'Great Sword', value: 0x1A },
  { label: 'Master Sword', value: 0x1B },
  { label: 'Darkness Sword', value: 0x1C },
  { label: 'Mareeta\'s Sword', value: 0x1D },
  { label: 'Broken Sword', value: 0x1E },
  { label: 'Iron Lance', value: 0x1F },
  { label: 'Steel Lance', value: 0x20 },
  { label: 'Silver Lance', value: 0x21 },
  { label: 'Thin Lance', value: 0x22 },
  { label: 'Poison Lance', value: 0x23 },
  { label: 'Dragon Lance', value: 0x24 },
  { label: 'Darkness Lance', value: 0x25 },
  { label: 'Hero Lance', value: 0x26 },
  { label: 'Short Lance', value: 0x27 },
  { label: 'Long Lance', value: 0x28 },
  { label: 'Great Lance', value: 0x29 },
  { label: 'Javelin', value: 0x2A },
  { label: 'Master Lance', value: 0x2B },
  { label: 'Knight Killer', value: 0x2C },
  { label: 'Killer Lance', value: 0x2D },
  { label: 'Gae Bolg', value: 0x2E },
  { label: 'Gungnir', value: 0x2F },
  { label: 'Broken Lance', value: 0x30 },
  { label: 'Iron Axe', value: 0x31 },
  { label: 'Poison Axe', value: 0x32 },
  { label: 'Steel Axe', value: 0x33 },
  { label: 'Silver Axe', value: 0x34 },
  { label: 'Hand Axe', value: 0x35 },
  { label: 'Hammer', value: 0x36 },
  { label: 'Killer Axe', value: 0x37 },
  { label: 'Pugi', value: 0x38 },
  { label: 'Hero Axe', value: 0x39 },
  { label: 'Devil Axe', value: 0x3A },
  { label: 'Battle Axe', value: 0x3B },
  { label: 'Poleaxe', value: 0x3C },
  { label: 'Master Axe', value: 0x3D },
  { label: 'Broken Axe', value: 0x3E },
  { label: 'Iron Bow', value: 0x3F },
  { label: 'Steel Bow', value: 0x40 },
  { label: 'Silver Bow', value: 0x41 },
  { label: 'Poison Bow', value: 0x42 },
  { label: 'Killer Bow', value: 0x43 },
  { label: 'Hero Bow', value: 0x44 },
  { label: 'Short Bow', value: 0x45 },
  { label: 'Long Bow', value: 0x46 },
  { label: 'Great Bow', value: 0x47 },
  { label: 'Master Bow', value: 0x48 },
  { label: 'Long Arch', value: 0x49 },
  { label: 'Iron Arch', value: 0x4A },
  { label: 'Killer Arch', value: 0x4B },
  { label: 'Poison Arch', value: 0x4C },
  { label: 'Broken Bow', value: 0x4D },
  { label: 'Fire', value: 0x4E },
  { label: 'Elfire', value: 0x4F },
  { label: 'Volcannon', value: 0x50 },
  { label: 'Falaflame', value: 0x51 },
  { label: 'Thunder', value: 0x52 },
  { label: 'Daim Thunder', value: 0x53 },
  { label: 'Tron', value: 0x54 },
  { label: 'Torhammer', value: 0x55 },
  { label: 'Wind', value: 0x56 },
  { label: 'Grafucalibur', value: 0x57 },
  { label: 'Tornado', value: 0x58 },
  { label: 'Holsety', value: 0x59 },
  { label: 'Lightning', value: 0x5A },
  { label: 'Rizziah', value: 0x5B },
  { label: 'Aura', value: 0x5C },
  { label: 'Yotsmungand', value: 0x5D },
  { label: 'Fenrir', value: 0x5E },
  { label: 'Hell', value: 0x5F },
  { label: 'Loputous', value: 0x60 },
  { label: 'Meteo', value: 0x61 },
  { label: 'Thunderstorm', value: 0x62 },
  { label: 'Blizzard', value: 0x63 },
  { label: 'Poison', value: 0x64 },
  { label: 'Stone', value: 0x65 },
  { label: 'Holsety(Unlimited)', value: 0x66 },
  { label: 'Broken Book', value: 0x67 },
  { label: 'Live', value: 0x68 },
  { label: 'Relive', value: 0x69 },
  { label: 'Recover', value: 0x6A },
  { label: 'Libro', value: 0x6B },
  { label: 'Reserve', value: 0x6C },
  { label: 'Rescue', value: 0x6D },
  { label: 'Warp', value: 0x6E },
  { label: 'Rest', value: 0x6F },
  { label: 'Silence', value: 0x70 },
  { label: 'Sleep', value: 0x71 },
  { label: 'Torch', value: 0x72 },
  { label: 'Return', value: 0x73 },
  { label: 'Repair', value: 0x74 },
  { label: 'Thief', value: 0x75 },
  { label: 'Watch', value: 0x76 },
  { label: 'Berserk', value: 0x77 },
  { label: 'Unlock', value: 0x78 },
  { label: 'Magic Shield', value: 0x79 },
  { label: 'Rewarp', value: 0x7A },
  { label: 'Cure', value: 0x7B },
  { label: 'Broken Staff', value: 0x7C },
  { label: 'Luck Ring', value: 0x7D },
  { label: 'Live Ring', value: 0x7E },
  { label: 'Speed Ring', value: 0x7F },
  { label: 'Magic Ring', value: 0x80 },
  { label: 'Power Ring', value: 0x81 },
  { label: 'Body Ring', value: 0x82 },
  { label: 'Shield Ring', value: 0x83 },
  { label: 'Skill Ring', value: 0x84 },
  { label: 'Leg Ring', value: 0x85 },
  { label: 'Knight Proof', value: 0x86 },
  { label: 'Master Proof', value: 0x87 },
  { label: 'Treasure Key', value: 0x88 },
  { label: 'Door Key', value: 0x89 },
  { label: 'Bridge Key', value: 0x8A },
  { label: 'Thief Key', value: 0x8B },
  { label: 'S Drink', value: 0x8C },
  { label: 'Medicine', value: 0x8D },
  { label: 'Holy Water', value: 0x8E },
  { label: 'Torch', value: 0x8F },
  { label: 'Antidote', value: 0x90 },
  { label: 'Member Card', value: 0x91 },
  { label: 'Odo Scroll', value: 0x92 },
  { label: 'Baldo Scroll', value: 0x93 },
  { label: 'Hezul Scroll', value: 0x94 },
  { label: 'Dain Scroll', value: 0x95 },
  { label: 'Noba Scroll', value: 0x96 },
  { label: 'Neir Scroll', value: 0x97 },
  { label: 'Ulir Scroll', value: 0x98 },
  { label: 'Tordo Scroll', value: 0x99 },
  { label: 'Fala Scroll', value: 0x9A },
  { label: 'Sety Scroll', value: 0x9B },
  { label: 'Blagi Scroll', value: 0x9C },
  { label: 'Heim Scroll', value: 0x9D },
  { label: 'Elite Manual', value: 0x9E },
  { label: 'Duel Manual', value: 0x9F },
  { label: 'Bargain Manual', value: 0xA0 },
  { label: 'Ambush Manual', value: 0xA1 },
  { label: 'Wrath Manual', value: 0xA2 },
  { label: 'Continue Manual', value: 0xA3 },
  { label: 'Prayer Manual', value: 0xA4 },
  { label: 'Awareness Manual', value: 0xA5 },
  { label: 'Sunlight Manual', value: 0xA6 },
  { label: 'Moonlight Manual', value: 0xA7 },
];
