export const FE7OceanSealPromotionEditorEntries = [
  { label: 'Entry 0', value: 0 },
];

export const PromotionAddress = [
  { label: 'Default Hero Crest', value: 0x8C97EDD },
  { label: 'Default Knight Crest', value: 0x8C97EE3 },
  { label: 'Default Orion Bolt', value: 0x8C97EE8 },
  { label: 'Default Elysian Whip', value: 0x8C97EED },
  { label: 'Default Guiding Ring', value: 0x8C97EF1 },
  { label: 'Default Master Seal', value: 0x8C97EFD },
  { label: 'Default Ocean Seal', value: 0x8C97F24 },
  { label: 'Default Fallen Contract', value: 0x8C97F29 },
  { label: 'Hector & Lyn', value: 0x8C97F16 },
  { label: 'Eliwood & Lyn', value: 0x8C97F21 },
  { label: 'Dancer & Bard', value: 0x8C97F26 },
  { label: 'Eliwood', value: 0X8C97F2B },
  { label: 'Hector', value: 0x8C97F2F },
  { label: 'Lyn', value: 0x8C97F33 },
  { label: 'Archsage', value: 0x8C97F37 },
  { label: 'Custom', value: 0x8FFFA00 },
  { label: 'Custom', value: 0x8FFFA20 },
  { label: 'Custom', value: 0x8FFFA40 },
  { label: 'Custom', value: 0x8FFFA60 },
  { label: 'Custom', value: 0x8FFFA80 },
  { label: 'Custom', value: 0x8FFFAA0 },
  { label: 'Custom', value: 0x8FFFAC0 },
  { label: 'Custom', value: 0x8FFFAE0 },
  { label: 'Custom', value: 0x8FFFB00 },
  { label: 'Custom', value: 0x8FFFB20 },
  { label: 'Custom', value: 0x8FFFB40 },
  { label: 'Custom', value: 0x8FFFB60 },
  { label: 'Custom', value: 0x8FFFB80 },
  { label: 'Custom', value: 0x8FFFBA0 },
  { label: 'Custom', value: 0x8FFFBC0 },
  { label: 'Custom', value: 0x8FFFBE0 },
];
