export const FE3115ManaketePrincessStartEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
];

export const FE3Characters = [
  { label: 'Marth', value: 0x00 },
  { label: 'Caeda', value: 0x01 },
  { label: 'Jagen', value: 0x02 },
  { label: 'Cain', value: 0x03 },
  { label: 'Abel', value: 0x04 },
  { label: 'Draug', value: 0x05 },
  { label: 'Gordin', value: 0x06 },
  { label: 'Rickard', value: 0x07 },
  { label: 'Wrys (unused)', value: 0x08 },
  { label: 'Bord', value: 0x09 },
  { label: 'Cord', value: 0x0A },
  { label: 'Barst', value: 0x0B },
  { label: 'Castor', value: 0x0C },
  { label: 'Ogma', value: 0x0D },
  { label: 'Darros', value: 0x0E },
  { label: 'Julian', value: 0x0F },
  { label: 'Lena', value: 0x10 },
  { label: 'Merric', value: 0x11 },
  { label: 'Navarre', value: 0x12 },
  { label: 'Hardin', value: 0x13 },
  { label: 'Wolf', value: 0x14 },
  { label: 'Sedgar', value: 0x15 },
  { label: 'Roshea', value: 0x16 },
  { label: 'Vyland', value: 0x17 },
  { label: 'Bantu', value: 0x18 },
  { label: 'Caesar', value: 0x19 },
  { label: 'Radd', value: 0x1A },
  { label: 'Midia', value: 0x1B },
  { label: 'Catria', value: 0x1C },
  { label: 'Maria', value: 0x1D },
  { label: 'Minerva', value: 0x1E },
  { label: 'Linde', value: 0x1F },
  { label: 'Jeorge', value: 0x20 },
  { label: 'Dolph', value: 0x21 },
  { label: 'Macellan', value: 0x22 },
  { label: 'Tomas', value: 0x23 },
  { label: 'Boah', value: 0x24 },
  { label: 'Arran', value: 0x25 },
  { label: 'Samson', value: 0x26 },
  { label: 'Beck', value: 0x27 },
  { label: 'Xane', value: 0x28 },
  { label: 'Wendell', value: 0x29 },
  { label: 'Est', value: 0x2A },
  { label: 'Astram', value: 0x2B },
  { label: 'Matthis', value: 0x2C },
  { label: 'Roger', value: 0x2D },
  { label: 'Jake', value: 0x2E },
  { label: 'Palla', value: 0x2F },
  { label: 'Tiki', value: 0x30 },
  { label: 'Lorenz', value: 0x31 },
  { label: 'Elice', value: 0x32 },
  { label: 'Gotoh', value: 0x33 },
  { label: 'Rickard (Enemy)', value: 0x34 },
  { label: 'Jeorge (Enemy)', value: 0x35 },
  { label: 'Navarre (Enemy)', value: 0x36 },
  { label: 'Matthis (Enemy)', value: 0x37 },
  { label: 'Sheena (Enemy)', value: 0x38 },
  { label: 'Samson (Enemy)', value: 0x39 },
  { label: '????', value: 0x3A },
  { label: '????', value: 0x3B },
  { label: 'Minerva (Enemy)', value: 0x3C },
  { label: '????', value: 0x3D },
  { label: 'Astram (Enemy)', value: 0x3E },
  { label: 'Palla (Enemy)', value: 0x3F },
  { label: '????', value: 0x40 },
  { label: 'Est (Enemy)', value: 0x41 },
  { label: '????', value: 0x42 },
  { label: '????', value: 0x43 },
  { label: '????', value: 0x44 },
  { label: 'Enemy', value: 0x45 },
  { label: 'Gharnef', value: 0x46 },
  { label: 'Boss?', value: 0x47 },
  { label: 'Boss?', value: 0x48 },
  { label: 'Michalis', value: 0x49 },
  { label: 'Boss?', value: 0x4A },
  { label: 'Enemy', value: 0x4B },
  { label: 'Enemy', value: 0x4C },
  { label: 'Enemy', value: 0x4D },
  { label: 'Enemy', value: 0x4E },
  { label: 'Enemy', value: 0x4F },
  { label: 'Enemy', value: 0x50 },
  { label: 'Enemy', value: 0x51 },
  { label: 'Enemy', value: 0x52 },
  { label: 'Enemy', value: 0x53 },
  { label: 'Enemy', value: 0x54 },
  { label: 'Enemy', value: 0x55 },
  { label: 'Enemy', value: 0x56 },
  { label: 'Enemy', value: 0x57 },
  { label: 'Enemy', value: 0x58 },
  { label: 'Enemy', value: 0x59 },
  { label: 'Boss?', value: 0x5A },
  { label: 'Boss?', value: 0x5B },
  { label: 'Enemy', value: 0x5C },
  { label: 'Enemy', value: 0x5D },
  { label: 'Enemy', value: 0x5E },
  { label: 'Enemy', value: 0x5F },
  { label: 'Enemy', value: 0x60 },
  { label: 'Enemy', value: 0x61 },
  { label: 'Enemy', value: 0x62 },
  { label: 'Enemy', value: 0x63 },
  { label: 'Enemy', value: 0x64 },
  { label: 'Enemy', value: 0x65 },
  { label: 'Enemy', value: 0x66 },
  { label: 'Enemy', value: 0x67 },
  { label: 'Enemy', value: 0x68 },
  { label: 'Enemy', value: 0x69 },
  { label: 'Enemy', value: 0x6A },
  { label: 'Camus', value: 0x6B },
  { label: 'Cecil', value: 0x6C },
  { label: 'Luke', value: 0x6D },
  { label: 'Roderick', value: 0x6E },
  { label: 'Ryan', value: 0x6F },
  { label: 'Warren', value: 0x70 },
  { label: 'Enemy', value: 0x71 },
  { label: 'Enemy', value: 0x72 },
  { label: 'Yuliya', value: 0x73 },
  { label: 'Jubelo', value: 0x74 },
  { label: 'Sirius', value: 0x75 },
  { label: 'Enemy', value: 0x76 },
  { label: 'Marisha', value: 0x77 },
  { label: 'Enemy', value: 0x78 },
  { label: 'Samuel', value: 0x79 },
  { label: 'Enemy', value: 0x7A },
  { label: 'Phina', value: 0x7B },
  { label: 'Enemy', value: 0x7C },
  { label: 'Enemy', value: 0x7D },
  { label: 'Enemy', value: 0x7E },
  { label: 'Enemy', value: 0x7F },
  { label: 'Sheena', value: 0x80 },
  { label: 'Marth (Book 2)', value: 0x81 },
  { label: 'Arran (Book 2)', value: 0x82 },
  { label: 'Gordin (Book 2)', value: 0x83 },
  { label: 'Draug (Book 2)', value: 0x84 },
  { label: 'Linde (Book 2)', value: 0x85 },
  { label: 'Matthis (Book 2)', value: 0x86 },
  { label: 'Julian (Book 2)', value: 0x87 },
  { label: 'Catria (Book 2)', value: 0x88 },
  { label: 'Ogma (Book 2)', value: 0x89 },
  { label: 'Castor (Book 2)', value: 0x8A },
  { label: 'Rickard (Book 2)', value: 0x8B },
  { label: 'Jeorge (Book 2)', value: 0x8C },
  { label: 'Wendell (Book 2)', value: 0x8D },
  { label: 'Navarre (Book 2)', value: 0x8E },
  { label: 'Astram (Book 2)', value: 0x8F },
  { label: 'Caeda (Book 2)', value: 0x90 },
  { label: 'Cain (Book 2)', value: 0x91 },
  { label: 'Bantu (Book 2)', value: 0x92 },
  { label: '????', value: 0x93 },
  { label: 'Merric (Book 2)', value: 0x94 },
  { label: 'Arlen', value: 0x95 },
  { label: 'Minerva (Book 2)', value: 0x96 },
  { label: 'Xane (Book 2)', value: 0x97 },
  { label: 'Tiki (Book 2)', value: 0x98 },
  { label: 'Abel (Book 2)', value: 0x99 },
  { label: '????', value: 0x9A },
  { label: 'Samson (Book 2)', value: 0x9B },
  { label: 'Enemy', value: 0x9C },
  { label: 'Vyland (Book 2)', value: 0x9D },
  { label: 'Roshea (Book 2)', value: 0x9E },
  { label: 'Enemy', value: 0x9F },
  { label: 'Medea (Book 2)', value: 0xA0 },
  { label: 'Enemy', value: 0xA1 },
  { label: 'Enemy', value: 0xA2 },
  { label: 'Enemy', value: 0xA3 },
  { label: 'Enemy', value: 0xA4 },
  { label: 'Enemy', value: 0xA5 },
  { label: 'Enemy', value: 0xA6 },
  { label: 'Nyna', value: 0xA7 },
  { label: 'Maria (Book 2)', value: 0xA8 },
  { label: 'Elice (Book 2)', value: 0xA9 },
  { label: 'Lena (Book 2)', value: 0xAA },
  { label: 'Palla (Book 2)', value: 0xAB },
  { label: 'stop', value: 0xFF },
];

export const FE3Classes = [
  { label: 'Lord', value: 0x00 },
  { label: 'Fighter', value: 0x01 },
  { label: 'Soldier', value: 0x02 },
  { label: 'Cavalier', value: 0x03 },
  { label: 'Paladin', value: 0x04 },
  { label: 'Dismounted Knight (Male)', value: 0x05 },
  { label: 'Dismounted Knight (Female)', value: 0x06 },
  { label: 'Armor Knight', value: 0x07 },
  { label: 'General', value: 0x08 },
  { label: 'Pegasus Knight', value: 0x09 },
  { label: 'Dracoknight', value: 0x0A },
  { label: 'Hunter', value: 0x0B },
  { label: 'Sniper', value: 0x0C },
  { label: 'Archer', value: 0x0D },
  { label: 'Horseman', value: 0x0E },
  { label: 'Manakete (Male)', value: 0x0F },
  { label: 'Fire Dragon', value: 0x10 },
  { label: 'Mercenary', value: 0x11 },
  { label: 'Hero', value: 0x12 },
  { label: 'Thief', value: 0x13 },
  { label: 'Commando', value: 0x14 },
  { label: 'Dancer', value: 0x15 },
  { label: 'Sister', value: 0x16 },
  { label: 'Mage (Female)', value: 0x17 },
  { label: 'Priest (Female)', value: 0x18 },
  { label: 'Mage (Male)', value: 0x19 },
  { label: 'Priest (Male)', value: 0x1A },
  { label: 'Sage', value: 0x1B },
  { label: 'Manakete (Female)', value: 0x1C },
  { label: 'Bandit', value: 0x1D },
  { label: 'Pirate', value: 0x1E },
  { label: 'Barbarian', value: 0x1F },
  { label: 'Berserker', value: 0x20 },
  { label: 'Dark Knight', value: 0x21 },
  { label: 'Dark Mage', value: 0x22 },
  { label: 'Shooter', value: 0x23 },
  { label: 'Emperor', value: 0x24 },
  { label: 'Guardian', value: 0x25 },
  { label: 'Ice Dragon', value: 0x26 },
  { label: 'Sea Dragon', value: 0x27 },
  { label: 'Flying Dragon', value: 0x28 },
  { label: 'Earth Dragon', value: 0x29 },
  { label: 'Dark Dragon', value: 0x2A },
  { label: 'Divine Dragon', value: 0x2B },
  { label: 'Demon Dragon', value: 0x2C },
];

export const FE3Names = [
  { label: 'Marth', value: 0x00 },
  { label: 'Caeda', value: 0x01 },
  { label: 'Jagen', value: 0x02 },
  { label: 'Cain', value: 0x03 },
  { label: 'Abel', value: 0x04 },
  { label: 'Draug', value: 0x05 },
  { label: 'Gordin', value: 0x06 },
  { label: 'Rickard', value: 0x07 },
  { label: 'Wrys (leftover from fe1)', value: 0x08 },
  { label: 'Bord', value: 0x09 },
  { label: 'Cord', value: 0x0A },
  { label: 'Barst', value: 0x0B },
  { label: 'Castor', value: 0x0C },
  { label: 'Ogma', value: 0x0D },
  { label: 'Darros (leftover from fe1)', value: 0x0E },
  { label: 'Julian', value: 0x0F },
  { label: 'Lena', value: 0x10 },
  { label: 'Merric', value: 0x11 },
  { label: 'Navarre', value: 0x12 },
  { label: 'Hardin', value: 0x13 },
  { label: 'Wolf', value: 0x14 },
  { label: 'Sedgar', value: 0x15 },
  { label: 'Roshea', value: 0x16 },
  { label: 'Vyland', value: 0x17 },
  { label: 'Bantu', value: 0x18 },
  { label: 'Caesar', value: 0x19 },
  { label: 'Radd', value: 0x1A },
  { label: 'Midia', value: 0x1B },
  { label: 'Catria', value: 0x1C },
  { label: 'Maria', value: 0x1D },
  { label: 'Minerva', value: 0x1E },
  { label: 'Linde', value: 0x1F },
  { label: 'Jeorge', value: 0x20 },
  { label: 'Dolph', value: 0x21 },
  { label: 'Macellan', value: 0x22 },
  { label: 'Tomas', value: 0x23 },
  { label: 'Boah', value: 0x24 },
  { label: 'Arran', value: 0x25 },
  { label: 'Samson', value: 0x26 },
  { label: 'Beck (leftover from fe1)', value: 0x27 },
  { label: 'Xane', value: 0x28 },
  { label: 'Wendell', value: 0x29 },
  { label: 'Est', value: 0x2A },
  { label: 'Astram', value: 0x2B },
  { label: 'Matthis', value: 0x2C },
  { label: 'Roger (leftover from fe1)', value: 0x2D },
  { label: 'Jake (leftover from fe1)', value: 0x2E },
  { label: 'Palla', value: 0x2F },
  { label: 'Tiki', value: 0x30 },
  { label: 'Lorenz', value: 0x31 },
  { label: 'Elice', value: 0x32 },
  { label: 'Gotoh', value: 0x33 },
  { label: 'Gazzak', value: 0x34 },
  { label: 'Wylar (unused)', value: 0x35 },
  { label: 'Grust Soldier', value: 0x36 },
  { label: 'Gomer', value: 0x37 },
  { label: 'Garuda Soldier', value: 0x38 },
  { label: 'Sabre (unused)', value: 0x39 },
  { label: 'Merach', value: 0x3A },
  { label: 'Harmein', value: 0x3B },
  { label: 'Emereus', value: 0x3C },
  { label: 'Bentheon (leftover from fe1)', value: 0x3D },
  { label: 'Kannival', value: 0x3E },
  { label: 'Mannu (leftover from fe1)', value: 0x3F },
  { label: 'Zharov', value: 0x40 },
  { label: 'Khozen', value: 0x41 },
  { label: 'Heimler (leftover from fe1)', value: 0x42 },
  { label: 'Grigas (leftover from fe1)', value: 0x43 },
  { label: 'Jiol', value: 0x44 },
  { label: 'Volzhin', value: 0x45 },
  { label: 'Hollstadt', value: 0x46 },
  { label: 'Sternlin (leftover from fe1)', value: 0x47 },
  { label: 'Hyman', value: 0x48 },
  { label: 'Xemcel', value: 0x49 },
  { label: 'Orridyon (leftover from fe1)', value: 0x4A },
  { label: 'Camus', value: 0x4B },
  { label: 'Michalis', value: 0x4C },
  { label: 'Morzas', value: 0x4D },
  { label: 'Gharnef', value: 0x4E },
  { label: 'Medeus', value: 0x4F },
  { label: 'Dolhr', value: 0x50 },
  { label: 'Gra', value: 0x51 },
  { label: 'Pyrathi', value: 0x52 },
  { label: 'Chiasmir', value: 0x53 },
  { label: 'SableOrd', value: 0x54 },
  { label: 'Khadein', value: 0x55 },
  { label: 'IronKnt', value: 0x56 },
  { label: 'Dragoon', value: 0x57 },
  { label: 'IronKnt', value: 0x58 },
  { label: 'Medon', value: 0x59 },
  { label: 'Pegasus', value: 0x5A },
  { label: 'Ruffian', value: 0x5B },
  { label: 'Raman', value: 0x5C },
  { label: 'Dark Mage', value: 0x5D },
  { label: 'Priest', value: 0x5E },
  { label: 'Ruffian', value: 0x5F },
  { label: 'Gharnef', value: 0x60 },
  { label: 'Cecil', value: 0x61 },
  { label: 'Luke', value: 0x62 },
  { label: 'Roderick', value: 0x63 },
  { label: 'Ryan', value: 0x64 },
  { label: 'Warren', value: 0x65 },
  { label: 'Brave', value: 0x66 },
  { label: 'Rumel', value: 0x67 },
  { label: 'Rucke', value: 0x68 },
  { label: 'Yuliya', value: 0x69 },
  { label: 'Jubelo', value: 0x6A },
  { label: 'Sirius', value: 0x6B },
  { label: 'Gail', value: 0x6C },
  { label: 'Paiking', value: 0x6D },
  { label: 'Marisha', value: 0x6E },
  { label: 'Toras', value: 0x6F },
  { label: 'Samuel', value: 0x70 },
  { label: 'Lang', value: 0x71 },
  { label: 'Phina', value: 0x72 },
  { label: 'Dahl', value: 0x73 },
  { label: 'Laman Thief', value: 0x74 },
  { label: 'Yodel', value: 0x75 },
  { label: 'Arlen', value: 0x76 },
  { label: 'FlyingDr', value: 0x77 },
  { label: 'Sand Tribe', value: 0x78 },
  { label: 'Evil Fighter', value: 0x79 },
  { label: 'Bandit', value: 0x7A },
  { label: 'Thief', value: 0x7B },
  { label: 'Good Dragon?', value: 0x7C },
  { label: 'Ice Dragon', value: 0x7D },
  { label: 'Ice Thief (wtf?)', value: 0x7E },
  { label: 'Eibel', value: 0x7F },
  { label: 'Sheena', value: 0x80 },
  { label: 'Earth Dragon', value: 0x81 },
  { label: 'Dark Priest', value: 0x82 },
  { label: 'Willow', value: 0x83 },
  { label: 'Akanea Soldier', value: 0x84 },
  { label: 'Orleans Soldier', value: 0x85 },
  { label: 'Nyna', value: 0x86 },
  { label: 'Khadein Mercenary', value: 0x87 },
  { label: 'Fire Tribe', value: 0x88 },
  { label: 'Earth Tribe', value: 0x89 },
  { label: 'Nehring', value: 0x8A },
  { label: 'Dark Tribe', value: 0x8B },
  { label: 'Dark Dragon', value: 0x8C },
  { label: 'Bodyguard', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'Nothing', value: 0xFF },
];

export const FE3Portraits = [
  { label: 'Marth', value: 0x00 },
  { label: 'Caeda', value: 0x01 },
  { label: 'Jagen', value: 0x02 },
  { label: 'Cain', value: 0x03 },
  { label: 'Abel', value: 0x04 },
  { label: 'Draug', value: 0x05 },
  { label: 'Gordin', value: 0x06 },
  { label: 'Rickard', value: 0x07 },
  { label: 'Pirate', value: 0x08 },
  { label: 'Bord', value: 0x09 },
  { label: 'Cord', value: 0x0A },
  { label: 'Barst', value: 0x0B },
  { label: 'Castor', value: 0x0C },
  { label: 'Ogma', value: 0x0D },
  { label: 'Brigand', value: 0x0E },
  { label: 'Julian', value: 0x0F },
  { label: 'Lena', value: 0x10 },
  { label: 'Merric', value: 0x11 },
  { label: 'Navarre', value: 0x12 },
  { label: 'Hardin', value: 0x13 },
  { label: 'Wolf', value: 0x14 },
  { label: 'Sedgar', value: 0x15 },
  { label: 'Roshea', value: 0x16 },
  { label: 'Vyland', value: 0x17 },
  { label: 'Bantu', value: 0x18 },
  { label: 'Caesar', value: 0x19 },
  { label: 'Radd', value: 0x1A },
  { label: 'Midia', value: 0x1B },
  { label: 'Catria', value: 0x1C },
  { label: 'Maria', value: 0x1D },
  { label: 'Minerva', value: 0x1E },
  { label: 'Linde', value: 0x1F },
  { label: 'Jeorge', value: 0x20 },
  { label: 'Dolph', value: 0x21 },
  { label: 'Macellan', value: 0x22 },
  { label: 'Tomas', value: 0x23 },
  { label: 'Boah', value: 0x24 },
  { label: 'Arran', value: 0x25 },
  { label: 'Samson', value: 0x26 },
  { label: 'Soldier', value: 0x27 },
  { label: 'Xane', value: 0x28 },
  { label: 'Wendell', value: 0x29 },
  { label: 'Est', value: 0x2A },
  { label: 'Astram', value: 0x2B },
  { label: 'Matthis', value: 0x2C },
  { label: 'Social Knight', value: 0x2D },
  { label: 'Dragon Knight', value: 0x2E },
  { label: 'Palla', value: 0x2F },
  { label: 'Tiki', value: 0x30 },
  { label: 'Lorenz', value: 0x31 },
  { label: 'Elice', value: 0x32 },
  { label: 'Gotoh', value: 0x33 },
  { label: 'Gazzak', value: 0x34 },
  { label: 'Thief', value: 0x35 },
  { label: 'Hunter', value: 0x36 },
  { label: 'Gomer', value: 0x37 },
  { label: 'Archer', value: 0x38 },
  { label: 'Blank', value: 0x39 },
  { label: 'Merach', value: 0x3a },
  { label: 'Harmein', value: 0x3b },
  { label: 'Emereus', value: 0x3c },
  { label: 'Sniper', value: 0x3d },
  { label: 'Kannival', value: 0x3e },
  { label: 'Mannu', value: 0x3f },
  { label: 'Zharov', value: 0x40 },
  { label: 'Khozen', value: 0x41 },
  { label: 'Barbarian', value: 0x42 },
  { label: 'Shooter', value: 0x43 },
  { label: 'Jiol', value: 0x44 },
  { label: 'Volzhin', value: 0x45 },
  { label: 'Hollstadt', value: 0x46 },
  { label: 'Pegasus Knight', value: 0x47 },
  { label: 'Hyman', value: 0x48 },
  { label: 'Xemcel', value: 0x49 },
  { label: 'Blank', value: 0x4A },
  { label: 'Camus', value: 0x4B },
  { label: 'Michalis', value: 0x4C },
  { label: 'Morzas', value: 0x4D },
  { label: 'Gharnef', value: 0x4E },
  { label: 'Medeus', value: 0x4F },
  { label: 'Armor Knight', value: 0x50 },
  { label: 'Nehring', value: 0x51 },
  { label: 'General', value: 0x52 },
  { label: 'Mercenary', value: 0x53 },
  { label: 'Black', value: 0x54 },
  { label: 'Hero', value: 0x55 },
  { label: 'Black', value: 0x56 },
  { label: 'Mage', value: 0x57 },
  { label: 'Sister', value: 0x58 },
  { label: 'Priest', value: 0x59 },
  { label: 'Dark Mage', value: 0x5A },
  { label: 'Mamkute', value: 0x5B },
  { label: 'Dragon', value: 0x5C },
  { label: 'Paladin', value: 0x5D },
  { label: 'Dark Knight', value: 0x5E },
  { label: 'Horseman', value: 0x5F },
  { label: 'Old Talking Guy', value: 0x60 },
  { label: 'Nyna', value: 0x61 },
  { label: 'King Tellius', value: 0x62 },
  { label: 'King Orleans', value: 0x63 },
  { label: 'Middle Aged Man Green', value: 0x64 },
  { label: 'Middle Aged Man Red', value: 0x65 },
  { label: 'Middle Aged Man Grey', value: 0x66 },
  { label: 'Old Man', value: 0x67 },
  { label: 'Old Woman', value: 0x68 },
  { label: 'Drunk Guy', value: 0x69 },
  { label: 'Middle Aged Woman', value: 0x6A },
  { label: 'Young Man (Weird)', value: 0x6B },
  { label: 'Village Girl', value: 0x6C },
  { label: 'Arena Clerk', value: 0x6D },
  { label: 'Weapon Shop Clerk', value: 0x6E },
  { label: 'Marisha\'s Grandma?', value: 0x6F },
  { label: 'Magic Shop Clerk', value: 0x70 },
  { label: 'Anna', value: 0x71 },
  { label: 'Slave Trader', value: 0x72 },
  { label: 'Linde (Dressed as Boy)', value: 0x73 },
  { label: 'Soldier', value: 0x74 },
  { label: 'Cecil', value: 0x75 },
  { label: 'Luke', value: 0x76 },
  { label: 'Roderick', value: 0x77 },
  { label: 'Ryan', value: 0x78 },
  { label: 'Warren', value: 0x79 },
  { label: 'Rumel', value: 0x7A },
  { label: 'Rucke', value: 0x7B },
  { label: 'Yuliya', value: 0x7C },
  { label: 'Jubelo', value: 0x7D },
  { label: 'Sirius', value: 0x7E },
  { label: 'Gail', value: 0x7F },
  { label: 'Marisha', value: 0x80 },
  { label: 'Toras', value: 0x81 },
  { label: 'Samuel', value: 0x82 },
  { label: 'Lang', value: 0x83 },
  { label: 'Phina', value: 0x84 },
  { label: 'Dahl', value: 0x85 },
  { label: 'Yodel', value: 0x86 },
  { label: 'Arlen', value: 0x87 },
  { label: 'Eibel', value: 0x88 },
  { label: 'Sheena', value: 0x89 },
  { label: 'Willow', value: 0x8A },
  { label: 'Marth (Book 2)', value: 0x8B },
  { label: 'Caeda (Book 2)', value: 0x8C },
  { label: 'Linde (Book 2)', value: 0x8D },
  { label: 'Merric (Book 2)', value: 0x8E },
  { label: 'Tiki (Book 2)', value: 0x8F },
  { label: 'Marth (Book 2)', value: 0x90 },
  { label: 'Medeus (Dragon)', value: 0x91 },
  { label: 'Minerva (Book 2)', value: 0x92 },
  { label: 'Hardin (Book 2)', value: 0x93 },
];

export const FE3Items = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Steel Sword', value: 0x01 },
  { label: 'Silver Sword', value: 0x02 },
  { label: 'Rapier', value: 0x03 },
  { label: 'Killer Sword', value: 0x04 },
  { label: 'Devil Sword', value: 0x05 },
  { label: 'Broken Sword', value: 0x06 },
  { label: 'Master Sword', value: 0x07 },
  { label: 'Lady Sword', value: 0x08 },
  { label: 'Thunder Sword', value: 0x09 },
  { label: 'Mercurius', value: 0x0A },
  { label: 'Falchion', value: 0x0B },
  { label: 'Armor Killer', value: 0x0C },
  { label: 'Dragon Killer', value: 0x0D },
  { label: 'Sword Killer', value: 0x0E },
  { label: 'Iron Lance', value: 0x0F },
  { label: 'Steel Lance', value: 0x10 },
  { label: 'Silver Lance', value: 0x11 },
  { label: 'Knight Killer', value: 0x12 },
  { label: 'Javelin', value: 0x13 },
  { label: 'Broken Lance', value: 0x14 },
  { label: 'Killer Lance', value: 0x15 },
  { label: 'Thin Lance', value: 0x16 },
  { label: 'Gradivus', value: 0x17 },
  { label: 'Iron Bow', value: 0x18 },
  { label: 'Broken Bow', value: 0x19 },
  { label: 'Steel Bow', value: 0x1A },
  { label: 'Silver Bow', value: 0x1B },
  { label: 'Killer Bow', value: 0x1C },
  { label: 'Parthia', value: 0x1D },
  { label: 'Iron Axe', value: 0x1E },
  { label: 'Steel Axe', value: 0x1F },
  { label: 'Hand Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Devil Axe', value: 0x22 },
  { label: 'Broken Axe', value: 0x23 },
  { label: 'Thunderbolt', value: 0x24 },
  { label: 'Quick Rain', value: 0x25 },
  { label: 'Stone Hedge', value: 0x26 },
  { label: 'Fire Gun', value: 0x27 },
  { label: 'Elephant', value: 0x28 },
  { label: 'Fire Breath', value: 0x29 },
  { label: 'Ice Breath', value: 0x2A },
  { label: 'Dark Breath', value: 0x2B },
  { label: 'Mist Breath', value: 0x2C },
  { label: 'Fire', value: 0x2D },
  { label: 'Thunder', value: 0x2E },
  { label: 'Blizzard', value: 0x2F },
  { label: 'Shaver', value: 0x30 },
  { label: 'Elfire', value: 0x31 },
  { label: 'Thoron', value: 0x32 },
  { label: 'Bolganone', value: 0x33 },
  { label: 'Excalibur', value: 0x34 },
  { label: 'Aura', value: 0x35 },
  { label: 'Starlight', value: 0x36 },
  { label: 'Imhullu', value: 0x37 },
  { label: 'Dulam', value: 0x38 },
  { label: 'Resire', value: 0x39 },
  { label: 'Meteor', value: 0x3A },
  { label: 'Worm', value: 0x3B },
  { label: 'Earth Orb', value: 0x3C },
  { label: 'Shield of Seals', value: 0x3D },
  { label: 'Dark Orb', value: 0x3E },
  { label: 'Fire Emblem', value: 0x3F },
  { label: 'Heal', value: 0x40 },
  { label: 'Recover', value: 0x41 },
  { label: 'Physic', value: 0x42 },
  { label: 'Mend', value: 0x43 },
  { label: 'Warp', value: 0x44 },
  { label: 'Magic Shield', value: 0x45 },
  { label: 'Hammerne', value: 0x46 },
  { label: 'Fortify', value: 0x47 },
  { label: 'Silence', value: 0x48 },
  { label: 'Rescue', value: 0x49 },
  { label: 'Aum', value: 0x4A },
  { label: 'Unlock', value: 0x4B },
  { label: 'Thief Staff', value: 0x4C },
  { label: 'Watch Staff', value: 0x4D },
  { label: 'Again Staff', value: 0x4E },
  { label: 'Fire Dragon Stone', value: 0x4F },
  { label: 'Aum', value: 0x50 },
  { label: 'Ice Dragon Stone', value: 0x51 },
  { label: 'Flying Dragon Stone', value: 0x52 },
  { label: 'Earth Dragon Stone', value: 0x53 },
  { label: 'Dark Dragon Stone', value: 0x54 },
  { label: 'Divine Dragon Stone', value: 0x55 },
  { label: 'Demon Dragon Stone', value: 0x56 },
  { label: 'Vulnerary', value: 0x57 },
  { label: 'Door Key', value: 0x58 },
  { label: 'Silver Key', value: 0x59 },
  { label: 'Bridge Key', value: 0x5A },
  { label: 'Treasure Key', value: 0x5B },
  { label: 'Energy Ring', value: 0x5C },
  { label: 'Shield Ring', value: 0x5D },
  { label: 'Secret Book', value: 0x5E },
  { label: 'Speed Ring', value: 0x5F },
  { label: 'Amulet', value: 0x60 },
  { label: 'Angelic Robe', value: 0x61 },
  { label: 'Goddess Icon', value: 0x62 },
  { label: 'Manual', value: 0x63 },
  { label: 'Boots', value: 0x64 },
  { label: 'Pure Water', value: 0x65 },
  { label: 'Knight Crest', value: 0x66 },
  { label: 'Hero Crest', value: 0x67 },
  { label: 'Guiding Ring', value: 0x68 },
  { label: 'Elysian Whip', value: 0x69 },
  { label: 'Orion\'s Bolt', value: 0x6A },
  { label: 'Earth Orb', value: 0x6B },
  { label: 'Life Orb', value: 0x6C },
  { label: 'Iote Shield', value: 0x6D },
  { label: 'Aquarius Orb', value: 0x6E },
  { label: 'Pisces Orb', value: 0x6F },
  { label: 'Aries Orb', value: 0x70 },
  { label: 'Taurus Orb', value: 0x71 },
  { label: 'Gemini Orb', value: 0x72 },
  { label: 'Cancer Orb', value: 0x73 },
  { label: 'Leo Orb', value: 0x74 },
  { label: 'Virgo Orb', value: 0x75 },
  { label: 'Libra Orb', value: 0x76 },
  { label: 'Scorpio Orb', value: 0x77 },
  { label: 'Sagittarius Orb', value: 0x78 },
  { label: 'Capricorn Orb', value: 0x79 },
  { label: 'Aum Fragment', value: 0x7A },
  { label: 'Silver Card', value: 0x7B },
  { label: 'Member Card', value: 0x7C },
  { label: 'Light Orb', value: 0x7D },
  { label: 'Star Orb', value: 0x7E },
  { label: 'Nothing', value: 0xFF },
];
