export const Chapters = [
  { label: '0x00 Debug Map', value: 0 },
  { label: '0x01 1-1: Marth Embarks', value: 1 },
  { label: '0x02 1-3: A Brush in The Teeth', value: 2 },
  { label: '0x03 1-4: Champion of Aurelis', value: 3 },
  { label: '0x04 1-5: Fire Emblem', value: 4 },
  { label: '0x05 1-6: Lefcandith Gauntlet', value: 5 },
  { label: '0x06 1-8: Princess Minerva', value: 6 },
  { label: '0x07 1-9: Knorda Slave Market', value: 7 },
  { label: '0x08 1-10: The Ageless Palace', value: 8 },
  { label: '0x09 1-11: Land of Sorrow', value: 9 },
  { label: '0x0A 1-12: An Oasis of Magic', value: 10 },
  { label: '0x0B 1-13: The Battle for Altea', value: 11 },
  { label: '0x0C 1-14: Star and Savior', value: 12 },
  { label: '0x0D 1-15: Manakete Princess', value: 13 },
  { label: '0x0E 1-16: Camus the Sable', value: 14 },
  { label: '0x0F 1-17: A Knight-Filled Sky', value: 15 },
  { label: '0x10 1-18: Dark Pontifex', value: 16 },
  { label: '0x11 1-20: Chosen by Fate', value: 17 },
  { label: '0x12 2-1: The Grustian Expedition', value: 18 },
  { label: '0x13 2-18: Battle of the Pass', value: 19 },
  { label: '0x14 2-4: Joy and Sorrow', value: 20 },
  { label: '0x15 2-2: Rebellion at Macedon', value: 21 },
  { label: '0x16 2-3: Abducted Princess', value: 22 },
  { label: '0x17 Cutscene?', value: 23 },
  { label: '0x18 2-5: Liberation of Grust', value: 24 },
  { label: '0x19 2-6: The Nest of Evil', value: 25 },
  { label: '0x1A 2-7: The Scarlet Swordsman', value: 26 },
  { label: '0x1B Cutscene?', value: 27 },
  { label: '0x1C 2-8: Soulful Bridge', value: 28 },
  { label: '0x1D 2-9: Sanctuary of Sorcery', value: 29 },
  { label: '0x1E 2-10: Two Sorcerers', value: 30 },
  { label: '0x1F 2-15: Return of the Prince', value: 31 },
  { label: '0x20 2-16: Regaining the Capital', value: 32 },
  { label: '0x21 2-11: Anri\'s Way', value: 33 },
  { label: '0x22 Cutscene?', value: 34 },
  { label: '0x23 2-12: Graveyard of Fire Dragons', value: 35 },
  { label: '0x24 2-13: Frozen Land', value: 36 },
  { label: '0x25 2-14: A Mystery Revealed', value: 37 },
  { label: '0x26 2-17: Gra\'s Sun Sets', value: 38 },
  { label: '0x27 2-21: The Wyvern\'s Dale', value: 39 },
  { label: '0x28 2-19: The Last Decisive Battle', value: 40 },
  { label: '0x29 2-20: Dark Emperor', value: 41 },
  { label: '0x2A Dragon\'s Table: Part 1', value: 42 },
  { label: '0x2B Dragon\'s Table: Part 2', value: 43 },
  { label: '0x2C Dragon\'s Table: Part 3', value: 44 },
  { label: '0x2D 1-2: The Pirates of Galder', value: 45 },
  { label: '0x2E 1-7: The Scarlet Sword', value: 46 },
  { label: '0x2F 1-19: The Dragonkin Realm', value: 47 },
];

export const FE3Classes = [
  { label: 'Lord', value: 0x00 },
  { label: 'Fighter', value: 0x01 },
  { label: 'Soldier', value: 0x02 },
  { label: 'Cavalier', value: 0x03 },
  { label: 'Paladin', value: 0x04 },
  { label: 'Dismounted Knight (Male)', value: 0x05 },
  { label: 'Dismounted Knight (Female)', value: 0x06 },
  { label: 'Armor Knight', value: 0x07 },
  { label: 'General', value: 0x08 },
  { label: 'Pegasus Knight', value: 0x09 },
  { label: 'Dracoknight', value: 0x0A },
  { label: 'Hunter', value: 0x0B },
  { label: 'Sniper', value: 0x0C },
  { label: 'Archer', value: 0x0D },
  { label: 'Horseman', value: 0x0E },
  { label: 'Manakete (Male)', value: 0x0F },
  { label: 'Fire Dragon', value: 0x10 },
  { label: 'Mercenary', value: 0x11 },
  { label: 'Hero', value: 0x12 },
  { label: 'Thief', value: 0x13 },
  { label: 'Commando', value: 0x14 },
  { label: 'Dancer', value: 0x15 },
  { label: 'Sister', value: 0x16 },
  { label: 'Mage (Female)', value: 0x17 },
  { label: 'Priest (Female)', value: 0x18 },
  { label: 'Mage (Male)', value: 0x19 },
  { label: 'Priest (Male)', value: 0x1A },
  { label: 'Sage', value: 0x1B },
  { label: 'Manakete (Female)', value: 0x1C },
  { label: 'Bandit', value: 0x1D },
  { label: 'Pirate', value: 0x1E },
  { label: 'Barbarian', value: 0x1F },
  { label: 'Berserker', value: 0x20 },
  { label: 'Dark Knight', value: 0x21 },
  { label: 'Dark Mage', value: 0x22 },
  { label: 'Shooter', value: 0x23 },
  { label: 'Emperor', value: 0x24 },
  { label: 'Guardian', value: 0x25 },
  { label: 'Ice Dragon', value: 0x26 },
  { label: 'Sea Dragon', value: 0x27 },
  { label: 'Flying Dragon', value: 0x28 },
  { label: 'Earth Dragon', value: 0x29 },
  { label: 'Dark Dragon', value: 0x2A },
  { label: 'Divine Dragon', value: 0x2B },
  { label: 'Demon Dragon', value: 0x2C },
];

export const Map = [
  { label: 'Outdoor', value: 0x00 },
  { label: 'Indoor', value: 0x01 },
];
