export const FE6DeathquoteeditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
  { label: 'Entry 68', value: 68 },
  { label: 'Entry 69', value: 69 },
  { label: 'Entry 70', value: 70 },
  { label: 'Entry 71', value: 71 },
  { label: 'Entry 72', value: 72 },
  { label: 'Entry 73', value: 73 },
  { label: 'Entry 74', value: 74 },
  { label: 'Entry 75', value: 75 },
  { label: 'Entry 76', value: 76 },
  { label: 'Entry 77', value: 77 },
  { label: 'Entry 78', value: 78 },
  { label: 'Entry 79', value: 79 },
  { label: 'Entry 80', value: 80 },
  { label: 'Entry 81', value: 81 },
  { label: 'Entry 82', value: 82 },
  { label: 'Entry 83', value: 83 },
  { label: 'Entry 84', value: 84 },
  { label: 'Entry 85', value: 85 },
  { label: 'Entry 86', value: 86 },
  { label: 'Entry 87', value: 87 },
  { label: 'Entry 88', value: 88 },
  { label: 'Entry 89', value: 89 },
  { label: 'Entry 90', value: 90 },
  { label: 'Entry 91', value: 91 },
  { label: 'Entry 92', value: 92 },
  { label: 'Entry 93', value: 93 },
  { label: 'Entry 94', value: 94 },
  { label: 'Entry 95', value: 95 },
  { label: 'Entry 96', value: 96 },
  { label: 'Entry 97', value: 97 },
  { label: 'Entry 98', value: 98 },
  { label: 'Entry 99', value: 99 },
  { label: 'Entry 100', value: 100 },
  { label: 'Entry 101', value: 101 },
  { label: 'Entry 102', value: 102 },
  { label: 'Entry 103', value: 103 },
  { label: 'Entry 104', value: 104 },
  { label: 'Entry 105', value: 105 },
  { label: 'Entry 106', value: 106 },
  { label: 'Entry 107', value: 107 },
];

export const Characters = [
  { label: 'None', value: 0x00 },
  { label: 'Roy', value: 0x01 },
  { label: 'Clarine', value: 0x02 },
  { label: 'Fa', value: 0x03 },
  { label: 'Shin', value: 0x04 },
  { label: 'Sue', value: 0x05 },
  { label: 'Dayan', value: 0x06 },
  { label: 'Dayan (NPC)', value: 0x07 },
  { label: 'Barth', value: 0x08 },
  { label: 'Bors', value: 0x09 },
  { label: 'Wendy', value: 0x0A },
  { label: 'Douglas', value: 0x0B },
  { label: 'Douglas (NPC)', value: 0x0C },
  { label: 'Wolt', value: 0x0D },
  { label: 'Dorothy', value: 0x0E },
  { label: 'Klein', value: 0x0F },
  { label: 'Saul', value: 0x10 },
  { label: 'Elen', value: 0x11 },
  { label: 'Yodel', value: 0x12 },
  { label: 'Yodel (NPC)', value: 0x13 },
  { label: 'Chad', value: 0x14 },
  { label: 'Karel', value: 0x15 },
  { label: 'Fir', value: 0x16 },
  { label: 'Rutger', value: 0x17 },
  { label: 'Dieck', value: 0x18 },
  { label: 'Oujay', value: 0x19 },
  { label: 'Garet', value: 0x1A },
  { label: 'Alan', value: 0x1B },
  { label: 'Lance', value: 0x1C },
  { label: 'Percival', value: 0x1D },
  { label: 'Igrene', value: 0x1E },
  { label: 'Marcus', value: 0x1F },
  { label: 'Astol', value: 0x20 },
  { label: 'Ward', value: 0x21 },
  { label: 'Lot', value: 0x22 },
  { label: 'Bartre', value: 0x23 },
  { label: 'Bartre (NPC)', value: 0x24 },
  { label: 'Lugh', value: 0x25 },
  { label: 'Lilina', value: 0x26 },
  { label: 'Hugh', value: 0x27 },
  { label: 'Niime', value: 0x28 },
  { label: 'Niime (NPC)', value: 0x29 },
  { label: 'Rei', value: 0x2A },
  { label: 'Lalam', value: 0x2B },
  { label: 'Yunno', value: 0x2C },
  { label: 'Yunno (NPC)', value: 0x2D },
  { label: 'Thito', value: 0x2E },
  { label: 'Thito (enemy)', value: 0x2F },
  { label: 'Thito (NPC)', value: 0x30 },
  { label: 'Thany', value: 0x31 },
  { label: 'Zeiss', value: 0x32 },
  { label: 'Gale', value: 0x33 },
  { label: 'Elfin', value: 0x34 },
  { label: 'Cass', value: 0x35 },
  { label: 'Sophia', value: 0x36 },
  { label: 'Miledy', value: 0x37 },
  { label: 'Gonzales', value: 0x38 },
  { label: 'Gonzales (NPC)', value: 0x39 },
  { label: 'Noah', value: 0x3A },
  { label: 'Treck', value: 0x3B },
  { label: 'Zealot', value: 0x3C },
  { label: 'Echidna', value: 0x3D },
  { label: 'Echidna (NPC)', value: 0x3E },
  { label: 'Cecilia', value: 0x3F },
  { label: 'Geese', value: 0x40 },
  { label: 'Geese (NPC)', value: 0x41 },
  { label: 'Merlinus', value: 0x42 },
  { label: 'Eliwood', value: 0x43 },
  { label: 'Guinevere', value: 0x44 },
  { label: 'Bandit', value: 0x45 },
  { label: 'Bandit', value: 0x46 },
  { label: 'Bandit', value: 0x47 },
  { label: 'Bandit', value: 0x48 },
  { label: 'Bandit', value: 0x49 },
  { label: 'Damas', value: 0x4A },
  { label: 'Rude', value: 0x4B },
  { label: 'Slater', value: 0x4C },
  { label: 'Erik', value: 0x4D },
  { label: 'Dory', value: 0x4E },
  { label: 'Wagner', value: 0x4F },
  { label: 'Devias', value: 0x50 },
  { label: 'Legylance', value: 0x51 },
  { label: 'Scott', value: 0x52 },
  { label: 'Nord', value: 0x53 },
  { label: 'William', value: 0x54 },
  { label: 'Flaer', value: 0x55 },
  { label: 'Oro', value: 0x56 },
  { label: 'Robarts', value: 0x57 },
  { label: 'Aine', value: 0x58 },
  { label: 'Narshen', value: 0x59 },
  { label: 'Randy', value: 0x5A },
  { label: 'Rose', value: 0x5B },
  { label: 'Maggie', value: 0x5C },
  { label: 'Raeth', value: 0x5D },
  { label: 'Arcard', value: 0x5E },
  { label: 'Martel', value: 0x5F },
  { label: 'Sigune', value: 0x60 },
  { label: 'Roartz', value: 0x61 },
  { label: 'Murdock', value: 0x62 },
  { label: 'Brunya', value: 0x63 },
  { label: 'Zephiel', value: 0x64 },
  { label: 'Idoun (no hood)', value: 0x65 },
  { label: 'Idoun (dragon form)', value: 0x66 },
  { label: 'Yahn', value: 0x67 },
  { label: 'Zinc', value: 0x68 },
  { label: 'Monke', value: 0x69 },
  { label: 'Gel', value: 0x6A },
  { label: 'Brigand', value: 0x6B },
  { label: 'Bern', value: 0x6C },
  { label: 'Bern', value: 0x6D },
  { label: 'Bern', value: 0x6E },
  { label: 'Bern', value: 0x6F },
  { label: 'Bern', value: 0x70 },
  { label: 'Laus', value: 0x71 },
  { label: 'Pirate', value: 0x72 },
  { label: 'Bandit', value: 0x73 },
  { label: 'Thria', value: 0x74 },
  { label: 'Rebel', value: 0x75 },
  { label: 'Bern', value: 0x76 },
  { label: 'Rebel', value: 0x77 },
  { label: 'Officials', value: 0x78 },
  { label: 'Thief', value: 0x79 },
  { label: 'Seihou', value: 0x7A },
  { label: 'Pirate', value: 0x7B },
  { label: 'Almar', value: 0x7C },
  { label: 'Robber', value: 0x7D },
  { label: 'Registrans', value: 0x7E },
  { label: 'Eturia', value: 0x7F },
  { label: 'Bandit', value: 0x80 },
  { label: 'Bandit', value: 0x81 },
  { label: 'Bandit', value: 0x82 },
  { label: 'Bern', value: 0x83 },
  { label: 'Eturian', value: 0x84 },
  { label: 'Isle', value: 0x85 },
  { label: 'Bern', value: 0x86 },
  { label: 'Eturia', value: 0x87 },
  { label: 'Bern', value: 0x88 },
  { label: 'Bandit', value: 0x89 },
  { label: 'Eturia', value: 0x8A },
  { label: 'Bern', value: 0x8B },
  { label: 'Ilia', value: 0x8C },
  { label: 'Bandit', value: 0x8D },
  { label: 'Bern', value: 0x8E },
  { label: 'Eturia', value: 0x8F },
  { label: 'Thief', value: 0x90 },
  { label: 'Bern', value: 0x91 },
  { label: 'Bern', value: 0x92 },
  { label: 'Pirate', value: 0x93 },
  { label: 'Pirate', value: 0x94 },
  { label: 'Ilia', value: 0x95 },
  { label: 'Bern', value: 0x96 },
  { label: 'Ilia', value: 0x97 },
  { label: 'Brigand', value: 0x98 },
  { label: 'Ilia', value: 0x99 },
  { label: 'Fighter', value: 0x9A },
  { label: 'Bandit', value: 0x9B },
  { label: 'Ilia', value: 0x9C },
  { label: 'Citizen', value: 0x9D },
  { label: 'Thief', value: 0x9E },
  { label: 'Bern', value: 0x9F },
  { label: 'Bern', value: 0xA0 },
  { label: 'Bern', value: 0xA1 },
  { label: 'Thief', value: 0xA2 },
  { label: 'Bandit', value: 0xA3 },
  { label: 'Citizen', value: 0xA4 },
  { label: 'Fighter', value: 0xA5 },
  { label: 'Eturia', value: 0xA6 },
  { label: 'Sacae', value: 0xA7 },
  { label: 'Bern', value: 0xA8 },
  { label: 'Djute', value: 0xA9 },
  { label: 'Sacae', value: 0xAA },
  { label: 'Sacae', value: 0xAB },
  { label: 'Bern', value: 0xAC },
  { label: 'Eturia', value: 0xAD },
  { label: 'Sacae', value: 0xAE },
  { label: 'Bern', value: 0xAF },
  { label: 'Mamkute', value: 0xB0 },
  { label: 'Bern', value: 0xB1 },
  { label: 'WarDragon', value: 0xB2 },
  { label: 'Bandit', value: 0xB3 },
  { label: 'Bandit', value: 0xB4 },
  { label: 'Henning', value: 0xB5 },
  { label: 'Scollan', value: 0xB6 },
  { label: 'Bandit', value: 0xB7 },
  { label: 'Grero', value: 0xB8 },
  { label: 'Ohtz', value: 0xB9 },
  { label: 'Teck', value: 0xBA },
  { label: 'Bern', value: 0xBB },
  { label: 'Bern', value: 0xBC },
  { label: 'Bern', value: 0xBD },
  { label: 'Thoril', value: 0xBE },
  { label: 'Brakul', value: 0xBF },
  { label: 'Kudoka', value: 0xC0 },
  { label: 'Marral', value: 0xC1 },
  { label: 'Kabul', value: 0xC2 },
  { label: 'Chan', value: 0xC3 },
  { label: 'Pereth', value: 0xC4 },
  { label: 'Bern', value: 0xC5 },
  { label: 'Windam', value: 0xC6 },
  { label: 'Eturia', value: 0xC7 },
  { label: 'Morgan', value: 0xC8 },
  { label: 'Rebel', value: 0xC9 },
  { label: 'Bern', value: 0xCA },
  { label: 'Bern', value: 0xCB },
  { label: 'Bern', value: 0xCC },
  { label: 'Citizen', value: 0xCD },
  { label: 'Citizen', value: 0xCE },
  { label: 'Hector', value: 0xCF },
  { label: 'Bors', value: 0xD0 },
  { label: 'Commander', value: 0xD1 },
  { label: 'Commander', value: 0xD2 },
  { label: 'Percival\'s Unit', value: 0xD3 },
  { label: 'Bandit', value: 0xD4 },
  { label: 'Percival\'s Unit', value: 0xD5 },
  { label: 'Percival\'s Unit', value: 0xD6 },
  { label: 'Percival\'s Unit', value: 0xD7 },
  { label: 'Klein\'s Unit', value: 0xD8 },
  { label: 'Tate\'s Unit', value: 0xD9 },
  { label: 'Bandit', value: 0xE0 },
  { label: 'Duelist', value: 0xE1 },
];

export const Chapters = [
  { label: 'Tutorial', value: 0x00 },
  { label: 'Ch 1', value: 0x01 },
  { label: 'Ch 2', value: 0x02 },
  { label: 'Ch 3', value: 0x03 },
  { label: 'Ch 4', value: 0x04 },
  { label: 'Ch 5', value: 0x05 },
  { label: 'Ch 6', value: 0x06 },
  { label: 'Ch 7', value: 0x07 },
  { label: 'Ch 8', value: 0x08 },
  { label: 'Ch 9', value: 0x09 },
  { label: 'Ch 10 Lalum', value: 0x0A },
  { label: 'Ch 11 Lalum', value: 0x0B },
  { label: 'Ch 12', value: 0x0C },
  { label: 'Ch 13', value: 0x0D },
  { label: 'Ch 14', value: 0x0E },
  { label: 'Ch 15', value: 0x0F },
  { label: 'Ch 16', value: 0x10 },
  { label: 'Ch 17 Ilia', value: 0x11 },
  { label: 'Ch 18 Ilia', value: 0x12 },
  { label: 'Ch 19 Ilia', value: 0x13 },
  { label: 'Ch 20 Ilia', value: 0x14 },
  { label: 'Ch 21', value: 0x15 },
  { label: 'Ch 22', value: 0x16 },
  { label: 'Ch 23', value: 0x17 },
  { label: 'Ch 24', value: 0x18 },
  { label: 'Ch Final', value: 0x19 },
  { label: 'Ch 10 Elfin', value: 0x1A },
  { label: 'Ch 11 Elfin', value: 0x1B },
  { label: 'Ch 17 Sacae', value: 0x1C },
  { label: 'Ch 18 Sacae', value: 0x1D },
  { label: 'Ch 19 Sacae', value: 0x1E },
  { label: 'Ch 20 Sacae', value: 0x1F },
  { label: 'Ch 8X', value: 0x20 },
  { label: 'Ch 12X', value: 0x21 },
  { label: 'Ch 14X', value: 0x22 },
  { label: 'Ch 16X', value: 0x23 },
  { label: 'Ch 20X Ilia', value: 0x24 },
  { label: 'Ch 20X Sacae', value: 0x25 },
  { label: 'Ch 21X', value: 0x26 },
  { label: 'Link Arena', value: 0x27 },
  { label: 'Trial Map 1', value: 0x28 },
  { label: 'Trial Map 2', value: 0x29 },
  { label: 'Trial Map 3', value: 0x2A },
  { label: 'Trial Map 4', value: 0x2B },
  { label: 'Trial Map 5', value: 0x2C },
  { label: 'All', value: 0x2D },
];
