export const FE4WeaponEditor = [
  { label: 'Iron Sword', value: 0 },
  { label: 'Steel Sword', value: 1 },
  { label: 'Silver Sword', value: 2 },
  { label: 'Iron Blade', value: 3 },
  { label: 'Steel Blade', value: 4 },
  { label: 'Silver Blade', value: 5 },
  { label: 'Prayer Sword', value: 6 },
  { label: 'Thief Sword', value: 7 },
  { label: 'Barrier Sword', value: 8 },
  { label: 'Berserk Sword', value: 9 },
  { label: 'Hero\'s Sword', value: 10 },
  { label: 'Silence Sword', value: 11 },
  { label: 'Sleep Sword', value: 12 },
  { label: 'Thin Sword', value: 13 },
  { label: 'Defence Sword', value: 14 },
  { label: 'Fire Sword', value: 15 },
  { label: 'Earth Sword', value: 16 },
  { label: 'Thunder Sword', value: 17 },
  { label: 'Wind Sword', value: 18 },
  { label: 'Light Sword', value: 19 },
  { label: 'Mistoltin', value: 20 },
  { label: 'Tyrfing', value: 21 },
  { label: 'Balmunk', value: 22 },
  { label: 'Armor Killer', value: 23 },
  { label: 'Wing Clipper', value: 24 },
  { label: 'Broken Sword (A)', value: 25 },
  { label: 'Broken Sword (B)', value: 26 },
  { label: 'Broken Sword (C)', value: 27 },
  { label: 'Iron Lance', value: 28 },
  { label: 'Steel Lance', value: 29 },
  { label: 'Silver Lance', value: 30 },
  { label: 'Hand Lance', value: 31 },
  { label: 'Knight Killer', value: 32 },
  { label: 'Hero\'s Lance', value: 33 },
  { label: 'Thin Lance', value: 34 },
  { label: 'Gungnir', value: 35 },
  { label: 'Gae Bolg', value: 36 },
  { label: 'Broken Lance (A)', value: 37 },
  { label: 'Broken Lance (B)', value: 38 },
  { label: 'Broken Lance (C)', value: 39 },
  { label: 'Iron Axe', value: 40 },
  { label: 'Steel Axe', value: 41 },
  { label: 'Silver Axe', value: 42 },
  { label: 'Hero\'s Axe', value: 43 },
  { label: 'Swanchika', value: 44 },
  { label: 'Hand Axe', value: 45 },
  { label: 'Broken Axe (A)', value: 46 },
  { label: 'Broken Axe (B)', value: 47 },
  { label: 'Broken Axe (C)', value: 48 },
  { label: 'Iron Bow', value: 49 },
  { label: 'Steel Bow', value: 50 },
  { label: 'Silver Bow', value: 51 },
  { label: 'Hero\'s Bow', value: 52 },
  { label: 'Killer Bow', value: 53 },
  { label: 'Ichieval', value: 54 },
  { label: 'Broken Bow (A)', value: 55 },
  { label: 'Broken Bow (B)', value: 56 },
  { label: 'Broken Bow (C)', value: 57 },
  { label: 'Long Arch', value: 58 },
  { label: 'Iron Arch', value: 59 },
  { label: 'Killer Arch', value: 60 },
  { label: 'Gold Arch', value: 61 },
  { label: 'Fire', value: 62 },
  { label: 'El Fire', value: 63 },
  { label: 'Volcanon', value: 64 },
  { label: 'Fala Flame', value: 65 },
  { label: 'Meteo', value: 66 },
  { label: 'Thunder', value: 67 },
  { label: 'El Thunder', value: 68 },
  { label: 'Torron', value: 69 },
  { label: 'Tor Hammer', value: 70 },
  { label: 'Thunderstorm', value: 71 },
  { label: 'Wind', value: 72 },
  { label: 'El Wind', value: 73 },
  { label: 'Tornado', value: 74 },
  { label: 'Holsety', value: 75 },
  { label: 'Blizzard', value: 76 },
  { label: 'Lightning', value: 77 },
  { label: 'Rizziah', value: 78 },
  { label: 'Aura', value: 79 },
  { label: 'Narga', value: 80 },
  { label: 'Yotsmungand', value: 81 },
  { label: 'Fenrir', value: 82 },
  { label: 'Hell', value: 83 },
  { label: 'Loptous', value: 84 },
  { label: 'Empty Book', value: 85 },
  { label: 'Empty Book', value: 86 },
  { label: 'Empty Book', value: 87 },
  { label: 'Live Staff', value: 88 },
  { label: 'Relive Staff', value: 89 },
  { label: 'Recover Staff', value: 90 },
  { label: 'Libro Staff', value: 91 },
  { label: 'Reserve Staff', value: 92 },
  { label: 'Return Staff', value: 93 },
  { label: 'Warp Staff', value: 94 },
  { label: 'Rescue Staff', value: 95 },
  { label: 'Charm Staff', value: 96 },
  { label: 'Rest Staff', value: 97 },
  { label: 'Valkyre Staff', value: 98 },
  { label: 'Silence Staff', value: 99 },
  { label: 'Sleep Staff', value: 100 },
  { label: 'Berserk Staff', value: 101 },
  { label: 'Thief Staff', value: 102 },
  { label: 'Broken Staff', value: 103 },
  { label: 'Broken Staff', value: 104 },
  { label: 'Broken Staff', value: 105 },
  { label: 'Live Bracelet', value: 106 },
  { label: 'Elite Ring', value: 107 },
  { label: 'Thief Bracelet', value: 108 },
  { label: 'Prayer Bracelet', value: 109 },
  { label: 'Pursuit Ring', value: 110 },
  { label: 'Recover Ring', value: 111 },
  { label: 'Bargain Bracelet', value: 112 },
  { label: 'Knight Ring', value: 113 },
  { label: 'Return Ring', value: 114 },
  { label: 'Speed Ring', value: 115 },
  { label: 'Magic Ring', value: 116 },
  { label: 'Power Ring', value: 117 },
  { label: 'Shield Ring', value: 118 },
  { label: 'Barrier Ring', value: 119 },
  { label: 'Leg Ring', value: 120 },
  { label: 'Skill Ring', value: 121 },
  { label: 'Broken Sword', value: 122 },
  { label: 'Broken Lance', value: 123 },
  { label: 'Broken Bow', value: 124 },
  { label: 'Empty Book', value: 125 },
  { label: 'Empty Book', value: 126 },
  { label: 'Empty Book', value: 127 },
  { label: 'Empty Book', value: 128 },
  { label: 'Empty Book', value: 129 },
  { label: 'Empty Book', value: 130 },
  { label: 'Empty Book', value: 131 },
  { label: 'Empty Book', value: 132 },
  { label: 'Empty Book', value: 133 },
  { label: 'Empty Book', value: 134 },
  { label: 'Empty Book', value: 135 },
  { label: 'Broken Staff', value: 136 },
  { label: 'Circlet', value: 137 },
];

export const FE4ItemSprites = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Steel Sword', value: 0x01 },
  { label: 'Silver Sword', value: 0x02 },
  { label: 'Thief Sword', value: 0x03 },
  { label: 'Prayer Sword', value: 0x04 },
  { label: 'Barrier Sword', value: 0x05 },
  { label: 'Berserk Sword', value: 0x06 },
  { label: 'Hero Sword', value: 0x07 },
  { label: 'Silence Sword', value: 0x08 },
  { label: 'Sleep Sword', value: 0x09 },
  { label: 'Thin Sword', value: 0x0A },
  { label: 'Defense Sword', value: 0x0B },
  { label: 'Fire Sword', value: 0x0C },
  { label: 'Earth Sword', value: 0x0D },
  { label: 'Thunder Sword', value: 0x0E },
  { label: 'Wind Sword', value: 0x0F },
  { label: 'Balmunk', value: 0x10 },
  { label: 'Light Sword', value: 0x11 },
  { label: '(unused) (not recommended, has a question mark on some frames)', value: 0x12 },
  { label: 'Mistoltin', value: 0x13 },
  { label: 'Tyrfing', value: 0x14 },
  { label: 'Armor Killer', value: 0x15 },
  { label: 'Wing Clipper', value: 0x16 },
  { label: 'Broken Sword', value: 0x17 },
  { label: 'Iron Lance', value: 0x18 },
  { label: 'Steel Lance', value: 0x19 },
  { label: 'Silver Lance', value: 0x1A },
  { label: 'Javelin', value: 0x1B },
  { label: 'Knight Killer', value: 0x1C },
  { label: 'Hero Lance', value: 0x1D },
  { label: 'Gungnir', value: 0x1E },
  { label: 'Gae Bolg', value: 0x1F },
  { label: 'Broken Lance', value: 0x20 },
  { label: 'Iron Axe', value: 0x21 },
  { label: 'Steel Axe', value: 0x22 },
  { label: 'Silver Axe', value: 0x23 },
  { label: 'Hand Axe', value: 0x24 },
  { label: 'Hero Axe', value: 0x25 },
  { label: 'Swanchika', value: 0x26 },
  { label: 'Broken Axe', value: 0x27 },
  { label: 'Iron Bow', value: 0x28 },
  { label: 'Steel Bow', value: 0x29 },
  { label: 'Silver Bow', value: 0x2A },
  { label: 'Hero Bow', value: 0x2B },
  { label: 'Killer Bow', value: 0x2C },
  { label: 'Ichival', value: 0x2D },
  { label: 'Broken Bow', value: 0x2E },
  { label: 'Live Staff', value: 0x2F },
  { label: 'Libro Staff', value: 0x30 },
  { label: 'Reserve Staff', value: 0x31 },
  { label: 'Warp Staff', value: 0x32 },
  { label: 'Return Staff', value: 0x33 },
  { label: 'Rescue Staff', value: 0x34 },
  { label: 'Charm Staff (unused)', value: 0x35 },
  { label: 'Rest Staff', value: 0x36 },
  { label: 'Sleep Staff', value: 0x37 },
  { label: 'Berserk Staff', value: 0x38 },
  { label: 'Silence Staff', value: 0x39 },
  { label: 'Thief Staff (unused)', value: 0x3A },
  { label: 'Valkyrie Staff', value: 0x3B },
  { label: 'Broken Staff (unused)', value: 0x3C },
  { label: 'Long Arch', value: 0x3D },
  { label: 'Iron Arch', value: 0x3E },
  { label: 'Killer Arch', value: 0x3F },
  { label: 'Gold Arch', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: '0x80', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: '0xFF', value: 0xFF },
];
