export const AnimationPointerTableEditor = [
  { label: 'Eliwood', value: 0 },
  { label: 'Eliwood Disarmed', value: 1 },
  { label: 'Lord Knight Eliwood w/ Sword', value: 2 },
  { label: 'Lord Knight Eliwood w/ Durandal', value: 3 },
  { label: 'Lord Knight Eliwood w/ Spear', value: 4 },
  { label: 'Lord Knight Eliwood Disarmed', value: 5 },
  { label: 'Hector', value: 6 },
  { label: 'Hector w/ Hand Axe', value: 7 },
  { label: 'Hector Disarmed', value: 8 },
  { label: 'Great Lord Hector w/ Axe', value: 9 },
  { label: 'Great Lord Hector w/ Hand Axe', value: 10 },
  { label: 'Great Lord Hector w/ Armads', value: 11 },
  { label: 'Great Lord Hector w/ Sword', value: 12 },
  { label: 'Great Lord Hector Disarmed', value: 13 },
  { label: 'Lyn', value: 14 },
  { label: 'Lyn Disarmed', value: 15 },
  { label: 'Blade Lord Lyn w/ Sword', value: 16 },
  { label: 'Blade Lord Lyn w/ Sol Katti', value: 17 },
  { label: 'Blade Lord Lyn w/ Bow', value: 18 },
  { label: 'Blade Lord Lyn Disarmed', value: 19 },
  { label: 'Mountain Thief', value: 20 },
  { label: 'Mountain Thief w/ Hand Axe', value: 21 },
  { label: 'Mountain Thief Disarmed', value: 22 },
  { label: 'Pirate', value: 23 },
  { label: 'Pirate w/ Hand Axe', value: 24 },
  { label: 'Pirate Disarmed', value: 25 },
  { label: 'Hawkeye', value: 26 },
  { label: 'Hawkeye w/ Hand Axe', value: 27 },
  { label: 'Hawkeye Disarmed', value: 28 },
  { label: 'Fighter', value: 29 },
  { label: 'Fighter w/ Hand Axe', value: 30 },
  { label: 'Fighter Disarmed', value: 31 },
  { label: 'Warrior w/ Axe', value: 32 },
  { label: 'Warrior w/ Hand Axe', value: 33 },
  { label: 'Warrior w/ Bow', value: 34 },
  { label: 'Warrior Disarmed', value: 35 },
  { label: 'Archer', value: 36 },
  { label: 'Archer Disarmed', value: 37 },
  { label: 'Archer (F)', value: 38 },
  { label: 'Archer (F) Disarmed', value: 39 },
  { label: 'Sniper', value: 40 },
  { label: 'Sniper Disarmed', value: 41 },
  { label: 'Sniper (F)', value: 42 },
  { label: 'Sniper (F) Disarmed', value: 43 },
  { label: 'Mercenary', value: 44 },
  { label: 'Mercenary Disarmed', value: 45 },
  { label: 'Hero w/ Sword', value: 46 },
  { label: 'Hero w/ Axe', value: 47 },
  { label: 'Hero w/ Hand Axe', value: 48 },
  { label: 'Hero Disarmed', value: 49 },
  { label: 'Swordfighter', value: 50 },
  { label: 'Swordfighter Disarmed', value: 51 },
  { label: 'Swordmaster', value: 52 },
  { label: 'Swordmaster Disarmed', value: 53 },
  { label: 'Lloyd', value: 54 },
  { label: 'Lloyd Disarmed', value: 55 },
  { label: 'Swordmaster (F)', value: 56 },
  { label: 'Swordmaster (F) Disarmed', value: 57 },
  { label: 'Socialknight w/ Spear', value: 58 },
  { label: 'Socialknight w/ Sword', value: 59 },
  { label: 'Socialknight Disarmed', value: 60 },
  { label: 'Socialknight w/ Spear (again?)', value: 61 },
  { label: 'Assassin Legault', value: 62 },
  { label: 'Assassin Legault Disarmed', value: 63 },
  { label: 'Paladin w/ Axe', value: 64 },
  { label: 'Paladin w/ Hand Axe', value: 65 },
  { label: 'Paladin w/ Sword', value: 66 },
  { label: 'Paladin w/ Spear', value: 67 },
  { label: 'Paladin Disarmed', value: 68 },
  { label: 'Paladin w/ Axe', value: 69 },
  { label: 'Paladin w/ Hand Axe', value: 70 },
  { label: 'Paladin w/ Sword', value: 71 },
  { label: 'Paladin w/ Spear', value: 72 },
  { label: 'Paladin Disarmed', value: 73 },
  { label: 'Isadora w/ Axe', value: 74 },
  { label: 'Isadora w/ Hand Axe', value: 75 },
  { label: 'Isadora w/ Sword', value: 76 },
  { label: 'Isadora w/ Spear', value: 77 },
  { label: 'Isadora Disarmed', value: 78 },
  { label: 'Soldier', value: 79 },
  { label: 'Soldier Disarmed', value: 80 },
  { label: 'Armour Knight', value: 81 },
  { label: 'Armour Knight Disarmed', value: 82 },
  { label: 'General w/ Spear', value: 83 },
  { label: 'General w/ Axe', value: 84 },
  { label: 'General w/ Hand Axe', value: 85 },
  { label: 'General Disarmed', value: 86 },
  { label: 'Mage', value: 87 },
  { label: 'Nino', value: 88 },
  { label: 'Sage', value: 89 },
  { label: 'Sage w/ Staff', value: 90 },
  { label: 'Sage (F)', value: 91 },
  { label: 'Sage (F) w/ Staff', value: 92 },
  { label: 'Sage Nino', value: 93 },
  { label: 'Sage Nino w/ Staff', value: 94 },
  { label: 'Priest', value: 95 },
  { label: 'Priest Disarmed', value: 96 },
  { label: 'Serra', value: 97 },
  { label: 'Serra Disarmed', value: 98 },
  { label: 'Monk', value: 99 },
  { label: 'Bishop', value: 100 },
  { label: 'Bishop w/ Staff', value: 101 },
  { label: 'Bishop Serra', value: 102 },
  { label: 'Bishop Serra w/ Staff', value: 103 },
  { label: 'Shaman', value: 104 },
  { label: 'Druid', value: 105 },
  { label: 'Druid w/ Staff', value: 106 },
  { label: 'Dark Druid', value: 107 },
  { label: 'Dark Druid w/ Staff (messed up)', value: 108 },
  { label: 'Troubadour', value: 109 },
  { label: 'Troubadour Disarmed', value: 110 },
  { label: 'Valkyrie', value: 111 },
  { label: 'Valkyrie w/ Staff', value: 112 },
  { label: 'Athos', value: 113 },
  { label: 'Athos w/ Staff', value: 114 },
  { label: 'Nomad', value: 115 },
  { label: 'Nomad Disarmed', value: 116 },
  { label: 'Nomad Trooper w/ Sword', value: 117 },
  { label: 'Nomad Trooper w/ Bow', value: 118 },
  { label: 'Nomad Trooper Disarmed', value: 119 },
  { label: 'Thief', value: 120 },
  { label: 'Thief Disarmed', value: 121 },
  { label: 'Legault', value: 122 },
  { label: 'Legault Disarmed', value: 123 },
  { label: 'Leila', value: 124 },
  { label: 'Leila Disarmed', value: 125 },
  { label: 'Assassin', value: 126 },
  { label: 'Assassin Disarmed', value: 127 },
  { label: 'Pegasus Knight', value: 128 },
  { label: 'Pegasus Knight Disarmed', value: 129 },
  { label: 'Falcon Knight w/ Sword', value: 130 },
  { label: 'Falcon Knight w/ Spear', value: 131 },
  { label: 'Falcon Knight Disarmed', value: 132 },
  { label: 'Dragon Knight', value: 133 },
  { label: 'Dragon Knight Disarmed', value: 134 },
  { label: 'Dragon Master w/ Spear', value: 135 },
  { label: 'Dragon Master w/ Sword', value: 136 },
  { label: 'Dragon Master Disarmed', value: 137 },
  { label: 'Fire Dragon', value: 138 },
  { label: 'Archer on Ballista (unused, but still here from FE6)', value: 139 },
  { label: 'Dancer', value: 140 },
  { label: 'Bard', value: 141 },
  { label: 'Lucius', value: 142 },
  { label: 'Hero w/ Coat w/ Sword', value: 143 },
  { label: 'Hero w/ Coat w/ Axe', value: 144 },
  { label: 'Hero w/ Coat w/ Hand Axe', value: 145 },
  { label: 'Hero w/ Coat Disarmed', value: 146 },
  { label: 'Bishop Lucius', value: 147 },
  { label: 'Bishop Lucius w/ Staff', value: 148 },
  { label: 'Bishop Lucius Disarmed', value: 149 },
  { label: 'Bishop Disarmed', value: 150 },
  { label: 'Serra Disarmed', value: 151 },
  { label: 'Guy', value: 152 },
  { label: 'Guy Disarmed', value: 153 },
  { label: 'Swordmaster Guy', value: 154 },
  { label: 'Guy Disarmed', value: 155 },
  { label: 'Berserker', value: 156 },
  { label: 'Berserker w/ Hand Axe', value: 157 },
  { label: 'Berserker Disarmed', value: 158 },
  { label: 'Magic Seal', value: 159 },
  { label: 'Tent', value: 160 },
  { label: 'Transporter', value: 161 },
  { label: 'Entry 162', value: 162 },
  { label: 'Entry 163', value: 163 },
  { label: 'Entry 164', value: 164 },
  { label: 'Entry 165', value: 165 },
  { label: 'Entry 166', value: 166 },
  { label: 'Entry 167', value: 167 },
  { label: 'Entry 168', value: 168 },
  { label: 'Entry 169', value: 169 },
  { label: 'Entry 170', value: 170 },
  { label: 'Entry 171', value: 171 },
  { label: 'Entry 172', value: 172 },
  { label: 'Entry 173', value: 173 },
  { label: 'Entry 174', value: 174 },
  { label: 'Entry 175', value: 175 },
  { label: 'Entry 176', value: 176 },
  { label: 'Entry 177', value: 177 },
  { label: 'Entry 178', value: 178 },
  { label: 'Entry 179', value: 179 },
  { label: 'Entry 180', value: 180 },
  { label: 'Entry 181', value: 181 },
  { label: 'Entry 182', value: 182 },
  { label: 'Entry 183', value: 183 },
  { label: 'Entry 184', value: 184 },
  { label: 'Entry 185', value: 185 },
  { label: 'Entry 186', value: 186 },
  { label: 'Entry 187', value: 187 },
  { label: 'Entry 188', value: 188 },
  { label: 'Entry 189', value: 189 },
  { label: 'Entry 190', value: 190 },
  { label: 'Entry 191', value: 191 },
  { label: 'Entry 192', value: 192 },
  { label: 'Entry 193', value: 193 },
  { label: 'Entry 194', value: 194 },
  { label: 'Entry 195', value: 195 },
  { label: 'Entry 196', value: 196 },
  { label: 'Entry 197', value: 197 },
  { label: 'Entry 198', value: 198 },
  { label: 'Entry 199', value: 199 },
  { label: 'Entry 200', value: 200 },
  { label: 'Entry 201', value: 201 },
  { label: 'Entry 202', value: 202 },
  { label: 'Entry 203', value: 203 },
  { label: 'Entry 204', value: 204 },
  { label: 'Entry 205', value: 205 },
  { label: 'Entry 206', value: 206 },
  { label: 'Entry 207', value: 207 },
  { label: 'Entry 208', value: 208 },
  { label: 'Entry 209', value: 209 },
  { label: 'Entry 210', value: 210 },
  { label: 'Entry 211', value: 211 },
  { label: 'Entry 212', value: 212 },
  { label: 'Entry 213', value: 213 },
  { label: 'Entry 214', value: 214 },
  { label: 'Entry 215', value: 215 },
  { label: 'Entry 216', value: 216 },
  { label: 'Entry 217', value: 217 },
  { label: 'Entry 218', value: 218 },
  { label: 'Entry 219', value: 219 },
  { label: 'Entry 220', value: 220 },
  { label: 'Entry 221', value: 221 },
  { label: 'Entry 222', value: 222 },
  { label: 'Entry 223', value: 223 },
  { label: 'Entry 224', value: 224 },
  { label: 'Entry 225', value: 225 },
  { label: 'Entry 226', value: 226 },
  { label: 'Entry 227', value: 227 },
  { label: 'Entry 228', value: 228 },
  { label: 'Entry 229', value: 229 },
  { label: 'Entry 230', value: 230 },
  { label: 'Entry 231', value: 231 },
  { label: 'Entry 232', value: 232 },
  { label: 'Entry 233', value: 233 },
  { label: 'Entry 234', value: 234 },
  { label: 'Entry 235', value: 235 },
  { label: 'Entry 236', value: 236 },
  { label: 'Entry 237', value: 237 },
  { label: 'Entry 238', value: 238 },
  { label: 'Entry 239', value: 239 },
  { label: 'Entry 240', value: 240 },
  { label: 'Entry 241', value: 241 },
  { label: 'Entry 242', value: 242 },
  { label: 'Entry 243', value: 243 },
  { label: 'Entry 244', value: 244 },
  { label: 'Entry 245', value: 245 },
  { label: 'Entry 246', value: 246 },
  { label: 'Entry 247', value: 247 },
  { label: 'Entry 248', value: 248 },
  { label: 'Entry 249', value: 249 },
  { label: 'Entry 250', value: 250 },
  { label: 'Entry 251', value: 251 },
  { label: 'Entry 252', value: 252 },
  { label: 'Entry 253', value: 253 },
  { label: 'Entry 254', value: 254 },
  { label: 'Entry 255', value: 255 },
];

export default AnimationPointerTableEditor;
