export const TerrainData = [
  { label: '___ / Wall', value: 0 },
  { label: 'Plain / Bridge / Bone', value: 1 },
  { label: 'Forest', value: 2 },
  { label: 'Desert', value: 3 },
  { label: 'Ledge', value: 4 },
  { label: 'Village', value: 5 },
  { label: 'Closed Village', value: 6 },
  { label: 'Ruined Village', value: 7 },
  { label: 'House / Armory / Vendor / Arena', value: 8 },
  { label: 'Fence', value: 9 },
  { label: 'Fort', value: 10 },
  { label: 'Castle Gate', value: 11 },
  { label: 'Castle', value: 12 },
  { label: 'Mountain', value: 13 },
  { label: 'Cave', value: 14 },
  { label: 'Peak', value: 15 },
  { label: 'River', value: 16 },
  { label: 'Sea', value: 17 },
  { label: 'Lava', value: 18 },
  { label: 'Floor / Stairs', value: 19 },
  { label: 'Pillar', value: 20 },
  { label: 'Throne', value: 21 },
  { label: 'Chest', value: 22 },
  { label: 'Door', value: 23 },
  { label: 'Drawbridge', value: 24 },
  { label: 'Altar', value: 25 },
  { label: '???', value: 26 },
  { label: '???', value: 27 },
];

export default TerrainData;
