export const FE7ArenaclasseditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
  { label: 'Entry 68', value: 68 },
  { label: 'Entry 69', value: 69 },
  { label: 'Entry 70', value: 70 },
  { label: 'Entry 71', value: 71 },
  { label: 'Entry 72', value: 72 },
  { label: 'Entry 73', value: 73 },
  { label: 'Entry 74', value: 74 },
  { label: 'Entry 75', value: 75 },
  { label: 'Entry 76', value: 76 },
  { label: 'Entry 77', value: 77 },
  { label: 'Entry 78', value: 78 },
  { label: 'Entry 79', value: 79 },
  { label: 'Entry 80', value: 80 },
  { label: 'Entry 81', value: 81 },
  { label: 'Entry 82', value: 82 },
  { label: 'Entry 83', value: 83 },
  { label: 'Entry 84', value: 84 },
  { label: 'Entry 85', value: 85 },
  { label: 'Entry 86', value: 86 },
  { label: 'Entry 87', value: 87 },
  { label: 'Entry 88', value: 88 },
  { label: 'Entry 89', value: 89 },
  { label: 'Entry 90', value: 90 },
  { label: 'Entry 91', value: 91 },
  { label: 'Entry 92', value: 92 },
  { label: 'Entry 93', value: 93 },
  { label: 'Entry 94', value: 94 },
  { label: 'Entry 95', value: 95 },
  { label: 'Entry 96', value: 96 },
  { label: 'Entry 97', value: 97 },
  { label: 'Entry 98', value: 98 },
  { label: 'Entry 99', value: 99 },
  { label: 'Entry 100', value: 100 },
  { label: 'Entry 101', value: 101 },
  { label: 'Entry 102', value: 102 },
  { label: 'Entry 103', value: 103 },
  { label: 'Entry 104', value: 104 },
  { label: 'Entry 105', value: 105 },
  { label: 'Entry 106', value: 106 },
  { label: 'Entry 107', value: 107 },
  { label: 'Entry 108', value: 108 },
  { label: 'Entry 109', value: 109 },
  { label: 'Entry 110', value: 110 },
  { label: 'Entry 111', value: 111 },
  { label: 'Entry 112', value: 112 },
  { label: 'Entry 113', value: 113 },
  { label: 'Entry 114', value: 114 },
  { label: 'Entry 115', value: 115 },
  { label: 'Entry 116', value: 116 },
  { label: 'Entry 117', value: 117 },
  { label: 'Entry 118', value: 118 },
  { label: 'Entry 119', value: 119 },
  { label: 'Entry 120', value: 120 },
  { label: 'Entry 121', value: 121 },
  { label: 'Entry 122', value: 122 },
  { label: 'Entry 123', value: 123 },
  { label: 'Entry 124', value: 124 },
];

export const ClassList = [
  { label: 'None', value: 0x00 },
  { label: 'Eliwood Lord', value: 0x01 },
  { label: 'Lyn Lord', value: 0x02 },
  { label: 'Hector Lord', value: 0x03 },
  { label: 'Eliwood Lord Knight (only by class name)', value: 0x04 },
  { label: 'Lyn Blade Lord (only by class name)', value: 0x05 },
  { label: 'Hector Great Lord (only by class name)', value: 0x06 },
  { label: 'Eliwood Lord Knight', value: 0x07 },
  { label: 'Lyn Blade Lord', value: 0x08 },
  { label: 'Hector Great Lord', value: 0x09 },
  { label: 'Mercenary', value: 0x0A },
  { label: 'Mercenary', value: 0x0B },
  { label: 'Hero', value: 0x0C },
  { label: 'Hero', value: 0x0D },
  { label: 'Myrmidon', value: 0x0E },
  { label: 'Myrmidon', value: 0x0F },
  { label: 'Swordmaster', value: 0x10 },
  { label: 'Swordmaster', value: 0x11 },
  { label: 'Fighter', value: 0x12 },
  { label: 'Warrior', value: 0x13 },
  { label: 'Knight', value: 0x14 },
  { label: 'Knight', value: 0x15 },
  { label: 'General', value: 0x16 },
  { label: 'General', value: 0x17 },
  { label: 'Archer', value: 0x18 },
  { label: 'Archer', value: 0x19 },
  { label: 'Sniper', value: 0x1A },
  { label: 'Sniper', value: 0x1B },
  { label: 'Monk', value: 0x1C },
  { label: 'Cleric', value: 0x1D },
  { label: 'Bishop', value: 0x1E },
  { label: 'Bishop', value: 0x1F },
  { label: 'Mage', value: 0x20 },
  { label: 'Mage', value: 0x21 },
  { label: 'Sage', value: 0x22 },
  { label: 'Sage', value: 0x23 },
  { label: 'Shaman', value: 0x24 },
  { label: 'Shaman', value: 0x25 },
  { label: 'Druid', value: 0x26 },
  { label: 'Druid', value: 0x27 },
  { label: 'Cavalier', value: 0x28 },
  { label: 'Cavalier', value: 0x29 },
  { label: 'Paladin', value: 0x2A },
  { label: 'Paladin', value: 0x2B },
  { label: 'Troubadour', value: 0x2C },
  { label: 'Valkyrie', value: 0x2D },
  { label: 'Nomad', value: 0x2E },
  { label: 'Nomad', value: 0x2F },
  { label: 'Nomad Trooper', value: 0x30 },
  { label: 'Nomad Trooper', value: 0x31 },
  { label: 'Pegasus Knight', value: 0x32 },
  { label: 'Falcon Knight', value: 0x33 },
  { label: 'Wyvern Knight', value: 0x34 },
  { label: 'Wyvern Knight', value: 0x35 },
  { label: 'Wyvern Lord', value: 0x36 },
  { label: 'Wyvern Lord', value: 0x37 },
  { label: 'Soldier', value: 0x38 },
  { label: 'Bandit', value: 0x39 },
  { label: 'Pirate', value: 0x3A },
  { label: 'Berserker', value: 0x3B },
  { label: 'Thief', value: 0x3C },
  { label: 'Thief', value: 0x3D },
  { label: 'Assassin', value: 0x3E },
  { label: 'Civilian', value: 0x3F },
  { label: 'Dancer', value: 0x40 },
  { label: 'Bard', value: 0x41 },
  { label: 'Archsage', value: 0x42 },
  { label: 'Magic Seal', value: 0x43 },
  { label: 'Transporter', value: 0x44 },
  { label: 'Transporter', value: 0x45 },
  { label: 'Fire Dragon', value: 0x46 },
  { label: 'Civilian', value: 0x47 },
  { label: 'Civilian (F)', value: 0x48 },
  { label: 'Child', value: 0x49 },
  { label: 'Brammimond', value: 0x4A },
  { label: 'Peer', value: 0x4B },
  { label: 'Peer (F)', value: 0x4C },
  { label: 'Prince', value: 0x4D },
  { label: 'Queen', value: 0x4E },
  { label: 'Hung Leila', value: 0x4F },
  { label: 'Corsair', value: 0x50 },
  { label: 'Prince (Tactician)', value: 0x51 },
  { label: 'Fallen Prince', value: 0x52 },
  { label: 'Prince facing upward', value: 0x53 },
  { label: 'Fallen Ninian', value: 0x54 },
  { label: 'Fallen Ice Dragon', value: 0x55 },
  { label: 'Fallen Warrior', value: 0x56 },
  { label: 'Child', value: 0x57 },
  { label: 'Child (F)', value: 0x58 },
  { label: 'Transporter w/ Horse', value: 0x59 },
  { label: 'Uber Sage', value: 0x5A },
  { label: 'Archer in Ballista', value: 0x5B },
  { label: 'Archer in Iron Ballista', value: 0x5C },
  { label: 'Archer in Killer Ballista', value: 0x5D },
  { label: 'Empty Ballista', value: 0x5E },
  { label: 'Empty Iron Ballista', value: 0x5F },
  { label: 'Empty Killer Ballista', value: 0x60 },
  { label: 'Empty (Make a custom class!)', value: 0x61 },
  { label: 'Empty (Make a custom class!)', value: 0x62 },
  { label: 'Empty (Make a custom class!)', value: 0x63 },
];
