export const FE5ArmyDataCh4xManster3Entries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
];

export const FE5CharacterList = [
  { label: 'Nothing/Separator', value: 0x0000 },
  { label: 'Leaf', value: 0x0001 },
  { label: 'Finn', value: 0x0002 },
  { label: 'Othin', value: 0x0003 },
  { label: 'Halvan', value: 0x0004 },
  { label: 'Eyvel', value: 0x0005 },
  { label: 'Dagudar', value: 0x0006 },
  { label: 'Ralf', value: 0x0007 },
  { label: 'Marty', value: 0x0008 },
  { label: 'Ronan', value: 0x0009 },
  { label: 'Miranda', value: 0x000A },
  { label: 'Saphy', value: 0x000B },
  { label: 'Lara', value: 0x000C },
  { label: 'Brighton', value: 0x000D },
  { label: 'Felgus', value: 0x000E },
  { label: 'Eda', value: 0x000F },
  { label: 'Asvel', value: 0x0010 },
  { label: 'Machyua', value: 0x0011 },
  { label: 'Hicks', value: 0x0012 },
  { label: 'Nanna', value: 0x0013 },
  { label: 'Selfina', value: 0x0014 },
  { label: 'Dalshein', value: 0x0015 },
  { label: 'Carrion', value: 0x0016 },
  { label: 'Shiva', value: 0x0017 },
  { label: 'Pahn', value: 0x0018 },
  { label: 'Glade', value: 0x0019 },
  { label: 'Kein', value: 0x001A },
  { label: 'Alba', value: 0x001B },
  { label: 'Roberto', value: 0x001C },
  { label: 'Fred', value: 0x001D },
  { label: 'Oruen', value: 0x001E },
  { label: 'Sety (Chapter 23)', value: 0x001F },
  { label: 'Rifis', value: 0x0020 },
  { label: 'Karin', value: 0x0021 },
  { label: 'Dean', value: 0x0022 },
  { label: 'Shanam', value: 0x0023 },
  { label: 'Trewd', value: 0x0024 },
  { label: 'Tanya', value: 0x0025 },
  { label: 'Linonan', value: 0x0026 },
  { label: 'Misha', value: 0x0027 },
  { label: 'Seiram', value: 0x0028 },
  { label: 'Sleuf', value: 0x0029 },
  { label: 'Mareeta', value: 0x002A },
  { label: 'Tina', value: 0x002B },
  { label: 'Gunna (Bishop from dialogue)', value: 0x002C },
  { label: 'Amalda', value: 0x002D },
  { label: 'Conomore', value: 0x002E },
  { label: 'Homeros', value: 0x002F },
  { label: 'Delmud', value: 0x0030 },
  { label: 'Sara', value: 0x0031 },
  { label: 'Cyas', value: 0x0032 },
  { label: 'Leidrick', value: 0x0033 },
  { label: 'Yurius (Dark Mage with Cyas portrait and Life...)', value: 0x0034 },
  { label: 'Beldo', value: 0x0035 },
  { label: 'Weissman (Boss)', value: 0x0036 },
  { label: 'Manster - Archer', value: 0x0037 },
  { label: 'Bugs (Boss)', value: 0x0038 },
  { label: 'Jabal', value: 0x0039 },
  { label: 'Rifis\' Gang - Pirate', value: 0x003A },
  { label: 'Rifis\' Gang - Hunter', value: 0x003B },
  { label: 'Rifis\' Gang - Warrior', value: 0x003C },
  { label: 'Robos (Boss)', value: 0x003D },
  { label: 'Manster - Bow Armor', value: 0x003E },
  { label: 'Manster - Thunder Mage', value: 0x003F },
  { label: 'Manster - Bishop', value: 0x0040 },
  { label: 'Romeo (NPC)', value: 0x0041 },
  { label: 'Luchea (NPC)', value: 0x0042 },
  { label: 'Yubel (NPC)', value: 0x0043 },
  { label: 'Corple (NPC,FE4 cameo)', value: 0x0044 },
  { label: 'Sety (Chapter 4G appearance)', value: 0x0045 },
  { label: 'Ishtar', value: 0x0046 },
  { label: 'Reinhart (Weak version,probably dialogue)', value: 0x0047 },
  { label: 'Rifis\' Gang - Sword Fighter', value: 0x0048 },
  { label: 'Emily (NPC)', value: 0x0049 },
  { label: 'Murphy (NPC)', value: 0x004A },
  { label: 'Bella (NPC)', value: 0x004B },
  { label: 'Krith (NPC)', value: 0x004C },
  { label: 'Boey (NPC)', value: 0x004D },
  { label: 'Leena (NPC)', value: 0x004E },
  { label: 'Mercenary - Sword Fighter', value: 0x004F },
  { label: 'Galzus', value: 0x0050 },
  { label: 'Manster - Social Knight', value: 0x0051 },
  { label: 'Manster - Paladin', value: 0x0052 },
  { label: 'Manster - Arch Knight', value: 0x0053 },
  { label: 'Manster - Troubadour', value: 0x0054 },
  { label: 'Izenau (Boss)', value: 0x0055 },
  { label: 'Hannibal (Dialogue,FE4 cameo)', value: 0x0056 },
  { label: 'Manster - Axe Knight', value: 0x0057 },
  { label: 'Bandit - Mountain Thief', value: 0x0058 },
  { label: 'Bandit - Hunter', value: 0x0059 },
  { label: 'Bandit - Warrior', value: 0x005A },
  { label: 'Lumei (Boss)', value: 0x005B },
  { label: 'Gomez (Boss)', value: 0x005C },
  { label: 'Mallock (Boss)', value: 0x005D },
  { label: 'Thracia - Dragon Knight', value: 0x005E },
  { label: 'Thracia - Sword Fighter', value: 0x005F },
  { label: 'Thracia - Axe Fighter', value: 0x0060 },
  { label: 'Althenna (Enemy only,FE4 cameo)', value: 0x0061 },
  { label: 'Torabant (Dialogue,FE4 cameo)', value: 0x0062 },
  { label: 'Ralgo (Boss)', value: 0x0063 },
  { label: 'Manster - Long Arch', value: 0x0064 },
  { label: 'Manster - Axe Armor', value: 0x0065 },
  { label: 'Kempf (Boss)', value: 0x0066 },
  { label: 'Oltov (Boss)', value: 0x0067 },
  { label: 'Rosa (NPC)', value: 0x0068 },
  { label: 'Serra (NPC)', value: 0x0069 },
  { label: 'Peter (NPC)', value: 0x006A },
  { label: 'Kolho (Mini-boss)', value: 0x006B },
  { label: 'Rist (Boss)', value: 0x006C },
  { label: 'Paluce (Boss)', value: 0x006D },
  { label: 'Baldack (Boss)', value: 0x006E },
  { label: 'Thracia - Lance Armor', value: 0x006F },
  { label: 'Lenster - Lance Knight', value: 0x0070 },
  { label: 'Lenster - Arch Knight', value: 0x0071 },
  { label: 'Arion (Dialogue,FE4 cameo)', value: 0x0072 },
  { label: 'Makroi (Boss)', value: 0x0073 },
  { label: 'Kodda (Boss)', value: 0x0074 },
  { label: 'Roputo - Dark Mage', value: 0x0075 },
  { label: 'Civilian', value: 0x0076 },
  { label: 'Thief', value: 0x0077 },
  { label: 'Manster - Sniper', value: 0x0078 },
  { label: 'Mercenary - Social Knight', value: 0x0079 },
  { label: 'Priest', value: 0x007A },
  { label: 'Mercenary - Sword Fighter', value: 0x007B },
  { label: '21 - Iron Arch', value: 0x007C },
  { label: 'Shupel (Boss)', value: 0x007D },
  { label: 'Bluke (Boss)', value: 0x007E },
  { label: 'Silesia - Pegasus Rider', value: 0x007F },
  { label: 'Nikolaf (Boss)', value: 0x0080 },
  { label: 'Muua (Boss)', value: 0x0081 },
  { label: 'Myura (Boss)', value: 0x0082 },
  { label: 'Reincock (Boss)', value: 0x0083 },
  { label: 'Palman (Boss)', value: 0x0084 },
  { label: 'Kanto (Boss)', value: 0x0085 },
  { label: 'Gustaf (Boss)', value: 0x0086 },
  { label: 'Dancer', value: 0x0087 },
  { label: 'Sister', value: 0x0088 },
  { label: 'Manheim (Boss)', value: 0x0089 },
  { label: 'Phlaus (Boss)', value: 0x008A },
  { label: 'Semitol (Boss)', value: 0x008B },
  { label: 'Zaom (Boss)', value: 0x008C },
  { label: 'Koen (Boss)', value: 0x008D },
  { label: 'Alphan (Boss)', value: 0x008E },
  { label: 'Opisu (Boss?)', value: 0x008F },
  { label: 'Ferden (Boss)', value: 0x0090 },
  { label: 'Koruta (Boss)', value: 0x0091 },
  { label: 'Reinhardt', value: 0x0092 },
  { label: 'Nancy (NPC)', value: 0x0093 },
  { label: 'Tahra Civilian', value: 0x0094 },
  { label: 'Tahra Civilian', value: 0x0095 },
  { label: 'Tahra Civilian', value: 0x0096 },
  { label: 'Tahra Civilian', value: 0x0097 },
  { label: 'Tahra Civilian', value: 0x0098 },
  { label: 'Tahra Civilian', value: 0x0099 },
  { label: 'Mercenary - Sword Fighter', value: 0x009A },
  { label: 'Freege - Long Arch', value: 0x009B },
  { label: 'Freege - Social Knight', value: 0x009C },
  { label: 'Freege - Troubadour', value: 0x009D },
  { label: 'Freege - Bow Armour', value: 0x009E },
  { label: 'Freege - Lance Armour', value: 0x009F },
  { label: 'Freege - Axe Armour', value: 0x00A0 },
  { label: 'Freege - Archer', value: 0x00A1 },
  { label: 'Freege - Mage', value: 0x00A2 },
  { label: 'Rilke (with Kempf portrait...)', value: 0x00A3 },
  { label: 'Manster - Lance Armour', value: 0x00A4 },
  { label: 'Civilian', value: 0x00A5 },
  { label: 'Civilian', value: 0x00A6 },
  { label: 'Civilian', value: 0x00A7 },
  { label: 'Civilian', value: 0x00A8 },
  { label: 'Civilian', value: 0x00A9 },
  { label: 'Civilian', value: 0x00AA },
  { label: 'Manster - Mage', value: 0x00AB },
  { label: 'Manster - Priest', value: 0x00AC },
  { label: 'Yurius (with Yuria portrait...)', value: 0x00AD },
  { label: 'Manfroy (with Machyua portrait...)', value: 0x00AE },
  { label: 'Manster - Mage', value: 0x00AF },
  { label: 'Manster - Sword Fighter', value: 0x00B0 },
  { label: 'Envoy - Mercenary', value: 0x00B1 },
  { label: 'Envoy - Warrior', value: 0x00B2 },
  { label: 'Envoy - General', value: 0x00B3 },
  { label: 'Envoy - Swordmaster', value: 0x00B4 },
  { label: 'Envoy - Berserker', value: 0x00B5 },
  { label: 'Manster - Priest', value: 0x00B6 },
  { label: 'Bantol (Boss)', value: 0x00B7 },
  { label: 'Lopto - Dark Bishop', value: 0x00B8 },
  { label: 'Torman (Boss)', value: 0x00B9 },
  { label: 'Manster - Soldier', value: 0x00BA },
  { label: 'Bandit - Berserker', value: 0x00BB },
  { label: 'Mercenary - Sword Fighter', value: 0x00BC },
  { label: 'Magi Squad - Sword Fighter', value: 0x00BD },
  { label: 'Magi Squad - Axe Fighter', value: 0x00BE },
  { label: 'Magi Squad - Bow Fighter', value: 0x00BF },
  { label: 'Magi Squad - Sword Fighter', value: 0x00C0 },
  { label: 'Dragon Rider', value: 0x00C1 },
  { label: 'Bishop', value: 0x00C2 },
  { label: 'Tobolzark (Boss)', value: 0x00C3 },
  { label: 'Manster - Bishop', value: 0x00C4 },
  { label: 'Freege - Long Arch', value: 0x00C5 },
  { label: 'Bandit - Mountain Thief 2', value: 0x00C6 },
  { label: 'Thief', value: 0x00C7 },
  { label: 'Bow Fighter', value: 0x00C8 },
  { label: 'Freege - Bishop', value: 0x00C9 },
  { label: 'Freege - Lance Armour', value: 0x00CA },
  { label: 'Freege - Bow Armour', value: 0x00CB },
  { label: 'Freege - Mage', value: 0x00CC },
  { label: 'Iron Arch', value: 0x00CD },
  { label: 'Freege - Axe Armour', value: 0x00CE },
  { label: 'Aightman (Boss)', value: 0x00CF },
  { label: 'Zail (Boss)', value: 0x00D0 },
  { label: 'Sword Armour', value: 0x00D1 },
  { label: 'Soldier', value: 0x00D2 },
  { label: 'Freege - Long Arch', value: 0x00D3 },
  { label: 'Eyrios', value: 0x00D4 },
  { label: 'Silesia - Pegasus Rider', value: 0x00D5 },
  { label: 'Freege - Mage Knight', value: 0x00D6 },
  { label: 'Paladin', value: 0x00D7 },
  { label: 'Freege - Great Knight', value: 0x00D8 },
  { label: 'Bow Knight', value: 0x00D9 },
  { label: 'Sword Armour', value: 0x00DA },
  { label: 'Freege - Soldier', value: 0x00DB },
  { label: 'Freege - Arch Knight', value: 0x00DC },
  { label: 'Freege - Troubadour', value: 0x00DD },
  { label: 'Freege - Lance Knight', value: 0x00DE },
  { label: 'Freege - Socialknight', value: 0x00DF },
  { label: 'Civilian', value: 0x00E0 },
  { label: 'Mercenary', value: 0x00E1 },
  { label: 'Swordmaster', value: 0x00E2 },
  { label: 'Berserker', value: 0x00E3 },
  { label: 'Berserker', value: 0x00E4 },
  { label: 'Silesia - Pegasus Rider', value: 0x00E5 },
  { label: 'Freege - Axe Armour', value: 0x00E6 },
  { label: 'Freege - Sword Armour', value: 0x00E7 },
  { label: 'Freege - Lance Armour', value: 0x00E8 },
  { label: 'Freege - Long Arch', value: 0x00E9 },
  { label: 'Bow Fighter', value: 0x00EA },
  { label: 'Sword Fighter', value: 0x00EB },
  { label: 'Mercenary', value: 0x00EC },
  { label: 'Xavier', value: 0x00ED },
  { label: 'Xavier\'s Lenster Armour', value: 0x00EE },
  { label: 'Xavier\'s Lenster Armour', value: 0x00EF },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F0 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F1 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F2 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F3 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F4 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F5 },
  { label: 'Civilian', value: 0x00F6 },
  { label: 'Civilian', value: 0x00F7 },
  { label: 'Civilian', value: 0x00F8 },
  { label: 'Civilian', value: 0x00F9 },
  { label: 'Civilian', value: 0x00FA },
  { label: 'Civilian', value: 0x00FB },
  { label: 'Civilian', value: 0x00FC },
  { label: 'Civilian', value: 0x00FD },
  { label: 'Freege - Soldier', value: 0x00FE },
  { label: 'Lenster - Soldier', value: 0x00FF },
  { label: 'August', value: 0x0100 },
  { label: 'Resistance - Sword Fighter', value: 0x0101 },
  { label: 'Barrat (Boss)', value: 0x0102 },
  { label: 'Freege - General', value: 0x0103 },
  { label: 'Freege - Sword Armour', value: 0x0104 },
  { label: 'Freege - Priest', value: 0x0105 },
  { label: 'Freege - Poison Arch', value: 0x0106 },
  { label: 'Thracia - Dragon Knight', value: 0x0107 },
  { label: 'Freege - Mage Knight', value: 0x0108 },
  { label: 'Freege - Axe Knight', value: 0x0109 },
  { label: 'Freege - Bow Knight', value: 0x010A },
  { label: 'Freege - Paladin', value: 0x010B },
  { label: 'Freege - Lance Knight', value: 0x010C },
  { label: 'Freege - Sniper', value: 0x010D },
  { label: 'Freege - Mercenary', value: 0x010E },
  { label: 'Freege - Bishop', value: 0x010F },
  { label: 'Freege - Troubadour', value: 0x0110 },
  { label: 'Freege - Mage Knight', value: 0x0111 },
  { label: 'Alster - Socialknight', value: 0x0112 },
  { label: 'Alster - Arch Knight', value: 0x0113 },
  { label: 'Alster - Bow Knight', value: 0x0114 },
  { label: 'Alster - Mage Knight', value: 0x0115 },
  { label: 'Freege - Priest', value: 0x0116 },
  { label: 'Freege - Bow Knight', value: 0x0117 },
  { label: 'Freege - Paladin', value: 0x0118 },
  { label: 'Freege - Sword Armour', value: 0x0119 },
  { label: 'Freege - Arch Knight', value: 0x011A },
  { label: 'Gelb Ritter', value: 0x011B },
  { label: 'Freege - General', value: 0x011C },
  { label: 'Manster - Duke Knight', value: 0x011D },
  { label: 'Manster - Bow Knight', value: 0x011E },
  { label: 'Manster - Great Knight', value: 0x011F },
  { label: 'Thracia - Dragon Knight', value: 0x0120 },
  { label: 'Civilian', value: 0x0121 },
  { label: 'Civilian', value: 0x0122 },
  { label: 'Civilian', value: 0x0123 },
  { label: 'Civilian', value: 0x0124 },
  { label: 'Civilian', value: 0x0125 },
  { label: 'Civilian', value: 0x0126 },
  { label: 'Civilian', value: 0x0127 },
  { label: 'Civilian', value: 0x0128 },
  { label: 'Civilian', value: 0x0129 },
  { label: 'Civilian', value: 0x012A },
  { label: 'Civilian', value: 0x012B },
  { label: 'Civilian', value: 0x012C },
  { label: 'Civilian', value: 0x012D },
  { label: 'Civilian', value: 0x012E },
  { label: 'Mercenary', value: 0x012F },
  { label: 'Mercenary', value: 0x0130 },
  { label: 'Mercenary', value: 0x0131 },
  { label: 'Sniper', value: 0x0132 },
  { label: 'Eins', value: 0x0133 },
  { label: 'Drei (Dagudar)', value: 0x0134 },
  { label: 'Drei', value: 0x0135 },
  { label: 'Elf (Sara)', value: 0x0136 },
  { label: 'Elf', value: 0x0137 },
  { label: 'Zwei (Galzus)', value: 0x0138 },
  { label: 'Zwei', value: 0x0139 },
  { label: 'Zw�lf (Lifis)', value: 0x013A },
  { label: 'Zw�lf', value: 0x013B },
  { label: 'F�nf (Eyvel)', value: 0x013C },
  { label: 'F�nf', value: 0x013D },
  { label: 'Lopto - Dark Mage', value: 0x013E },
  { label: 'Lopto - Axe Armour', value: 0x013F },
  { label: 'Lopto - Bow Armour', value: 0x0140 },
  { label: 'Lopto - Lance Armour', value: 0x0141 },
  { label: 'Manster - Poison Arch', value: 0x0142 },
  { label: 'Leidrick (again)', value: 0x0143 },
  { label: 'Manster - Sword Armour', value: 0x0144 },
  { label: 'Manster - Soldier', value: 0x0145 },
  { label: 'Freege - Iron Arch', value: 0x0146 },
  { label: 'Thracia - Archer', value: 0x0147 },
  { label: 'Thracia - Bishop', value: 0x0148 },
  { label: 'Thracia - Dragon Rider', value: 0x0149 },
  { label: 'Thracia - Soldier', value: 0x014A },
  { label: 'Alster - Socialknight', value: 0x014B },
  { label: 'Pirate', value: 0x014C },
  { label: 'Resistance - Bow Fighter', value: 0x014D },
  { label: 'Resistance - Priest', value: 0x014E },
  { label: 'Resistance - Axe Fighter', value: 0x014F },
  { label: 'Resistance - Bow Fighter', value: 0x0150 },
  { label: 'Resistance - Sword Fighter', value: 0x0151 },
  { label: 'Resistance - Mage', value: 0x0152 },
  { label: 'Manster - General', value: 0x0153 },
  { label: 'Lopto - Dark Mage', value: 0x0154 },
  { label: 'Thracia - Sword Armour', value: 0x0155 },
  { label: 'Wolf (Boss)', value: 0x0156 },
  { label: 'Wolf (Boss)', value: 0x0157 },
];

export const FE5ItemData = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Iron Sword', value: 0x01 },
  { label: 'Steel Sword', value: 0x02 },
  { label: 'Silver Sword', value: 0x03 },
  { label: 'Thin Sword', value: 0x04 },
  { label: 'Iron Broadsword', value: 0x05 },
  { label: 'Killer Sword', value: 0x06 },
  { label: 'Poison Sword', value: 0x07 },
  { label: 'Berserk Sword', value: 0x08 },
  { label: 'Sleep Sword', value: 0x09 },
  { label: 'Beosword', value: 0x0A },
  { label: 'Holy Sword', value: 0x0B },
  { label: 'Loputous Sword', value: 0x0C },
  { label: 'Blagi Sword', value: 0x0D },
  { label: 'Light Sword', value: 0x0E },
  { label: 'Hero Sword', value: 0x0F },
  { label: 'King Sword', value: 0x10 },
  { label: 'Earth Sword', value: 0x11 },
  { label: 'Wind Sword', value: 0x12 },
  { label: 'Fire Sword', value: 0x13 },
  { label: 'Thunder Sword', value: 0x14 },
  { label: 'Elite Sword', value: 0x15 },
  { label: 'Armour Killer', value: 0x16 },
  { label: 'Rapier', value: 0x17 },
  { label: 'Short Sword', value: 0x18 },
  { label: 'Long Sword', value: 0x19 },
  { label: 'Great Sword', value: 0x1A },
  { label: 'Master Sword', value: 0x1B },
  { label: 'Darkness Sword', value: 0x1C },
  { label: 'Mareeta\'s Sword', value: 0x1D },
  { label: 'Broken Sword', value: 0x1E },
  { label: 'Iron Lance', value: 0x1F },
  { label: 'Steel Lance', value: 0x20 },
  { label: 'Silver Lance', value: 0x21 },
  { label: 'Thin Lance', value: 0x22 },
  { label: 'Poison Lance', value: 0x23 },
  { label: 'Dragon Lance', value: 0x24 },
  { label: 'Darkness Lance', value: 0x25 },
  { label: 'Hero Lance', value: 0x26 },
  { label: 'Short Lance', value: 0x27 },
  { label: 'Long Lance', value: 0x28 },
  { label: 'Great Lance', value: 0x29 },
  { label: 'Javelin', value: 0x2A },
  { label: 'Master Lance', value: 0x2B },
  { label: 'Knight Killer', value: 0x2C },
  { label: 'Killer Lance', value: 0x2D },
  { label: 'Gae Bolg', value: 0x2E },
  { label: 'Gungnir', value: 0x2F },
  { label: 'Broken Lance', value: 0x30 },
  { label: 'Iron Axe', value: 0x31 },
  { label: 'Poison Axe', value: 0x32 },
  { label: 'Steel Axe', value: 0x33 },
  { label: 'Silver Axe', value: 0x34 },
  { label: 'Hand Axe', value: 0x35 },
  { label: 'Hammer', value: 0x36 },
  { label: 'Killer Axe', value: 0x37 },
  { label: 'Pugi', value: 0x38 },
  { label: 'Hero Axe', value: 0x39 },
  { label: 'Devil Axe', value: 0x3A },
  { label: 'Battle Axe', value: 0x3B },
  { label: 'Poleaxe', value: 0x3C },
  { label: 'Master Axe', value: 0x3D },
  { label: 'Broken Axe', value: 0x3E },
  { label: 'Iron Bow', value: 0x3F },
  { label: 'Steel Bow', value: 0x40 },
  { label: 'Silver Bow', value: 0x41 },
  { label: 'Poison Bow', value: 0x42 },
  { label: 'Killer Bow', value: 0x43 },
  { label: 'Hero Bow', value: 0x44 },
  { label: 'Short Bow', value: 0x45 },
  { label: 'Long Bow', value: 0x46 },
  { label: 'Great Bow', value: 0x47 },
  { label: 'Master Bow', value: 0x48 },
  { label: 'Long Arch', value: 0x49 },
  { label: 'Iron Arch', value: 0x4A },
  { label: 'Killer Arch', value: 0x4B },
  { label: 'Poison Arch', value: 0x4C },
  { label: 'Broken Bow', value: 0x4D },
  { label: 'Fire', value: 0x4E },
  { label: 'Elfire', value: 0x4F },
  { label: 'Volcannon', value: 0x50 },
  { label: 'Falaflame', value: 0x51 },
  { label: 'Thunder', value: 0x52 },
  { label: 'Daim Thunder', value: 0x53 },
  { label: 'Tron', value: 0x54 },
  { label: 'Torhammer', value: 0x55 },
  { label: 'Wind', value: 0x56 },
  { label: 'Grafucalibur', value: 0x57 },
  { label: 'Tornado', value: 0x58 },
  { label: 'Holsety', value: 0x59 },
  { label: 'Lightning', value: 0x5A },
  { label: 'Rizziah', value: 0x5B },
  { label: 'Aura', value: 0x5C },
  { label: 'Yotsmungand', value: 0x5D },
  { label: 'Fenrir', value: 0x5E },
  { label: 'Hell', value: 0x5F },
  { label: 'Loputous', value: 0x60 },
  { label: 'Meteo', value: 0x61 },
  { label: 'Thunderstorm', value: 0x62 },
  { label: 'Blizzard', value: 0x63 },
  { label: 'Poison', value: 0x64 },
  { label: 'Stone', value: 0x65 },
  { label: 'Holsety(Unlimited)', value: 0x66 },
  { label: 'Broken Book', value: 0x67 },
  { label: 'Live', value: 0x68 },
  { label: 'Relive', value: 0x69 },
  { label: 'Recover', value: 0x6A },
  { label: 'Libro', value: 0x6B },
  { label: 'Reserve', value: 0x6C },
  { label: 'Rescue', value: 0x6D },
  { label: 'Warp', value: 0x6E },
  { label: 'Rest', value: 0x6F },
  { label: 'Silence', value: 0x70 },
  { label: 'Sleep', value: 0x71 },
  { label: 'Torch', value: 0x72 },
  { label: 'Return', value: 0x73 },
  { label: 'Repair', value: 0x74 },
  { label: 'Thief', value: 0x75 },
  { label: 'Watch', value: 0x76 },
  { label: 'Berserk', value: 0x77 },
  { label: 'Unlock', value: 0x78 },
  { label: 'Magic Shield', value: 0x79 },
  { label: 'Rewarp', value: 0x7A },
  { label: 'Cure', value: 0x7B },
  { label: 'Broken Staff', value: 0x7C },
  { label: 'Luck Ring', value: 0x7D },
  { label: 'Live Ring', value: 0x7E },
  { label: 'Speed Ring', value: 0x7F },
  { label: 'Magic Ring', value: 0x80 },
  { label: 'Power Ring', value: 0x81 },
  { label: 'Body Ring', value: 0x82 },
  { label: 'Shield Ring', value: 0x83 },
  { label: 'Skill Ring', value: 0x84 },
  { label: 'Leg Ring', value: 0x85 },
  { label: 'Knight Proof', value: 0x86 },
  { label: 'Master Proof', value: 0x87 },
  { label: 'Treasure Key', value: 0x88 },
  { label: 'Door Key', value: 0x89 },
  { label: 'Bridge Key', value: 0x8A },
  { label: 'Thief Key', value: 0x8B },
  { label: 'S Drink', value: 0x8C },
  { label: 'Medicine', value: 0x8D },
  { label: 'Holy Water', value: 0x8E },
  { label: 'Torch', value: 0x8F },
  { label: 'Antidote', value: 0x90 },
  { label: 'Member Card', value: 0x91 },
  { label: 'Odo Scroll', value: 0x92 },
  { label: 'Baldo Scroll', value: 0x93 },
  { label: 'Hezul Scroll', value: 0x94 },
  { label: 'Dain Scroll', value: 0x95 },
  { label: 'Noba Scroll', value: 0x96 },
  { label: 'Neir Scroll', value: 0x97 },
  { label: 'Ulir Scroll', value: 0x98 },
  { label: 'Tordo Scroll', value: 0x99 },
  { label: 'Fala Scroll', value: 0x9A },
  { label: 'Sety Scroll', value: 0x9B },
  { label: 'Blagi Scroll', value: 0x9C },
  { label: 'Heim Scroll', value: 0x9D },
  { label: 'Elite Manual', value: 0x9E },
  { label: 'Duel Manual', value: 0x9F },
  { label: 'Bargain Manual', value: 0xA0 },
  { label: 'Ambush Manual', value: 0xA1 },
  { label: 'Wrath Manual', value: 0xA2 },
  { label: 'Continue Manual', value: 0xA3 },
  { label: 'Prayer Manual', value: 0xA4 },
  { label: 'Awareness Manual', value: 0xA5 },
  { label: 'Sunlight Manual', value: 0xA6 },
  { label: 'Moonlight Manual', value: 0xA7 },
];
