import React from 'react';
import { Link, useOutletContext } from 'react-router-dom';
import { Alert, Space } from 'antd';

export default function FE7HomePage() {
  const [buffer] = useOutletContext();

  return (
    <Space
      direction="vertical"
      align="center"
      style={{ width: '100%' }}
    >
      <Alert
        message="FE7: Blazing Sword"
        type="info"
      />
      <Link to={{ pathname: 'AIRecruitmentEditor', state: { buffer } }}>AI Recruitment Editor</Link>
      <Link to={{ pathname: 'AIRecruitmentEditorP2', state: { buffer } }}>AI Recruitment Editor P2</Link>
      <Link to={{ pathname: 'AssassinLegaultCustomAnimationEditor', state: { buffer } }}>Assassin Legault Custom Animation Editor</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart1', state: { buffer } }}>Battle screen editor part 1</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart2', state: { buffer } }}>Battle screen editor part 2</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart3', state: { buffer } }}>Battle screen editor part 3</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart4', state: { buffer } }}>Battle screen editor part 4</Link>
      <Link to={{ pathname: 'Battlescreeneditorpart5', state: { buffer } }}>Battle screen editor part 5</Link>
      <Link to={{ pathname: 'BlessingoftheEightGeneralsEditor', state: { buffer } }}>Blessing of the Eight Generals Editor</Link>
      <Link to={{ pathname: 'Chapter1TableEditor', state: { buffer } }}>Chapter 1 Table Editor</Link>
      <Link to={{ pathname: 'Chapter1UnitEditor', state: { buffer } }}>Chapter 1 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter10ArmouryEditor', state: { buffer } }}>Chapter 10 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter10SeizeEditor', state: { buffer } }}>Chapter 10 Seize Editor</Link>
      <Link to={{ pathname: 'Chapter10ShopEditor', state: { buffer } }}>Chapter 10 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter10TableEditor', state: { buffer } }}>Chapter 10 Table Editor</Link>
      <Link to={{ pathname: 'Chapter10UnitEditor', state: { buffer } }}>Chapter 10 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter11SeizeEditor', state: { buffer } }}>Chapter 11 Seize Editor</Link>
      <Link to={{ pathname: 'Chapter11ShopEditor', state: { buffer } }}>Chapter 11 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter11TableEditor', state: { buffer } }}>Chapter 11 Table Editor</Link>
      <Link to={{ pathname: 'Chapter11UnitEditor', state: { buffer } }}>Chapter 11 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter11HTableEditor', state: { buffer } }}>Chapter 11H Table Editor</Link>
      <Link to={{ pathname: 'Chapter11HUnitEditor', state: { buffer } }}>Chapter 11H Unit Editor</Link>
      <Link to={{ pathname: 'Chapter12ArmouryEditor', state: { buffer } }}>Chapter 12 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter12ShopEditor', state: { buffer } }}>Chapter 12 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter12TableEditor', state: { buffer } }}>Chapter 12 Table Editor</Link>
      <Link to={{ pathname: 'Chapter12UnitEditor', state: { buffer } }}>Chapter 12 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter13ArmouryEditor', state: { buffer } }}>Chapter 13 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter13SeizeEditor', state: { buffer } }}>Chapter 13 Seize Editor</Link>
      <Link to={{ pathname: 'Chapter13ShopEditor', state: { buffer } }}>Chapter 13 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter13TableEditor', state: { buffer } }}>Chapter 13 Table Editor</Link>
      <Link to={{ pathname: 'Chapter13UnitEditor', state: { buffer } }}>Chapter 13 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter13xTableEditor', state: { buffer } }}>Chapter 13x Table Editor</Link>
      <Link to={{ pathname: 'Chapter13xUnitEditor', state: { buffer } }}>Chapter 13x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter14ArmouryEditor', state: { buffer } }}>Chapter 14 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter14ShopEditor', state: { buffer } }}>Chapter 14 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter14UnitEditor', state: { buffer } }}>Chapter 14 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter15SeizeEditor', state: { buffer } }}>Chapter 15 Seize Editor</Link>
      <Link to={{ pathname: 'Chapter15TableEditor', state: { buffer } }}>Chapter 15 Table Editor</Link>
      <Link to={{ pathname: 'Chapter15UnitEditor', state: { buffer } }}>Chapter 15 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter16LeftArmouryEditor', state: { buffer } }}>Chapter 16 Left Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter16RightArmouryEditor', state: { buffer } }}>Chapter 16 Right Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter16SeizeEditor', state: { buffer } }}>Chapter 16 Seize Editor</Link>
      <Link to={{ pathname: 'Chapter16ShopEditor', state: { buffer } }}>Chapter 16 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter16TableEditor', state: { buffer } }}>Chapter 16 Table Editor</Link>
      <Link to={{ pathname: 'Chapter16UnitEditor', state: { buffer } }}>Chapter 16 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter17TableEditor', state: { buffer } }}>Chapter 17 Table Editor</Link>
      <Link to={{ pathname: 'Chapter17UnitEditor', state: { buffer } }}>Chapter 17 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter17xShopEditor', state: { buffer } }}>Chapter 17x Shop Editor</Link>
      <Link to={{ pathname: 'Chapter17xTableEditor', state: { buffer } }}>Chapter 17x Table Editor</Link>
      <Link to={{ pathname: 'Chapter17xUnitEditor', state: { buffer } }}>Chapter 17x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter18ArmouryEditor', state: { buffer } }}>Chapter 18 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter18ShopEditor', state: { buffer } }}>Chapter 18 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter18TableEditor', state: { buffer } }}>Chapter 18 Table Editor</Link>
      <Link to={{ pathname: 'Chapter18UnitEditor', state: { buffer } }}>Chapter 18 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter18xSeizeEditor', state: { buffer } }}>Chapter 18x Seize Editor</Link>
      <Link to={{ pathname: 'Chapter19SeizeEditor', state: { buffer } }}>Chapter 19 Seize Editor</Link>
      <Link to={{ pathname: 'Chapter19TableEditor', state: { buffer } }}>Chapter 19 Table Editor</Link>
      <Link to={{ pathname: 'Chapter19UnitEditor', state: { buffer } }}>Chapter 19 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter19xTableEditor', state: { buffer } }}>Chapter 19x Table Editor</Link>
      <Link to={{ pathname: 'Chapter19xUnitEditor', state: { buffer } }}>Chapter 19x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter19xxTableEditor', state: { buffer } }}>Chapter 19xx Table Editor</Link>
      <Link to={{ pathname: 'Chapter19xxUnitEditor', state: { buffer } }}>Chapter 19xx Unit Editor</Link>
      <Link to={{ pathname: 'Chapter2SeizeEditor', state: { buffer } }}>Chapter 2 Seize Editor</Link>
      <Link to={{ pathname: 'Chapter2UnitEditor', state: { buffer } }}>Chapter 2 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter20Secret1Editor', state: { buffer } }}>Chapter 20 Secret1 Editor</Link>
      <Link to={{ pathname: 'Chapter20Secret2Editor', state: { buffer } }}>Chapter 20 Secret2 Editor</Link>
      <Link to={{ pathname: 'Chapter20TableEditor', state: { buffer } }}>Chapter 20 Table Editor</Link>
      <Link to={{ pathname: 'Chapter20UnitEditor', state: { buffer } }}>Chapter 20 Unit Editor</Link>
      <Link to={{ pathname: '21TableEditor', state: { buffer } }}>Chapter 20/21 Table Editor</Link>
      <Link to={{ pathname: 'Chapter21LeftArmouryEditor', state: { buffer } }}>Chapter 21 Left Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter21LeftShopEditor', state: { buffer } }}>Chapter 21 Left Shop Editor</Link>
      <Link to={{ pathname: 'Chapter21RightArmouryEditor', state: { buffer } }}>Chapter 21 Right Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter21RightShopEditor', state: { buffer } }}>Chapter 21 Right Shop Editor</Link>
      <Link to={{ pathname: 'Chapter21UnitEditor', state: { buffer } }}>Chapter 21 Unit Editor</Link>
      <Link to={{ pathname: '22TableEditor', state: { buffer } }}>Chapter 21/22 Table Editor</Link>
      <Link to={{ pathname: 'Chapter22SecretEditor', state: { buffer } }}>Chapter 22 Secret Editor</Link>
      <Link to={{ pathname: 'Chapter22UnitEditor', state: { buffer } }}>Chapter 22 Unit Editor</Link>
      <Link to={{ pathname: '23TableEditor', state: { buffer } }}>Chapter 22/23 Table Editor</Link>
      <Link to={{ pathname: '23xTableEditor', state: { buffer } }}>Chapter 22x/23x Table Editor</Link>
      <Link to={{ pathname: 'Chapter23UnitEditor', state: { buffer } }}>Chapter 23 Unit Editor</Link>
      <Link to={{ pathname: '24LinusTableEditor', state: { buffer } }}>Chapter 23/24 Linus Table Editor</Link>
      <Link to={{ pathname: '24LloydTableEditor', state: { buffer } }}>Chapter 23/24 Lloyd Table Editor</Link>
      <Link to={{ pathname: 'Chapter23xUnitEditor', state: { buffer } }}>Chapter 23x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter24LinusUnitEditor', state: { buffer } }}>Chapter 24 Linus Unit Editor</Link>
      <Link to={{ pathname: 'Chapter24LloydUnitEditor', state: { buffer } }}>Chapter 24 Lloyd Unit Editor</Link>
      <Link to={{ pathname: '26TableEditor', state: { buffer } }}>Chapter 24/26 Table Editor</Link>
      <Link to={{ pathname: 'Chapter24ALeftArmouryEditor', state: { buffer } }}>Chapter 24A Left Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter24ALeftShopEditor', state: { buffer } }}>Chapter 24A Left Shop Editor</Link>
      <Link to={{ pathname: 'Chapter24ARightArmouryEditor', state: { buffer } }}>Chapter 24A Right Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter24ARightShopEditor', state: { buffer } }}>Chapter 24A Right Shop Editor</Link>
      <Link to={{ pathname: 'Chapter24ASecretEditor', state: { buffer } }}>Chapter 24A Secret Editor</Link>
      <Link to={{ pathname: 'Chapter24BLeftArmouryEditor', state: { buffer } }}>Chapter 24B Left Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter24BLeftShopEditor', state: { buffer } }}>Chapter 24B Left Shop Editor</Link>
      <Link to={{ pathname: 'Chapter24BRightArmouryEditor', state: { buffer } }}>Chapter 24B Right Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter24BRightShopEditor', state: { buffer } }}>Chapter 24B Right Shop Editor</Link>
      <Link to={{ pathname: 'Chapter24BSecretEditor', state: { buffer } }}>Chapter 24B Secret Editor</Link>
      <Link to={{ pathname: 'Chapter25ArmouryEditor', state: { buffer } }}>Chapter 25 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter25CutsceneUnitEditor', state: { buffer } }}>Chapter 25 Cutscene Unit Editor</Link>
      <Link to={{ pathname: 'Chapter25ShopEditor', state: { buffer } }}>Chapter 25 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter25UnitEditor', state: { buffer } }}>Chapter 25 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter2527JermeTableEditor', state: { buffer } }}>Chapter 25-27 Jerme Table Editor</Link>
      <Link to={{ pathname: 'Chapter2527KennethTableEditor', state: { buffer } }}>Chapter 25-27 Kenneth Table Editor</Link>
      <Link to={{ pathname: 'Chapter25HTableEditor', state: { buffer } }}>Chapter 25H Table Editor</Link>
      <Link to={{ pathname: 'Chapter26ArmouryEditor', state: { buffer } }}>Chapter 26 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter26ShopEditor', state: { buffer } }}>Chapter 26 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter26UnitEditor', state: { buffer } }}>Chapter 26 Unit Editor</Link>
      <Link to={{ pathname: '28TableEditor', state: { buffer } }}>Chapter 26/28 Table Editor</Link>
      <Link to={{ pathname: '28xTableEditor', state: { buffer } }}>Chapter 26x/28x Table Editor</Link>
      <Link to={{ pathname: 'Chapter27JermeUnitEditor', state: { buffer } }}>Chapter 27 Jerme Unit Editor</Link>
      <Link to={{ pathname: 'Chapter27KennethUnitEditor', state: { buffer } }}>Chapter 27 Kenneth Unit Editor</Link>
      <Link to={{ pathname: '29TableEditor', state: { buffer } }}>Chapter 27/29 Table Editor</Link>
      <Link to={{ pathname: 'Chapter28EliwoodTableEditor', state: { buffer } }}>Chapter 28 Eliwood Table Editor</Link>
      <Link to={{ pathname: 'Chapter28UnitEditor', state: { buffer } }}>Chapter 28 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter28xUnitEditor', state: { buffer } }}>Chapter 28x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter29ArmouryEditor', state: { buffer } }}>Chapter 29 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter29ShopEditor', state: { buffer } }}>Chapter 29 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter29UnitEditor', state: { buffer } }}>Chapter 29 Unit Editor</Link>
      <Link to={{ pathname: '31TableEditor', state: { buffer } }}>Chapter 29/31 Table Editor</Link>
      <Link to={{ pathname: '31xTableEditor', state: { buffer } }}>Chapter 29x/31x Table Editor</Link>
      <Link to={{ pathname: 'Chapter3ArmouryEditor', state: { buffer } }}>Chapter 3 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter3TableEditor', state: { buffer } }}>Chapter 3 Table Editor</Link>
      <Link to={{ pathname: 'Chapter3UnitEditor', state: { buffer } }}>Chapter 3 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter30EliwoodUnitEditor', state: { buffer } }}>Chapter 30 Eliwood Unit Editor</Link>
      <Link to={{ pathname: 'Chapter30HectorTableEditor', state: { buffer } }}>Chapter 30 Hector Table Editor</Link>
      <Link to={{ pathname: 'Chapter30HectorUnitEditor', state: { buffer } }}>Chapter 30 Hector Unit Editor</Link>
      <Link to={{ pathname: '32TableEditor', state: { buffer } }}>Chapter 30/32 Table Editor</Link>
      <Link to={{ pathname: 'Chapter31SecretEditor', state: { buffer } }}>Chapter 31 Secret Editor</Link>
      <Link to={{ pathname: 'Chapter31UnitEditor', state: { buffer } }}>Chapter 31 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter31xBottomArmouryEditor', state: { buffer } }}>Chapter 31x Bottom Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter31xLeftShopEditor', state: { buffer } }}>Chapter 31x Left Shop Editor</Link>
      <Link to={{ pathname: 'Chapter31xRightShopEditor', state: { buffer } }}>Chapter 31x Right Shop Editor</Link>
      <Link to={{ pathname: 'Chapter31xtLeftArmouryEditor', state: { buffer } }}>Chapter 31x tLeft Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter31xtMiddleArmouryEditor', state: { buffer } }}>Chapter 31x tMiddle Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter31xtRightArmouryEditor', state: { buffer } }}>Chapter 31x tRight Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter31xUnitEditor', state: { buffer } }}>Chapter 31x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter32SecretEditor', state: { buffer } }}>Chapter 32 Secret Editor</Link>
      <Link to={{ pathname: 'Chapter32UnitEditor', state: { buffer } }}>Chapter 32 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter32xTableEditor', state: { buffer } }}>Chapter 32x Table Editor</Link>
      <Link to={{ pathname: 'Chapter32xUnitEditor', state: { buffer } }}>Chapter 32x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter4TableEditor', state: { buffer } }}>Chapter 4 Table Editor</Link>
      <Link to={{ pathname: 'Chapter4UnitEditor', state: { buffer } }}>Chapter 4 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter5ArmouryEditor', state: { buffer } }}>Chapter 5 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter5TableEditor', state: { buffer } }}>Chapter 5 Table Editor</Link>
      <Link to={{ pathname: 'Chapter5UnitEditor', state: { buffer } }}>Chapter 5 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter6TableEditor', state: { buffer } }}>Chapter 6 Table Editor</Link>
      <Link to={{ pathname: 'Chapter6UnitEditor', state: { buffer } }}>Chapter 6 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter7ShopEditor', state: { buffer } }}>Chapter 7 Shop Editor</Link>
      <Link to={{ pathname: 'Chapter7TableEditor', state: { buffer } }}>Chapter 7 Table Editor</Link>
      <Link to={{ pathname: 'Chapter7UnitEditor', state: { buffer } }}>Chapter 7 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter7xTableEditor', state: { buffer } }}>Chapter 7x Table Editor</Link>
      <Link to={{ pathname: 'Chapter7xUnitEditor', state: { buffer } }}>Chapter 7x Unit Editor</Link>
      <Link to={{ pathname: 'Chapter8ArmouryEditor', state: { buffer } }}>Chapter 8 Armoury Editor</Link>
      <Link to={{ pathname: 'Chapter8TableEditor', state: { buffer } }}>Chapter 8 Table Editor</Link>
      <Link to={{ pathname: 'Chapter8UnitEditor', state: { buffer } }}>Chapter 8 Unit Editor</Link>
      <Link to={{ pathname: 'Chapter9SeizeEditor', state: { buffer } }}>Chapter 9 Seize Editor</Link>
      <Link to={{ pathname: 'Chapter9TableEditor', state: { buffer } }}>Chapter 9 Table Editor</Link>
      <Link to={{ pathname: 'Chapter9UnitEditor', state: { buffer } }}>Chapter 9 Unit Editor</Link>
      <Link to={{ pathname: 'ChapterDataEditorFE7', state: { buffer } }}>Chapter Data Editor (FE7) -</Link>
      <Link to={{ pathname: 'ChapterFinalBossUnitEditor', state: { buffer } }}>Chapter Final Boss Unit Editor</Link>
      <Link to={{ pathname: 'ChapterFinalUnitEditor', state: { buffer } }}>Chapter Final Unit Editor</Link>
      <Link to={{ pathname: 'ChapterUnitEditor', state: { buffer } }}>Chapter Unit Editor</Link>
      <Link to={{ pathname: 'CustomBattleSpriteTableEditor', state: { buffer } }}>Custom Battle Sprite Table Editor</Link>
      <Link to={{ pathname: 'CustomShopEditor', state: { buffer } }}>Custom Shop Editor</Link>
      <Link to={{ pathname: 'Deathquoteeditorpart1', state: { buffer } }}>Death quote editor part 1</Link>
      <Link to={{ pathname: 'Deathquoteeditorpart2', state: { buffer } }}>Death quote editor part 2</Link>
      <Link to={{ pathname: 'EscapeTilePointerEditor', state: { buffer } }}>Escape Tile Pointer Editor</Link>
      <Link to={{ pathname: 'AnimationPointerTableEditor', state: { buffer } }}>FE 7 Animation Pointer Table Editor</Link>
      <Link to={{ pathname: 'Arenaclasseditor', state: { buffer } }}>FE 7 Arena class editor</Link>
      <Link to={{ pathname: 'Eventtablereferences', state: { buffer } }}>FE 7 Event table references</Link>
      <Link to={{ pathname: 'Mapspritepointertableeditor', state: { buffer } }}>FE 7 Map sprite pointer table editor</Link>
      <Link to={{ pathname: 'TutorialEditor', state: { buffer } }}>FE 7 Tutorial Editor</Link>
      <Link to={{ pathname: 'WorldMapDataReferences', state: { buffer } }}>FE 7 World Map Data References</Link>
      <Link to={{ pathname: 'AfaDropsBoostEditor', state: { buffer } }}>FE7 Afa Drops Boost Editor</Link>
      <Link to={{ pathname: 'BattleAnimationEditor', state: { buffer } }}>FE7 Battle Animation Editor</Link>
      <Link to={{ pathname: 'BattleBGEditor', state: { buffer } }}>FE7 Battle BG Editor</Link>
      <Link to={{ pathname: 'BattlePaletteReference', state: { buffer } }}>FE7 Battle Palette Reference</Link>
      <Link to={{ pathname: 'BetaCharacterEditor', state: { buffer } }}>FE7 Beta Character Editor</Link>
      <Link to={{ pathname: 'BetaClassEditor', state: { buffer } }}>FE7 Beta Class Editor</Link>
      <Link to={{ pathname: 'BetaItemEditor', state: { buffer } }}>FE7 Beta Item Editor</Link>
      <Link to={{ pathname: 'BossMusicEditor', state: { buffer } }}>FE7 Boss Music Editor</Link>
      <Link to={{ pathname: 'CGEditor', state: { buffer } }}>FE7 CG Editor</Link>
      <Link to={{ pathname: 'Ch11HChestEditor', state: { buffer } }}>FE7 Ch 11H Chest Editor</Link>
      <Link to={{ pathname: 'Ch15ChestEditor', state: { buffer } }}>FE7 Ch 15 Chest Editor</Link>
      <Link to={{ pathname: 'Ch17ChestEditor', state: { buffer } }}>FE7 Ch 17 Chest Editor</Link>
      <Link to={{ pathname: 'Ch19xChestEditor', state: { buffer } }}>FE7 Ch 19x Chest Editor</Link>
      <Link to={{ pathname: 'Ch19xxChestEditor', state: { buffer } }}>FE7 Ch 19xx Chest Editor</Link>
      <Link to={{ pathname: 'Ch20ChestEditor', state: { buffer } }}>FE7 Ch 20 Chest Editor</Link>
      <Link to={{ pathname: 'Ch22ChestEditor', state: { buffer } }}>FE7 Ch 22 Chest Editor</Link>
      <Link to={{ pathname: 'Ch23xChestEditor', state: { buffer } }}>FE7 Ch 23x Chest Editor</Link>
      <Link to={{ pathname: 'Ch26ChestEditor', state: { buffer } }}>FE7 Ch 26 Chest Editor</Link>
      <Link to={{ pathname: 'Ch27AChestEditor', state: { buffer } }}>FE7 Ch 27A Chest Editor</Link>
      <Link to={{ pathname: 'Ch27BChestEditor', state: { buffer } }}>FE7 Ch 27B Chest Editor</Link>
      <Link to={{ pathname: 'Ch28ChestEditor', state: { buffer } }}>FE7 Ch 28 Chest Editor</Link>
      <Link to={{ pathname: 'Ch28xChestEditor', state: { buffer } }}>FE7 Ch 28x Chest Editor</Link>
      <Link to={{ pathname: 'Ch29ChestEditor', state: { buffer } }}>FE7 Ch 29 Chest Editor</Link>
      <Link to={{ pathname: 'Ch30HChestEditor', state: { buffer } }}>FE7 Ch 30H Chest Editor</Link>
      <Link to={{ pathname: 'Ch31ChestEditor', state: { buffer } }}>FE7 Ch 31 Chest Editor</Link>
      <Link to={{ pathname: 'Ch32xChestEditor', state: { buffer } }}>FE7 Ch 32x Chest Editor</Link>
      <Link to={{ pathname: 'Ch6ChestEditor', state: { buffer } }}>FE7 Ch 6 Chest Editor</Link>
      <Link to={{ pathname: 'Ch7xChestEditor', state: { buffer } }}>FE7 Ch 7x Chest Editor</Link>
      <Link to={{ pathname: 'ChFinalChestEditor', state: { buffer } }}>FE7 Ch Final Chest Editor</Link>
      <Link to={{ pathname: 'ChUnknown2ChestEditor', state: { buffer } }}>FE7 Ch Unknown2 Chest Editor</Link>
      <Link to={{ pathname: 'CharacterEditor', state: { buffer } }}>FE7 Character Editor</Link>
      <Link to={{ pathname: 'ClassEditor', state: { buffer } }}>FE7 Class Editor</Link>
      <Link to={{ pathname: 'ConvoBGEditor', state: { buffer } }}>FE7 Convo BG Editor</Link>
      <Link to={{ pathname: 'CustomBattleAnimationEditor', state: { buffer } }}>FE7 Custom Battle Animation Editor</Link>
      <Link to={{ pathname: 'CustomItemAnimationListWorksonlywithanexpandedROM', state: { buffer } }}>FE7 Custom Item Animation List - Works only with an expanded ROM!</Link>
      <Link to={{ pathname: 'CustomPromotionPointerEditor', state: { buffer } }}>FE7 Custom Promotion Pointer Editor</Link>
      <Link to={{ pathname: 'FallenContractPromotionEditor', state: { buffer } }}>FE7 Fallen Contract Promotion Editor</Link>
      <Link to={{ pathname: 'HeavenSealPromotionEditor', state: { buffer } }}>FE7 Heaven Seal Promotion Editor</Link>
      <Link to={{ pathname: 'ItemAnimationReferencePointerExpandedROMrequired', state: { buffer } }}>FE7 Item Animation Reference Pointer - Expanded ROM required</Link>
      <Link to={{ pathname: 'ItemEditor', state: { buffer } }}>FE7 Item Editor</Link>
      <Link to={{ pathname: 'MusicArrayEditor', state: { buffer } }}>FE7 Music Array Editor</Link>
      <Link to={{ pathname: 'OceanSealPromotionEditor', state: { buffer } }}>FE7 Ocean Seal Promotion Editor</Link>
      <Link to={{ pathname: 'PortraitEditor', state: { buffer } }}>FE7 Portrait Editor</Link>
      <Link to={{ pathname: 'PromotionItemEditor', state: { buffer } }}>FE7 Promotion Item Editor</Link>
      <Link to={{ pathname: 'SoundRoomEditor', state: { buffer } }}>FE7 Sound Room Editor</Link>
      <Link to={{ pathname: 'SpellAssociationEditor', state: { buffer } }}>FE7 Spell Association Editor</Link>
      <Link to={{ pathname: 'Standingmapspriteeditor', state: { buffer } }}>FE7 Standing map sprite editor</Link>
      <Link to={{ pathname: 'StatBonusesEditor', state: { buffer } }}>FE7 Stat Bonuses Editor</Link>
      <Link to={{ pathname: 'SupportPointerEditor', state: { buffer } }}>FE7 Support Pointer Editor</Link>
      <Link to={{ pathname: 'TerrainStatEditor', state: { buffer } }}>FE7 Terrain Stat Editor</Link>
      <Link to={{ pathname: 'FinalChapter2TableEditor', state: { buffer } }}>Final Chapter (2) Table Editor</Link>
      <Link to={{ pathname: 'FinalChapterTableEditor', state: { buffer } }}>Final Chapter Table Editor</Link>
      <Link to={{ pathname: 'FireEmblem7PairedEndingsEditorbyIcyToast', state: { buffer } }}>Fire Emblem 7 (Paired) Endings Editor (by Icy Toast)</Link>
      <Link to={{ pathname: 'FireEmblem7SupportcompatibilityEditorbyIcyToast', state: { buffer } }}>Fire Emblem 7 Support compatibility Editor (by Icy Toast)</Link>
      <Link to={{ pathname: 'FireEmblem7SupportConvoAvailabilityEditorbyIcyToast', state: { buffer } }}>Fire Emblem 7 Support Convo Availability Editor (by Icy Toast)</Link>
      <Link to={{ pathname: 'HawkeyeCustomAnimationEditor', state: { buffer } }}>Hawkeye Custom Animation Editor</Link>
      <Link to={{ pathname: 'HeroRavenCustomAnimationEditor', state: { buffer } }}>Hero Raven Custom Animation Editor</Link>
      <Link to={{ pathname: 'IsadoraCustomAnimationEditor', state: { buffer } }}>Isadora Custom Animation Editor</Link>
      <Link to={{ pathname: 'Linus1CustomAnimationEditor', state: { buffer } }}>Linus (1) Custom Animation Editor</Link>
      <Link to={{ pathname: 'Linus2CustomAnimationEditor', state: { buffer } }}>Linus (2) Custom Animation Editor</Link>
      <Link to={{ pathname: 'Linus3CustomAnimationEditor', state: { buffer } }}>Linus (3) Custom Animation Editor</Link>
      <Link to={{ pathname: 'Lloyd1CustomAnimationEditor', state: { buffer } }}>Lloyd (1) Custom Animation Editor</Link>
      <Link to={{ pathname: 'Lloyd2CustomAnimationEditor', state: { buffer } }}>Lloyd (2) Custom Animation Editor</Link>
      <Link to={{ pathname: 'Lloyd3CustomAnimationEditor', state: { buffer } }}>Lloyd (3) Custom Animation Editor</Link>
      <Link to={{ pathname: 'LuciusBishopCustomAnimationEditor', state: { buffer } }}>Lucius Bishop Custom Animation Editor</Link>
      <Link to={{ pathname: 'LuciusMonkCustomAnimationEditor', state: { buffer } }}>Lucius Monk Custom Animation Editor</Link>
      <Link to={{ pathname: 'LynsEndingEditor', state: { buffer } }}>Lyn&apos;s Ending Editor</Link>
      <Link to={{ pathname: 'MovementTypeEditorFE7CredittoFireBlazer', state: { buffer } }}>Movement Type Editor (FE7) - Credit to Fire Blazer</Link>
      <Link to={{ pathname: 'MyrmidonGuyCustomAnimationEditor', state: { buffer } }}>Myrmidon Guy Custom Animation Editor</Link>
      <Link to={{ pathname: 'NinoSageCustomAnimationEditor', state: { buffer } }}>Nino Sage Custom Animation Editor</Link>
      <Link to={{ pathname: 'PrologueSeizeEditor', state: { buffer } }}>Prologue Seize Editor</Link>
      <Link to={{ pathname: 'PrologueUnitEditor', state: { buffer } }}>Prologue Unit Editor</Link>
      <Link to={{ pathname: 'SpecifiedBattleConvoEditorFE7', state: { buffer } }}>Specified Battle Convo Editor (FE7) -</Link>
      <Link to={{ pathname: 'SupportBonusEditor', state: { buffer } }}>Support Bonus Editor</Link>
      <Link to={{ pathname: 'SwordmasterGuyCustomAnimationEditor', state: { buffer } }}>Swordmaster Guy Custom Animation Editor</Link>
      <Link to={{ pathname: 'ThiefLegaultCustomAnimationEditor', state: { buffer } }}>Thief Legault Custom Animation Editor</Link>
      <Link to={{ pathname: 'TriangleattackConvo', state: { buffer } }}>Triangle attack Convo -</Link>
      <Link to={{ pathname: 'TurnMenutable', state: { buffer } }}>Turn Menu table</Link>
      <Link to={{ pathname: 'UnitMenutable', state: { buffer } }}>Unit Menu table</Link>
      <Link to={{ pathname: 'Unknown18UnitEditor', state: { buffer } }}>Unknown18 Unit Editor</Link>
      <Link to={{ pathname: 'UnspecifiedBattleConvoEditorFE7', state: { buffer } }}>Unspecified Battle Convo Editor (FE7) -</Link>
    </Space>
  );
}
