export const ChapterList = [
  { label: '00 Prologue', value: 0 },
  { label: '01 Ch 1', value: 1 },
  { label: '02 Ch 2', value: 2 },
  { label: '03 Ch 3', value: 3 },
  { label: '04 Ch 4/Zaha Woods', value: 4 },
  { label: '05 Ch 5x', value: 5 },
  { label: '06 Ch 5', value: 6 },
  { label: '07 Ch 6/Adlas Plains', value: 7 },
  { label: '08 Ch 7', value: 8 },
  { label: '09 Ch 8', value: 9 },
  { label: '0A Ch 9 Eirika', value: 10 },
  { label: '0B Ch 10 Eirika/Teras Plateau', value: 11 },
  { label: '0C Ch 12 Eirika', value: 12 },
  { label: '0D Ch 13 Eirika', value: 13 },
  { label: '0E Ch 14 Eirika', value: 14 },
  { label: '0F Ch 15 Eirika', value: 15 },
  { label: '10 Ch 16 Eirika', value: 16 },
  { label: '11 Ch 17 Eirika/Narube River', value: 17 },
  { label: '12 Ch 18 Eirika/Neleras Peak', value: 18 },
  { label: '13 Ch 19 Eirika', value: 19 },
  { label: '14 Ch 20 Eirika', value: 20 },
  { label: '15 Final Ch 1 Eirika', value: 21 },
  { label: '16 Final Ch 2 Erika', value: 22 },
  { label: '17 Ch 9 Ephraim', value: 23 },
  { label: '18 Ch 10 Ephraim/Bethroen', value: 24 },
  { label: '19 Ch 12 Ephraim', value: 25 },
  { label: '1A Ch 13 Ephraim/Za\'abadul Marsh', value: 26 },
  { label: '1B Ch 14 Ephraim', value: 27 },
  { label: '1C Ch 15 Ephraim', value: 28 },
  { label: '1D Ch 16 Ephraim', value: 29 },
  { label: '1E Ch 17 Ephraim/Narube River', value: 30 },
  { label: '1F Ch 18 Ephraim/Neleras Peak', value: 31 },
  { label: '20 Ch 19 Ephraim', value: 32 },
  { label: '21 Ch 20 Ephraim', value: 33 },
  { label: '22 Final Ch 1 Ephraim', value: 34 },
  { label: '23 Final Ch 2 Ephraim', value: 35 },
  { label: '24 Tower of Valni 1', value: 36 },
  { label: '25 Tower of Valni 2', value: 37 },
  { label: '26 Tower of Valni 3', value: 38 },
  { label: '27 Tower of Valni 4', value: 39 },
  { label: '28 Tower of Valni 5', value: 40 },
  { label: '29 Tower of Valni 6', value: 41 },
  { label: '2A Tower of Valni 7', value: 42 },
  { label: '2B Tower of Valni 8', value: 43 },
  { label: '2C Tower of Valni 8 Clone', value: 44 },
  { label: '2D Tower of Valni 8 Clone', value: 45 },
  { label: '2E Lagdou Ruins 1', value: 46 },
  { label: '2F Lagdou Ruins 2', value: 47 },
  { label: '30 Lagdou Ruins 3', value: 48 },
  { label: '31 Lagdou Ruins 4', value: 49 },
  { label: '32 Lagdou Ruins 5', value: 50 },
  { label: '33 Lagdou Ruins 6', value: 51 },
  { label: '34 Lagdou Ruins 7', value: 52 },
  { label: '35 Lagdou Ruins 8', value: 53 },
  { label: '36 Lagdou Ruins 9', value: 54 },
  { label: '37 Lagdou Ruins 10', value: 55 },
  { label: '38 Lords split up (glitchy map)', value: 56 },
  { label: '39 Melkaen Coast', value: 57 },
  { label: '3A Link Arena', value: 58 },
  { label: '3B The interesting map...', value: 59 },
  { label: '3C Debug map', value: 60 },
  { label: '3D Ch 11 Eirika', value: 61 },
  { label: '3E Ch 11 Ephraim', value: 62 },
  { label: '3F Grado castle', value: 63 },
  { label: '40 Renais castle', value: 64 },
  { label: '41 Caer Pelyn', value: 65 },
  { label: '42 Renais throne', value: 66 },
  { label: '43 Renais audience', value: 67 },
  { label: '44 Renval gate', value: 68 },
  { label: '45 Grado borders', value: 69 },
  { label: '46 Grado prison', value: 70 },
  { label: '47 Grado shrine (Past)', value: 71 },
  { label: '48 Renais shrine', value: 72 },
  { label: '49 Some path', value: 73 },
  { label: '4A Some building', value: 74 },
  { label: '4B Another shrine', value: 75 },
  { label: '4C Another path', value: 76 },
  { label: '4D Grado shrine (Present)', value: 77 },
  { label: '4E Ch 5 town (Past)', value: 78 },
];

export const Pointers = [
  { label: 'Not used', value: 0x00 },
  { label: 'Object type 1', value: 0x01 },
  { label: 'Map Palette 1', value: 0x02 },
  { label: 'Tile Configuration 1', value: 0x03 },
  { label: 'Prologue Map', value: 0x04 },
  { label: 'Tile animations 1', value: 0x05 },
  { label: 'Prologue Map changes', value: 0x06 },
  { label: 'Prologue events', value: 0x07 },
  { label: 'Ch 1 Map', value: 0x08 },
  { label: 'Ch 1 map changes', value: 0x09 },
  { label: 'Ch 1 events', value: 0x0A },
  { label: 'Ch 2 map', value: 0x0B },
  { label: 'Ch 2 Tile changes', value: 0x0C },
  { label: 'Ch 2 events', value: 0x0D },
  { label: 'Object type 2', value: 0x0E },
  { label: 'Map palette 2', value: 0x0F },
  { label: 'Tile configuration 2', value: 0x10 },
  { label: 'Ch 3 map', value: 0x11 },
  { label: 'Tile animations 2', value: 0x12 },
  { label: 'Ch 3 map changes', value: 0x13 },
  { label: 'Ch 3 events', value: 0x14 },
  { label: 'Ch 4 Map', value: 0x15 },
  { label: 'Ch 4 Map changes', value: 0x16 },
  { label: 'Ch 4 events', value: 0x17 },
  { label: 'Object type 3', value: 0x18 },
  { label: 'Map palette 3', value: 0x19 },
  { label: 'Tile confihutation 3', value: 0x1A },
  { label: 'Ch 5x map', value: 0x1B },
  { label: 'Tile animations 3', value: 0x1C },
  { label: 'Ch 5x Map changes', value: 0x1D },
  { label: 'Ch 5x Events', value: 0x1E },
  { label: 'Ch 5 Map', value: 0x1F },
  { label: 'Ch 5 map changes', value: 0x20 },
  { label: 'Ch 5 event data', value: 0x21 },
  { label: 'Ch 6 map', value: 0x22 },
  { label: 'Ch 6 Map changes', value: 0x23 },
  { label: 'Ch 6 events', value: 0x24 },
  { label: 'Ch 7 map', value: 0x25 },
  { label: 'Ch 7 map changes', value: 0x26 },
  { label: 'Ch 7 event data', value: 0x27 },
  { label: 'Ch 8 map', value: 0x28 },
  { label: 'Ch 8 map changes', value: 0x29 },
  { label: 'Ch 8 event data', value: 0x2A },
  { label: 'Ch 9 Eir. map', value: 0x2B },
  { label: 'Ch 9 Eir. map changes', value: 0x2C },
  { label: 'Ch 9 Eir. Events', value: 0x2D },
  { label: 'Object type 4', value: 0x2E },
  { label: 'Map palette 4', value: 0x2F },
  { label: 'Tile configuration 4', value: 0x30 },
  { label: 'Ch 10 Eir. Map', value: 0x31 },
  { label: 'Ch 10 Eir. Map changes', value: 0x32 },
  { label: 'Ch 10 Eir. Events', value: 0x33 },
  { label: 'Map palette 5', value: 0x34 },
  { label: 'Ch 12 Eir. Map', value: 0x35 },
  { label: 'Ch 12 Eir. map changes', value: 0x36 },
  { label: 'Ch 12 Eir. event data', value: 0x37 },
  { label: 'Map palette 6', value: 0x38 },
  { label: 'Ch 13 Eir. Map', value: 0x39 },
  { label: 'Ch 13 Eir. Map changes', value: 0x3A },
  { label: 'Ch 13 Eir. Events (3B)', value: 0x3B },
  { label: 'Object type 5', value: 0x3C },
  { label: 'Map palette 7', value: 0x3D },
  { label: 'Tile configuration 5', value: 0x3E },
  { label: 'Ch 14 Eir. Map', value: 0x3F },
  { label: 'Ch 14 Eir. Map changes', value: 0x40 },
  { label: 'Ch 14 Eir. Events', value: 0x41 },
  { label: 'Object type 6', value: 0x42 },
  { label: 'Map palette 8', value: 0x43 },
  { label: 'Tile configuration 6', value: 0x44 },
  { label: 'Ch 15 map', value: 0x45 },
  { label: 'Ch 15 Map changes', value: 0x46 },
  { label: 'Ch 15 Eir. events', value: 0x47 },
  { label: 'Map palette 9', value: 0x48 },
  { label: 'Ch 16 Map', value: 0x49 },
  { label: 'Ch 16 Map changes', value: 0x4A },
  { label: 'Ch 16 Eir events', value: 0x4B },
  { label: 'Map palette 10', value: 0x4C },
  { label: 'Ch 17 Map', value: 0x4D },
  { label: 'Ch 17 Map changes', value: 0x4E },
  { label: 'Ch 17 Eir. Events', value: 0x4F },
  { label: 'Object type 7', value: 0x50 },
  { label: 'Map palette 11', value: 0x51 },
  { label: 'Tile configuration 7', value: 0x52 },
  { label: 'Ch 18 Map', value: 0x53 },
  { label: 'Tile animations 4', value: 0x54 },
  { label: 'Ch 18 Map changes', value: 0x55 },
  { label: 'Ch 18 Eir. Events', value: 0x56 },
  { label: 'Map palette 12', value: 0x57 },
  { label: 'Ch 19 Map', value: 0x58 },
  { label: 'Ch 19 Map changes', value: 0x59 },
  { label: 'Ch 19 Eir. Events', value: 0x5A },
  { label: 'Map palette 13', value: 0x5B },
  { label: 'Ch 20 Map', value: 0x5C },
  { label: 'Ch 20 Map changes', value: 0x5D },
  { label: 'Ch 20 Eir. Events', value: 0x5E },
  { label: 'Object type 8', value: 0x5F },
  { label: 'Map palette 14', value: 0x60 },
  { label: 'Tile configuration 8', value: 0x61 },
  { label: 'Final Chapter Map 1', value: 0x62 },
  { label: 'Final Chapter Map 1 changes', value: 0x63 },
  { label: 'Final Eir. events 1', value: 0x64 },
  { label: 'Final Chapter Map 2', value: 0x65 },
  { label: 'Final Chapter Map 2 changes', value: 0x66 },
  { label: 'Final Eirika events 2', value: 0x67 },
  { label: 'Map palette 15', value: 0x68 },
  { label: 'Ch 9 Eph map', value: 0x69 },
  { label: 'Ch 9 Eph Map changes', value: 0x6A },
  { label: 'Ch 9 events', value: 0x6B },
  { label: 'Object type 9', value: 0x6C },
  { label: 'Map palette 15', value: 0x6D },
  { label: 'Tile configuration 9', value: 0x6E },
  { label: 'Ch 10 Ephraim map', value: 0x6F },
  { label: 'Ch 10 Ephraim map changes', value: 0x70 },
  { label: 'Ch 10 Ephraim events', value: 0x71 },
  { label: 'Map palette 16', value: 0x72 },
  { label: 'Ch 12 Ephraim map', value: 0x73 },
  { label: 'Ch 12 Ephraim map changes', value: 0x74 },
  { label: 'Ch 12 Ephraim events', value: 0x75 },
  { label: 'Ch 13 Ephraim map', value: 0x76 },
  { label: 'Ch 13 Ephraim map changes', value: 0x77 },
  { label: 'Ch 13 Ephraim event data', value: 0x78 },
  { label: 'Object type 10', value: 0x79 },
  { label: 'Map palette 17', value: 0x7A },
  { label: 'Tile configuration 10', value: 0x7B },
  { label: 'Ch 14 Ephraim map', value: 0x7C },
  { label: 'Tile animations 5', value: 0x7D },
  { label: 'Ch 14 Ephraim map changes', value: 0x7E },
  { label: 'Ch 14 Ephraim event data', value: 0x7F },
  { label: 'Ch 15 Ephraim event data', value: 0x80 },
  { label: 'Ch 16 Ephraim event data', value: 0x81 },
  { label: 'Ch 17 Ephraim event data', value: 0x82 },
  { label: 'Ch 18 Ephraim event data', value: 0x83 },
  { label: 'Ch 19 Ephraim event data', value: 0x84 },
  { label: 'Ch 20 Ephraim event data', value: 0x85 },
  { label: 'Final Ephraim events 1', value: 0x86 },
  { label: 'Final Ephraim events 2', value: 0x87 },
  { label: 'Tower of Valni Object type', value: 0x88 },
  { label: 'Tower of Valni map palette', value: 0x89 },
  { label: 'Tower of Valni Tile configuration', value: 0x8A },
  { label: 'Tower of Valni 1 Map', value: 0x8B },
  { label: 'Tower of Valni 1 Map changes', value: 0X8C },
  { label: 'Tower of Valni 1 events', value: 0x8D },
  { label: 'Tower of Valni 2 map', value: 0x8E },
  { label: 'Tower of Valni 2 map changes', value: 0x8F },
  { label: 'Tower of Valni 2 events', value: 0x90 },
  { label: 'Tower of Valni 3 map', value: 0x91 },
  { label: 'Tower of Valni 3 map changes', value: 0x92 },
  { label: 'Tower of Valni 3 events', value: 0x93 },
  { label: 'Tower of Valni 4 map', value: 0x94 },
  { label: 'Tower of Valni 4 map changes', value: 0x95 },
  { label: 'Tower of Valni 4 events', value: 0x96 },
  { label: 'Tower of Valni 5 map', value: 0x97 },
  { label: 'Tower of Valni 5 map changes', value: 0x98 },
  { label: 'Tower of Valni 5 events', value: 0x99 },
  { label: 'Tower of Valni 6 map', value: 0x9A },
  { label: 'Tower of Valni 6 map changes', value: 0x9B },
  { label: 'Tower of Valni 6 events', value: 0x9C },
  { label: 'Tower of Valni 7 map', value: 0x9D },
  { label: 'Tower of Valni 7 map changes', value: 0x9E },
  { label: 'Tower of Valni 7 events', value: 0x9F },
  { label: 'Tower of Valni 8 map', value: 0xA0 },
  { label: 'Tower of Valni 8 map changes', value: 0xA1 },
  { label: 'Tower of Valni 8 events', value: 0xA2 },
  { label: 'Lagdou ruins palette', value: 0xA3 },
  { label: 'Lagdou ruins 1 Map', value: 0xA4 },
  { label: 'Lagdou ruins 1 Map changes', value: 0xA5 },
  { label: 'Lagdou ruins 1 Event', value: 0xA6 },
  { label: 'Lagdou ruins 2 Map', value: 0xA7 },
  { label: 'Lagdou ruins 2 Map changes', value: 0xA8 },
  { label: 'Lagdou ruins 2 Event', value: 0xA9 },
  { label: 'Lagdou ruins 3 Map', value: 0xAA },
  { label: 'Lagdou ruins 3 Map changes', value: 0xAB },
  { label: 'Lagdou ruins 3 Event', value: 0xAC },
  { label: 'Lagdou ruins 4 Map', value: 0xAD },
  { label: 'Lagdou ruins 4 Map changes', value: 0xAE },
  { label: 'Lagdou ruins 4 Event', value: 0xAF },
  { label: 'Lagdou ruins 5 Map', value: 0xB0 },
  { label: 'Lagdou ruins 5 Map changes', value: 0xB1 },
  { label: 'Lagdou ruins 5 Event', value: 0xB2 },
  { label: 'Lagdou ruins 6 Map', value: 0xB3 },
  { label: 'Lagdou ruins 6 Map changes', value: 0xB4 },
  { label: 'Lagdou ruins 6 Event', value: 0xB5 },
  { label: 'Lagdou ruins 7 Map', value: 0xB6 },
  { label: 'Lagdou ruins 7 Map changes', value: 0xB7 },
  { label: 'Lagdou ruins 7 Event', value: 0xB8 },
  { label: 'Lagdou ruins 8 palette', value: 0xB9 },
  { label: 'Lagdou ruins 8 Map', value: 0xBA },
  { label: 'Lagdou ruins 8 Map changes', value: 0xBB },
  { label: 'Lagdou ruins 8 Event', value: 0xBC },
  { label: 'Lagdou ruins 9 Map', value: 0xBD },
  { label: 'Lagdou ruins 9 Map changes', value: 0xBE },
  { label: 'Lagdou ruins 9 Event', value: 0xBF },
  { label: 'Lagdou ruins 10 Map', value: 0xC0 },
  { label: 'Lagdou ruins 10 Map changes', value: 0xC1 },
  { label: 'Lagdou ruins 10 Event', value: 0xC2 },
  { label: 'Lords split map', value: 0xC3 },
  { label: 'Lords split map changes', value: 0xC4 },
  { label: 'Lords split events', value: 0xC5 },
  { label: 'Melkaen Coast map', value: 0xC6 },
  { label: 'Melkaen Coast map changes', value: 0xC7 },
  { label: 'Melkaen Coast event', value: 0xC8 },
  { label: 'Link arena map C9', value: 0xC9 },
  { label: 'An interesting map...', value: 0xCA },
  { label: 'An interesting map events...', value: 0xCB },
  { label: 'Debug map', value: 0xCC },
  { label: 'Debug map events', value: 0xCD },
  { label: 'Map palette', value: 0xCE },
  { label: 'Ch 11 Eirika map', value: 0xCF },
  { label: 'Ch 11 Eirika map changes', value: 0xD0 },
  { label: 'Ch 11 Eirika events', value: 0xD1 },
  { label: 'Ch 11 Ephraim map', value: 0xD2 },
  { label: 'Ch 11 Ephraim tile animations', value: 0xD3 },
  { label: 'Ch 11 Ephraim map changes', value: 0xD4 },
  { label: 'Ch 11 Ephraim events', value: 0xD5 },
  { label: 'Grado castle map', value: 0xD6 },
  { label: 'Renais castle map', value: 0xD7 },
  { label: 'Caer Pelyn map', value: 0xD8 },
  { label: 'Renais throne map', value: 0xD9 },
  { label: 'Renais throne map changes', value: 0xDA },
  { label: 'Renais audience map', value: 0xDB },
  { label: 'Renval gate map', value: 0xDC },
  { label: 'Grado borders map', value: 0xDD },
  { label: 'Grado prison map', value: 0xDE },
  { label: 'Grado prison map changes', value: 0xDF },
  { label: 'Grado shrine map (past)', value: 0xE0 },
  { label: 'Grado shrine map changes (past)', value: 0xE1 },
  { label: 'Renais shrine map', value: 0xE2 },
  { label: 'Renais shrine map changes', value: 0xE3 },
  { label: 'Some path map', value: 0xE4 },
  { label: 'Some building map', value: 0xE5 },
  { label: 'Another shrine palette', value: 0xE6 },
  { label: 'Another shrine map', value: 0xE7 },
  { label: 'Another path map', value: 0xE8 },
  { label: 'Grado shrine map (present)', value: 0xE9 },
  { label: 'Ch 5 town palette (past)', value: 0xEA },
  { label: 'Ch 5 town map (past)', value: 0xEB },
];

export const BattlePreparations = [
  { label: 'Off', value: 0x00 },
  { label: 'On', value: 0x01 },
];

export const WeatherConditions = [
  { label: 'Clear', value: 0x00 },
  { label: 'Flurries', value: 0x01 },
  { label: 'Blizzard', value: 0x02 },
  { label: 'Blue Gradient (from FE6 Dragon chapter)', value: 0x03 },
  { label: 'Rain', value: 0x04 },
  { label: 'Ashes (from FE6 Durandal map)', value: 0x05 },
  { label: 'Sandstorm', value: 0x06 },
  { label: 'Background clouds (from FE6 Aureola map)', value: 0x07 },
];

export const Battletileset = [
  { label: 'Normal', value: 0x00 },
  { label: 'Lava cave', value: 0x02 },
  { label: '0x04', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: 'City?', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: '0x08', value: 0x08 },
  { label: 'Desert?', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: 'Jehanna Hall?', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: 'Lagdou Ruins', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: '0x10', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: 'Mountains?', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
];

export const MusicList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'The Valiant', value: 0x01 },
  { label: 'Main Theme', value: 0x02 },
  { label: 'Prologue', value: 0x03 },
  { label: 'The Beginning', value: 0x04 },
  { label: 'Treasured Memories', value: 0x05 },
  { label: 'Grim Journey', value: 0x06 },
  { label: 'Ties of Friendship', value: 0x07 },
  { label: 'Ray of Hope', value: 0x08 },
  { label: 'Distant Roads', value: 0x09 },
  { label: 'Rise Above', value: 0x0A },
  { label: 'Follow Me!', value: 0x0B },
  { label: 'Determination', value: 0x0C },
  { label: 'Truth, Despair, and Hope', value: 0x0D },
  { label: 'Land of Promise', value: 0x0E },
  { label: 'Binding Vow', value: 0x0F },
  { label: 'Grasping at Victory', value: 0x10 },
  { label: 'Shadows Approach', value: 0x11 },
  { label: 'Confront the Past', value: 0x12 },
  { label: 'Shadow of the Enemy', value: 0x13 },
  { label: 'Assault', value: 0x14 },
  { label: 'From the Darkness', value: 0x15 },
  { label: 'Twisted Shadows A', value: 0x16 },
  { label: 'Twisted Shadows B', value: 0x17 },
  { label: 'Envoy from the Dark', value: 0x18 },
  { label: 'Attack', value: 0x19 },
  { label: 'Defense', value: 0x1A },
  { label: 'The Battle Must Be Won', value: 0x1B },
  { label: 'Powerful Foe', value: 0x1C },
  { label: 'The Prince\'s Despair', value: 0x1D },
  { label: 'Return of the Demon King', value: 0x1E },
  { label: 'Sacred Strength', value: 0x1F },
  { label: 'Tethys', value: 0x20 },
  { label: 'Healing', value: 0x21 },
  { label: 'Curing', value: 0x22 },
  { label: 'To a Higher Place', value: 0x23 },
  { label: 'Advance', value: 0x24 },
  { label: 'Tension', value: 0x25 },
  { label: 'Raid!', value: 0x26 },
  { label: 'Reunion', value: 0x27 },
  { label: 'Indignation', value: 0x28 },
  { label: 'Sorrow', value: 0x29 },
  { label: 'Laughter', value: 0x2A },
  { label: 'Legacy', value: 0x2B },
  { label: 'Lyon', value: 0x2C },
  { label: 'Lost Heart', value: 0x2D },
  { label: 'Solve the Riddle', value: 0x2E },
  { label: 'Lights in the Dark', value: 0x2F },
  { label: 'Comrades', value: 0x30 },
  { label: 'Victory', value: 0x31 },
  { label: 'Into the Shadow of Victory', value: 0x32 },
  { label: 'Main Theme (Reprise)', value: 0x33 },
  { label: 'Combat Preparation', value: 0x34 },
  { label: 'Shops', value: 0x35 },
  { label: 'Armories', value: 0x36 },
  { label: 'Bonds', value: 0x37 },
  { label: 'Colosseum Entrance', value: 0x38 },
  { label: 'In the Colosseum', value: 0x39 },
  { label: 'Colosseum Victory', value: 0x3A },
  { label: 'Colosseum Defeat', value: 0x3B },
  { label: 'Victory Song A', value: 0x3C },
  { label: 'Victory Song B', value: 0x3D },
  { label: 'Game Over', value: 0x3E },
  { label: 'In Sorrow\'s Shroud', value: 0x3F },
  { label: 'Records', value: 0x40 },
  { label: 'Victory and the Future', value: 0x41 },
  { label: 'Fly with the Breeze', value: 0x42 },
  { label: 'Fire Emblem Theme (no intro)', value: 0x43 },
  { label: 'Lyon (Organ Arrangement)', value: 0x44 },
  { label: 'The Final Battle', value: 0x45 },
  { label: 'Epilogue', value: 0x46 },
  { label: 'Windy day', value: 0x47 },
  { label: 'Windy day with birds', value: 0x48 },
  { label: 'Lava boiling', value: 0x49 },
  { label: 'Nighttime', value: 0x4A },
  { label: 'Water flowing', value: 0x4B },
  { label: 'Birds chirping', value: 0x4C },
  { label: 'Soft swooshy sound', value: 0x4D },
  { label: 'Wind gusts', value: 0x4E },
  { label: 'Wind gust stopping', value: 0x4F },
  { label: 'Blizzard', value: 0x50 },
  { label: 'Legendary weapon theme of FE', value: 0x51 },
  { label: 'Outside with birds softly chirping', value: 0x52 },
  { label: 'River', value: 0x53 },
  { label: 'Comrades (again?)', value: 0x54 },
  { label: 'Return of the Demon King (without intro)', value: 0x55 },
  { label: 'Lyon?', value: 0x56 },
  { label: 'Nothing', value: 0x57 },
  { label: 'Nothing', value: 0x58 },
  { label: 'Nothing', value: 0x59 },
  { label: 'Item Get!', value: 0x5A },
  { label: 'Level Up!', value: 0x5B },
  { label: 'Weapon broke', value: 0x5C },
  { label: 'Nothing', value: 0x5D },
  { label: 'Weapon broke', value: 0x5E },
  { label: 'Nothing', value: 0x5F },
  { label: '??? 8-bit sound', value: 0x60 },
  { label: '??? 8-bit sound', value: 0x61 },
  { label: 'Nothing', value: 0x62 },
  { label: 'Nothing', value: 0x63 },
  { label: 'Nothing', value: 0x64 },
  { label: 'Cursor', value: 0x65 },
  { label: 'Menu Cursor', value: 0x66 },
  { label: 'Menu Cursor 2', value: 0x67 },
];

export const Worldmapprologue = [
  { label: 'None', value: 0X00 },
  { label: 'Prologue', value: 0x01 },
  { label: 'Ch 1', value: 0x02 },
  { label: 'Ch 2', value: 0x03 },
  { label: 'Ch 3', value: 0x04 },
  { label: 'Ch 4/Zaha Woods', value: 0x05 },
  { label: 'Ch 5x', value: 0x06 },
  { label: 'Ch 5', value: 0x07 },
  { label: 'Ch 6/Adlas Plains', value: 0x08 },
  { label: 'Ch 7', value: 0x09 },
  { label: 'Ch 8', value: 0x0A },
  { label: 'Ch 9 Eirika', value: 0x0B },
  { label: 'Ch 10 Eirika/Teras Plateau', value: 0x0C },
  { label: 'Ch 12 Eirika', value: 0x0D },
  { label: 'Ch 13 Eirika', value: 0x0E },
  { label: 'Ch 14 Eirika', value: 0x0F },
  { label: 'Ch 15 Eirika', value: 0x10 },
  { label: 'Ch 16 Eirika', value: 0x11 },
  { label: 'Ch 17 Eirika/Narube River', value: 0x12 },
  { label: 'Ch 18 Eirika/Neleras Peak', value: 0x13 },
  { label: 'Ch 19 Eirika', value: 0x14 },
  { label: 'Ch 20 Eirika', value: 0x15 },
  { label: 'Final Ch 1 Eirika', value: 0x16 },
  { label: 'Final Ch 2 Erika', value: 0x17 },
  { label: 'Ch 9 Ephraim', value: 0x18 },
  { label: 'Ch 10 Ephraim/Bethroen', value: 0x19 },
  { label: 'Ch 12 Ephraim', value: 0x1A },
  { label: 'Ch 13 Ephraim/Za\'abadul Marsh', value: 0x1B },
  { label: 'Ch 14 Ephraim', value: 0x1C },
  { label: 'Ch 15 Ephraim', value: 0x1D },
  { label: 'Ch 16 Ephraim', value: 0x1E },
  { label: 'Ch 17 Ephraim/Narube River', value: 0x1F },
  { label: 'Ch 18 Ephraim/Neleras Peak', value: 0x20 },
  { label: 'Ch 19 Ephraim', value: 0x21 },
  { label: 'Ch 20 Ephraim', value: 0x22 },
  { label: 'Final Ch 1 Ephraim', value: 0x23 },
  { label: 'Final Ch 2 Ephraim', value: 0x24 },
  { label: 'Tower of Valni 1', value: 0x25 },
  { label: 'Tower of Valni 2', value: 0x26 },
  { label: 'Tower of Valni 3', value: 0x27 },
  { label: 'Tower of Valni 4', value: 0x28 },
  { label: 'Tower of Valni 5', value: 0x29 },
  { label: 'Tower of Valni 6', value: 0x2A },
  { label: 'Tower of Valni 7', value: 0x2B },
  { label: 'Tower of Valni 8', value: 0x2C },
  { label: 'Lagdou Ruins 1', value: 0x2D },
  { label: 'Lagdou Ruins 2', value: 0x2E },
  { label: 'Lagdou Ruins 3', value: 0x2F },
  { label: 'Lagdou Ruins 4', value: 0x30 },
  { label: 'Lagdou Ruins 5', value: 0x31 },
  { label: 'Lagdou Ruins 6', value: 0x32 },
  { label: 'Lagdou Ruins 7', value: 0x33 },
  { label: 'Lagdou Ruins 8', value: 0x34 },
  { label: 'Lagdou Ruins 9', value: 0x35 },
  { label: 'Lagdou Ruins 10', value: 0x36 },
  { label: 'Lords split up (glitchy map)', value: 0x37 },
  { label: 'Melkaen Coast', value: 0X38 },
  { label: 'Ch 11 Eirika', value: 0X39 },
  { label: 'Ch 11 Ephraim', value: 0X3A },
];

export const Fadeout = [
  { label: 'Fade to map', value: 0x00 },
  { label: 'Fade to black', value: 0x01 },
];

export const GoalWindow = [
  { label: 'None (Seize goals)', value: 0x00 },
  { label: 'Number of enemies', value: 0x01 },
  { label: 'Turn number', value: 0x02 },
  { label: 'None (Defeat Boss goals)', value: 0x03 },
  { label: 'None (Special goals)', value: 0x04 },
];

export const CharacterList = [
  { label: '(No one/Not referenced)', value: 0x00 },
  { label: 'Eirika', value: 0x01 },
  { label: 'Seth', value: 0x02 },
  { label: 'Gilliam', value: 0x03 },
  { label: 'Frantz', value: 0x04 },
  { label: 'Moulder', value: 0x05 },
  { label: 'Vanessa', value: 0x06 },
  { label: 'Ross', value: 0x07 },
  { label: 'Neimi', value: 0x08 },
  { label: 'Colm', value: 0x09 },
  { label: 'Garcia', value: 0x0A },
  { label: 'Innes', value: 0x0B },
  { label: 'Lute', value: 0x0C },
  { label: 'Natasha', value: 0x0D },
  { label: 'Cougar', value: 0x0E },
  { label: 'Ephraim', value: 0x0F },
  { label: 'Forde', value: 0x10 },
  { label: 'Kyle', value: 0x11 },
  { label: 'Amelia', value: 0x12 },
  { label: 'Artur', value: 0x13 },
  { label: 'Gerik', value: 0x14 },
  { label: 'Tethys', value: 0x15 },
  { label: 'Marisa', value: 0x16 },
  { label: 'Saleh', value: 0x17 },
  { label: 'Ewan', value: 0x18 },
  { label: 'L\'Arachel', value: 0x19 },
  { label: 'Dozla', value: 0x1A },
  { label: '-', value: 0x1B },
  { label: 'Rennac', value: 0x1C },
  { label: 'Duessel', value: 0x1D },
  { label: 'Myrrh', value: 0x1E },
  { label: 'Knoll', value: 0x1F },
  { label: 'Joshua', value: 0x20 },
  { label: 'Syrene', value: 0x21 },
  { label: 'Tana', value: 0x22 },
  { label: 'Lyon', value: 0x23 },
  { label: 'Orson', value: 0x24 },
  { label: 'Glen', value: 0x25 },
  { label: 'Selena', value: 0x26 },
  { label: 'Valter', value: 0x27 },
  { label: 'Riev', value: 0x28 },
  { label: 'Caellach', value: 0x29 },
  { label: 'Fado', value: 0x2A },
  { label: 'Ismaire', value: 0x2B },
  { label: 'Hayden', value: 0x2C },
  { label: '-', value: 0x2D },
  { label: '-', value: 0x2E },
  { label: '-', value: 0x2F },
  { label: '-', value: 0x30 },
  { label: '-', value: 0x31 },
  { label: '-', value: 0x32 },
  { label: '-', value: 0x33 },
  { label: '-', value: 0x34 },
  { label: '-', value: 0x35 },
  { label: '-', value: 0x36 },
  { label: '-', value: 0x37 },
  { label: '-', value: 0x38 },
  { label: '-', value: 0x39 },
  { label: '-', value: 0x3A },
  { label: 'Leon\'s Summon', value: 0x3B },
  { label: '-', value: 0x3C },
  { label: '-', value: 0x3D },
  { label: 'Knoll\'s Summon', value: 0x3E },
  { label: 'Yuan\'s Summon', value: 0x3F },
  { label: 'Lyon (Ch 17)', value: 0x40 },
  { label: 'Morva (Ch 20)', value: 0x41 },
  { label: 'Orson (Ch 5x)', value: 0x42 },
  { label: 'Valter (Ch 15)', value: 0x43 },
  { label: 'Selena (Ch 10B & 13B)', value: 0x44 },
  { label: 'Valter (Prologue)', value: 0x45 },
  { label: 'Breguet (Ch 1)', value: 0x46 },
  { label: 'Bone (Ch 2)', value: 0x47 },
  { label: 'Bazba (Ch 3)', value: 0x48 },
  { label: 'Mummy (Ch 4)', value: 0x49 },
  { label: 'Saar (Ch 5)', value: 0x4A },
  { label: 'Novala (Ch 6)', value: 0x4B },
  { label: 'Murray (Ch 7)', value: 0x4C },
  { label: 'Tirado (Ch 8)', value: 0x4D },
  { label: 'Binks (Ch 9A)', value: 0x4E },
  { label: 'Pablo (Ch 10A)', value: 0x4F },
  { label: 'Macdaire (Ch 12A)', value: 0x50 },
  { label: 'Aias (Ch 13A)', value: 0x51 },
  { label: 'Carlyle (Ch 14A)', value: 0x52 },
  { label: 'Caellach (Ch 15)', value: 0x53 },
  { label: 'Pablo (Ch 13A)', value: 0x54 },
  { label: '-', value: 0x55 },
  { label: 'Gorgon (Ch 18)', value: 0x56 },
  { label: 'Riev (Ch 19 & 20)', value: 0x57 },
  { label: '-', value: 0x58 },
  { label: '-', value: 0x59 },
  { label: 'Gheb (Ch 9B)', value: 0x5A },
  { label: 'Beran (Ch 10B)', value: 0x5B },
  { label: 'Cyclops (Ch 12B)', value: 0x5C },
  { label: 'Hellbone (Ch 11A)', value: 0x5D },
  { label: 'Death Gargoyle (Ch 11B)', value: 0x5E },
  { label: 'Mummy', value: 0x5F },
  { label: '-', value: 0x60 },
  { label: '-', value: 0x61 },
  { label: '-', value: 0x62 },
  { label: '-', value: 0x63 },
  { label: '-', value: 0x64 },
  { label: '-', value: 0x65 },
  { label: 'Mountain Thief', value: 0x66 },
  { label: '-', value: 0x67 },
  { label: 'O\'Neill (Prologue)', value: 0x68 },
  { label: 'Glen (Cutscene)', value: 0x69 },
  { label: 'Zonta (Ch 5x)', value: 0x6A },
  { label: 'Vigarde (Ch 14B)', value: 0x6B },
  { label: 'Lyon (Ch Final)', value: 0x6C },
  { label: 'Orson (Ch 16)', value: 0x6D },
  { label: '-', value: 0x6E },
  { label: '-', value: 0x6F },
  { label: '-', value: 0x70 },
  { label: '-', value: 0x71 },
  { label: '-', value: 0x72 },
  { label: '-', value: 0x73 },
  { label: '-', value: 0x74 },
  { label: '-', value: 0x75 },
  { label: '-', value: 0x76 },
  { label: '-', value: 0x77 },
  { label: '-', value: 0x78 },
  { label: '-', value: 0x79 },
  { label: '-', value: 0x7A },
  { label: '-', value: 0x7B },
  { label: '-', value: 0x7C },
  { label: '-', value: 0x7D },
  { label: '-', value: 0x7E },
  { label: '-', value: 0x7F },
  { label: '-', value: 0x80 },
  { label: '-', value: 0x81 },
  { label: '-', value: 0x82 },
  { label: '-', value: 0x83 },
  { label: '-', value: 0x84 },
  { label: '-', value: 0x85 },
  { label: '-', value: 0x86 },
  { label: '-', value: 0x87 },
  { label: '-', value: 0x88 },
  { label: '-', value: 0x89 },
  { label: '-', value: 0x8A },
  { label: '-', value: 0x8B },
  { label: '-', value: 0x8C },
  { label: '-', value: 0x8D },
  { label: '-', value: 0x8E },
  { label: '-', value: 0x8F },
  { label: '-', value: 0x90 },
  { label: '-', value: 0x91 },
  { label: '-', value: 0x92 },
  { label: '-', value: 0x93 },
  { label: '-', value: 0x94 },
  { label: '-', value: 0x95 },
  { label: '-', value: 0x96 },
  { label: '-', value: 0x97 },
  { label: '-', value: 0x98 },
  { label: '-', value: 0x99 },
  { label: '-', value: 0x9A },
  { label: '-', value: 0x9B },
  { label: '-', value: 0x9C },
  { label: '-', value: 0x9D },
  { label: '-', value: 0x9E },
  { label: '-', value: 0x9F },
  { label: '-', value: 0xA0 },
  { label: '-', value: 0xA1 },
  { label: '-', value: 0xA2 },
  { label: '-', value: 0xA3 },
  { label: '-', value: 0xA4 },
  { label: '-', value: 0xA5 },
  { label: '-', value: 0xA6 },
  { label: '-', value: 0xA7 },
  { label: '-', value: 0xA8 },
  { label: '-', value: 0xA9 },
  { label: '-', value: 0xAA },
  { label: '-', value: 0xAB },
  { label: '-', value: 0xAC },
  { label: '-', value: 0xAD },
  { label: '-', value: 0xAE },
  { label: '-', value: 0xAF },
  { label: '-', value: 0xB0 },
  { label: '-', value: 0xB1 },
  { label: '-', value: 0xB2 },
  { label: '-', value: 0xB3 },
  { label: '-', value: 0xB4 },
  { label: '-', value: 0xB5 },
  { label: '-', value: 0xB6 },
  { label: '-', value: 0xB7 },
  { label: '-', value: 0xB8 },
  { label: '-', value: 0xB9 },
  { label: '-', value: 0xBA },
  { label: '-', value: 0xBB },
  { label: '-', value: 0xBC },
  { label: '-', value: 0xBD },
  { label: 'Demon King', value: 0xBE },
  { label: '-', value: 0xBF },
  { label: 'Frelian', value: 0xC0 },
  { label: 'Frelian', value: 0xC1 },
  { label: '-', value: 0xC2 },
  { label: '-', value: 0xC3 },
  { label: '-', value: 0xC4 },
  { label: 'Fado (Renais)', value: 0xC5 },
  { label: '-', value: 0xC6 },
  { label: 'Hayden (Frelia)', value: 0xC7 },
  { label: 'Mansel (Rausten)', value: 0xC8 },
  { label: 'Klimt (Carcino)', value: 0xC9 },
  { label: 'Dara (Caer Pelyn)', value: 0xCA },
  { label: 'Ismaire (Jehanna)', value: 0xCB },
  { label: 'Pegasus Messenger', value: 0xCC },
  { label: 'Rausten Knight', value: 0xCD },
  { label: 'Rausten Knight', value: 0xCE },
  { label: '(Untested starting and beyond this point)', value: 0xCF },
  { label: '-', value: 0xD0 },
  { label: '-', value: 0xD1 },
  { label: '-', value: 0xD2 },
  { label: '-', value: 0xD3 },
  { label: '-', value: 0xD4 },
  { label: '-', value: 0xD5 },
  { label: '-', value: 0xD6 },
  { label: '-', value: 0xD7 },
  { label: '-', value: 0xD8 },
  { label: '-', value: 0xD9 },
  { label: '-', value: 0xDA },
  { label: '-', value: 0xDB },
  { label: '-', value: 0xDC },
  { label: '-', value: 0xDD },
  { label: '-', value: 0xDE },
  { label: '-', value: 0xDF },
  { label: '-', value: 0xE0 },
  { label: '-', value: 0xE1 },
  { label: '-', value: 0xE2 },
  { label: '-', value: 0xE3 },
  { label: '-', value: 0xE4 },
  { label: '-', value: 0xE5 },
  { label: '-', value: 0xE6 },
  { label: '-', value: 0xE7 },
  { label: '-', value: 0xE8 },
  { label: '-', value: 0xE9 },
  { label: '-', value: 0xEA },
  { label: '-', value: 0xEB },
  { label: '-', value: 0xEC },
  { label: '-', value: 0xED },
  { label: '-', value: 0xEE },
  { label: '-', value: 0xEF },
  { label: '-', value: 0xF0 },
  { label: '-', value: 0xF1 },
  { label: '-', value: 0xF2 },
  { label: '-', value: 0xF3 },
  { label: 'River Folk Child (F)', value: 0xF4 },
  { label: 'River Folk (F)', value: 0xF5 },
  { label: 'River Folk', value: 0xF6 },
  { label: 'River Folk (F)', value: 0xF7 },
  { label: 'River Folk Child', value: 0xF8 },
  { label: 'Renais Civilian Child (F)', value: 0xF9 },
  { label: 'Renais Civilian', value: 0xFA },
  { label: 'Renais Civilian (F)', value: 0xFB },
  { label: 'Old Civilian', value: 0xFC },
  { label: 'Enemy', value: 0xFD },
  { label: 'Wall', value: 0xFE },
  { label: 'Snag', value: 0xFF },
];
