export const FE3CharacterList = [
  { label: 'Marth', value: 0 },
  { label: 'Caeda', value: 1 },
  { label: 'Jagen', value: 2 },
  { label: 'Cain', value: 3 },
  { label: 'Abel', value: 4 },
  { label: 'Draug', value: 5 },
  { label: 'Gordin', value: 6 },
  { label: 'Rickard', value: 7 },
  { label: 'Wrys (unused?)', value: 8 },
  { label: 'Bord', value: 9 },
  { label: 'Cord', value: 10 },
  { label: 'Barst', value: 11 },
  { label: 'Castor', value: 12 },
  { label: 'Ogma', value: 13 },
  { label: 'Darros', value: 14 },
  { label: 'Julian', value: 15 },
  { label: 'Lena', value: 16 },
  { label: 'Merric', value: 17 },
  { label: 'Navarre', value: 18 },
  { label: 'Hardin', value: 19 },
  { label: 'Wolf', value: 20 },
  { label: 'Sedgar', value: 21 },
  { label: 'Roshea', value: 22 },
  { label: 'Vyland', value: 23 },
  { label: 'Bantu', value: 24 },
  { label: 'Caesar', value: 25 },
  { label: 'Radd', value: 26 },
  { label: 'Midia', value: 27 },
  { label: 'Catria', value: 28 },
  { label: 'Maria', value: 29 },
  { label: 'Minerva', value: 30 },
  { label: 'Linde', value: 31 },
  { label: 'Jeorge', value: 32 },
  { label: 'Dolph', value: 33 },
  { label: 'Macellan', value: 34 },
  { label: 'Tomas', value: 35 },
  { label: 'Boah', value: 36 },
  { label: 'Arran', value: 37 },
  { label: 'Samson', value: 38 },
  { label: 'Beck', value: 39 },
  { label: 'Xane', value: 40 },
  { label: 'Wendell', value: 41 },
  { label: 'Est', value: 42 },
  { label: 'Astram', value: 43 },
  { label: 'Matthis', value: 44 },
  { label: 'Roger', value: 45 },
  { label: 'Jake', value: 46 },
  { label: 'Palla', value: 47 },
  { label: 'Tiki', value: 48 },
  { label: 'Lorenz', value: 49 },
  { label: 'Elice', value: 50 },
  { label: 'Gotoh', value: 51 },
  { label: 'Rickard (Enemy)', value: 52 },
  { label: 'Jeorge (Enemy)', value: 53 },
  { label: 'Navarre (Enemy)', value: 54 },
  { label: 'Matthis (Enemy)', value: 55 },
  { label: 'Sheena (Enemy)', value: 56 },
  { label: 'Samson (Enemy)', value: 57 },
  { label: '????', value: 58 },
  { label: '????', value: 59 },
  { label: 'Minerva (Enemy)', value: 60 },
  { label: '????', value: 61 },
  { label: 'Astram (Enemy)', value: 62 },
  { label: 'Palla (Enemy)', value: 63 },
  { label: '????', value: 64 },
  { label: 'Est (Enemy)', value: 65 },
  { label: '????', value: 66 },
  { label: '????', value: 67 },
  { label: '????', value: 68 },
  { label: 'Enemy', value: 69 },
  { label: 'Gharnef', value: 70 },
  { label: 'Boss?', value: 71 },
  { label: 'Boss?', value: 72 },
  { label: 'Michalis', value: 73 },
  { label: 'Boss?', value: 74 },
  { label: 'Enemy', value: 75 },
  { label: 'Enemy', value: 76 },
  { label: 'Enemy', value: 77 },
  { label: 'Enemy', value: 78 },
  { label: 'Enemy', value: 79 },
  { label: 'Enemy', value: 80 },
  { label: 'Enemy', value: 81 },
  { label: 'Enemy', value: 82 },
  { label: 'Enemy', value: 83 },
  { label: 'Enemy', value: 84 },
  { label: 'Enemy', value: 85 },
  { label: 'Enemy', value: 86 },
  { label: 'Enemy', value: 87 },
  { label: 'Enemy', value: 88 },
  { label: 'Enemy', value: 89 },
  { label: 'Boss?', value: 90 },
  { label: 'Boss?', value: 91 },
  { label: 'Enemy', value: 92 },
  { label: 'Enemy', value: 93 },
  { label: 'Enemy', value: 94 },
  { label: 'Enemy', value: 95 },
  { label: 'Enemy', value: 96 },
  { label: 'Enemy', value: 97 },
  { label: 'Enemy', value: 98 },
  { label: 'Enemy', value: 99 },
  { label: 'Enemy', value: 100 },
  { label: 'Enemy', value: 101 },
  { label: 'Enemy', value: 102 },
  { label: 'Enemy', value: 103 },
  { label: 'Enemy', value: 104 },
  { label: 'Enemy', value: 105 },
  { label: 'Enemy', value: 106 },
  { label: 'Camus', value: 107 },
  { label: 'Cecil', value: 108 },
  { label: 'Luke', value: 109 },
  { label: 'Roderick', value: 110 },
  { label: 'Ryan', value: 111 },
  { label: 'Warren', value: 112 },
  { label: 'Enemy', value: 113 },
  { label: 'Enemy', value: 114 },
  { label: 'Yuliya', value: 115 },
  { label: 'Jubelo', value: 116 },
  { label: 'Sirius', value: 117 },
  { label: 'Enemy', value: 118 },
  { label: 'Marisha', value: 119 },
  { label: 'Enemy', value: 120 },
  { label: 'Samuel', value: 121 },
  { label: 'Enemy', value: 122 },
  { label: 'Phina', value: 123 },
  { label: 'Enemy', value: 124 },
  { label: 'Enemy', value: 125 },
  { label: 'Enemy', value: 126 },
  { label: 'Enemy', value: 127 },
  { label: 'Sheena', value: 128 },
  { label: 'Marth (Book 2)', value: 129 },
  { label: 'Arran (Book 2)', value: 130 },
  { label: 'Gordin (Book 2)', value: 131 },
  { label: 'Draug (Book 2)', value: 132 },
  { label: 'Linde (Book 2)', value: 133 },
  { label: 'Matthis (Book 2)', value: 134 },
  { label: 'Julian (Book 2)', value: 135 },
  { label: 'Catria (Book 2)', value: 136 },
  { label: 'Ogma (Book 2)', value: 137 },
  { label: 'Castor (Book 2)', value: 138 },
  { label: 'Rickard (Book 2)', value: 139 },
  { label: 'Jeorge (Book 2)', value: 140 },
  { label: 'Wendell (Book 2)', value: 141 },
  { label: 'Navarre (Book 2)', value: 142 },
  { label: 'Astram (Book 2)', value: 143 },
  { label: 'Caeda (Book 2)', value: 144 },
  { label: 'Cain (Book 2)', value: 145 },
  { label: 'Bantu (Book 2)', value: 146 },
  { label: '????', value: 147 },
  { label: 'Merric (Book 2)', value: 148 },
  { label: 'Arlen', value: 149 },
  { label: 'Minerva (Book 2)', value: 150 },
  { label: 'Xane (Book 2)', value: 151 },
  { label: 'Tiki (Book 2)', value: 152 },
  { label: 'Abel (Book 2)', value: 153 },
  { label: '????', value: 154 },
  { label: 'Samson (Book 2)', value: 155 },
  { label: 'Enemy?', value: 156 },
  { label: 'Enemy?', value: 157 },
  { label: 'Roshea', value: 158 },
  { label: 'Enemy?', value: 159 },
  { label: 'Midia', value: 160 },
  { label: 'Enemy?', value: 161 },
  { label: 'Enemy?', value: 162 },
  { label: 'Enemy?', value: 163 },
  { label: 'Enemy?', value: 164 },
  { label: 'Enemy', value: 165 },
  { label: 'Enemy', value: 166 },
  { label: 'Nyna', value: 167 },
  { label: 'Maria (Book 2)', value: 168 },
  { label: 'Elice (Book 2)', value: 169 },
  { label: 'Lena (Book 2)', value: 170 },
  { label: 'Palla (Book 2)', value: 171 },
];

export const FE3Gender = [
  { label: 'Male', value: 0x00 },
  { label: 'Female', value: 0x01 },
];
