export const FE6SoundRoomDefinitions = [
  { label: '0x00 Fire Emblem Theme', value: 0 },
  { label: '0x01 Deer of the Plains', value: 1 },
  { label: '0x02 Wild Frontier', value: 2 },
  { label: '0x03 Distant Lands', value: 3 },
  { label: '0x04 The Kingdom of Bern', value: 4 },
  { label: '0x05 Dragon Sanctuary', value: 5 },
  { label: '0x06 Legendary Inheritance', value: 6 },
  { label: '0x07 FE Gaiden Enemy Phase', value: 7 },
  { label: '0x08 Messenger from the Darkness', value: 8 },
  { label: '0x09 Beyond the Sky', value: 9 },
  { label: '0x0A One Will', value: 10 },
  { label: '0x0B Beholding Nature\'s Beauty', value: 11 },
  { label: '0x0C Beneath a New Light', value: 12 },
  { label: '0x0D The Path to Greatness', value: 13 },
  { label: '0x0E Scars of the Scouring', value: 14 },
  { label: '0x0F FE Gaiden Player Phase', value: 15 },
  { label: '0x10 Shadow Approaches', value: 16 },
  { label: '0x11 Binding Ties', value: 17 },
  { label: '0x12 Winning Road', value: 18 },
  { label: '0x13 Poem of the Soft Wind', value: 19 },
  { label: '0x14 At the Final Dragon', value: 20 },
  { label: '0x15 Battle for Tomorrow', value: 21 },
  { label: '0x16 In the Name of Bern', value: 22 },
  { label: '0x17 Battle for Whom?', value: 23 },
  { label: '0x18 Priestess in the Dark', value: 24 },
  { label: '0x19 Healing', value: 25 },
  { label: '0x1A Curing', value: 26 },
  { label: '0x1B To the Heights', value: 27 },
  { label: '0x1C I - Campaign', value: 28 },
  { label: '0x1D II - Recapturing the Royal Capital', value: 29 },
  { label: '0x1E III - Invisible Enemy', value: 30 },
  { label: '0x1F IV - Final Chapter', value: 31 },
  { label: '0x20 Prepare to Charge', value: 32 },
  { label: '0x21 An Unexpected Caller', value: 33 },
  { label: '0x22 When the Rush Comes', value: 34 },
  { label: '0x23 Cogs of Fate', value: 35 },
  { label: '0x24 Distant Utopia', value: 36 },
  { label: '0x25 Triumph', value: 37 },
  { label: '0x26 Into the Shadow of Triumph', value: 38 },
  { label: '0x27 The Dark Priestess', value: 39 },
  { label: '0x28 The King of Bern', value: 40 },
  { label: '0x29 Princess of Destiny', value: 41 },
  { label: '0x2A Suspicious', value: 42 },
  { label: '0x2B Dignified', value: 43 },
  { label: '0x2C Melancholic', value: 44 },
  { label: '0x2D Final Farewell', value: 45 },
  { label: '0x2E Going My Way', value: 46 },
  { label: '0x2F Join Us!', value: 47 },
  { label: '0x30 Epilouge', value: 48 },
  { label: '0x31 Battle Results', value: 49 },
  { label: '0x32 After the War', value: 50 },
  { label: '0x33 Game Over', value: 51 },
  { label: '0x34 Shop', value: 52 },
  { label: '0x35 Arena Entrance', value: 53 },
  { label: '0x36 Arena Battle', value: 54 },
  { label: '0x37 Happiness Abounds', value: 55 },
  { label: '0x38 Main Theme Arrangement', value: 56 },
  { label: '0x39 Shocking Truth I', value: 57 },
  { label: '0x3A Shocking Truth II', value: 58 },
  { label: '0x3B Talking', value: 59 },
  { label: '0x3C Captivating Dance', value: 60 },
  { label: '0x3D Prelude - Telling a Legend', value: 61 },
  { label: '0x3E Eternal Wind', value: 62 },
  { label: '0x3F What Came Before', value: 63 },
  { label: '0x40 Attack!', value: 64 },
  { label: '0x41 Revenge!', value: 65 },
];

export default FE6SoundRoomDefinitions;
