export const Itemeditorlist = [
  { label: 'Steel Lance', value: 0 },
  { label: 'Silver Lance', value: 1 },
  { label: 'Javelin', value: 2 },
  { label: 'Holy Lance', value: 3 },
  { label: 'Knight Killer', value: 4 },
  { label: 'Gradius', value: 5 },
  { label: 'Shooting Star', value: 6 },
  { label: 'Sun', value: 7 },
  { label: 'Moonlight', value: 8 },
  { label: 'Steel Sword', value: 9 },
  { label: 'Silver Sword', value: 10 },
  { label: 'Hero Sword', value: 11 },
  { label: 'Darkness Sword', value: 12 },
  { label: 'Thunder Sword', value: 13 },
  { label: 'Holy Sword', value: 14 },
  { label: 'Falchion', value: 15 },
  { label: 'Royal Sword', value: 16 },
  { label: 'Tentacle', value: 17 },
  { label: 'Steel Bow', value: 18 },
  { label: 'Holy Bow', value: 19 },
  { label: 'Silver Bow', value: 20 },
  { label: 'Fire', value: 21 },
  { label: 'Thunder', value: 22 },
  { label: 'Rainarok', value: 23 },
  { label: 'Angel', value: 24 },
  { label: 'Excalibur', value: 25 },
  { label: 'Arrow', value: 26 },
  { label: 'Aura', value: 27 },
  { label: 'Gaia (unused)', value: 28 },
  { label: 'Dora', value: 29 },
  { label: 'Slime', value: 30 },
  { label: 'Death', value: 31 },
  { label: 'Medusa', value: 32 },
  { label: 'Recover', value: 33 },
  { label: 'Reserve', value: 34 },
  { label: 'Messaih', value: 35 },
  { label: 'Eyebeam', value: 36 },
  { label: 'Eyeball', value: 37 },
  { label: 'Recover', value: 38 },
  { label: 'Reblow', value: 39 },
  { label: 'Resire', value: 40 },
  { label: 'Warp', value: 41 },
  { label: 'Reserve', value: 42 },
  { label: 'Illusion', value: 43 },
  { label: 'Dear', value: 44 },
  { label: 'No Name', value: 45 },
  { label: 'Leather Shield', value: 46 },
  { label: 'Steel Shield', value: 47 },
  { label: 'Silver Shield', value: 48 },
  { label: 'Holy Shield', value: 49 },
  { label: 'Magic Seal Shield', value: 50 },
  { label: 'Dragon Shield', value: 51 },
  { label: 'Holy Ring', value: 52 },
  { label: 'Angel Ring', value: 53 },
  { label: 'Speed Ring', value: 54 },
  { label: 'Magic Ring', value: 55 },
  { label: 'Prayer Ring', value: 56 },
];

export const Effective = [
  { label: 'None', value: 0x00 },
  { label: 'Monster', value: 0x01 },
  { label: 'None', value: 0x02 },
  { label: 'Flying', value: 0x03 },
  { label: 'Horse Knight', value: 0x04 },
];
