export const FE6Chapter7LeftArmoryEditorEntries = [
  { label: 'Entry 0', value: 0 },
];

export const ItemList = [
  { label: '- None', value: 0x00 },
  { label: '- Iron Sword', value: 0x01 },
  { label: '- Iron Blade', value: 0x02 },
  { label: '- Steel Sword', value: 0x03 },
  { label: '- Silver Sword', value: 0x04 },
  { label: '- Slim Sword', value: 0x05 },
  { label: '- Poison Sword', value: 0x06 },
  { label: '- Hero Sword', value: 0x07 },
  { label: '- Light Brand', value: 0x08 },
  { label: '- Durandal', value: 0x09 },
  { label: '- Armourslayer', value: 0x0A },
  { label: '- Rapier', value: 0x0B },
  { label: '- Killing Edge', value: 0x0C },
  { label: '- Lancereaver', value: 0x0D },
  { label: '- Wo Dao', value: 0x0E },
  { label: '- Sword of Seals', value: 0x0F },
  { label: '- Iron Lance', value: 0x10 },
  { label: '- Steel Lance', value: 0x11 },
  { label: '- Silver Lance', value: 0x12 },
  { label: '- Slim Lance', value: 0x13 },
  { label: '- Poison Lance', value: 0x14 },
  { label: '- Hero Lance', value: 0x15 },
  { label: '- Javelin', value: 0x16 },
  { label: '- Maltae', value: 0x17 },
  { label: '- Horseslayer', value: 0x18 },
  { label: '- Killer Lance', value: 0x19 },
  { label: '- Axereaver', value: 0x1A },
  { label: '- Iron Axe', value: 0x1B },
  { label: '- Steel Axe', value: 0x1C },
  { label: '- Silver Axe', value: 0x1D },
  { label: '- Poison Axe', value: 0x1E },
  { label: '- Hero Axe', value: 0x1F },
  { label: '- Hand Axe', value: 0x20 },
  { label: '- Armads', value: 0x21 },
  { label: '- Hammer', value: 0x22 },
  { label: '- Killer Axe', value: 0x23 },
  { label: '- Swordreaver', value: 0x24 },
  { label: '- Devil Axe', value: 0x25 },
  { label: '- Halberd', value: 0x26 },
  { label: '- Iron Bow', value: 0x27 },
  { label: '- Steel Bow', value: 0x28 },
  { label: '- Silver Bow', value: 0x29 },
  { label: '- Poison Bow', value: 0x2A },
  { label: '- Killer Bow', value: 0x2B },
  { label: '- Hero Bow', value: 0x2C },
  { label: '- Short Bow', value: 0x2D },
  { label: '- Longbow', value: 0x2E },
  { label: '- Miugre', value: 0x2F },
  { label: '- Ballista', value: 0x30 },
  { label: '- Iron Ballista', value: 0x31 },
  { label: '- Killer Ballista', value: 0x32 },
  { label: '- Fire', value: 0x33 },
  { label: '- Thunder', value: 0x34 },
  { label: '- Fimbulvetr', value: 0x35 },
  { label: '- Elfire', value: 0x36 },
  { label: '- Aircalibur', value: 0x37 },
  { label: '- Fenrir', value: 0x38 },
  { label: '- Bolting', value: 0x39 },
  { label: '- Forblaze', value: 0x3A },
  { label: '- Lightning', value: 0x3B },
  { label: '- Divine', value: 0x3C },
  { label: '- Purge', value: 0x3D },
  { label: '- Aureola', value: 0x3E },
  { label: '- Flux', value: 0x3F },
  { label: '- Nosferatu', value: 0x40 },
  { label: '- Eclipse', value: 0x41 },
  { label: '- Apocalypse', value: 0x42 },
  { label: '- Heal', value: 0x43 },
  { label: '- Mend', value: 0x44 },
  { label: '- Recover', value: 0x45 },
  { label: '- Libro', value: 0x46 },
  { label: '- Reserve', value: 0x47 },
  { label: '- Warp', value: 0x48 },
  { label: '- Rescue', value: 0x49 },
  { label: '- Restore', value: 0x4A },
  { label: '- Silence', value: 0x4B },
  { label: '- Sleep', value: 0x4C },
  { label: '- Torch', value: 0x4D },
  { label: '- Hammerne', value: 0x4E },
  { label: '- Watch', value: 0x4F },
  { label: '- Berserk', value: 0x50 },
  { label: '- Unlock', value: 0x51 },
  { label: '- Shield', value: 0x52 },
  { label: '- Fire Dragon Stone', value: 0x53 },
  { label: '- Divine Dragon Stone', value: 0x54 },
  { label: '- Magic Dragon Stone', value: 0x55 },
  { label: '- Secret Book', value: 0x56 },
  { label: '- Goddess Icon', value: 0x57 },
  { label: '- Angelic Robe', value: 0x58 },
  { label: '- Dragon Shield', value: 0x59 },
  { label: '- Energy Ring', value: 0x5A },
  { label: '- Speedwing', value: 0x5B },
  { label: '- Talisman', value: 0x5C },
  { label: '- Boots', value: 0x5D },
  { label: '- Body Ring', value: 0x5E },
  { label: '- Hero\'s Proof', value: 0x5F },
  { label: '- Knight\'s Proof', value: 0x60 },
  { label: '- Orion\'s Bolt', value: 0x61 },
  { label: '- Elysian Whip', value: 0x62 },
  { label: '- Guiding Ring', value: 0x63 },
  { label: '- Chest Key (5)', value: 0x64 },
  { label: '- Door Key', value: 0x65 },
  { label: '- Bridge Key', value: 0x66 },
  { label: '- Lockpick', value: 0x67 },
  { label: '- Vulnerary', value: 0x68 },
  { label: '- Elixir', value: 0x69 },
  { label: '- Holy Water', value: 0x6A },
  { label: '- Torch', value: 0x6B },
  { label: '- Antitoxin', value: 0x6C },
  { label: '- Member Card', value: 0x6D },
  { label: '- Silver Card', value: 0x6E },
  { label: '- Gold', value: 0x6F },
  { label: '- Dark Breath', value: 0x70 },
  { label: '- Exaccus', value: 0x71 },
  { label: '- Steel Blade', value: 0x72 },
  { label: '- Silver Blade', value: 0x73 },
  { label: '- Al\'s Sword', value: 0x74 },
  { label: '- Gant\'s Lance', value: 0x75 },
  { label: '- Tina\'s Staff', value: 0x76 },
  { label: '- Holy Maiden', value: 0x77 },
  { label: '- Wyrmslayer', value: 0x78 },
  { label: '- White Gem', value: 0x79 },
  { label: '- Blue Gem', value: 0x7A },
  { label: '- Red Gem', value: 0x7B },
  { label: '- Delphi Shield', value: 0x7C },
  { label: '- Runesword', value: 0x7D },
  { label: '- Spear', value: 0x7E },
  { label: '- Tomahawk', value: 0x7F },
];
