export const FE4PlayerWeaponEditorEntries = [
  { label: '01-02', value: 0 },
  { label: '03-04', value: 1 },
  { label: '05-06', value: 2 },
  { label: '07-08', value: 3 },
  { label: '09-0A', value: 4 },
  { label: '0B-0C', value: 5 },
  { label: '0D-0E', value: 6 },
  { label: '0F-10', value: 7 },
  { label: '11-12', value: 8 },
  { label: '13-14', value: 9 },
  { label: '15-16', value: 10 },
  { label: '17-18', value: 11 },
  { label: '19-1A', value: 12 },
  { label: '1B-1C', value: 13 },
  { label: '1D-1E', value: 14 },
  { label: '1F-20', value: 15 },
  { label: '21-22', value: 16 },
  { label: '23-24', value: 17 },
  { label: '25-26', value: 18 },
  { label: '27-28', value: 19 },
  { label: '29-2A', value: 20 },
  { label: '2B-2C', value: 21 },
  { label: '2D-2E', value: 22 },
  { label: '2F-30', value: 23 },
  { label: '31-32', value: 24 },
  { label: '33-34', value: 25 },
  { label: '35-36', value: 26 },
  { label: '37-38', value: 27 },
  { label: '39-3A', value: 28 },
  { label: '3B-3C', value: 29 },
  { label: '3D-3E', value: 30 },
  { label: '3F-40', value: 31 },
  { label: '41-42', value: 32 },
  { label: '43-44', value: 33 },
  { label: '45-46', value: 34 },
  { label: '47-48', value: 35 },
  { label: '49-4A', value: 36 },
  { label: '4B-4C', value: 37 },
  { label: '4D-4E', value: 38 },
  { label: '4F-50', value: 39 },
  { label: '51-52', value: 40 },
  { label: '53-54', value: 41 },
  { label: '55-56', value: 42 },
  { label: '57-58', value: 43 },
  { label: '59-5A', value: 44 },
  { label: '5B-5C', value: 45 },
  { label: '5D-5E', value: 46 },
  { label: '5F-60', value: 47 },
  { label: '61-62', value: 48 },
  { label: '63-64', value: 49 },
  { label: '65-66', value: 50 },
  { label: '67-68', value: 51 },
  { label: '69-6A', value: 52 },
  { label: '6B-6C', value: 53 },
  { label: '6D-6E', value: 54 },
  { label: '6F-70', value: 55 },
  { label: '71-72', value: 56 },
  { label: '73-74', value: 57 },
  { label: '75-76', value: 58 },
  { label: '77-78', value: 59 },
  { label: '79-7A', value: 60 },
  { label: '7B-7C', value: 61 },
  { label: '7D-7E', value: 62 },
  { label: '7F-80', value: 63 },
  { label: '81-82', value: 64 },
  { label: '83-84', value: 65 },
  { label: '85-86', value: 66 },
  { label: '87-88', value: 67 },
  { label: '89-8A', value: 68 },
  { label: '8B-8C', value: 69 },
  { label: '8D-8E', value: 70 },
  { label: 'Entry 71', value: 71 },
];

export const FE4WeaponList = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Steel Sword', value: 0x01 },
  { label: 'Silver Sword', value: 0x02 },
  { label: 'Iron Blade', value: 0x03 },
  { label: 'Steel Blade', value: 0x04 },
  { label: 'Silver Blade', value: 0x05 },
  { label: 'Prayer Sword', value: 0x06 },
  { label: 'Thief Sword', value: 0x07 },
  { label: 'Barrier Sword', value: 0x08 },
  { label: 'Berserk Sword', value: 0x09 },
  { label: 'Hero\'s Sword', value: 0x0A },
  { label: 'Silence Sword', value: 0x0B },
  { label: 'Sleep Sword', value: 0x0C },
  { label: 'Thin Sword', value: 0x0D },
  { label: 'Defence Sword', value: 0x0E },
  { label: 'Fire Sword', value: 0x0F },
  { label: 'Earth Sword', value: 0x10 },
  { label: 'Thunder Sword', value: 0x11 },
  { label: 'Wind Sword', value: 0x12 },
  { label: 'Light Sword', value: 0x13 },
  { label: 'Mistoltin', value: 0x14 },
  { label: 'Tyrfing', value: 0x15 },
  { label: 'Balmunk', value: 0x16 },
  { label: 'Armor Killer', value: 0x17 },
  { label: 'Wing Clipper', value: 0x18 },
  { label: 'Broken Sword', value: 0x19 },
  { label: 'Broken Sword', value: 0x1A },
  { label: 'Broken Sword', value: 0x1B },
  { label: 'Iron Lance', value: 0x1C },
  { label: 'Steel Lance', value: 0x1D },
  { label: 'Silver Lance', value: 0x1E },
  { label: 'Hand Lance', value: 0x1F },
  { label: 'Knight Killer', value: 0x20 },
  { label: 'Hero\'s Lance', value: 0x21 },
  { label: 'Thin Lance', value: 0x22 },
  { label: 'Gungnir', value: 0x23 },
  { label: 'Gae Bolg', value: 0x24 },
  { label: 'Broken Lance', value: 0x25 },
  { label: 'Broken Lance', value: 0x26 },
  { label: 'Broken Lance', value: 0x27 },
  { label: 'Iron Axe', value: 0x28 },
  { label: 'Steel Axe', value: 0x29 },
  { label: 'Silver Axe', value: 0x2A },
  { label: 'Hero\'s Axe', value: 0x2B },
  { label: 'Swanchika', value: 0x2C },
  { label: 'Hand Axe', value: 0x2D },
  { label: 'Broken Axe', value: 0x2E },
  { label: 'Broken Axe', value: 0x2F },
  { label: 'Broken Axe', value: 0x30 },
  { label: 'Iron Bow', value: 0x31 },
  { label: 'Steel Bow', value: 0x32 },
  { label: 'Silver Bow', value: 0x33 },
  { label: 'Hero\'s Bow', value: 0x34 },
  { label: 'Killer Bow', value: 0x35 },
  { label: 'Ichieval', value: 0x36 },
  { label: 'Broken Bow', value: 0x37 },
  { label: 'Broken Bow', value: 0x38 },
  { label: 'Broken Bow', value: 0x39 },
  { label: 'Long Arch', value: 0x3A },
  { label: 'Iron Arch', value: 0x3B },
  { label: 'Killer Arch', value: 0x3C },
  { label: 'Gold Arch', value: 0x3D },
  { label: 'Fire', value: 0x3E },
  { label: 'El Fire', value: 0x3F },
  { label: 'Volcanon', value: 0x40 },
  { label: 'Fala Flame', value: 0x41 },
  { label: 'Meteo', value: 0x42 },
  { label: 'Thunder', value: 0x43 },
  { label: 'El Thunder', value: 0x44 },
  { label: 'Torron', value: 0x45 },
  { label: 'Tor Hammer', value: 0x46 },
  { label: 'Thunderstorm', value: 0x47 },
  { label: 'Wind', value: 0x48 },
  { label: 'El Wind', value: 0x49 },
  { label: 'Tornado', value: 0x4A },
  { label: 'Holsety', value: 0x4B },
  { label: 'Blizzard', value: 0x4C },
  { label: 'Lightning', value: 0x4D },
  { label: 'Rizziah', value: 0x4E },
  { label: 'Aura', value: 0x4F },
  { label: 'Narga', value: 0x50 },
  { label: 'Yotsmungand', value: 0x51 },
  { label: 'Fenrir', value: 0x52 },
  { label: 'Hell', value: 0x53 },
  { label: 'Loptous', value: 0x54 },
  { label: 'Empty Book', value: 0x55 },
  { label: 'Empty Book', value: 0x56 },
  { label: 'Empty Book', value: 0x57 },
  { label: 'Live Staff', value: 0x58 },
  { label: 'Relive Staff', value: 0x59 },
  { label: 'Recover Staff', value: 0x5A },
  { label: 'Libro Staff', value: 0x5B },
  { label: 'Reserve Staff', value: 0x5C },
  { label: 'Return Staff', value: 0x5D },
  { label: 'Warp Staff', value: 0x5E },
  { label: 'Rescue Staff', value: 0x5F },
  { label: 'Charm Staff', value: 0x60 },
  { label: 'Rest Staff', value: 0x61 },
  { label: 'Valkyre Staff', value: 0x62 },
  { label: 'Silence Staff', value: 0x63 },
  { label: 'Sleep Staff', value: 0x64 },
  { label: 'Berserk Staff', value: 0x65 },
  { label: 'Thief Staff', value: 0x66 },
  { label: 'Broken Staff', value: 0x67 },
  { label: 'Broken Staff', value: 0x68 },
  { label: 'Broken Staff', value: 0x69 },
  { label: 'Live Bracelet', value: 0x6A },
  { label: 'Elite Ring', value: 0x6B },
  { label: 'Thief Bracelet', value: 0x6C },
  { label: 'Prayer Bracelet', value: 0x6D },
  { label: 'Pursuit Ring', value: 0x6E },
  { label: 'Recover Ring', value: 0x6F },
  { label: 'Bargain Bracelet', value: 0x70 },
  { label: 'Knight Ring', value: 0x71 },
  { label: 'Return Ring', value: 0x72 },
  { label: 'Speed Ring', value: 0x73 },
  { label: 'Magic Ring', value: 0x74 },
  { label: 'Power Ring', value: 0x75 },
  { label: 'Shield Ring', value: 0x76 },
  { label: 'Barrier Ring', value: 0x77 },
  { label: 'Leg Ring', value: 0x78 },
  { label: 'Skill Ring', value: 0x79 },
  { label: 'Broken Sword', value: 0x7A },
  { label: 'Broken Spear', value: 0x7B },
  { label: 'Broken Bow', value: 0x7C },
  { label: 'Empty Book', value: 0x7D },
  { label: 'Empty Book', value: 0x7E },
  { label: 'Empty Book', value: 0x7F },
  { label: 'Empty Book', value: 0x80 },
  { label: 'Empty Book', value: 0x81 },
  { label: 'Empty Book', value: 0x82 },
  { label: 'Empty Book', value: 0x83 },
  { label: 'Empty Book', value: 0x84 },
  { label: 'Empty Book', value: 0x85 },
  { label: 'Empty Book', value: 0x86 },
  { label: 'Empty Book', value: 0x87 },
  { label: 'Broken Staff', value: 0x88 },
  { label: 'Circlet', value: 0x89 },
  { label: 'None', value: 0xFF },
];
