export const FE6Chapter6ArmyEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
  { label: 'Entry 68', value: 68 },
  { label: 'Entry 69', value: 69 },
  { label: 'Entry 70', value: 70 },
  { label: 'Entry 71', value: 71 },
  { label: 'Entry 72', value: 72 },
  { label: 'Entry 73', value: 73 },
  { label: 'Entry 74', value: 74 },
  { label: 'Entry 75', value: 75 },
  { label: 'Entry 76', value: 76 },
  { label: 'Entry 77', value: 77 },
  { label: 'Entry 78', value: 78 },
  { label: 'Entry 79', value: 79 },
  { label: 'Entry 80', value: 80 },
  { label: 'Entry 81', value: 81 },
  { label: 'Entry 82', value: 82 },
  { label: 'Entry 83', value: 83 },
  { label: 'Entry 84', value: 84 },
  { label: 'Entry 85', value: 85 },
  { label: 'Entry 86', value: 86 },
  { label: 'Entry 87', value: 87 },
  { label: 'Entry 88', value: 88 },
  { label: 'Entry 89', value: 89 },
  { label: 'Entry 90', value: 90 },
  { label: 'Entry 91', value: 91 },
];

export const CharacterList = [
  { label: 'None', value: 0x00 },
  { label: 'Roy', value: 0x01 },
  { label: 'Clarine', value: 0x02 },
  { label: 'Fa', value: 0x03 },
  { label: 'Shin', value: 0x04 },
  { label: 'Sue', value: 0x05 },
  { label: 'Dayan', value: 0x06 },
  { label: 'Dayan (NPC)', value: 0x07 },
  { label: 'Barth', value: 0x08 },
  { label: 'Bors', value: 0x09 },
  { label: 'Wendy', value: 0x0A },
  { label: 'Douglas', value: 0x0B },
  { label: 'Douglas (Enemy)', value: 0x0C },
  { label: 'Wolt', value: 0x0D },
  { label: 'Dorothy', value: 0x0E },
  { label: 'Klein', value: 0x0F },
  { label: 'Saul', value: 0x10 },
  { label: 'Ellen', value: 0x11 },
  { label: 'Yodel', value: 0x12 },
  { label: 'Yodel (NPC)', value: 0x13 },
  { label: 'Chad', value: 0x14 },
  { label: 'Karel', value: 0x15 },
  { label: 'Fir', value: 0x16 },
  { label: 'Rutger', value: 0x17 },
  { label: 'Dieck', value: 0x18 },
  { label: 'Oujay', value: 0x19 },
  { label: 'Garret', value: 0x1A },
  { label: 'Alen', value: 0x1B },
  { label: 'Lance', value: 0x1C },
  { label: 'Percival', value: 0x1D },
  { label: 'Igrene', value: 0x1E },
  { label: 'Marcus', value: 0x1F },
  { label: 'Ashtol', value: 0x20 },
  { label: 'Wade', value: 0x21 },
  { label: 'Lot', value: 0x22 },
  { label: 'Bartre', value: 0x23 },
  { label: 'Bartre (NPC)', value: 0x24 },
  { label: 'Lugh', value: 0x25 },
  { label: 'Lilina', value: 0x26 },
  { label: 'Hugh', value: 0x27 },
  { label: 'Niime', value: 0x28 },
  { label: 'Niime (NPC)', value: 0x29 },
  { label: 'Rei', value: 0x2A },
  { label: 'Lalum', value: 0x2B },
  { label: 'Junno', value: 0x2C },
  { label: 'Junno (NPC)', value: 0x2D },
  { label: 'Tate', value: 0x2E },
  { label: 'Tate (Enemy)', value: 0x2F },
  { label: 'Tate (NPC)', value: 0x30 },
  { label: 'Thany', value: 0x31 },
  { label: 'Zeiss', value: 0x32 },
  { label: 'Gale', value: 0x33 },
  { label: 'Elfin', value: 0x34 },
  { label: 'Cath', value: 0x35 },
  { label: 'Sophia', value: 0x36 },
  { label: 'Miledy', value: 0x37 },
  { label: 'Gonzales (Route A)', value: 0x38 },
  { label: 'Gonzales (Route B)', value: 0x39 },
  { label: 'Noah', value: 0x3A },
  { label: 'Treck', value: 0x3B },
  { label: 'Zealot', value: 0x3C },
  { label: 'Echidna', value: 0x3D },
  { label: 'Echidna (NPC)', value: 0x3E },
  { label: 'Cecilia', value: 0x3F },
  { label: 'Geese', value: 0x40 },
  { label: 'Geese (NPC)', value: 0x41 },
  { label: 'Merlinus', value: 0x42 },
  { label: 'Eliwood', value: 0x43 },
  { label: 'Guinevere', value: 0x44 },
  { label: 'Bandit', value: 0x45 },
  { label: 'Bandit', value: 0x46 },
  { label: 'Bandit', value: 0x47 },
  { label: 'Bandit', value: 0x48 },
  { label: 'Bandit', value: 0x49 },
  { label: 'Damas', value: 0x4A },
  { label: 'Rude', value: 0x4B },
  { label: 'Slater', value: 0x4C },
  { label: 'Erik', value: 0x4D },
  { label: 'Dory', value: 0x4E },
  { label: 'Wagner', value: 0x4F },
  { label: 'Devias', value: 0x50 },
  { label: 'Reigans', value: 0x51 },
  { label: 'Scott', value: 0x52 },
  { label: 'Nord', value: 0x53 },
  { label: 'William', value: 0x54 },
  { label: 'Flear', value: 0x55 },
  { label: 'Oro', value: 0x56 },
  { label: 'Robert', value: 0x57 },
  { label: 'Ain', value: 0x58 },
  { label: 'Narshan', value: 0x59 },
  { label: 'Randy', value: 0x5A },
  { label: 'Maggie', value: 0x5B },
  { label: 'Rose', value: 0x5C },
  { label: 'Reath', value: 0x5D },
  { label: 'Alcard', value: 0x5E },
  { label: 'Martel', value: 0x5F },
  { label: 'Sigune', value: 0x60 },
  { label: 'Roartz', value: 0x61 },
  { label: 'Murdock', value: 0x62 },
  { label: 'Brenya', value: 0x63 },
  { label: 'Zephiel', value: 0x64 },
  { label: 'Idoun (Shaman)', value: 0x65 },
  { label: 'Idoun (Dragon)', value: 0x66 },
  { label: 'Jahn', value: 0x67 },
  { label: 'Zeke', value: 0x68 },
  { label: 'Monke', value: 0x69 },
  { label: 'Kel', value: 0x6A },
  { label: 'Bandit', value: 0x6B },
  { label: 'Bern Soldier', value: 0x6C },
  { label: 'Bern Soldier', value: 0x6D },
  { label: 'Bern Soldier', value: 0x6E },
  { label: 'Bern Soldier', value: 0x6F },
  { label: 'Bern Soldier', value: 0x70 },
  { label: 'Laus Soldier', value: 0x71 },
  { label: 'Pirate', value: 0x72 },
  { label: 'Bandit', value: 0x73 },
  { label: 'Thria Soldier', value: 0x74 },
  { label: 'Rebel', value: 0x75 },
  { label: 'Bern Soldier', value: 0x76 },
  { label: 'Rebel', value: 0x77 },
  { label: 'Government Official', value: 0x78 },
  { label: 'Thief', value: 0x79 },
  { label: 'Western Robber', value: 0x7A },
  { label: 'Pirate', value: 0x7B },
  { label: 'Almar Soldier', value: 0x7C },
  { label: 'Western Robber', value: 0x7D },
  { label: 'Registans', value: 0x7E },
  { label: 'Embericum Soldier', value: 0x7F },
  { label: 'Bandit', value: 0x80 },
  { label: 'Western Soldier', value: 0x81 },
  { label: 'Western Robber', value: 0x82 },
  { label: 'Bern Soldier', value: 0x83 },
  { label: 'Jutes Soldier', value: 0x84 },
  { label: 'Western Soldier', value: 0x85 },
  { label: 'Bern Soldier', value: 0x86 },
  { label: 'Etruria Soldier', value: 0x87 },
  { label: 'Bern Mercenary', value: 0x88 },
  { label: 'Bandit', value: 0x89 },
  { label: 'Etruria Soldier', value: 0x8A },
  { label: 'Bern Soldier', value: 0x8B },
  { label: 'Thria Knight Group', value: 0x8C },
  { label: 'Bandit', value: 0x8D },
  { label: 'Bern Soldier', value: 0x8E },
  { label: 'Etruria Soldier', value: 0x8F },
  { label: 'Thief', value: 0x90 },
  { label: 'Etruria Soldier', value: 0x91 },
  { label: 'Bern Soldier', value: 0x92 },
  { label: 'Pirate', value: 0x93 },
  { label: 'Pirate', value: 0x94 },
  { label: 'Thria Knight Group', value: 0x95 },
  { label: 'Bern Soldier', value: 0x96 },
  { label: 'Thria Knight Group', value: 0x97 },
  { label: 'Bandit', value: 0x98 },
  { label: 'Pegasus Knight Group', value: 0x99 },
  { label: 'Ilia Knight Group', value: 0x9A },
  { label: 'Bandit', value: 0x9B },
  { label: 'Ilia Knight Group', value: 0x9C },
  { label: 'Ilia Citizen', value: 0x9D },
  { label: 'Thief', value: 0x9E },
  { label: 'Bern Soldier', value: 0x9F },
  { label: 'Bern Soldier', value: 0xA0 },
  { label: 'Bern Soldier', value: 0xA1 },
  { label: 'Thief', value: 0xA2 },
  { label: 'Idina Soldier', value: 0xA3 },
  { label: 'Citizens', value: 0xA4 },
  { label: 'Western Robber', value: 0xA5 },
  { label: 'Etruria Soldier', value: 0xA6 },
  { label: 'Tribe Warriors', value: 0xA7 },
  { label: 'Bern Soldier', value: 0xA8 },
  { label: 'Dejute Tribe Warrior', value: 0xA9 },
  { label: 'Bern Soldier', value: 0xAA },
  { label: 'Sacae Tribe Warrior', value: 0xAB },
  { label: 'Bern Soldier', value: 0xAC },
  { label: 'Etruria Soldier', value: 0xAD },
  { label: 'Sacae Tribe Warrior', value: 0xAE },
  { label: 'Thief', value: 0xAF },
  { label: 'Bern Battle Dragon', value: 0xB0 },
  { label: 'Bern Soldier', value: 0xB1 },
  { label: 'Bern Battle Dragon', value: 0xB2 },
  { label: 'Rebel', value: 0xB3 },
  { label: 'Rebel', value: 0xB4 },
  { label: 'Henning', value: 0xB5 },
  { label: 'Scollin', value: 0xB6 },
  { label: '???', value: 0xB7 },
  { label: 'Grero', value: 0xB8 },
  { label: 'Ohtz', value: 0xB9 },
  { label: 'Dick', value: 0xBA },
  { label: 'Bern Soldier', value: 0xBB },
  { label: 'Sacae Tribe Warrior', value: 0xBC },
  { label: 'Bern Soldier', value: 0xBD },
  { label: 'Thoril', value: 0xBE },
  { label: 'Brakul', value: 0xBF },
  { label: 'Kudoka', value: 0xC0 },
  { label: 'Maral', value: 0xC1 },
  { label: 'Kabul', value: 0xC2 },
  { label: 'Chan', value: 0xC3 },
  { label: 'Perith', value: 0xC4 },
  { label: 'Bern Soldier', value: 0xC5 },
  { label: 'Windam', value: 0xC6 },
  { label: 'Etruria Soldier', value: 0xC7 },
  { label: 'Morgan', value: 0xC8 },
  { label: 'Rebel', value: 0xC9 },
  { label: 'Bern Soldier', value: 0xCA },
  { label: 'Bern Soldier', value: 0xCB },
  { label: 'Bern Soldier', value: 0xCC },
  { label: 'Citizen', value: 0xCD },
  { label: 'Ilia Citizen', value: 0xCE },
  { label: 'Hector', value: 0xCF },
  { label: 'Bors (Training)', value: 0xD0 },
  { label: 'Ostia Soldier', value: 0xD1 },
  { label: 'Ostia Soldier', value: 0xD2 },
  { label: 'Army Knight Commander Group', value: 0xD3 },
  { label: 'Idina Soldier', value: 0xD4 },
  { label: 'Army Knight Commander Group', value: 0xD5 },
  { label: 'Army Knight Commander Group', value: 0xD6 },
  { label: 'Army Knight Commander Group', value: 0xD7 },
  { label: 'Klein\'s Group', value: 0xD8 },
  { label: 'Tate\'s Group', value: 0xD9 },
  { label: 'Enemy Leader', value: 0xDA },
  { label: 'Enemy Leader', value: 0xDB },
  { label: 'Enemy Leader', value: 0xDC },
  { label: 'Enemy Leader', value: 0xDD },
  { label: 'Enemy Leader', value: 0xDE },
  { label: 'Enemy Leader', value: 0xDF },
  { label: 'Bandit', value: 0xE0 },
  { label: 'Combatant', value: 0xE1 },
  { label: 'Cracked Wall', value: 0xE2 },
];

export const ClassList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Roy Lord', value: 0x01 },
  { label: 'Mercenary', value: 0x02 },
  { label: 'Mercenary (F)', value: 0x03 },
  { label: 'Hero', value: 0x04 },
  { label: 'Hero (F)', value: 0x05 },
  { label: 'Swordfighter', value: 0x06 },
  { label: 'Swordfighter (F)', value: 0x07 },
  { label: 'Swordmaster', value: 0x08 },
  { label: 'Swordmaster (F)', value: 0x09 },
  { label: 'Axefighter', value: 0x0A },
  { label: 'Warrior', value: 0x0B },
  { label: 'Armour Knight', value: 0x0C },
  { label: 'Armour Knight (F)', value: 0x0D },
  { label: 'General', value: 0x0E },
  { label: 'General (F)', value: 0x0F },
  { label: 'Archer', value: 0x10 },
  { label: 'Archer (F)', value: 0x11 },
  { label: 'Sniper', value: 0x12 },
  { label: 'Sniper (F)', value: 0x13 },
  { label: 'Priest', value: 0x14 },
  { label: 'Sister', value: 0x15 },
  { label: 'Bishop', value: 0x16 },
  { label: 'Bishop (F)', value: 0x17 },
  { label: 'Mage', value: 0x18 },
  { label: 'Mage (F)', value: 0x19 },
  { label: 'Sage', value: 0x1A },
  { label: 'Sage (F)', value: 0x1B },
  { label: 'Shaman', value: 0x1C },
  { label: 'Shaman (F)', value: 0x1D },
  { label: 'Druid', value: 0x1E },
  { label: 'Druid (F)', value: 0x1F },
  { label: 'Socialknight', value: 0x20 },
  { label: 'Socialknight (F) (messed up palette)', value: 0x21 },
  { label: 'Paladin', value: 0x22 },
  { label: 'Paladin (F) (messed up palette)', value: 0x23 },
  { label: 'Troubadour', value: 0x24 },
  { label: 'Valkyrie', value: 0x25 },
  { label: 'Nomad', value: 0x26 },
  { label: 'Nomad (F)', value: 0x27 },
  { label: 'Nomad Trooper', value: 0x28 },
  { label: 'Nomad Trooper (F)', value: 0x29 },
  { label: 'Pegasus Knight', value: 0x2A },
  { label: 'Falcon Knight', value: 0x2B },
  { label: 'Dragon Knight', value: 0x2C },
  { label: 'Dragon Knight (F)', value: 0x2D },
  { label: 'Dragon Master', value: 0x2E },
  { label: 'Dragon Master (F)', value: 0x2F },
  { label: 'Soldier', value: 0x30 },
  { label: 'Mountain Thief', value: 0x31 },
  { label: 'Pirate', value: 0x32 },
  { label: 'Berserker', value: 0x33 },
  { label: 'Thief', value: 0x34 },
  { label: 'Thief (F)', value: 0x35 },
  { label: 'Bard', value: 0x36 },
  { label: 'Dancer', value: 0x37 },
  { label: 'Mamkute', value: 0x38 },
  { label: 'Mamkute (F)', value: 0x39 },
  { label: 'Fire Dragon', value: 0x3A },
  { label: 'Divine Dragon', value: 0x3B },
  { label: 'Magic Dragon', value: 0x3C },
  { label: 'King', value: 0x3D },
  { label: 'Civilian', value: 0x3E },
  { label: 'Civilian (F)', value: 0x3F },
  { label: 'Child', value: 0x40 },
  { label: 'Child (F)', value: 0x41 },
  { label: 'Storage', value: 0x42 },
  { label: 'Roy Master Lord', value: 0x43 },
  { label: 'Archer on Long Arch', value: 0x44 },
  { label: 'Archer on Iron Arch', value: 0x45 },
  { label: 'Archer on Killer Arch', value: 0x46 },
  { label: 'Long Arch', value: 0x47 },
  { label: 'Iron Arch', value: 0x48 },
  { label: 'Killer Arch', value: 0x49 },
  { label: 'Disarmed Sniper (no standing sprites)', value: 0x4A },
  { label: 'Disarmed Sniper (F) (no standing sprites)', value: 0x4B },
];

export const Level = [
  { label: '0, Player, Fixed', value: 0x00 },
  { label: '0, Player, Random', value: 0x01 },
  { label: '0, NPC, Fixed', value: 0x02 },
  { label: '0, NPC, Random', value: 0x03 },
  { label: '0, Enemy, Fixed', value: 0x04 },
  { label: '0, Enemy, Random', value: 0x05 },
  { label: 'Freeze', value: 0x06 },
  { label: 'Freeze', value: 0x07 },
  { label: '1, Player, Fixed', value: 0x08 },
  { label: '1, Player, Random', value: 0x09 },
  { label: '1, NPC, Fixed', value: 0x0A },
  { label: '1, NPC, Random', value: 0x0B },
  { label: '1, Enemy, Fixed', value: 0x0C },
  { label: '1, Enemy, Random', value: 0x0D },
  { label: 'Freeze', value: 0x0E },
  { label: 'Freeze', value: 0x0F },
  { label: '2, Player, Fixed', value: 0x10 },
  { label: '2, Player, Random', value: 0x11 },
  { label: '2, NPC, Fixed', value: 0x12 },
  { label: '2, NPC, Random', value: 0x13 },
  { label: '2, Enemy, Fixed', value: 0x14 },
  { label: '2, Enemy, Random', value: 0x15 },
  { label: 'Freeze', value: 0x16 },
  { label: 'Freeze', value: 0x17 },
  { label: '3, Player, Fixed', value: 0x18 },
  { label: '3, Player, Random', value: 0x19 },
  { label: '3, NPC, Fixed', value: 0x1A },
  { label: '3, NPC, Random', value: 0x1B },
  { label: '3, Enemy, Fixed', value: 0x1C },
  { label: '3, Enemy, Random', value: 0x1D },
  { label: 'Freeze', value: 0x1E },
  { label: 'Freeze', value: 0x1F },
  { label: '4, Player, Fixed', value: 0x20 },
  { label: '4, Player, Random', value: 0x21 },
  { label: '4, NPC, Fixed', value: 0x22 },
  { label: '4, NPC, Random', value: 0x23 },
  { label: '4, Enemy, Fixed', value: 0x24 },
  { label: '4, Enemy, Random', value: 0x25 },
  { label: 'Freeze', value: 0x26 },
  { label: 'Freeze', value: 0x27 },
  { label: '5, Player, Fixed', value: 0x28 },
  { label: '5, Player, Random', value: 0x29 },
  { label: '5, NPC, Fixed', value: 0x2A },
  { label: '5, NPC, Random', value: 0x2B },
  { label: '5, Enemy, Fixed', value: 0x2C },
  { label: '5, Enemy, Random', value: 0x2D },
  { label: 'Freeze', value: 0x2E },
  { label: 'Freeze', value: 0x2F },
  { label: '6, Player, Fixed', value: 0x30 },
  { label: '6, Player, Random', value: 0x31 },
  { label: '6, NPC, Fixed', value: 0x32 },
  { label: '6, NPC, Random', value: 0x33 },
  { label: '6, Enemy, Fixed', value: 0x34 },
  { label: '6, Enemy, Random', value: 0x35 },
  { label: 'Freeze', value: 0x36 },
  { label: 'Freeze', value: 0x37 },
  { label: '7, Player, Fixed', value: 0x38 },
  { label: '7, Player, Random', value: 0x39 },
  { label: '7, NPC, Fixed', value: 0x3A },
  { label: '7, NPC, Random', value: 0x3B },
  { label: '7, Enemy, Fixed', value: 0x3C },
  { label: '7, Enemy, Random', value: 0x3D },
  { label: 'Freeze', value: 0x3E },
  { label: 'Freeze', value: 0x3F },
  { label: '8, Player, Fixed', value: 0x40 },
  { label: '8, Player, Random', value: 0x41 },
  { label: '8, NPC, Fixed', value: 0x42 },
  { label: '8, NPC, Random', value: 0x43 },
  { label: '8, Enemy, Fixed', value: 0x44 },
  { label: '8, Enemy, Random', value: 0x45 },
  { label: 'Freeze', value: 0x46 },
  { label: 'Freeze', value: 0x47 },
  { label: '9, Player, Fixed', value: 0x48 },
  { label: '9, Player, Random', value: 0x49 },
  { label: '9, NPC, Fixed', value: 0x4A },
  { label: '9, NPC, Random', value: 0x4B },
  { label: '9, Enemy, Fixed', value: 0x4C },
  { label: '9, Enemy, Random', value: 0x4D },
  { label: 'Freeze', value: 0x4E },
  { label: 'Freeze', value: 0x4F },
  { label: '10, Player, Fixed', value: 0x50 },
  { label: '10, Player, Random', value: 0x51 },
  { label: '10, NPC, Fixed', value: 0x52 },
  { label: '10, NPC, Random', value: 0x53 },
  { label: '10, Enemy, Fixed', value: 0x54 },
  { label: '10, Enemy, Random', value: 0x55 },
  { label: 'Freeze', value: 0x56 },
  { label: 'Freeze', value: 0x57 },
  { label: '11, Player, Fixed', value: 0x58 },
  { label: '11, Player, Random', value: 0x59 },
  { label: '11, NPC, Fixed', value: 0x5A },
  { label: '11, NPC, Random', value: 0x5B },
  { label: '11, Enemy, Fixed', value: 0x5C },
  { label: '11, Enemy, Random', value: 0x5D },
  { label: 'Freeze', value: 0x5E },
  { label: 'Freeze', value: 0x5F },
  { label: '12, Player, Fixed', value: 0x60 },
  { label: '12, Player, Random', value: 0x61 },
  { label: '12, NPC, Fixed', value: 0x62 },
  { label: '12, NPC, Random', value: 0x63 },
  { label: '12, Enemy, Fixed', value: 0x64 },
  { label: '12, Enemy, Random', value: 0x65 },
  { label: 'Freeze', value: 0x66 },
  { label: 'Freeze', value: 0x67 },
  { label: '13, Player, Fixed', value: 0x68 },
  { label: '13, Player, Random', value: 0x69 },
  { label: '13, NPC, Fixed', value: 0x6A },
  { label: '13, NPC, Random', value: 0x6B },
  { label: '13, Enemy, Fixed', value: 0x6C },
  { label: '13, Enemy, Random', value: 0x6D },
  { label: 'Freeze', value: 0x6E },
  { label: 'Freeze', value: 0x6F },
  { label: '14, Player, Fixed', value: 0x70 },
  { label: '14, Player, Random', value: 0x71 },
  { label: '14, NPC, Fixed', value: 0x72 },
  { label: '14, NPC, Random', value: 0x73 },
  { label: '14, Enemy, Fixed', value: 0x74 },
  { label: '14, Enemy, Random', value: 0x75 },
  { label: 'Freeze', value: 0x76 },
  { label: 'Freeze', value: 0x77 },
  { label: '15, Player, Fixed', value: 0x78 },
  { label: '15, Player, Random', value: 0x79 },
  { label: '15, NPC, Fixed', value: 0x7A },
  { label: '15, NPC, Random', value: 0x7B },
  { label: '15, Enemy, Fixed', value: 0x7C },
  { label: '15, Enemy, Random', value: 0x7D },
  { label: 'Freeze', value: 0x7E },
  { label: 'Freeze', value: 0x7F },
  { label: '16, Player, Fixed', value: 0x80 },
  { label: '16, Player, Random', value: 0x81 },
  { label: '16, NPC, Fixed', value: 0x82 },
  { label: '16, NPC, Random', value: 0x83 },
  { label: '16, Enemy, Fixed', value: 0x84 },
  { label: '16, Enemy, Random', value: 0x85 },
  { label: 'Freeze', value: 0x86 },
  { label: 'Freeze', value: 0x87 },
  { label: '17, Player, Fixed', value: 0x88 },
  { label: '17, Player, Random', value: 0x89 },
  { label: '17, NPC, Fixed', value: 0x8A },
  { label: '17, NPC, Random', value: 0x8B },
  { label: '17, Enemy, Fixed', value: 0x8C },
  { label: '17, Enemy, Random', value: 0x8D },
  { label: 'Freeze', value: 0x8E },
  { label: 'Freeze', value: 0x8F },
  { label: '18, Player, Fixed', value: 0x90 },
  { label: '18, Player, Random', value: 0x91 },
  { label: '18, NPC, Fixed', value: 0x92 },
  { label: '18, NPC, Random', value: 0x93 },
  { label: '18, Enemy, Fixed', value: 0x94 },
  { label: '18, Enemy, Random', value: 0x95 },
  { label: 'Freeze', value: 0x96 },
  { label: 'Freeze', value: 0x97 },
  { label: '19, Player, Fixed', value: 0x98 },
  { label: '19, Player, Random', value: 0x99 },
  { label: '19, NPC, Fixed', value: 0x9A },
  { label: '19, NPC, Random', value: 0x9B },
  { label: '19, Enemy, Fixed', value: 0x9C },
  { label: '19, Enemy, Random', value: 0x9D },
  { label: 'Freeze', value: 0x9E },
  { label: 'Freeze', value: 0x9F },
  { label: '20, Player, Fixed', value: 0xA0 },
  { label: '20, Player, Random', value: 0xA1 },
  { label: '20, NPC, Fixed', value: 0xA2 },
  { label: '20, NPC, Random', value: 0xA3 },
  { label: '20, Enemy, Fixed', value: 0xA4 },
  { label: '20, Enemy, Random', value: 0xA5 },
  { label: 'Freeze', value: 0xA6 },
  { label: 'Freeze', value: 0xA7 },
  { label: 'You can continue beyond', value: 0xA8 },
  { label: 'level 20 from here, but', value: 0xA9 },
  { label: 'I am too lazy to type', value: 0xAA },
  { label: 'the rest of them.', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: '0xFF', value: 0xFF },
];

export const ItemList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Iron Sword', value: 0x01 },
  { label: 'Iron Blade', value: 0x02 },
  { label: 'Steel Sword', value: 0x03 },
  { label: 'Silver Sword', value: 0x04 },
  { label: 'Thin Sword', value: 0x05 },
  { label: 'Poison Sword', value: 0x06 },
  { label: 'Hero Sword', value: 0x07 },
  { label: 'Light Sword', value: 0x08 },
  { label: 'Durandal', value: 0x09 },
  { label: 'Armour Killer', value: 0x0A },
  { label: 'Rapier', value: 0x0B },
  { label: 'Killer Sword', value: 0x0C },
  { label: 'Lancebuster', value: 0x0D },
  { label: 'Wo Dao', value: 0x0E },
  { label: 'Sword of Seals', value: 0x0F },
  { label: 'Iron Spear', value: 0x10 },
  { label: 'Steel Spear', value: 0x11 },
  { label: 'Silver Spear', value: 0x12 },
  { label: 'Thin Spear', value: 0x13 },
  { label: 'Poison Spear', value: 0x14 },
  { label: 'Hero Spear', value: 0x15 },
  { label: 'Javelin', value: 0x16 },
  { label: 'Maltae', value: 0x17 },
  { label: 'Horse Killer', value: 0x18 },
  { label: 'Killer Spear', value: 0x19 },
  { label: 'Axebuster', value: 0x1A },
  { label: 'Iron Axe', value: 0x1B },
  { label: 'Steel Axe', value: 0x1C },
  { label: 'Silver Axe', value: 0x1D },
  { label: 'Poison Axe', value: 0x1E },
  { label: 'Hero Axe', value: 0x1F },
  { label: 'Hand Axe', value: 0x20 },
  { label: 'Armads', value: 0x21 },
  { label: 'Hammer', value: 0x22 },
  { label: 'Killer Axe', value: 0x23 },
  { label: 'Swordbuster', value: 0x24 },
  { label: 'Devil Axe', value: 0x25 },
  { label: 'Pole Axe', value: 0x26 },
  { label: 'Iron Bow', value: 0x27 },
  { label: 'Steel Bow', value: 0x28 },
  { label: 'Silver Bow', value: 0x29 },
  { label: 'Poison Bow', value: 0x2A },
  { label: 'Killer Bow', value: 0x2B },
  { label: 'Hero Bow', value: 0x2C },
  { label: 'Short Bow', value: 0x2D },
  { label: 'Long Bow', value: 0x2E },
  { label: 'Miugre', value: 0x2F },
  { label: 'Long Arch', value: 0x30 },
  { label: 'Iron Arch', value: 0x31 },
  { label: 'Killer Arch', value: 0x32 },
  { label: 'Fire', value: 0x33 },
  { label: 'Thunder', value: 0x34 },
  { label: 'Fimbulwinter', value: 0x35 },
  { label: 'Elfire', value: 0x36 },
  { label: 'Aircalibur', value: 0x37 },
  { label: 'Nosferatu', value: 0x38 },
  { label: 'Thunderstorm', value: 0x39 },
  { label: 'Forblaze', value: 0x3A },
  { label: 'Lightning', value: 0x3B },
  { label: 'Divine', value: 0x3C },
  { label: 'Purge', value: 0x3D },
  { label: 'Aureola', value: 0x3E },
  { label: 'Miru', value: 0x3F },
  { label: 'Rizziah', value: 0x40 },
  { label: 'Eclipse', value: 0x41 },
  { label: 'Apocalypse', value: 0x42 },
  { label: 'Live', value: 0x43 },
  { label: 'Relive', value: 0x44 },
  { label: 'Recover', value: 0x45 },
  { label: 'Libro', value: 0x46 },
  { label: 'Reserve', value: 0x47 },
  { label: 'Warp', value: 0x48 },
  { label: 'Rescue', value: 0x49 },
  { label: 'Rest', value: 0x4A },
  { label: 'Silence', value: 0x4B },
  { label: 'Sleep', value: 0x4C },
  { label: 'Torch', value: 0x4D },
  { label: 'Hammerne', value: 0x4E },
  { label: 'Watch', value: 0x4F },
  { label: 'Berserk', value: 0x50 },
  { label: 'Unlock', value: 0x51 },
  { label: 'Magic Shield', value: 0x52 },
  { label: 'Fire Dragon Stone', value: 0x53 },
  { label: 'Divine Dragon Stone', value: 0x54 },
  { label: 'Magic Dragon Stone', value: 0x55 },
  { label: 'Secret Book', value: 0x56 },
  { label: 'Goddess Statue', value: 0x57 },
  { label: 'Angel Robe', value: 0x58 },
  { label: 'Dragon Shield', value: 0x59 },
  { label: 'Energy Ring', value: 0x5A },
  { label: 'Speed Wing', value: 0x5B },
  { label: 'Talisman', value: 0x5C },
  { label: 'Boots', value: 0x5D },
  { label: 'Body Ring', value: 0x5E },
  { label: 'Hero\'s Proof', value: 0x5F },
  { label: 'Knight\'s Medal', value: 0x60 },
  { label: 'Orion\'s Arrow', value: 0x61 },
  { label: 'Dragon\'s Whip', value: 0x62 },
  { label: 'Priest\'s Ring', value: 0x63 },
  { label: 'Chest Key', value: 0x64 },
  { label: 'Door Key', value: 0x65 },
  { label: 'Bridge Key', value: 0x66 },
  { label: 'Thief Key', value: 0x67 },
  { label: 'Vulnerary', value: 0x68 },
  { label: 'Elixir', value: 0x69 },
  { label: 'Holy Water', value: 0x6A },
  { label: 'Torch', value: 0x6B },
  { label: 'Antitoxin', value: 0x6C },
  { label: 'Member Card', value: 0x6D },
  { label: 'Silver Card', value: 0x6E },
  { label: 'Gold', value: 0x6F },
  { label: 'Blessing of Darkness', value: 0x70 },
  { label: 'Exaccus', value: 0x71 },
  { label: 'Steel Broadsword', value: 0x72 },
  { label: 'Silver Broadsword', value: 0x73 },
  { label: 'Al\'s Sword', value: 0x74 },
  { label: 'Ganto\'s Spear', value: 0x75 },
  { label: 'Tiena\'s Staff', value: 0x76 },
  { label: 'Holy Maiden', value: 0x77 },
  { label: 'Dragon Killer', value: 0x78 },
  { label: 'White Gem', value: 0x79 },
  { label: 'Blue Gem', value: 0x7A },
  { label: 'Red Gem', value: 0x7B },
  { label: 'Delphi Shield', value: 0x7C },
  { label: 'Rune Sword', value: 0x7D },
  { label: 'Slender Spear', value: 0x7E },
  { label: 'Tomahawk', value: 0x7F },
];
