export const FE1Charactereditor4FE1Entries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
];

export const Chardata = [
  { label: 'Marth', value: 0x01 },
  { label: 'Sheeda', value: 0x02 },
  { label: 'Jeigan', value: 0x03 },
  { label: 'Kain', value: 0x04 },
  { label: 'Abel', value: 0x05 },
  { label: 'Doga', value: 0x06 },
  { label: 'Gordon', value: 0x07 },
  { label: 'Ricardo', value: 0x08 },
  { label: 'Riff', value: 0x09 },
  { label: 'Saji', value: 0x0A },
  { label: 'Maji', value: 0x0B },
  { label: 'Barts', value: 0x0C },
  { label: 'Kashim', value: 0x0D },
  { label: 'Oguma', value: 0x0E },
  { label: 'Daros', value: 0x0F },
  { label: 'Julian', value: 0x10 },
  { label: 'Rena', value: 0x11 },
  { label: 'Marich', value: 0x12 },
  { label: 'Navarre', value: 0x13 },
  { label: 'Hardin', value: 0x14 },
  { label: 'Wolf', value: 0x15 },
  { label: 'Zagaro', value: 0x16 },
  { label: 'Roshe', value: 0x17 },
  { label: 'Biraku', value: 0x18 },
  { label: 'Banutu', value: 0x19 },
  { label: 'Caesar', value: 0x1A },
  { label: 'Raddy', value: 0x1B },
  { label: 'Midia', value: 0x1C },
  { label: 'Katua', value: 0x1D },
  { label: 'Maria', value: 0x1E },
  { label: 'Minerva', value: 0x1F },
  { label: 'Linda', value: 0x20 },
  { label: 'George', value: 0x21 },
  { label: 'Tomth', value: 0x22 },
  { label: 'Mishelan', value: 0x23 },
  { label: 'Thomas', value: 0x24 },
  { label: 'Boa', value: 0x25 },
  { label: 'Alan', value: 0x26 },
  { label: 'Samson', value: 0x27 },
  { label: 'Beck', value: 0x28 },
  { label: 'Chainy', value: 0x29 },
  { label: 'Wendel', value: 0x2A },
  { label: 'Est', value: 0x2B },
  { label: 'Astria', value: 0x2C },
  { label: 'Machis', value: 0x2D },
  { label: 'Roger', value: 0x2E },
  { label: 'Jake', value: 0x2F },
  { label: 'Paola', value: 0x30 },
  { label: 'Chiki', value: 0x31 },
  { label: 'Lawrence', value: 0x32 },
  { label: 'Ellis', value: 0x33 },
  { label: 'Saber', value: 0x34 },
  { label: 'Gato', value: 0x35 },
  { label: 'Gazack', value: 0x81 },
  { label: 'Wylar', value: 0x82 },
  { label: 'Grunia Soldier', value: 0x83 },
  { label: 'Gomes', value: 0x84 },
  { label: 'Garda Soldier', value: 0x85 },
  { label: 'Samsian', value: 0x86 },
  { label: 'Navarre', value: 0x87 },
  { label: 'Merak', value: 0x88 },
  { label: 'Hermine', value: 0x89 },
  { label: 'Mariones', value: 0x8A },
  { label: 'Benson', value: 0x8B },
  { label: 'Canaris', value: 0x8C },
  { label: 'Manuu', value: 0x8D },
  { label: 'Zhukov', value: 0x8E },
  { label: 'Shozen', value: 0x8F },
  { label: 'Heimler', value: 0x90 },
  { label: 'Gigash', value: 0x91 },
  { label: 'Jiol', value: 0x92 },
  { label: 'Bozen', value: 0x93 },
  { label: 'Holstat', value: 0x94 },
  { label: 'Stallone', value: 0x95 },
  { label: 'Hyman', value: 0x96 },
  { label: 'Zemcel', value: 0x97 },
  { label: 'Ordyne', value: 0x98 },
  { label: 'Camus', value: 0x99 },
  { label: 'Misheil', value: 0x9A },
  { label: 'Moses', value: 0x9B },
  { label: 'Garnef', value: 0x9C },
  { label: 'Mediuth', value: 0x9D },
  { label: 'Maria', value: 0x9E },
  { label: 'Durhua Soldier', value: 0x9F },
  { label: 'Gra Soldier', value: 0xA0 },
  { label: 'Peraty Soldier', value: 0xA1 },
  { label: 'Cashmere Soldier', value: 0xA2 },
  { label: 'Black Knight', value: 0xA3 },
  { label: 'Khadein Mage', value: 0xA4 },
  { label: 'Minerva', value: 0xA5 },
  { label: 'Basilisk', value: 0xA6 },
  { label: 'Salamander', value: 0xA7 },
  { label: 'Narga', value: 0xA8 },
  { label: 'Gaia', value: 0xA9 },
  { label: 'Iron Knight', value: 0xAA },
  { label: 'Dragon Knight', value: 0xAB },
  { label: 'Enemy', value: 0xAC },
  { label: 'Daros', value: 0xAD },
  { label: 'Ricardo', value: 0xAE },
  { label: 'Macedonia Soldier', value: 0xAF },
  { label: 'Katua', value: 0xB0 },
  { label: 'Paola', value: 0xB1 },
  { label: 'Est', value: 0xB2 },
  { label: 'White Knight', value: 0xB3 },
  { label: 'Gra Soldier', value: 0xB4 },
  { label: 'Rogue', value: 0xB5 },
  { label: 'Wendel', value: 0xB6 },
  { label: 'Raman Soldier', value: 0xB7 },
  { label: 'Thebes Mage', value: 0xB8 },
  { label: 'Priest Army', value: 0xB9 },
  { label: 'Chiki', value: 0xBA },
  { label: 'King Grunia', value: 0xBB },
  { label: 'Reinforcements', value: 0xBC },
  { label: 'Kashim', value: 0xBD },
  { label: 'Saber', value: 0xBE },
  { label: 'Jake', value: 0xBF },
  { label: 'Lawrence', value: 0xC0 },
  { label: 'Chainy', value: 0xC1 },
  { label: 'Garnef', value: 0xC2 },
  { label: 'Roger', value: 0xC3 },
  { label: 'Machis', value: 0xC4 },
  { label: 'Astria', value: 0xC5 },
];

export const Classlist = [
  { label: 'Cavalier', value: 0x01 },
  { label: 'Knight', value: 0x02 },
  { label: 'Pegasus Knight', value: 0x03 },
  { label: 'Paladin', value: 0x04 },
  { label: 'Dracoknight', value: 0x05 },
  { label: 'Mercenary', value: 0x06 },
  { label: 'Fighter', value: 0x07 },
  { label: 'Pirate', value: 0x08 },
  { label: 'Thief', value: 0x09 },
  { label: 'Hero', value: 0x0A },
  { label: 'Archer', value: 0x0B },
  { label: 'Hunter', value: 0x0C },
  { label: 'Ballistician', value: 0x0D },
  { label: 'Horseman', value: 0x0E },
  { label: 'Sniper', value: 0x0F },
  { label: 'Commando', value: 0x10 },
  { label: 'Manakete', value: 0x11 },
  { label: 'Mage', value: 0x12 },
  { label: 'Priest', value: 0x13 },
  { label: 'Bishop', value: 0x14 },
  { label: 'Lord', value: 0x15 },
  { label: 'General', value: 0x16 },
];

export const Itemlist = [
  { label: '---', value: 0x00 },
  { label: 'Silver Sword', value: 0x01 },
  { label: 'Iron Sword', value: 0x02 },
  { label: 'Steel Sword', value: 0x03 },
  { label: 'Armorslayer', value: 0x04 },
  { label: 'Rapier', value: 0x05 },
  { label: 'Wyrmslayer', value: 0x06 },
  { label: 'Killing Edge', value: 0x07 },
  { label: 'Mercurius', value: 0x08 },
  { label: 'Levin Sword', value: 0x09 },
  { label: 'Devil Sword', value: 0x0A },
  { label: 'Falchion', value: 0x0B },
  { label: 'Iron Lance', value: 0x0C },
  { label: 'Ridersbane', value: 0x0D },
  { label: 'Silver Lance', value: 0x0E },
  { label: 'Javelin', value: 0x0F },
  { label: 'Gradivus', value: 0x10 },
  { label: 'Iron Bow', value: 0x11 },
  { label: 'Steel Bow', value: 0x12 },
  { label: 'Bowgun', value: 0x13 },
  { label: 'Silver Bow', value: 0x14 },
  { label: 'Parthia', value: 0x15 },
  { label: 'Quincrane', value: 0x16 },
  { label: 'Stonehedge', value: 0x17 },
  { label: 'Fire Gun', value: 0x18 },
  { label: 'Thunderbolt', value: 0x19 },
  { label: 'Elephant', value: 0x1A },
  { label: 'Iron Axe', value: 0x1B },
  { label: 'Steel Axe', value: 0x1C },
  { label: 'Hammer', value: 0x1D },
  { label: 'Devil Axe', value: 0x1E },
  { label: 'Hand Axe', value: 0x1F },
  { label: 'Wyvern*', value: 0x20 },
  { label: 'Gargoyle*', value: 0x21 },
  { label: 'Magicstone', value: 0x22 },
  { label: 'Divinestone', value: 0x23 },
  { label: 'Firestone', value: 0x24 },
  { label: 'Salamander*', value: 0x25 },
  { label: 'Earthstone', value: 0x26 },
  { label: 'Shenron*', value: 0x27 },
  { label: 'Neptune*', value: 0x28 },
  { label: 'Darkdragon*', value: 0x29 },
  { label: 'Magicstone?', value: 0x2A },
  { label: 'Fire', value: 0x2B },
  { label: 'Thunder', value: 0x2C },
  { label: 'Blizzard', value: 0x2D },
  { label: 'Elfire', value: 0x2E },
  { label: 'Bolganone', value: 0x2F },
  { label: 'Thoron', value: 0x30 },
  { label: 'Swarm', value: 0x31 },
  { label: 'Aura', value: 0x32 },
  { label: 'Excalibur', value: 0x33 },
  { label: 'Imhullu', value: 0x34 },
  { label: 'Starlight', value: 0x35 },
  { label: 'Heal', value: 0x36 },
  { label: 'Mend', value: 0x37 },
  { label: 'Recover', value: 0x38 },
  { label: 'Helarn*', value: 0x39 },
  { label: 'Warp', value: 0x3A },
  { label: 'Hammerne', value: 0x3B },
  { label: 'Physic', value: 0x3C },
  { label: 'Barrier', value: 0x3D },
  { label: 'Fortify', value: 0x3E },
  { label: 'Aum', value: 0x3F },
  { label: 'Vulnerary', value: 0x40 },
  { label: 'Pure Water', value: 0x41 },
  { label: 'Door Key', value: 0x42 },
  { label: 'Bridge Key', value: 0x43 },
  { label: 'Lockpick', value: 0x44 },
  { label: 'Unequipped', value: 0x45 },
  { label: 'Dragonshield', value: 0x46 },
  { label: 'Talisman', value: 0x47 },
  { label: 'Boots', value: 0x48 },
  { label: 'Manual', value: 0x49 },
  { label: 'Secret Book', value: 0x4A },
  { label: 'Power Ring', value: 0x4B },
  { label: 'Telescope*', value: 0x4C },
  { label: 'Speed Ring', value: 0x4D },
  { label: 'Goddess Icon', value: 0x4E },
  { label: 'Angelic Robe', value: 0x4F },
  { label: 'Knight Crest', value: 0x50 },
  { label: 'Hero Crest', value: 0x51 },
  { label: 'Guiding Ring', value: 0x52 },
  { label: 'Orion\'s Bolt', value: 0x53 },
  { label: 'Elysian Whip', value: 0x54 },
  { label: 'Geosphere', value: 0x55 },
  { label: 'Time Orb*', value: 0x56 },
  { label: 'Dark Orb*', value: 0x57 },
  { label: 'Starsphere', value: 0x58 },
  { label: 'Member Card', value: 0x59 },
  { label: 'Silver Card', value: 0x5A },
  { label: 'Lightsphere', value: 0x5B },
  { label: 'Fire Emblem', value: 0x5C },
];
