export const EndingsList = [
  { label: 'Eirika Mode Ending Slot #001', value: 0 },
  { label: 'Eirika Mode Ending Slot #002', value: 1 },
  { label: 'Eirika Mode Ending Slot #003', value: 2 },
  { label: 'Eirika Mode Ending Slot #004', value: 3 },
  { label: 'Eirika Mode Ending Slot #005', value: 4 },
  { label: 'Eirika Mode Ending Slot #006', value: 5 },
  { label: 'Eirika Mode Ending Slot #007', value: 6 },
  { label: 'Eirika Mode Ending Slot #008', value: 7 },
  { label: 'Eirika Mode Ending Slot #009', value: 8 },
  { label: 'Eirika Mode Ending Slot #010', value: 9 },
  { label: 'Eirika Mode Ending Slot #011', value: 10 },
  { label: 'Eirika Mode Ending Slot #012', value: 11 },
  { label: 'Eirika Mode Ending Slot #013', value: 12 },
  { label: 'Eirika Mode Ending Slot #014', value: 13 },
  { label: 'Eirika Mode Ending Slot #015', value: 14 },
  { label: 'Eirika Mode Ending Slot #016', value: 15 },
  { label: 'Eirika Mode Ending Slot #017', value: 16 },
  { label: 'Eirika Mode Ending Slot #018', value: 17 },
  { label: 'Eirika Mode Ending Slot #019', value: 18 },
  { label: 'Eirika Mode Ending Slot #020', value: 19 },
  { label: 'Eirika Mode Ending Slot #021', value: 20 },
  { label: 'Eirika Mode Ending Slot #022', value: 21 },
  { label: 'Eirika Mode Ending Slot #023', value: 22 },
  { label: 'Eirika Mode Ending Slot #024', value: 23 },
  { label: 'Eirika Mode Ending Slot #025', value: 24 },
  { label: 'Eirika Mode Ending Slot #026', value: 25 },
  { label: 'Eirika Mode Ending Slot #027', value: 26 },
  { label: 'Eirika Mode Ending Slot #028', value: 27 },
  { label: 'Eirika Mode Ending Slot #029', value: 28 },
  { label: 'Eirika Mode Ending Slot #030', value: 29 },
  { label: 'Eirika Mode Ending Slot #031', value: 30 },
  { label: 'Eirika Mode Ending Slot #032', value: 31 },
  { label: 'Eirika Mode Ending Slot #033', value: 32 },
  { label: 'Eirika Mode Ending Slot #034', value: 33 },
  { label: 'Eirika Mode Ending Slot #035', value: 34 },
  { label: 'Eirika Mode Ending Slot #036', value: 35 },
  { label: 'Eirika Mode Ending Slot #037', value: 36 },
  { label: 'Eirika Mode Ending Slot #038', value: 37 },
  { label: 'Eirika Mode Ending Slot #039', value: 38 },
  { label: 'Eirika Mode Ending Slot #040', value: 39 },
  { label: 'Eirika Mode Ending Slot #041', value: 40 },
  { label: 'Eirika Mode Ending Slot #042', value: 41 },
  { label: 'Eirika Mode Ending Slot #043', value: 42 },
  { label: 'Eirika Mode Ending Slot #044', value: 43 },
  { label: 'Eirika Mode Ending Slot #045', value: 44 },
  { label: 'Eirika Mode Ending Slot #046', value: 45 },
  { label: 'Eirika Mode Ending Slot #047', value: 46 },
  { label: 'Eirika Mode Ending Slot #048', value: 47 },
  { label: 'Eirika Mode Ending Slot #049', value: 48 },
  { label: 'Eirika Mode Ending Slot #050', value: 49 },
  { label: 'Eirika Mode Ending Slot #051', value: 50 },
  { label: 'Eirika Mode Ending Slot #052', value: 51 },
  { label: 'Eirika Mode Ending Slot #053', value: 52 },
  { label: 'Eirika Mode Ending Slot #054', value: 53 },
  { label: 'Eirika Mode Ending Slot #055', value: 54 },
  { label: 'Eirika Mode Ending Slot #056', value: 55 },
  { label: 'Eirika Mode Ending Slot #057', value: 56 },
  { label: 'Eirika Mode Ending Slot #058', value: 57 },
  { label: 'Eirika Mode Ending Slot #059', value: 58 },
  { label: 'Eirika Mode Ending Slot #060', value: 59 },
  { label: 'Eirika Mode Ending Slot #061', value: 60 },
  { label: 'Eirika Mode Ending Slot #062', value: 61 },
  { label: 'Eirika Mode Ending Slot #063', value: 62 },
  { label: 'Eirika Mode Ending Slot #064', value: 63 },
  { label: 'Eirika Mode Ending Slot #065', value: 64 },
  { label: 'Eirika Mode Ending Slot #066', value: 65 },
  { label: 'Eirika Mode Ending Slot #067', value: 66 },
  { label: 'NOT TO BE EDITED', value: 67 },
  { label: 'Ephraim Mode Ending Slot #001', value: 68 },
  { label: 'Ephraim Mode Ending Slot #002', value: 69 },
  { label: 'Ephraim Mode Ending Slot #003', value: 70 },
  { label: 'Ephraim Mode Ending Slot #004', value: 71 },
  { label: 'Ephraim Mode Ending Slot #005', value: 72 },
  { label: 'Ephraim Mode Ending Slot #006', value: 73 },
  { label: 'Ephraim Mode Ending Slot #007', value: 74 },
  { label: 'Ephraim Mode Ending Slot #008', value: 75 },
  { label: 'Ephraim Mode Ending Slot #009', value: 76 },
  { label: 'Ephraim Mode Ending Slot #010', value: 77 },
  { label: 'Ephraim Mode Ending Slot #011', value: 78 },
  { label: 'Ephraim Mode Ending Slot #012', value: 79 },
  { label: 'Ephraim Mode Ending Slot #013', value: 80 },
  { label: 'Ephraim Mode Ending Slot #014', value: 81 },
  { label: 'Ephraim Mode Ending Slot #015', value: 82 },
  { label: 'Ephraim Mode Ending Slot #016', value: 83 },
  { label: 'Ephraim Mode Ending Slot #017', value: 84 },
  { label: 'Ephraim Mode Ending Slot #018', value: 85 },
  { label: 'Ephraim Mode Ending Slot #019', value: 86 },
  { label: 'Ephraim Mode Ending Slot #020', value: 87 },
  { label: 'Ephraim Mode Ending Slot #021', value: 88 },
  { label: 'Ephraim Mode Ending Slot #022', value: 89 },
  { label: 'Ephraim Mode Ending Slot #023', value: 90 },
  { label: 'Ephraim Mode Ending Slot #024', value: 91 },
  { label: 'Ephraim Mode Ending Slot #025', value: 92 },
  { label: 'Ephraim Mode Ending Slot #026', value: 93 },
  { label: 'Ephraim Mode Ending Slot #027', value: 94 },
  { label: 'Ephraim Mode Ending Slot #028', value: 95 },
  { label: 'Ephraim Mode Ending Slot #029', value: 96 },
  { label: 'Ephraim Mode Ending Slot #030', value: 97 },
  { label: 'Ephraim Mode Ending Slot #031', value: 98 },
  { label: 'Ephraim Mode Ending Slot #032', value: 99 },
  { label: 'Ephraim Mode Ending Slot #033', value: 100 },
  { label: 'Ephraim Mode Ending Slot #034', value: 101 },
  { label: 'Ephraim Mode Ending Slot #035', value: 102 },
  { label: 'Ephraim Mode Ending Slot #036', value: 103 },
  { label: 'Ephraim Mode Ending Slot #037', value: 104 },
  { label: 'Ephraim Mode Ending Slot #038', value: 105 },
  { label: 'Ephraim Mode Ending Slot #039', value: 106 },
  { label: 'Ephraim Mode Ending Slot #040', value: 107 },
  { label: 'Ephraim Mode Ending Slot #041', value: 108 },
  { label: 'Ephraim Mode Ending Slot #042', value: 109 },
  { label: 'Ephraim Mode Ending Slot #043', value: 110 },
  { label: 'Ephraim Mode Ending Slot #044', value: 111 },
  { label: 'Ephraim Mode Ending Slot #045', value: 112 },
  { label: 'Ephraim Mode Ending Slot #046', value: 113 },
  { label: 'Ephraim Mode Ending Slot #047', value: 114 },
  { label: 'Ephraim Mode Ending Slot #048', value: 115 },
  { label: 'Ephraim Mode Ending Slot #049', value: 116 },
  { label: 'Ephraim Mode Ending Slot #050', value: 117 },
  { label: 'Ephraim Mode Ending Slot #051', value: 118 },
  { label: 'Ephraim Mode Ending Slot #052', value: 119 },
  { label: 'Ephraim Mode Ending Slot #053', value: 120 },
  { label: 'Ephraim Mode Ending Slot #054', value: 121 },
  { label: 'Ephraim Mode Ending Slot #055', value: 122 },
  { label: 'Ephraim Mode Ending Slot #056', value: 123 },
  { label: 'Ephraim Mode Ending Slot #057', value: 124 },
  { label: 'Ephraim Mode Ending Slot #058', value: 125 },
  { label: 'Ephraim Mode Ending Slot #059', value: 126 },
  { label: 'Ephraim Mode Ending Slot #060', value: 127 },
  { label: 'Ephraim Mode Ending Slot #061', value: 128 },
  { label: 'Ephraim Mode Ending Slot #062', value: 129 },
  { label: 'Ephraim Mode Ending Slot #063', value: 130 },
  { label: 'Ephraim Mode Ending Slot #064', value: 131 },
  { label: 'Ephraim Mode Ending Slot #065', value: 132 },
  { label: 'Ephraim Mode Ending Slot #066', value: 133 },
  { label: 'Ephraim Mode Ending Slot #067', value: 134 },
];

export const EndingTypeList = [
  { label: 'Disabled', value: 0x00 },
  { label: 'Solo Ending', value: 0x01 },
  { label: 'Paired Ending', value: 0x02 },
];

export const EndingPartnerList = [
  { label: 'None (Solo Ending)', value: 0x00 },
  { label: 'Eirika', value: 0x01 },
  { label: 'Seth', value: 0x02 },
  { label: 'Gilliam', value: 0x03 },
  { label: 'Franz', value: 0x04 },
  { label: 'Moulder', value: 0x05 },
  { label: 'Vanessa', value: 0x06 },
  { label: 'Ross', value: 0x07 },
  { label: 'Neimi', value: 0x08 },
  { label: 'Colm', value: 0x09 },
  { label: 'Garcia', value: 0x0A },
  { label: 'Innes', value: 0x0B },
  { label: 'Lute', value: 0x0C },
  { label: 'Natasha', value: 0x0D },
  { label: 'Cormag', value: 0x0E },
  { label: 'Ephraim', value: 0x0F },
  { label: 'Forde', value: 0x10 },
  { label: 'Kyle', value: 0x11 },
  { label: 'Amelia', value: 0x12 },
  { label: 'Artur', value: 0x13 },
  { label: 'Gerik', value: 0x14 },
  { label: 'Tethys', value: 0x15 },
  { label: 'Marisa', value: 0x16 },
  { label: 'Saleh', value: 0x17 },
  { label: 'Ewan', value: 0x18 },
  { label: 'L\'Arachel', value: 0x19 },
  { label: 'Dozla', value: 0x1A },
  { label: 'Rennac', value: 0x1C },
  { label: 'Duessel', value: 0x1D },
  { label: 'Myrrh', value: 0x1E },
  { label: 'Knoll', value: 0x1F },
  { label: 'Joshua', value: 0x20 },
  { label: 'Syrene', value: 0x21 },
  { label: 'Tana', value: 0x22 },
];
