export const ClassList = [
  { label: 'Lord', value: 0 },
  { label: 'Pegasus Knight', value: 1 },
  { label: 'Pegasus Knight (F)', value: 2 },
  { label: 'Falcon Knight', value: 3 },
  { label: 'Dracoknight', value: 4 },
  { label: 'Dracoknight (F)', value: 5 },
  { label: 'Cavalier', value: 6 },
  { label: 'Cavalier (F)', value: 7 },
  { label: 'Paladin', value: 8 },
  { label: 'Paladin (F)', value: 9 },
  { label: 'Armour Knight', value: 10 },
  { label: 'Armour Knight (F)', value: 11 },
  { label: 'General', value: 12 },
  { label: 'General (F)', value: 13 },
  { label: 'Archer', value: 14 },
  { label: 'Archer (F)', value: 15 },
  { label: 'Sniper', value: 16 },
  { label: 'Sniper (F)', value: 17 },
  { label: 'Mercenary', value: 18 },
  { label: 'Hero', value: 19 },
  { label: 'Myrmidon', value: 20 },
  { label: 'Myrmidon (F)', value: 21 },
  { label: 'Swordmaster', value: 22 },
  { label: 'Swordmaster (F)', value: 23 },
  { label: 'Fighter', value: 24 },
  { label: 'Warrior', value: 25 },
  { label: 'Hunter', value: 26 },
  { label: 'Horseman', value: 27 },
  { label: 'Barbarian', value: 28 },
  { label: 'Pirate', value: 29 },
  { label: 'Berserker', value: 30 },
  { label: 'Dark Mage', value: 31 },
  { label: 'Sorcerer', value: 32 },
  { label: 'Mage', value: 33 },
  { label: 'Mage (F)', value: 34 },
  { label: 'Priest', value: 35 },
  { label: 'Cleric', value: 36 },
  { label: 'Sage', value: 37 },
  { label: 'Sage (F)', value: 38 },
  { label: 'Bishop', value: 39 },
  { label: 'Bishop (F)', value: 40 },
  { label: 'Thief', value: 41 },
  { label: 'Mamkute', value: 42 },
  { label: 'Mamkute (F)', value: 43 },
  { label: 'Ballistician', value: 44 },
  { label: 'Commando', value: 45 },
  { label: 'Dancer', value: 46 },
  { label: 'Soldier', value: 47 },
  { label: 'Emperor', value: 48 },
  { label: 'Magic Dragon', value: 49 },
  { label: 'Earth Dragon', value: 50 },
  { label: 'Fire Dragon', value: 51 },
  { label: 'Ice Dragon', value: 52 },
  { label: 'Wyvern', value: 53 },
  { label: 'Divine Dragon', value: 54 },
  { label: 'Dark Dragon', value: 55 },
  { label: 'Dummy', value: 56 },
];

export const MovementTypes = [
  { label: '- Default/Lord', value: 0 },
  { label: '- Knight', value: 1 },
  { label: '- General', value: 2 },
  { label: '- Cavalier', value: 3 },
  { label: '- Paladin', value: 4 },
  { label: '- Merc/Myrm', value: 5 },
  { label: '- Hero/Swdmaster', value: 6 },
  { label: '- Fighter', value: 7 },
  { label: '- Warrior', value: 8 },
  { label: '- Pirate', value: 9 },
  { label: '- Berserker', value: 10 },
  { label: '- Thief', value: 11 },
  { label: '- Archer/Dismounted Knight', value: 12 },
  { label: '- Sniper/Dismounted Knight (F)', value: 13 },
  { label: '- Hunter', value: 14 },
  { label: '- Horsemen', value: 15 },
  { label: '- Chameleon', value: 16 },
  { label: '- Manakete', value: 17 },
  { label: '- Magic Users', value: 18 },
  { label: '- Unused', value: 19 },
  { label: '- Promoted Magic Users', value: 20 },
  { label: '- Flying', value: 21 },
  { label: '- Magic Dragon', value: 22 },
  { label: '- Soldier', value: 23 },
  { label: '- Ballistician', value: 24 },
];

export const WeaponUsage = [
  { label: 'None/Blank', value: 0x00 },
  { label: 'Special', value: 0x02 },
  { label: 'Normal', value: 0x03 },
  { label: 'Dragonstone', value: 0x05 },
];

export const WeaponLevels = [
  { label: 'None', value: 0x00 },
  { label: 'E', value: 0x01 },
  { label: 'D', value: 0x1F },
  { label: 'C', value: 0x4C },
  { label: 'B', value: 0x88 },
  { label: 'A', value: 0xC4 },
];

export const ReclassSets = [
  { label: 'No Reclass', value: 0x00 },
  { label: 'Set 1 (M)', value: 0x01 },
  { label: 'Set 2 (M2)', value: 0x02 },
  { label: 'Set 3 (F)', value: 0x03 },
  { label: 'Set 4 (M-Pro)', value: 0x04 },
  { label: 'Set 5 (M-Pro 2)', value: 0x05 },
  { label: 'Set 6 (F-Pro)', value: 0x06 },
  { label: 'Custom', value: 0x07 },
  { label: 'Custom', value: 0x08 },
  { label: 'Custom', value: 0x09 },
  { label: 'Custom', value: 0x0A },
  { label: 'Custom', value: 0x0B },
  { label: 'Custom', value: 0x0C },
  { label: 'Custom', value: 0x0D },
  { label: 'Custom', value: 0x0E },
  { label: 'Custom', value: 0x0F },
];

export const ReclassLines = [
  { label: 'Pegasus Knights', value: 0x00 },
  { label: 'Cavaliers', value: 0x01 },
  { label: 'Armour Knights', value: 0x02 },
  { label: 'Archers', value: 0x03 },
  { label: 'Mercenaries', value: 0x04 },
  { label: 'Myrmidons', value: 0x05 },
  { label: 'Fighters', value: 0x06 },
  { label: 'Hunters', value: 0x07 },
  { label: 'Pirates', value: 0x08 },
  { label: 'Shamans', value: 0x09 },
  { label: 'Mages', value: 0x0A },
  { label: 'Clerics', value: 0x0B },
  { label: 'Cannot reclass', value: 0xFF },
];

export const UnitTypes = [
  { label: 'Normal', value: 0x00 },
  { label: 'Dragon', value: 0x01 },
  { label: 'Mediuth', value: 0x02 },
  { label: 'Armor', value: 0x04 },
  { label: 'Ballistician', value: 0x08 },
  { label: 'Mounted', value: 0x10 },
  { label: 'Flying', value: 0x20 },
  { label: 'Manakete', value: 0x40 },
  { label: 'Dragon', value: 0x41 },
  { label: 'Dragon (Earth)', value: 0x42 },
  { label: 'Sword', value: 0x80 },
];

export const WeaponLocks = [
  { label: 'None', value: 0x00 },
  { label: 'Longbow', value: 0x01 },
];

export const Gender = [
  { label: 'Male', value: 0 },
  { label: 'Female', value: 1 },
];

export const Experience = [
  { label: 'Unpromoted', value: 0x00 },
  { label: 'Unpromoted + Boost', value: 0x04 },
  { label: 'Promoted', value: 0x08 },
  { label: 'Can Imitate', value: 0x80 },
];

export const ClassAbilities = [
  { label: 'None', value: 0x00 },
  { label: 'Can Dance', value: 0x01 },
  { label: '+5% Hit', value: 0x02 },
  { label: '+10% Avoid', value: 0x04 },
  { label: '+5% Crit', value: 0x08 },
  { label: '+5% Hit/Crit', value: 0x0A },
  { label: '+10% Crit', value: 0x10 },
  { label: 'Open Locks Without Keys', value: 0x20 },
  { label: 'On clerics, more staff EXP?', value: 0x40 },
  { label: 'Enemy Only', value: 0x80 },
];

export const ClassAbilities2 = [
  { label: 'None', value: 0x00 },
  { label: '?', value: 0x01 },
  { label: 'Is Dragon', value: 0x02 },
  { label: '?', value: 0x04 },
  { label: '?', value: 0x08 },
  { label: '?', value: 0x0A },
  { label: '?', value: 0x10 },
  { label: '?', value: 0x20 },
  { label: '?', value: 0x40 },
  { label: 'Unused Class/Enemy Only', value: 0x80 },
];

export const ClassListPointers = [
  { label: 'None', value: 0x00 },
  { label: 'Lord', value: 0x90D8 },
  { label: 'Pegasus Knight', value: 0x9128 },
  { label: 'Pegasus Knight F', value: 0x9178 },
  { label: 'Falcon Knight', value: 0x91C8 },
  { label: 'Dracoknight', value: 0x9218 },
  { label: 'Dracoknight (F)', value: 0x9268 },
  { label: 'Cavalier', value: 0x92B8 },
  { label: 'Cavalier (F)', value: 0x9308 },
  { label: 'Paladin', value: 0x9358 },
  { label: 'Paladin (F)', value: 0x93A8 },
  { label: 'Knight', value: 0x93F8 },
  { label: 'Knight F', value: 0x9448 },
  { label: 'General', value: 0x9498 },
  { label: 'General F', value: 0x94E8 },
  { label: 'Archer', value: 0x9538 },
  { label: 'Archer (F)', value: 0x9588 },
  { label: 'Sniper', value: 0x95D8 },
  { label: 'Sniper (F)', value: 0x9628 },
  { label: 'Mercenary', value: 0x9678 },
  { label: 'Hero', value: 0x96C8 },
  { label: 'Myrmidon', value: 0x9718 },
  { label: 'Myrmidon (F)', value: 0x9768 },
  { label: 'Swordmaster', value: 0x97B8 },
  { label: 'Swordmaster (F)', value: 0x9808 },
  { label: 'Fighter', value: 0x9858 },
  { label: 'Warrior', value: 0x98A8 },
  { label: 'Hunter', value: 0x98F8 },
  { label: 'Horsemen', value: 0x9948 },
  { label: 'Barbarian', value: 0x9998 },
  { label: 'Pirate', value: 0x99E8 },
  { label: 'Berserker', value: 0x9A38 },
  { label: 'Dark Mage', value: 0x9A88 },
  { label: 'Sorcerer', value: 0x9AD8 },
  { label: 'Mage', value: 0x9B28 },
  { label: 'Mage (F)', value: 0x9B78 },
  { label: 'Curate', value: 0x9BC8 },
  { label: 'Cleric', value: 0x9C18 },
  { label: 'Sage', value: 0x9C68 },
  { label: 'Sage (F)', value: 0x9CB8 },
  { label: 'Bishop', value: 0x9D08 },
  { label: 'Bishop (F)', value: 0x9D58 },
  { label: 'Thief', value: 0x9DA8 },
  { label: 'Manakete', value: 0x9DF8 },
  { label: 'Manakete (F)', value: 0x9E48 },
  { label: 'Ballistician', value: 0x9E98 },
  { label: 'Chameleon', value: 0x9EE8 },
  { label: 'Dancer', value: 0x9F38 },
  { label: 'Soldier', value: 0x9F88 },
  { label: 'Emperor', value: 0x9FD8 },
  { label: 'Magic Dragon', value: 0xA028 },
  { label: 'Earth Dragon', value: 0xA078 },
  { label: 'Fire Dragon', value: 0xA0C8 },
  { label: 'Ice Dragon', value: 0xA118 },
  { label: 'Wyvern', value: 0xA168 },
  { label: 'Divine Dragon', value: 0xA1B8 },
  { label: 'Dark Dragon', value: 0xA208 },
];

export const MoveSound = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Foot', value: 0x01 },
  { label: 'Bandit', value: 0x02 },
  { label: 'Armour', value: 0x03 },
  { label: 'Cavalier', value: 0x04 },
  { label: 'Paladin', value: 0x05 },
  { label: 'Pegasus', value: 0x06 },
  { label: 'Wyvern', value: 0x07 },
  { label: 'Ballista', value: 0x08 },
  { label: 'Dragon', value: 0x09 },
];
