export const Standinglist = [
  { label: 'Ephraim Lord', value: 0 },
  { label: 'Eirika Lord', value: 1 },
  { label: 'Ephraim Master Lord', value: 2 },
  { label: 'Eirika Master Lord', value: 3 },
  { label: 'Socialknight', value: 4 },
  { label: 'Paladin', value: 5 },
  { label: 'Armour Knight', value: 6 },
  { label: 'General', value: 7 },
  { label: 'Thief', value: 8 },
  { label: 'Mamkute', value: 9 },
  { label: 'Mercenary', value: 10 },
  { label: 'Mercenary (F)', value: 11 },
  { label: 'Hero', value: 12 },
  { label: 'Hero (F)', value: 13 },
  { label: 'Swordfighter', value: 14 },
  { label: 'Swordfighter (F)', value: 15 },
  { label: 'Swordmaster', value: 16 },
  { label: 'Swordmaster (F)', value: 17 },
  { label: 'Assassin', value: 18 },
  { label: 'Assassin (F)', value: 19 },
  { label: 'Archer', value: 20 },
  { label: 'Archer (F)', value: 21 },
  { label: 'Sniper', value: 22 },
  { label: 'Sniper (F)', value: 23 },
  { label: 'Ranger', value: 24 },
  { label: 'Dragon Knight', value: 25 },
  { label: 'Dragon Knight (F)', value: 26 },
  { label: 'Dragon Master', value: 27 },
  { label: 'Dragon Master (F)', value: 28 },
  { label: 'Wyvern Knight', value: 29 },
  { label: 'Mage', value: 30 },
  { label: 'Mage (F)', value: 31 },
  { label: 'Sage', value: 32 },
  { label: 'Sage (F)', value: 33 },
  { label: 'Mage Knight', value: 34 },
  { label: 'Mage Knight (F)', value: 35 },
  { label: 'Bishop', value: 36 },
  { label: 'Bishop (F)', value: 37 },
  { label: 'Shaman', value: 38 },
  { label: 'Druid', value: 39 },
  { label: 'Summoner', value: 40 },
  { label: 'Rogue', value: 41 },
  { label: 'Gorgon Egg', value: 42 },
  { label: 'Great Knight', value: 43 },
  { label: 'Trainee Soldier (2)', value: 44 },
  { label: 'Trainee Fighter (3)', value: 45 },
  { label: 'Trainee Mage (3)', value: 46 },
  { label: 'Mamkute', value: 47 },
  { label: 'Mamkute (F)', value: 48 },
  { label: 'Fighter', value: 49 },
  { label: 'Warrior', value: 50 },
  { label: 'Mountain Thief', value: 51 },
  { label: 'Pirate', value: 52 },
  { label: 'Berserker', value: 53 },
  { label: 'Monk', value: 54 },
  { label: 'Priest', value: 55 },
  { label: 'Bard', value: 56 },
  { label: 'Pegasus Knight', value: 57 },
  { label: 'Falcon Knight', value: 58 },
  { label: 'Sister', value: 59 },
  { label: 'Troubadour', value: 60 },
  { label: 'Valkyrie', value: 61 },
  { label: 'Dancer', value: 62 },
  { label: 'Soldier', value: 63 },
  { label: 'Necromancer', value: 64 },
  { label: 'Fleet', value: 65 },
  { label: 'Ghost Fighter', value: 66 },
  { label: 'Zombie', value: 67 },
  { label: 'Mummy', value: 68 },
  { label: 'Skeleton', value: 69 },
  { label: 'Skeleton (Bow)', value: 70 },
  { label: 'Hellbone', value: 71 },
  { label: 'Hellbone (Bow)', value: 72 },
  { label: 'Bael', value: 73 },
  { label: 'Elder Bael', value: 74 },
  { label: 'Cyclops', value: 75 },
  { label: 'Mauthedoog', value: 76 },
  { label: 'Cerberus', value: 77 },
  { label: 'Tarvos', value: 78 },
  { label: 'Macdaire', value: 79 },
  { label: 'Bigl', value: 80 },
  { label: 'Archbigl', value: 81 },
  { label: 'Gorgon', value: 82 },
  { label: 'Gorgon Egg', value: 83 },
  { label: 'Gargoyle', value: 84 },
  { label: 'Death Gargoyle', value: 85 },
  { label: 'Dragon Zombie', value: 86 },
  { label: 'Demon King', value: 87 },
  { label: 'Archer on Ballista', value: 88 },
  { label: 'Archer on Iron Ballista', value: 89 },
  { label: 'Archer on Killer Ballista', value: 90 },
  { label: 'Ballista', value: 91 },
  { label: 'Iron Ballista', value: 92 },
  { label: 'Killer Ballista', value: 93 },
  { label: 'Civilian', value: 94 },
  { label: 'Civilian (F)', value: 95 },
  { label: 'Civilian', value: 96 },
  { label: 'Civilian (F)', value: 97 },
  { label: 'Peer', value: 98 },
  { label: 'Queen', value: 99 },
  { label: 'Prince', value: 100 },
  { label: 'Queen', value: 101 },
  { label: '(empty)', value: 102 },
  { label: 'Fallen Prince', value: 103 },
  { label: 'Tent', value: 104 },
  { label: 'Pontifex', value: 105 },
  { label: 'Dead Peer', value: 106 },
];

export const Size = [
  { label: '16x16', value: 0x00 },
  { label: '16x32', value: 0x01 },
  { label: '32x32', value: 0x02 },
];
