export const FE5SupportsEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
];

export const FE5CharacterList = [
  { label: 'Nothing/Separator', value: 0x0000 },
  { label: 'Leaf', value: 0x0001 },
  { label: 'Finn', value: 0x0002 },
  { label: 'Othin', value: 0x0003 },
  { label: 'Halvan', value: 0x0004 },
  { label: 'Eyvel', value: 0x0005 },
  { label: 'Dagudar', value: 0x0006 },
  { label: 'Ralf', value: 0x0007 },
  { label: 'Marty', value: 0x0008 },
  { label: 'Ronan', value: 0x0009 },
  { label: 'Miranda', value: 0x000A },
  { label: 'Saphy', value: 0x000B },
  { label: 'Lara', value: 0x000C },
  { label: 'Brighton', value: 0x000D },
  { label: 'Felgus', value: 0x000E },
  { label: 'Eda', value: 0x000F },
  { label: 'Asvel', value: 0x0010 },
  { label: 'Machyua', value: 0x0011 },
  { label: 'Hicks', value: 0x0012 },
  { label: 'Nanna', value: 0x0013 },
  { label: 'Selfina', value: 0x0014 },
  { label: 'Dalshein', value: 0x0015 },
  { label: 'Carrion', value: 0x0016 },
  { label: 'Shiva', value: 0x0017 },
  { label: 'Pahn', value: 0x0018 },
  { label: 'Glade', value: 0x0019 },
  { label: 'Kein', value: 0x001A },
  { label: 'Alba', value: 0x001B },
  { label: 'Roberto', value: 0x001C },
  { label: 'Fred', value: 0x001D },
  { label: 'Oruen', value: 0x001E },
  { label: 'Sety (Chapter 23)', value: 0x001F },
  { label: 'Rifis', value: 0x0020 },
  { label: 'Karin', value: 0x0021 },
  { label: 'Dean', value: 0x0022 },
  { label: 'Shanam', value: 0x0023 },
  { label: 'Trewd', value: 0x0024 },
  { label: 'Tanya', value: 0x0025 },
  { label: 'Linonan', value: 0x0026 },
  { label: 'Misha', value: 0x0027 },
  { label: 'Seiram', value: 0x0028 },
  { label: 'Sleuf', value: 0x0029 },
  { label: 'Mareeta', value: 0x002A },
  { label: 'Tina', value: 0x002B },
  { label: 'Gunna (Bishop from dialogue)', value: 0x002C },
  { label: 'Amalda', value: 0x002D },
  { label: 'Conomore', value: 0x002E },
  { label: 'Homeros', value: 0x002F },
  { label: 'Delmud', value: 0x0030 },
  { label: 'Sara', value: 0x0031 },
  { label: 'Cyas', value: 0x0032 },
  { label: 'Leidrick', value: 0x0033 },
  { label: 'Yurius (Dark Mage with Cyas portrait and Life...)', value: 0x0034 },
  { label: 'Beldo', value: 0x0035 },
  { label: 'Weissman (Boss)', value: 0x0036 },
  { label: 'Manster - Archer', value: 0x0037 },
  { label: 'Bugs (Boss)', value: 0x0038 },
  { label: 'Jabal', value: 0x0039 },
  { label: 'Rifis\' Gang - Pirate', value: 0x003A },
  { label: 'Rifis\' Gang - Hunter', value: 0x003B },
  { label: 'Rifis\' Gang - Warrior', value: 0x003C },
  { label: 'Robos (Boss)', value: 0x003D },
  { label: 'Manster - Bow Armor', value: 0x003E },
  { label: 'Manster - Thunder Mage', value: 0x003F },
  { label: 'Manster - Bishop', value: 0x0040 },
  { label: 'Romeo (NPC)', value: 0x0041 },
  { label: 'Luchea (NPC)', value: 0x0042 },
  { label: 'Yubel (NPC)', value: 0x0043 },
  { label: 'Corple (NPC,FE4 cameo)', value: 0x0044 },
  { label: 'Sety (Chapter 4G appearance)', value: 0x0045 },
  { label: 'Ishtar', value: 0x0046 },
  { label: 'Reinhart (Weak version,probably dialogue)', value: 0x0047 },
  { label: 'Rifis\' Gang - Sword Fighter', value: 0x0048 },
  { label: 'Emily (NPC)', value: 0x0049 },
  { label: 'Murphy (NPC)', value: 0x004A },
  { label: 'Bella (NPC)', value: 0x004B },
  { label: 'Krith (NPC)', value: 0x004C },
  { label: 'Boey (NPC)', value: 0x004D },
  { label: 'Leena (NPC)', value: 0x004E },
  { label: 'Mercenary - Sword Fighter', value: 0x004F },
  { label: 'Galzus', value: 0x0050 },
  { label: 'Manster - Social Knight', value: 0x0051 },
  { label: 'Manster - Paladin', value: 0x0052 },
  { label: 'Manster - Arch Knight', value: 0x0053 },
  { label: 'Manster - Troubadour', value: 0x0054 },
  { label: 'Izenau (Boss)', value: 0x0055 },
  { label: 'Hannibal (Dialogue,FE4 cameo)', value: 0x0056 },
  { label: 'Manster - Axe Knight', value: 0x0057 },
  { label: 'Bandit - Mountain Thief', value: 0x0058 },
  { label: 'Bandit - Hunter', value: 0x0059 },
  { label: 'Bandit - Warrior', value: 0x005A },
  { label: 'Lumei (Boss)', value: 0x005B },
  { label: 'Gomez (Boss)', value: 0x005C },
  { label: 'Mallock (Boss)', value: 0x005D },
  { label: 'Thracia - Dragon Knight', value: 0x005E },
  { label: 'Thracia - Sword Fighter', value: 0x005F },
  { label: 'Thracia - Axe Fighter', value: 0x0060 },
  { label: 'Althenna (Enemy only,FE4 cameo)', value: 0x0061 },
  { label: 'Torabant (Dialogue,FE4 cameo)', value: 0x0062 },
  { label: 'Ralgo (Boss)', value: 0x0063 },
  { label: 'Manster - Long Arch', value: 0x0064 },
  { label: 'Manster - Axe Armor', value: 0x0065 },
  { label: 'Kempf (Boss)', value: 0x0066 },
  { label: 'Oltov (Boss)', value: 0x0067 },
  { label: 'Rosa (NPC)', value: 0x0068 },
  { label: 'Serra (NPC)', value: 0x0069 },
  { label: 'Peter (NPC)', value: 0x006A },
  { label: 'Kolho (Mini-boss)', value: 0x006B },
  { label: 'Rist (Boss)', value: 0x006C },
  { label: 'Paluce (Boss)', value: 0x006D },
  { label: 'Baldack (Boss)', value: 0x006E },
  { label: 'Thracia - Lance Armor', value: 0x006F },
  { label: 'Lenster - Lance Knight', value: 0x0070 },
  { label: 'Lenster - Arch Knight', value: 0x0071 },
  { label: 'Arion (Dialogue,FE4 cameo)', value: 0x0072 },
  { label: 'Makroi (Boss)', value: 0x0073 },
  { label: 'Kodda (Boss)', value: 0x0074 },
  { label: 'Roputo - Dark Mage', value: 0x0075 },
  { label: 'Civilian', value: 0x0076 },
  { label: 'Thief', value: 0x0077 },
  { label: 'Manster - Sniper', value: 0x0078 },
  { label: 'Mercenary - Social Knight', value: 0x0079 },
  { label: 'Priest', value: 0x007A },
  { label: 'Mercenary - Sword Fighter', value: 0x007B },
  { label: '21 - Iron Arch', value: 0x007C },
  { label: 'Shupel (Boss)', value: 0x007D },
  { label: 'Bluke (Boss)', value: 0x007E },
  { label: 'Silesia - Pegasus Rider', value: 0x007F },
  { label: 'Nikolaf (Boss)', value: 0x0080 },
  { label: 'Muua (Boss)', value: 0x0081 },
  { label: 'Myura (Boss)', value: 0x0082 },
  { label: 'Reincock (Boss)', value: 0x0083 },
  { label: 'Palman (Boss)', value: 0x0084 },
  { label: 'Kanto (Boss)', value: 0x0085 },
  { label: 'Gustaf (Boss)', value: 0x0086 },
  { label: 'Dancer', value: 0x0087 },
  { label: 'Sister', value: 0x0088 },
  { label: 'Manheim (Boss)', value: 0x0089 },
  { label: 'Phlaus (Boss)', value: 0x008A },
  { label: 'Semitol (Boss)', value: 0x008B },
  { label: 'Zaom (Boss)', value: 0x008C },
  { label: 'Koen (Boss)', value: 0x008D },
  { label: 'Alphan (Boss)', value: 0x008E },
  { label: 'Opisu (Boss?)', value: 0x008F },
  { label: 'Ferden (Boss)', value: 0x0090 },
  { label: 'Koruta (Boss)', value: 0x0091 },
  { label: 'Reinhardt', value: 0x0092 },
  { label: 'Nancy (NPC)', value: 0x0093 },
  { label: 'Tahra Civilian', value: 0x0094 },
  { label: 'Tahra Civilian', value: 0x0095 },
  { label: 'Tahra Civilian', value: 0x0096 },
  { label: 'Tahra Civilian', value: 0x0097 },
  { label: 'Tahra Civilian', value: 0x0098 },
  { label: 'Tahra Civilian', value: 0x0099 },
  { label: 'Mercenary - Sword Fighter', value: 0x009A },
  { label: 'Freege - Long Arch', value: 0x009B },
  { label: 'Freege - Social Knight', value: 0x009C },
  { label: 'Freege - Troubadour', value: 0x009D },
  { label: 'Freege - Bow Armour', value: 0x009E },
  { label: 'Freege - Lance Armour', value: 0x009F },
  { label: 'Freege - Axe Armour', value: 0x00A0 },
  { label: 'Freege - Archer', value: 0x00A1 },
  { label: 'Freege - Mage', value: 0x00A2 },
  { label: 'Rilke (with Kempf portrait...)', value: 0x00A3 },
  { label: 'Manster - Lance Armour', value: 0x00A4 },
  { label: 'Civilian', value: 0x00A5 },
  { label: 'Civilian', value: 0x00A6 },
  { label: 'Civilian', value: 0x00A7 },
  { label: 'Civilian', value: 0x00A8 },
  { label: 'Civilian', value: 0x00A9 },
  { label: 'Civilian', value: 0x00AA },
  { label: 'Manster - Mage', value: 0x00AB },
  { label: 'Manster - Priest', value: 0x00AC },
  { label: 'Yurius (with Yuria portrait...)', value: 0x00AD },
  { label: 'Manfroy (with Machyua portrait...)', value: 0x00AE },
  { label: 'Manster - Mage', value: 0x00AF },
  { label: 'Manster - Sword Fighter', value: 0x00B0 },
  { label: 'Envoy - Mercenary', value: 0x00B1 },
  { label: 'Envoy - Warrior', value: 0x00B2 },
  { label: 'Envoy - General', value: 0x00B3 },
  { label: 'Envoy - Swordmaster', value: 0x00B4 },
  { label: 'Envoy - Berserker', value: 0x00B5 },
  { label: 'Manster - Priest', value: 0x00B6 },
  { label: 'Bantol (Boss)', value: 0x00B7 },
  { label: 'Lopto - Dark Bishop', value: 0x00B8 },
  { label: 'Torman (Boss)', value: 0x00B9 },
  { label: 'Manster - Soldier', value: 0x00BA },
  { label: 'Bandit - Berserker', value: 0x00BB },
  { label: 'Mercenary - Sword Fighter', value: 0x00BC },
  { label: 'Magi Squad - Sword Fighter', value: 0x00BD },
  { label: 'Magi Squad - Axe Fighter', value: 0x00BE },
  { label: 'Magi Squad - Bow Fighter', value: 0x00BF },
  { label: 'Magi Squad - Sword Fighter', value: 0x00C0 },
  { label: 'Dragon Rider', value: 0x00C1 },
  { label: 'Bishop', value: 0x00C2 },
  { label: 'Tobolzark (Boss)', value: 0x00C3 },
  { label: 'Manster - Bishop', value: 0x00C4 },
  { label: 'Freege - Long Arch', value: 0x00C5 },
  { label: 'Bandit - Mountain Thief 2', value: 0x00C6 },
  { label: 'Thief', value: 0x00C7 },
  { label: 'Bow Fighter', value: 0x00C8 },
  { label: 'Freege - Bishop', value: 0x00C9 },
  { label: 'Freege - Lance Armour', value: 0x00CA },
  { label: 'Freege - Bow Armour', value: 0x00CB },
  { label: 'Freege - Mage', value: 0x00CC },
  { label: 'Iron Arch', value: 0x00CD },
  { label: 'Freege - Axe Armour', value: 0x00CE },
  { label: 'Aightman (Boss)', value: 0x00CF },
  { label: 'Zail (Boss)', value: 0x00D0 },
  { label: 'Sword Armour', value: 0x00D1 },
  { label: 'Soldier', value: 0x00D2 },
  { label: 'Freege - Long Arch', value: 0x00D3 },
  { label: 'Eyrios', value: 0x00D4 },
  { label: 'Silesia - Pegasus Rider', value: 0x00D5 },
  { label: 'Freege - Mage Knight', value: 0x00D6 },
  { label: 'Paladin', value: 0x00D7 },
  { label: 'Freege - Great Knight', value: 0x00D8 },
  { label: 'Bow Knight', value: 0x00D9 },
  { label: 'Sword Armour', value: 0x00DA },
  { label: 'Freege - Soldier', value: 0x00DB },
  { label: 'Freege - Arch Knight', value: 0x00DC },
  { label: 'Freege - Troubadour', value: 0x00DD },
  { label: 'Freege - Lance Knight', value: 0x00DE },
  { label: 'Freege - Socialknight', value: 0x00DF },
  { label: 'Civilian', value: 0x00E0 },
  { label: 'Mercenary', value: 0x00E1 },
  { label: 'Swordmaster', value: 0x00E2 },
  { label: 'Berserker', value: 0x00E3 },
  { label: 'Berserker', value: 0x00E4 },
  { label: 'Silesia - Pegasus Rider', value: 0x00E5 },
  { label: 'Freege - Axe Armour', value: 0x00E6 },
  { label: 'Freege - Sword Armour', value: 0x00E7 },
  { label: 'Freege - Lance Armour', value: 0x00E8 },
  { label: 'Freege - Long Arch', value: 0x00E9 },
  { label: 'Bow Fighter', value: 0x00EA },
  { label: 'Sword Fighter', value: 0x00EB },
  { label: 'Mercenary', value: 0x00EC },
  { label: 'Xavier', value: 0x00ED },
  { label: 'Xavier\'s Lenster Armour', value: 0x00EE },
  { label: 'Xavier\'s Lenster Armour', value: 0x00EF },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F0 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F1 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F2 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F3 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F4 },
  { label: 'Xavier\'s Lenster Armour', value: 0x00F5 },
  { label: 'Civilian', value: 0x00F6 },
  { label: 'Civilian', value: 0x00F7 },
  { label: 'Civilian', value: 0x00F8 },
  { label: 'Civilian', value: 0x00F9 },
  { label: 'Civilian', value: 0x00FA },
  { label: 'Civilian', value: 0x00FB },
  { label: 'Civilian', value: 0x00FC },
  { label: 'Civilian', value: 0x00FD },
  { label: 'Freege - Soldier', value: 0x00FE },
  { label: 'Lenster - Soldier', value: 0x00FF },
  { label: 'August', value: 0x0100 },
  { label: 'Resistance - Sword Fighter', value: 0x0101 },
  { label: 'Barrat (Boss)', value: 0x0102 },
  { label: 'Freege - General', value: 0x0103 },
  { label: 'Freege - Sword Armour', value: 0x0104 },
  { label: 'Freege - Priest', value: 0x0105 },
  { label: 'Freege - Poison Arch', value: 0x0106 },
  { label: 'Thracia - Dragon Knight', value: 0x0107 },
  { label: 'Freege - Mage Knight', value: 0x0108 },
  { label: 'Freege - Axe Knight', value: 0x0109 },
  { label: 'Freege - Bow Knight', value: 0x010A },
  { label: 'Freege - Paladin', value: 0x010B },
  { label: 'Freege - Lance Knight', value: 0x010C },
  { label: 'Freege - Sniper', value: 0x010D },
  { label: 'Freege - Mercenary', value: 0x010E },
  { label: 'Freege - Bishop', value: 0x010F },
  { label: 'Freege - Troubadour', value: 0x0110 },
  { label: 'Freege - Mage Knight', value: 0x0111 },
  { label: 'Alster - Socialknight', value: 0x0112 },
  { label: 'Alster - Arch Knight', value: 0x0113 },
  { label: 'Alster - Bow Knight', value: 0x0114 },
  { label: 'Alster - Mage Knight', value: 0x0115 },
  { label: 'Freege - Priest', value: 0x0116 },
  { label: 'Freege - Bow Knight', value: 0x0117 },
  { label: 'Freege - Paladin', value: 0x0118 },
  { label: 'Freege - Sword Armour', value: 0x0119 },
  { label: 'Freege - Arch Knight', value: 0x011A },
  { label: 'Gelb Ritter', value: 0x011B },
  { label: 'Freege - General', value: 0x011C },
  { label: 'Manster - Duke Knight', value: 0x011D },
  { label: 'Manster - Bow Knight', value: 0x011E },
  { label: 'Manster - Great Knight', value: 0x011F },
  { label: 'Thracia - Dragon Knight', value: 0x0120 },
  { label: 'Civilian', value: 0x0121 },
  { label: 'Civilian', value: 0x0122 },
  { label: 'Civilian', value: 0x0123 },
  { label: 'Civilian', value: 0x0124 },
  { label: 'Civilian', value: 0x0125 },
  { label: 'Civilian', value: 0x0126 },
  { label: 'Civilian', value: 0x0127 },
  { label: 'Civilian', value: 0x0128 },
  { label: 'Civilian', value: 0x0129 },
  { label: 'Civilian', value: 0x012A },
  { label: 'Civilian', value: 0x012B },
  { label: 'Civilian', value: 0x012C },
  { label: 'Civilian', value: 0x012D },
  { label: 'Civilian', value: 0x012E },
  { label: 'Mercenary', value: 0x012F },
  { label: 'Mercenary', value: 0x0130 },
  { label: 'Mercenary', value: 0x0131 },
  { label: 'Sniper', value: 0x0132 },
  { label: 'Eins', value: 0x0133 },
  { label: 'Drei (Dagudar)', value: 0x0134 },
  { label: 'Drei', value: 0x0135 },
  { label: 'Elf (Sara)', value: 0x0136 },
  { label: 'Elf', value: 0x0137 },
  { label: 'Zwei (Galzus)', value: 0x0138 },
  { label: 'Zwei', value: 0x0139 },
  { label: 'Zw�lf (Lifis)', value: 0x013A },
  { label: 'Zw�lf', value: 0x013B },
  { label: 'F�nf (Eyvel)', value: 0x013C },
  { label: 'F�nf', value: 0x013D },
  { label: 'Lopto - Dark Mage', value: 0x013E },
  { label: 'Lopto - Axe Armour', value: 0x013F },
  { label: 'Lopto - Bow Armour', value: 0x0140 },
  { label: 'Lopto - Lance Armour', value: 0x0141 },
  { label: 'Manster - Poison Arch', value: 0x0142 },
  { label: 'Leidrick (again)', value: 0x0143 },
  { label: 'Manster - Sword Armour', value: 0x0144 },
  { label: 'Manster - Soldier', value: 0x0145 },
  { label: 'Freege - Iron Arch', value: 0x0146 },
  { label: 'Thracia - Archer', value: 0x0147 },
  { label: 'Thracia - Bishop', value: 0x0148 },
  { label: 'Thracia - Dragon Rider', value: 0x0149 },
  { label: 'Thracia - Soldier', value: 0x014A },
  { label: 'Alster - Socialknight', value: 0x014B },
  { label: 'Pirate', value: 0x014C },
  { label: 'Resistance - Bow Fighter', value: 0x014D },
  { label: 'Resistance - Priest', value: 0x014E },
  { label: 'Resistance - Axe Fighter', value: 0x014F },
  { label: 'Resistance - Bow Fighter', value: 0x0150 },
  { label: 'Resistance - Sword Fighter', value: 0x0151 },
  { label: 'Resistance - Mage', value: 0x0152 },
  { label: 'Manster - General', value: 0x0153 },
  { label: 'Lopto - Dark Mage', value: 0x0154 },
  { label: 'Thracia - Sword Armour', value: 0x0155 },
  { label: 'Wolf (Boss)', value: 0x0156 },
];
