export const FE7LynsEndingEditorEntries = [
  { label: 'Entry 0', value: 0 },
];

export const CharacterList = [
  { label: 'None', value: 0x00 },
  { label: 'Eliwood', value: 0x01 },
  { label: 'Hector', value: 0x02 },
  { label: 'Lyn (Tutorial)', value: 0x03 },
  { label: 'Raven', value: 0x04 },
  { label: 'Geitz', value: 0x05 },
  { label: 'Guy', value: 0x06 },
  { label: 'Karel', value: 0x07 },
  { label: 'Dorcas', value: 0x08 },
  { label: 'Bartre', value: 0x09 },
  { label: 'Citizen', value: 0x0A },
  { label: 'Oswin', value: 0x0B },
  { label: 'Fargus', value: 0x0C },
  { label: 'Wil (Tutorial)', value: 0x0D },
  { label: 'Rebecca', value: 0x0E },
  { label: 'Louise', value: 0x0F },
  { label: 'Lucius', value: 0x10 },
  { label: 'Serra', value: 0x11 },
  { label: 'Renault', value: 0x12 },
  { label: 'Erk', value: 0x13 },
  { label: 'Nino', value: 0x14 },
  { label: 'Pent', value: 0x15 },
  { label: 'Canas', value: 0x16 },
  { label: 'Kent (Tutorial)', value: 0x17 },
  { label: 'Sain (Tutorial)', value: 0x18 },
  { label: 'Lowen', value: 0x19 },
  { label: 'Marcus', value: 0x1A },
  { label: 'Priscilla', value: 0x1B },
  { label: 'Rath (Tutorial)', value: 0x1C },
  { label: 'Florina (Tutorial)', value: 0x1D },
  { label: 'Fiora', value: 0x1E },
  { label: 'Farina', value: 0x1F },
  { label: 'Heath', value: 0x20 },
  { label: 'Vaida', value: 0x21 },
  { label: 'Hawkeye', value: 0x22 },
  { label: 'Matthew', value: 0x23 },
  { label: 'Jaffar', value: 0x24 },
  { label: 'Ninian', value: 0x25 },
  { label: 'Nils', value: 0x26 },
  { label: 'Athos', value: 0x27 },
  { label: 'Merlinus', value: 0x28 },
  { label: 'Nils(Final Chapter)', value: 0x29 },
  { label: 'Uther', value: 0x2A },
  { label: 'Vaida (Boss)', value: 0x2B },
  { label: 'Wallace', value: 0x2C },
  { label: 'Lyn (not tutorial)', value: 0x2D },
  { label: 'Wil (not tutorial)', value: 0x2E },
  { label: 'Kent (not tutorial)', value: 0x2F },
  { label: 'Sain (not tutorial)', value: 0x30 },
  { label: 'Florina (not tutorial)', value: 0x31 },
  { label: 'Rath (not tutorial)', value: 0x32 },
  { label: 'Dart', value: 0x33 },
  { label: 'Isadora', value: 0x34 },
  { label: 'Elenora', value: 0x35 },
  { label: 'Legault', value: 0x36 },
  { label: 'Karla', value: 0x37 },
  { label: 'Harken', value: 0x38 },
  { label: 'Leila', value: 0x39 },
  { label: 'Bramimond', value: 0x3A },
  { label: 'Kishuna', value: 0x3B },
  { label: 'Groznyi', value: 0x3C },
  { label: 'Wire', value: 0x3D },
  { label: 'Bandit', value: 0x3E },
  { label: 'Zagan', value: 0x3F },
  { label: 'Boies', value: 0x40 },
  { label: 'Puzon', value: 0x41 },
  { label: 'Bandit', value: 0x42 },
  { label: 'Santals', value: 0x43 },
  { label: 'Nergal', value: 0x44 },
  { label: 'Erik', value: 0x45 },
  { label: 'Sealen', value: 0x46 },
  { label: 'Bauker', value: 0x47 },
  { label: 'Bernard', value: 0x48 },
  { label: 'Damian', value: 0x49 },
  { label: 'Zoldam', value: 0x4A },
  { label: 'Uhai', value: 0x4B },
  { label: 'Aion', value: 0x4C },
  { label: 'Darin', value: 0x4D },
  { label: 'Cameron', value: 0x4E },
  { label: 'Oleg', value: 0x4F },
  { label: 'Eubans', value: 0x50 },
  { label: 'Ursula', value: 0x51 },
  { label: 'Black Fang', value: 0x52 },
  { label: 'Paul', value: 0x53 },
  { label: 'Jasmine', value: 0x54 },
  { label: 'Black Fang', value: 0x55 },
  { label: 'Morph Jerme', value: 0x56 },
  { label: 'Pascal', value: 0x57 },
  { label: 'Kenneth', value: 0x58 },
  { label: 'Jerme', value: 0x59 },
  { label: 'Maxime', value: 0x5A },
  { label: 'Sonia', value: 0x5B },
  { label: 'Teodor', value: 0x5C },
  { label: 'Georg', value: 0x5D },
  { label: 'Kaim', value: 0x5E },
  { label: 'Merc', value: 0x5F },
  { label: 'Denning', value: 0x60 },
  { label: 'Bern', value: 0x61 },
  { label: 'Morph', value: 0x62 },
  { label: 'Lloyd (Four-Fanged Offense)', value: 0x63 },
  { label: 'Linus (Four-Fanged Offense)', value: 0x64 },
  { label: 'Lloyd (Cog of Destiny)', value: 0x65 },
  { label: 'Linus (Cog of Destiny)', value: 0x66 },
  { label: 'Bandit', value: 0x67 },
  { label: 'Bandit', value: 0x68 },
  { label: 'Bandit', value: 0x69 },
  { label: 'Laus', value: 0x6A },
  { label: 'Laus', value: 0x6B },
  { label: 'Pirate', value: 0x6C },
  { label: 'Black Fang', value: 0x6D },
  { label: 'Black Fang', value: 0x6E },
  { label: 'Ostia', value: 0x6F },
  { label: 'Black Fang', value: 0x70 },
  { label: 'Guardian', value: 0x71 },
  { label: 'Morph', value: 0x72 },
  { label: 'Morph', value: 0x73 },
  { label: 'Morph', value: 0x74 },
  { label: 'Caelin', value: 0x75 },
  { label: 'Caelin', value: 0x76 },
  { label: 'Caelin', value: 0x77 },
  { label: 'Laus', value: 0x78 },
  { label: 'Laus', value: 0x79 },
  { label: 'Zephiel', value: 0x7A },
  { label: 'Elbert', value: 0x7B },
  { label: 'Black Fang', value: 0x7C },
  { label: 'Black Fang', value: 0x7D },
  { label: 'Black Fang', value: 0x7E },
  { label: 'Morph', value: 0x7F },
  { label: 'Morph', value: 0x80 },
  { label: 'Morph', value: 0x81 },
  { label: 'Morph', value: 0x82 },
  { label: 'Black Fang', value: 0x83 },
  { label: 'Brendan', value: 0x84 },
  { label: 'Limstella', value: 0x85 },
  { label: 'Dragon', value: 0x86 },
  { label: 'Batta', value: 0x87 },
  { label: 'Bandit', value: 0x88 },
  { label: 'Zugu', value: 0x89 },
  { label: 'Bandit', value: 0x8A },
  { label: 'Bandit', value: 0x8B },
  { label: 'Bandit', value: 0x8C },
  { label: 'Glass', value: 0x8D },
  { label: 'Migal', value: 0x8E },
  { label: 'Bandit', value: 0x8F },
  { label: 'Bandit', value: 0x90 },
  { label: 'Bandit', value: 0x91 },
  { label: 'Bandit', value: 0x92 },
  { label: 'Bandit', value: 0x93 },
  { label: 'Carjiga', value: 0x94 },
  { label: 'Bandit', value: 0x95 },
  { label: 'Bandit', value: 0x96 },
  { label: 'Bandit', value: 0x97 },
  { label: 'Bandit', value: 0x98 },
  { label: 'Bug', value: 0x99 },
  { label: 'Bandit', value: 0x9A },
  { label: 'Bandit', value: 0x9B },
  { label: 'Bandit', value: 0x9C },
  { label: 'Bandit', value: 0x9D },
  { label: 'Natalie', value: 0x9E },
  { label: 'Bool', value: 0x9F },
  { label: 'Bandit', value: 0xA0 },
  { label: 'Bandit', value: 0xA1 },
  { label: 'Bandit', value: 0xA2 },
  { label: 'Bandit', value: 0xA3 },
  { label: 'Bandit', value: 0xA4 },
  { label: 'Bandit', value: 0xA5 },
  { label: 'Heintz', value: 0xA6 },
  { label: 'Black Fang', value: 0xA7 },
  { label: 'Black Fang', value: 0xA8 },
  { label: 'Black Fang', value: 0xA9 },
  { label: 'Black Fang', value: 0xAA },
  { label: 'Black Fang', value: 0xAB },
  { label: 'Black Fang', value: 0xAC },
  { label: 'Beyard', value: 0xAD },
  { label: 'Black Fang', value: 0xAE },
  { label: 'Black Fang', value: 0xAF },
  { label: 'Black Fang', value: 0xB0 },
  { label: 'Black Fang', value: 0xB1 },
  { label: 'Black Fang', value: 0xB2 },
  { label: 'Black Fang', value: 0xB3 },
  { label: 'Black Fang', value: 0xB4 },
  { label: 'Black Fang', value: 0xB5 },
  { label: 'Yogi', value: 0xB6 },
  { label: 'Caelin', value: 0xB7 },
  { label: 'Caelin', value: 0xB8 },
  { label: 'Caelin', value: 0xB9 },
  { label: 'Caelin', value: 0xBA },
  { label: 'Caelin', value: 0xBB },
  { label: 'Caelin', value: 0xBC },
  { label: 'Caelin', value: 0xBD },
  { label: 'Eagler', value: 0xBE },
  { label: 'Caelin', value: 0xBF },
  { label: 'Caelin', value: 0xC0 },
  { label: 'Caelin', value: 0xC1 },
  { label: 'Caelin', value: 0xC2 },
  { label: 'Caelin', value: 0xC3 },
  { label: 'Caelin', value: 0xC4 },
  { label: 'Lundgren', value: 0xC5 },
  { label: 'Caelin', value: 0xC6 },
  { label: 'Caelin', value: 0xC7 },
  { label: 'Caelin', value: 0xC8 },
  { label: 'Caelin', value: 0xC9 },
  { label: 'Caelin', value: 0xCA },
  { label: 'Caelin', value: 0xCB },
  { label: 'Caelin', value: 0xCC },
  { label: 'Tactician', value: 0xCD },
  { label: 'Citizen', value: 0xCE },
  { label: 'Citizen', value: 0xCF },
  { label: 'Citizen', value: 0xD0 },
  { label: 'Citizen', value: 0xD1 },
  { label: 'Citizen', value: 0xD2 },
  { label: 'Citizen', value: 0xD3 },
  { label: 'Citizen', value: 0xD4 },
  { label: 'Citizen', value: 0xD5 },
  { label: 'Citizen', value: 0xD6 },
  { label: 'Merc', value: 0xD7 },
  { label: 'Pirate', value: 0xD8 },
  { label: 'Bandit', value: 0xD9 },
  { label: 'Citizen', value: 0xDA },
  { label: 'Citizen', value: 0xDB },
  { label: 'Citizen', value: 0xDC },
  { label: 'Black Fang', value: 0xDD },
  { label: 'Black Fang', value: 0xDE },
  { label: 'Bandit', value: 0xDF },
  { label: 'Black Fang', value: 0xE0 },
  { label: 'Morph', value: 0xE1 },
  { label: 'Black Fang', value: 0xE2 },
  { label: 'Black Fang', value: 0xE3 },
  { label: 'Bandit', value: 0xE4 },
  { label: 'Ostia', value: 0xE5 },
  { label: 'Rath\'s unit', value: 0xE6 },
  { label: 'Bandit', value: 0xE7 },
  { label: 'Bandit', value: 0xE8 },
  { label: 'Bern', value: 0xE9 },
  { label: 'Guardian', value: 0xEA },
  { label: 'Morph', value: 0xEB },
  { label: 'Laus', value: 0xEC },
  { label: 'Bandit', value: 0xED },
  { label: 'Bandit', value: 0xEE },
  { label: 'Bern', value: 0xEF },
  { label: 'Guardian', value: 0xF0 },
  { label: 'Morph', value: 0xF1 },
  { label: 'Guardian', value: 0xF2 },
  { label: 'Black Fang', value: 0xF3 },
  { label: 'Morph Lloyd', value: 0xF4 },
  { label: 'Morph Linus', value: 0xF5 },
  { label: 'Morph Brendan', value: 0xF6 },
  { label: 'Morph Uhai', value: 0xF7 },
  { label: 'Morph Ursula', value: 0xF8 },
  { label: 'Morph Kenneth', value: 0xF9 },
  { label: 'Morph Darin', value: 0xFA },
  { label: 'Enemy', value: 0xFB },
  { label: 'Wall', value: 0xFC },
  { label: 'Snag', value: 0xFD },
  { label: 'None', value: 0xFE },
  { label: 'None', value: 0xFF },
];
