export const FE4EnemyEditor16Entries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
];

export const FE4CharacterType = [
  { label: 'Static', value: 0x00 },
  { label: 'Dynamic', value: 0x01 },
  { label: 'Holy', value: 0x02 },
  { label: 'Enemy', value: 0x03 },
];

export const FE4CharacterNumbers = [
  { label: 'None', value: 0x0000 },
  { label: 'Sigurd', value: 0x0001 },
  { label: 'Noish', value: 0x0002 },
  { label: 'Alec', value: 0x0003 },
  { label: 'Arden', value: 0x0004 },
  { label: 'Young Fin', value: 0x0005 },
  { label: 'Cuan', value: 0x0006 },
  { label: 'Mideel', value: 0x0007 },
  { label: 'Levin', value: 0x0008 },
  { label: 'Holyn', value: 0x0009 },
  { label: 'Azel', value: 0x000A },
  { label: 'Jamuka', value: 0x000B },
  { label: 'Claud', value: 0x000C },
  { label: 'Beowulf', value: 0x000D },
  { label: 'Lex', value: 0x000E },
  { label: 'Dew', value: 0x000F },
  { label: 'Diadora', value: 0x0010 },
  { label: 'Ethrin', value: 0x0011 },
  { label: 'Lachesis', value: 0x0012 },
  { label: 'Ira', value: 0x0013 },
  { label: 'Fury', value: 0x0014 },
  { label: 'Tiltyu', value: 0x0015 },
  { label: 'Sylvia', value: 0x0016 },
  { label: 'Edin', value: 0x0017 },
  { label: 'Bridget', value: 0x0018 },
  { label: 'Celice', value: 0x0019 },
  { label: 'Shanan', value: 0x001A },
  { label: 'Rodolban', value: 0x001B },
  { label: 'Asaello', value: 0x001C },
  { label: 'Leaf', value: 0x001D },
  { label: 'Johan', value: 0x001E },
  { label: 'Sharlow', value: 0x001F },
  { label: 'Hawk', value: 0x0020 },
  { label: 'Tristan', value: 0x0021 },
  { label: 'Adult Fin', value: 0x0022 },
  { label: 'Dimna', value: 0x0023 },
  { label: 'Hannibal', value: 0x0024 },
  { label: 'Aless', value: 0x0025 },
  { label: 'Amid', value: 0x0026 },
  { label: 'Oifaye', value: 0x0027 },
  { label: 'Daisy', value: 0x0028 },
  { label: 'Radney', value: 0x0029 },
  { label: 'Mana', value: 0x002A },
  { label: 'Julia', value: 0x002B },
  { label: 'Altenna', value: 0x002C },
  { label: 'Femina', value: 0x002D },
  { label: 'Linda', value: 0x002E },
  { label: 'Laylea', value: 0x002F },
  { label: 'Janne', value: 0x0030 },
  { label: 'Johalva', value: 0x0031 },
  { label: 'Skasaher', value: 0x0032 },
  { label: 'Faval', value: 0x0033 },
  { label: 'Corple', value: 0x0034 },
  { label: 'Sety', value: 0x0035 },
  { label: 'Delmud', value: 0x0036 },
  { label: 'Lester', value: 0x0037 },
  { label: 'Arthur', value: 0x0038 },
  { label: 'Patty', value: 0x0039 },
  { label: 'Lakche', value: 0x003A },
  { label: 'Rana', value: 0x003B },
  { label: 'Fee', value: 0x003C },
  { label: 'Tinny', value: 0x003D },
  { label: 'Lynn', value: 0x003E },
  { label: 'Nanna', value: 0x003F },
  { label: 'Gerrard', value: 0x0040 },
  { label: 'DiMaggio', value: 0x0041 },
  { label: 'Verdane Army', value: 0x0042 },
  { label: 'Verdane Army', value: 0x0043 },
  { label: 'Verdane Army', value: 0x0044 },
  { label: 'Verdane Army', value: 0x0045 },
  { label: 'Verdane Army', value: 0x0046 },
  { label: 'Verdane Army', value: 0x0047 },
  { label: 'Kinbois', value: 0x0048 },
  { label: 'Verdane Army', value: 0x0049 },
  { label: 'Verdane Army', value: 0x004A },
  { label: 'Verdane Army', value: 0x004B },
  { label: 'Verdane Army', value: 0x004C },
  { label: 'Gandolf', value: 0x004D },
  { label: 'Commander', value: 0x004E },
  { label: 'Verdane Army', value: 0x004F },
  { label: 'Verdane Army', value: 0x0050 },
  { label: 'Verdane Army', value: 0x0051 },
  { label: 'Sandima', value: 0x0052 },
  { label: 'Verdane Army', value: 0x0053 },
  { label: 'Verdane Army', value: 0x0054 },
  { label: 'Commander', value: 0x0055 },
  { label: 'Verdane Army', value: 0x0056 },
  { label: 'Thief', value: 0x0057 },
  { label: 'Elliot', value: 0x0058 },
  { label: 'Heirhein Army', value: 0x0059 },
  { label: 'Eltosian', value: 0x005A },
  { label: 'Cross Knight', value: 0x005B },
  { label: 'Commander', value: 0x005C },
  { label: 'Boldor', value: 0x005D },
  { label: 'Heirhein Army', value: 0x005E },
  { label: 'Phillip', value: 0x005F },
  { label: 'Heirhein Army', value: 0x0060 },
  { label: 'Heirhein Army', value: 0x0061 },
  { label: 'Heirhein Army', value: 0x0062 },
  { label: 'Heirhein Army', value: 0x0063 },
  { label: 'Heirhein Army', value: 0x0064 },
  { label: 'Heirhein Army', value: 0x0065 },
  { label: 'Elliot', value: 0x0066 },
  { label: 'Heirhein Army', value: 0x0067 },
  { label: 'Heirhein Army', value: 0x0068 },
  { label: 'Heirhein Army', value: 0x0069 },
  { label: 'Commander', value: 0x006A },
  { label: 'Anphony Army', value: 0x006B },
  { label: 'Thief', value: 0x006C },
  { label: 'Mackily Army', value: 0x006D },
  { label: 'Eve', value: 0x006E },
  { label: 'Macbeth', value: 0x006F },
  { label: 'Anphony Army', value: 0x0070 },
  { label: 'Anphony Army', value: 0x0071 },
  { label: 'Anphony Army', value: 0x0072 },
  { label: 'Voltz', value: 0x0073 },
  { label: 'Mercenary', value: 0x0074 },
  { label: 'Clement', value: 0x0075 },
  { label: 'Mackily Army', value: 0x0076 },
  { label: 'Mackily Army', value: 0x0077 },
  { label: 'Mackily Army', value: 0x0078 },
  { label: 'Commander', value: 0x0079 },
  { label: 'Mackily Army', value: 0x007A },
  { label: 'Shagaar', value: 0x007B },
  { label: 'Agusty Army', value: 0x007C },
  { label: 'Agusty Army', value: 0x007D },
  { label: 'Commander', value: 0x007E },
  { label: 'Agusty Army', value: 0x007F },
  { label: 'Commander', value: 0x0080 },
  { label: 'Agusty Army', value: 0x0081 },
  { label: 'Fury Squad', value: 0x0082 },
  { label: 'Zain', value: 0x0083 },
  { label: 'Agusty Army', value: 0x0084 },
  { label: 'Agusty Army', value: 0x0085 },
  { label: 'Agusty Army', value: 0x0086 },
  { label: 'Agusty Army', value: 0x0087 },
  { label: 'Eva', value: 0x0088 },
  { label: 'Alva', value: 0x0089 },
  { label: 'Shacoban', value: 0x008A },
  { label: 'Madino Army', value: 0x008B },
  { label: 'Madino Army', value: 0x008C },
  { label: 'Madino Army', value: 0x008D },
  { label: 'Madino Army', value: 0x008E },
  { label: 'Madino Army', value: 0x008F },
  { label: 'Commander', value: 0x0090 },
  { label: 'Madino Army', value: 0x0091 },
  { label: 'Commander', value: 0x0092 },
  { label: 'Madino Army', value: 0x0093 },
  { label: 'Commander', value: 0x0094 },
  { label: 'Madino Army', value: 0x0095 },
  { label: 'Commander', value: 0x0096 },
  { label: 'Madino Army', value: 0x0097 },
  { label: 'Commander', value: 0x0098 },
  { label: 'Madino Army', value: 0x0099 },
  { label: 'Commander', value: 0x009A },
  { label: 'Madino Army', value: 0x009B },
  { label: 'Pirate', value: 0x009C },
  { label: 'Commander', value: 0x009D },
  { label: 'Silvail Army', value: 0x009E },
  { label: 'Eltosian', value: 0x009F },
  { label: 'Cross Knight', value: 0x00A0 },
  { label: 'Shagaar', value: 0x00A1 },
  { label: 'Silvail Army', value: 0x00A2 },
  { label: 'Silvail Army', value: 0x00A3 },
  { label: 'Papilion', value: 0x00A4 },
  { label: 'Thracia Army', value: 0x00A5 },
  { label: 'Pirate', value: 0x00A6 },
  { label: 'Pirate', value: 0x00A7 },
  { label: 'Pirate', value: 0x00A8 },
  { label: 'Pirate', value: 0x00A9 },
  { label: 'Dobarl', value: 0x00AA },
  { label: 'Pirate', value: 0x00AB },
  { label: 'Pizarl', value: 0x00AC },
  { label: 'Pirate', value: 0x00AD },
  { label: 'Pirate', value: 0x00AE },
  { label: 'Pirate', value: 0x00AF },
  { label: 'Pirate', value: 0x00B0 },
  { label: 'Alvis', value: 0x00B1 },
  { label: 'Langobalt', value: 0x00B2 },
  { label: 'Grao Ritter', value: 0x00B3 },
  { label: 'Leptor', value: 0x00B4 },
  { label: 'Gelp Ritter', value: 0x00B5 },
  { label: 'Mahnya', value: 0x00B6 },
  { label: 'Silesia Army', value: 0x00B7 },
  { label: 'Maios', value: 0x00B8 },
  { label: 'Thove Army', value: 0x00B9 },
  { label: 'Thove Army', value: 0x00BA },
  { label: 'Commander', value: 0x00BB },
  { label: 'Thove Army', value: 0x00BC },
  { label: 'Cuvuli', value: 0x00BD },
  { label: 'Thove Army', value: 0x00BE },
  { label: 'Commander', value: 0x00BF },
  { label: 'Thove Army', value: 0x00C0 },
  { label: 'Thove Army', value: 0x00C1 },
  { label: 'Deetva', value: 0x00C2 },
  { label: 'Deetva Squad', value: 0x00C3 },
  { label: 'Pirate', value: 0x00C4 },
  { label: 'Silesia Army', value: 0x00C5 },
  { label: 'Dakar', value: 0x00C6 },
  { label: 'Mahnya', value: 0x00C7 },
  { label: 'Mahnya Squad', value: 0x00C8 },
  { label: 'Pamela', value: 0x00C9 },
  { label: 'Pamela Squad', value: 0x00CA },
  { label: 'Andrei', value: 0x00CB },
  { label: 'Beig Ritter', value: 0x00CC },
  { label: 'Civilian', value: 0x00CD },
  { label: 'Civilian', value: 0x00CE },
  { label: 'Donovan', value: 0x00CF },
  { label: 'Zaxon Army', value: 0x00D0 },
  { label: 'Zaxon Army', value: 0x00D1 },
  { label: 'Zaxon Army', value: 0x00D2 },
  { label: 'Zaxon Army', value: 0x00D3 },
  { label: 'Zaxon Army', value: 0x00D4 },
  { label: 'Lamia', value: 0x00D5 },
  { label: 'Mercenary', value: 0x00D6 },
  { label: 'Mercenary', value: 0x00D7 },
  { label: 'Mercenary', value: 0x00D8 },
  { label: 'Mercenary', value: 0x00D9 },
  { label: 'Mercenary', value: 0x00DA },
  { label: 'Langobalt', value: 0x00DB },
  { label: 'Child', value: 0x00DC },
  { label: 'Lubeck Army', value: 0x00DD },
  { label: 'Slayder', value: 0x00DE },
  { label: 'Lubeck Army', value: 0x00DF },
  { label: 'Commander', value: 0x00E0 },
  { label: 'Lubeck Army', value: 0x00E1 },
  { label: 'Lubeck Army', value: 0x00E2 },
  { label: 'Thief', value: 0x00E3 },
  { label: 'Commander', value: 0x00E4 },
  { label: 'Lubeck Army', value: 0x00E5 },
  { label: 'Lubeck Army', value: 0x00E6 },
  { label: 'Lubeck Army', value: 0x00E7 },
  { label: 'Vylon', value: 0x00E8 },
  { label: 'Andrei', value: 0x00E9 },
  { label: 'Beig Ritter', value: 0x00EA },
  { label: 'Vaha', value: 0x00EB },
  { label: 'Velthomer Army', value: 0x00EC },
  { label: 'Priest', value: 0x00ED },
  { label: 'Velthomer Army', value: 0x00EE },
  { label: 'Torabant', value: 0x00EF },
  { label: 'Magorn', value: 0x00F0 },
  { label: 'Thracia Army', value: 0x00F1 },
  { label: 'Lenster Army', value: 0x00F2 },
  { label: 'Aida', value: 0x00F3 },
  { label: 'Velthomer Army', value: 0x00F4 },
  { label: 'Leptor', value: 0x00F5 },
  { label: 'Freege Army', value: 0x00F6 },
  { label: 'Freege Army', value: 0x00F7 },
  { label: 'Freege Army', value: 0x00F8 },
  { label: 'Freege Army', value: 0x00F9 },
  { label: 'Freege Army', value: 0x00FA },
  { label: 'Freege Army', value: 0x00FB },
  { label: 'Freege Army', value: 0x00FC },
  { label: 'Freege Army', value: 0x00FD },
  { label: 'Commander', value: 0x00FE },
  { label: 'Rot Ritter', value: 0x00FF },
  { label: 'Commander', value: 0x0100 },
  { label: 'Rot Ritter', value: 0x0101 },
  { label: 'Commander', value: 0x0102 },
  { label: 'Rot Ritter', value: 0x0103 },
  { label: 'Alvis', value: 0x0104 },
  { label: 'Commander', value: 0x0105 },
  { label: 'Rot Ritter', value: 0x0106 },
  { label: 'Harold', value: 0x0107 },
  { label: 'Ganesha Army', value: 0x0108 },
  { label: 'Ganesha Army', value: 0x0109 },
  { label: 'Thief', value: 0x010A },
  { label: 'Sophara Army', value: 0x010B },
  { label: 'Isaac Army', value: 0x010C },
  { label: 'Isaac Army', value: 0x010D },
  { label: 'Sophara Army', value: 0x010E },
  { label: 'Shumit', value: 0x010F },
  { label: 'Rivough Army', value: 0x0110 },
  { label: 'Danan', value: 0x0111 },
  { label: 'Ganesha Army', value: 0x0112 },
  { label: 'Ganesha Army', value: 0x0113 },
  { label: 'Coutouzov', value: 0x0114 },
  { label: 'YiedMage', value: 0x0115 },
  { label: 'Yied Mage', value: 0x0116 },
  { label: 'Mercenary', value: 0x0117 },
  { label: 'Yied Mage', value: 0x0118 },
  { label: 'Commander', value: 0x0119 },
  { label: 'Alster Army', value: 0x011A },
  { label: 'Alster Army', value: 0x011B },
  { label: 'Thief', value: 0x011C },
  { label: 'Blume', value: 0x011D },
  { label: 'Alster Army', value: 0x011E },
  { label: 'Darna Army', value: 0x011F },
  { label: 'Ishtor', value: 0x0120 },
  { label: 'Melgen Army', value: 0x0121 },
  { label: 'Liza', value: 0x0122 },
  { label: 'Melgen Army', value: 0x0123 },
  { label: 'Melgen Army', value: 0x0124 },
  { label: 'Melgen Army', value: 0x0125 },
  { label: 'Melgen Army', value: 0x0126 },
  { label: 'Melgen Army', value: 0x0127 },
  { label: 'Melgen Army', value: 0x0128 },
  { label: 'Jabarro', value: 0x0129 },
  { label: 'Mercenary', value: 0x012A },
  { label: 'Mercenary', value: 0x012B },
  { label: 'Bramsel', value: 0x012C },
  { label: 'Darna Army', value: 0x012D },
  { label: 'Commander', value: 0x012E },
  { label: 'Alster Army', value: 0x012F },
  { label: 'Alster Army', value: 0x0130 },
  { label: 'Vanpa', value: 0x0131 },
  { label: 'Fetora', value: 0x0132 },
  { label: 'Eliu', value: 0x0133 },
  { label: 'High Mage', value: 0x0134 },
  { label: 'High Mage', value: 0x0135 },
  { label: 'High Mage', value: 0x0136 },
  { label: 'Muhammed', value: 0x0137 },
  { label: 'Conote Army', value: 0x0138 },
  { label: 'Conote Army', value: 0x0139 },
  { label: 'Conote Army', value: 0x013A },
  { label: 'Priest', value: 0x013B },
  { label: 'Ovo', value: 0x013C },
  { label: 'Conote Army', value: 0x013D },
  { label: 'Conote Army', value: 0x013E },
  { label: 'Thief', value: 0x013F },
  { label: 'Commander', value: 0x0140 },
  { label: 'Conote Army', value: 0x0141 },
  { label: 'Ishtar', value: 0x0142 },
  { label: 'Commander', value: 0x0143 },
  { label: 'Conote Army', value: 0x0144 },
  { label: 'Blume', value: 0x0145 },
  { label: 'Conote Army', value: 0x0146 },
  { label: 'Civilian', value: 0x0147 },
  { label: 'Civilian', value: 0x0148 },
  { label: 'Commander', value: 0x0149 },
  { label: 'Thracia Army', value: 0x014A },
  { label: 'Coruta', value: 0x014B },
  { label: 'Thracia Army', value: 0x014C },
  { label: 'Commander', value: 0x014D },
  { label: 'Thracia Army', value: 0x014E },
  { label: 'Commander', value: 0x014F },
  { label: 'Thracia Army', value: 0x0150 },
  { label: 'Maikov', value: 0x0151 },
  { label: 'Vanpa', value: 0x0152 },
  { label: 'Fetora', value: 0x0153 },
  { label: 'Eliu', value: 0x0154 },
  { label: 'Kapathogia Army', value: 0x0155 },
  { label: 'Kapathogia Army', value: 0x0156 },
  { label: 'Kapathogia Army', value: 0x0157 },
  { label: 'Kapathogia Army', value: 0x0158 },
  { label: 'Thracia Army', value: 0x0159 },
  { label: 'Thracia Army', value: 0x015A },
  { label: 'Thief', value: 0x015B },
  { label: 'Kanatz', value: 0x015C },
  { label: 'Disler', value: 0x015D },
  { label: 'Grutia Army', value: 0x015E },
  { label: 'Mercenary', value: 0x015F },
  { label: 'Mercenary', value: 0x0160 },
  { label: 'Torabant', value: 0x0161 },
  { label: 'Thracia Army', value: 0x0162 },
  { label: 'Judah', value: 0x0163 },
  { label: 'Commander', value: 0x0164 },
  { label: 'Grutia Army', value: 0x0165 },
  { label: 'Arion', value: 0x0166 },
  { label: 'Dragon Knight', value: 0x0167 },
  { label: 'Dragon Knight', value: 0x0168 },
  { label: 'Commander', value: 0x0169 },
  { label: 'Thracia Army', value: 0x016A },
  { label: 'Commander', value: 0x016B },
  { label: 'Thracia Army', value: 0x016C },
  { label: 'Commander', value: 0x016D },
  { label: 'Thracia Army', value: 0x016E },
  { label: 'Musar', value: 0x016F },
  { label: 'Imperial Army', value: 0x0170 },
  { label: 'Imperial Army', value: 0x0171 },
  { label: 'Imperial Army', value: 0x0172 },
  { label: 'Imperial Army', value: 0x0173 },
  { label: 'Lideel', value: 0x0174 },
  { label: 'Lideel Squad', value: 0x0175 },
  { label: 'Lideel Squad', value: 0x0176 },
  { label: 'Lideel Squad', value: 0x0177 },
  { label: 'Lideel Squad', value: 0x0178 },
  { label: 'Lideel Squad', value: 0x0179 },
  { label: 'Morrigan', value: 0x017A },
  { label: 'Dark Mage', value: 0x017B },
  { label: 'Pirate', value: 0x017C },
  { label: 'Hilda', value: 0x017D },
  { label: 'Dark Priest', value: 0x017E },
  { label: 'Dark Mage', value: 0x017F },
  { label: 'Dark Mage', value: 0x0180 },
  { label: 'Mercenary', value: 0x0181 },
  { label: 'Mercenary', value: 0x0182 },
  { label: 'Child', value: 0x0183 },
  { label: 'Child', value: 0x0184 },
  { label: 'Zagam', value: 0x0185 },
  { label: 'Dark Mage', value: 0x0186 },
  { label: 'Dark Mage', value: 0x0187 },
  { label: 'Dark Mage', value: 0x0188 },
  { label: 'Dark Mage', value: 0x0189 },
  { label: 'Dark Mage', value: 0x018A },
  { label: 'Mercenary', value: 0x018B },
  { label: 'Mercenary', value: 0x018C },
  { label: 'Mercenary', value: 0x018D },
  { label: 'Julius', value: 0x018E },
  { label: 'Ishtar', value: 0x018F },
  { label: 'Alvis', value: 0x0190 },
  { label: 'Rot Ritter', value: 0x0191 },
  { label: 'Rot Ritter', value: 0x0192 },
  { label: 'Rot Ritter', value: 0x0193 },
  { label: 'Dark Mage', value: 0x0194 },
  { label: 'Palmark', value: 0x0195 },
  { label: 'Child', value: 0x0196 },
  { label: 'Child', value: 0x0197 },
  { label: 'Commander', value: 0x0198 },
  { label: 'Rot Ritter', value: 0x0199 },
  { label: 'Rot Ritter', value: 0x019A },
  { label: 'Commander', value: 0x019B },
  { label: 'Rot Ritter', value: 0x019C },
  { label: 'Rot Ritter', value: 0x019D },
  { label: 'Commander', value: 0x019E },
  { label: 'Rot Ritter', value: 0x019F },
  { label: 'Rot Ritter', value: 0x01A0 },
  { label: 'Rot Ritter', value: 0x01A1 },
  { label: 'Dark Mage', value: 0x01A2 },
  { label: 'Dark Mage', value: 0x01A3 },
  { label: 'Robert', value: 0x01A4 },
  { label: 'Mercenary', value: 0x01A5 },
  { label: 'Mercenary', value: 0x01A6 },
  { label: 'Mercenary', value: 0x01A7 },
  { label: 'Mercenary', value: 0x01A8 },
  { label: 'Mercenary', value: 0x01A9 },
  { label: 'Boyce', value: 0x01AA },
  { label: 'Mercenary', value: 0x01AB },
  { label: 'Mercenary', value: 0x01AC },
  { label: 'Rodan', value: 0x01AD },
  { label: 'Edda Army', value: 0x01AE },
  { label: 'Edda Army', value: 0x01AF },
  { label: 'Edda Army', value: 0x01B0 },
  { label: 'Edda Army', value: 0x01B1 },
  { label: 'Yupheel', value: 0x01B2 },
  { label: 'Dark Mage', value: 0x01B3 },
  { label: 'Dark Mage', value: 0x01B4 },
  { label: 'Fisher', value: 0x01B5 },
  { label: 'Dozel Army', value: 0x01B6 },
  { label: 'Dozel Army', value: 0x01B7 },
  { label: 'Brian', value: 0x01B8 },
  { label: 'Grao Ritter', value: 0x01B9 },
  { label: 'Grao Ritter', value: 0x01BA },
  { label: 'Dagon', value: 0x01BB },
  { label: 'Scorpio', value: 0x01BC },
  { label: 'Beig Ritter', value: 0x01BD },
  { label: 'Beig Ritter', value: 0x01BE },
  { label: 'Hilda', value: 0x01BF },
  { label: 'Gelp Ritter', value: 0x01C0 },
  { label: 'Gelp Ritter', value: 0x01C1 },
  { label: 'Dark Priest', value: 0x01C2 },
  { label: 'Dark Mage', value: 0x01C3 },
  { label: 'Manfloy', value: 0x01C4 },
  { label: 'Dark Mage', value: 0x01C5 },
  { label: 'Julius', value: 0x01C6 },
  { label: 'Eins', value: 0x01C7 },
  { label: 'Zwei', value: 0x01C8 },
  { label: 'Drei', value: 0x01C9 },
  { label: 'Vier', value: 0x01CA },
  { label: 'Funf', value: 0x01CB },
  { label: 'Sechs', value: 0x01CC },
  { label: 'Seiben', value: 0x01CD },
  { label: 'Acht', value: 0x01CE },
  { label: 'Neun', value: 0x01CF },
  { label: 'Zehn', value: 0x01D0 },
  { label: 'Elf', value: 0x01D1 },
  { label: 'Zwolf', value: 0x01D2 },
  { label: 'Arion', value: 0x01D3 },
  { label: 'Dragon Knight', value: 0x01D4 },
  { label: 'Ishtar', value: 0x01D5 },
  { label: 'Meng', value: 0x01D6 },
  { label: 'Maybell', value: 0x01D7 },
  { label: 'Bleg', value: 0x01D8 },
  { label: 'Barhara Army', value: 0x01D9 },
  { label: 'Barhara Army', value: 0x01DA },
  { label: 'Barhara Army', value: 0x01DB },
  { label: 'Barhara Army', value: 0x01DC },
  { label: 'Baran', value: 0x01DD },
  { label: 'Coutouzov', value: 0x01DE },
  { label: 'Thief', value: 0x01DF },
  { label: 'Gazak', value: 0x01E0 },
  { label: 'Clotho', value: 0x01E1 },
  { label: 'Weissman', value: 0x01E2 },
  { label: 'Shark', value: 0x01E3 },
  { label: 'Hood', value: 0x01E4 },
  { label: 'Bacchus', value: 0x01E5 },
  { label: 'Emmile', value: 0x01E6 },
  { label: 'Darez', value: 0x01E7 },
  { label: 'Jirou', value: 0x01E8 },
  { label: 'Mahatma', value: 0x01E9 },
  { label: 'Lovin', value: 0x01EA },
  { label: 'Backnun', value: 0x01EB },
  { label: 'Milley', value: 0x01EC },
  { label: 'Hertzog', value: 0x01ED },
  { label: 'Chekov', value: 0x01EE },
  { label: 'Keimos', value: 0x01EF },
  { label: 'Marilyn', value: 0x01F0 },
  { label: 'Taylor', value: 0x01F1 },
  { label: 'Ripp', value: 0x01F2 },
  { label: 'Perio', value: 0x01F3 },
  { label: 'Trevic', value: 0x01F4 },
  { label: 'Gellar', value: 0x01F5 },
  { label: 'Bazan', value: 0x01F6 },
  { label: 'Duma', value: 0x01F7 },
  { label: 'Keller', value: 0x01F8 },
  { label: 'Torton', value: 0x01F9 },
  { label: 'Mario', value: 0x01FA },
  { label: 'Kemall', value: 0x01FB },
  { label: 'Karedin', value: 0x01FC },
  { label: 'Keith', value: 0x01FD },
  { label: 'Sangor', value: 0x01FE },
  { label: 'Nikita', value: 0x01FF },
  { label: 'Nene', value: 0x0200 },
  { label: 'Kraff', value: 0x0201 },
  { label: 'Nikias', value: 0x0202 },
  { label: 'Atlas', value: 0x0203 },
  { label: 'Jackal', value: 0x0204 },
  { label: 'Ripp', value: 0x0205 },
  { label: 'Greias', value: 0x0206 },
  { label: 'Geese', value: 0x0207 },
  { label: 'Lee', value: 0x0208 },
  { label: 'Shishel', value: 0x0209 },
  { label: 'Hawks', value: 0x020A },
  { label: 'Nazar', value: 0x020B },
  { label: 'Thief', value: 0x020C },
  { label: 'Tolstoy', value: 0x020D },
  { label: 'Botman', value: 0x020E },
  { label: 'Kulyuge', value: 0x020F },
  { label: 'Mansten', value: 0x0210 },
  { label: 'Kashim', value: 0x0211 },
  { label: 'Hepner', value: 0x0212 },
  { label: 'Randok', value: 0x0213 },
  { label: 'Volf', value: 0x0214 },
  { label: 'Duey', value: 0x0215 },
  { label: 'Fet', value: 0x0216 },
  { label: 'Marshak', value: 0x0217 },
  { label: 'Luis', value: 0x0218 },
  { label: 'Heste', value: 0x0219 },
  { label: 'Madah', value: 0x021A },
  { label: 'Jismunt', value: 0x021B },
  { label: 'Zenon', value: 0x021C },
  { label: 'Jakson', value: 0x021D },
  { label: 'Indra', value: 0x021E },
  { label: 'Neizche', value: 0x021F },
  { label: 'Apostle', value: 0x0220 },
  { label: 'Millia', value: 0x0221 },
  { label: 'Siron', value: 0x0222 },
  { label: 'Grein', value: 0x0223 },
  { label: 'Slayton', value: 0x0224 },
  { label: 'Torstar', value: 0x0225 },
  { label: 'Kanan', value: 0x0226 },
  { label: 'Hasman', value: 0x0227 },
  { label: 'Grantz', value: 0x0228 },
  { label: 'Krosloy', value: 0x0229 },
  { label: 'Rolan', value: 0x022A },
  { label: 'Mashgli', value: 0x022B },
  { label: 'Riva', value: 0x022C },
  { label: 'Gloria', value: 0x022D },
  { label: 'Nothe', value: 0x022E },
  { label: 'Indra', value: 0x022F },
  { label: 'Dares', value: 0x0230 },
  { label: 'Keimos', value: 0x0231 },
  { label: 'Marilyn', value: 0x0232 },
  { label: 'Zenon', value: 0x0233 },
  { label: 'Jakson', value: 0x0234 },
  { label: 'Torton', value: 0x0235 },
  { label: 'Mario', value: 0x0236 },
  { label: 'Kanan', value: 0x0237 },
  { label: 'Atlas', value: 0x0238 },
  { label: 'Zeus', value: 0x0239 },
  { label: 'Andrei', value: 0x023B },
  { label: 'Young Trabant', value: 0x023C },
  { label: 'Maios', value: 0x023F },
  { label: 'Dakar', value: 0x0240 },
  { label: 'Pamela', value: 0x0241 },
  { label: 'Deetva', value: 0x0242 },
  { label: 'Donovan', value: 0x0243 },
  { label: 'Langobalt', value: 0x0244 },
  { label: 'Shumit', value: 0x0245 },
  { label: 'Reptor', value: 0x0246 },
  { label: 'Aida', value: 0x024B },
  { label: 'Danan', value: 0x024D },
  { label: 'Harold', value: 0x024E },
  { label: 'Bramsel', value: 0x024F },
  { label: 'Coutouzov', value: 0x0250 },
  { label: 'Jabarro', value: 0x0251 },
  { label: 'Ishtor', value: 0x0252 },
  { label: 'Liza', value: 0x0253 },
  { label: 'Blume', value: 0x0254 },
  { label: 'Vampa', value: 0x0255 },
  { label: 'Fetora', value: 0x0256 },
  { label: 'Eliu', value: 0x0257 },
  { label: 'Manya', value: 0x0258 },
  { label: 'Arion', value: 0x025B },
  { label: 'Maikov', value: 0x025C },
  { label: 'Ovo', value: 0x025D },
  { label: 'Muhammed', value: 0x025E },
  { label: 'Morrigan', value: 0x025F },
  { label: 'Trabant', value: 0x0260 },
  { label: 'Musar', value: 0x0261 },
  { label: 'Disler', value: 0x0262 },
  { label: 'Kanatz', value: 0x0263 },
  { label: 'Eve', value: 0x0264 },
  { label: 'Judah', value: 0x0267 },
  { label: 'Hilda', value: 0x0268 },
  { label: 'Meng', value: 0x0269 },
  { label: 'Manfloy', value: 0x026C },
  { label: 'Lideel', value: 0x026D },
  { label: 'Alvis', value: 0x026E },
  { label: 'Julius', value: 0x026F },
  { label: 'Ishtar', value: 0x0271 },
  { label: 'Civilian', value: 0x027A },
  { label: 'Azmule', value: 0x027B },
  { label: 'Vylon', value: 0x027E },
  { label: 'Young Oifaye', value: 0x027F },
  { label: 'Levin', value: 0x0280 },
  { label: 'Young Shanan', value: 0x0281 },
  { label: 'Rahna', value: 0x0284 },
  { label: 'Slayder', value: 0x029A },
  { label: 'Soldier', value: 0x02A5 },
  { label: 'Civilian', value: 0x02AB },
  { label: 'Civilian', value: 0x02AC },
  { label: 'Civilian', value: 0x02AD },
  { label: 'Civilian', value: 0x02AE },
  { label: 'Civilian', value: 0x02AF },
  { label: 'Civilian', value: 0x02B0 },
  { label: 'Civilian', value: 0x02B1 },
  { label: 'Civilian', value: 0x02B2 },
  { label: 'Civilian', value: 0x02B3 },
  { label: 'Next', value: 0xFFFF },
];

export const FE4CharacterNameNumbers = [
  { label: 'Sigurd', value: 0x0000 },
  { label: 'Noish', value: 0x0001 },
  { label: 'Alec', value: 0x0002 },
  { label: 'Arden', value: 0x0003 },
  { label: 'Young Fin', value: 0x0004 },
  { label: 'Cuan', value: 0x0005 },
  { label: 'Midale', value: 0x0006 },
  { label: 'Levin', value: 0x0007 },
  { label: 'Holyn', value: 0x0008 },
  { label: 'Azel', value: 0x0009 },
  { label: 'Jamuka', value: 0x000A },
  { label: 'Claude', value: 0x000B },
  { label: 'Beowulf', value: 0x000C },
  { label: 'Lex', value: 0x000D },
  { label: 'Dew', value: 0x000E },
  { label: 'Diadora', value: 0x000F },
  { label: 'Ethrin', value: 0x0010 },
  { label: 'Lachesis', value: 0x0011 },
  { label: 'Ira', value: 0x0012 },
  { label: 'Fury', value: 0x0013 },
  { label: 'Tiltyu', value: 0x0014 },
  { label: 'Sylvia', value: 0x0015 },
  { label: 'Edin', value: 0x0016 },
  { label: 'Bridget', value: 0x0017 },
  { label: 'Celice', value: 0x0018 },
  { label: 'Shanan', value: 0x0019 },
  { label: 'Rodolban', value: 0x001A },
  { label: 'Asaello', value: 0x001B },
  { label: 'Leaf', value: 0x001C },
  { label: 'Johan', value: 0x001D },
  { label: 'Sharlow', value: 0x001E },
  { label: 'Hawk', value: 0x001F },
  { label: 'Tristan', value: 0x0020 },
  { label: 'Adult Fin', value: 0x0021 },
  { label: 'Dimna', value: 0x0022 },
  { label: 'Hannibal', value: 0x0023 },
  { label: 'Aless', value: 0x0024 },
  { label: 'Amid', value: 0x0025 },
  { label: 'Oifaye', value: 0x0026 },
  { label: 'Daisy', value: 0x0027 },
  { label: 'Radney', value: 0x0028 },
  { label: 'Mana', value: 0x0029 },
  { label: 'Julia', value: 0x002A },
  { label: 'Altenna', value: 0x002B },
  { label: 'Femina', value: 0x002C },
  { label: 'Linda', value: 0x002D },
  { label: 'Laylea', value: 0x002E },
  { label: 'Janne', value: 0x002F },
  { label: 'Johalva', value: 0x0030 },
  { label: 'Skasaher', value: 0x0031 },
  { label: 'Faval', value: 0x0032 },
  { label: 'Corple', value: 0x0033 },
  { label: 'Sety', value: 0x0034 },
  { label: 'Delmud', value: 0x0035 },
  { label: 'Lester', value: 0x0036 },
  { label: 'Arthur', value: 0x0037 },
  { label: 'Patty', value: 0x0038 },
  { label: 'Lakche', value: 0x0039 },
  { label: 'Rana', value: 0x003A },
  { label: 'Fee', value: 0x003B },
  { label: 'Tinny', value: 0x003C },
  { label: 'Lynn', value: 0x003D },
  { label: 'Nanna', value: 0x003E },
  { label: 'Gerrard', value: 0x003F },
  { label: 'DiMaggio', value: 0x0040 },
  { label: 'Verdane Army', value: 0x0041 },
  { label: 'Verdane Army', value: 0x0042 },
  { label: 'Verdane Army', value: 0x0043 },
  { label: 'Verdane Army', value: 0x0044 },
  { label: 'Verdane Army', value: 0x0045 },
  { label: 'Verdane Army', value: 0x0046 },
  { label: 'Kinbois', value: 0x0047 },
  { label: 'Verdane Army', value: 0x0048 },
  { label: 'Verdane Army', value: 0x0049 },
  { label: 'Verdane Army', value: 0x004A },
  { label: 'Verdane Army', value: 0x004B },
  { label: 'Gandolf', value: 0x004C },
  { label: 'Commander', value: 0x004D },
  { label: 'Verdane Army', value: 0x004E },
  { label: 'Verdane Army', value: 0x004F },
  { label: 'Verdane Army', value: 0x0050 },
  { label: 'Sandima', value: 0x0051 },
  { label: 'Verdane Army', value: 0x0052 },
  { label: 'Verdane Army', value: 0x0053 },
  { label: 'Commander', value: 0x0054 },
  { label: 'Verdane Army', value: 0x0055 },
  { label: 'Thief', value: 0x0056 },
  { label: 'Elliot', value: 0x0057 },
  { label: 'Heirhein Army', value: 0x0058 },
  { label: 'Eltosian', value: 0x0059 },
  { label: 'Cross Knight', value: 0x005A },
  { label: 'Commander', value: 0x005B },
  { label: 'Boldor', value: 0x005C },
  { label: 'Heirhein Army', value: 0x005D },
  { label: 'Phillip', value: 0x005E },
  { label: 'Heirhein Army', value: 0x005F },
  { label: 'Heirhein Army', value: 0x0060 },
  { label: 'Heirhein Army', value: 0x0061 },
  { label: 'Heirhein Army', value: 0x0062 },
  { label: 'Heirhein Army', value: 0x0063 },
  { label: 'Heirhein Army', value: 0x0064 },
  { label: 'Elliot', value: 0x0065 },
  { label: 'Heirhein Army', value: 0x0066 },
  { label: 'Heirhein Army', value: 0x0067 },
  { label: 'Heirhein Army', value: 0x0068 },
  { label: 'Commander', value: 0x0069 },
  { label: 'Anphony Army', value: 0x006A },
  { label: 'Thief', value: 0x006B },
  { label: 'Mackily Army', value: 0x006C },
  { label: 'Eve', value: 0x006D },
  { label: 'Macbeth', value: 0x006E },
  { label: 'Anphony Army', value: 0x006F },
  { label: 'Anphony Army', value: 0x0070 },
  { label: 'Anphony Army', value: 0x0071 },
  { label: 'Voltz', value: 0x0072 },
  { label: 'Mercenary', value: 0x0073 },
  { label: 'Clement', value: 0x0074 },
  { label: 'Mackily Army', value: 0x0075 },
  { label: 'Mackily Army', value: 0x0076 },
  { label: 'Mackily Army', value: 0x0077 },
  { label: 'Commander', value: 0x0078 },
  { label: 'Mackily Army', value: 0x0079 },
  { label: 'Shagall', value: 0x007A },
  { label: 'Agusty Army', value: 0x007B },
  { label: 'Agusty Army', value: 0x007C },
  { label: 'Commander', value: 0x007D },
  { label: 'Agusty Army', value: 0x007E },
  { label: 'Commander', value: 0x007F },
  { label: 'Agusty Army', value: 0x0080 },
  { label: 'Fury Squad', value: 0x0081 },
  { label: 'Zain', value: 0x0082 },
  { label: 'Agusty Army', value: 0x0083 },
  { label: 'Agusty Army', value: 0x0084 },
  { label: 'Agusty Army', value: 0x0085 },
  { label: 'Agusty Army', value: 0x0086 },
  { label: 'Eva', value: 0x0087 },
  { label: 'Alva', value: 0x0088 },
  { label: 'Shacoban', value: 0x0089 },
  { label: 'Madino Army', value: 0x008A },
  { label: 'Madino Army', value: 0x008B },
  { label: 'Madino Army', value: 0x008C },
  { label: 'Madino Army', value: 0x008D },
  { label: 'Madino Army', value: 0x008E },
  { label: 'Commander', value: 0x008F },
  { label: 'Madino Army', value: 0x0090 },
  { label: 'Commander', value: 0x0091 },
  { label: 'Madino Army', value: 0x0092 },
  { label: 'Commander', value: 0x0093 },
  { label: 'Madino Army', value: 0x0094 },
  { label: 'Commander', value: 0x0095 },
  { label: 'Madino Army', value: 0x0096 },
  { label: 'Commander', value: 0x0097 },
  { label: 'Madino Army', value: 0x0098 },
  { label: 'Commander', value: 0x0099 },
  { label: 'Madino Army', value: 0x009A },
  { label: 'Pirate', value: 0x009B },
  { label: 'Commander', value: 0x009C },
  { label: 'Silvail Army', value: 0x009D },
  { label: 'Eltosian', value: 0x009E },
  { label: 'Cross Knight', value: 0x009F },
  { label: 'Shagall', value: 0x00A0 },
  { label: 'Silvail Army', value: 0x00A1 },
  { label: 'Silvail Army', value: 0x00A2 },
  { label: 'Papilion', value: 0x00A3 },
  { label: 'Thracia Army', value: 0x00A4 },
  { label: 'Pirate', value: 0x00A5 },
  { label: 'Pirate', value: 0x00A6 },
  { label: 'Pirate', value: 0x00A7 },
  { label: 'Pirate', value: 0x00A8 },
  { label: 'Dobarl', value: 0x00A9 },
  { label: 'Pirate', value: 0x00AA },
  { label: 'Pizarl', value: 0x00AB },
  { label: 'Pirate', value: 0x00AC },
  { label: 'Pirate', value: 0x00AD },
  { label: 'Pirate', value: 0x00AE },
  { label: 'Pirate', value: 0x00AF },
  { label: 'Alvis', value: 0x00B0 },
  { label: 'Langobalt', value: 0x00B1 },
  { label: 'Grao Ritter', value: 0x00B2 },
  { label: 'Reptor', value: 0x00B3 },
  { label: 'Gelp Ritter', value: 0x00B4 },
  { label: 'Mahnya', value: 0x00B5 },
  { label: 'Silesia Army', value: 0x00B6 },
  { label: 'Maios', value: 0x00B7 },
  { label: 'Thove Army', value: 0x00B8 },
  { label: 'Thove Army', value: 0x00B9 },
  { label: 'Commander', value: 0x00BA },
  { label: 'Thove Army', value: 0x00BB },
  { label: 'Cuvuli', value: 0x00BC },
  { label: 'Thove Army', value: 0x00BD },
  { label: 'Commander', value: 0x00BE },
  { label: 'Thove Army', value: 0x00BF },
  { label: 'Thove Army', value: 0x00C0 },
  { label: 'Deetva', value: 0x00C1 },
  { label: 'Deetva Squad', value: 0x00C2 },
  { label: 'Pirate', value: 0x00C3 },
  { label: 'Silesia Army', value: 0x00C4 },
  { label: 'Dakar', value: 0x00C5 },
  { label: 'Mahnya', value: 0x00C6 },
  { label: 'Mahnya Squad', value: 0x00C7 },
  { label: 'Pamela', value: 0x00C8 },
  { label: 'Pamela Squad', value: 0x00C9 },
  { label: 'Andr�', value: 0x00CA },
  { label: 'Beig Ritter', value: 0x00CB },
  { label: 'Civilian', value: 0x00CC },
  { label: 'Civilian', value: 0x00CD },
  { label: 'Donovan', value: 0x00CE },
  { label: 'Zaxon Army', value: 0x00CF },
  { label: 'Zaxon Army', value: 0x00D0 },
  { label: 'Zaxon Army', value: 0x00D1 },
  { label: 'Zaxon Army', value: 0x00D2 },
  { label: 'Zaxon Army', value: 0x00D3 },
  { label: 'Lamia', value: 0x00D4 },
  { label: 'Mercenary', value: 0x00D5 },
  { label: 'Mercenary', value: 0x00D6 },
  { label: 'Mercenary', value: 0x00D7 },
  { label: 'Mercenary', value: 0x00D8 },
  { label: 'Mercenary', value: 0x00D9 },
  { label: 'Langobalt', value: 0x00DA },
  { label: 'Child', value: 0x00DB },
  { label: 'Lubeck Army', value: 0x00DC },
  { label: 'Slayder', value: 0x00DD },
  { label: 'Lubeck Army', value: 0x00DE },
  { label: 'Commander', value: 0x00DF },
  { label: 'Lubeck Army', value: 0x00E0 },
  { label: 'Lubeck Army', value: 0x00E1 },
  { label: 'Thief', value: 0x00E2 },
  { label: 'Commander', value: 0x00E3 },
  { label: 'Lubeck Army', value: 0x00E4 },
  { label: 'Lubeck Army', value: 0x00E5 },
  { label: 'Lubeck Army', value: 0x00E6 },
  { label: 'Vylon', value: 0x00E7 },
  { label: 'Andr�', value: 0x00E8 },
  { label: 'Beig Ritter', value: 0x00E9 },
  { label: 'Vaha', value: 0x00EA },
  { label: 'Velthomer Army', value: 0x00EB },
  { label: 'Priest', value: 0x00EC },
  { label: 'Velthomer Army', value: 0x00ED },
  { label: 'Torabant', value: 0x00EE },
  { label: 'Magorn', value: 0x00EF },
  { label: 'Thracia Army', value: 0x00F0 },
  { label: 'Lenster Army', value: 0x00F1 },
  { label: 'Aida', value: 0x00F2 },
  { label: 'Velthomer Army', value: 0x00F3 },
  { label: 'Reptor', value: 0x00F4 },
  { label: 'Freege Army', value: 0x00F5 },
  { label: 'Freege Army', value: 0x00F6 },
  { label: 'Freege Army', value: 0x00F7 },
  { label: 'Freege Army', value: 0x00F8 },
  { label: 'Freege Army', value: 0x00F9 },
  { label: 'Freege Army', value: 0x00FA },
  { label: 'Freege Army', value: 0x00FB },
  { label: 'Freege Army', value: 0x00FC },
  { label: 'Commander', value: 0x00FD },
  { label: 'Rot Ritter', value: 0x00FE },
  { label: 'Commander', value: 0x00FF },
  { label: 'Rot Ritter', value: 0x0100 },
  { label: 'Commander', value: 0x0101 },
  { label: 'Rot Ritter', value: 0x0102 },
  { label: 'Alvis', value: 0x0103 },
  { label: 'Commander', value: 0x0104 },
  { label: 'Rot Ritter', value: 0x0105 },
  { label: 'Harold', value: 0x0106 },
  { label: 'Ganesha Army', value: 0x0107 },
  { label: 'Ganesha Army', value: 0x0108 },
  { label: 'Thief', value: 0x0109 },
  { label: 'Sophara Army', value: 0x010A },
  { label: 'Isaac Army', value: 0x010B },
  { label: 'Isaac Army', value: 0x010C },
  { label: 'Sophara Army', value: 0x010D },
  { label: 'Shumit', value: 0x010E },
  { label: 'Rivough Army', value: 0x010F },
  { label: 'Danan', value: 0x0110 },
  { label: 'Ganesha Army', value: 0x0111 },
  { label: 'Ganesha Army', value: 0x0112 },
  { label: 'Coutouzov', value: 0x0113 },
  { label: 'YiedMage', value: 0x0114 },
  { label: 'Yied Mage', value: 0x0115 },
  { label: 'Mercenary', value: 0x0116 },
  { label: 'Yied Mage', value: 0x0117 },
  { label: 'Commander', value: 0x0118 },
  { label: 'Alster Army', value: 0x0119 },
  { label: 'Alster Army', value: 0x011A },
  { label: 'Thief', value: 0x011B },
  { label: 'Blume', value: 0x011C },
  { label: 'Alster Army', value: 0x011D },
  { label: 'Darna Army', value: 0x011E },
  { label: 'Ishtor', value: 0x011F },
  { label: 'Melgen Army', value: 0x0120 },
  { label: 'Liza', value: 0x0121 },
  { label: 'Melgen Army', value: 0x0122 },
  { label: 'Melgen Army', value: 0x0123 },
  { label: 'Melgen Army', value: 0x0124 },
  { label: 'Melgen Army', value: 0x0125 },
  { label: 'Melgen Army', value: 0x0126 },
  { label: 'Melgen Army', value: 0x0127 },
  { label: 'Jabarro', value: 0x0128 },
  { label: 'Mercenary', value: 0x0129 },
  { label: 'Mercenary', value: 0x012A },
  { label: 'Bramsel', value: 0x012B },
  { label: 'Darna Army', value: 0x012C },
  { label: 'Commander', value: 0x012D },
  { label: 'Alster Army', value: 0x012E },
  { label: 'Alster Army', value: 0x012F },
  { label: 'Vanpa', value: 0x0130 },
  { label: 'Fetora', value: 0x0131 },
  { label: 'Eliu', value: 0x0132 },
  { label: 'High Mage', value: 0x0133 },
  { label: 'High Mage', value: 0x0134 },
  { label: 'High Mage', value: 0x0135 },
  { label: 'Muhammed', value: 0x0136 },
  { label: 'Conote Army', value: 0x0137 },
  { label: 'Conote Army', value: 0x0138 },
  { label: 'Conote Army', value: 0x0139 },
  { label: 'Priest', value: 0x013A },
  { label: 'Ovo', value: 0x013B },
  { label: 'Conote Army', value: 0x013C },
  { label: 'Conote Army', value: 0x013D },
  { label: 'Thief', value: 0x013E },
  { label: 'Commander', value: 0x013F },
  { label: 'Conote Army', value: 0x0140 },
  { label: 'Ishtar', value: 0x0141 },
  { label: 'Commander', value: 0x0142 },
  { label: 'Conote Army', value: 0x0143 },
  { label: 'Blume', value: 0x0144 },
  { label: 'Conote Army', value: 0x0145 },
  { label: 'Civilian', value: 0x0146 },
  { label: 'Civilian', value: 0x0147 },
  { label: 'Commander', value: 0x0148 },
  { label: 'Thracia Army', value: 0x0149 },
  { label: 'Coruta', value: 0x014A },
  { label: 'Thracia Army', value: 0x014B },
  { label: 'Commander', value: 0x014C },
  { label: 'Thracia Army', value: 0x014D },
  { label: 'Commander', value: 0x014E },
  { label: 'Thracia Army', value: 0x014F },
  { label: 'Maikov', value: 0x0150 },
  { label: 'Vanpa', value: 0x0151 },
  { label: 'Fetora', value: 0x0152 },
  { label: 'Eliu', value: 0x0153 },
  { label: 'Kapathogia Army', value: 0x0154 },
  { label: 'Kapathogia Army', value: 0x0155 },
  { label: 'Kapathogia Army', value: 0x0156 },
  { label: 'Kapathogia Army', value: 0x0157 },
  { label: 'Thracia Army', value: 0x0158 },
  { label: 'Thracia Army', value: 0x0159 },
  { label: 'Thief', value: 0x015A },
  { label: 'Kanatz', value: 0x015B },
  { label: 'Disler', value: 0x015C },
  { label: 'Grutia Army', value: 0x015D },
  { label: 'Mercenary', value: 0x015E },
  { label: 'Mercenary', value: 0x015F },
  { label: 'Torabant', value: 0x0160 },
  { label: 'Thracia Army', value: 0x0161 },
  { label: 'Judah', value: 0x0162 },
  { label: 'Commander', value: 0x0163 },
  { label: 'Grutia Army', value: 0x0164 },
  { label: 'Arion', value: 0x0165 },
  { label: 'Dragon Knight', value: 0x0166 },
  { label: 'Dragon Knight', value: 0x0167 },
  { label: 'Commander', value: 0x0168 },
  { label: 'Thracia Army', value: 0x0169 },
  { label: 'Commander', value: 0x016A },
  { label: 'Thracia Army', value: 0x016B },
  { label: 'Commander', value: 0x016C },
  { label: 'Thracia Army', value: 0x016D },
  { label: 'Musar', value: 0x016E },
  { label: 'Imperial Army', value: 0x016F },
  { label: 'Imperial Army', value: 0x0170 },
  { label: 'Imperial Army', value: 0x0171 },
  { label: 'Imperial Army', value: 0x0172 },
  { label: 'Lideel', value: 0x0173 },
  { label: 'Lideel Squad', value: 0x0174 },
  { label: 'Lideel Squad', value: 0x0175 },
  { label: 'Lideel Squad', value: 0x0176 },
  { label: 'Lideel Squad', value: 0x0177 },
  { label: 'Lideel Squad', value: 0x0178 },
  { label: 'Morrigan', value: 0x0179 },
  { label: 'Dark Mage', value: 0x017A },
  { label: 'Pirate', value: 0x017B },
  { label: 'Hilda', value: 0x017C },
  { label: 'Dark Priest', value: 0x017D },
  { label: 'Dark Mage', value: 0x017E },
  { label: 'Dark Mage', value: 0x017F },
  { label: 'Mercenary', value: 0x0180 },
  { label: 'Mercenary', value: 0x0181 },
  { label: 'Child', value: 0x0182 },
  { label: 'Child', value: 0x0183 },
  { label: 'Zagam', value: 0x0184 },
  { label: 'Dark Mage', value: 0x0185 },
  { label: 'Dark Mage', value: 0x0186 },
  { label: 'Dark Mage', value: 0x0187 },
  { label: 'Dark Mage', value: 0x0188 },
  { label: 'Dark Mage', value: 0x0189 },
  { label: 'Mercenary', value: 0x018A },
  { label: 'Mercenary', value: 0x018B },
  { label: 'Mercenary', value: 0x018C },
  { label: 'Julius', value: 0x018D },
  { label: 'Ishtar', value: 0x018E },
  { label: 'Alvis', value: 0x018F },
  { label: 'Rot Ritter', value: 0x0190 },
  { label: 'Rot Ritter', value: 0x0191 },
  { label: 'Rot Ritter', value: 0x0192 },
  { label: 'Dark Mage', value: 0x0193 },
  { label: 'Palmark', value: 0x0194 },
  { label: 'Child', value: 0x0195 },
  { label: 'Child', value: 0x0196 },
  { label: 'Commander', value: 0x0197 },
  { label: 'Rot Ritter', value: 0x0198 },
  { label: 'Rot Ritter', value: 0x0199 },
  { label: 'Commander', value: 0x019A },
  { label: 'Rot Ritter', value: 0x019B },
  { label: 'Rot Ritter', value: 0x019C },
  { label: 'Commander', value: 0x019D },
  { label: 'Rot Ritter', value: 0x019E },
  { label: 'Rot Ritter', value: 0x019F },
  { label: 'Rot Ritter', value: 0x01A0 },
  { label: 'Dark Mage', value: 0x01A1 },
  { label: 'Dark Mage', value: 0x01A2 },
  { label: 'Robert', value: 0x01A3 },
  { label: 'Mercenary', value: 0x01A4 },
  { label: 'Mercenary', value: 0x01A5 },
  { label: 'Mercenary', value: 0x01A6 },
  { label: 'Mercenary', value: 0x01A7 },
  { label: 'Mercenary', value: 0x01A8 },
  { label: 'Boyce', value: 0x01A9 },
  { label: 'Mercenary', value: 0x01AA },
  { label: 'Mercenary', value: 0x01AB },
  { label: 'Rodan', value: 0x01AC },
  { label: 'Edda Army', value: 0x01AD },
  { label: 'Edda Army', value: 0x01AE },
  { label: 'Edda Army', value: 0x01AF },
  { label: 'Edda Army', value: 0x01B0 },
  { label: 'Yupheel', value: 0x01B1 },
  { label: 'Dark Mage', value: 0x01B2 },
  { label: 'Dark Mage', value: 0x01B3 },
  { label: 'Fisher', value: 0x01B4 },
  { label: 'Dozel Army', value: 0x01B5 },
  { label: 'Dozel Army', value: 0x01B6 },
  { label: 'Brian', value: 0x01B7 },
  { label: 'Grao Ritter', value: 0x01B8 },
  { label: 'Grao Ritter', value: 0x01B9 },
  { label: 'Dagon', value: 0x01BA },
  { label: 'Scorpio', value: 0x01BB },
  { label: 'Beig Ritter', value: 0x01BC },
  { label: 'Beig Ritter', value: 0x01BD },
  { label: 'Hilda', value: 0x01BE },
  { label: 'Gelp Ritter', value: 0x01BF },
  { label: 'Gelp Ritter', value: 0x01C0 },
  { label: 'Dark Priest', value: 0x01C1 },
  { label: 'Dark Mage', value: 0x01C2 },
  { label: 'Manfloy', value: 0x01C3 },
  { label: 'Dark Mage', value: 0x01C4 },
  { label: 'Julius', value: 0x01C5 },
  { label: 'Eins', value: 0x01C6 },
  { label: 'Zwei', value: 0x01C7 },
  { label: 'Drei', value: 0x01C8 },
  { label: 'Vier', value: 0x01C9 },
  { label: 'Funf', value: 0x01CA },
  { label: 'Sechs', value: 0x01CB },
  { label: 'Seiben', value: 0x01CC },
  { label: 'Aght', value: 0x01CD },
  { label: 'Neun', value: 0x01CE },
  { label: 'Zehn', value: 0x01CF },
  { label: 'Elf', value: 0x01D0 },
  { label: 'Zwolf', value: 0x01D1 },
  { label: 'Arion', value: 0x01D2 },
  { label: 'Dragon Knight', value: 0x01D3 },
  { label: 'Ishtar', value: 0x01D4 },
  { label: 'Meng', value: 0x01D5 },
  { label: 'Maybell', value: 0x01D6 },
  { label: 'Bleg', value: 0x01D7 },
  { label: 'Barhara Army', value: 0x01D8 },
  { label: 'Barhara Army', value: 0x01D9 },
  { label: 'Barhara Army', value: 0x01DA },
  { label: 'Barhara Army', value: 0x01DB },
  { label: 'Baran', value: 0x01DC },
  { label: 'Coutouzov', value: 0x01DD },
  { label: 'Thief', value: 0x01DE },
  { label: 'Gazak', value: 0x01DF },
  { label: 'Clotho', value: 0x01E0 },
  { label: 'Weissman', value: 0x01E1 },
  { label: 'Shark', value: 0x01E2 },
  { label: 'Hood', value: 0x01E3 },
  { label: 'Bacchus', value: 0x01E4 },
  { label: 'Emmile', value: 0x01E5 },
  { label: 'Darez', value: 0x01E6 },
  { label: 'Jirou', value: 0x01E7 },
  { label: 'Mahatma', value: 0x01E8 },
  { label: 'Lovin', value: 0x01E9 },
  { label: 'Backnun', value: 0x01EA },
  { label: 'Milley', value: 0x01EB },
  { label: 'Hertzog', value: 0x01EC },
  { label: 'Chekov', value: 0x01ED },
  { label: 'Keimos', value: 0x01EE },
  { label: 'Marilyn', value: 0x01EF },
  { label: 'Taylor', value: 0x01F0 },
  { label: 'Ripp', value: 0x01F1 },
  { label: 'Perio', value: 0x01F2 },
  { label: 'Trevic', value: 0x01F3 },
  { label: 'Gellar', value: 0x01F4 },
  { label: 'Bazan', value: 0x01F5 },
  { label: 'Duma', value: 0x01F6 },
  { label: 'Keller', value: 0x01F7 },
  { label: 'Torton', value: 0x01F8 },
  { label: 'Mario', value: 0x01F9 },
  { label: 'Kemall', value: 0x01FA },
  { label: 'Karedin', value: 0x01FB },
  { label: 'Keith', value: 0x01FC },
  { label: 'Sangor', value: 0x01FD },
  { label: 'Nikita', value: 0x01FE },
  { label: 'Nene', value: 0x01FF },
  { label: 'Kraff', value: 0x0200 },
  { label: 'Nikias', value: 0x0201 },
  { label: 'Atlas', value: 0x0202 },
  { label: 'Jackal', value: 0x0203 },
  { label: 'Ripp', value: 0x0204 },
  { label: 'Greias', value: 0x0205 },
  { label: 'Geese', value: 0x0206 },
  { label: 'Lee', value: 0x0207 },
  { label: 'Shishel', value: 0x0208 },
  { label: 'Hawks', value: 0x0209 },
  { label: 'Nazar', value: 0x020A },
  { label: 'Thief', value: 0x020B },
  { label: 'Tolstoy', value: 0x020C },
  { label: 'Botman', value: 0x020D },
  { label: 'Kulyuge', value: 0x020E },
  { label: 'Mansten', value: 0x020F },
  { label: 'Kashim', value: 0x0210 },
  { label: 'Hepner', value: 0x0211 },
  { label: 'Randok', value: 0x0212 },
  { label: 'Volf', value: 0x0213 },
  { label: 'Duey', value: 0x0214 },
  { label: 'Fet', value: 0x0215 },
  { label: 'Marshak', value: 0x0216 },
  { label: 'Luis', value: 0x0217 },
  { label: 'Heste', value: 0x0218 },
  { label: 'Madah', value: 0x0219 },
  { label: 'Jismunt', value: 0x021A },
  { label: 'Zenon', value: 0x021B },
  { label: 'Jakson', value: 0x021C },
  { label: 'Indra', value: 0x021D },
  { label: 'Neizche', value: 0x021E },
  { label: 'Apostle', value: 0x021F },
  { label: 'Millia', value: 0x0220 },
  { label: 'Siron', value: 0x0221 },
  { label: 'Grein', value: 0x0222 },
  { label: 'Slayton', value: 0x0223 },
  { label: 'Torstar', value: 0x0224 },
  { label: 'Kanan', value: 0x0225 },
  { label: 'Hasman', value: 0x0226 },
  { label: 'Grantz', value: 0x0227 },
  { label: 'Krosloy', value: 0x0228 },
  { label: 'Rolan', value: 0x0229 },
  { label: 'Mashgli', value: 0x022A },
  { label: 'Riva', value: 0x022B },
  { label: 'Gloria', value: 0x022C },
  { label: 'Nothe', value: 0x022D },
  { label: 'Indra', value: 0x022E },
  { label: 'Dares', value: 0x022F },
  { label: 'Keimos', value: 0x0230 },
  { label: 'Marilyn', value: 0x0231 },
  { label: 'Zenon', value: 0x0232 },
  { label: 'Jakson', value: 0x0233 },
  { label: 'Torton', value: 0x0234 },
  { label: 'Mario', value: 0x0235 },
  { label: 'Kanan', value: 0x0236 },
  { label: 'Atlas', value: 0x0237 },
  { label: 'Zeus', value: 0x0238 },
  { label: 'Holsety', value: 0x0239 },
];

export const FE4Classes = [
  { label: 'Social Knight', value: 0x00 },
  { label: 'Lance Knight', value: 0x01 },
  { label: 'Arch Knight', value: 0x02 },
  { label: 'Axe Knight', value: 0x03 },
  { label: 'Free Knight', value: 0x04 },
  { label: 'Trobadour', value: 0x05 },
  { label: 'Lord Knight', value: 0x06 },
  { label: 'Duke Knight', value: 0x07 },
  { label: 'Master Knight', value: 0x08 },
  { label: 'Male Paladin', value: 0x09 },
  { label: 'Female Paladin', value: 0x0A },
  { label: 'Bow Knight', value: 0x0B },
  { label: 'Forrest Knight', value: 0x0C },
  { label: 'Mage Knight', value: 0x0D },
  { label: 'Great Knight', value: 0x0E },
  { label: 'Pegasus Rider', value: 0x0F },
  { label: 'Pegasus Knight', value: 0x10 },
  { label: 'Falcon Knight', value: 0x11 },
  { label: 'Dragon Rider', value: 0x12 },
  { label: 'Dragon Knight', value: 0x13 },
  { label: 'Dragon Master', value: 0x14 },
  { label: 'Bow Fighter', value: 0x15 },
  { label: 'Sword Fighter', value: 0x16 },
  { label: 'Sword Master', value: 0x17 },
  { label: 'Sniper', value: 0x18 },
  { label: 'Forrest', value: 0x19 },
  { label: 'General', value: 0x1A },
  { label: 'Emperor', value: 0x1B },
  { label: 'Baron', value: 0x1C },
  { label: 'Soldier', value: 0x1D },
  { label: 'Spear Soldier', value: 0x1E },
  { label: 'Axe Soldier', value: 0x1F },
  { label: 'Archer', value: 0x20 },
  { label: 'Sword Soldier', value: 0x21 },
  { label: 'Armor', value: 0x22 },
  { label: 'Axe Armor', value: 0x23 },
  { label: 'Bow Armor', value: 0x24 },
  { label: 'Sword Armor', value: 0x25 },
  { label: 'Barbarian', value: 0x26 },
  { label: 'Axe Fighter', value: 0x27 },
  { label: 'Mountain Thief', value: 0x28 },
  { label: 'Warrior', value: 0x29 },
  { label: 'Hunter', value: 0x2A },
  { label: 'Pirate', value: 0x2B },
  { label: 'Junior Lord', value: 0x2C },
  { label: 'Male Mage Fighter', value: 0x2D },
  { label: 'Prince', value: 0x2E },
  { label: 'Princess', value: 0x2F },
  { label: 'Female Mage Fighter', value: 0x30 },
  { label: 'Queen', value: 0x31 },
  { label: 'Dancer', value: 0x32 },
  { label: 'Priest', value: 0x33 },
  { label: 'Mage', value: 0x34 },
  { label: 'Fire Mage', value: 0x35 },
  { label: 'Thunder Mage', value: 0x36 },
  { label: 'Wind Mage', value: 0x37 },
  { label: 'High Priest', value: 0x38 },
  { label: 'Bishop', value: 0x39 },
  { label: 'Sage', value: 0x3A },
  { label: 'Bard', value: 0x3B },
  { label: 'Shaman', value: 0x3C },
  { label: 'Dark Mage', value: 0x3D },
  { label: 'Dark Bishop', value: 0x3E },
  { label: 'Thief', value: 0x3F },
  { label: 'Thief Fighter', value: 0x40 },
  { label: 'Civilian', value: 0x41 },
  { label: 'Child', value: 0x42 },
  { label: 'Long Arch', value: 0x43 },
  { label: 'Iron Arch', value: 0x44 },
  { label: 'Killer Arch', value: 0x45 },
  { label: 'Gold Arch', value: 0x46 },
  { label: 'Dark Prince', value: 0x47 },
  { label: 'None', value: 0xFF },
];

export const FE4Gender = [
  { label: 'Male', value: 0x00 },
  { label: 'Female', value: 0x01 },
  { label: 'None (Generic Enemies)', value: 0xFF },
];

export const FE4WeaponList = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Steel Sword', value: 0x01 },
  { label: 'Silver Sword', value: 0x02 },
  { label: 'Iron Blade', value: 0x03 },
  { label: 'Steel Blade', value: 0x04 },
  { label: 'Silver Blade', value: 0x05 },
  { label: 'Prayer Sword', value: 0x06 },
  { label: 'Thief Sword', value: 0x07 },
  { label: 'Barrier Sword', value: 0x08 },
  { label: 'Berserk Sword', value: 0x09 },
  { label: 'Hero\'s Sword', value: 0x0A },
  { label: 'Silence Sword', value: 0x0B },
  { label: 'Sleep Sword', value: 0x0C },
  { label: 'Thin Sword', value: 0x0D },
  { label: 'Defence Sword', value: 0x0E },
  { label: 'Fire Sword', value: 0x0F },
  { label: 'Earth Sword', value: 0x10 },
  { label: 'Thunder Sword', value: 0x11 },
  { label: 'Wind Sword', value: 0x12 },
  { label: 'Light Sword', value: 0x13 },
  { label: 'Mistoltin', value: 0x14 },
  { label: 'Tyrfing', value: 0x15 },
  { label: 'Balmunk', value: 0x16 },
  { label: 'Armor Killer', value: 0x17 },
  { label: 'Wing Clipper', value: 0x18 },
  { label: 'Broken Sword', value: 0x19 },
  { label: 'Broken Sword', value: 0x1A },
  { label: 'Broken Sword', value: 0x1B },
  { label: 'Iron Lance', value: 0x1C },
  { label: 'Steel Lance', value: 0x1D },
  { label: 'Silver Lance', value: 0x1E },
  { label: 'Hand Lance', value: 0x1F },
  { label: 'Knight Killer', value: 0x20 },
  { label: 'Hero\'s Lance', value: 0x21 },
  { label: 'Thin Lance', value: 0x22 },
  { label: 'Gungnir', value: 0x23 },
  { label: 'Gae Bolg', value: 0x24 },
  { label: 'Broken Lance', value: 0x25 },
  { label: 'Broken Lance', value: 0x26 },
  { label: 'Broken Lance', value: 0x27 },
  { label: 'Iron Axe', value: 0x28 },
  { label: 'Steel Axe', value: 0x29 },
  { label: 'Silver Axe', value: 0x2A },
  { label: 'Hero\'s Axe', value: 0x2B },
  { label: 'Swanchika', value: 0x2C },
  { label: 'Hand Axe', value: 0x2D },
  { label: 'Broken Axe', value: 0x2E },
  { label: 'Broken Axe', value: 0x2F },
  { label: 'Broken Axe', value: 0x30 },
  { label: 'Iron Bow', value: 0x31 },
  { label: 'Steel Bow', value: 0x32 },
  { label: 'Silver Bow', value: 0x33 },
  { label: 'Hero\'s Bow', value: 0x34 },
  { label: 'Killer Bow', value: 0x35 },
  { label: 'Ichieval', value: 0x36 },
  { label: 'Broken Bow', value: 0x37 },
  { label: 'Broken Bow', value: 0x38 },
  { label: 'Broken Bow', value: 0x39 },
  { label: 'Long Arch', value: 0x3A },
  { label: 'Iron Arch', value: 0x3B },
  { label: 'Killer Arch', value: 0x3C },
  { label: 'Gold Arch', value: 0x3D },
  { label: 'Fire', value: 0x3E },
  { label: 'El Fire', value: 0x3F },
  { label: 'Volcanon', value: 0x40 },
  { label: 'Fala Flame', value: 0x41 },
  { label: 'Meteo', value: 0x42 },
  { label: 'Thunder', value: 0x43 },
  { label: 'El Thunder', value: 0x44 },
  { label: 'Torron', value: 0x45 },
  { label: 'Tor Hammer', value: 0x46 },
  { label: 'Thunderstorm', value: 0x47 },
  { label: 'Wind', value: 0x48 },
  { label: 'El Wind', value: 0x49 },
  { label: 'Tornado', value: 0x4A },
  { label: 'Holsety', value: 0x4B },
  { label: 'Blizzard', value: 0x4C },
  { label: 'Lightning', value: 0x4D },
  { label: 'Rizziah', value: 0x4E },
  { label: 'Aura', value: 0x4F },
  { label: 'Narga', value: 0x50 },
  { label: 'Yotsmungand', value: 0x51 },
  { label: 'Fenrir', value: 0x52 },
  { label: 'Hell', value: 0x53 },
  { label: 'Loptous', value: 0x54 },
  { label: 'Empty Book', value: 0x55 },
  { label: 'Empty Book', value: 0x56 },
  { label: 'Empty Book', value: 0x57 },
  { label: 'Live Staff', value: 0x58 },
  { label: 'Relive Staff', value: 0x59 },
  { label: 'Recover Staff', value: 0x5A },
  { label: 'Libro Staff', value: 0x5B },
  { label: 'Reserve Staff', value: 0x5C },
  { label: 'Return Staff', value: 0x5D },
  { label: 'Warp Staff', value: 0x5E },
  { label: 'Rescue Staff', value: 0x5F },
  { label: 'Charm Staff', value: 0x60 },
  { label: 'Rest Staff', value: 0x61 },
  { label: 'Valkyre Staff', value: 0x62 },
  { label: 'Silence Staff', value: 0x63 },
  { label: 'Sleep Staff', value: 0x64 },
  { label: 'Berserk Staff', value: 0x65 },
  { label: 'Thief Staff', value: 0x66 },
  { label: 'Broken Staff', value: 0x67 },
  { label: 'Broken Staff', value: 0x68 },
  { label: 'Broken Staff', value: 0x69 },
  { label: 'Live Bracelet', value: 0x6A },
  { label: 'Elite Ring', value: 0x6B },
  { label: 'Thief Bracelet', value: 0x6C },
  { label: 'Prayer Bracelet', value: 0x6D },
  { label: 'Pursuit Ring', value: 0x6E },
  { label: 'Recover Ring', value: 0x6F },
  { label: 'Bargain Bracelet', value: 0x70 },
  { label: 'Knight Ring', value: 0x71 },
  { label: 'Return Ring', value: 0x72 },
  { label: 'Speed Ring', value: 0x73 },
  { label: 'Magic Ring', value: 0x74 },
  { label: 'Power Ring', value: 0x75 },
  { label: 'Shield Ring', value: 0x76 },
  { label: 'Barrier Ring', value: 0x77 },
  { label: 'Leg Ring', value: 0x78 },
  { label: 'Skill Ring', value: 0x79 },
  { label: 'Broken Sword', value: 0x7A },
  { label: 'Broken Spear', value: 0x7B },
  { label: 'Broken Bow', value: 0x7C },
  { label: 'Empty Book', value: 0x7D },
  { label: 'Empty Book', value: 0x7E },
  { label: 'Empty Book', value: 0x7F },
  { label: 'Empty Book', value: 0x80 },
  { label: 'Empty Book', value: 0x81 },
  { label: 'Empty Book', value: 0x82 },
  { label: 'Empty Book', value: 0x83 },
  { label: 'Empty Book', value: 0x84 },
  { label: 'Empty Book', value: 0x85 },
  { label: 'Empty Book', value: 0x86 },
  { label: 'Empty Book', value: 0x87 },
  { label: 'Broken Staff', value: 0x88 },
  { label: 'Circlet', value: 0x89 },
  { label: 'None', value: 0xFF },
];

export const FE4PlayerEquipment = [
  { label: '(Alec/Ch.6 Shop)', value: 0x01 },
  { label: '(Iron Sword)', value: 0x02 },
  { label: '(Arden/Ch.6 Shop)', value: 0x03 },
  { label: '(Dew/Ch.6 Shop)', value: 0x04 },
  { label: '(Delmud/Ch.7 Shop)', value: 0x05 },
  { label: '(Nanna/Ch. 8 Shop)', value: 0x06 },
  { label: '(Sigurd/Ch.7 Shop)', value: 0x07 },
  { label: '(Beowulf/Ch. 8 Shop)', value: 0x08 },
  { label: '(Noish/Ch. 9 Shop)', value: 0x09 },
  { label: '(Alvis>Sigurd/Ch.6 Shop)', value: 0x0A },
  { label: '(Ch.3 Shop/Ch. 9 Shop)', value: 0x0B },
  { label: '(Holyn/Ch.6 Shop)', value: 0x0C },
  { label: '(Ayra/Ch. 10 Shop)', value: 0x0D },
  { label: '(Skasaher/Ch.7 Shop)', value: 0x0E },
  { label: '(Lakche)', value: 0x0F },
  { label: '(Ch.2 Shop/Ch.7 Shop)', value: 0x10 },
  { label: '(Shanan)', value: 0x11 },
  { label: '(Steel Blade)', value: 0x12 },
  { label: '(*Shagall/*Blume)', value: 0x13 },
  { label: '(Hannibal)', value: 0x14 },
  { label: '(Lachesis/Commander)', value: 0x15 },
  { label: '(Dew>Lachesis/*Danan)', value: 0x16 },
  { label: '(Barrier Sword)', value: 0x17 },
  { label: '(Fee)', value: 0x18 },
  { label: '(Ayra Hero Sword/*Coruta)', value: 0x19 },
  { label: '(Patty Hero Sword)', value: 0x1A },
  { label: '(Patty)', value: 0x1B },
  { label: '(Ethlin/Ch. 8 Shop)', value: 0x1C },
  { label: '(Ch.1 Shop/Ch.7 Shop)', value: 0x1D },
  { label: '(Sylvia/Ch. 9 Shop)', value: 0x1E },
  { label: '(Celice/Ch.7 Shop)', value: 0x1F },
  { label: '(Defence Sword)', value: 0x20 },
  { label: '(Fire Sword/Ch.7 Shop)', value: 0x21 },
  { label: '(Eltoshan>Lachesis/Ch. 9 Shop)', value: 0x22 },
  { label: '(*Shacoban/Ch. 8 Shop)', value: 0x23 },
  { label: '(Wind Sword/Ch. 10 Shop)', value: 0x24 },
  { label: '(Light Sword/Ch.6 Shop)', value: 0x25 },
  { label: '(Mistoltin)', value: 0x26 },
  { label: '(Tyrfing)', value: 0x27 },
  { label: '(Balmunk)', value: 0x28 },
  { label: '(Armor Killer/Ch. 8 Shop)', value: 0x29 },
  { label: '(Oifaye)', value: 0x2A },
  { label: '(Wing Clipper/Ch. 9 Shop)', value: 0x2B },
  { label: '(Hannibal)', value: 0x2C },
  { label: '(Sigurd/Ch.7 Shop)', value: 0x2D },
  { label: '(Fin/Ch.7 Shop)', value: 0x2E },
  { label: '(Ch.1 Shop/Ch.7 Shop)', value: 0x2F },
  { label: '(Fin-Older/Ch. 8 Shop)', value: 0x30 },
  { label: '(Aless)', value: 0x31 },
  { label: '(Cuan/Ch. 8 Shop)', value: 0x32 },
  { label: '(Ch.2 Shop/Ch. 8 Shop)', value: 0x33 },
  { label: '(Steel Lance/Ch. 8 Shop)', value: 0x34 },
  { label: '(*Elliot/Ch. 9 Shop)', value: 0x35 },
  { label: '(Ch.3 Shop/Ch. 9 Shop)', value: 0x36 },
  { label: '(Cuan/Ch. 9 Shop)', value: 0x37 },
  { label: '(Ch.1 Shop/Ch. 9 Shop)', value: 0x38 },
  { label: '(Oifaye)', value: 0x39 },
  { label: '(*Zain/Bramsel)', value: 0x3A },
  { label: '(Hero Lance/*Muhammed)', value: 0x3B },
  { label: '(Fury/Ch.7 Shop)', value: 0x3C },
  { label: '(Fee/Ch.7 Shop)', value: 0x3D },
  { label: '(Gae Bolg)', value: 0x3E },
  { label: '(Lex\'s Iron Axe/Ch.7 Shop)', value: 0x3F },
  { label: '(Iron Axe)', value: 0x40 },
  { label: '(Ch.1 Shop/Ch.7 Shop)', value: 0x41 },
  { label: '(Johan)', value: 0x42 },
  { label: '(Johalver)', value: 0x43 },
  { label: '(Ch.3 Shop/Ch. 8 Shop)', value: 0x44 },
  { label: '(Hero Axe/*Shumit)', value: 0x45 },
  { label: '(*Kinbois/Ch.7 Shop)', value: 0x46 },
  { label: '(Mideel/Ch. 8 Shop)', value: 0x47 },
  { label: '(Lester/Ch. 8 Shop)', value: 0x48 },
  { label: '(Briggid/Ch.7 Shop)', value: 0x49 },
  { label: '(Ch.2 Shop/Ch. 8 Shop)', value: 0x4A },
  { label: '(Ch.3 Shop/Ch. 9 Shop)', value: 0x4B },
  { label: '(Faval)', value: 0x4C },
  { label: '(Hero Bow/*Commander)', value: 0x4D },
  { label: '(Jamuka/*Maikov)', value: 0x4E },
  { label: '(Ichival)', value: 0x4F },
  { label: '(Azel/Ch. 8 Shop)', value: 0x50 },
  { label: '(Fire/Ch.7 Shop)', value: 0x51 },
  { label: '(Ch.3 Shop/Ch. 9 Shop)', value: 0x52 },
  { label: '(*Hilda)', value: 0x53 },
  { label: '(Tiltyu/Ch.7 Shop)', value: 0x54 },
  { label: '(Ch.2 Shop/Ch. 8 Shop)', value: 0x55 },
  { label: '(Tinny)', value: 0x56 },
  { label: '(Tiltyu/*Ishtor)', value: 0x57 },
  { label: '(Ch.4 Shop/Ch. 8 Shop)', value: 0x58 },
  { label: '(Arthur/Ch. 9 Shop)', value: 0x59 },
  { label: '(Levin/Ch. 9 Shop)', value: 0x5A },
  { label: '(*Musar)', value: 0x5B },
  { label: '(Holsety)', value: 0x5C },
  { label: '(Sety/Ch. 8 Shop)', value: 0x5D },
  { label: '(Lightning)', value: 0x5E },
  { label: '(Ch. 6 Rizziah)', value: 0x5F },
  { label: '(Diadora/Ch.6 Aura)', value: 0x60 },
  { label: '(Narga)', value: 0x61 },
  { label: '(Ethlin/Ch.7 Shop)', value: 0x62 },
  { label: '(Lachesis/Ch.7 Shop)', value: 0x63 },
  { label: '(Rana/Ch. 8 Shop)', value: 0x64 },
  { label: '(Aideen/Ch. 8 Shop)', value: 0x65 },
  { label: '(Relive Staff)', value: 0x66 },
  { label: '(Nanna/Ch. 8 Shop)', value: 0x67 },
  { label: '(Ch.4 Shop/Ch. 10 Shop)', value: 0x68 },
  { label: '(Recover Staff/Ch.7 Shop)', value: 0x69 },
  { label: '(*Shagall/Ch. 10 Shop)', value: 0x6A },
  { label: '(Corple/Ch. 10 Shop)', value: 0x6B },
  { label: '(Claude/*Kapathogia)', value: 0x6C },
  { label: '(Return Staff/Ch.7 Shop)', value: 0x6D },
  { label: '(Warp Staff/Ch. 9 Shop)', value: 0x6E },
  { label: '(Rescue Staff/Ch. 10 Shop)', value: 0x6F },
  { label: '(Restore Staff/Ch. 9 Shop)', value: 0x70 },
  { label: '(Claude)', value: 0x71 },
  { label: '(Diadora/Ch. 8 Shop)', value: 0x72 },
  { label: '(*Clement/Ch. 10 Shop)', value: 0x73 },
  { label: '(Berserk Staff)', value: 0x74 },
  { label: '(*Dobarl/*Trabant Ring)', value: 0x75 },
  { label: '(Ch.8 Village)', value: 0x76 },
  { label: '(*Sandima/*Liza Ring)', value: 0x77 },
  { label: '(Magic Ring)', value: 0x78 },
  { label: '(*Gandolf/*Jabarro Ring)', value: 0x79 },
  { label: '(Skill Ring)', value: 0x7A },
  { label: '(Ch.P Village/Johan)', value: 0x7B },
  { label: '(Speed Ring)', value: 0x7C },
  { label: '(*Macbeth/*Ovo Ring)', value: 0x7D },
  { label: '(Ch.7 Village)', value: 0x7E },
  { label: '(*Boldor/Dark Priest Ring)', value: 0x7F },
  { label: '(Barrier Ring)', value: 0x80 },
  { label: '(*Pizarl/*Yurius Ring)', value: 0x81 },
  { label: '(*Phillip Ring)', value: 0x82 },
  { label: '(*Harold/Ch.4 Shop/*Disler Ring)', value: 0x83 },
  { label: '(Ch.10 Celice Beach)', value: 0x84 },
  { label: '(*Papilon/*Ishtar Bracelet)', value: 0x85 },
  { label: '(*Voltz/Johalver Ring)', value: 0x86 },
  { label: '(Bargain Ring)', value: 0x87 },
  { label: '(Knight Ring)', value: 0x88 },
  { label: '(Pursuit Ring)', value: 0x89 },
  { label: '(Prayer Bracelet/*Arion)', value: 0x8A },
  { label: '(Thief Bracelet)', value: 0x8B },
  { label: '(Circlet)', value: 0x8C },
  { label: '(Nothing)', value: 0x8D },
  { label: '(Nothing)', value: 0x8E },
  { label: 'Nothing', value: 0xFF },
];
