export const Backgrounds = [
  { label: '0x00 - Lyn\'s Tent Background', value: 0 },
  { label: '0x01 - House with fireplace', value: 1 },
  { label: '0x02 - Village (Garden)', value: 2 },
  { label: '0x03 - Village (Garden) (Night)', value: 3 },
  { label: '0x04 - On a Road to a Town or Village', value: 4 },
  { label: '0x05 - On a Road to a Town or Village (Night)', value: 5 },
  { label: '0x06 - On a Road to a Town or Village (Sunset)', value: 6 },
  { label: '0x07 - On a Road to a Town or Village (Partial Dark)', value: 7 },
  { label: '0x08 - On a Road to a Town or Village (Lighter Thing?)', value: 8 },
  { label: '0x09 - Destroyed Village (Originally 0x02)', value: 9 },
  { label: '0x0A - Sea Port', value: 10 },
  { label: '0x0B - Ship', value: 11 },
  { label: '0x0C - Ocean Coast with Rocks', value: 12 },
  { label: '0x0D - Hotel/House', value: 13 },
  { label: '0x0E - Outside of Palace (One in Bern)', value: 14 },
  { label: '0x0F - Outside of Castle (Special)', value: 15 },
  { label: '0x10 - Inside of Castle (Bluish-Green Pillars)', value: 16 },
  { label: '0x11 - Same as 0x10, Darker', value: 17 },
  { label: '0x12 - Room in a Castle (Used in Laus and Caelin?)', value: 18 },
  { label: '0x13 - Same as 0x12, Darker', value: 19 },
  { label: '0x14 - Castle Room (Used in Bern)', value: 20 },
  { label: '0x15 - Castle Hall (Light-Colored Walls)', value: 21 },
  { label: '0x16 - Same as 0x15, Darker, Purple Walls', value: 22 },
  { label: '0x17 - Caelin Castle Garden (used in end of Lyn\'s Tale)', value: 23 },
  { label: '0x18 - Castle Garden with Bushes', value: 24 },
  { label: '0x19 - Castle Hallway, Door in Front', value: 25 },
  { label: '0x1A - Same as 0x19, Darker, Purple Walls', value: 26 },
  { label: '0x1B - Prison/Cell', value: 27 },
  { label: '0x1C - Outside, Forest on Left (Grass)', value: 28 },
  { label: '0x1D - Plains with Hill and Mountains in background', value: 29 },
  { label: '0x1E - Same as 0x1C, Sunset', value: 30 },
  { label: '0x1F - Same as 0x1C, Dark/Night', value: 31 },
  { label: '0x20 - Same as 0x1C, Foggy/Cloudy', value: 32 },
  { label: '0x21 - Same as 0x20, More Fog', value: 33 },
  { label: '0x22 - Plains', value: 34 },
  { label: '0x23 - Outside, Forest and Mountains Background', value: 35 },
  { label: '0x24 - Same as 0x23, Part Darker', value: 36 },
  { label: '0x25 - Same as 0x23, Fog', value: 37 },
  { label: '0x26 - Same as 0x23, Sunset', value: 38 },
  { label: '0x27 - Same as 0x24, Darker/Night', value: 39 },
  { label: '0x28 - Same as 0x24, Lighter', value: 40 },
  { label: '0x29 - Forest/Grass with Mountains (Special)', value: 41 },
  { label: '0x2A - Forest with Tall Trees', value: 42 },
  { label: '0x2B - Forest (Special)', value: 43 },
  { label: '0x2C - Forest (Different)', value: 44 },
  { label: '0x2D - Forest with Light out of Corner', value: 45 },
  { label: '0x2E - Forest of 0x2C (Foggy)', value: 46 },
  { label: '0x2F - City (Bulgar)', value: 47 },
  { label: '0x30 - City (Bulgar, Golden)', value: 48 },
  { label: '0x31 - Outside of City Gate', value: 49 },
  { label: '0x32 - Same as 0x31, Sunset', value: 50 },
  { label: '0x33 - Same as 0x31, Darker', value: 51 },
  { label: '0x34 - Same as 0x31 (???)', value: 52 },
  { label: '0x35 - House/Hotel with Bed', value: 53 },
  { label: '0x36 - Outside of Castle/Fortress (Brown)', value: 54 },
  { label: '0x37 - Outside of Castle/Fortress (Gray)', value: 55 },
  { label: '0x38 - Same as 0x36, Night', value: 56 },
  { label: '0x39 - Outside of Castle/Fortress (Different) (Brown)', value: 57 },
  { label: '0x3A - Outside of Castle/Fortress (Gray)', value: 58 },
  { label: '0x3B - Same as 0x39, Different Palette', value: 59 },
  { label: '0x3C - Castle/Dungeon (Inside)', value: 60 },
  { label: '0x3D - Same as 0x3C, Night? (Purple)', value: 61 },
  { label: '0x3E - Same as 0x3C, Sunset?', value: 62 },
  { label: '0x3F - Outside, Abandoned Fortress Background', value: 63 },
  { label: '0x40 - Same as 0x3F, Sunset', value: 64 },
  { label: '0x41 - Same as 0x3F, Foggy', value: 65 },
  { label: '0x42 - Inside Abandoned Fortress (Brown)', value: 66 },
  { label: '0x43 - Inside Abandoned Fortress (Purple/Dark?)', value: 67 },
  { label: '0x44 - Dragon\'s Gate Hall/Chamber (Brown)', value: 68 },
  { label: '0x45 - Dragon\'s Gate Hall/Chamber (Green)', value: 69 },
  { label: '0x46 - Dungeon Hallway (Brown)', value: 70 },
  { label: '0x47 - Dungeon Hallway (Blue)', value: 71 },
  { label: '0x48 - Dungeon Hallway (Green)', value: 72 },
  { label: '0x49 - Shrine/Alter', value: 73 },
  { label: '0x4A - Athos Shrine/Alter', value: 74 },
  { label: '0x4B - Athos Shrine/Alter (Darker)', value: 75 },
  { label: '0x4C - Shrine Hallway', value: 76 },
  { label: '0x4D - Shrine Hallway (Darker)', value: 77 },
  { label: '0x4E - Shrine Hallway (Purple)', value: 78 },
  { label: '0x4F - Shrine/Alter 2 (Brown)', value: 79 },
  { label: '0x50 - Shrine/Alter 2 (Golden)', value: 80 },
  { label: '0x51 - Desert', value: 81 },
  { label: '0x52 - Desert (Sunset)', value: 82 },
  { label: '0x53 - Dragon\'s Gate (Green)', value: 83 },
  { label: '0x54 - Dragon\'s Gate (Dark/Night)', value: 84 },
  { label: '0x55 - Fire Pit/Underworld', value: 85 },
  { label: '0x56 - Shrine/Alter 3 (Durandal?)', value: 86 },
  { label: '0x57 - Cave', value: 87 },
  { label: '0x58 - Shrine/Alter 4', value: 88 },
  { label: '0x59 - Sky', value: 89 },
  { label: '0x5A - Camp/Tent with Weapons', value: 90 },
  { label: '0x5B - Black Background', value: 91 },
  { label: '0x5C - Dragon\'s Gate (Close-Up)', value: 92 },
  { label: '0x5D - Dragon\'s Gate (Close-Up) (Lighter)', value: 93 },
  { label: '0x5E - To Be Continued', value: 94 },
  { label: '0x5F- Game Over', value: 95 },
];

export default Backgrounds;
