export const names = [
  { label: 'Durandal', value: 0 },
  { label: 'Armads', value: 1 },
  { label: 'Aureola', value: 2 },
  { label: 'Forblaze', value: 3 },
];

export const ItemList = [
  { label: 'None', value: 0x00 },
  { label: 'Iron Sword', value: 0x01 },
  { label: 'Slim Sword', value: 0x02 },
  { label: 'Steel Sword', value: 0x03 },
  { label: 'Silver Sword', value: 0x04 },
  { label: 'Iron Blade', value: 0x05 },
  { label: 'Steel Blade', value: 0x06 },
  { label: 'Silver Blade', value: 0x07 },
  { label: 'Poison Sword', value: 0x08 },
  { label: 'Rapier', value: 0x09 },
  { label: 'Mani Katti', value: 0x0A },
  { label: 'Brave Sword', value: 0x0B },
  { label: 'Wo Dao', value: 0x0C },
  { label: 'Killing Edge', value: 0x0D },
  { label: 'Armourslayer', value: 0x0E },
  { label: 'Wyrmslayer', value: 0x0F },
  { label: 'Light Brand', value: 0x10 },
  { label: 'Rune Sword', value: 0x11 },
  { label: 'Lancereaver', value: 0x12 },
  { label: 'Long Sword', value: 0x13 },
  { label: 'Iron Lance', value: 0x14 },
  { label: 'Slim Lance', value: 0x15 },
  { label: 'Steel Lance', value: 0x16 },
  { label: 'Silver Lance', value: 0x17 },
  { label: 'Poison Lance', value: 0x18 },
  { label: 'Brave Spear', value: 0x19 },
  { label: 'Killer Lance', value: 0x1A },
  { label: 'Horseslayer', value: 0x1B },
  { label: 'Javelin', value: 0x1C },
  { label: 'Spear', value: 0x1D },
  { label: 'Axereaver', value: 0x1E },
  { label: 'Iron Axe', value: 0x1F },
  { label: 'Steel Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Poison Axe', value: 0x22 },
  { label: 'Brave Axe', value: 0x23 },
  { label: 'Killer Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Hammer', value: 0x26 },
  { label: 'Devil Axe', value: 0x27 },
  { label: 'Hand Axe', value: 0x28 },
  { label: 'Tomahawk', value: 0x29 },
  { label: 'Swordreaver', value: 0x2A },
  { label: 'Swordslayer', value: 0x2B },
  { label: 'Iron Bow', value: 0x2C },
  { label: 'Steel Bow', value: 0x2D },
  { label: 'Silver Bow', value: 0x2E },
  { label: 'Poison Bow', value: 0x2F },
  { label: 'Killer Bow', value: 0x30 },
  { label: 'Brave Bow', value: 0x31 },
  { label: 'Short Bow', value: 0x32 },
  { label: 'Longbow', value: 0x33 },
  { label: 'Ballista', value: 0x34 },
  { label: 'Iron Ballista', value: 0x35 },
  { label: 'Killer Ballista', value: 0x36 },
  { label: 'Fire', value: 0x37 },
  { label: 'Thunder', value: 0x38 },
  { label: 'Elfire', value: 0x39 },
  { label: 'Bolting', value: 0x3A },
  { label: 'Fimbulvetr', value: 0x3B },
  { label: 'Forblaze', value: 0x3C },
  { label: 'Excalibur', value: 0x3D },
  { label: 'Lightning', value: 0x3E },
  { label: 'Shine', value: 0x3F },
  { label: 'Divine', value: 0x40 },
  { label: 'Purge', value: 0x41 },
  { label: 'Aura', value: 0x42 },
  { label: 'Luce', value: 0x43 },
  { label: 'Flux', value: 0x44 },
  { label: 'Luna', value: 0x45 },
  { label: 'Nosferatu', value: 0x46 },
  { label: 'Eclipse', value: 0x47 },
  { label: 'Fenrir', value: 0x48 },
  { label: 'Gespenst', value: 0x49 },
  { label: 'Heal', value: 0x4A },
  { label: 'Mend', value: 0x4B },
  { label: 'Recover', value: 0x4C },
  { label: 'Physic', value: 0x4D },
  { label: 'Fortify', value: 0x4E },
  { label: 'Restore', value: 0x4F },
  { label: 'Silence', value: 0x50 },
  { label: 'Sleep', value: 0x51 },
  { label: 'Berserk', value: 0x52 },
  { label: 'Warp', value: 0x53 },
  { label: 'Rescue', value: 0x54 },
  { label: 'Torch', value: 0x55 },
  { label: 'Hammerne', value: 0x56 },
  { label: 'Unlock', value: 0x57 },
  { label: 'Barrier', value: 0x58 },
  { label: 'Dragon Axe', value: 0x59 },
  { label: 'Angelic Robe', value: 0x5A },
  { label: 'Energy Ring', value: 0x5B },
  { label: 'Secret Book', value: 0x5C },
  { label: 'Speedwings', value: 0x5D },
  { label: 'Goddess Icon', value: 0x5E },
  { label: 'Dragon Shield', value: 0x5F },
  { label: 'Talisman', value: 0x60 },
  { label: 'Boots', value: 0x61 },
  { label: 'Body Ring', value: 0x62 },
  { label: 'Hero\'s Crest', value: 0x63 },
  { label: 'Knight\'s Crest', value: 0x64 },
  { label: 'Orion\'s Bolt', value: 0x65 },
  { label: 'Elysian Whip', value: 0x66 },
  { label: 'Guiding Ring', value: 0x67 },
  { label: 'Chest Key', value: 0x68 },
  { label: 'Door Key', value: 0x69 },
  { label: 'Lockpick', value: 0x6A },
  { label: 'Vulnerary', value: 0x6B },
  { label: 'Elixir', value: 0x6C },
  { label: 'Pure Water', value: 0x6D },
  { label: 'Antitoxin', value: 0x6E },
  { label: 'Torch', value: 0x6F },
  { label: 'Delphi Shield', value: 0x70 },
  { label: 'Member Card', value: 0x71 },
  { label: 'Silver Card', value: 0x72 },
  { label: 'White Gem', value: 0x73 },
  { label: 'Blue Gem', value: 0x74 },
  { label: 'Red Gem', value: 0x75 },
  { label: 'Gold', value: 0x76 },
  { label: 'Uber Spear', value: 0x77 },
  { label: 'Chest Key (5)', value: 0x78 },
  { label: 'Mine', value: 0x79 },
  { label: 'Light Rune', value: 0x7A },
  { label: 'Iron Rune', value: 0x7B },
  { label: 'Filla\'s Might', value: 0x7C },
  { label: 'Ninis\'s Grace', value: 0x7D },
  { label: 'Thor\'s Ire', value: 0x7E },
  { label: 'Set\'s Litany', value: 0x7F },
  { label: 'Emblem Sword', value: 0x80 },
  { label: 'Emblem Spear', value: 0x81 },
  { label: 'Emblem Axe', value: 0x82 },
  { label: 'Emblem Bow', value: 0x83 },
  { label: 'Durandal', value: 0x84 },
  { label: 'Armads', value: 0x85 },
  { label: 'Aureola', value: 0x86 },
  { label: 'Earth Seal', value: 0x87 },
  { label: 'Afa\'s Drops', value: 0x88 },
  { label: 'Heaven Seal', value: 0x89 },
  { label: 'Emblem Seal', value: 0x8A },
  { label: 'Fell Contract', value: 0x8B },
  { label: 'Sol Katti', value: 0x8C },
  { label: 'Wolf Beil/Flamberge', value: 0x8D },
  { label: 'Ereshkigal', value: 0x8E },
  { label: 'Flametongue', value: 0x8F },
  { label: 'Regal Blade', value: 0x90 },
  { label: 'Rex Hasta', value: 0x91 },
  { label: 'Basilikos', value: 0x92 },
  { label: 'Rienfleche', value: 0x93 },
  { label: 'Heavy Spear', value: 0x94 },
  { label: 'Short Spear', value: 0x95 },
  { label: 'Ocean Seal', value: 0x96 },
  { label: '3000 G', value: 0x97 },
  { label: '5000 G', value: 0x98 },
  { label: 'Wind Sword', value: 0x99 },
  { label: '???', value: 0x9A },
];
