export const FE6SpellAssociationEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
  { label: 'Entry 68', value: 68 },
  { label: 'Entry 69', value: 69 },
  { label: 'Entry 70', value: 70 },
  { label: 'Entry 71', value: 71 },
  { label: 'Entry 72', value: 72 },
  { label: 'Entry 73', value: 73 },
  { label: 'Entry 74', value: 74 },
  { label: 'Entry 75', value: 75 },
  { label: 'Entry 76', value: 76 },
  { label: 'Entry 77', value: 77 },
  { label: 'Entry 78', value: 78 },
  { label: 'Entry 79', value: 79 },
  { label: 'Entry 80', value: 80 },
  { label: 'Entry 81', value: 81 },
  { label: 'Entry 82', value: 82 },
  { label: 'Entry 83', value: 83 },
  { label: 'Entry 84', value: 84 },
  { label: 'Entry 85', value: 85 },
  { label: 'Entry 86', value: 86 },
  { label: 'Entry 87', value: 87 },
  { label: 'Entry 88', value: 88 },
  { label: 'Entry 89', value: 89 },
  { label: 'Entry 90', value: 90 },
  { label: 'Entry 91', value: 91 },
  { label: 'Entry 92', value: 92 },
  { label: 'Entry 93', value: 93 },
  { label: 'Entry 94', value: 94 },
  { label: 'Entry 95', value: 95 },
  { label: 'Entry 96', value: 96 },
  { label: 'Entry 97', value: 97 },
  { label: 'Entry 98', value: 98 },
  { label: 'Entry 99', value: 99 },
  { label: 'Entry 100', value: 100 },
  { label: 'Entry 101', value: 101 },
  { label: 'Entry 102', value: 102 },
  { label: 'Entry 103', value: 103 },
  { label: 'Entry 104', value: 104 },
  { label: 'Entry 105', value: 105 },
  { label: 'Entry 106', value: 106 },
];

export const ItemList = [
  { label: '- None', value: 0x00 },
  { label: '- Iron Sword', value: 0x01 },
  { label: '- Iron Blade', value: 0x02 },
  { label: '- Steel Sword', value: 0x03 },
  { label: '- Silver Sword', value: 0x04 },
  { label: '- Slim Sword', value: 0x05 },
  { label: '- Poison Sword', value: 0x06 },
  { label: '- Hero Sword', value: 0x07 },
  { label: '- Light Brand', value: 0x08 },
  { label: '- Durandal', value: 0x09 },
  { label: '- Armourslayer', value: 0x0A },
  { label: '- Rapier', value: 0x0B },
  { label: '- Killing Edge', value: 0x0C },
  { label: '- Lancereaver', value: 0x0D },
  { label: '- Wo Dao', value: 0x0E },
  { label: '- Sword of Seals', value: 0x0F },
  { label: '- Iron Lance', value: 0x10 },
  { label: '- Steel Lance', value: 0x11 },
  { label: '- Silver Lance', value: 0x12 },
  { label: '- Slim Lance', value: 0x13 },
  { label: '- Poison Lance', value: 0x14 },
  { label: '- Hero Lance', value: 0x15 },
  { label: '- Javelin', value: 0x16 },
  { label: '- Maltae', value: 0x17 },
  { label: '- Horseslayer', value: 0x18 },
  { label: '- Killer Lance', value: 0x19 },
  { label: '- Axereaver', value: 0x1A },
  { label: '- Iron Axe', value: 0x1B },
  { label: '- Steel Axe', value: 0x1C },
  { label: '- Silver Axe', value: 0x1D },
  { label: '- Poison Axe', value: 0x1E },
  { label: '- Hero Axe', value: 0x1F },
  { label: '- Hand Axe', value: 0x20 },
  { label: '- Armads', value: 0x21 },
  { label: '- Hammer', value: 0x22 },
  { label: '- Killer Axe', value: 0x23 },
  { label: '- Swordreaver', value: 0x24 },
  { label: '- Devil Axe', value: 0x25 },
  { label: '- Halberd', value: 0x26 },
  { label: '- Iron Bow', value: 0x27 },
  { label: '- Steel Bow', value: 0x28 },
  { label: '- Silver Bow', value: 0x29 },
  { label: '- Poison Bow', value: 0x2A },
  { label: '- Killer Bow', value: 0x2B },
  { label: '- Hero Bow', value: 0x2C },
  { label: '- Short Bow', value: 0x2D },
  { label: '- Longbow', value: 0x2E },
  { label: '- Miugre', value: 0x2F },
  { label: '- Ballista', value: 0x30 },
  { label: '- Iron Ballista', value: 0x31 },
  { label: '- Killer Ballista', value: 0x32 },
  { label: '- Fire', value: 0x33 },
  { label: '- Thunder', value: 0x34 },
  { label: '- Fimbulvetr', value: 0x35 },
  { label: '- Elfire', value: 0x36 },
  { label: '- Aircalibur', value: 0x37 },
  { label: '- Fenrir', value: 0x38 },
  { label: '- Bolting', value: 0x39 },
  { label: '- Forblaze', value: 0x3A },
  { label: '- Lightning', value: 0x3B },
  { label: '- Divine', value: 0x3C },
  { label: '- Purge', value: 0x3D },
  { label: '- Aureola', value: 0x3E },
  { label: '- Flux', value: 0x3F },
  { label: '- Nosferatu', value: 0x40 },
  { label: '- Eclipse', value: 0x41 },
  { label: '- Apocalypse', value: 0x42 },
  { label: '- Heal', value: 0x43 },
  { label: '- Mend', value: 0x44 },
  { label: '- Recover', value: 0x45 },
  { label: '- Physic', value: 0x46 },
  { label: '- Fortify', value: 0x47 },
  { label: '- Warp', value: 0x48 },
  { label: '- Rescue', value: 0x49 },
  { label: '- Restore', value: 0x4A },
  { label: '- Silence', value: 0x4B },
  { label: '- Sleep', value: 0x4C },
  { label: '- Torch', value: 0x4D },
  { label: '- Hammerne', value: 0x4E },
  { label: '- Watch', value: 0x4F },
  { label: '- Berserk', value: 0x50 },
  { label: '- Unlock', value: 0x51 },
  { label: '- Shield', value: 0x52 },
  { label: '- Fire Dragon Stone', value: 0x53 },
  { label: '- Divine Dragon Stone', value: 0x54 },
  { label: '- Magic Dragon Stone', value: 0x55 },
  { label: '- Secret Book', value: 0x56 },
  { label: '- Goddess Icon', value: 0x57 },
  { label: '- Angelic Robe', value: 0x58 },
  { label: '- Dragon Shield', value: 0x59 },
  { label: '- Energy Ring', value: 0x5A },
  { label: '- Speedwing', value: 0x5B },
  { label: '- Talisman', value: 0x5C },
  { label: '- Boots', value: 0x5D },
  { label: '- Body Ring', value: 0x5E },
  { label: '- Hero\'s Proof', value: 0x5F },
  { label: '- Knight\'s Proof', value: 0x60 },
  { label: '- Orion\'s Bolt', value: 0x61 },
  { label: '- Elysian Whip', value: 0x62 },
  { label: '- Guiding Ring', value: 0x63 },
  { label: '- Chest Key (5)', value: 0x64 },
  { label: '- Door Key', value: 0x65 },
  { label: '- Bridge Key', value: 0x66 },
  { label: '- Lockpick', value: 0x67 },
  { label: '- Vulnerary', value: 0x68 },
  { label: '- Elixir', value: 0x69 },
  { label: '- Holy Water', value: 0x6A },
  { label: '- Torch', value: 0x6B },
  { label: '- Antitoxin', value: 0x6C },
  { label: '- Member Card', value: 0x6D },
  { label: '- Silver Card', value: 0x6E },
  { label: '- Gold', value: 0x6F },
  { label: '- Dark Breath', value: 0x70 },
  { label: '- Exaccus', value: 0x71 },
  { label: '- Steel Blade', value: 0x72 },
  { label: '- Silver Blade', value: 0x73 },
  { label: '- Al\'s Sword', value: 0x74 },
  { label: '- Gant\'s Lance', value: 0x75 },
  { label: '- Tina\'s Staff', value: 0x76 },
  { label: '- Holy Maiden', value: 0x77 },
  { label: '- Wyrmslayer', value: 0x78 },
  { label: '- White Gem', value: 0x79 },
  { label: '- Blue Gem', value: 0x7A },
  { label: '- Red Gem', value: 0x7B },
  { label: '- Delphi Shield', value: 0x7C },
  { label: '- Runesword', value: 0x7D },
  { label: '- Spear', value: 0x7E },
  { label: '- Tomahawk', value: 0x7F },
];

export const SpellAnimations = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Throwing Axe', value: 0x01 },
  { label: 'Arrow', value: 0x02 },
  { label: 'Javelin', value: 0x03 },
  { label: 'Javelin #2', value: 0x04 },
  { label: 'Javelin #3', value: 0x05 },
  { label: 'Javelin #4', value: 0x06 },
  { label: 'Javelin #5', value: 0x07 },
  { label: 'Javelin #6', value: 0x08 },
  { label: 'Javelin #7', value: 0x09 },
  { label: 'Javelin #8', value: 0x0A },
  { label: 'Javelin #9', value: 0x0B },
  { label: 'Javelin #10', value: 0x0C },
  { label: 'Javelin #11', value: 0x0D },
  { label: 'Dance/Play', value: 0x0E },
  { label: 'Dance/Play', value: 0x0F },
  { label: 'Ballista Arrow', value: 0x10 },
  { label: 'Exaccus Wave', value: 0x11 },
  { label: 'Sword of Seals Fire', value: 0x12 },
  { label: 'Fire Dragon Stone', value: 0x13 },
  { label: 'Fa\'s Holy Dragon Stone', value: 0x14 },
  { label: 'Idoun\'s Dark Dragon Stone', value: 0x15 },
  { label: 'Fire', value: 0x16 },
  { label: 'Elfire', value: 0x17 },
  { label: 'Forblaze', value: 0x18 },
  { label: 'Thunder', value: 0x19 },
  { label: 'Bolting', value: 0x1A },
  { label: 'Fimbulvetr', value: 0x1B },
  { label: 'Aircalibur', value: 0x1C },
  { label: 'Flux', value: 0x1D },
  { label: 'Nosferatu', value: 0x1E },
  { label: 'Lightning', value: 0x1F },
  { label: 'Purge', value: 0x20 },
  { label: 'Aureola', value: 0x21 },
  { label: 'Divine', value: 0x22 },
  { label: 'Apocalypse', value: 0x23 },
  { label: 'Eclipse', value: 0x24 },
  { label: 'Fenrir', value: 0x25 },
  { label: 'Heal', value: 0x26 },
  { label: 'Mend', value: 0x27 },
  { label: 'Recover', value: 0x28 },
  { label: 'Physic', value: 0x29 },
  { label: 'Fortify (stalls battle screen)', value: 0x2A },
  { label: 'Holy Maiden (stalls battle screen)', value: 0x2B },
  { label: 'Restore', value: 0x2C },
  { label: 'Silence', value: 0x2D },
  { label: 'Sleep', value: 0x2E },
  { label: 'Hammerne', value: 0x2F },
  { label: 'Berserk', value: 0x30 },
  { label: 'Barrier', value: 0x31 },
  { label: '[[Reserved for Promo/Boost items]]', value: 0x32 },
  { label: 'Shine', value: 0x33 },
  { label: 'Luna', value: 0x34 },
  { label: 'Excalibur', value: 0x35 },
  { label: 'Gespenst', value: 0x36 },
  { label: 'Aura', value: 0x37 },
  { label: 'Luce', value: 0x38 },
  { label: 'Erishkigal', value: 0x39 },
  { label: 'Filla\'s Might', value: 0x3A },
  { label: 'Ninis\'s Grace', value: 0x3B },
  { label: 'Thor\'s Ire', value: 0x3C },
  { label: 'Set\'s Litany', value: 0x3D },
  { label: 'Map Only', value: 0xFFFE },
  { label: 'None', value: 0xFFFF },
];

export const Returning = [
  { label: 'Off', value: 0x00 },
  { label: 'On', value: 0x01 },
];

export const Facing = [
  { label: 'Towards target', value: 0x00 },
  { label: 'Always right', value: 0x01 },
  { label: 'Always up', value: 0x02 },
  { label: 'Always selected', value: 0x03 },
];

export const MapAnimationHitColor = [
  { label: 'White (normal)', value: 0x00 },
  { label: 'Black (dark)', value: 0x01 },
  { label: 'Red (fire)', value: 0x02 },
  { label: 'Green (wind)', value: 0x03 },
  { label: 'Blue (ice)', value: 0x04 },
  { label: 'Yellow (light)', value: 0x05 },
  { label: 'Pinkish (dummy)', value: 0x06 },
  { label: 'Dark purplish (dummy)', value: 0x07 },
];
