export const FE1VendorEditor3Entries = [
  { label: 'Entry 0', value: 0 },
];

export const Itemlist = [
  { label: '---', value: 0x00 },
  { label: 'Silver Sword', value: 0x01 },
  { label: 'Iron Sword', value: 0x02 },
  { label: 'Steel Sword', value: 0x03 },
  { label: 'Armorslayer', value: 0x04 },
  { label: 'Rapier', value: 0x05 },
  { label: 'Wyrmslayer', value: 0x06 },
  { label: 'Killing Edge', value: 0x07 },
  { label: 'Mercurius', value: 0x08 },
  { label: 'Levin Sword', value: 0x09 },
  { label: 'Devil Sword', value: 0x0A },
  { label: 'Falchion', value: 0x0B },
  { label: 'Iron Lance', value: 0x0C },
  { label: 'Ridersbane', value: 0x0D },
  { label: 'Silver Lance', value: 0x0E },
  { label: 'Javelin', value: 0x0F },
  { label: 'Gradivus', value: 0x10 },
  { label: 'Iron Bow', value: 0x11 },
  { label: 'Steel Bow', value: 0x12 },
  { label: 'Bowgun', value: 0x13 },
  { label: 'Silver Bow', value: 0x14 },
  { label: 'Parthia', value: 0x15 },
  { label: 'Quincrane', value: 0x16 },
  { label: 'Stonehedge', value: 0x17 },
  { label: 'Fire Gun', value: 0x18 },
  { label: 'Thunderbolt', value: 0x19 },
  { label: 'Elephant', value: 0x1A },
  { label: 'Iron Axe', value: 0x1B },
  { label: 'Steel Axe', value: 0x1C },
  { label: 'Hammer', value: 0x1D },
  { label: 'Devil Axe', value: 0x1E },
  { label: 'Hand Axe', value: 0x1F },
  { label: 'Wyvern*', value: 0x20 },
  { label: 'Gargoyle*', value: 0x21 },
  { label: 'Magicstone', value: 0x22 },
  { label: 'Divinestone', value: 0x23 },
  { label: 'Firestone', value: 0x24 },
  { label: 'Salamander*', value: 0x25 },
  { label: 'Earthstone', value: 0x26 },
  { label: 'Shenron*', value: 0x27 },
  { label: 'Neptune*', value: 0x28 },
  { label: 'Darkdragon*', value: 0x29 },
  { label: 'Magicstone?', value: 0x2A },
  { label: 'Fire', value: 0x2B },
  { label: 'Thunder', value: 0x2C },
  { label: 'Blizzard', value: 0x2D },
  { label: 'Elfire', value: 0x2E },
  { label: 'Bolganone', value: 0x2F },
  { label: 'Thoron', value: 0x30 },
  { label: 'Swarm', value: 0x31 },
  { label: 'Aura', value: 0x32 },
  { label: 'Excalibur', value: 0x33 },
  { label: 'Imhullu', value: 0x34 },
  { label: 'Starlight', value: 0x35 },
  { label: 'Heal', value: 0x36 },
  { label: 'Mend', value: 0x37 },
  { label: 'Recover', value: 0x38 },
  { label: 'Helarn*', value: 0x39 },
  { label: 'Warp', value: 0x3A },
  { label: 'Hammerne', value: 0x3B },
  { label: 'Physic', value: 0x3C },
  { label: 'Barrier', value: 0x3D },
  { label: 'Fortify', value: 0x3E },
  { label: 'Aum', value: 0x3F },
  { label: 'Vulnerary', value: 0x40 },
  { label: 'Pure Water', value: 0x41 },
  { label: 'Door Key', value: 0x42 },
  { label: 'Bridge Key', value: 0x43 },
  { label: 'Lockpick', value: 0x44 },
  { label: 'Unequipped', value: 0x45 },
  { label: 'Dragonshield', value: 0x46 },
  { label: 'Talisman', value: 0x47 },
  { label: 'Boots', value: 0x48 },
  { label: 'Manual', value: 0x49 },
  { label: 'Secret Book', value: 0x4A },
  { label: 'Power Ring', value: 0x4B },
  { label: 'Telescope*', value: 0x4C },
  { label: 'Speed Ring', value: 0x4D },
  { label: 'Goddess Icon', value: 0x4E },
  { label: 'Angelic Robe', value: 0x4F },
  { label: 'Knight Crest', value: 0x50 },
  { label: 'Hero Crest', value: 0x51 },
  { label: 'Guiding Ring', value: 0x52 },
  { label: 'Orion\'s Bolt', value: 0x53 },
  { label: 'Elysian Whip', value: 0x54 },
  { label: 'Geosphere', value: 0x55 },
  { label: 'Time Orb*', value: 0x56 },
  { label: 'Dark Orb*', value: 0x57 },
  { label: 'Starsphere', value: 0x58 },
  { label: 'Member Card', value: 0x59 },
  { label: 'Silver Card', value: 0x5A },
  { label: 'Lightsphere', value: 0x5B },
  { label: 'Fire Emblem', value: 0x5C },
];
