export const Characterlist = [
  { label: 'Alm', value: 0 },
  { label: 'Cellica', value: 1 },
  { label: 'Maisen', value: 2 },
  { label: 'Norma', value: 3 },
  { label: 'Ruka', value: 4 },
  { label: 'Cliff', value: 5 },
  { label: 'Robin', value: 6 },
  { label: 'Grey', value: 7 },
  { label: 'Clea', value: 8 },
  { label: 'Clerbe', value: 9 },
  { label: 'Clerbe', value: 10 },
  { label: 'Fols', value: 11 },
  { label: 'May', value: 12 },
  { label: 'Silk', value: 13 },
  { label: 'Jenny', value: 14 },
  { label: 'Bowy', value: 15 },
  { label: 'Kamui', value: 16 },
  { label: 'Valbo', value: 17 },
  { label: 'Matilda', value: 18 },
  { label: 'Paison', value: 19 },
  { label: 'Leo', value: 20 },
  { label: 'Atlas', value: 21 },
  { label: 'Jesey', value: 22 },
  { label: 'Fols (Alm\'s portrait)', value: 23 },
  { label: 'Sonia', value: 24 },
  { label: 'Dean', value: 25 },
  { label: 'Savor', value: 26 },
  { label: 'Ryuto', value: 27 },
  { label: 'Dyute', value: 28 },
  { label: 'Teeta', value: 29 },
  { label: 'Katua', value: 30 },
  { label: 'Paola', value: 31 },
  { label: 'Est', value: 32 },
  { label: 'Zeke', value: 33 },
];

export default Characterlist;
