export const FE11Chapter20UnitEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
];

export const Characters = [
  { label: 'Marth', value: 0x00 },
  { label: 'Caeda', value: 0x01 },
  { label: 'Jagan', value: 0x02 },
  { label: 'Cain', value: 0x03 },
  { label: 'Abel', value: 0x04 },
  { label: 'Draug', value: 0x05 },
  { label: 'Gordin', value: 0x06 },
  { label: 'Wrys', value: 0x07 },
  { label: 'Ogma', value: 0x08 },
  { label: 'Barst', value: 0x09 },
  { label: 'Bord', value: 0x0A },
  { label: 'Cord', value: 0x0B },
  { label: 'Castor', value: 0x0C },
  { label: 'Darros', value: 0x0D },
  { label: 'Julian', value: 0x0E },
  { label: 'Lena', value: 0x0F },
  { label: 'Nabarl', value: 0x10 },
  { label: 'Merric', value: 0x11 },
  { label: 'Matthis', value: 0x12 },
  { label: 'Hardin', value: 0x13 },
  { label: 'Wolf', value: 0x14 },
  { label: 'Sedgar', value: 0x15 },
  { label: 'Roshea', value: 0x16 },
  { label: 'Vyland', value: 0x17 },
  { label: 'Wendell', value: 0x18 },
  { label: 'Rikard', value: 0x19 },
  { label: 'Bantu', value: 0x1A },
  { label: 'Caesar', value: 0x1B },
  { label: 'Radd', value: 0x1C },
  { label: 'Roger', value: 0x1D },
  { label: 'Jeorge', value: 0x1E },
  { label: 'Maria', value: 0x1F },
  { label: 'Minerva', value: 0x20 },
  { label: 'Linde', value: 0x21 },
  { label: 'Jake', value: 0x22 },
  { label: 'Midia', value: 0x23 },
  { label: 'Dolph', value: 0x24 },
  { label: 'Macellan', value: 0x25 },
  { label: 'Tomas', value: 0x26 },
  { label: 'Boah', value: 0x27 },
  { label: 'Beck', value: 0x28 },
  { label: 'Astram', value: 0x29 },
  { label: 'Palla', value: 0x2A },
  { label: 'Catria', value: 0x2B },
  { label: 'Arran', value: 0x2C },
  { label: 'Samson', value: 0x2D },
  { label: 'Xane', value: 0x2E },
  { label: 'Est', value: 0x2F },
  { label: 'Tiki', value: 0x30 },
  { label: 'Lorenz', value: 0x31 },
  { label: 'Elice', value: 0x32 },
  { label: 'Gotoh', value: 0x33 },
  { label: 'Frey', value: 0x34 },
  { label: 'Nornw', value: 0x35 },
  { label: 'Athena', value: 0x36 },
  { label: 'Horace', value: 0x37 },
  { label: 'Etzel', value: 0x38 },
  { label: 'Nagi', value: 0x39 },
  { label: 'Ymir', value: 0x3A },
  { label: 'Dummy', value: 0x3B },
  { label: 'No Name', value: 0x3C },
  { label: 'No Name', value: 0x3D },
  { label: 'No Name', value: 0x3E },
  { label: 'No Name', value: 0x3F },
  { label: 'No Name', value: 0x40 },
  { label: 'No Name', value: 0x41 },
  { label: 'No Name', value: 0x42 },
  { label: 'No Name', value: 0x43 },
  { label: 'No Name', value: 0x44 },
  { label: 'No Name', value: 0x45 },
  { label: 'No Name', value: 0x46 },
  { label: 'No Name', value: 0x47 },
  { label: 'No Name', value: 0x48 },
  { label: 'No Name', value: 0x49 },
  { label: 'No Name', value: 0x4A },
  { label: 'No Name', value: 0x4B },
  { label: 'No Name', value: 0x4C },
  { label: 'No Name', value: 0x4D },
  { label: 'Gazzak', value: 0x4E },
  { label: 'Gomer', value: 0x4F },
  { label: 'Hyman', value: 0x50 },
  { label: 'Bentheon', value: 0x51 },
  { label: 'Merach', value: 0x52 },
  { label: 'Emereus', value: 0x53 },
  { label: 'Harmein', value: 0x54 },
  { label: 'Kannival', value: 0x55 },
  { label: 'Mannu', value: 0x56 },
  { label: 'Zharov', value: 0x57 },
  { label: 'Khozen', value: 0x58 },
  { label: 'Volzhin', value: 0x59 },
  { label: 'Heimler', value: 0x5A },
  { label: 'Grigas', value: 0x5B },
  { label: 'Jiol', value: 0x5C },
  { label: 'Gharnef', value: 0x5D },
  { label: 'Gharnef 2', value: 0x5E },
  { label: 'Hollstadt', value: 0x5F },
  { label: 'Morzas', value: 0x60 },
  { label: 'Sternlin', value: 0x61 },
  { label: 'Camus', value: 0x62 },
  { label: 'Orridyon', value: 0x63 },
  { label: 'Michalis', value: 0x64 },
  { label: 'Xemcel', value: 0x65 },
  { label: 'Medeus', value: 0x66 },
  { label: 'Galder', value: 0x67 },
  { label: 'Galder', value: 0x68 },
  { label: 'Galder', value: 0x69 },
  { label: 'Galder', value: 0x6A },
  { label: 'Galder', value: 0x6B },
  { label: 'Galder', value: 0x6C },
  { label: 'Grust', value: 0x6D },
  { label: 'Soothsire', value: 0x6E },
  { label: 'Soothsire', value: 0x6F },
  { label: 'Soothsire', value: 0x70 },
  { label: 'Macedon', value: 0x71 },
  { label: 'Macedon', value: 0x72 },
  { label: 'Macedon', value: 0x73 },
  { label: 'Macedon', value: 0x74 },
  { label: 'Macedon', value: 0x75 },
  { label: 'Macedon', value: 0x76 },
  { label: 'Macedon', value: 0x77 },
  { label: 'Macedon', value: 0x78 },
  { label: 'Macedon', value: 0x79 },
  { label: 'Macedon', value: 0x7A },
  { label: 'Macedon', value: 0x7B },
  { label: 'Macedon', value: 0x7C },
  { label: 'Macedon', value: 0x7D },
  { label: 'Macedon', value: 0x7E },
  { label: 'Macedon', value: 0x7F },
  { label: 'Macedon', value: 0x80 },
  { label: 'Macedon', value: 0x81 },
  { label: 'Macedon', value: 0x82 },
  { label: 'Macedon', value: 0x83 },
  { label: 'Macedon', value: 0x84 },
  { label: 'Grust', value: 0x85 },
  { label: 'Dragoon', value: 0x86 },
  { label: 'Dragoon', value: 0x87 },
  { label: 'Grust', value: 0x88 },
  { label: 'Grust', value: 0x89 },
  { label: 'Grust', value: 0x8A },
  { label: 'Grust', value: 0x8B },
  { label: 'Grust', value: 0x8C },
  { label: 'Grust', value: 0x8D },
  { label: 'Grust', value: 0x8E },
  { label: 'Grust', value: 0x8F },
  { label: 'Grust', value: 0x90 },
  { label: 'Pyrathi', value: 0x91 },
  { label: 'Pyrathi', value: 0x92 },
  { label: 'Pyrathi', value: 0x93 },
  { label: 'Pyrathi', value: 0x94 },
  { label: 'Pyrathi', value: 0x95 },
  { label: 'Grust', value: 0x96 },
  { label: 'Grust', value: 0x97 },
  { label: 'Grust', value: 0x98 },
  { label: 'Grust', value: 0x99 },
  { label: 'Grust', value: 0x9A },
  { label: 'Grust', value: 0x9B },
  { label: 'Grust', value: 0x9C },
  { label: 'Grust', value: 0x9D },
  { label: 'Grust', value: 0x9E },
  { label: 'Grust', value: 0x9F },
  { label: 'Grust', value: 0xA0 },
  { label: 'Grust', value: 0xA1 },
  { label: 'Grust', value: 0xA2 },
  { label: 'Grust', value: 0xA3 },
  { label: 'Grust', value: 0xA4 },
  { label: 'Grust', value: 0xA5 },
  { label: 'Ruffian', value: 0xA6 },
  { label: 'Grust', value: 0xA7 },
  { label: 'Grust', value: 0xA8 },
  { label: 'Grust', value: 0xA9 },
  { label: 'Grust', value: 0xAA },
  { label: 'Grust', value: 0xAB },
  { label: 'Grust', value: 0xAC },
  { label: 'Grust', value: 0xAD },
  { label: 'Grust', value: 0xAE },
  { label: 'Grust', value: 0xAF },
  { label: 'Grust', value: 0xB0 },
  { label: 'Grust', value: 0xB1 },
  { label: 'Grust', value: 0xB2 },
  { label: 'Dragoon', value: 0xB3 },
  { label: 'Gra', value: 0xB4 },
  { label: 'Gra', value: 0xB5 },
  { label: 'Gra', value: 0xB6 },
  { label: 'Gra', value: 0xB7 },
  { label: 'Gra', value: 0xB8 },
  { label: 'Gra', value: 0xB9 },
  { label: 'Dragoon', value: 0xBA },
  { label: 'Khadein', value: 0xBB },
  { label: 'Khadein', value: 0xBC },
  { label: 'Khadein', value: 0xBD },
  { label: 'Khadein', value: 0xBE },
  { label: 'Grust', value: 0xBF },
  { label: 'Grust', value: 0xC0 },
  { label: 'Grust', value: 0xC1 },
  { label: 'Grust', value: 0xC2 },
  { label: 'Grust', value: 0xC3 },
  { label: 'Grust', value: 0xC4 },
  { label: 'Grust', value: 0xC5 },
  { label: 'Grust', value: 0xC6 },
  { label: 'Grust', value: 0xC7 },
  { label: 'Dolhr', value: 0xC8 },
  { label: 'Dolhr', value: 0xC9 },
  { label: 'Dolhr', value: 0xCA },
  { label: 'Dolhr', value: 0xCB },
  { label: 'Dolhr', value: 0xCC },
  { label: 'Dolhr', value: 0xCD },
  { label: 'Dolhr', value: 0xCE },
  { label: 'Dolhr', value: 0xCF },
  { label: 'Dolhr', value: 0xD0 },
  { label: 'Dolhr', value: 0xD1 },
  { label: 'Sable', value: 0xD2 },
  { label: 'Sable', value: 0xD3 },
  { label: 'Sable', value: 0xD4 },
  { label: 'Sable', value: 0xD5 },
  { label: 'Raman', value: 0xD6 },
  { label: 'Raman', value: 0xD7 },
  { label: 'Raman', value: 0xD8 },
  { label: 'Raman', value: 0xD9 },
  { label: 'Raman', value: 0xDA },
  { label: 'Raman', value: 0xDB },
  { label: 'Raman', value: 0xDC },
  { label: 'Sable', value: 0xDD },
  { label: 'Sable', value: 0xDE },
  { label: 'Sable', value: 0xDF },
  { label: 'Sable', value: 0xE0 },
  { label: 'Sable', value: 0xE1 },
  { label: 'Sable', value: 0xE2 },
  { label: 'Sable', value: 0xE3 },
  { label: 'Grust', value: 0xE4 },
  { label: 'Grust', value: 0xE5 },
  { label: 'Grust', value: 0xE6 },
  { label: 'Grust', value: 0xE7 },
  { label: 'Dragoon', value: 0xE8 },
  { label: 'Dragoon', value: 0xE9 },
  { label: 'Dragoon', value: 0xEA },
  { label: 'Dragoon', value: 0xEB },
  { label: 'Dragoon', value: 0xEC },
  { label: 'Dragoon', value: 0xED },
  { label: 'Dragoon', value: 0xEE },
  { label: 'Dragoon', value: 0xEF },
  { label: 'Dragoon', value: 0xF0 },
  { label: 'Dragoon', value: 0xF1 },
  { label: 'Dragoon', value: 0xF2 },
  { label: 'Dragoon', value: 0xF3 },
  { label: 'Dragoon', value: 0xF4 },
  { label: 'Dragoon', value: 0xF5 },
  { label: 'Dragoon', value: 0xF6 },
  { label: 'Dolhr', value: 0xF7 },
  { label: 'Dolhr', value: 0xF8 },
  { label: 'Dolhr', value: 0xF9 },
  { label: 'Khadein', value: 0xFA },
  { label: 'Khadein', value: 0xFB },
  { label: 'Khadein', value: 0xFC },
  { label: 'Dolhr', value: 0xFD },
  { label: 'Dolhr', value: 0xFE },
  { label: 'Dolhr', value: 0xFF },
  { label: 'Dolhr', value: 0x100 },
  { label: 'Dolhr', value: 0x101 },
  { label: 'Dolhr', value: 0x102 },
  { label: 'Dolhr', value: 0x103 },
  { label: 'Dolhr', value: 0x104 },
  { label: 'Dolhr', value: 0x105 },
  { label: 'Dolhr', value: 0x106 },
  { label: 'Dolhr', value: 0x107 },
  { label: 'Dolhr', value: 0x108 },
  { label: 'Dolhr', value: 0x109 },
  { label: 'Dolhr', value: 0x10A },
  { label: 'Dolhr', value: 0x10B },
  { label: 'Dolhr', value: 0x10C },
  { label: 'Dolhr', value: 0x10D },
  { label: 'Opponent', value: 0x10E },
  { label: 'Opponent', value: 0x10F },
  { label: 'Opponent', value: 0x110 },
  { label: 'Opponent', value: 0x111 },
  { label: 'Opponent', value: 0x112 },
  { label: 'Opponent', value: 0x113 },
  { label: 'Opponent', value: 0x114 },
  { label: 'Opponent', value: 0x115 },
  { label: 'Opponent', value: 0x116 },
  { label: 'Opponent', value: 0x117 },
  { label: 'Opponent', value: 0x118 },
  { label: 'Opponent', value: 0x119 },
  { label: 'Opponent', value: 0x11A },
  { label: 'Opponent', value: 0x11B },
  { label: 'Opponent', value: 0x11C },
  { label: 'Opponent', value: 0x11D },
  { label: 'Opponent', value: 0x11E },
  { label: 'Opponent', value: 0x11F },
  { label: 'Opponent', value: 0x120 },
  { label: 'Opponent', value: 0x121 },
  { label: 'Opponent', value: 0x122 },
  { label: 'Opponent', value: 0x123 },
  { label: 'Opponent', value: 0x124 },
  { label: 'Gra', value: 0x125 },
  { label: 'Gra', value: 0x126 },
  { label: 'Gra', value: 0x127 },
  { label: 'Gra', value: 0x128 },
  { label: 'Nyna', value: 0x129 },
  { label: 'Malledus', value: 0x12A },
  { label: 'Soldier', value: 0x12B },
  { label: 'Bathys', value: 0x12C },
  { label: 'Dejanira', value: 0x12D },
  { label: 'Dactyl', value: 0x12E },
  { label: 'Larissa', value: 0x12F },
  { label: 'Soldier', value: 0x130 },
  { label: 'Soldier', value: 0x131 },
  { label: 'Soldier', value: 0x132 },
  { label: 'Soldier', value: 0x133 },
  { label: 'Soldier', value: 0x134 },
  { label: 'Soldier', value: 0x135 },
  { label: 'Captain', value: 0x136 },
  { label: 'Gra', value: 0x137 },
  { label: 'Gra', value: 0x138 },
  { label: 'Gra', value: 0x139 },
  { label: 'Gra', value: 0x13A },
  { label: 'Gra', value: 0x13B },
  { label: 'Gra', value: 0x13C },
  { label: 'Gra', value: 0x13D },
  { label: 'Gra', value: 0x13E },
  { label: 'Gra', value: 0x13F },
  { label: 'Gra', value: 0x140 },
  { label: 'Gra', value: 0x141 },
  { label: 'Gra', value: 0x142 },
  { label: 'Gra', value: 0x143 },
  { label: 'Ruffian', value: 0x144 },
  { label: 'Ruffian', value: 0x145 },
  { label: 'Ruffian', value: 0x146 },
  { label: 'Ruffian', value: 0x147 },
  { label: 'Grust', value: 0x148 },
  { label: 'Grust', value: 0x149 },
  { label: 'Archanea', value: 0x14A },
  { label: 'Archanea', value: 0x14B },
  { label: 'Grust', value: 0x14C },
  { label: 'Grust', value: 0x14D },
  { label: 'Grust', value: 0x14E },
  { label: 'Grust', value: 0x14F },
  { label: 'Ruffian', value: 0x150 },
  { label: 'Dolhr', value: 0x151 },
  { label: 'Grust', value: 0x152 },
  { label: 'Grust', value: 0x153 },
  { label: 'Grust', value: 0x154 },
  { label: 'Grust', value: 0x155 },
  { label: 'Grust', value: 0x156 },
  { label: 'Grust', value: 0x157 },
  { label: 'Grust', value: 0x158 },
  { label: 'Grust', value: 0x159 },
  { label: 'Grust', value: 0x15A },
  { label: 'Grust', value: 0x15B },
  { label: 'Grust', value: 0x15C },
  { label: 'Grust', value: 0x15D },
  { label: 'Dolhr', value: 0x15E },
  { label: 'Grust', value: 0x15F },
  { label: 'Grust', value: 0x160 },
  { label: 'Grust', value: 0x161 },
  { label: 'Grust', value: 0x162 },
  { label: 'Keeper', value: 0x163 },
  { label: 'Keeper', value: 0x164 },
  { label: 'Keeper', value: 0x165 },
  { label: 'Keeper', value: 0x166 },
  { label: 'Keeper', value: 0x167 },
  { label: 'Keeper', value: 0x168 },
  { label: 'Keeper', value: 0x169 },
  { label: 'Keeper', value: 0x16A },
  { label: 'Marth', value: 0x16B },
  { label: 'Gra', value: 0x16C },
  { label: 'Gra', value: 0x16D },
  { label: 'Gra', value: 0x16E },
  { label: 'Gra', value: 0x16F },
  { label: 'Gra', value: 0x170 },
  { label: 'Gra', value: 0x171 },
  { label: 'Gra', value: 0x172 },
  { label: 'Gra', value: 0x173 },
  { label: 'Dragoon', value: 0x174 },
  { label: 'Dragoon', value: 0x175 },
];

export const Classes = [
  { label: 'Lord (Marth)', value: 0x00 },
  { label: 'Pegasus Knight', value: 0x01 },
  { label: 'Pegasus Knight (Caeda)', value: 0x02 },
  { label: 'Falcon Knight', value: 0x03 },
  { label: 'Dracoknight', value: 0x04 },
  { label: 'Dracoknight (F)', value: 0x05 },
  { label: 'Cavalier', value: 0x06 },
  { label: 'Cavalier (F)', value: 0x07 },
  { label: 'Paladin', value: 0x08 },
  { label: 'Paladin (F)', value: 0x09 },
  { label: 'Knight', value: 0x0A },
  { label: 'General', value: 0x0B },
  { label: 'Archer', value: 0x0C },
  { label: 'Archer (F)', value: 0x0D },
  { label: 'Sniper', value: 0x0E },
  { label: 'Sniper (F)', value: 0x0F },
  { label: 'Mercenary', value: 0x10 },
  { label: 'Hero', value: 0x11 },
  { label: 'Myrmidon', value: 0x12 },
  { label: 'Myrmidon (F)', value: 0x13 },
  { label: 'Swordmaster', value: 0x14 },
  { label: 'Swordmaster (F)', value: 0x15 },
  { label: 'Fighter', value: 0x16 },
  { label: 'Warrior', value: 0x17 },
  { label: 'Hunter', value: 0x18 },
  { label: 'Horsemen', value: 0x19 },
  { label: 'Pirate', value: 0x1A },
  { label: 'Berserker', value: 0x1B },
  { label: 'Dark Mage', value: 0x1C },
  { label: 'Sorcerer', value: 0x1D },
  { label: 'Mage', value: 0x1E },
  { label: 'Mage (F)', value: 0x1F },
  { label: 'Curate', value: 0x20 },
  { label: 'Cleric', value: 0x21 },
  { label: 'Sage', value: 0x22 },
  { label: 'Sage (F)', value: 0x23 },
  { label: 'Bishop', value: 0x24 },
  { label: 'Bishop (F)', value: 0x25 },
  { label: 'Thief', value: 0x26 },
  { label: 'Manakete', value: 0x27 },
  { label: 'Manakete (F)', value: 0x28 },
  { label: 'Ballistician', value: 0x29 },
  { label: 'Chameleon', value: 0x2A },
  { label: 'Soldier', value: 0x2B },
  { label: 'Magic Dragon', value: 0x2C },
  { label: 'Earth Dragon', value: 0x2D },
  { label: 'Fire Dragon', value: 0x2E },
  { label: 'Divine Dragon', value: 0x2F },
  { label: 'Dismounted Knight', value: 0x30 },
  { label: 'Dismounted Knight (F)', value: 0x31 },
  { label: 'Empty (?)', value: 0x32 },
];

export const Enemy1 = [
  { label: '- Ally', value: 0x00 },
  { label: '- Enemy', value: 0x01 },
];

export const Enemy2 = [
  { label: '- --', value: 0x00 },
  { label: '- Ally', value: 0x01 },
  { label: '- Ally?', value: 0x03 },
  { label: '- Enemy?', value: 0x08 },
  { label: '- Enemy', value: 0x0E },
];

export const Items = [
  { label: 'None', value: 0x00 },
  { label: 'Iron Sword', value: 0x01 },
  { label: 'Steel Sword', value: 0x02 },
  { label: 'Silver Sword', value: 0x03 },
  { label: 'Killing Edge', value: 0x04 },
  { label: 'Levin Sword', value: 0x05 },
  { label: 'Devil Sword', value: 0x06 },
  { label: 'Wyrmslayer', value: 0x07 },
  { label: 'Armorslayer', value: 0x08 },
  { label: 'Mercurius', value: 0x09 },
  { label: 'Rapier', value: 0x0A },
  { label: 'Wo Dao', value: 0x0B },
  { label: 'Brave Sword', value: 0x0C },
  { label: 'Falchion (Fake)', value: 0x0D },
  { label: 'Falchion (Weak)', value: 0x0E },
  { label: 'Falchion', value: 0x0F },
  { label: 'Iron Lance', value: 0x10 },
  { label: 'Steel Lance', value: 0x11 },
  { label: 'Silver Lance', value: 0x12 },
  { label: 'Javelin', value: 0x13 },
  { label: 'Killer Lance', value: 0x14 },
  { label: 'Ridersbane', value: 0x15 },
  { label: 'Wing Spear', value: 0x16 },
  { label: 'Dragonpike', value: 0x17 },
  { label: 'Brave Lance', value: 0x18 },
  { label: 'Gradivus', value: 0x19 },
  { label: 'Iron Axe', value: 0x1A },
  { label: 'Steel Axe', value: 0x1B },
  { label: 'Silver Axe', value: 0x1C },
  { label: 'Hand Axe', value: 0x1D },
  { label: 'Killer Axe', value: 0x1E },
  { label: 'Hammer', value: 0x1F },
  { label: 'Poleax', value: 0x20 },
  { label: 'Devil Axe', value: 0x21 },
  { label: 'Brave Axe', value: 0x22 },
  { label: 'Hauteclere', value: 0x23 },
  { label: 'Iron Bow', value: 0x24 },
  { label: 'Steel Bow', value: 0x25 },
  { label: 'Silver Bow', value: 0x26 },
  { label: 'Killer Bow', value: 0x27 },
  { label: 'Longbow', value: 0x28 },
  { label: 'Brave Bow', value: 0x29 },
  { label: 'Parthia', value: 0x2A },
  { label: 'Arrowspate', value: 0x2B },
  { label: 'Stonehoist', value: 0x2C },
  { label: 'Hoistflamme', value: 0x2D },
  { label: 'Thunderbolt', value: 0x2E },
  { label: 'Pachyderm', value: 0x2F },
  { label: 'Firestone', value: 0x30 },
  { label: 'Earthstone', value: 0x31 },
  { label: 'Magestone', value: 0x32 },
  { label: 'Divinestone', value: 0x33 },
  { label: 'Fire', value: 0x34 },
  { label: 'Thunder', value: 0x35 },
  { label: 'Blizzard', value: 0x36 },
  { label: 'Elfire', value: 0x37 },
  { label: 'Imhullu (False)', value: 0x38 },
  { label: 'Bolganone', value: 0x39 },
  { label: 'Thoron', value: 0x3A },
  { label: 'Swarm', value: 0x3B },
  { label: 'Aura', value: 0x3C },
  { label: 'Excalibur', value: 0x3D },
  { label: 'Imhullu', value: 0x3E },
  { label: 'Starlight', value: 0x3F },
  { label: 'Heal', value: 0x40 },
  { label: 'Mend', value: 0x41 },
  { label: 'Recover', value: 0x42 },
  { label: 'Physic', value: 0x43 },
  { label: 'Fortify', value: 0x44 },
  { label: 'Warp', value: 0x45 },
  { label: 'Barrier', value: 0x46 },
  { label: 'Hammerne', value: 0x47 },
  { label: 'Aum', value: 0x48 },
  { label: 'Door Key', value: 0x49 },
  { label: 'Bridge Key', value: 0x4A },
  { label: 'Master Key', value: 0x4B },
  { label: 'Vulnerary', value: 0x4C },
  { label: 'Pure Water', value: 0x4D },
  { label: 'Energy Drop', value: 0x4E },
  { label: 'Spirit Dust', value: 0x4F },
  { label: 'Secret Book', value: 0x50 },
  { label: 'Speedwings', value: 0x51 },
  { label: 'Goddess Icon', value: 0x52 },
  { label: 'Dracoshield', value: 0x53 },
  { label: 'Talisman', value: 0x54 },
  { label: 'Seraph Robe', value: 0x55 },
  { label: 'Boots', value: 0x56 },
  { label: 'Arms Scroll', value: 0x57 },
  { label: 'Silver Card', value: 0x58 },
  { label: 'VIP Card', value: 0x59 },
  { label: 'Master Seal', value: 0x5A },
  { label: 'Elysian Whip', value: 0x5B },
  { label: 'Torch', value: 0x5C },
  { label: 'Iote\'s Shield', value: 0x5D },
  { label: 'Lightsphere', value: 0x5E },
  { label: 'Starsphere', value: 0x5F },
  { label: 'Geosphere', value: 0x60 },
  { label: 'Fire Emblem', value: 0x61 },
  { label: 'Door Key', value: 0x62 },
  { label: 'Bullion (S)', value: 0x63 },
  { label: 'Bullion (M)', value: 0x64 },
  { label: 'Bullion (L)', value: 0x65 },
  { label: 'Bullion (XL)', value: 0x66 },
];

export const Droppable = [
  { label: '- --', value: 0x00 },
  { label: '- Item Dropped when Defeated', value: 0x01 },
];
