export const FE4ShopEditorChapter6Entries = [
  { label: 'Entry 0', value: 0 },
];

export const FE4PlayerEquipment = [
  { label: '(Alec/Ch.6 Shop)', value: 0x01 },
  { label: '(Iron Sword)', value: 0x02 },
  { label: '(Arden/Ch.6 Shop)', value: 0x03 },
  { label: '(Dew/Ch.6 Shop)', value: 0x04 },
  { label: '(Delmud/Ch.7 Shop)', value: 0x05 },
  { label: '(Nanna/Ch. 8 Shop)', value: 0x06 },
  { label: '(Sigurd/Ch.7 Shop)', value: 0x07 },
  { label: '(Beowulf/Ch. 8 Shop)', value: 0x08 },
  { label: '(Noish/Ch. 9 Shop)', value: 0x09 },
  { label: '(Alvis>Sigurd/Ch.6 Shop)', value: 0x0A },
  { label: '(Ch.3 Shop/Ch. 9 Shop)', value: 0x0B },
  { label: '(Holyn/Ch.6 Shop)', value: 0x0C },
  { label: '(Ayra/Ch. 10 Shop)', value: 0x0D },
  { label: '(Skasaher/Ch.7 Shop)', value: 0x0E },
  { label: '(Lakche)', value: 0x0F },
  { label: '(Ch.2 Shop/Ch.7 Shop)', value: 0x10 },
  { label: '(Shanan)', value: 0x11 },
  { label: '(Steel Blade)', value: 0x12 },
  { label: '(*Shagall/*Blume)', value: 0x13 },
  { label: '(Hannibal)', value: 0x14 },
  { label: '(Lachesis/Commander)', value: 0x15 },
  { label: '(Dew>Lachesis/*Danan)', value: 0x16 },
  { label: '(Barrier Sword)', value: 0x17 },
  { label: '(Fee)', value: 0x18 },
  { label: '(Ayra Hero Sword/*Coruta)', value: 0x19 },
  { label: '(Patty Hero Sword)', value: 0x1A },
  { label: '(Patty)', value: 0x1B },
  { label: '(Ethlin/Ch. 8 Shop)', value: 0x1C },
  { label: '(Ch.1 Shop/Ch.7 Shop)', value: 0x1D },
  { label: '(Sylvia/Ch. 9 Shop)', value: 0x1E },
  { label: '(Celice/Ch.7 Shop)', value: 0x1F },
  { label: '(Defence Sword)', value: 0x20 },
  { label: '(Fire Sword/Ch.7 Shop)', value: 0x21 },
  { label: '(Eltoshan>Lachesis/Ch. 9 Shop)', value: 0x22 },
  { label: '(*Shacoban/Ch. 8 Shop)', value: 0x23 },
  { label: '(Wind Sword/Ch. 10 Shop)', value: 0x24 },
  { label: '(Light Sword/Ch.6 Shop)', value: 0x25 },
  { label: '(Mistoltin)', value: 0x26 },
  { label: '(Tyrfing)', value: 0x27 },
  { label: '(Balmunk)', value: 0x28 },
  { label: '(Armor Killer/Ch. 8 Shop)', value: 0x29 },
  { label: '(Oifaye)', value: 0x2A },
  { label: '(Wing Clipper/Ch. 9 Shop)', value: 0x2B },
  { label: '(Hannibal)', value: 0x2C },
  { label: '(Sigurd/Ch.7 Shop)', value: 0x2D },
  { label: '(Fin/Ch.7 Shop)', value: 0x2E },
  { label: '(Ch.1 Shop/Ch.7 Shop)', value: 0x2F },
  { label: '(Fin-Older/Ch. 8 Shop)', value: 0x30 },
  { label: '(Aless)', value: 0x31 },
  { label: '(Cuan/Ch. 8 Shop)', value: 0x32 },
  { label: '(Ch.2 Shop/Ch. 8 Shop)', value: 0x33 },
  { label: '(Steel Lance/Ch. 8 Shop)', value: 0x34 },
  { label: '(*Elliot/Ch. 9 Shop)', value: 0x35 },
  { label: '(Ch.3 Shop/Ch. 9 Shop)', value: 0x36 },
  { label: '(Cuan/Ch. 9 Shop)', value: 0x37 },
  { label: '(Ch.1 Shop/Ch. 9 Shop)', value: 0x38 },
  { label: '(Oifaye)', value: 0x39 },
  { label: '(*Zain/Bramsel)', value: 0x3A },
  { label: '(Hero Lance/*Muhammed)', value: 0x3B },
  { label: '(Fury/Ch.7 Shop)', value: 0x3C },
  { label: '(Fee/Ch.7 Shop)', value: 0x3D },
  { label: '(Gae Bolg)', value: 0x3E },
  { label: '(Lex\'s Iron Axe/Ch.7 Shop)', value: 0x3F },
  { label: '(Iron Axe)', value: 0x40 },
  { label: '(Ch.1 Shop/Ch.7 Shop)', value: 0x41 },
  { label: '(Johan)', value: 0x42 },
  { label: '(Johalver)', value: 0x43 },
  { label: '(Ch.3 Shop/Ch. 8 Shop)', value: 0x44 },
  { label: '(Hero Axe/*Shumit)', value: 0x45 },
  { label: '(*Kinbois/Ch.7 Shop)', value: 0x46 },
  { label: '(Mideel/Ch. 8 Shop)', value: 0x47 },
  { label: '(Lester/Ch. 8 Shop)', value: 0x48 },
  { label: '(Briggid/Ch.7 Shop)', value: 0x49 },
  { label: '(Ch.2 Shop/Ch. 8 Shop)', value: 0x4A },
  { label: '(Ch.3 Shop/Ch. 9 Shop)', value: 0x4B },
  { label: '(Faval)', value: 0x4C },
  { label: '(Hero Bow/*Commander)', value: 0x4D },
  { label: '(Jamuka/*Maikov)', value: 0x4E },
  { label: '(Ichival)', value: 0x4F },
  { label: '(Azel/Ch. 8 Shop)', value: 0x50 },
  { label: '(Fire/Ch.7 Shop)', value: 0x51 },
  { label: '(Ch.3 Shop/Ch. 9 Shop)', value: 0x52 },
  { label: '(*Hilda)', value: 0x53 },
  { label: '(Tiltyu/Ch.7 Shop)', value: 0x54 },
  { label: '(Ch.2 Shop/Ch. 8 Shop)', value: 0x55 },
  { label: '(Tinny)', value: 0x56 },
  { label: '(Tiltyu/*Ishtor)', value: 0x57 },
  { label: '(Ch.4 Shop/Ch. 8 Shop)', value: 0x58 },
  { label: '(Arthur/Ch. 9 Shop)', value: 0x59 },
  { label: '(Levin/Ch. 9 Shop)', value: 0x5A },
  { label: '(*Musar)', value: 0x5B },
  { label: '(Holsety)', value: 0x5C },
  { label: '(Sety/Ch. 8 Shop)', value: 0x5D },
  { label: '(Lightning)', value: 0x5E },
  { label: '(Ch. 6 Rizziah)', value: 0x5F },
  { label: '(Diadora/Ch.6 Aura)', value: 0x60 },
  { label: '(Narga)', value: 0x61 },
  { label: '(Ethlin/Ch.7 Shop)', value: 0x62 },
  { label: '(Lachesis/Ch.7 Shop)', value: 0x63 },
  { label: '(Rana/Ch. 8 Shop)', value: 0x64 },
  { label: '(Aideen/Ch. 8 Shop)', value: 0x65 },
  { label: '(Relive Staff)', value: 0x66 },
  { label: '(Nanna/Ch. 8 Shop)', value: 0x67 },
  { label: '(Ch.4 Shop/Ch. 10 Shop)', value: 0x68 },
  { label: '(Recover Staff/Ch.7 Shop)', value: 0x69 },
  { label: '(*Shagall/Ch. 10 Shop)', value: 0x6A },
  { label: '(Corple/Ch. 10 Shop)', value: 0x6B },
  { label: '(Claude/*Kapathogia)', value: 0x6C },
  { label: '(Return Staff/Ch.7 Shop)', value: 0x6D },
  { label: '(Warp Staff/Ch. 9 Shop)', value: 0x6E },
  { label: '(Rescue Staff/Ch. 10 Shop)', value: 0x6F },
  { label: '(Restore Staff/Ch. 9 Shop)', value: 0x70 },
  { label: '(Claude)', value: 0x71 },
  { label: '(Diadora/Ch. 8 Shop)', value: 0x72 },
  { label: '(*Clement/Ch. 10 Shop)', value: 0x73 },
  { label: '(Berserk Staff)', value: 0x74 },
  { label: '(*Dobarl/*Trabant Ring)', value: 0x75 },
  { label: '(Ch.8 Village)', value: 0x76 },
  { label: '(*Sandima/*Liza Ring)', value: 0x77 },
  { label: '(Magic Ring)', value: 0x78 },
  { label: '(*Gandolf/*Jabarro Ring)', value: 0x79 },
  { label: '(Skill Ring)', value: 0x7A },
  { label: '(Ch.P Village/Johan)', value: 0x7B },
  { label: '(Speed Ring)', value: 0x7C },
  { label: '(*Macbeth/*Ovo Ring)', value: 0x7D },
  { label: '(Ch.7 Village)', value: 0x7E },
  { label: '(*Boldor/Dark Priest Ring)', value: 0x7F },
  { label: '(Barrier Ring)', value: 0x80 },
  { label: '(*Pizarl/*Yurius Ring)', value: 0x81 },
  { label: '(*Phillip Ring)', value: 0x82 },
  { label: '(*Harold/Ch.4 Shop/*Disler Ring)', value: 0x83 },
  { label: '(Ch.10 Celice Beach)', value: 0x84 },
  { label: '(*Papilon/*Ishtar Bracelet)', value: 0x85 },
  { label: '(*Voltz/Johalver Ring)', value: 0x86 },
  { label: '(Bargain Ring)', value: 0x87 },
  { label: '(Knight Ring)', value: 0x88 },
  { label: '(Pursuit Ring)', value: 0x89 },
  { label: '(Prayer Bracelet/*Arion)', value: 0x8A },
  { label: '(Thief Bracelet)', value: 0x8B },
  { label: '(Circlet)', value: 0x8C },
  { label: '(Nothing)', value: 0x8D },
  { label: '(Nothing)', value: 0x8E },
  { label: 'Nothing', value: 0xFF },
];
