export const Characterlist = [
  { label: 'Alm', value: 0 },
  { label: 'Cellica', value: 1 },
  { label: 'Maisen', value: 2 },
  { label: 'Norma', value: 3 },
  { label: 'Ruka', value: 4 },
  { label: 'Cliff', value: 5 },
  { label: 'Robin', value: 6 },
  { label: 'Grey', value: 7 },
  { label: 'Clea', value: 8 },
  { label: 'Clerbe', value: 9 },
  { label: 'Clerbe', value: 10 },
  { label: 'Fols', value: 11 },
  { label: 'May', value: 12 },
  { label: 'Silk', value: 13 },
  { label: 'Jenny', value: 14 },
  { label: 'Bowy', value: 15 },
  { label: 'Kamui', value: 16 },
  { label: 'Valbo', value: 17 },
  { label: 'Matilda', value: 18 },
  { label: 'Paison', value: 19 },
  { label: 'Leo', value: 20 },
  { label: 'Atlas', value: 21 },
  { label: 'Jesey', value: 22 },
  { label: 'Fols (Alm\'s portrait)', value: 23 },
  { label: 'Sonia', value: 24 },
  { label: 'Dean', value: 25 },
  { label: 'Savor', value: 26 },
  { label: 'Ryuto', value: 27 },
  { label: 'Dyute', value: 28 },
  { label: 'Teeta', value: 29 },
  { label: 'Katua', value: 30 },
  { label: 'Paola', value: 31 },
  { label: 'Est', value: 32 },
  { label: 'Zeke', value: 33 },
];

export const Classlist = [
  { label: 'None', value: 0x00 },
  { label: 'Knight', value: 0x01 },
  { label: 'Armor', value: 0x02 },
  { label: 'Pegasus Knight', value: 0x03 },
  { label: 'Paladin', value: 0x04 },
  { label: 'Falcon Knight', value: 0x05 },
  { label: 'Soldier', value: 0x06 },
  { label: 'Gold Knight', value: 0x07 },
  { label: 'Mercenary', value: 0x08 },
  { label: 'Swordfighter', value: 0x09 },
  { label: 'Demon Fighter', value: 0x0A },
  { label: 'Priestess', value: 0x0B },
  { label: 'Archer', value: 0x0C },
  { label: 'Sniper', value: 0x0D },
  { label: 'Villager', value: 0x0E },
  { label: 'Mage (M)', value: 0x0F },
  { label: 'Mage (F)', value: 0x10 },
  { label: 'Saint', value: 0x11 },
  { label: 'Sister', value: 0x12 },
  { label: 'Sage', value: 0x13 },
  { label: 'Bow Knight', value: 0x14 },
  { label: 'Fighter', value: 0x15 },
  { label: 'Baron', value: 0x16 },
  { label: 'Hero', value: 0x17 },
  { label: 'Princess', value: 0x18 },
];

export const Itemlist = [
  { label: 'None', value: 0x00 },
  { label: 'No Name', value: 0x01 },
  { label: 'Steel Lance', value: 0x02 },
  { label: 'Silver Lance', value: 0x03 },
  { label: 'Javelin', value: 0x04 },
  { label: 'Holy Lance', value: 0x05 },
  { label: 'Knight Killer', value: 0x06 },
  { label: 'Gradius', value: 0x07 },
  { label: 'Shooting Star', value: 0x08 },
  { label: 'Sun', value: 0x09 },
  { label: 'Moonlight', value: 0x0A },
  { label: 'Steel Sword', value: 0x0B },
  { label: 'Silver Sword', value: 0x0C },
  { label: 'Hero Sword', value: 0x0D },
  { label: 'Darkness Sword', value: 0x0E },
  { label: 'Thunder Sword', value: 0x0F },
  { label: 'Holy Sword', value: 0x10 },
  { label: 'Falchion', value: 0x11 },
  { label: 'Royal Sword', value: 0x12 },
  { label: 'Tentacle', value: 0x13 },
  { label: 'Steel Bow', value: 0x14 },
  { label: 'Holy Bow', value: 0x15 },
  { label: 'Silver Bow', value: 0x16 },
  { label: 'Fire', value: 0x17 },
  { label: 'Thunder', value: 0x18 },
  { label: 'Rainarok', value: 0x19 },
  { label: 'Angel', value: 0x1A },
  { label: 'Excalibur', value: 0x1B },
  { label: 'Arrow', value: 0x1C },
  { label: 'Aura', value: 0x1D },
  { label: 'Gaia (unused)', value: 0x1E },
  { label: 'Dora', value: 0x1F },
  { label: 'Slime', value: 0x20 },
  { label: 'Death', value: 0x21 },
  { label: 'Medusa', value: 0x22 },
  { label: 'Recover', value: 0x23 },
  { label: 'Reserve', value: 0x24 },
  { label: 'Messaih', value: 0x25 },
  { label: 'Eyebeam', value: 0x26 },
  { label: 'Eyeball', value: 0x27 },
  { label: 'Recover', value: 0x28 },
  { label: 'Reblow', value: 0x29 },
  { label: 'Resire', value: 0x2A },
  { label: 'Warp', value: 0x2B },
  { label: 'Reserve', value: 0x2C },
  { label: 'Illusion', value: 0x2D },
  { label: 'Dear', value: 0x2E },
  { label: 'No Name', value: 0x2F },
  { label: 'Leather Shield', value: 0x30 },
  { label: 'Steel Shield', value: 0x31 },
  { label: 'Silver Shield', value: 0x32 },
  { label: 'Holy Shield', value: 0x33 },
  { label: 'Magic Seal Shield', value: 0x34 },
  { label: 'Dragon Shield', value: 0x35 },
  { label: 'Holy Ring', value: 0x36 },
  { label: 'Angel Ring', value: 0x37 },
  { label: 'Speed Ring', value: 0x38 },
  { label: 'Magic Ring', value: 0x39 },
  { label: 'Prayer Ring', value: 0x3A },
];
