export const ItemList = [
  { label: 'Iron Sword', value: 0 },
  { label: 'Steel Sword', value: 1 },
  { label: 'Silver Sword', value: 2 },
  { label: 'Killing Edge', value: 3 },
  { label: 'Levin Sword', value: 4 },
  { label: 'Devil Sword', value: 5 },
  { label: 'Wyrmslayer', value: 6 },
  { label: 'Armorslayer', value: 7 },
  { label: 'Mercurius', value: 8 },
  { label: 'Rapier', value: 9 },
  { label: 'Wo Dao', value: 10 },
  { label: 'Brave Sword', value: 11 },
  { label: 'Falchion (Fake)', value: 12 },
  { label: 'Falchion (Weak)', value: 13 },
  { label: 'Falchion', value: 14 },
  { label: 'Iron Lance', value: 15 },
  { label: 'Steel Lance', value: 16 },
  { label: 'Silver Lance', value: 17 },
  { label: 'Javelin', value: 18 },
  { label: 'Killer Lance', value: 19 },
  { label: 'Ridersbane', value: 20 },
  { label: 'Wing Spear', value: 21 },
  { label: 'Dragonpike', value: 22 },
  { label: 'Brave Lance', value: 23 },
  { label: 'Gradivus', value: 24 },
  { label: 'Iron Axe', value: 25 },
  { label: 'Steel Axe', value: 26 },
  { label: 'Silver Axe', value: 27 },
  { label: 'Hand Axe', value: 28 },
  { label: 'Killer Axe', value: 29 },
  { label: 'Hammer', value: 30 },
  { label: 'Poleax', value: 31 },
  { label: 'Devil Axe', value: 32 },
  { label: 'Brave Axe', value: 33 },
  { label: 'Hauteclere', value: 34 },
  { label: 'Iron Bow', value: 35 },
  { label: 'Steel Bow', value: 36 },
  { label: 'Silver Bow', value: 37 },
  { label: 'Killer Bow', value: 38 },
  { label: 'Longbow', value: 39 },
  { label: 'Brave Bow', value: 40 },
  { label: 'Parthia', value: 41 },
  { label: 'Arrowspate', value: 42 },
  { label: 'Stonehoist', value: 43 },
  { label: 'Hoistflamme', value: 44 },
  { label: 'Thunderbolt', value: 45 },
  { label: 'Pachyderm', value: 46 },
  { label: 'Firestone', value: 47 },
  { label: 'Earthstone', value: 48 },
  { label: 'Magestone', value: 49 },
  { label: 'Divinestone', value: 50 },
  { label: 'Fire', value: 51 },
  { label: 'Thunder', value: 52 },
  { label: 'Blizzard', value: 53 },
  { label: 'Elfire', value: 54 },
  { label: 'Imhullu (False)', value: 55 },
  { label: 'Bolganone', value: 56 },
  { label: 'Thoron', value: 57 },
  { label: 'Swarm', value: 58 },
  { label: 'Aura', value: 59 },
  { label: 'Excalibur', value: 60 },
  { label: 'Imhullu', value: 61 },
  { label: 'Starlight', value: 62 },
  { label: 'Heal', value: 63 },
  { label: 'Mend', value: 64 },
  { label: 'Recover', value: 65 },
  { label: 'Physic', value: 66 },
  { label: 'Fortify', value: 67 },
  { label: 'Warp', value: 68 },
  { label: 'Barrier', value: 69 },
  { label: 'Hammerne', value: 70 },
  { label: 'Aum', value: 71 },
  { label: 'Door Key', value: 72 },
  { label: 'Bridge Key', value: 73 },
  { label: 'Master Key', value: 74 },
  { label: 'Vulnerary', value: 75 },
  { label: 'Pure Water', value: 76 },
  { label: 'Energy Drop', value: 77 },
  { label: 'Spirit Dust', value: 78 },
  { label: 'Secret Book', value: 79 },
  { label: 'Speedwings', value: 80 },
  { label: 'Goddess Icon', value: 81 },
  { label: 'Dracoshield', value: 82 },
  { label: 'Talisman', value: 83 },
  { label: 'Seraph Robe', value: 84 },
  { label: 'Boots', value: 85 },
  { label: 'Arms Scroll', value: 86 },
  { label: 'Silver Card', value: 87 },
  { label: 'VIP Card', value: 88 },
  { label: 'Master Seal', value: 89 },
  { label: 'Elysian Whip', value: 90 },
  { label: 'Torch', value: 91 },
  { label: 'Iote\'s Shield', value: 92 },
  { label: 'Lightsphere', value: 93 },
  { label: 'Starsphere', value: 94 },
  { label: 'Geosphere', value: 95 },
  { label: 'Fire Emblem', value: 96 },
  { label: 'Door Key', value: 97 },
  { label: 'Bullion (S)', value: 98 },
  { label: 'Bullion (M)', value: 99 },
  { label: 'Bullion (L)', value: 100 },
  { label: 'Bullion (XL)', value: 101 },
  { label: 'All blanks beyond this point.', value: 102 },
  { label: 'This list was painstakingly created by Arch.', value: 103 },
  { label: 'Entry 104', value: 104 },
  { label: 'Entry 105', value: 105 },
  { label: 'Entry 106', value: 106 },
  { label: 'Entry 107', value: 107 },
  { label: 'Entry 108', value: 108 },
  { label: 'Entry 109', value: 109 },
  { label: 'Entry 110', value: 110 },
  { label: 'Entry 111', value: 111 },
  { label: 'Entry 112', value: 112 },
  { label: 'Entry 113', value: 113 },
  { label: 'Entry 114', value: 114 },
  { label: 'Entry 115', value: 115 },
  { label: 'Entry 116', value: 116 },
  { label: 'Entry 117', value: 117 },
  { label: 'Entry 118', value: 118 },
  { label: 'Entry 119', value: 119 },
  { label: 'Entry 120', value: 120 },
  { label: 'Entry 121', value: 121 },
  { label: 'Entry 122', value: 122 },
  { label: 'Entry 123', value: 123 },
  { label: 'Entry 124', value: 124 },
  { label: 'Entry 125', value: 125 },
  { label: 'Entry 126', value: 126 },
  { label: 'Entry 127', value: 127 },
  { label: 'Entry 128', value: 128 },
  { label: 'Entry 129', value: 129 },
  { label: 'Entry 130', value: 130 },
  { label: 'Entry 131', value: 131 },
  { label: 'Entry 132', value: 132 },
  { label: 'Entry 133', value: 133 },
  { label: 'Entry 134', value: 134 },
  { label: 'Entry 135', value: 135 },
  { label: 'Entry 136', value: 136 },
  { label: 'Entry 137', value: 137 },
  { label: 'Entry 138', value: 138 },
  { label: 'Entry 139', value: 139 },
  { label: 'Entry 140', value: 140 },
  { label: 'Entry 141', value: 141 },
  { label: 'Entry 142', value: 142 },
  { label: 'Entry 143', value: 143 },
  { label: 'Entry 144', value: 144 },
  { label: 'Entry 145', value: 145 },
  { label: 'Entry 146', value: 146 },
  { label: 'Entry 147', value: 147 },
  { label: 'Entry 148', value: 148 },
  { label: 'Entry 149', value: 149 },
  { label: 'Entry 150', value: 150 },
  { label: 'Entry 151', value: 151 },
  { label: 'Entry 152', value: 152 },
];

export const ItemTypes = [
  { label: 'Sword', value: 0 },
  { label: 'Lance', value: 1 },
  { label: 'Axe', value: 2 },
  { label: 'Bow', value: 3 },
  { label: 'Magic', value: 4 },
  { label: 'Staff', value: 5 },
  { label: 'Dragonstone', value: 6 },
  { label: 'Ballista', value: 7 },
  { label: 'Item', value: 8 },
];

export const WeaponLevels = [
  { label: 'None', value: 0x00 },
  { label: 'E', value: 0x01 },
  { label: 'D', value: 0x1F },
  { label: 'C', value: 0x4C },
  { label: 'B', value: 0x88 },
  { label: 'A', value: 0xC4 },
];

export const Effect3 = [
  { label: 'None', value: 0x00 },
  { label: 'Res +2', value: 0x02 },
  { label: 'Barrier Effect (Res +7)', value: 0x07 },
  { label: 'Adds Use Command', value: 0x100 },
  { label: 'Talisman Effect (Res +2)', value: 0x102 },
  { label: 'Pure Water Effect (Res +7)', value: 0x107 },
  { label: 'Physic Effect', value: 0x2000 },
  { label: 'Fortify Effect', value: 0x3000 },
  { label: 'Brave Weapon', value: 0x200 },
  { label: 'Magic Weapon', value: 0x400 },
  { label: 'Brave Magic Weapon', value: 0x600 },
  { label: 'Uncounterable Weapon', value: 0x800 },
  { label: 'Uncounterable Brave Weapon', value: 0xA00 },
  { label: 'Uncounterable Magic Weapon', value: 0xC00 },
  { label: 'Uncounterable Brave Magic Weapon', value: 0xE00 },
  { label: 'Devil Weapon', value: 0x4000 },
  { label: 'Brave Devil Weapon', value: 0x4200 },
  { label: 'Magic Devil Weapon', value: 0x4400 },
  { label: 'Brave Magic Devil Weapon', value: 0x4600 },
  { label: 'Uncounterable Devil Weapon', value: 0x4800 },
  { label: 'Uncounterable Brave Devil Weapon', value: 0x4A00 },
  { label: 'Uncounterable Magic Devil Weapon', value: 0x4C00 },
  { label: 'Uncounterable Brave Magic Devil Weapon', value: 0x4E00 },
  { label: 'Invincibility (Imhullu)', value: 0x40000 },
  { label: 'Starlight', value: 0x80000 },
  { label: 'Negate Magic', value: 0x100000 },
  { label: 'Magestone', value: 0x100400 },
  { label: 'Open Chests', value: 0x8000000 },
  { label: 'Open Doors', value: 0x10000000 },
  { label: 'Open Doors,Chests', value: 0x18000000 },
  { label: 'Open Bridges', value: 0x20000000 },
  { label: 'Open Bridges,Chests', value: 0x28000000 },
  { label: 'Open Bridges,Doors', value: 0x30000000 },
  { label: 'Open Chests,Doors,Bridges', value: 0x38000000 },
  { label: 'Silver Card', value: 0x80000000 },
];

export const Effectiveness = [
  { label: 'None', value: 0x00 },
  { label: 'Unknown', value: 0x01 },
  { label: 'Unknown', value: 0x04 },
  { label: 'Unknown', value: 0x08 },
  { label: 'Unknown', value: 0x40 },
  { label: 'Aura (Unknown)', value: 0x48 },
  { label: 'Excalibur (Unknown)', value: 0x2044 },
  { label: 'Divinestone (Unknown)', value: 0x4041 },
  { label: 'Dragonkiller', value: 0x100 },
  { label: 'Dragonkiller; Unknown', value: 0x140 },
  { label: 'Falchion', value: 0x340 },
  { label: 'Armorkiller', value: 0x400 },
  { label: 'Armorkiller; Unknown', value: 0x440 },
  { label: 'Armor,Dragonkiller', value: 0x500 },
  { label: 'Armor,Dragonkiller; Unknown', value: 0x540 },
  { label: 'Ballistakiller', value: 0x800 },
  { label: 'Ballistakiller; Unknown', value: 0x840 },
  { label: 'Ballista,Dragonkiller', value: 0x900 },
  { label: 'Ballista,Dragon,Armorkiller; Unknown', value: 0x940 },
  { label: 'Ballista,Armorkiller', value: 0xC000 },
  { label: 'Ballista,Armorkiller; Unknown', value: 0xC040 },
  { label: 'Ballista,Dragon,Armorkiller', value: 0xD000 },
  { label: 'Ballista,Dragon,Armorkiller; Unknown', value: 0xD040 },
  { label: 'Riderkiller', value: 0x1000 },
  { label: 'Riderkiller; Unknown', value: 0x1040 },
  { label: 'Rider,Dragonkiller', value: 0x1100 },
  { label: 'Rider,Dragonkiller;Unknown', value: 0x1140 },
  { label: 'Rider,Armorkiller', value: 0x1400 },
  { label: 'Rider,Armorkiller; Unknown', value: 0x1440 },
  { label: 'Rider,Dragon,Armorkiller', value: 0x1500 },
  { label: 'Rider,Dragon,Armorkiller; Unknown', value: 0x1540 },
  { label: 'Rider,Ballistakiller', value: 0x1800 },
  { label: 'Rider,Ballistakiller; Unknown', value: 0x1840 },
  { label: 'Rider,Dragon,Ballistakiller; Unknown', value: 0x1900 },
  { label: 'Rider,Dragon,Ballistakiller; Unknown', value: 0x1940 },
  { label: 'Rider,Armor,Ballistakiller', value: 0x1C00 },
  { label: 'Rider,Armor,Ballistakiller; Unknown', value: 0x1C40 },
  { label: 'Rider,Dragon,Armor,Ballistakiller', value: 0x1D00 },
  { label: 'Rider,Dragon,Armor,Ballistakiller; Unknown', value: 0x1D40 },
  { label: 'Flierkiller', value: 0x2000 },
  { label: 'Flierkiller; Unknown', value: 0x2040 },
  { label: 'Flier,Dragonkiller', value: 0x2100 },
  { label: 'Flier,Dragonkiller; Unknown', value: 0x2140 },
  { label: 'Flier;Armorkiller', value: 0x2400 },
  { label: 'Flier;Armorkiller; Unknown', value: 0x2440 },
  { label: 'Flier Dragon,Armorkiller', value: 0x2500 },
  { label: 'Flier,Dragon,Armorkiller; Unknown', value: 0x2540 },
  { label: 'Flier,Ballistakiller', value: 0x2800 },
  { label: 'Flier,Ballistakiller; Unknown', value: 0x2840 },
  { label: 'Flier,Dragon,Ballistakiller', value: 0x2900 },
  { label: 'Flier,Dragon,Ballistakiller; Unknown', value: 0x2940 },
  { label: 'Flier,Armor,Ballistakiller', value: 0x2C00 },
  { label: 'Flier,Armor,Ballistakiller; Unknown', value: 0x2C40 },
  { label: 'Flier,Dragon,Armor,Ballistakiller', value: 0x2D00 },
  { label: 'Flier,Dragon,Armor,Ballistakiller; Unknown', value: 0x2D40 },
  { label: 'Flier,Riderkiller', value: 0x3000 },
  { label: 'Flier,Riderkiller; Unknown', value: 0x3040 },
  { label: 'Flier,Dragon,Riderkiller', value: 0x3100 },
  { label: 'Flier,Dragon,Riderkiller; Unknown', value: 0x3140 },
  { label: 'Flier,Armor,Riderkiller', value: 0x3400 },
  { label: 'Flier,Armor,Riderkiller; Unknown', value: 0x3440 },
  { label: 'Flier,Dragon,Armor,Riderkiller', value: 0x3500 },
  { label: 'Flier,Dragon,Armor,Riderkiller; Unknown', value: 0x3540 },
  { label: 'Flier,Ballista,Riderkiller', value: 0x3800 },
  { label: 'Flier,Ballista,Riderkiller; Unknown', value: 0x3840 },
  { label: 'Flier,Dragon,Ballista,Riderkiller', value: 0x3900 },
  { label: 'Flier,Dragon,Ballista,Riderkiller; Unknown', value: 0x3940 },
  { label: 'Flier,Armor,Ballista,Riderkiller', value: 0x3C00 },
  { label: 'Flier,Armor,Ballista,Riderkiller; Unknown', value: 0x3C40 },
  { label: 'Flier,Dragon,Armor,Ballista,Riderkiller', value: 0x3D00 },
  { label: 'Flier,Dragon,Armor,Ballista,Riderkiller; Unknown;', value: 0x3D40 },
  { label: 'Flier,Dragon,Armor,Ballista,Riderkiller; Unknown,Unknown', value: 0x3D41 },
  { label: 'Flier,Dragon,Armor,Ballista,Riderkiller; Unknown,Unknown', value: 0x3D44 },
  { label: 'Flier,Dragon,Armor,Ballista,Riderkiller; Unknown;Unknown,Unknown', value: 0x3D45 },
];

export const MapAnimationPointer = [
  { label: 'None', value: 0x00 },
  { label: 'Vulnerary/Gradivus/Falchion/Hauteclere', value: 0xF8B000 },
  { label: 'Pure Water/Parthia', value: 0xC0E100 },
  { label: 'Heal/Physic', value: 0xCB9400 },
  { label: 'Mend', value: 0xF81200 },
  { label: 'Recover', value: 0xF80A00 },
  { label: 'Fortify', value: 0xF81900 },
  { label: 'Warp', value: 0xF8BA00 },
  { label: 'Barrier', value: 0xE17200 },
  { label: 'Hammerne', value: 0xC0D800 },
  { label: 'Aum', value: 0xE18D00 },
  { label: 'Stat Boosters', value: 0xBAF100 },
  { label: 'Torch', value: 0xF89100 },
  { label: 'Geosphere', value: 0xBAF800 },
];

export const RangedAttackAnimation = [
  { label: 'None', value: 0x00 },
  { label: 'Levin Sword', value: 0xF88100 },
  { label: 'Arrwowspate', value: 0xF7FD00 },
  { label: 'Stonehoist', value: 0xBB0100 },
  { label: 'Hoistflame', value: 0xC0B200 },
  { label: 'Thunderbolt', value: 0xF87200 },
  { label: 'Pachyderm', value: 0xBB0100 },
  { label: 'Firestone', value: 0xC0A400 },
  { label: 'Earthstone', value: 0xC0BD00 },
  { label: 'Magestone', value: 0xE17E00 },
  { label: 'Divinestone', value: 0xC0CB00 },
  { label: 'Fire', value: 0xC09B00 },
  { label: 'Thunder', value: 0xF86700 },
  { label: 'Blizzard', value: 0xBAE600 },
  { label: 'Elfire', value: 0xBB0D00 },
  { label: 'Bolganone', value: 0xF8A400 },
  { label: 'Thoron', value: 0xF89B00 },
  { label: 'Swarm', value: 0xF8BF00 },
  { label: 'Aura', value: 0xBA5A00 },
  { label: 'Excalibur', value: 0xBB1700 },
  { label: 'Imhullu', value: 0xE16A00 },
  { label: 'Starlight', value: 0xF82100 },
];
