export const FE7CharacterList = [
  { label: 'None', value: 0 },
  { label: 'Eliwood', value: 1 },
  { label: 'Hector', value: 2 },
  { label: 'Lyn (tutorial)', value: 3 },
  { label: 'Raven', value: 4 },
  { label: 'Geitz', value: 5 },
  { label: 'Guy', value: 6 },
  { label: 'Karel', value: 7 },
  { label: 'Dorcas', value: 8 },
  { label: 'Bartre', value: 9 },
  { label: 'Citizen', value: 10 },
  { label: 'Oswin', value: 11 },
  { label: 'Fargus', value: 12 },
  { label: 'Wil (tutorial)', value: 13 },
  { label: 'Rebecca', value: 14 },
  { label: 'Louise', value: 15 },
  { label: 'Lucius', value: 16 },
  { label: 'Serra', value: 17 },
  { label: 'Renault', value: 18 },
  { label: 'Erk', value: 19 },
  { label: 'Nino', value: 20 },
  { label: 'Pent', value: 21 },
  { label: 'Canas', value: 22 },
  { label: 'Kent (tutorial)', value: 23 },
  { label: 'Sain (tutorial)', value: 24 },
  { label: 'Lowen', value: 25 },
  { label: 'Marcus', value: 26 },
  { label: 'Priscilla', value: 27 },
  { label: 'Rath (tutorial)', value: 28 },
  { label: 'Florina (tutorial)', value: 29 },
  { label: 'Fiora', value: 30 },
  { label: 'Farina', value: 31 },
  { label: 'Heath', value: 32 },
  { label: 'Vaida', value: 33 },
  { label: 'Hawkeye', value: 34 },
  { label: 'Matthew', value: 35 },
  { label: 'Jaffar', value: 36 },
  { label: 'Ninian', value: 37 },
  { label: 'Nils', value: 38 },
  { label: 'Athos', value: 39 },
  { label: 'Merlinus', value: 40 },
  { label: 'Nils (Final Chapter)', value: 41 },
  { label: 'Uther', value: 42 },
  { label: 'Vaida (Boss)', value: 43 },
  { label: 'Wallace', value: 44 },
  { label: 'Lyn (Not tutorial)', value: 45 },
  { label: 'Wil (Not tutorial)', value: 46 },
  { label: 'Kent (Not tutorial)', value: 47 },
  { label: 'Sain (Not tutorial)', value: 48 },
  { label: 'Florina (Not tutorial)', value: 49 },
  { label: 'Rath (Not tutorial)', value: 50 },
  { label: 'Dart', value: 51 },
  { label: 'Isadora', value: 52 },
  { label: 'Elenora', value: 53 },
  { label: 'Legault', value: 54 },
  { label: 'Karla', value: 55 },
  { label: 'Harken', value: 56 },
  { label: 'Leila', value: 57 },
  { label: 'Bramimond', value: 58 },
  { label: 'Kishuna', value: 59 },
  { label: 'Groznyi', value: 60 },
  { label: 'Wire', value: 61 },
  { label: 'Bandit', value: 62 },
  { label: 'Zagan', value: 63 },
  { label: 'Boies', value: 64 },
  { label: 'Puzon', value: 65 },
  { label: 'Bandit', value: 66 },
  { label: 'Santals', value: 67 },
  { label: 'Nergal', value: 68 },
  { label: 'Erik', value: 69 },
  { label: 'Sealen', value: 70 },
  { label: 'Bauker', value: 71 },
  { label: 'Bernard', value: 72 },
  { label: 'Damian', value: 73 },
  { label: 'Zoldam', value: 74 },
  { label: 'Uhai', value: 75 },
  { label: 'Aion', value: 76 },
  { label: 'Darin', value: 77 },
  { label: 'Cameron', value: 78 },
  { label: 'Oleg', value: 79 },
  { label: 'Eubans', value: 80 },
  { label: 'Ursula', value: 81 },
  { label: 'Black Fang', value: 82 },
  { label: 'Paul', value: 83 },
  { label: 'Jasmine', value: 84 },
  { label: 'Black Fang', value: 85 },
  { label: 'Jerme (Morph)', value: 86 },
  { label: 'Pascal', value: 87 },
  { label: 'Kenneth', value: 88 },
  { label: 'Jerme', value: 89 },
  { label: 'Maxime', value: 90 },
  { label: 'Sonia', value: 91 },
  { label: 'Teodor', value: 92 },
  { label: 'Georg', value: 93 },
  { label: 'Kaim', value: 94 },
  { label: 'Merc', value: 95 },
  { label: 'Denning', value: 96 },
  { label: 'Bern', value: 97 },
  { label: 'Morph', value: 98 },
  { label: 'Lloyd (1)', value: 99 },
  { label: 'Linus (1)', value: 100 },
  { label: 'Lloyd (2)', value: 101 },
  { label: 'Linus (2)', value: 102 },
  { label: 'Bandit', value: 103 },
  { label: 'Bandit', value: 104 },
  { label: 'Bandit', value: 105 },
  { label: 'Laus', value: 106 },
  { label: 'Laus', value: 107 },
  { label: 'Pirate', value: 108 },
  { label: 'Black Fang', value: 109 },
  { label: 'Black Fang', value: 110 },
  { label: 'Ostia', value: 111 },
  { label: 'Black Fang', value: 112 },
  { label: 'Guardian', value: 113 },
  { label: 'Morph', value: 114 },
  { label: 'Morph', value: 115 },
  { label: 'Morph', value: 116 },
  { label: 'Caelin', value: 117 },
  { label: 'Caelin', value: 118 },
  { label: 'Caelin', value: 119 },
  { label: 'Laus', value: 120 },
  { label: 'Laus', value: 121 },
  { label: 'Zephiel', value: 122 },
  { label: 'Elbert', value: 123 },
  { label: 'Black Fang', value: 124 },
  { label: 'Black Fang', value: 125 },
  { label: 'Black Fang', value: 126 },
  { label: 'Morph', value: 127 },
  { label: 'Morph', value: 128 },
  { label: 'Morph', value: 129 },
  { label: 'Morph', value: 130 },
  { label: 'Black Fang', value: 131 },
  { label: 'Brendan', value: 132 },
  { label: 'Limstella', value: 133 },
  { label: 'Dragon', value: 134 },
  { label: 'Batta', value: 135 },
  { label: 'Bandit', value: 136 },
  { label: 'Zugu', value: 137 },
  { label: 'Bandit', value: 138 },
  { label: 'Bandit', value: 139 },
  { label: 'Bandit', value: 140 },
  { label: 'Glass', value: 141 },
  { label: 'Migal', value: 142 },
  { label: 'Bandit', value: 143 },
  { label: 'Bandit', value: 144 },
  { label: 'Bandit', value: 145 },
  { label: 'Bandit', value: 146 },
  { label: 'Bandit', value: 147 },
  { label: 'Carjiga', value: 148 },
  { label: 'Bandit', value: 149 },
  { label: 'Bandit', value: 150 },
  { label: 'Bandit', value: 151 },
  { label: 'Bandit', value: 152 },
  { label: 'Bug', value: 153 },
  { label: 'Bandit', value: 154 },
  { label: 'Bandit', value: 155 },
  { label: 'Bandit', value: 156 },
  { label: 'Bandit', value: 157 },
  { label: 'Natalie', value: 158 },
  { label: 'Bool', value: 159 },
  { label: 'Bandit', value: 160 },
  { label: 'Bandit', value: 161 },
  { label: 'Bandit', value: 162 },
  { label: 'Bandit', value: 163 },
  { label: 'Bandit', value: 164 },
  { label: 'Bandit', value: 165 },
  { label: 'Heintz', value: 166 },
  { label: 'Black Fang', value: 167 },
  { label: 'Black Fang', value: 168 },
  { label: 'Black Fang', value: 169 },
  { label: 'Black Fang', value: 170 },
  { label: 'Black Fang', value: 171 },
  { label: 'Black Fang', value: 172 },
  { label: 'Beyard', value: 173 },
  { label: 'Black Fang', value: 174 },
  { label: 'Black Fang', value: 175 },
  { label: 'Black Fang', value: 176 },
  { label: 'Black Fang', value: 177 },
  { label: 'Black Fang', value: 178 },
  { label: 'Black Fang', value: 179 },
  { label: 'Black Fang', value: 180 },
  { label: 'Black Fang', value: 181 },
  { label: 'Yogi', value: 182 },
  { label: 'Caelin', value: 183 },
  { label: 'Caelin', value: 184 },
  { label: 'Caelin', value: 185 },
  { label: 'Caelin', value: 186 },
  { label: 'Caelin', value: 187 },
  { label: 'Caelin', value: 188 },
  { label: 'Caelin', value: 189 },
  { label: 'Eagler', value: 190 },
  { label: 'Caelin', value: 191 },
  { label: 'Caelin', value: 192 },
  { label: 'Caelin', value: 193 },
  { label: 'Caelin', value: 194 },
  { label: 'Caelin', value: 195 },
  { label: 'Caelin', value: 196 },
  { label: 'Lundgren', value: 197 },
  { label: 'Caelin', value: 198 },
  { label: 'Caelin', value: 199 },
  { label: 'Caelin', value: 200 },
  { label: 'Caelin', value: 201 },
  { label: 'Caelin', value: 202 },
  { label: 'Caelin', value: 203 },
  { label: 'Caelin', value: 204 },
  { label: 'Tactician', value: 205 },
  { label: 'Citizen', value: 206 },
  { label: 'Citizen', value: 207 },
  { label: 'Citizen', value: 208 },
  { label: 'Citizen', value: 209 },
  { label: 'Citizen', value: 210 },
  { label: 'Citizen', value: 211 },
  { label: 'Citizen', value: 212 },
  { label: 'Citizen', value: 213 },
  { label: 'Citizen', value: 214 },
  { label: 'Merc', value: 215 },
  { label: 'Pirate', value: 216 },
  { label: 'Bandit', value: 217 },
  { label: 'Citizen', value: 218 },
  { label: 'Citizen', value: 219 },
  { label: 'Citizen', value: 220 },
  { label: 'Black Fang', value: 221 },
  { label: 'Black Fang', value: 222 },
  { label: 'Bandit', value: 223 },
  { label: 'Black Fang', value: 224 },
  { label: 'Morph', value: 225 },
  { label: 'Black Fang', value: 226 },
  { label: 'Black Fang', value: 227 },
  { label: 'Bandit', value: 228 },
  { label: 'Ostia', value: 229 },
  { label: 'Rath\'s unit', value: 230 },
  { label: 'Bandit', value: 231 },
  { label: 'Bandit', value: 232 },
  { label: 'Bern', value: 233 },
  { label: 'Guardian', value: 234 },
  { label: 'Morph', value: 235 },
  { label: 'Laus', value: 236 },
  { label: 'Bandit', value: 237 },
  { label: 'Bandit', value: 238 },
  { label: 'Bern', value: 239 },
  { label: 'Guardian', value: 240 },
  { label: 'Morph', value: 241 },
  { label: 'Guardian', value: 242 },
  { label: 'Black Fang', value: 243 },
  { label: 'Lloyd (Morph)', value: 244 },
  { label: 'Linus (Morph)', value: 245 },
  { label: 'Brendan (Morph)', value: 246 },
  { label: 'Uhai (Morph)', value: 247 },
  { label: 'Ursula (Morph)', value: 248 },
  { label: 'Kenneth (Morph)', value: 249 },
  { label: 'Darin (Morph)', value: 250 },
  { label: 'Enemy', value: 251 },
  { label: 'Wall', value: 252 },
  { label: 'Snag', value: 253 },
];

export const Characters = [
  { label: 'None', value: 0x00 },
  { label: 'Eliwood', value: 0x01 },
  { label: 'Hector', value: 0x02 },
  { label: 'Lyn (Tutorial)', value: 0x03 },
  { label: 'Raven', value: 0x04 },
  { label: 'Geitz', value: 0x05 },
  { label: 'Guy', value: 0x06 },
  { label: 'Karel', value: 0x07 },
  { label: 'Dorcas', value: 0x08 },
  { label: 'Bartre', value: 0x09 },
  { label: 'Citizen', value: 0x0A },
  { label: 'Oswin', value: 0x0B },
  { label: 'Fargus', value: 0x0C },
  { label: 'Wil (Tutorial)', value: 0x0D },
  { label: 'Rebecca', value: 0x0E },
  { label: 'Louise', value: 0x0F },
  { label: 'Lucius', value: 0x10 },
  { label: 'Serra', value: 0x11 },
  { label: 'Renault', value: 0x12 },
  { label: 'Erk', value: 0x13 },
  { label: 'Nino', value: 0x14 },
  { label: 'Pent', value: 0x15 },
  { label: 'Canas', value: 0x16 },
  { label: 'Kent (Tutorial)', value: 0x17 },
  { label: 'Sain (Tutorial)', value: 0x18 },
  { label: 'Lowen', value: 0x19 },
  { label: 'Marcus', value: 0x1A },
  { label: 'Priscilla', value: 0x1B },
  { label: 'Rath (Tutorial)', value: 0x1C },
  { label: 'Florina (Tutorial)', value: 0x1D },
  { label: 'Fiora', value: 0x1E },
  { label: 'Farina', value: 0x1F },
  { label: 'Heath', value: 0x20 },
  { label: 'Vaida', value: 0x21 },
  { label: 'Hawkeye', value: 0x22 },
  { label: 'Matthew', value: 0x23 },
  { label: 'Jaffar', value: 0x24 },
  { label: 'Ninian', value: 0x25 },
  { label: 'Nils', value: 0x26 },
  { label: 'Athos', value: 0x27 },
  { label: 'Merlinus', value: 0x28 },
  { label: 'Nils(Final Chapter)', value: 0x29 },
  { label: 'Uther', value: 0x2A },
  { label: 'Vaida (Boss)', value: 0x2B },
  { label: 'Wallace', value: 0x2C },
  { label: 'Lyn (not tutorial)', value: 0x2D },
  { label: 'Wil (not tutorial)', value: 0x2E },
  { label: 'Kent (not tutorial)', value: 0x2F },
  { label: 'Sain (not tutorial)', value: 0x30 },
  { label: 'Florina (not tutorial)', value: 0x31 },
  { label: 'Rath (not tutorial)', value: 0x32 },
  { label: 'Dart', value: 0x33 },
  { label: 'Isadora', value: 0x34 },
  { label: 'Elenora', value: 0x35 },
  { label: 'Legault', value: 0x36 },
  { label: 'Karla', value: 0x37 },
  { label: 'Harken', value: 0x38 },
  { label: 'Leila', value: 0x39 },
  { label: 'Bramimond', value: 0x3A },
  { label: 'Kishuna', value: 0x3B },
  { label: 'Groznyi', value: 0x3C },
  { label: 'Wire', value: 0x3D },
  { label: 'Bandit', value: 0x3E },
  { label: 'Zagan', value: 0x3F },
  { label: 'Boies', value: 0x40 },
  { label: 'Puzon', value: 0x41 },
  { label: 'Bandit', value: 0x42 },
  { label: 'Santals', value: 0x43 },
  { label: 'Nergal', value: 0x44 },
  { label: 'Erik', value: 0x45 },
  { label: 'Sealen', value: 0x46 },
  { label: 'Bauker', value: 0x47 },
  { label: 'Bernard', value: 0x48 },
  { label: 'Damian', value: 0x49 },
  { label: 'Zoldam', value: 0x4A },
  { label: 'Uhai', value: 0x4B },
  { label: 'Aion', value: 0x4C },
  { label: 'Darin', value: 0x4D },
  { label: 'Cameron', value: 0x4E },
  { label: 'Oleg', value: 0x4F },
  { label: 'Eubans', value: 0x50 },
  { label: 'Ursula', value: 0x51 },
  { label: 'Black Fang', value: 0x52 },
  { label: 'Paul', value: 0x53 },
  { label: 'Jasmine', value: 0x54 },
  { label: 'Black Fang', value: 0x55 },
  { label: 'Morph Jerme', value: 0x56 },
  { label: 'Pascal', value: 0x57 },
  { label: 'Kenneth', value: 0x58 },
  { label: 'Jerme', value: 0x59 },
  { label: 'Maxime', value: 0x5A },
  { label: 'Sonia', value: 0x5B },
  { label: 'Teodor', value: 0x5C },
  { label: 'Georg', value: 0x5D },
  { label: 'Kaim', value: 0x5E },
  { label: 'Merc', value: 0x5F },
  { label: 'Denning', value: 0x60 },
  { label: 'Bern', value: 0x61 },
  { label: 'Morph', value: 0x62 },
  { label: 'Lloyd (Four-Fanged Offense)', value: 0x63 },
  { label: 'Linus (Four-Fanged Offense)', value: 0x64 },
  { label: 'Lloyd (Cog of Destiny)', value: 0x65 },
  { label: 'Linus (Cog of Destiny)', value: 0x66 },
  { label: 'Bandit', value: 0x67 },
  { label: 'Bandit', value: 0x68 },
  { label: 'Bandit', value: 0x69 },
  { label: 'Laus', value: 0x6A },
  { label: 'Laus', value: 0x6B },
  { label: 'Pirate', value: 0x6C },
  { label: 'Black Fang', value: 0x6D },
  { label: 'Black Fang', value: 0x6E },
  { label: 'Ostia', value: 0x6F },
  { label: 'Black Fang', value: 0x70 },
  { label: 'Guardian', value: 0x71 },
  { label: 'Morph', value: 0x72 },
  { label: 'Morph', value: 0x73 },
  { label: 'Morph', value: 0x74 },
  { label: 'Caelin', value: 0x75 },
  { label: 'Caelin', value: 0x76 },
  { label: 'Caelin', value: 0x77 },
  { label: 'Laus', value: 0x78 },
  { label: 'Laus', value: 0x79 },
  { label: 'Zephiel', value: 0x7A },
  { label: 'Elbert', value: 0x7B },
  { label: 'Black Fang', value: 0x7C },
  { label: 'Black Fang', value: 0x7D },
  { label: 'Black Fang', value: 0x7E },
  { label: 'Morph', value: 0x7F },
  { label: 'Morph', value: 0x80 },
  { label: 'Morph', value: 0x81 },
  { label: 'Morph', value: 0x82 },
  { label: 'Black Fang', value: 0x83 },
  { label: 'Brendan', value: 0x84 },
  { label: 'Limstella', value: 0x85 },
  { label: 'Dragon', value: 0x86 },
  { label: 'Batta', value: 0x87 },
  { label: 'Bandit', value: 0x88 },
  { label: 'Zugu', value: 0x89 },
  { label: 'Bandit', value: 0x8A },
  { label: 'Bandit', value: 0x8B },
  { label: 'Bandit', value: 0x8C },
  { label: 'Glass', value: 0x8D },
  { label: 'Migal', value: 0x8E },
  { label: 'Bandit', value: 0x8F },
  { label: 'Bandit', value: 0x90 },
  { label: 'Bandit', value: 0x91 },
  { label: 'Bandit', value: 0x92 },
  { label: 'Bandit', value: 0x93 },
  { label: 'Carjiga', value: 0x94 },
  { label: 'Bandit', value: 0x95 },
  { label: 'Bandit', value: 0x96 },
  { label: 'Bandit', value: 0x97 },
  { label: 'Bandit', value: 0x98 },
  { label: 'Bug', value: 0x99 },
  { label: 'Bandit', value: 0x9A },
  { label: 'Bandit', value: 0x9B },
  { label: 'Bandit', value: 0x9C },
  { label: 'Bandit', value: 0x9D },
  { label: 'Natalie', value: 0x9E },
  { label: 'Bool', value: 0x9F },
  { label: 'Bandit', value: 0xA0 },
  { label: 'Bandit', value: 0xA1 },
  { label: 'Bandit', value: 0xA2 },
  { label: 'Bandit', value: 0xA3 },
  { label: 'Bandit', value: 0xA4 },
  { label: 'Bandit', value: 0xA5 },
  { label: 'Heintz', value: 0xA6 },
  { label: 'Black Fang', value: 0xA7 },
  { label: 'Black Fang', value: 0xA8 },
  { label: 'Black Fang', value: 0xA9 },
  { label: 'Black Fang', value: 0xAA },
  { label: 'Black Fang', value: 0xAB },
  { label: 'Black Fang', value: 0xAC },
  { label: 'Beyard', value: 0xAD },
  { label: 'Black Fang', value: 0xAE },
  { label: 'Black Fang', value: 0xAF },
  { label: 'Black Fang', value: 0xB0 },
  { label: 'Black Fang', value: 0xB1 },
  { label: 'Black Fang', value: 0xB2 },
  { label: 'Black Fang', value: 0xB3 },
  { label: 'Black Fang', value: 0xB4 },
  { label: 'Black Fang', value: 0xB5 },
  { label: 'Yogi', value: 0xB6 },
  { label: 'Caelin', value: 0xB7 },
  { label: 'Caelin', value: 0xB8 },
  { label: 'Caelin', value: 0xB9 },
  { label: 'Caelin', value: 0xBA },
  { label: 'Caelin', value: 0xBB },
  { label: 'Caelin', value: 0xBC },
  { label: 'Caelin', value: 0xBD },
  { label: 'Eagler', value: 0xBE },
  { label: 'Caelin', value: 0xBF },
  { label: 'Caelin', value: 0xC0 },
  { label: 'Caelin', value: 0xC1 },
  { label: 'Caelin', value: 0xC2 },
  { label: 'Caelin', value: 0xC3 },
  { label: 'Caelin', value: 0xC4 },
  { label: 'Lundgren', value: 0xC5 },
  { label: 'Caelin', value: 0xC6 },
  { label: 'Caelin', value: 0xC7 },
  { label: 'Caelin', value: 0xC8 },
  { label: 'Caelin', value: 0xC9 },
  { label: 'Caelin', value: 0xCA },
  { label: 'Caelin', value: 0xCB },
  { label: 'Caelin', value: 0xCC },
  { label: 'Tactician', value: 0xCD },
  { label: 'Citizen', value: 0xCE },
  { label: 'Citizen', value: 0xCF },
  { label: 'Citizen', value: 0xD0 },
  { label: 'Citizen', value: 0xD1 },
  { label: 'Citizen', value: 0xD2 },
  { label: 'Citizen', value: 0xD3 },
  { label: 'Citizen', value: 0xD4 },
  { label: 'Citizen', value: 0xD5 },
  { label: 'Citizen', value: 0xD6 },
  { label: 'Merc', value: 0xD7 },
  { label: 'Pirate', value: 0xD8 },
  { label: 'Bandit', value: 0xD9 },
  { label: 'Citizen', value: 0xDA },
  { label: 'Citizen', value: 0xDB },
  { label: 'Citizen', value: 0xDC },
  { label: 'Black Fang', value: 0xDD },
  { label: 'Black Fang', value: 0xDE },
  { label: 'Bandit', value: 0xDF },
  { label: 'Black Fang', value: 0xE0 },
  { label: 'Morph', value: 0xE1 },
  { label: 'Black Fang', value: 0xE2 },
  { label: 'Black Fang', value: 0xE3 },
  { label: 'Bandit', value: 0xE4 },
  { label: 'Ostia', value: 0xE5 },
  { label: 'Rath\'s unit', value: 0xE6 },
  { label: 'Bandit', value: 0xE7 },
  { label: 'Bandit', value: 0xE8 },
  { label: 'Bern', value: 0xE9 },
  { label: 'Guardian', value: 0xEA },
  { label: 'Morph', value: 0xEB },
  { label: 'Laus', value: 0xEC },
  { label: 'Bandit', value: 0xED },
  { label: 'Bandit', value: 0xEE },
  { label: 'Bern', value: 0xEF },
  { label: 'Guardian', value: 0xF0 },
  { label: 'Morph', value: 0xF1 },
  { label: 'Guardian', value: 0xF2 },
  { label: 'Black Fang', value: 0xF3 },
  { label: 'Morph Lloyd', value: 0xF4 },
  { label: 'Morph Linus', value: 0xF5 },
  { label: 'Morph Brendan', value: 0xF6 },
  { label: 'Morph Uhai', value: 0xF7 },
  { label: 'Morph Ursula', value: 0xF8 },
  { label: 'Morph Kenneth', value: 0xF9 },
  { label: 'Morph Darin', value: 0xFA },
  { label: 'Enemy', value: 0xFB },
  { label: 'Wall', value: 0xFC },
  { label: 'Snag', value: 0xFD },
  { label: 'None', value: 0xFE },
  { label: 'None', value: 0xFF },
];

export const ClassList = [
  { label: 'None', value: 0x00 },
  { label: 'Eliwood Lord', value: 0x01 },
  { label: 'Lyn Lord', value: 0x02 },
  { label: 'Hector Lord', value: 0x03 },
  { label: 'Eliwood Lord Knight (only by class name)', value: 0x04 },
  { label: 'Lyn Blade Lord (only by class name)', value: 0x05 },
  { label: 'Hector Great Lord (only by class name)', value: 0x06 },
  { label: 'Eliwood Lord Knight', value: 0x07 },
  { label: 'Lyn Blade Lord', value: 0x08 },
  { label: 'Hector Great Lord', value: 0x09 },
  { label: 'Mercenary', value: 0x0A },
  { label: 'Mercenary', value: 0x0B },
  { label: 'Hero', value: 0x0C },
  { label: 'Hero', value: 0x0D },
  { label: 'Myrmidon', value: 0x0E },
  { label: 'Myrmidon', value: 0x0F },
  { label: 'Swordmaster', value: 0x10 },
  { label: 'Swordmaster', value: 0x11 },
  { label: 'Fighter', value: 0x12 },
  { label: 'Warrior', value: 0x13 },
  { label: 'Knight', value: 0x14 },
  { label: 'Knight', value: 0x15 },
  { label: 'General', value: 0x16 },
  { label: 'General', value: 0x17 },
  { label: 'Archer', value: 0x18 },
  { label: 'Archer', value: 0x19 },
  { label: 'Sniper', value: 0x1A },
  { label: 'Sniper', value: 0x1B },
  { label: 'Monk', value: 0x1C },
  { label: 'Cleric', value: 0x1D },
  { label: 'Bishop', value: 0x1E },
  { label: 'Bishop', value: 0x1F },
  { label: 'Mage', value: 0x20 },
  { label: 'Mage', value: 0x21 },
  { label: 'Sage', value: 0x22 },
  { label: 'Sage', value: 0x23 },
  { label: 'Shaman', value: 0x24 },
  { label: 'Shaman', value: 0x25 },
  { label: 'Druid', value: 0x26 },
  { label: 'Druid', value: 0x27 },
  { label: 'Cavalier', value: 0x28 },
  { label: 'Cavalier', value: 0x29 },
  { label: 'Paladin', value: 0x2A },
  { label: 'Paladin', value: 0x2B },
  { label: 'Troubadour', value: 0x2C },
  { label: 'Valkyrie', value: 0x2D },
  { label: 'Nomad', value: 0x2E },
  { label: 'Nomad', value: 0x2F },
  { label: 'Nomad Trooper', value: 0x30 },
  { label: 'Nomad Trooper', value: 0x31 },
  { label: 'Pegasus Knight', value: 0x32 },
  { label: 'Falcon Knight', value: 0x33 },
  { label: 'Wyvern Knight', value: 0x34 },
  { label: 'Wyvern Knight', value: 0x35 },
  { label: 'Wyvern Lord', value: 0x36 },
  { label: 'Wyvern Lord', value: 0x37 },
  { label: 'Soldier', value: 0x38 },
  { label: 'Brigand', value: 0x39 },
  { label: 'Pirate', value: 0x3A },
  { label: 'Berserker', value: 0x3B },
  { label: 'Thief', value: 0x3C },
  { label: 'Thief', value: 0x3D },
  { label: 'Assassin', value: 0x3E },
  { label: 'Civilian', value: 0x3F },
  { label: 'Dancer', value: 0x40 },
  { label: 'Bard', value: 0x41 },
  { label: 'Archsage', value: 0x42 },
  { label: 'Magic Seal', value: 0x43 },
  { label: 'Transporter', value: 0x44 },
  { label: 'Transporter', value: 0x45 },
  { label: 'Fire Dragon', value: 0x46 },
  { label: 'Civilian', value: 0x47 },
  { label: 'Civilian (F)', value: 0x48 },
  { label: 'Child', value: 0x49 },
  { label: 'Brammimond', value: 0x4A },
  { label: 'Peer', value: 0x4B },
  { label: 'Peer (F)', value: 0x4C },
  { label: 'Prince', value: 0x4D },
  { label: 'Queen', value: 0x4E },
  { label: 'Hung Leila', value: 0x4F },
  { label: 'Corsair', value: 0x50 },
  { label: 'Prince (Tactician)', value: 0x51 },
  { label: 'Fallen Prince', value: 0x52 },
  { label: 'Prince facing upward', value: 0x53 },
  { label: 'Fallen Ninian', value: 0x54 },
  { label: 'Fallen Ice Dragon', value: 0x55 },
  { label: 'Fallen Warrior', value: 0x56 },
  { label: 'Child', value: 0x57 },
  { label: 'Child (F)', value: 0x58 },
  { label: 'Transporter w/ Horse', value: 0x59 },
  { label: 'Uber Sage', value: 0x5A },
  { label: 'Archer in Ballista', value: 0x5B },
  { label: 'Archer in Iron Ballista', value: 0x5C },
  { label: 'Archer in Killer Ballista', value: 0x5D },
  { label: 'Empty Ballista', value: 0x5E },
  { label: 'Empty Iron Ballista', value: 0x5F },
  { label: 'Empty Killer Ballista', value: 0x60 },
  { label: 'Empty (Make a custom class!)', value: 0x61 },
  { label: 'Empty (Make a custom class!)', value: 0x62 },
  { label: 'Empty (Make a custom class!)', value: 0x63 },
];

export const PortraitList = [
  { label: 'No portrait/Generic enemy', value: 0x00 },
  { label: 'Question mark circle on a shadowed box', value: 0x01 },
  { label: 'Eliwood', value: 0x02 },
  { label: 'Angry Eliwood', value: 0x03 },
  { label: 'Sad Eliwood', value: 0x04 },
  { label: 'Eliwood dressed as a commoner', value: 0x05 },
  { label: 'Eliwood (Looking at you)', value: 0x06 },
  { label: 'Eliwood dressed as a commoner (Looking at you)', value: 0x07 },
  { label: 'Eliwood in noble clothing', value: 0x08 },
  { label: 'Happy Eliwood in noble clothing', value: 0x09 },
  { label: 'Happy Eliwood', value: 0x0A },
  { label: 'Old Eliwood', value: 0x0B },
  { label: 'Hector', value: 0x0C },
  { label: 'Angry Hector', value: 0x0D },
  { label: 'Sad Hector', value: 0x0E },
  { label: 'Hector dressed as a commoner', value: 0x0F },
  { label: 'Hector dressed as a commoner (Looking at you)', value: 0x10 },
  { label: 'Angry Hector dressed as a commoner', value: 0x11 },
  { label: 'Hector in noble clothing', value: 0x12 },
  { label: 'Hector in noble clothing (Looking at you)', value: 0x13 },
  { label: 'Hector (Looking at you)', value: 0x14 },
  { label: 'Old Hector (beard included)', value: 0x15 },
  { label: 'Lyn', value: 0x16 },
  { label: 'Lyn in deep thought', value: 0x17 },
  { label: 'Sad Lyn', value: 0x18 },
  { label: 'Lyn dressed as a commoner', value: 0x19 },
  { label: 'Lyn (Looking at you)', value: 0x1A },
  { label: 'Athos', value: 0x1B },
  { label: 'Ninian', value: 0x1C },
  { label: 'Possessed Ninian', value: 0x1D },
  { label: 'Sad Ninian', value: 0x1E },
  { label: 'Hawkeye', value: 0x1F },
  { label: 'Matthew', value: 0x20 },
  { label: 'Jaffar', value: 0x21 },
  { label: 'Angry Jaffar', value: 0x22 },
  { label: 'Raven', value: 0x23 },
  { label: 'Geitz', value: 0x24 },
  { label: 'Legault', value: 0x25 },
  { label: 'Karel', value: 0x26 },
  { label: 'Dorcas', value: 0x27 },
  { label: 'Bartre', value: 0x28 },
  { label: 'Oswin', value: 0x29 },
  { label: 'Dart', value: 0x2A },
  { label: 'Wil', value: 0x2B },
  { label: 'Guy', value: 0x2C },
  { label: 'Karla', value: 0x2D },
  { label: 'Rath', value: 0x2E },
  { label: 'Kent', value: 0x2F },
  { label: 'Sain', value: 0x30 },
  { label: 'Lowen', value: 0x31 },
  { label: 'Marcus', value: 0x32 },
  { label: 'Florina', value: 0x33 },
  { label: 'Shy Florina', value: 0x34 },
  { label: 'Fiora', value: 0x35 },
  { label: 'Heath', value: 0x36 },
  { label: 'Vaida', value: 0x37 },
  { label: 'Erk', value: 0x38 },
  { label: 'Nino', value: 0x39 },
  { label: 'Pent', value: 0x3A },
  { label: 'Louise', value: 0x3B },
  { label: 'Canas', value: 0x3C },
  { label: 'Lucius', value: 0x3D },
  { label: 'Serra', value: 0x3E },
  { label: 'Priscilla', value: 0x3F },
  { label: 'Farina', value: 0x40 },
  { label: 'Nils', value: 0x41 },
  { label: 'Sad Nils', value: 0x42 },
  { label: 'Possessed Nils', value: 0x43 },
  { label: 'Nils deep in thought', value: 0x44 },
  { label: 'Renault', value: 0x45 },
  { label: 'Isadora', value: 0x46 },
  { label: 'Harken', value: 0x47 },
  { label: 'Rebecca', value: 0x48 },
  { label: 'Wallace', value: 0x49 },
  { label: 'Merlinus', value: 0x4A },
  { label: 'Hannah (Old fortune teller)', value: 0x4B },
  { label: 'Elenora', value: 0x4C },
  { label: 'Serious Elenora', value: 0x4D },
  { label: 'Uther', value: 0x4E },
  { label: 'Elbert', value: 0x4F },
  { label: 'Fargus', value: 0x50 },
  { label: 'Zephiel', value: 0x51 },
  { label: 'Guinevere', value: 0x52 },
  { label: 'Desmond', value: 0x53 },
  { label: 'Hellene', value: 0x54 },
  { label: 'Happy Hellene', value: 0x55 },
  { label: 'Murdock', value: 0x56 },
  { label: 'Leila', value: 0x57 },
  { label: 'Leila looking down with her eyes closed', value: 0x58 },
  { label: 'Hausen (Lyn\'s grandfather)', value: 0x59 },
  { label: 'Jan', value: 0x5A },
  { label: 'Natalie', value: 0x5B },
  { label: 'Bramimond', value: 0x5C },
  { label: 'Roland', value: 0x5D },
  { label: 'Durban', value: 0x5E },
  { label: 'Evil-faced Nergal (masked)', value: 0x5F },
  { label: 'Evil-faced Nergal #2 (masked)', value: 0x60 },
  { label: 'Nergal (Generic/unmasked)', value: 0x61 },
  { label: 'Eil Nergal (unmasked)', value: 0x62 },
  { label: 'Sonia', value: 0x63 },
  { label: 'Brendan', value: 0x64 },
  { label: 'Lloyd', value: 0x65 },
  { label: 'Linus', value: 0x66 },
  { label: 'Limstella', value: 0x67 },
  { label: 'Ephidel', value: 0x68 },
  { label: 'Ephidel (hooded)', value: 0x69 },
  { label: 'Darin', value: 0x6A },
  { label: 'Erik', value: 0x6B },
  { label: 'Helman', value: 0x6C },
  { label: 'Marquess Araphen', value: 0x6D },
  { label: 'Groznyi', value: 0x6E },
  { label: 'Wire', value: 0x6F },
  { label: 'Zagan', value: 0x70 },
  { label: 'Boies', value: 0x71 },
  { label: 'Sealen', value: 0x72 },
  { label: 'Bauker', value: 0x73 },
  { label: 'Bernard', value: 0x74 },
  { label: 'Damian', value: 0x75 },
  { label: 'Zoldam', value: 0x76 },
  { label: 'Uhai', value: 0x77 },
  { label: 'Aion', value: 0x78 },
  { label: 'Georg', value: 0x79 },
  { label: 'Cameron', value: 0x7A },
  { label: 'Oleg', value: 0x7B },
  { label: 'Eubans', value: 0x7C },
  { label: 'Kishuna', value: 0x7D },
  { label: 'Paul', value: 0x7E },
  { label: 'Jasmine', value: 0x7F },
  { label: 'Pascal', value: 0x80 },
  { label: 'Kenneth', value: 0x81 },
  { label: 'Jerme', value: 0x82 },
  { label: 'Maxime', value: 0x83 },
  { label: 'Ursula', value: 0x84 },
  { label: 'Teodor', value: 0x85 },
  { label: 'Denning', value: 0x86 },
  { label: 'Kaim', value: 0x87 },
  { label: 'Batta', value: 0x88 },
  { label: 'Zugu', value: 0x89 },
  { label: 'Glass', value: 0x8A },
  { label: 'Migal', value: 0x8B },
  { label: 'Carjiga', value: 0x8C },
  { label: 'Bug', value: 0x8D },
  { label: 'Puzon', value: 0x8E },
  { label: 'Bool', value: 0x8F },
  { label: 'Heintz', value: 0x90 },
  { label: 'Beyard', value: 0x91 },
  { label: 'Yogi', value: 0x92 },
  { label: 'Eagler', value: 0x93 },
  { label: 'Lundgren', value: 0x94 },
  { label: 'Unlisted (Looks like a blue haired generic mercenary boss)', value: 0x95 },
  { label: 'Lloyd (Morph)', value: 0x96 },
  { label: 'Linus (Morph)', value: 0x97 },
  { label: 'Brendan (Morph)', value: 0x98 },
  { label: 'Uhai (Morph)', value: 0x99 },
  { label: 'Ursula (Morph)', value: 0x9A },
  { label: 'Kenneth (Morph)', value: 0x9B },
  { label: 'Darin (Morph)', value: 0x9C },
  { label: 'Jerme (Morph)', value: 0x9D },
  { label: 'Roy (Young)', value: 0x9E },
  { label: 'Lilina (Young)', value: 0x9F },
  { label: 'Fa', value: 0xA0 },
  { label: 'Sophia', value: 0xA1 },
  { label: 'Bishop that gives Lyn the Mani Katti', value: 0xA2 },
  { label: 'Caelin servant that talks to you at the end of chapter 10', value: 0xA3 },
  { label: 'Caelin servant that talks to you at the end of chapter 10 looking relieved', value: 0xA4 },
  { label: 'Generic Blue Soldier', value: 0xA5 },
  { label: 'Generic Red Soldier', value: 0xA6 },
  { label: 'Generic Gray Soldier', value: 0xA7 },
  { label: 'Generic Bronze Soldier', value: 0xA8 },
  { label: 'Random male citizen (Balding man with moustache)', value: 0xA9 },
  { label: 'Random male citizen (Green hair and moustache)', value: 0xAA },
  { label: 'Random male citizen (The above, recolored with brown hair)', value: 0xAB },
  { label: 'Random male citizen (Scrawny, older man with a moustache)', value: 0xAC },
  { label: 'Random female citizen (Older lady with her hair in a bun)', value: 0xAD },
  { label: 'Random female citizen (Younger lady with freckles)', value: 0xAE },
  { label: 'Random female citizen (Younger lady with long hair)', value: 0xAF },
  { label: 'Random male citizen (Younger man with short hair)', value: 0xB0 },
  { label: 'Random male citizen (Younger man with freckles)', value: 0xB1 },
  { label: 'Random male citizen (Boy with short blond hair)', value: 0xB2 },
  { label: 'Random male citizen (Boy with short ruddy [Reddish orange] hair)', value: 0xB3 },
  { label: 'Random female citizen (Little girl with brown pigtails)', value: 0xB4 },
  { label: 'Random female citizen (Younger lady with long orange hair)', value: 0xB5 },
  { label: 'Random male citizen (Old man with a short beard)', value: 0xB6 },
  { label: 'Random female citizen (Old lady with a hood and grey hair)', value: 0xB7 },
  { label: 'Random female citizen (same as above, only recolored, and with brown hair)', value: 0xB8 },
  { label: 'Random male citizen (Younger with orange hair)', value: 0xB9 },
  { label: 'Random enemy assassin/Black fang member', value: 0xBA },
  { label: 'Random enemy hero/thug (looks like it could be a boss, but no name was attached to it)', value: 0xBB },
  { label: 'Random enemy brigand (headband and buckteeth)', value: 0xBC },
  { label: 'Random enemy brigand (Sideburns)', value: 0xBD },
  { label: 'Enemy Myrmidon card', value: 0xBE },
  { label: 'Enemy Swordmaster card', value: 0xBF },
  { label: 'Enemy Fighter card', value: 0xC0 },
  { label: 'Enemy Warrior card', value: 0xC1 },
  { label: 'Enemy Knight card', value: 0xC2 },
  { label: 'Enemy General card', value: 0xC3 },
  { label: 'Enemy Archer card', value: 0xC4 },
  { label: 'Enemy Sniper card', value: 0xC5 },
  { label: 'Enemy Cleric card', value: 0xC6 },
  { label: 'Enemy Bishop card', value: 0xC7 },
  { label: 'Enemy Mage card', value: 0xC8 },
  { label: 'Enemy Sage card', value: 0xC9 },
  { label: 'Enemy Shaman card', value: 0xCA },
  { label: 'Enemy Druid card', value: 0xCB },
  { label: 'Enemy Cavalier card', value: 0xCC },
  { label: 'Enemy Paladin card', value: 0xCD },
  { label: 'Enemy Troubadour card', value: 0xCE },
  { label: 'Enemy Valkyrie card', value: 0xCF },
  { label: 'Enemy Nomad card', value: 0xD0 },
  { label: 'Enemy Nomadic Trooper card', value: 0xD1 },
  { label: 'Enemy Pegasus card', value: 0xD2 },
  { label: 'Enemy Falcon Knight card', value: 0xD3 },
  { label: 'Enemy Wywern Knight card', value: 0xD4 },
  { label: 'Enemy Wywern Lord card', value: 0xD5 },
  { label: 'Enemy Soldier card', value: 0xD6 },
  { label: 'Enemy Brigand card', value: 0xD7 },
  { label: 'Enemy Pirate card', value: 0xD8 },
  { label: 'Enemy Berserker card', value: 0xD9 },
  { label: 'Enemy Thief card', value: 0xDA },
  { label: 'Enemy Mamkute card', value: 0xDB },
  { label: 'Enemy Mercenary card', value: 0xDC },
  { label: 'Enemy Hero card', value: 0xDD },
  { label: 'Enemy Fire Dragon card', value: 0xDE },
  { label: 'Anna', value: 0xDF },
  { label: 'Jake', value: 0xE0 },
  { label: 'Armory man (not a full sized portrait)', value: 0xE1 },
  { label: 'Arena man (not a full sized portrait)', value: 0xE2 },
  { label: 'Shop girl (not a full sized portrait)', value: 0xE3 },
  { label: 'Anna (Secret shop)', value: 0xE4 },
];

export const MiniProtrait = [
  { label: 'Default', value: 0x00 },
  { label: 'Dragon', value: 0x01 },
  { label: 'Ostia/Caelin/Civilian', value: 0x02 },
  { label: 'Black Fang/Morph/Bandit', value: 0x03 },
  { label: '???', value: 0x06 },
];

export const Affinity = [
  { label: 'None', value: 0x00 },
  { label: 'Fire', value: 0x01 },
  { label: 'Thunder', value: 0x02 },
  { label: 'Wind', value: 0x03 },
  { label: 'Water', value: 0x04 },
  { label: 'Dark', value: 0x05 },
  { label: 'Light', value: 0x06 },
  { label: 'Anima', value: 0x07 },
];

export const WeaponRank = [
  { label: 'None', value: 0x00 },
  { label: 'E', value: 0x01 },
  { label: 'D', value: 0x1F },
  { label: 'C', value: 0x47 },
  { label: 'B', value: 0x79 },
  { label: 'A', value: 0xB5 },
  { label: 'S', value: 0xFB },
];

export const CharacterPalettes = [
  { label: 'Default Generic Colours', value: 0x00 },
  { label: 'Lyn unpromoted', value: 0x01 },
  { label: 'Rebecca unpromoted', value: 0x02 },
  { label: 'Wil unpromoted', value: 0x03 },
  { label: 'Boies', value: 0x04 },
  { label: 'Bool', value: 0x05 },
  { label: 'Bauker', value: 0x06 },
  { label: 'Eagler', value: 0x07 },
  { label: 'Oswin unpromoted', value: 0x08 },
  { label: 'Wallace unpromoted', value: 0x09 },
  { label: 'Wire', value: 0x0A },
  { label: 'Yogi', value: 0x0B },
  { label: 'Jaffar', value: 0x0C },
  { label: 'Jerme', value: 0x0D },
  { label: 'Legault promoted', value: 0x0E },
  { label: 'Matthew promoted', value: 0x0F },
  { label: 'Batta', value: 0x10 },
  { label: 'Bug', value: 0x11 },
  { label: 'Carjiga', value: 0x12 },
  { label: 'Migal', value: 0x13 },
  { label: 'Zagan', value: 0x14 },
  { label: 'Zugu', value: 0x15 },
  { label: 'Hawkeye', value: 0x16 },
  { label: 'Serra promoted', value: 0x17 },
  { label: 'Kenneth', value: 0x18 },
  { label: 'Renault', value: 0x19 },
  { label: 'Lucius promoted', value: 0x1A },
  { label: 'Lyn promoted', value: 0x1B },
  { label: 'Harken', value: 0x1C },
  { label: 'Kaim', value: 0x1D },
  { label: 'Raven promoted', value: 0x1E },
  { label: 'Linus', value: 0x1F },
  { label: 'Nils', value: 0x20 },
  { label: 'Dart promoted', value: 0x21 },
  { label: 'Fargus', value: 0x22 },
  { label: 'Georg', value: 0x23 },
  { label: 'Ninian', value: 0x24 },
  { label: 'Heath unpromoted', value: 0x25 },
  { label: 'Heath promoted', value: 0x26 },
  { label: 'Vaida', value: 0x27 },
  { label: 'Nergal', value: 0x28 },
  { label: 'Canas promoted', value: 0x29 },
  { label: 'Vaida', value: 0x2A },
  { label: 'Eliwood unpromoted', value: 0x2B },
  { label: 'Farina promoted', value: 0x2C },
  { label: 'Fiora promoted', value: 0x2D },
  { label: 'Florina promoted', value: 0x2E },
  { label: 'Bartre unpromoted', value: 0x2F },
  { label: 'Dorcas unpromoted', value: 0x30 },
  { label: 'Bernard', value: 0x31 },
  { label: 'Darin', value: 0x32 },
  { label: 'Oswin promoted', value: 0x33 },
  { label: 'Wallace promoted', value: 0x34 },
  { label: 'Lundgren', value: 0x35 },
  { label: 'Hector promoted', value: 0x36 },
  { label: 'Hector unpromoted', value: 0x37 },
  { label: 'Eliwood promoted', value: 0x38 },
  { label: 'Nino unpromoted', value: 0x39 },
  { label: 'Erk unpromoted', value: 0x3A },
  { label: 'Beyard', value: 0x3B },
  { label: 'Glass', value: 0x3C },
  { label: 'Raven unpromoted', value: 0x3D },
  { label: 'Puzon', value: 0x3E },
  { label: 'Lucius unpromoted', value: 0x3F },
  { label: 'Guy unpromoted', value: 0x40 },
  { label: 'Rath unpromoted', value: 0x41 },
  { label: 'Sealen', value: 0x42 },
  { label: 'Rath promoted', value: 0x43 },
  { label: 'Uhai', value: 0x44 },
  { label: 'Isadora', value: 0x45 },
  { label: 'Cameron', value: 0x46 },
  { label: 'Damian', value: 0x47 },
  { label: 'Eubans', value: 0x48 },
  { label: 'Kent promoted', value: 0x49 },
  { label: 'Lowen promoted', value: 0x4A },
  { label: 'Marcus', value: 0x4B },
  { label: 'Maxime', value: 0x4C },
  { label: 'Pascal', value: 0x4D },
  { label: 'Sain promoted', value: 0x4E },
  { label: 'Farina unpromoted', value: 0x4F },
  { label: 'Fiora unpromoted', value: 0x50 },
  { label: 'Florina unpromoted', value: 0x51 },
  { label: 'Dart unpromoted', value: 0x52 },
  { label: 'Serra unpromoted', value: 0x53 },
  { label: 'Limstella', value: 0x54 },
  { label: 'Nino promoted', value: 0x55 },
  { label: 'Sonia', value: 0x56 },
  { label: 'Aion', value: 0x57 },
  { label: 'Erk promoted', value: 0x58 },
  { label: 'Pent', value: 0x59 },
  { label: 'Canas unpromoted', value: 0x5A },
  { label: 'Heintz', value: 0x5B },
  { label: 'Zoldam', value: 0x5C },
  { label: 'Louise', value: 0x5D },
  { label: 'Rebecca promoted', value: 0x5E },
  { label: 'Denning', value: 0x5F },
  { label: 'Wil promoted', value: 0x60 },
  { label: 'Erik', value: 0x61 },
  { label: 'Kent unpromoted', value: 0x62 },
  { label: 'Lowen unpromoted', value: 0x63 },
  { label: 'Sain unpromoted', value: 0x64 },
  { label: 'Athos', value: 0x65 },
  { label: 'Karla', value: 0x66 },
  { label: 'Guy promoted', value: 0x67 },
  { label: 'Karel promoted', value: 0x68 },
  { label: 'Lloyd', value: 0x69 },
  { label: 'Leila', value: 0x6A },
  { label: 'Legault unpromoted', value: 0x6B },
  { label: 'Matthew unpromoted', value: 0x6C },
  { label: 'Priscilla unpromoted', value: 0x6D },
  { label: 'Priscilla promoted', value: 0x6E },
  { label: 'Ursula', value: 0x6F },
  { label: 'Bartre promoted', value: 0x70 },
  { label: 'Brendan', value: 0x71 },
  { label: 'Dorcas promoted', value: 0x72 },
  { label: 'Geitz promoted', value: 0x73 },
  { label: 'Jasmine', value: 0x74 },
  { label: 'Oleg', value: 0x75 },
  { label: 'Paul', value: 0x76 },
  { label: 'Kishuna', value: 0x77 },
  { label: 'Groznyi', value: 0x78 },
  { label: '-', value: 0x79 },
  { label: '-', value: 0x7A },
  { label: '-', value: 0x7B },
  { label: '-', value: 0x7C },
  { label: '-', value: 0x7D },
  { label: '-', value: 0x7E },
  { label: '-', value: 0x7F },
  { label: '-', value: 0x80 },
  { label: '-', value: 0x81 },
  { label: '-', value: 0x82 },
  { label: '-', value: 0x83 },
  { label: '-', value: 0x84 },
  { label: '-', value: 0x85 },
  { label: '-', value: 0x86 },
  { label: '-', value: 0x87 },
  { label: '-', value: 0x88 },
  { label: '-', value: 0x89 },
  { label: '-', value: 0x8A },
  { label: '-', value: 0x8B },
  { label: '-', value: 0x8C },
  { label: '-', value: 0x8D },
  { label: '-', value: 0x8E },
  { label: '-', value: 0x8F },
  { label: '-', value: 0x90 },
  { label: '-', value: 0x91 },
  { label: '-', value: 0x92 },
  { label: '-', value: 0x93 },
  { label: '-', value: 0x94 },
  { label: '-', value: 0x95 },
  { label: '-', value: 0x96 },
  { label: '-', value: 0x97 },
  { label: '-', value: 0x98 },
  { label: '-', value: 0x99 },
  { label: '-', value: 0x9A },
  { label: '-', value: 0x9B },
  { label: '-', value: 0x9C },
  { label: '-', value: 0x9D },
  { label: '-', value: 0x9E },
  { label: '-', value: 0x9F },
  { label: '-', value: 0xA0 },
  { label: '-', value: 0xA1 },
  { label: '-', value: 0xA2 },
  { label: '-', value: 0xA3 },
  { label: '-', value: 0xA4 },
  { label: '-', value: 0xA5 },
  { label: '-', value: 0xA6 },
  { label: '-', value: 0xA7 },
  { label: '-', value: 0xA8 },
  { label: '-', value: 0xA9 },
  { label: '-', value: 0xAA },
  { label: '-', value: 0xAB },
  { label: '-', value: 0xAC },
  { label: '-', value: 0xAD },
  { label: '-', value: 0xAE },
  { label: '-', value: 0xAF },
  { label: '-', value: 0xB0 },
  { label: '-', value: 0xB1 },
  { label: '-', value: 0xB2 },
  { label: '-', value: 0xB3 },
  { label: '-', value: 0xB4 },
  { label: '-', value: 0xB5 },
  { label: '-', value: 0xB6 },
  { label: '-', value: 0xB7 },
  { label: '-', value: 0xB8 },
  { label: '-', value: 0xB9 },
  { label: '-', value: 0xBA },
  { label: '-', value: 0xBB },
  { label: '-', value: 0xBC },
  { label: '-', value: 0xBD },
  { label: '-', value: 0xBE },
  { label: '-', value: 0xBF },
  { label: '-', value: 0xC0 },
  { label: '-', value: 0xC1 },
  { label: '-', value: 0xC2 },
  { label: '-', value: 0xC3 },
  { label: '-', value: 0xC4 },
  { label: '-', value: 0xC5 },
  { label: '-', value: 0xC6 },
  { label: '-', value: 0xC7 },
  { label: '-', value: 0xC8 },
  { label: '-', value: 0xC9 },
  { label: '-', value: 0xCA },
  { label: '-', value: 0xCB },
  { label: '-', value: 0xCC },
  { label: '-', value: 0xCD },
  { label: '-', value: 0xCE },
  { label: '-', value: 0xCF },
  { label: '-', value: 0xD0 },
  { label: '-', value: 0xD1 },
  { label: '-', value: 0xD2 },
  { label: '-', value: 0xD3 },
  { label: '-', value: 0xD4 },
  { label: '-', value: 0xD5 },
  { label: '-', value: 0xD6 },
  { label: '-', value: 0xD7 },
  { label: '-', value: 0xD8 },
  { label: '-', value: 0xD9 },
  { label: '-', value: 0xDA },
  { label: '-', value: 0xDB },
  { label: '-', value: 0xDC },
  { label: '-', value: 0xDD },
  { label: '-', value: 0xDE },
  { label: '-', value: 0xDF },
  { label: '-', value: 0xE0 },
  { label: '-', value: 0xE1 },
  { label: '-', value: 0xE2 },
  { label: '-', value: 0xE3 },
  { label: '-', value: 0xE4 },
  { label: '-', value: 0xE5 },
  { label: '-', value: 0xE6 },
  { label: '-', value: 0xE7 },
  { label: '-', value: 0xE8 },
  { label: '-', value: 0xE9 },
  { label: '-', value: 0xEA },
  { label: '-', value: 0xEB },
  { label: '-', value: 0xEC },
  { label: '-', value: 0xED },
  { label: '-', value: 0xEE },
  { label: '-', value: 0xEF },
  { label: '-', value: 0xF0 },
  { label: '-', value: 0xF1 },
  { label: '-', value: 0xF2 },
  { label: '-', value: 0xF3 },
  { label: '-', value: 0xF4 },
  { label: '-', value: 0xF5 },
  { label: '-', value: 0xF6 },
  { label: '-', value: 0xF7 },
  { label: '-', value: 0xF8 },
  { label: '-', value: 0xF9 },
  { label: '-', value: 0xFA },
  { label: '-', value: 0xFB },
  { label: '-', value: 0xFC },
  { label: '-', value: 0xFD },
  { label: '-', value: 0xFE },
  { label: '-', value: 0xFF },
];

export const CustomBattleSprites = [
  { label: 'Default', value: 0x00 },
  { label: 'Lucius (Monk)', value: 0x01 },
  { label: 'Lucius (Bishop)', value: 0x02 },
  { label: 'Linus (1)', value: 0x03 },
  { label: 'Linus (2)', value: 0x04 },
  { label: 'Linus (3)', value: 0x05 },
  { label: 'Lloyd (1)', value: 0x06 },
  { label: 'Lloyd (2)', value: 0x07 },
  { label: 'Lloyd (3)', value: 0x08 },
  { label: 'Isadora', value: 0x09 },
  { label: 'Nino (Sage)', value: 0x0A },
  { label: 'Legault (Thief)', value: 0x0B },
  { label: 'Legault (Assassin)', value: 0x0C },
  { label: 'Raven (Hero)', value: 0x0D },
  { label: 'Guy (Swordfighter)', value: 0x0E },
  { label: 'Guy (Swordmaster)', value: 0x0F },
  { label: 'Hawkeye', value: 0x10 },
  { label: '-', value: 0x11 },
  { label: '-', value: 0x12 },
  { label: '-', value: 0x13 },
  { label: '-', value: 0x14 },
  { label: '-', value: 0x15 },
  { label: '-', value: 0x16 },
  { label: '-', value: 0x17 },
  { label: '-', value: 0x18 },
  { label: '-', value: 0x19 },
  { label: '-', value: 0x1A },
  { label: '-', value: 0x1B },
  { label: '-', value: 0x1C },
  { label: '-', value: 0x1D },
  { label: '-', value: 0x1E },
  { label: '-', value: 0x1F },
  { label: '-', value: 0x20 },
  { label: '-', value: 0x21 },
  { label: '-', value: 0x22 },
  { label: '-', value: 0x23 },
  { label: '-', value: 0x24 },
  { label: '-', value: 0x25 },
  { label: '-', value: 0x26 },
  { label: '-', value: 0x27 },
  { label: '-', value: 0x28 },
  { label: '-', value: 0x29 },
  { label: '-', value: 0x2A },
  { label: '-', value: 0x2B },
  { label: '-', value: 0x2C },
  { label: '-', value: 0x2D },
  { label: '-', value: 0x2E },
  { label: '-', value: 0x2F },
  { label: '-', value: 0x30 },
  { label: '-', value: 0x31 },
  { label: '-', value: 0x32 },
  { label: '-', value: 0x33 },
  { label: '-', value: 0x34 },
  { label: '-', value: 0x35 },
  { label: '-', value: 0x36 },
  { label: '-', value: 0x37 },
  { label: '-', value: 0x38 },
  { label: '-', value: 0x39 },
  { label: '-', value: 0x3A },
  { label: '-', value: 0x3B },
  { label: '-', value: 0x3C },
  { label: '-', value: 0x3D },
  { label: '-', value: 0x3E },
  { label: '-', value: 0x3F },
  { label: '-', value: 0x40 },
  { label: '-', value: 0x41 },
  { label: '-', value: 0x42 },
  { label: '-', value: 0x43 },
  { label: '-', value: 0x44 },
  { label: '-', value: 0x45 },
  { label: '-', value: 0x46 },
  { label: '-', value: 0x47 },
  { label: '-', value: 0x48 },
  { label: '-', value: 0x49 },
  { label: '-', value: 0x4A },
  { label: '-', value: 0x4B },
  { label: '-', value: 0x4C },
  { label: '-', value: 0x4D },
  { label: '-', value: 0x4E },
  { label: '-', value: 0x4F },
  { label: '-', value: 0x50 },
  { label: '-', value: 0x51 },
  { label: '-', value: 0x52 },
  { label: '-', value: 0x53 },
  { label: '-', value: 0x54 },
  { label: '-', value: 0x55 },
  { label: '-', value: 0x56 },
  { label: '-', value: 0x57 },
  { label: '-', value: 0x58 },
  { label: '-', value: 0x59 },
  { label: '-', value: 0x5A },
  { label: '-', value: 0x5B },
  { label: '-', value: 0x5C },
  { label: '-', value: 0x5D },
  { label: '-', value: 0x5E },
  { label: '-', value: 0x5F },
  { label: '-', value: 0x60 },
  { label: '-', value: 0x61 },
  { label: '-', value: 0x62 },
  { label: '-', value: 0x63 },
  { label: '-', value: 0x64 },
  { label: '-', value: 0x65 },
  { label: '-', value: 0x66 },
  { label: '-', value: 0x67 },
  { label: '-', value: 0x68 },
  { label: '-', value: 0x69 },
  { label: '-', value: 0x6A },
  { label: '-', value: 0x6B },
  { label: '-', value: 0x6C },
  { label: '-', value: 0x6D },
  { label: '-', value: 0x6E },
  { label: '-', value: 0x6F },
  { label: '-', value: 0x70 },
  { label: '-', value: 0x71 },
  { label: '-', value: 0x72 },
  { label: '-', value: 0x73 },
  { label: '-', value: 0x74 },
  { label: '-', value: 0x75 },
  { label: '-', value: 0x76 },
  { label: '-', value: 0x77 },
  { label: '-', value: 0x78 },
  { label: '-', value: 0x79 },
  { label: '-', value: 0x7A },
  { label: '-', value: 0x7B },
  { label: '-', value: 0x7C },
  { label: '-', value: 0x7D },
  { label: '-', value: 0x7E },
  { label: '-', value: 0x7F },
  { label: '-', value: 0x80 },
  { label: '-', value: 0x81 },
  { label: '-', value: 0x82 },
  { label: '-', value: 0x83 },
  { label: '-', value: 0x84 },
  { label: '-', value: 0x85 },
  { label: '-', value: 0x86 },
  { label: '-', value: 0x87 },
  { label: '-', value: 0x88 },
  { label: '-', value: 0x89 },
  { label: '-', value: 0x8A },
  { label: '-', value: 0x8B },
  { label: '-', value: 0x8C },
  { label: '-', value: 0x8D },
  { label: '-', value: 0x8E },
  { label: '-', value: 0x8F },
  { label: '-', value: 0x90 },
  { label: '-', value: 0x91 },
  { label: '-', value: 0x92 },
  { label: '-', value: 0x93 },
  { label: '-', value: 0x94 },
  { label: '-', value: 0x95 },
  { label: '-', value: 0x96 },
  { label: '-', value: 0x97 },
  { label: '-', value: 0x98 },
  { label: '-', value: 0x99 },
  { label: '-', value: 0x9A },
  { label: '-', value: 0x9B },
  { label: '-', value: 0x9C },
  { label: '-', value: 0x9D },
  { label: '-', value: 0x9E },
  { label: '-', value: 0x9F },
  { label: '-', value: 0xA0 },
  { label: '-', value: 0xA1 },
  { label: '-', value: 0xA2 },
  { label: '-', value: 0xA3 },
  { label: '-', value: 0xA4 },
  { label: '-', value: 0xA5 },
  { label: '-', value: 0xA6 },
  { label: '-', value: 0xA7 },
  { label: '-', value: 0xA8 },
  { label: '-', value: 0xA9 },
  { label: '-', value: 0xAA },
  { label: '-', value: 0xAB },
  { label: '-', value: 0xAC },
  { label: '-', value: 0xAD },
  { label: '-', value: 0xAE },
  { label: '-', value: 0xAF },
  { label: '-', value: 0xB0 },
  { label: '-', value: 0xB1 },
  { label: '-', value: 0xB2 },
  { label: '-', value: 0xB3 },
  { label: '-', value: 0xB4 },
  { label: '-', value: 0xB5 },
  { label: '-', value: 0xB6 },
  { label: '-', value: 0xB7 },
  { label: '-', value: 0xB8 },
  { label: '-', value: 0xB9 },
  { label: '-', value: 0xBA },
  { label: '-', value: 0xBB },
  { label: '-', value: 0xBC },
  { label: '-', value: 0xBD },
  { label: '-', value: 0xBE },
  { label: '-', value: 0xBF },
  { label: '-', value: 0xC0 },
  { label: '-', value: 0xC1 },
  { label: '-', value: 0xC2 },
  { label: '-', value: 0xC3 },
  { label: '-', value: 0xC4 },
  { label: '-', value: 0xC5 },
  { label: '-', value: 0xC6 },
  { label: '-', value: 0xC7 },
  { label: '-', value: 0xC8 },
  { label: '-', value: 0xC9 },
  { label: '-', value: 0xCA },
  { label: '-', value: 0xCB },
  { label: '-', value: 0xCC },
  { label: '-', value: 0xCD },
  { label: '-', value: 0xCE },
  { label: '-', value: 0xCF },
  { label: '-', value: 0xD0 },
  { label: '-', value: 0xD1 },
  { label: '-', value: 0xD2 },
  { label: '-', value: 0xD3 },
  { label: '-', value: 0xD4 },
  { label: '-', value: 0xD5 },
  { label: '-', value: 0xD6 },
  { label: '-', value: 0xD7 },
  { label: '-', value: 0xD8 },
  { label: '-', value: 0xD9 },
  { label: '-', value: 0xDA },
  { label: '-', value: 0xDB },
  { label: '-', value: 0xDC },
  { label: '-', value: 0xDD },
  { label: '-', value: 0xDE },
  { label: '-', value: 0xDF },
  { label: '-', value: 0xE0 },
  { label: '-', value: 0xE1 },
  { label: '-', value: 0xE2 },
  { label: '-', value: 0xE3 },
  { label: '-', value: 0xE4 },
  { label: '-', value: 0xE5 },
  { label: '-', value: 0xE6 },
  { label: '-', value: 0xE7 },
  { label: '-', value: 0xE8 },
  { label: '-', value: 0xE9 },
  { label: '-', value: 0xEA },
  { label: '-', value: 0xEB },
  { label: '-', value: 0xEC },
  { label: '-', value: 0xED },
  { label: '-', value: 0xEE },
  { label: '-', value: 0xEF },
  { label: '-', value: 0xF0 },
  { label: '-', value: 0xF1 },
  { label: '-', value: 0xF2 },
  { label: '-', value: 0xF3 },
  { label: '-', value: 0xF4 },
  { label: '-', value: 0xF5 },
  { label: '-', value: 0xF6 },
  { label: '-', value: 0xF7 },
  { label: '-', value: 0xF8 },
  { label: '-', value: 0xF9 },
  { label: '-', value: 0xFA },
  { label: '-', value: 0xFB },
  { label: '-', value: 0xFC },
  { label: '-', value: 0xFD },
  { label: '-', value: 0xFE },
  { label: '-', value: 0xFF },
];

export const Ability1 = [
  { label: 'None', value: 0x00 },
  { label: 'Mounted Aid system', value: 0x01 },
  { label: 'Move Again', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Steal', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'Thief Key', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Dance', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Play', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Critical +15', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Ballistas', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'All of the above', value: 0xFF },
];

export const Ability2 = [
  { label: 'None', value: 0x00 },
  { label: 'Promoted', value: 0x01 },
  { label: 'Supply Depot', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Mounted icon(next to aid)', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'Dragon Knight icon', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Pegasus Knight icon', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Lord', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Female', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Boss', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'All of the above', value: 0xFF },
];

export const Ability3 = [
  { label: 'None', value: 0x00 },
  { label: 'Unused weapon lock', value: 0x01 },
  { label: 'Wo Dao weapon lock', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Dragonstone weapon lock', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'All Morphs, Boss Vaida', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Prevents controlling', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Triangle attack', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Different Triangle attack', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Qlitches, don\'t use', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: '0xFF', value: 0xFF },
];

export const Ability4 = [
  { label: 'None', value: 0x00 },
  { label: 'Opponent doesn\'t gain experience', value: 0x01 },
  { label: 'Lethality', value: 0x02 },
  { label: '0x03', value: 0x03 },
  { label: 'Magic Sealing', value: 0x04 },
  { label: '0x05', value: 0x05 },
  { label: '0x06', value: 0x06 },
  { label: '0x07', value: 0x07 },
  { label: 'Last item droppable', value: 0x08 },
  { label: '0x09', value: 0x09 },
  { label: '0x0A', value: 0x0A },
  { label: '0x0B', value: 0x0B },
  { label: '0x0C', value: 0x0C },
  { label: '0x0D', value: 0x0D },
  { label: '0x0E', value: 0x0E },
  { label: '0x0F', value: 0x0F },
  { label: 'Unlock Rapier/Durandal', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '0x12', value: 0x12 },
  { label: '0x13', value: 0x13 },
  { label: '0x14', value: 0x14 },
  { label: '0x15', value: 0x15 },
  { label: '0x16', value: 0x16 },
  { label: '0x17', value: 0x17 },
  { label: '0x18', value: 0x18 },
  { label: '0x19', value: 0x19 },
  { label: '0x1A', value: 0x1A },
  { label: '0x1B', value: 0x1B },
  { label: '0x1C', value: 0x1C },
  { label: '0x1D', value: 0x1D },
  { label: '0x1E', value: 0x1E },
  { label: '0x1F', value: 0x1F },
  { label: 'Unlock Wolf Beil/Armads', value: 0x20 },
  { label: '0x21', value: 0x21 },
  { label: '0x22', value: 0x22 },
  { label: '0x23', value: 0x23 },
  { label: '0x24', value: 0x24 },
  { label: '0x25', value: 0x25 },
  { label: '0x26', value: 0x26 },
  { label: '0x27', value: 0x27 },
  { label: '0x28', value: 0x28 },
  { label: '0x29', value: 0x29 },
  { label: '0x2A', value: 0x2A },
  { label: '0x2B', value: 0x2B },
  { label: '0x2C', value: 0x2C },
  { label: '0x2D', value: 0x2D },
  { label: '0x2E', value: 0x2E },
  { label: '0x2F', value: 0x2F },
  { label: '0x30', value: 0x30 },
  { label: '0x31', value: 0x31 },
  { label: '0x32', value: 0x32 },
  { label: '0x33', value: 0x33 },
  { label: '0x34', value: 0x34 },
  { label: '0x35', value: 0x35 },
  { label: '0x36', value: 0x36 },
  { label: '0x37', value: 0x37 },
  { label: '0x38', value: 0x38 },
  { label: '0x39', value: 0x39 },
  { label: '0x3A', value: 0x3A },
  { label: '0x3B', value: 0x3B },
  { label: '0x3C', value: 0x3C },
  { label: '0x3D', value: 0x3D },
  { label: '0x3E', value: 0x3E },
  { label: '0x3F', value: 0x3F },
  { label: 'Unlock Mani/Sol Katti', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x42', value: 0x42 },
  { label: '0x43', value: 0x43 },
  { label: '0x44', value: 0x44 },
  { label: '0x45', value: 0x45 },
  { label: '0x46', value: 0x46 },
  { label: '0x47', value: 0x47 },
  { label: '0x48', value: 0x48 },
  { label: '0x49', value: 0x49 },
  { label: '0x4A', value: 0x4A },
  { label: '0x4B', value: 0x4B },
  { label: '0x4C', value: 0x4C },
  { label: '0x4D', value: 0x4D },
  { label: '0x4E', value: 0x4E },
  { label: '0x4F', value: 0x4F },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
  { label: '0x52', value: 0x52 },
  { label: '0x53', value: 0x53 },
  { label: '0x54', value: 0x54 },
  { label: '0x55', value: 0x55 },
  { label: '0x56', value: 0x56 },
  { label: '0x57', value: 0x57 },
  { label: '0x58', value: 0x58 },
  { label: '0x59', value: 0x59 },
  { label: '0x5A', value: 0x5A },
  { label: '0x5B', value: 0x5B },
  { label: '0x5C', value: 0x5C },
  { label: '0x5D', value: 0x5D },
  { label: '0x5E', value: 0x5E },
  { label: '0x5F', value: 0x5F },
  { label: '0x60', value: 0x60 },
  { label: '0x61', value: 0x61 },
  { label: '0x62', value: 0x62 },
  { label: '0x63', value: 0x63 },
  { label: '0x64', value: 0x64 },
  { label: '0x65', value: 0x65 },
  { label: '0x66', value: 0x66 },
  { label: '0x67', value: 0x67 },
  { label: '0x68', value: 0x68 },
  { label: '0x69', value: 0x69 },
  { label: '0x6A', value: 0x6A },
  { label: '0x6B', value: 0x6B },
  { label: '0x6C', value: 0x6C },
  { label: '0x6D', value: 0x6D },
  { label: '0x6E', value: 0x6E },
  { label: '0x6F', value: 0x6F },
  { label: '0x70', value: 0x70 },
  { label: '0x71', value: 0x71 },
  { label: '0x72', value: 0x72 },
  { label: '0x73', value: 0x73 },
  { label: '0x74', value: 0x74 },
  { label: '0x75', value: 0x75 },
  { label: '0x76', value: 0x76 },
  { label: '0x77', value: 0x77 },
  { label: '0x78', value: 0x78 },
  { label: '0x79', value: 0x79 },
  { label: '0x7A', value: 0x7A },
  { label: '0x7B', value: 0x7B },
  { label: '0x7C', value: 0x7C },
  { label: '0x7D', value: 0x7D },
  { label: '0x7E', value: 0x7E },
  { label: '0x7F', value: 0x7F },
  { label: 'Unlock Forblaze', value: 0x80 },
  { label: '0x81', value: 0x81 },
  { label: '0x82', value: 0x82 },
  { label: '0x83', value: 0x83 },
  { label: '0x84', value: 0x84 },
  { label: '0x85', value: 0x85 },
  { label: '0x86', value: 0x86 },
  { label: '0x87', value: 0x87 },
  { label: '0x88', value: 0x88 },
  { label: '0x89', value: 0x89 },
  { label: '0x8A', value: 0x8A },
  { label: '0x8B', value: 0x8B },
  { label: '0x8C', value: 0x8C },
  { label: '0x8D', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: '0xFF', value: 0xFF },
];
