export const FE1WeaponEffectivenessEditorEntries = [
  { label: 'Entry 0', value: 0 },
];

export const Classnames = [
  { label: 'Cavalier', value: 0x01 },
  { label: 'Knight', value: 0x02 },
  { label: 'Pegasus Knight', value: 0x03 },
  { label: 'Paladin', value: 0x04 },
  { label: 'Dracoknight', value: 0x05 },
  { label: 'Mercenary', value: 0x06 },
  { label: 'Fighter', value: 0x07 },
  { label: 'Pirate', value: 0x08 },
  { label: 'Thief', value: 0x09 },
  { label: 'Hero', value: 0x0A },
  { label: 'Archer', value: 0x0B },
  { label: 'Hunter', value: 0x0C },
  { label: 'Ballistician', value: 0x0D },
  { label: 'Horseman', value: 0x0E },
  { label: 'Sniper', value: 0x0F },
  { label: 'Commando', value: 0x10 },
  { label: 'Mamkute', value: 0x11 },
  { label: 'Mage', value: 0x12 },
  { label: 'Priest', value: 0x13 },
  { label: 'Bishop', value: 0x14 },
  { label: 'Lord', value: 0x15 },
  { label: 'General', value: 0x16 },
  { label: 'Dragons', value: 0x17 },
  { label: 'Earth Dragon', value: 0x18 },
];
