export const CharList = [
  { label: '01 Roy', value: 0 },
  { label: '02 Clarine', value: 1 },
  { label: '03 Fa', value: 2 },
  { label: '04 Shin', value: 3 },
  { label: '05 Sue', value: 4 },
  { label: '06 Dayan', value: 5 },
  { label: '08 Barth', value: 6 },
  { label: '09 Bors', value: 7 },
  { label: '0A Wendy', value: 8 },
  { label: '0B Douglas', value: 9 },
  { label: '0D Wolt', value: 10 },
  { label: '0E Dorothy', value: 11 },
  { label: '0F Klein', value: 12 },
  { label: '10 Saul', value: 13 },
  { label: '11 Ellen', value: 14 },
  { label: '12 Yodel', value: 15 },
  { label: '14 Chad', value: 16 },
  { label: '15 Karel', value: 17 },
  { label: '16 Fir', value: 18 },
  { label: '17 Rutger', value: 19 },
  { label: '18 Deak', value: 20 },
  { label: '19 OJ', value: 21 },
  { label: '1A Garret', value: 22 },
  { label: '1B Alan', value: 23 },
  { label: '1C Lance', value: 24 },
  { label: '1D Percival', value: 25 },
  { label: '1E Igrene', value: 26 },
  { label: '1F Marcus', value: 27 },
  { label: '20 Astol', value: 28 },
  { label: '21 Ward', value: 29 },
  { label: '22 Lot', value: 30 },
  { label: '23 Bartre', value: 31 },
  { label: '25 Lugh', value: 32 },
  { label: '26 Lilina', value: 33 },
  { label: '27 Hugh', value: 34 },
  { label: '28 Niime', value: 35 },
  { label: '2A Ray', value: 36 },
  { label: '2B Lalum', value: 37 },
  { label: '2C Yunno', value: 38 },
  { label: '2E Tate', value: 39 },
  { label: '31 Thany', value: 40 },
  { label: '32 Zeiss', value: 41 },
  { label: '34 Elfin', value: 42 },
  { label: '35 Cath', value: 43 },
  { label: '36 Sophia', value: 44 },
  { label: '37 Miledy', value: 45 },
  { label: '38 Gonzales', value: 46 },
  { label: '3A Noah', value: 47 },
  { label: '3B Treck', value: 48 },
  { label: '3C Zealot', value: 49 },
  { label: '3D Echidna', value: 50 },
  { label: '3F Cecilia', value: 51 },
  { label: '40 Geese', value: 52 },
];

export const CharacterList = [
  { label: 'None', value: 0x00 },
  { label: 'Roy', value: 0x01 },
  { label: 'Clarine', value: 0x02 },
  { label: 'Fa', value: 0x03 },
  { label: 'Shin', value: 0x04 },
  { label: 'Sue', value: 0x05 },
  { label: 'Dayan', value: 0x06 },
  { label: 'Dayan (NPC)', value: 0x07 },
  { label: 'Barth', value: 0x08 },
  { label: 'Bors', value: 0x09 },
  { label: 'Wendy', value: 0x0A },
  { label: 'Douglas', value: 0x0B },
  { label: 'Douglas (NPC)', value: 0x0C },
  { label: 'Wolt', value: 0x0D },
  { label: 'Dorothy', value: 0x0E },
  { label: 'Klein', value: 0x0F },
  { label: 'Saul', value: 0x10 },
  { label: 'Elen', value: 0x11 },
  { label: 'Yodel', value: 0x12 },
  { label: 'Yodel (NPC)', value: 0x13 },
  { label: 'Chad', value: 0x14 },
  { label: 'Karel', value: 0x15 },
  { label: 'Fir', value: 0x16 },
  { label: 'Rutger', value: 0x17 },
  { label: 'Dieck', value: 0x18 },
  { label: 'Oujay', value: 0x19 },
  { label: 'Garet', value: 0x1A },
  { label: 'Alan', value: 0x1B },
  { label: 'Lance', value: 0x1C },
  { label: 'Percival', value: 0x1D },
  { label: 'Igrene', value: 0x1E },
  { label: 'Marcus', value: 0x1F },
  { label: 'Astol', value: 0x20 },
  { label: 'Ward', value: 0x21 },
  { label: 'Lot', value: 0x22 },
  { label: 'Bartre', value: 0x23 },
  { label: 'Bartre (NPC)', value: 0x24 },
  { label: 'Lugh', value: 0x25 },
  { label: 'Lilina', value: 0x26 },
  { label: 'Hugh', value: 0x27 },
  { label: 'Niime', value: 0x28 },
  { label: 'Niime (NPC)', value: 0x29 },
  { label: 'Rei', value: 0x2A },
  { label: 'Lalam', value: 0x2B },
  { label: 'Yunno', value: 0x2C },
  { label: 'Yunno (NPC)', value: 0x2D },
  { label: 'Thito', value: 0x2E },
  { label: 'Thito (enemy)', value: 0x2F },
  { label: 'Thito (NPC)', value: 0x30 },
  { label: 'Thany', value: 0x31 },
  { label: 'Zeiss', value: 0x32 },
  { label: 'Gale', value: 0x33 },
  { label: 'Elfin', value: 0x34 },
  { label: 'Cass', value: 0x35 },
  { label: 'Sophia', value: 0x36 },
  { label: 'Miledy', value: 0x37 },
  { label: 'Gonzales', value: 0x38 },
  { label: 'Gonzales (NPC)', value: 0x39 },
  { label: 'Noah', value: 0x3A },
  { label: 'Treck', value: 0x3B },
  { label: 'Zealot', value: 0x3C },
  { label: 'Echidna', value: 0x3D },
  { label: 'Echidna (NPC)', value: 0x3E },
  { label: 'Cecilia', value: 0x3F },
  { label: 'Geese', value: 0x40 },
  { label: 'Geese (NPC)', value: 0x41 },
  { label: 'Merlinus', value: 0x42 },
  { label: 'Eliwood', value: 0x43 },
  { label: 'Guinevere', value: 0x44 },
  { label: 'Bandit', value: 0x45 },
  { label: 'Bandit', value: 0x46 },
  { label: 'Bandit', value: 0x47 },
  { label: 'Bandit', value: 0x48 },
  { label: 'Bandit', value: 0x49 },
  { label: 'Damas', value: 0x4A },
  { label: 'Rude', value: 0x4B },
  { label: 'Slater', value: 0x4C },
  { label: 'Erik', value: 0x4D },
  { label: 'Dory', value: 0x4E },
  { label: 'Wagner', value: 0x4F },
  { label: 'Devias', value: 0x50 },
  { label: 'Legylance', value: 0x51 },
  { label: 'Scott', value: 0x52 },
  { label: 'Nord', value: 0x53 },
  { label: 'William', value: 0x54 },
  { label: 'Flaer', value: 0x55 },
  { label: 'Oro', value: 0x56 },
  { label: 'Robarts', value: 0x57 },
  { label: 'Aine', value: 0x58 },
  { label: 'Narshen', value: 0x59 },
  { label: 'Randy', value: 0x5A },
  { label: 'Rose', value: 0x5B },
  { label: 'Maggie', value: 0x5C },
  { label: 'Raeth', value: 0x5D },
  { label: 'Arcard', value: 0x5E },
  { label: 'Martel', value: 0x5F },
  { label: 'Sigune', value: 0x60 },
  { label: 'Roartz', value: 0x61 },
  { label: 'Murdock', value: 0x62 },
  { label: 'Brunya', value: 0x63 },
  { label: 'Zephiel', value: 0x64 },
  { label: 'Idoun (no hood)', value: 0x65 },
  { label: 'Idoun (dragon form)', value: 0x66 },
  { label: 'Yahn', value: 0x67 },
  { label: 'Zinc', value: 0x68 },
  { label: 'Monke', value: 0x69 },
  { label: 'Gel', value: 0x6A },
  { label: 'Brigand', value: 0x6B },
  { label: 'Bern', value: 0x6C },
  { label: 'Bern', value: 0x6D },
  { label: 'Bern', value: 0x6E },
  { label: 'Bern', value: 0x6F },
  { label: 'Bern', value: 0x70 },
  { label: 'Laus', value: 0x71 },
  { label: 'Pirate', value: 0x72 },
  { label: 'Bandit', value: 0x73 },
  { label: 'Thria', value: 0x74 },
  { label: 'Rebel', value: 0x75 },
  { label: 'Bern', value: 0x76 },
  { label: 'Rebel', value: 0x77 },
  { label: 'Officials', value: 0x78 },
  { label: 'Thief', value: 0x79 },
  { label: 'Seihou', value: 0x7A },
  { label: 'Pirate', value: 0x7B },
  { label: 'Almar', value: 0x7C },
  { label: 'Robber', value: 0x7D },
  { label: 'Registrans', value: 0x7E },
  { label: 'Eturia', value: 0x7F },
  { label: 'Bandit', value: 0x80 },
  { label: 'Bandit', value: 0x81 },
  { label: 'Bandit', value: 0x82 },
  { label: 'Bern', value: 0x83 },
  { label: 'Eturian', value: 0x84 },
  { label: 'Isle', value: 0x85 },
  { label: 'Bern', value: 0x86 },
  { label: 'Eturia', value: 0x87 },
  { label: 'Bern', value: 0x88 },
  { label: 'Bandit', value: 0x89 },
  { label: 'Eturia', value: 0x8A },
  { label: 'Bern', value: 0x8B },
  { label: 'Ilia', value: 0x8C },
  { label: 'Bandit', value: 0x8D },
  { label: 'Bern', value: 0x8E },
  { label: 'Eturia', value: 0x8F },
  { label: 'Thief', value: 0x90 },
  { label: 'Bern', value: 0x91 },
  { label: 'Bern', value: 0x92 },
  { label: 'Pirate', value: 0x93 },
  { label: 'Pirate', value: 0x94 },
  { label: 'Ilia', value: 0x95 },
  { label: 'Bern', value: 0x96 },
  { label: 'Ilia', value: 0x97 },
  { label: 'Brigand', value: 0x98 },
  { label: 'Ilia', value: 0x99 },
  { label: 'Fighter', value: 0x9A },
  { label: 'Bandit', value: 0x9B },
  { label: 'Ilia', value: 0x9C },
  { label: 'Citizen', value: 0x9D },
  { label: 'Thief', value: 0x9E },
  { label: 'Bern', value: 0x9F },
  { label: 'Bern', value: 0xA0 },
  { label: 'Bern', value: 0xA1 },
  { label: 'Thief', value: 0xA2 },
  { label: 'Bandit', value: 0xA3 },
  { label: 'Citizen', value: 0xA4 },
  { label: 'Fighter', value: 0xA5 },
  { label: 'Eturia', value: 0xA6 },
  { label: 'Sacae', value: 0xA7 },
  { label: 'Bern', value: 0xA8 },
  { label: 'Djute', value: 0xA9 },
  { label: 'Sacae', value: 0xAA },
  { label: 'Sacae', value: 0xAB },
  { label: 'Bern', value: 0xAC },
  { label: 'Eturia', value: 0xAD },
  { label: 'Sacae', value: 0xAE },
  { label: 'Bern', value: 0xAF },
  { label: 'Mamkute', value: 0xB0 },
  { label: 'Bern', value: 0xB1 },
  { label: 'WarDragon', value: 0xB2 },
  { label: 'Bandit', value: 0xB3 },
  { label: 'Bandit', value: 0xB4 },
  { label: 'Henning', value: 0xB5 },
  { label: 'Scollan', value: 0xB6 },
  { label: 'Bandit', value: 0xB7 },
  { label: 'Grero', value: 0xB8 },
  { label: 'Ohtz', value: 0xB9 },
  { label: 'Teck', value: 0xBA },
  { label: 'Bern', value: 0xBB },
  { label: 'Bern', value: 0xBC },
  { label: 'Bern', value: 0xBD },
  { label: 'Thoril', value: 0xBE },
  { label: 'Brakul', value: 0xBF },
  { label: 'Kudoka', value: 0xC0 },
  { label: 'Marral', value: 0xC1 },
  { label: 'Kabul', value: 0xC2 },
  { label: 'Chan', value: 0xC3 },
  { label: 'Pereth', value: 0xC4 },
  { label: 'Bern', value: 0xC5 },
  { label: 'Windam', value: 0xC6 },
  { label: 'Eturia', value: 0xC7 },
  { label: 'Morgan', value: 0xC8 },
  { label: 'Rebel', value: 0xC9 },
  { label: 'Bern', value: 0xCA },
  { label: 'Bern', value: 0xCB },
  { label: 'Bern', value: 0xCC },
  { label: 'Citizen', value: 0xCD },
  { label: 'Citizen', value: 0xCE },
  { label: 'Hector', value: 0xCF },
  { label: 'Bors', value: 0xD0 },
  { label: 'Commander', value: 0xD1 },
  { label: 'Commander', value: 0xD2 },
  { label: 'Percival\'s Unit', value: 0xD3 },
  { label: 'Bandit', value: 0xD4 },
  { label: 'Percival\'s Unit', value: 0xD5 },
  { label: 'Percival\'s Unit', value: 0xD6 },
  { label: 'Percival\'s Unit', value: 0xD7 },
  { label: 'Klein\'s Unit', value: 0xD8 },
  { label: 'Tate\'s Unit', value: 0xD9 },
  { label: 'Bandit', value: 0xE0 },
  { label: 'Duelist', value: 0xE1 },
];
