export const CustomAnimationEditor = [
  { label: 'What do you think you\'re editing?', value: 0 },
];

export const AnimationTypes = [
  { label: 'All Swords/   Separator', value: 0x00 },
  { label: 'All Spears/   Iron Sword', value: 0x01 },
  { label: 'All Axes/   Thin Sword', value: 0x02 },
  { label: 'All Bows/   Steel Sword', value: 0x03 },
  { label: 'All Staves/   Silver Sword', value: 0x04 },
  { label: 'All Anima/   Iron Blade', value: 0x05 },
  { label: 'All Light/   Steel Blade', value: 0x06 },
  { label: 'All Dark/   Silver Blade', value: 0x07 },
  { label: 'Poison Sword', value: 0x08 },
  { label: 'Disarmed(required)/   Rapier', value: 0x09 },
  { label: 'Mani Katti', value: 0x0A },
  { label: 'Hero Sword', value: 0x0B },
  { label: 'Wo Dao', value: 0x0C },
  { label: 'Killer Sword', value: 0x0D },
  { label: 'Armour Killer', value: 0x0E },
  { label: 'Dragon Killer', value: 0x0F },
  { label: 'Light Sword', value: 0x10 },
  { label: 'Rune Sword', value: 0x11 },
  { label: 'Lancebuster', value: 0x12 },
  { label: 'Long Sword', value: 0x13 },
  { label: 'Iron Spear', value: 0x14 },
  { label: 'Thin Spear', value: 0x15 },
  { label: 'Steel Spear', value: 0x16 },
  { label: 'Silver Spear', value: 0x17 },
  { label: 'Poison Spear', value: 0x18 },
  { label: 'Hero Spear', value: 0x19 },
  { label: 'Killer Lance', value: 0x1A },
  { label: 'Horse Killer', value: 0x1B },
  { label: 'Javelin', value: 0x1C },
  { label: 'Slender Spear', value: 0x1D },
  { label: 'Axebuster', value: 0x1E },
  { label: 'Iron Axe', value: 0x1F },
  { label: 'Steel Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Poison Axe', value: 0x22 },
  { label: 'Hero Axe', value: 0x23 },
  { label: 'Killer Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Hammer', value: 0x26 },
  { label: 'Devil Axe', value: 0x27 },
  { label: 'Hand Axe', value: 0x28 },
  { label: 'Tomahawk', value: 0x29 },
  { label: 'Swordbuster', value: 0x2A },
  { label: 'Sword Killer', value: 0x2B },
  { label: 'Iron Bow', value: 0x2C },
  { label: 'Steel Bow', value: 0x2D },
  { label: 'Silver Bow', value: 0x2E },
  { label: 'Poison Bow', value: 0x2F },
  { label: 'Killer Bow', value: 0x30 },
  { label: 'Hero Bow', value: 0x31 },
  { label: 'Short Bow', value: 0x32 },
  { label: 'Longbow', value: 0x33 },
  { label: 'Ballista', value: 0x34 },
  { label: 'Iron Ballista', value: 0x35 },
  { label: 'Killer Ballista', value: 0x36 },
  { label: 'Fire', value: 0x37 },
  { label: 'Thunder', value: 0x38 },
  { label: 'Elfire', value: 0x39 },
  { label: 'Thunderstorm', value: 0x3A },
  { label: 'Fimbulvetr', value: 0x3B },
  { label: 'Forblaze', value: 0x3C },
  { label: 'Excalibur', value: 0x3D },
  { label: 'Lightning', value: 0x3E },
  { label: 'Shine', value: 0x3F },
  { label: 'Divine', value: 0x40 },
  { label: 'Purge', value: 0x41 },
  { label: 'Aura', value: 0x42 },
  { label: 'Luce', value: 0x43 },
  { label: 'Flux', value: 0x44 },
  { label: 'Luna', value: 0x45 },
  { label: 'Nosferatu', value: 0x46 },
  { label: 'Eclipse', value: 0x47 },
  { label: 'Fenrir', value: 0x48 },
  { label: 'Gespenst', value: 0x49 },
  { label: 'Blagi\'s Touch', value: 0x4A },
  { label: 'Dragon Axe', value: 0x59 },
  { label: 'Bolt Axe', value: 0x63 },
  { label: 'Uber Spear', value: 0x77 },
  { label: 'Filla\'s Might', value: 0x7C },
  { label: 'Ninis\'s Grace', value: 0x7D },
  { label: 'Thor\'s Ire', value: 0x7E },
  { label: 'Set\'s Litany', value: 0x7F },
  { label: 'Emblem Sword', value: 0x80 },
  { label: 'Emblem Spear', value: 0x81 },
  { label: 'Emblem Axe', value: 0x82 },
  { label: 'Emblem Bow', value: 0x83 },
  { label: 'Durandal', value: 0x84 },
  { label: 'Armads', value: 0x85 },
  { label: 'Aureola', value: 0x86 },
  { label: 'Sol Katti', value: 0x8C },
  { label: 'Wolf Beil', value: 0x8D },
  { label: 'Ereshkigal', value: 0x8E },
  { label: 'Fire Dragon Stone', value: 0x8F },
  { label: 'Regal Blade', value: 0x90 },
  { label: 'Rex Hasta', value: 0x91 },
  { label: 'Basilikos', value: 0x92 },
  { label: 'Rienfleche', value: 0x93 },
  { label: 'Heavy Spear', value: 0x94 },
  { label: 'Short Spear', value: 0x95 },
  { label: 'Wind Sword', value: 0x99 },
  { label: '???', value: 0x9A },
  { label: '???', value: 0x9B },
  { label: '???', value: 0x9C },
];

export const WeaponAnimationType = [
  { label: 'Custom Animation for a Weapon', value: 0x00 },
  { label: 'All Weapons for a Weapon Type', value: 0x01 },
];

export const AnimationList = [
  { label: 'None (map animation)', value: 0x00 },
  { label: 'Eliwood', value: 0x01 },
  { label: 'Eliwood Disarmed', value: 0x02 },
  { label: 'Lord Knight Eliwood w/ Sword', value: 0x03 },
  { label: 'Lord Knight Eliwood w/ Durandal', value: 0x04 },
  { label: 'Lord Knight Eliwood w/ Spear', value: 0x05 },
  { label: 'Lord Knight Eliwood Disarmed', value: 0x06 },
  { label: 'Hector', value: 0x07 },
  { label: 'Hector w/ Hand Axe', value: 0x08 },
  { label: 'Hector Disarmed', value: 0x09 },
  { label: 'Great Lord Hector w/ Axe', value: 0x0A },
  { label: 'Great Lord Hector w/ Hand Axe', value: 0x0B },
  { label: 'Great Lord Hector w/ Armads', value: 0x0C },
  { label: 'Great Lord Hector w/ Sword', value: 0x0D },
  { label: 'Great Lord Hector Disarmed', value: 0x0E },
  { label: 'Lyn', value: 0x0F },
  { label: 'Lyn Disarmed', value: 0x10 },
  { label: 'Blade Lord Lyn w/ Sword', value: 0x11 },
  { label: 'Blade Lord Lyn w/ Sol Katti', value: 0x12 },
  { label: 'Blade Lord Lyn w/ Bow', value: 0x13 },
  { label: 'Blade Lord Lyn Disarmed', value: 0x14 },
  { label: 'Mountain Thief', value: 0x15 },
  { label: 'Mountain Thief w/ Hand Axe', value: 0x16 },
  { label: 'Mountain Thief Disarmed', value: 0x17 },
  { label: 'Pirate', value: 0x18 },
  { label: 'Pirate w/ Hand Axe', value: 0x19 },
  { label: 'Pirate Disarmed', value: 0x1A },
  { label: 'Hawkeye', value: 0x1B },
  { label: 'Hawkeye w/ Hand Axe', value: 0x1C },
  { label: 'Hawkeye Disarmed', value: 0x1D },
  { label: 'Fighter', value: 0x1E },
  { label: 'Fighter w/ Hand Axe', value: 0x1F },
  { label: 'Fighter Disarmed', value: 0x20 },
  { label: 'Warrior w/ Axe', value: 0x21 },
  { label: 'Warrior w/ Hand Axe', value: 0x22 },
  { label: 'Warrior w/ Bow', value: 0x23 },
  { label: 'Warrior Disarmed', value: 0x24 },
  { label: 'Archer', value: 0x25 },
  { label: 'Archer Disarmed', value: 0x26 },
  { label: 'Archer (F)', value: 0x27 },
  { label: 'Archer (F) Disarmed', value: 0x28 },
  { label: 'Sniper', value: 0x29 },
  { label: 'Sniper Disarmed', value: 0x2A },
  { label: 'Sniper (F)', value: 0x2B },
  { label: 'Sniper (F) Disarmed', value: 0x2C },
  { label: 'Mercenary', value: 0x2D },
  { label: 'Mercenary Disarmed', value: 0x2E },
  { label: 'Hero w/ Sword', value: 0x2F },
  { label: 'Hero w/ Axe', value: 0x30 },
  { label: 'Hero w/ Hand Axe', value: 0x31 },
  { label: 'Hero Disarmed', value: 0x32 },
  { label: 'Swordfighter', value: 0x33 },
  { label: 'Swordfighter Disarmed', value: 0x34 },
  { label: 'Swordmaster', value: 0x35 },
  { label: 'Swordmaster Disarmed', value: 0x36 },
  { label: 'Lloyd', value: 0x37 },
  { label: 'Lloyd Disarmed', value: 0x38 },
  { label: 'Swordmaster (F)', value: 0x39 },
  { label: 'Swordmaster (F) Disarmed', value: 0x3A },
  { label: 'Socialknight w/ Spear', value: 0x3B },
  { label: 'Socialknight w/ Sword', value: 0x3C },
  { label: 'Socialknight Disarmed', value: 0x3D },
  { label: 'Socialknight w/ Spear (again?)', value: 0x3E },
  { label: 'Assassin Legault', value: 0x3F },
  { label: 'Assassin Legault Disarmed', value: 0x40 },
  { label: 'Paladin w/ Axe', value: 0x41 },
  { label: 'Paladin w/ Hand Axe', value: 0x42 },
  { label: 'Paladin w/ Sword', value: 0x43 },
  { label: 'Paladin w/ Spear', value: 0x44 },
  { label: 'Paladin Disarmed', value: 0x45 },
  { label: 'Paladin w/ Axe', value: 0x46 },
  { label: 'Paladin w/ Hand Axe', value: 0x47 },
  { label: 'Paladin w/ Sword', value: 0x48 },
  { label: 'Paladin w/ Spear', value: 0x49 },
  { label: 'Paladin Disarmed', value: 0x4A },
  { label: 'Isadora w/ Axe', value: 0x4B },
  { label: 'Isadora w/ Hand Axe', value: 0x4C },
  { label: 'Isadora w/ Sword', value: 0x4D },
  { label: 'Isadora w/ Spear', value: 0x4E },
  { label: 'Isadora Disarmed', value: 0x4F },
  { label: 'Soldier', value: 0x50 },
  { label: 'Soldier Disarmed', value: 0x51 },
  { label: 'Armour Knight', value: 0x52 },
  { label: 'Armour Knight Disarmed', value: 0x53 },
  { label: 'General w/ Spear', value: 0x54 },
  { label: 'General w/ Axe', value: 0x55 },
  { label: 'General w/ Hand Axe', value: 0x56 },
  { label: 'General Disarmed', value: 0x57 },
  { label: 'Mage', value: 0x58 },
  { label: 'Nino', value: 0x59 },
  { label: 'Sage', value: 0x5A },
  { label: 'Sage w/ Staff', value: 0x5B },
  { label: 'Sage (F)', value: 0x5C },
  { label: 'Sage (F) w/ Staff', value: 0x5D },
  { label: 'Sage Nino', value: 0x5E },
  { label: 'Sage Nino w/ Staff', value: 0x5F },
  { label: 'Priest', value: 0x60 },
  { label: 'Priest Disarmed', value: 0x61 },
  { label: 'Serra', value: 0x62 },
  { label: 'Serra Disarmed', value: 0x63 },
  { label: 'Monk', value: 0x64 },
  { label: 'Bishop', value: 0x65 },
  { label: 'Bishop w/ Staff', value: 0x66 },
  { label: 'Bishop Serra', value: 0x67 },
  { label: 'Bishop Serra w/ Staff', value: 0x68 },
  { label: 'Shaman', value: 0x69 },
  { label: 'Druid', value: 0x6A },
  { label: 'Druid w/ Staff', value: 0x6B },
  { label: 'Dark Druid', value: 0x6C },
  { label: 'Dark Druid w/ Staff (messed up)', value: 0x6D },
  { label: 'Troubadour', value: 0x6E },
  { label: 'Troubadour Disarmed', value: 0x6F },
  { label: 'Valkyrie', value: 0x70 },
  { label: 'Valkyrie w/ Staff', value: 0x71 },
  { label: 'Athos', value: 0x72 },
  { label: 'Athos w/ Staff', value: 0x73 },
  { label: 'Nomad', value: 0x74 },
  { label: 'Nomad Disarmed', value: 0x75 },
  { label: 'Nomad Trooper w/ Sword', value: 0x76 },
  { label: 'Nomad Trooper w/ Bow', value: 0x77 },
  { label: 'Nomad Trooper Disarmed', value: 0x78 },
  { label: 'Thief', value: 0x79 },
  { label: 'Thief Disarmed', value: 0x7A },
  { label: 'Legault', value: 0x7B },
  { label: 'Legault Disarmed', value: 0x7C },
  { label: 'Leila', value: 0x7D },
  { label: 'Leila Disarmed', value: 0x7E },
  { label: 'Assassin', value: 0x7F },
  { label: 'Assassin Disarmed', value: 0x80 },
  { label: 'Pegasus Knight', value: 0x81 },
  { label: 'Pegasus Knight Disarmed', value: 0x82 },
  { label: 'Falcon Knight w/ Sword', value: 0x83 },
  { label: 'Falcon Knight w/ Spear', value: 0x84 },
  { label: 'Falcon Knight Disarmed', value: 0x85 },
  { label: 'Dragon Knight', value: 0x86 },
  { label: 'Dragon Knight Disarmed', value: 0x87 },
  { label: 'Dragon Master w/ Spear', value: 0x88 },
  { label: 'Dragon Master w/ Sword', value: 0x89 },
  { label: 'Dragon Master Disarmed', value: 0x8A },
  { label: 'Fire Dragon', value: 0x8B },
  { label: 'Archer on Ballista (unused, but still here from FE6)', value: 0x8C },
  { label: 'Dancer', value: 0x8D },
  { label: 'Bard', value: 0x8E },
  { label: 'Lucius', value: 0x8F },
  { label: 'Hero w/ Coat w/ Sword', value: 0x90 },
  { label: 'Hero w/ Coat w/ Axe', value: 0x91 },
  { label: 'Hero w/ Coat w/ Hand Axe', value: 0x92 },
  { label: 'Hero w/ Coat Disarmed', value: 0x93 },
  { label: 'Bishop Lucius', value: 0x94 },
  { label: 'Bishop Lucius w/ Staff', value: 0x95 },
  { label: 'Bishop Lucius Disarmed', value: 0x96 },
  { label: 'Bishop Disarmed', value: 0x97 },
  { label: 'Serra Disarmed', value: 0x98 },
  { label: 'Guy', value: 0x99 },
  { label: 'Guy Disarmed', value: 0x9A },
  { label: 'Swordmaster Guy', value: 0x9B },
  { label: 'Guy Disarmed', value: 0x9C },
  { label: 'Berserker', value: 0x9D },
  { label: 'Berserker w/ Hand Axe', value: 0x9E },
  { label: 'Berserker Disarmed', value: 0x9F },
  { label: 'Magic Seal', value: 0xA0 },
  { label: 'Tent', value: 0xA1 },
  { label: 'Transporter', value: 0xA2 },
  { label: 'Rogue Disarmed', value: 0xA3 },
  { label: 'Mage Knight (magic)', value: 0xA4 },
  { label: 'Mage Knight (staff)', value: 0xA5 },
  { label: 'Great Knight (sword)', value: 0xA6 },
  { label: 'Great Knight (lance)', value: 0xA7 },
  { label: 'Great Knight (axe)', value: 0xA8 },
  { label: 'Great Knight (disarmed)', value: 0xA9 },
  { label: 'BOLT AXE!!!', value: 0xAB },
  { label: 'Bishop (F)', value: 0xAC },
  { label: 'Bishop (F) AGAIN', value: 0xAD },
  { label: 'Halberdier w/ Lance', value: 0xAE },
  { label: 'Halberdier Disarmed', value: 0xAF },
];

export const AlwaysZero = [
  { label: '----------Always Zero----------', value: 0x00 },
];
