export const FE5EffectivenessEditor = [
  { label: '0xF700 ---->Custom Effectiveness 1<----', value: 0 },
  { label: '0xF710 ---->Custom Effectiveness 2<----', value: 1 },
  { label: '0xF720 ---->Custom Effectiveness 3<----', value: 2 },
  { label: '0xF730 ---->Custom Effectiveness 4<----', value: 3 },
  { label: '0xF740 ---->Custom Effectiveness 5<----', value: 4 },
  { label: '0xF750 ---->Custom Effectiveness 6<----', value: 5 },
  { label: '0xF760 ---->Custom Effectiveness 7<----', value: 6 },
  { label: '0xF770 ---->Custom Effectiveness 8<----', value: 7 },
  { label: '0xF780 ---->Custom Effectiveness 9<----', value: 8 },
  { label: '0xF790 ---->Custom Effectiveness 10<----', value: 9 },
  { label: '0xF7A0 ---->Custom Effectiveness 11<----', value: 10 },
  { label: '0xF7B0 ---->Custom Effectiveness 12<----', value: 11 },
  { label: '0xF7C0 ---->Custom Effectiveness 13<----', value: 12 },
  { label: '0xF7D0 ---->Custom Effectiveness 14<----', value: 13 },
  { label: '0xF7E0 ---->Custom Effectiveness 15<----', value: 14 },
  { label: '0xF7F0 ---->Custom Effectiveness 16<----', value: 15 },
];

export const ClassList = [
  { label: 'Nothing/Separator', value: 0x00 },
  { label: 'Social Knight', value: 0x01 },
  { label: 'Lance Knight', value: 0x02 },
  { label: 'Arch Knight', value: 0x03 },
  { label: 'Axe Knight', value: 0x04 },
  { label: 'Free Knight', value: 0x05 },
  { label: 'Troubadour', value: 0x06 },
  { label: 'Lord Knight', value: 0x07 },
  { label: 'Duke Knight', value: 0x08 },
  { label: 'Master Knight', value: 0x09 },
  { label: 'Paladin', value: 0x0A },
  { label: 'Paladin (F)', value: 0x0B },
  { label: 'Bow Knight', value: 0x0C },
  { label: 'Forrest Knight', value: 0x0D },
  { label: 'Mage Knight', value: 0x0E },
  { label: 'Great Knight', value: 0x0F },
  { label: 'Pegasus Knight', value: 0x10 },
  { label: 'Falcon Knight', value: 0x11 },
  { label: 'Dragon Rider', value: 0x12 },
  { label: 'Dragon Knight', value: 0x13 },
  { label: 'Dragon Master', value: 0x14 },
  { label: 'Bow Fighter', value: 0x15 },
  { label: 'Sword Fighter', value: 0x16 },
  { label: 'Swordmaster', value: 0x17 },
  { label: 'Sniper', value: 0x18 },
  { label: 'Forrest', value: 0x19 },
  { label: 'General', value: 0x1A },
  { label: 'Emperor', value: 0x1B },
  { label: 'Baron', value: 0x1C },
  { label: 'Lance Armour', value: 0x1D },
  { label: 'Axe Armour', value: 0x1E },
  { label: 'Bow Armour', value: 0x1F },
  { label: 'Sword Armour', value: 0x20 },
  { label: 'Berserker', value: 0x21 },
  { label: 'Mountain Thief', value: 0x22 },
  { label: 'Mountain Thief (2)', value: 0x23 },
  { label: 'Warrior', value: 0x24 },
  { label: 'Hunter', value: 0x25 },
  { label: 'Pirate', value: 0x26 },
  { label: 'Junior Lord', value: 0x27 },
  { label: 'Mage Knight', value: 0x28 },
  { label: 'Lord', value: 0x29 },
  { label: 'Prince', value: 0x2A },
  { label: 'Mage Knight (F)', value: 0x2B },
  { label: 'Baron (messed up battle sprite)', value: 0x2C },
  { label: 'Dancer', value: 0x2D },
  { label: 'Priest', value: 0x2E },
  { label: 'Mage', value: 0x2F },
  { label: 'Lopto Mage', value: 0x30 },
  { label: '(Thunder) Mage', value: 0x31 },
  { label: '(Wind) Mage', value: 0x32 },
  { label: 'High Priest', value: 0x33 },
  { label: 'Bishop', value: 0x34 },
  { label: 'Sage', value: 0x35 },
  { label: 'Bard', value: 0x36 },
  { label: 'Sister', value: 0x37 },
  { label: 'Dark Mage', value: 0x38 },
  { label: 'Dark Bishop', value: 0x39 },
  { label: 'Thief', value: 0x3A },
  { label: 'Thief Fighter', value: 0x3B },
  { label: 'Civilian', value: 0x3C },
  { label: 'Long Arch', value: 0x3D },
  { label: 'Iron Arch', value: 0x3E },
  { label: 'Killer Arch', value: 0x3F },
  { label: 'Dark Prince', value: 0x40 },
  { label: 'Axe Fighter', value: 0x41 },
  { label: 'Socialknight (dismounted)', value: 0x42 },
  { label: 'Lance Knight (dismounted)', value: 0x43 },
  { label: 'Arch Knight (dismounted)', value: 0x44 },
  { label: 'Axe Knight (dismounted)', value: 0x45 },
  { label: 'Free Knight (dismounted)', value: 0x46 },
  { label: 'Troubadour (dismounted)', value: 0x47 },
  { label: 'Lord Knight (dismounted)', value: 0x48 },
  { label: 'Duke Knight (dismounted)', value: 0x49 },
  { label: 'Master Knight (dismounted)', value: 0x4A },
  { label: 'Paladin (M) (dismounted)', value: 0x4B },
  { label: 'Paladin (F) (dismounted)', value: 0x4C },
  { label: 'Bow Knight (dismounted)', value: 0x4D },
  { label: 'Forrest Knight (dismounted)', value: 0x4E },
  { label: 'Great Knight (dismounted)', value: 0x4F },
  { label: 'Pegasus Knight (dismounted)', value: 0x50 },
  { label: 'Falcon Knight (dismounted)', value: 0x51 },
  { label: 'Dragon Rider (dismounted)', value: 0x52 },
  { label: 'Dragon Knight (dismounted)', value: 0x53 },
  { label: 'Dragon Master (dismounted)', value: 0x54 },
  { label: 'Arch Knight (F)', value: 0x55 },
  { label: 'Arch Knight (F) (dismounted)', value: 0x56 },
  { label: 'Bow Knight (F)', value: 0x57 },
  { label: 'Bow Knight (F) (dismounted)', value: 0x58 },
  { label: 'Master Knight (F)', value: 0x59 },
  { label: 'Master Knight (F) (dismounted)', value: 0x5A },
  { label: 'Dragon Rider (F)', value: 0x5B },
  { label: 'Dragon Rider (F) (dismounted)', value: 0x5C },
  { label: 'Dragon Knight (F)', value: 0x5D },
  { label: 'Dragon Knight (F) (dismounted)', value: 0x5E },
  { label: 'Dragon Master (F)', value: 0x5F },
  { label: 'Dragon Master (F) (dismounted)', value: 0x60 },
  { label: 'Poison Arch', value: 0x61 },
  { label: 'Mage (F)', value: 0x62 },
  { label: '(Thunder) Mage (F)', value: 0x63 },
  { label: 'Lopto Mage (F)', value: 0x64 },
  { label: '(Wind) Mage (F)', value: 0x65 },
  { label: 'Mage Knight (F)', value: 0x66 },
  { label: 'Mage Knight (F) (dismounted)', value: 0x67 },
  { label: 'Priest (F)', value: 0x68 },
  { label: 'High Priest (F)', value: 0x69 },
  { label: 'Sword Fighter (F)', value: 0x6A },
  { label: 'Forrest (F)', value: 0x6B },
  { label: 'Sword Master (F)', value: 0x6C },
  { label: 'Bow Fighter (F)', value: 0x6D },
  { label: 'Sniper (F)', value: 0x6E },
  { label: 'Thief (F)', value: 0x6F },
  { label: 'Thief Fighter (F)', value: 0x70 },
  { label: 'Mercenary', value: 0x71 },
  { label: 'Thief (Thief Fighter battle sprite)', value: 0x72 },
  { label: 'Pegasus Rider', value: 0x73 },
  { label: 'Pegasus Rider (dismounted)', value: 0x74 },
  { label: 'Soldier', value: 0x75 },
  { label: 'Archer', value: 0x76 },
  { label: 'Mercenary (F)', value: 0x77 },
];

export const AlwaysZero = [
  { label: '----------Always Zero----------', value: 0x00 },
];
