export const Miscmapsprites = [
  { label: 'Eliwood Lord', value: 0 },
  { label: 'Lyn Lord', value: 1 },
  { label: 'Hector Lord', value: 2 },
  { label: 'Eliwood Lord Knight (only by class name)', value: 3 },
  { label: 'Lyn Blade Lord (only by class name)', value: 4 },
  { label: 'Hector Great Lord (only by class name)', value: 5 },
  { label: 'Eliwood Lord Knight', value: 6 },
  { label: 'Lyn Blade Lord', value: 7 },
  { label: 'Hector Great Lord', value: 8 },
  { label: 'Mercenary', value: 9 },
  { label: 'Mercenary (F)', value: 10 },
  { label: 'Hero', value: 11 },
  { label: 'Hero (F)', value: 12 },
  { label: 'Swordfighter', value: 13 },
  { label: 'Swordfighter (F)', value: 14 },
  { label: 'Swordmaster', value: 15 },
  { label: 'Swordmaster (F)', value: 16 },
  { label: 'Fighter', value: 17 },
  { label: 'Warrior', value: 18 },
  { label: 'Armour Knight', value: 19 },
  { label: 'Armour Knight (F)', value: 20 },
  { label: 'General', value: 21 },
  { label: 'General (F)', value: 22 },
  { label: 'Archer', value: 23 },
  { label: 'Archer (F)', value: 24 },
  { label: 'Sniper', value: 25 },
  { label: 'Sniper (F)', value: 26 },
  { label: 'Monk', value: 27 },
  { label: 'Sister', value: 28 },
  { label: 'Bishop', value: 29 },
  { label: 'Bishop (F)', value: 30 },
  { label: 'Mage', value: 31 },
  { label: 'Mage (F)', value: 32 },
  { label: 'Sage', value: 33 },
  { label: 'Sage (F)', value: 34 },
  { label: 'Shaman', value: 35 },
  { label: 'Shaman (F)', value: 36 },
  { label: 'Druid', value: 37 },
  { label: 'Druid (F)', value: 38 },
  { label: 'Socialknight', value: 39 },
  { label: 'Socialknight (F)', value: 40 },
  { label: 'Paladin', value: 41 },
  { label: 'Paladin (F)', value: 42 },
  { label: 'Troubadour', value: 43 },
  { label: 'Valkyrie', value: 44 },
  { label: 'Nomad', value: 45 },
  { label: 'Nomad (F)', value: 46 },
  { label: 'Nomad Trooper', value: 47 },
  { label: 'Nomad Trooper (F)', value: 48 },
  { label: 'Pegasus Knight', value: 49 },
  { label: 'Falcon Knight', value: 50 },
  { label: 'Dragon Knight', value: 51 },
  { label: 'Dragon Knight (F)', value: 52 },
  { label: 'Dragon Master', value: 53 },
  { label: 'Dragon Master (F)', value: 54 },
  { label: 'Soldier', value: 55 },
  { label: 'Mountain Thief', value: 56 },
  { label: 'Pirate', value: 57 },
  { label: 'Berserker', value: 58 },
  { label: 'Thief', value: 59 },
  { label: 'Thief (F)', value: 60 },
  { label: 'Assassin', value: 61 },
  { label: 'Civilian', value: 62 },
  { label: 'Dancer', value: 63 },
  { label: 'Bard', value: 64 },
  { label: 'Archsage', value: 65 },
  { label: 'Magic Seal', value: 66 },
  { label: 'Transporter Tent', value: 67 },
  { label: 'Dark Druid', value: 68 },
  { label: 'Fire Dragon', value: 69 },
  { label: 'Civilian', value: 70 },
  { label: 'Civilian (F)', value: 71 },
  { label: 'Child', value: 72 },
  { label: 'Brammimond', value: 73 },
  { label: 'Peer', value: 74 },
  { label: 'Peer (F)', value: 75 },
  { label: 'Prince', value: 76 },
  { label: 'Queen', value: 77 },
  { label: 'Hung Leila', value: 78 },
  { label: 'Corsair', value: 79 },
  { label: 'Prince (Tactician)', value: 80 },
  { label: 'Fallen Prince', value: 81 },
  { label: 'Prince facing upward', value: 82 },
  { label: 'Fallen Ninian', value: 83 },
  { label: 'Fallen Ice Dragon', value: 84 },
  { label: 'Fallen Warrior', value: 85 },
  { label: 'Child', value: 86 },
  { label: 'Child (F)', value: 87 },
  { label: 'Transporter w/ Horse', value: 88 },
  { label: 'Uber Sage', value: 89 },
  { label: 'Archer in Ballista', value: 90 },
  { label: 'Archer in Iron Ballista', value: 91 },
  { label: 'Archer in Killer Ballista', value: 92 },
  { label: 'Empty Ballista', value: 93 },
  { label: 'Empty Iron Ballista', value: 94 },
  { label: 'Empty Killer Ballista', value: 95 },
  { label: 'Empty (Make a custom class!)', value: 96 },
  { label: 'Empty (Make a custom class!)', value: 97 },
  { label: 'Empty (Make a custom class!)', value: 98 },
  { label: 'Empty (Make a custom class!)', value: 99 },
];

export default Miscmapsprites;
