export const FE8SpecialDeathQuoteEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
  { label: 'Entry 68', value: 68 },
  { label: 'Entry 69', value: 69 },
  { label: 'Entry 70', value: 70 },
  { label: 'Entry 71', value: 71 },
  { label: 'Entry 72', value: 72 },
  { label: 'Entry 73', value: 73 },
  { label: 'Entry 74', value: 74 },
  { label: 'Entry 75', value: 75 },
  { label: 'Entry 76', value: 76 },
  { label: 'Entry 77', value: 77 },
  { label: 'Entry 78', value: 78 },
];

export const Characters = [
  { label: '(No one/Not referenced)', value: 0x00 },
  { label: 'Eirika', value: 0x01 },
  { label: 'Seth', value: 0x02 },
  { label: 'Gilliam', value: 0x03 },
  { label: 'Frantz', value: 0x04 },
  { label: 'Moulder', value: 0x05 },
  { label: 'Vanessa', value: 0x06 },
  { label: 'Ross', value: 0x07 },
  { label: 'Neimi', value: 0x08 },
  { label: 'Colm', value: 0x09 },
  { label: 'Garcia', value: 0x0A },
  { label: 'Innes', value: 0x0B },
  { label: 'Lute', value: 0x0C },
  { label: 'Natasha', value: 0x0D },
  { label: 'Cougar', value: 0x0E },
  { label: 'Ephraim', value: 0x0F },
  { label: 'Forde', value: 0x10 },
  { label: 'Kyle', value: 0x11 },
  { label: 'Amelia', value: 0x12 },
  { label: 'Artur', value: 0x13 },
  { label: 'Gerik', value: 0x14 },
  { label: 'Tethys', value: 0x15 },
  { label: 'Marisa', value: 0x16 },
  { label: 'Saleh', value: 0x17 },
  { label: 'Ewan', value: 0x18 },
  { label: 'L\'Arachel', value: 0x19 },
  { label: 'Dozla', value: 0x1A },
  { label: '-', value: 0x1B },
  { label: 'Rennac', value: 0x1C },
  { label: 'Duessel', value: 0x1D },
  { label: 'Myrrh', value: 0x1E },
  { label: 'Knoll', value: 0x1F },
  { label: 'Joshua', value: 0x20 },
  { label: 'Syrene', value: 0x21 },
  { label: 'Tana', value: 0x22 },
  { label: 'Lyon', value: 0x23 },
  { label: 'Orson', value: 0x24 },
  { label: 'Glen', value: 0x25 },
  { label: 'Selena', value: 0x26 },
  { label: 'Valter', value: 0x27 },
  { label: 'Riev', value: 0x28 },
  { label: 'Caellach', value: 0x29 },
  { label: 'Fado', value: 0x2A },
  { label: 'Ismaire', value: 0x2B },
  { label: 'Hayden', value: 0x2C },
  { label: '-', value: 0x2D },
  { label: '-', value: 0x2E },
  { label: '-', value: 0x2F },
  { label: '-', value: 0x30 },
  { label: '-', value: 0x31 },
  { label: '-', value: 0x32 },
  { label: '-', value: 0x33 },
  { label: '-', value: 0x34 },
  { label: '-', value: 0x35 },
  { label: '-', value: 0x36 },
  { label: '-', value: 0x37 },
  { label: '-', value: 0x38 },
  { label: '-', value: 0x39 },
  { label: '-', value: 0x3A },
  { label: 'Leon\'s Summon', value: 0x3B },
  { label: '-', value: 0x3C },
  { label: '-', value: 0x3D },
  { label: 'Knoll\'s Summon', value: 0x3E },
  { label: 'Yuan\'s Summon', value: 0x3F },
  { label: 'Lyon (Ch 17)', value: 0x40 },
  { label: 'Morva (Ch 20)', value: 0x41 },
  { label: 'Orson (Ch 5x)', value: 0x42 },
  { label: 'Valter (Ch 15)', value: 0x43 },
  { label: 'Selena (Ch 10B & 13B)', value: 0x44 },
  { label: 'Valter (Prologue)', value: 0x45 },
  { label: 'Breguet (Ch 1)', value: 0x46 },
  { label: 'Bone (Ch 2)', value: 0x47 },
  { label: 'Bazba (Ch 3)', value: 0x48 },
  { label: 'Mummy (Ch 4)', value: 0x49 },
  { label: 'Saar (Ch 5)', value: 0x4A },
  { label: 'Novala (Ch 6)', value: 0x4B },
  { label: 'Murray (Ch 7)', value: 0x4C },
  { label: 'Tirado (Ch 8)', value: 0x4D },
  { label: 'Binks (Ch 9A)', value: 0x4E },
  { label: 'Pablo (Ch 10A)', value: 0x4F },
  { label: 'Macdaire (Ch 12A)', value: 0x50 },
  { label: 'Aias (Ch 13A)', value: 0x51 },
  { label: 'Carlyle (Ch 14A)', value: 0x52 },
  { label: 'Caellach (Ch 15)', value: 0x53 },
  { label: 'Pablo (Ch 13A)', value: 0x54 },
  { label: '-', value: 0x55 },
  { label: 'Gorgon (Ch 18)', value: 0x56 },
  { label: 'Riev (Ch 19 & 20)', value: 0x57 },
  { label: '-', value: 0x58 },
  { label: '-', value: 0x59 },
  { label: 'Gheb (Ch 9B)', value: 0x5A },
  { label: 'Beran (Ch 10B)', value: 0x5B },
  { label: 'Cyclops (Ch 12B)', value: 0x5C },
  { label: 'Hellbone (Ch 11A)', value: 0x5D },
  { label: 'Death Gargoyle (Ch 11B)', value: 0x5E },
  { label: 'Mummy', value: 0x5F },
  { label: '-', value: 0x60 },
  { label: '-', value: 0x61 },
  { label: '-', value: 0x62 },
  { label: '-', value: 0x63 },
  { label: '-', value: 0x64 },
  { label: '-', value: 0x65 },
  { label: 'Mountain Thief', value: 0x66 },
  { label: '-', value: 0x67 },
  { label: 'O\'Neill (Prologue)', value: 0x68 },
  { label: 'Glen (Cutscene)', value: 0x69 },
  { label: 'Zonta (Ch 5x)', value: 0x6A },
  { label: 'Vigarde (Ch 14B)', value: 0x6B },
  { label: 'Lyon (Ch Final)', value: 0x6C },
  { label: 'Orson (Ch 16)', value: 0x6D },
  { label: '-', value: 0x6E },
  { label: '-', value: 0x6F },
  { label: '-', value: 0x70 },
  { label: '-', value: 0x71 },
  { label: '-', value: 0x72 },
  { label: '-', value: 0x73 },
  { label: '-', value: 0x74 },
  { label: '-', value: 0x75 },
  { label: '-', value: 0x76 },
  { label: '-', value: 0x77 },
  { label: '-', value: 0x78 },
  { label: '-', value: 0x79 },
  { label: '-', value: 0x7A },
  { label: '-', value: 0x7B },
  { label: '-', value: 0x7C },
  { label: '-', value: 0x7D },
  { label: '-', value: 0x7E },
  { label: '-', value: 0x7F },
  { label: '-', value: 0x80 },
  { label: '-', value: 0x81 },
  { label: '-', value: 0x82 },
  { label: '-', value: 0x83 },
  { label: '-', value: 0x84 },
  { label: '-', value: 0x85 },
  { label: '-', value: 0x86 },
  { label: '-', value: 0x87 },
  { label: '-', value: 0x88 },
  { label: '-', value: 0x89 },
  { label: '-', value: 0x8A },
  { label: '-', value: 0x8B },
  { label: '-', value: 0x8C },
  { label: '-', value: 0x8D },
  { label: '-', value: 0x8E },
  { label: '-', value: 0x8F },
  { label: '-', value: 0x90 },
  { label: '-', value: 0x91 },
  { label: '-', value: 0x92 },
  { label: '-', value: 0x93 },
  { label: '-', value: 0x94 },
  { label: '-', value: 0x95 },
  { label: '-', value: 0x96 },
  { label: '-', value: 0x97 },
  { label: '-', value: 0x98 },
  { label: '-', value: 0x99 },
  { label: '-', value: 0x9A },
  { label: '-', value: 0x9B },
  { label: '-', value: 0x9C },
  { label: '-', value: 0x9D },
  { label: '-', value: 0x9E },
  { label: '-', value: 0x9F },
  { label: '-', value: 0xA0 },
  { label: '-', value: 0xA1 },
  { label: '-', value: 0xA2 },
  { label: '-', value: 0xA3 },
  { label: '-', value: 0xA4 },
  { label: '-', value: 0xA5 },
  { label: '-', value: 0xA6 },
  { label: '-', value: 0xA7 },
  { label: '-', value: 0xA8 },
  { label: '-', value: 0xA9 },
  { label: '-', value: 0xAA },
  { label: '-', value: 0xAB },
  { label: '-', value: 0xAC },
  { label: '-', value: 0xAD },
  { label: '-', value: 0xAE },
  { label: '-', value: 0xAF },
  { label: '-', value: 0xB0 },
  { label: '-', value: 0xB1 },
  { label: '-', value: 0xB2 },
  { label: '-', value: 0xB3 },
  { label: '-', value: 0xB4 },
  { label: '-', value: 0xB5 },
  { label: '-', value: 0xB6 },
  { label: '-', value: 0xB7 },
  { label: '-', value: 0xB8 },
  { label: '-', value: 0xB9 },
  { label: '-', value: 0xBA },
  { label: '-', value: 0xBB },
  { label: '-', value: 0xBC },
  { label: '-', value: 0xBD },
  { label: 'Demon King', value: 0xBE },
  { label: '-', value: 0xBF },
  { label: 'Frelian', value: 0xC0 },
  { label: 'Frelian', value: 0xC1 },
  { label: '-', value: 0xC2 },
  { label: '-', value: 0xC3 },
  { label: '-', value: 0xC4 },
  { label: 'Fado (Renais)', value: 0xC5 },
  { label: '-', value: 0xC6 },
  { label: 'Hayden (Frelia)', value: 0xC7 },
  { label: 'Mansel (Rausten)', value: 0xC8 },
  { label: 'Klimt (Carcino)', value: 0xC9 },
  { label: 'Dara (Caer Pelyn)', value: 0xCA },
  { label: 'Ismaire (Jehanna)', value: 0xCB },
  { label: 'Pegasus Messenger', value: 0xCC },
  { label: 'Rausten Knight', value: 0xCD },
  { label: 'Rausten Knight', value: 0xCE },
  { label: '(Untested starting and beyond this point)', value: 0xCF },
  { label: '-', value: 0xD0 },
  { label: '-', value: 0xD1 },
  { label: '-', value: 0xD2 },
  { label: '-', value: 0xD3 },
  { label: '-', value: 0xD4 },
  { label: '-', value: 0xD5 },
  { label: '-', value: 0xD6 },
  { label: '-', value: 0xD7 },
  { label: '-', value: 0xD8 },
  { label: '-', value: 0xD9 },
  { label: '-', value: 0xDA },
  { label: '-', value: 0xDB },
  { label: '-', value: 0xDC },
  { label: '-', value: 0xDD },
  { label: '-', value: 0xDE },
  { label: '-', value: 0xDF },
  { label: '-', value: 0xE0 },
  { label: '-', value: 0xE1 },
  { label: '-', value: 0xE2 },
  { label: '-', value: 0xE3 },
  { label: '-', value: 0xE4 },
  { label: '-', value: 0xE5 },
  { label: '-', value: 0xE6 },
  { label: '-', value: 0xE7 },
  { label: '-', value: 0xE8 },
  { label: '-', value: 0xE9 },
  { label: '-', value: 0xEA },
  { label: '-', value: 0xEB },
  { label: '-', value: 0xEC },
  { label: '-', value: 0xED },
  { label: '-', value: 0xEE },
  { label: '-', value: 0xEF },
  { label: '-', value: 0xF0 },
  { label: '-', value: 0xF1 },
  { label: '-', value: 0xF2 },
  { label: '-', value: 0xF3 },
  { label: 'River Folk Child (F)', value: 0xF4 },
  { label: 'River Folk (F)', value: 0xF5 },
  { label: 'River Folk', value: 0xF6 },
  { label: 'River Folk (F)', value: 0xF7 },
  { label: 'River Folk Child', value: 0xF8 },
  { label: 'Renais Civilian Child (F)', value: 0xF9 },
  { label: 'Renais Civilian', value: 0xFA },
  { label: 'Renais Civilian (F)', value: 0xFB },
  { label: 'Old Civilian', value: 0xFC },
  { label: 'Enemy', value: 0xFD },
  { label: 'Wall', value: 0xFE },
  { label: 'Snag', value: 0xFF },
];

export const Chapters = [
  { label: 'Prologue', value: 0x00 },
  { label: 'Ch 1', value: 0x01 },
  { label: 'Ch 2', value: 0x02 },
  { label: 'Ch 3', value: 0x03 },
  { label: 'Ch 4/Zaha Woods', value: 0x04 },
  { label: 'Ch 5x', value: 0x05 },
  { label: 'Ch 5', value: 0x06 },
  { label: 'Ch 6/Adlas Plains', value: 0x07 },
  { label: 'Ch 7', value: 0x08 },
  { label: 'Ch 8', value: 0x09 },
  { label: 'Ch 9 Eirika', value: 0x0A },
  { label: 'Ch 10 Eirika/Teras Plateau', value: 0x0B },
  { label: 'Ch 12 Eirika', value: 0x0C },
  { label: 'Ch 13 Eirika', value: 0x0D },
  { label: 'Ch 14 Eirika', value: 0x0E },
  { label: 'Ch 15 Eirika', value: 0x0F },
  { label: 'Ch 16 Eirika', value: 0x10 },
  { label: 'Ch 17 Eirika/Narube River', value: 0x11 },
  { label: 'Ch 18 Eirika/Neleras Peak', value: 0x12 },
  { label: 'Ch 19 Eirika', value: 0x13 },
  { label: 'Ch 20 Eirika', value: 0x14 },
  { label: 'Final Ch 1 Eirika', value: 0x15 },
  { label: 'Final Ch 2 Erika', value: 0x16 },
  { label: 'Ch 9 Ephraim', value: 0x17 },
  { label: 'Ch 10 Ephraim/Bethroen', value: 0x18 },
  { label: 'Ch 12 Ephraim', value: 0x19 },
  { label: 'Ch 13 Ephraim/Za\'abadul Marsh', value: 0x1A },
  { label: 'Ch 14 Ephraim', value: 0x1B },
  { label: 'Ch 15 Ephraim', value: 0x1C },
  { label: 'Ch 16 Ephraim', value: 0x1D },
  { label: 'Ch 17 Ephraim/Narube River', value: 0x1E },
  { label: 'Ch 18 Ephraim/Neleras Peak', value: 0x1F },
  { label: 'Ch 19 Ephraim', value: 0x20 },
  { label: 'Ch 20 Ephraim', value: 0x21 },
  { label: 'Final Ch 1 Ephraim', value: 0x22 },
  { label: 'Final Ch 2 Ephraim', value: 0x23 },
  { label: 'Tower of Valni 1', value: 0x24 },
  { label: 'Tower of Valni 2', value: 0x25 },
  { label: 'Tower of Valni 3', value: 0x26 },
  { label: 'Tower of Valni 4', value: 0x27 },
  { label: 'Tower of Valni 5', value: 0x28 },
  { label: 'Tower of Valni 6', value: 0x29 },
  { label: 'Tower of Valni 7', value: 0x2A },
  { label: 'Tower of Valni 8', value: 0x2B },
  { label: 'Tower of Valni 8 Clone', value: 0x2C },
  { label: 'Tower of Valni 8 Clone', value: 0x2D },
  { label: 'Lagdou Ruins 1', value: 0x2E },
  { label: 'Lagdou Ruins 2', value: 0x2F },
  { label: 'Lagdou Ruins 3', value: 0x30 },
  { label: 'Lagdou Ruins 4', value: 0x31 },
  { label: 'Lagdou Ruins 5', value: 0x32 },
  { label: 'Lagdou Ruins 6', value: 0x33 },
  { label: 'Lagdou Ruins 7', value: 0x34 },
  { label: 'Lagdou Ruins 8', value: 0x35 },
  { label: 'Lagdou Ruins 9', value: 0x36 },
  { label: 'Lagdou Ruins 10', value: 0x37 },
  { label: 'Lords split up (glitchy map)', value: 0x38 },
  { label: 'Melkaen Coast', value: 0x39 },
  { label: 'Link Arena', value: 0x3A },
  { label: 'The interesting map...', value: 0x3B },
  { label: 'Debug map', value: 0x3C },
  { label: 'Ch 11 Eirika', value: 0x3D },
  { label: 'Ch 11 Ephraim', value: 0x3E },
  { label: 'Grado castle', value: 0x3F },
  { label: 'Renais castle', value: 0x40 },
  { label: 'Caer Pelyn', value: 0x41 },
  { label: 'Renais throne', value: 0x42 },
  { label: 'Renais audience', value: 0x43 },
  { label: 'Renval gate', value: 0x44 },
  { label: 'Grado borders', value: 0x45 },
  { label: 'Grado prison', value: 0x46 },
  { label: 'Grado shrine (Past)', value: 0x47 },
  { label: 'Renais shrine', value: 0x48 },
  { label: 'Some path', value: 0x49 },
  { label: 'Some building', value: 0x4A },
  { label: 'Another shrine', value: 0x4B },
  { label: 'Another path', value: 0x4C },
  { label: 'Grado shrine (Present)', value: 0x4D },
  { label: 'Ch 5 town (Past)', value: 0x4E },
  { label: 'All', value: 0xFF },
];
