export const FE3DeathQuoteEditorEntries = [
  { label: 'Entry 0', value: 0 },
  { label: 'Entry 1', value: 1 },
  { label: 'Entry 2', value: 2 },
  { label: 'Entry 3', value: 3 },
  { label: 'Entry 4', value: 4 },
  { label: 'Entry 5', value: 5 },
  { label: 'Entry 6', value: 6 },
  { label: 'Entry 7', value: 7 },
  { label: 'Entry 8', value: 8 },
  { label: 'Entry 9', value: 9 },
  { label: 'Entry 10', value: 10 },
  { label: 'Entry 11', value: 11 },
  { label: 'Entry 12', value: 12 },
  { label: 'Entry 13', value: 13 },
  { label: 'Entry 14', value: 14 },
  { label: 'Entry 15', value: 15 },
  { label: 'Entry 16', value: 16 },
  { label: 'Entry 17', value: 17 },
  { label: 'Entry 18', value: 18 },
  { label: 'Entry 19', value: 19 },
  { label: 'Entry 20', value: 20 },
  { label: 'Entry 21', value: 21 },
  { label: 'Entry 22', value: 22 },
  { label: 'Entry 23', value: 23 },
  { label: 'Entry 24', value: 24 },
  { label: 'Entry 25', value: 25 },
  { label: 'Entry 26', value: 26 },
  { label: 'Entry 27', value: 27 },
  { label: 'Entry 28', value: 28 },
  { label: 'Entry 29', value: 29 },
  { label: 'Entry 30', value: 30 },
  { label: 'Entry 31', value: 31 },
  { label: 'Entry 32', value: 32 },
  { label: 'Entry 33', value: 33 },
  { label: 'Entry 34', value: 34 },
  { label: 'Entry 35', value: 35 },
  { label: 'Entry 36', value: 36 },
  { label: 'Entry 37', value: 37 },
  { label: 'Entry 38', value: 38 },
  { label: 'Entry 39', value: 39 },
  { label: 'Entry 40', value: 40 },
  { label: 'Entry 41', value: 41 },
  { label: 'Entry 42', value: 42 },
  { label: 'Entry 43', value: 43 },
  { label: 'Entry 44', value: 44 },
  { label: 'Entry 45', value: 45 },
  { label: 'Entry 46', value: 46 },
  { label: 'Entry 47', value: 47 },
  { label: 'Entry 48', value: 48 },
  { label: 'Entry 49', value: 49 },
  { label: 'Entry 50', value: 50 },
  { label: 'Entry 51', value: 51 },
  { label: 'Entry 52', value: 52 },
  { label: 'Entry 53', value: 53 },
  { label: 'Entry 54', value: 54 },
  { label: 'Entry 55', value: 55 },
  { label: 'Entry 56', value: 56 },
  { label: 'Entry 57', value: 57 },
  { label: 'Entry 58', value: 58 },
  { label: 'Entry 59', value: 59 },
  { label: 'Entry 60', value: 60 },
  { label: 'Entry 61', value: 61 },
  { label: 'Entry 62', value: 62 },
  { label: 'Entry 63', value: 63 },
  { label: 'Entry 64', value: 64 },
  { label: 'Entry 65', value: 65 },
  { label: 'Entry 66', value: 66 },
  { label: 'Entry 67', value: 67 },
  { label: 'Entry 68', value: 68 },
  { label: 'Entry 69', value: 69 },
  { label: 'Entry 70', value: 70 },
  { label: 'Entry 71', value: 71 },
  { label: 'Entry 72', value: 72 },
  { label: 'Entry 73', value: 73 },
  { label: 'Entry 74', value: 74 },
  { label: 'Entry 75', value: 75 },
  { label: 'Entry 76', value: 76 },
  { label: 'Entry 77', value: 77 },
  { label: 'Entry 78', value: 78 },
  { label: 'Entry 79', value: 79 },
  { label: 'Entry 80', value: 80 },
  { label: 'Entry 81', value: 81 },
  { label: 'Entry 82', value: 82 },
  { label: 'Entry 83', value: 83 },
  { label: 'Entry 84', value: 84 },
  { label: 'Entry 85', value: 85 },
  { label: 'Entry 86', value: 86 },
  { label: 'Entry 87', value: 87 },
  { label: 'Entry 88', value: 88 },
  { label: 'Entry 89', value: 89 },
  { label: 'Entry 90', value: 90 },
  { label: 'Entry 91', value: 91 },
  { label: 'Entry 92', value: 92 },
];

export const FE3Names = [
  { label: 'Marth', value: 0x00 },
  { label: 'Caeda', value: 0x01 },
  { label: 'Jagen', value: 0x02 },
  { label: 'Cain', value: 0x03 },
  { label: 'Abel', value: 0x04 },
  { label: 'Draug', value: 0x05 },
  { label: 'Gordin', value: 0x06 },
  { label: 'Rickard', value: 0x07 },
  { label: 'Wrys (leftover from fe1)', value: 0x08 },
  { label: 'Bord', value: 0x09 },
  { label: 'Cord', value: 0x0A },
  { label: 'Barst', value: 0x0B },
  { label: 'Castor', value: 0x0C },
  { label: 'Ogma', value: 0x0D },
  { label: 'Darros (leftover from fe1)', value: 0x0E },
  { label: 'Julian', value: 0x0F },
  { label: 'Lena', value: 0x10 },
  { label: 'Merric', value: 0x11 },
  { label: 'Navarre', value: 0x12 },
  { label: 'Hardin', value: 0x13 },
  { label: 'Wolf', value: 0x14 },
  { label: 'Sedgar', value: 0x15 },
  { label: 'Roshea', value: 0x16 },
  { label: 'Vyland', value: 0x17 },
  { label: 'Bantu', value: 0x18 },
  { label: 'Caesar', value: 0x19 },
  { label: 'Radd', value: 0x1A },
  { label: 'Midia', value: 0x1B },
  { label: 'Catria', value: 0x1C },
  { label: 'Maria', value: 0x1D },
  { label: 'Minerva', value: 0x1E },
  { label: 'Linde', value: 0x1F },
  { label: 'Jeorge', value: 0x20 },
  { label: 'Dolph', value: 0x21 },
  { label: 'Macellan', value: 0x22 },
  { label: 'Tomas', value: 0x23 },
  { label: 'Boah', value: 0x24 },
  { label: 'Arran', value: 0x25 },
  { label: 'Samson', value: 0x26 },
  { label: 'Beck (leftover from fe1)', value: 0x27 },
  { label: 'Xane', value: 0x28 },
  { label: 'Wendell', value: 0x29 },
  { label: 'Est', value: 0x2A },
  { label: 'Astram', value: 0x2B },
  { label: 'Matthis', value: 0x2C },
  { label: 'Roger (leftover from fe1)', value: 0x2D },
  { label: 'Jake (leftover from fe1)', value: 0x2E },
  { label: 'Palla', value: 0x2F },
  { label: 'Tiki', value: 0x30 },
  { label: 'Lorenz', value: 0x31 },
  { label: 'Elice', value: 0x32 },
  { label: 'Gotoh', value: 0x33 },
  { label: 'Gazzak', value: 0x34 },
  { label: 'Wylar (unused)', value: 0x35 },
  { label: 'Grust Soldier', value: 0x36 },
  { label: 'Gomer', value: 0x37 },
  { label: 'Garuda Soldier', value: 0x38 },
  { label: 'Sabre (unused)', value: 0x39 },
  { label: 'Merach', value: 0x3A },
  { label: 'Harmein', value: 0x3B },
  { label: 'Emereus', value: 0x3C },
  { label: 'Bentheon (leftover from fe1)', value: 0x3D },
  { label: 'Kannival', value: 0x3E },
  { label: 'Mannu (leftover from fe1)', value: 0x3F },
  { label: 'Zharov', value: 0x40 },
  { label: 'Khozen', value: 0x41 },
  { label: 'Heimler (leftover from fe1)', value: 0x42 },
  { label: 'Grigas (leftover from fe1)', value: 0x43 },
  { label: 'Jiol', value: 0x44 },
  { label: 'Volzhin', value: 0x45 },
  { label: 'Hollstadt', value: 0x46 },
  { label: 'Sternlin (leftover from fe1)', value: 0x47 },
  { label: 'Hyman', value: 0x48 },
  { label: 'Xemcel', value: 0x49 },
  { label: 'Orridyon (leftover from fe1)', value: 0x4A },
  { label: 'Camus', value: 0x4B },
  { label: 'Michalis', value: 0x4C },
  { label: 'Morzas', value: 0x4D },
  { label: 'Gharnef', value: 0x4E },
  { label: 'Medeus', value: 0x4F },
  { label: 'Dolhr', value: 0x50 },
  { label: 'Gra', value: 0x51 },
  { label: 'Pyrathi', value: 0x52 },
  { label: 'Chiasmir', value: 0x53 },
  { label: 'SableOrd', value: 0x54 },
  { label: 'Khadein', value: 0x55 },
  { label: 'IronKnt', value: 0x56 },
  { label: 'Dragoon', value: 0x57 },
  { label: 'IronKnt', value: 0x58 },
  { label: 'Medon', value: 0x59 },
  { label: 'Pegasus', value: 0x5A },
  { label: 'Ruffian', value: 0x5B },
  { label: 'Raman', value: 0x5C },
  { label: 'Dark Mage', value: 0x5D },
  { label: 'Priest', value: 0x5E },
  { label: 'Ruffian', value: 0x5F },
  { label: 'Gharnef', value: 0x60 },
  { label: 'Cecil', value: 0x61 },
  { label: 'Luke', value: 0x62 },
  { label: 'Roderick', value: 0x63 },
  { label: 'Ryan', value: 0x64 },
  { label: 'Warren', value: 0x65 },
  { label: 'Brave', value: 0x66 },
  { label: 'Rumel', value: 0x67 },
  { label: 'Rucke', value: 0x68 },
  { label: 'Yuliya', value: 0x69 },
  { label: 'Jubelo', value: 0x6A },
  { label: 'Sirius', value: 0x6B },
  { label: 'Gail', value: 0x6C },
  { label: 'Paiking', value: 0x6D },
  { label: 'Marisha', value: 0x6E },
  { label: 'Toras', value: 0x6F },
  { label: 'Samuel', value: 0x70 },
  { label: 'Lang', value: 0x71 },
  { label: 'Phina', value: 0x72 },
  { label: 'Dahl', value: 0x73 },
  { label: 'Laman Thief', value: 0x74 },
  { label: 'Yodel', value: 0x75 },
  { label: 'Arlen', value: 0x76 },
  { label: 'FlyingDr', value: 0x77 },
  { label: 'Sand Tribe', value: 0x78 },
  { label: 'Evil Fighter', value: 0x79 },
  { label: 'Bandit', value: 0x7A },
  { label: 'Thief', value: 0x7B },
  { label: 'Good Dragon?', value: 0x7C },
  { label: 'Ice Dragon', value: 0x7D },
  { label: 'Ice Thief (wtf?)', value: 0x7E },
  { label: 'Eibel', value: 0x7F },
  { label: 'Sheena', value: 0x80 },
  { label: 'Earth Dragon', value: 0x81 },
  { label: 'Dark Priest', value: 0x82 },
  { label: 'Willow', value: 0x83 },
  { label: 'Akanea Soldier', value: 0x84 },
  { label: 'Orleans Soldier', value: 0x85 },
  { label: 'Nyna', value: 0x86 },
  { label: 'Khadein Mercenary', value: 0x87 },
  { label: 'Fire Tribe', value: 0x88 },
  { label: 'Earth Tribe', value: 0x89 },
  { label: 'Nehring', value: 0x8A },
  { label: 'Dark Tribe', value: 0x8B },
  { label: 'Dark Dragon', value: 0x8C },
  { label: 'Bodyguard', value: 0x8D },
  { label: '0x8E', value: 0x8E },
  { label: '0x8F', value: 0x8F },
  { label: '0x90', value: 0x90 },
  { label: '0x91', value: 0x91 },
  { label: '0x92', value: 0x92 },
  { label: '0x93', value: 0x93 },
  { label: '0x94', value: 0x94 },
  { label: '0x95', value: 0x95 },
  { label: '0x96', value: 0x96 },
  { label: '0x97', value: 0x97 },
  { label: '0x98', value: 0x98 },
  { label: '0x99', value: 0x99 },
  { label: '0x9A', value: 0x9A },
  { label: '0x9B', value: 0x9B },
  { label: '0x9C', value: 0x9C },
  { label: '0x9D', value: 0x9D },
  { label: '0x9E', value: 0x9E },
  { label: '0x9F', value: 0x9F },
  { label: '0xA0', value: 0xA0 },
  { label: '0xA1', value: 0xA1 },
  { label: '0xA2', value: 0xA2 },
  { label: '0xA3', value: 0xA3 },
  { label: '0xA4', value: 0xA4 },
  { label: '0xA5', value: 0xA5 },
  { label: '0xA6', value: 0xA6 },
  { label: '0xA7', value: 0xA7 },
  { label: '0xA8', value: 0xA8 },
  { label: '0xA9', value: 0xA9 },
  { label: '0xAA', value: 0xAA },
  { label: '0xAB', value: 0xAB },
  { label: '0xAC', value: 0xAC },
  { label: '0xAD', value: 0xAD },
  { label: '0xAE', value: 0xAE },
  { label: '0xAF', value: 0xAF },
  { label: '0xB0', value: 0xB0 },
  { label: '0xB1', value: 0xB1 },
  { label: '0xB2', value: 0xB2 },
  { label: '0xB3', value: 0xB3 },
  { label: '0xB4', value: 0xB4 },
  { label: '0xB5', value: 0xB5 },
  { label: '0xB6', value: 0xB6 },
  { label: '0xB7', value: 0xB7 },
  { label: '0xB8', value: 0xB8 },
  { label: '0xB9', value: 0xB9 },
  { label: '0xBA', value: 0xBA },
  { label: '0xBB', value: 0xBB },
  { label: '0xBC', value: 0xBC },
  { label: '0xBD', value: 0xBD },
  { label: '0xBE', value: 0xBE },
  { label: '0xBF', value: 0xBF },
  { label: '0xC0', value: 0xC0 },
  { label: '0xC1', value: 0xC1 },
  { label: '0xC2', value: 0xC2 },
  { label: '0xC3', value: 0xC3 },
  { label: '0xC4', value: 0xC4 },
  { label: '0xC5', value: 0xC5 },
  { label: '0xC6', value: 0xC6 },
  { label: '0xC7', value: 0xC7 },
  { label: '0xC8', value: 0xC8 },
  { label: '0xC9', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: 'Nothing', value: 0xFF },
];
