export const CharacterList = [
  { label: 'Marth', value: 0 },
  { label: 'Caeda', value: 1 },
  { label: 'Jagan', value: 2 },
  { label: 'Cain', value: 3 },
  { label: 'Abel', value: 4 },
  { label: 'Draug', value: 5 },
  { label: 'Gordin', value: 6 },
  { label: 'Wrys', value: 7 },
  { label: 'Ogma', value: 8 },
  { label: 'Barst', value: 9 },
  { label: 'Bord', value: 10 },
  { label: 'Cord', value: 11 },
  { label: 'Castor', value: 12 },
  { label: 'Darros', value: 13 },
  { label: 'Julian', value: 14 },
  { label: 'Lena', value: 15 },
  { label: 'Nabarl', value: 16 },
  { label: 'Merric', value: 17 },
  { label: 'Matthis', value: 18 },
  { label: 'Hardin', value: 19 },
  { label: 'Wolf', value: 20 },
  { label: 'Sedgar', value: 21 },
  { label: 'Roshea', value: 22 },
  { label: 'Vyland', value: 23 },
  { label: 'Wendell', value: 24 },
  { label: 'Rikard', value: 25 },
  { label: 'Bantu', value: 26 },
  { label: 'Caesar', value: 27 },
  { label: 'Radd', value: 28 },
  { label: 'Roger', value: 29 },
  { label: 'Jeorge', value: 30 },
  { label: 'Maria', value: 31 },
  { label: 'Minerva', value: 32 },
  { label: 'Linde', value: 33 },
  { label: 'Jake', value: 34 },
  { label: 'Midia', value: 35 },
  { label: 'Dolph', value: 36 },
  { label: 'Macellan', value: 37 },
  { label: 'Tomas', value: 38 },
  { label: 'Boah', value: 39 },
  { label: 'Beck', value: 40 },
  { label: 'Astram', value: 41 },
  { label: 'Palla', value: 42 },
  { label: 'Catria', value: 43 },
  { label: 'Arran', value: 44 },
  { label: 'Samson', value: 45 },
  { label: 'Xane', value: 46 },
  { label: 'Est', value: 47 },
  { label: 'Tiki', value: 48 },
  { label: 'Lorenz', value: 49 },
  { label: 'Elice', value: 50 },
  { label: 'Gotoh', value: 51 },
  { label: 'Frey', value: 52 },
  { label: 'Nornw', value: 53 },
  { label: 'Athena', value: 54 },
  { label: 'Horace', value: 55 },
  { label: 'Etzel', value: 56 },
  { label: 'Nagi', value: 57 },
  { label: 'Ymir', value: 58 },
  { label: 'Dummy', value: 59 },
  { label: 'No Name', value: 60 },
  { label: 'No Name', value: 61 },
  { label: 'No Name', value: 62 },
  { label: 'No Name', value: 63 },
  { label: 'No Name', value: 64 },
  { label: 'No Name', value: 65 },
  { label: 'No Name', value: 66 },
  { label: 'No Name', value: 67 },
  { label: 'No Name', value: 68 },
  { label: 'No Name', value: 69 },
  { label: 'No Name', value: 70 },
  { label: 'No Name', value: 71 },
  { label: 'No Name', value: 72 },
  { label: 'No Name', value: 73 },
  { label: 'No Name', value: 74 },
  { label: 'No Name', value: 75 },
  { label: 'No Name', value: 76 },
  { label: 'No Name', value: 77 },
  { label: 'Gazzak', value: 78 },
  { label: 'Gomer', value: 79 },
  { label: 'Hyman', value: 80 },
  { label: 'Bentheon', value: 81 },
  { label: 'Merach', value: 82 },
  { label: 'Emereus', value: 83 },
  { label: 'Harmein', value: 84 },
  { label: 'Kannival', value: 85 },
  { label: 'Mannu', value: 86 },
  { label: 'Zharov', value: 87 },
  { label: 'Khozen', value: 88 },
  { label: 'Volzhin', value: 89 },
  { label: 'Heimler', value: 90 },
  { label: 'Grigas', value: 91 },
  { label: 'Jiol', value: 92 },
  { label: 'Gharnef', value: 93 },
  { label: 'Gharnef 2', value: 94 },
  { label: 'Hollstadt', value: 95 },
  { label: 'Morzas', value: 96 },
  { label: 'Sternlin', value: 97 },
  { label: 'Camus', value: 98 },
  { label: 'Orridyon', value: 99 },
  { label: 'Michalis', value: 100 },
  { label: 'Xemcel', value: 101 },
  { label: 'Medeus', value: 102 },
  { label: 'Galder', value: 103 },
  { label: 'Galder', value: 104 },
  { label: 'Galder', value: 105 },
  { label: 'Galder', value: 106 },
  { label: 'Galder', value: 107 },
  { label: 'Galder', value: 108 },
  { label: 'Grust', value: 109 },
  { label: 'Soothsire', value: 110 },
  { label: 'Soothsire', value: 111 },
  { label: 'Soothsire', value: 112 },
  { label: 'Macedon', value: 113 },
  { label: 'Macedon', value: 114 },
  { label: 'Macedon', value: 115 },
  { label: 'Macedon', value: 116 },
  { label: 'Macedon', value: 117 },
  { label: 'Macedon', value: 118 },
  { label: 'Macedon', value: 119 },
  { label: 'Macedon', value: 120 },
  { label: 'Macedon', value: 121 },
  { label: 'Macedon', value: 122 },
  { label: 'Macedon', value: 123 },
  { label: 'Macedon', value: 124 },
  { label: 'Macedon', value: 125 },
  { label: 'Macedon', value: 126 },
  { label: 'Macedon', value: 127 },
  { label: 'Macedon', value: 128 },
  { label: 'Macedon', value: 129 },
  { label: 'Macedon', value: 130 },
  { label: 'Macedon', value: 131 },
  { label: 'Macedon', value: 132 },
  { label: 'Grust', value: 133 },
  { label: 'Dragoon', value: 134 },
  { label: 'Dragoon', value: 135 },
  { label: 'Grust', value: 136 },
  { label: 'Grust', value: 137 },
  { label: 'Grust', value: 138 },
  { label: 'Grust', value: 139 },
  { label: 'Grust', value: 140 },
  { label: 'Grust', value: 141 },
  { label: 'Grust', value: 142 },
  { label: 'Grust', value: 143 },
  { label: 'Grust', value: 144 },
  { label: 'Pyrathi', value: 145 },
  { label: 'Pyrathi', value: 146 },
  { label: 'Pyrathi', value: 147 },
  { label: 'Pyrathi', value: 148 },
  { label: 'Pyrathi', value: 149 },
  { label: 'Grust', value: 150 },
  { label: 'Grust', value: 151 },
  { label: 'Grust', value: 152 },
  { label: 'Grust', value: 153 },
  { label: 'Grust', value: 154 },
  { label: 'Grust', value: 155 },
  { label: 'Grust', value: 156 },
  { label: 'Grust', value: 157 },
  { label: 'Grust', value: 158 },
  { label: 'Grust', value: 159 },
  { label: 'Grust', value: 160 },
  { label: 'Grust', value: 161 },
  { label: 'Grust', value: 162 },
  { label: 'Grust', value: 163 },
  { label: 'Grust', value: 164 },
  { label: 'Grust', value: 165 },
  { label: 'Ruffian', value: 166 },
  { label: 'Grust', value: 167 },
  { label: 'Grust', value: 168 },
  { label: 'Grust', value: 169 },
  { label: 'Grust', value: 170 },
  { label: 'Grust', value: 171 },
  { label: 'Grust', value: 172 },
  { label: 'Grust', value: 173 },
  { label: 'Grust', value: 174 },
  { label: 'Grust', value: 175 },
  { label: 'Grust', value: 176 },
  { label: 'Grust', value: 177 },
  { label: 'Grust', value: 178 },
  { label: 'Dragoon', value: 179 },
  { label: 'Gra', value: 180 },
  { label: 'Gra', value: 181 },
  { label: 'Gra', value: 182 },
  { label: 'Gra', value: 183 },
  { label: 'Gra', value: 184 },
  { label: 'Gra', value: 185 },
  { label: 'Dragoon', value: 186 },
  { label: 'Khadein', value: 187 },
  { label: 'Khadein', value: 188 },
  { label: 'Khadein', value: 189 },
  { label: 'Khadein', value: 190 },
  { label: 'Grust', value: 191 },
  { label: 'Grust', value: 192 },
  { label: 'Grust', value: 193 },
  { label: 'Grust', value: 194 },
  { label: 'Grust', value: 195 },
  { label: 'Grust', value: 196 },
  { label: 'Grust', value: 197 },
  { label: 'Grust', value: 198 },
  { label: 'Grust', value: 199 },
  { label: 'Dolhr', value: 200 },
  { label: 'Dolhr', value: 201 },
  { label: 'Dolhr', value: 202 },
  { label: 'Dolhr', value: 203 },
  { label: 'Dolhr', value: 204 },
  { label: 'Dolhr', value: 205 },
  { label: 'Dolhr', value: 206 },
  { label: 'Dolhr', value: 207 },
  { label: 'Dolhr', value: 208 },
  { label: 'Dolhr', value: 209 },
  { label: 'Sable', value: 210 },
  { label: 'Sable', value: 211 },
  { label: 'Sable', value: 212 },
  { label: 'Sable', value: 213 },
  { label: 'Raman', value: 214 },
  { label: 'Raman', value: 215 },
  { label: 'Raman', value: 216 },
  { label: 'Raman', value: 217 },
  { label: 'Raman', value: 218 },
  { label: 'Raman', value: 219 },
  { label: 'Raman', value: 220 },
  { label: 'Sable', value: 221 },
  { label: 'Sable', value: 222 },
  { label: 'Sable', value: 223 },
  { label: 'Sable', value: 224 },
  { label: 'Sable', value: 225 },
  { label: 'Sable', value: 226 },
  { label: 'Sable', value: 227 },
  { label: 'Grust', value: 228 },
  { label: 'Grust', value: 229 },
  { label: 'Grust', value: 230 },
  { label: 'Grust', value: 231 },
  { label: 'Dragoon', value: 232 },
  { label: 'Dragoon', value: 233 },
  { label: 'Dragoon', value: 234 },
  { label: 'Dragoon', value: 235 },
  { label: 'Dragoon', value: 236 },
  { label: 'Dragoon', value: 237 },
  { label: 'Dragoon', value: 238 },
  { label: 'Dragoon', value: 239 },
  { label: 'Dragoon', value: 240 },
  { label: 'Dragoon', value: 241 },
  { label: 'Dragoon', value: 242 },
  { label: 'Dragoon', value: 243 },
  { label: 'Dragoon', value: 244 },
  { label: 'Dragoon', value: 245 },
  { label: 'Dragoon', value: 246 },
  { label: 'Dolhr', value: 247 },
  { label: 'Dolhr', value: 248 },
  { label: 'Dolhr', value: 249 },
  { label: 'Khadein', value: 250 },
  { label: 'Khadein', value: 251 },
  { label: 'Khadein', value: 252 },
  { label: 'Dolhr', value: 253 },
  { label: 'Dolhr', value: 254 },
  { label: 'Dolhr', value: 255 },
  { label: 'Dolhr', value: 256 },
  { label: 'Dolhr', value: 257 },
  { label: 'Dolhr', value: 258 },
  { label: 'Dolhr', value: 259 },
  { label: 'Dolhr', value: 260 },
  { label: 'Dolhr', value: 261 },
  { label: 'Dolhr', value: 262 },
  { label: 'Dolhr', value: 263 },
  { label: 'Dolhr', value: 264 },
  { label: 'Dolhr', value: 265 },
  { label: 'Dolhr', value: 266 },
  { label: 'Dolhr', value: 267 },
  { label: 'Dolhr', value: 268 },
  { label: 'Dolhr', value: 269 },
  { label: 'Opponent', value: 270 },
  { label: 'Opponent', value: 271 },
  { label: 'Opponent', value: 272 },
  { label: 'Opponent', value: 273 },
  { label: 'Opponent', value: 274 },
  { label: 'Opponent', value: 275 },
  { label: 'Opponent', value: 276 },
  { label: 'Opponent', value: 277 },
  { label: 'Opponent', value: 278 },
  { label: 'Opponent', value: 279 },
  { label: 'Opponent', value: 280 },
  { label: 'Opponent', value: 281 },
  { label: 'Opponent', value: 282 },
  { label: 'Opponent', value: 283 },
  { label: 'Opponent', value: 284 },
  { label: 'Opponent', value: 285 },
  { label: 'Opponent', value: 286 },
  { label: 'Opponent', value: 287 },
  { label: 'Opponent', value: 288 },
  { label: 'Opponent', value: 289 },
  { label: 'Opponent', value: 290 },
  { label: 'Opponent', value: 291 },
  { label: 'Opponent', value: 292 },
  { label: 'Gra', value: 293 },
  { label: 'Gra', value: 294 },
  { label: 'Gra', value: 295 },
  { label: 'Gra', value: 296 },
  { label: 'Nyna', value: 297 },
  { label: 'Malledus', value: 298 },
  { label: 'Soldier', value: 299 },
  { label: 'Bathys', value: 300 },
  { label: 'Dejanira', value: 301 },
  { label: 'Dactyl', value: 302 },
  { label: 'Larissa', value: 303 },
  { label: 'Soldier', value: 304 },
  { label: 'Soldier', value: 305 },
  { label: 'Soldier', value: 306 },
  { label: 'Soldier', value: 307 },
  { label: 'Soldier', value: 308 },
  { label: 'Soldier', value: 309 },
  { label: 'Captain', value: 310 },
  { label: 'Gra', value: 311 },
  { label: 'Gra', value: 312 },
  { label: 'Gra', value: 313 },
  { label: 'Gra', value: 314 },
  { label: 'Gra', value: 315 },
  { label: 'Gra', value: 316 },
  { label: 'Gra', value: 317 },
  { label: 'Gra', value: 318 },
  { label: 'Gra', value: 319 },
  { label: 'Gra', value: 320 },
  { label: 'Gra', value: 321 },
  { label: 'Gra', value: 322 },
  { label: 'Gra', value: 323 },
  { label: 'Ruffian', value: 324 },
  { label: 'Ruffian', value: 325 },
  { label: 'Ruffian', value: 326 },
  { label: 'Ruffian', value: 327 },
  { label: 'Grust', value: 328 },
  { label: 'Grust', value: 329 },
  { label: 'Archanea', value: 330 },
  { label: 'Archanea', value: 331 },
  { label: 'Grust', value: 332 },
  { label: 'Grust', value: 333 },
  { label: 'Grust', value: 334 },
  { label: 'Grust', value: 335 },
  { label: 'Ruffian', value: 336 },
  { label: 'Dolhr', value: 337 },
  { label: 'Grust', value: 338 },
  { label: 'Grust', value: 339 },
  { label: 'Grust', value: 340 },
  { label: 'Grust', value: 341 },
  { label: 'Grust', value: 342 },
  { label: 'Grust', value: 343 },
  { label: 'Grust', value: 344 },
  { label: 'Grust', value: 345 },
  { label: 'Grust', value: 346 },
  { label: 'Grust', value: 347 },
  { label: 'Grust', value: 348 },
  { label: 'Grust', value: 349 },
  { label: 'Dolhr', value: 350 },
  { label: 'Grust', value: 351 },
  { label: 'Grust', value: 352 },
  { label: 'Grust', value: 353 },
  { label: 'Grust', value: 354 },
  { label: 'Keeper', value: 355 },
  { label: 'Keeper', value: 356 },
  { label: 'Keeper', value: 357 },
  { label: 'Keeper', value: 358 },
  { label: 'Keeper', value: 359 },
  { label: 'Keeper', value: 360 },
  { label: 'Keeper', value: 361 },
  { label: 'Keeper', value: 362 },
  { label: 'Marth', value: 363 },
  { label: 'Gra', value: 364 },
  { label: 'Gra', value: 365 },
  { label: 'Gra', value: 366 },
  { label: 'Gra', value: 367 },
  { label: 'Gra', value: 368 },
  { label: 'Gra', value: 369 },
  { label: 'Gra', value: 370 },
  { label: 'Gra', value: 371 },
  { label: 'Dragoon', value: 372 },
  { label: 'Dragoon', value: 373 },
];

export const WeaponLevels = [
  { label: 'None or E', value: 0x00 },
  { label: 'D', value: 0x1E },
  { label: 'D Lv2', value: 0x28 },
  { label: 'D Lv3', value: 0x2D },
  { label: 'C', value: 0x4B },
  { label: 'B', value: 0x69 },
  { label: 'B Lv2', value: 0x87 },
  { label: 'A', value: 0xA5 },
  { label: 'A Lv2', value: 0xC3 },
];

export const SpecialWeaponAbilities = [
  { label: 'None', value: 0x00 },
  { label: 'Unknown', value: 0x01 },
  { label: 'Rapier & Falchion', value: 0x04 },
  { label: 'Aum Staff', value: 0x09 },
  { label: 'Earthstone', value: 0x10 },
  { label: 'Winged Spear', value: 0x29 },
  { label: 'Hammerne Staff', value: 0x41 },
  { label: 'Excalibur', value: 0x80 },
  { label: 'Aura', value: 0x101 },
  { label: 'Divinestone', value: 0x201 },
];

export const SpecialBonuses = [
  { label: 'None', value: 0x00 },
  { label: '+5% Hit', value: 0xF1 },
  { label: '+10% Hit', value: 0xF2 },
  { label: '+15% Hit', value: 0xF3 },
  { label: '+5% Critical', value: 0xF4 },
  { label: '+5% Hit, +5% Critical', value: 0xF5 },
  { label: '+10% Hit, +5% Critical', value: 0xF6 },
  { label: '+15% Hit, +5% Critical', value: 0xF7 },
  { label: '+10% Critical', value: 0xF8 },
  { label: '+5% Hit, +10% Critical', value: 0xF9 },
  { label: '+10% Hit, +10% Critical', value: 0xFA },
  { label: '+15% Hit, +10% Critical', value: 0xFB },
  { label: '+15% Critical', value: 0xFC },
  { label: '+5% Hit, +15% Critical', value: 0xFD },
  { label: '+5% Hit, +15% Critical', value: 0xFE },
  { label: '+15% Hit, +15% Critical', value: 0xFF },
];
