export const BattleAnimationPointers = [
  { label: 'FFF800 Pointer - 0x8FFF800', value: 0 },
  { label: 'FFF810 Pointer - 0x8FFF810', value: 1 },
  { label: 'FFF820 Pointer - 0x8FFF820', value: 2 },
  { label: 'FFF830 Pointer - 0x8FFF830', value: 3 },
  { label: 'FFF840 Pointer - 0x8FFF840', value: 4 },
  { label: 'FFF850 Pointer - 0x8FFF850', value: 5 },
  { label: 'FFF860 Pointer - 0x8FFF860', value: 6 },
  { label: 'FFF870 Pointer - 0x8FFF870', value: 7 },
  { label: 'FFF880 Pointer - 0x8FFF880', value: 8 },
  { label: 'FFF890 Pointer - 0x8FFF890', value: 9 },
  { label: 'FFF8A0 Pointer - 0x8FFF8A0', value: 10 },
  { label: 'FFF8B0 Pointer - 0x8FFF8B0', value: 11 },
  { label: 'FFF8C0 Pointer - 0x8FFF8C0', value: 12 },
  { label: 'FFF8D0 Pointer - 0x8FFF8D0', value: 13 },
  { label: 'FFF8E0 Pointer - 0x8FFF8E0', value: 14 },
  { label: 'FFF8F0 Pointer - 0x8FFF8F0', value: 15 },
  { label: 'FFF900 Pointer - 0x8FFF900', value: 16 },
  { label: 'FFF910 Pointer - 0x8FFF910', value: 17 },
  { label: 'FFF920 Pointer - 0x8FFF920', value: 18 },
  { label: 'FFF930 Pointer - 0x8FFF930', value: 19 },
  { label: 'FFF940 Pointer - 0x8FFF940', value: 20 },
  { label: 'FFF950 Pointer - 0x8FFF950', value: 21 },
  { label: 'FFF960 Pointer - 0x8FFF960', value: 22 },
  { label: 'FFF970 Pointer - 0x8FFF970', value: 23 },
  { label: 'FFF980 Pointer - 0x8FFF980', value: 24 },
  { label: 'FFF990 Pointer - 0x8FFF990', value: 25 },
  { label: 'FFF9A0 Pointer - 0x8FFF9A0', value: 26 },
  { label: 'FFF9B0 Pointer - 0x8FFF9B0', value: 27 },
  { label: 'FFF9C0 Pointer - 0x8FFF9C0', value: 28 },
  { label: 'FFF9D0 Pointer - 0x8FFF9D0', value: 29 },
  { label: 'FFF9E0 Pointer - 0x8FFF9E0', value: 30 },
  { label: 'FFF9F0 Pointer - 0x8FFF9F0', value: 31 },
  { label: 'FFFA00 Pointer - 0x8FFFA00', value: 32 },
  { label: 'FFFA10 Pointer - 0x8FFFA10', value: 33 },
  { label: 'FFFA20 Pointer - 0x8FFFA20', value: 34 },
  { label: 'FFFA30 Pointer - 0x8FFFA30', value: 35 },
  { label: 'FFFA40 Pointer - 0x8FFFA40', value: 36 },
  { label: 'FFFA50 Pointer - 0x8FFFA50', value: 37 },
  { label: 'FFFA60 Pointer - 0x8FFFA60', value: 38 },
  { label: 'FFFA70 Pointer - 0x8FFFA70', value: 39 },
  { label: 'FFFA80 Pointer - 0x8FFFA80', value: 40 },
  { label: 'FFFA90 Pointer - 0x8FFFA90', value: 41 },
  { label: 'FFFAA0 Pointer - 0x8FFFAA0', value: 42 },
  { label: 'FFFAB0 Pointer - 0x8FFFAB0', value: 43 },
  { label: 'FFFAC0 Pointer - 0x8FFFAC0', value: 44 },
  { label: 'FFFAD0 Pointer - 0x8FFFAD0', value: 45 },
  { label: 'FFFAE0 Pointer - 0x8FFFAE0', value: 46 },
  { label: 'FFFAF0 Pointer - 0x8FFFAF0', value: 47 },
  { label: 'FFFB00 Pointer - 0x8FFFB00', value: 48 },
  { label: 'FFFB10 Pointer - 0x8FFFB10', value: 49 },
  { label: 'FFFB20 Pointer - 0x8FFFB20', value: 50 },
  { label: 'FFFB30 Pointer - 0x8FFFB30', value: 51 },
  { label: 'FFFB40 Pointer - 0x8FFFB40', value: 52 },
  { label: 'FFFB50 Pointer - 0x8FFFB50', value: 53 },
  { label: 'FFFB60 Pointer - 0x8FFFB60', value: 54 },
  { label: 'FFFB70 Pointer - 0x8FFFB70', value: 55 },
  { label: 'FFFB80 Pointer - 0x8FFFB80', value: 56 },
  { label: 'FFFB90 Pointer - 0x8FFFB90', value: 57 },
  { label: 'FFFBA0 Pointer - 0x8FFFBA0', value: 58 },
  { label: 'FFFBB0 Pointer - 0x8FFFBB0', value: 59 },
  { label: 'FFFBC0 Pointer - 0x8FFFBC0', value: 60 },
  { label: 'FFFBD0 Pointer - 0x8FFFBD0', value: 61 },
  { label: 'FFFBE0 Pointer - 0x8FFFBE0', value: 62 },
  { label: 'FFFBF0 Pointer - 0x8FFFBF0', value: 63 },
  { label: 'FFFC00 Pointer - 0x8FFFC00', value: 64 },
  { label: 'FFFC10 Pointer - 0x8FFFC10', value: 65 },
  { label: 'FFFC20 Pointer - 0x8FFFC20', value: 66 },
  { label: 'FFFC30 Pointer - 0x8FFFC30', value: 67 },
  { label: 'FFFC40 Pointer - 0x8FFFC40', value: 68 },
  { label: 'FFFC50 Pointer - 0x8FFFC50', value: 69 },
  { label: 'FFFC60 Pointer - 0x8FFFC60', value: 70 },
  { label: 'FFFC70 Pointer - 0x8FFFC70', value: 71 },
  { label: 'FFFC80 Pointer - 0x8FFFC80', value: 72 },
  { label: 'FFFC90 Pointer - 0x8FFFC90', value: 73 },
  { label: 'FFFCA0 Pointer - 0x8FFFCA0', value: 74 },
  { label: 'FFFCB0 Pointer - 0x8FFFCB0', value: 75 },
  { label: 'FFFCC0 Pointer - 0x8FFFCC0', value: 76 },
  { label: 'FFFCD0 Pointer - 0x8FFFCD0', value: 77 },
  { label: 'FFFCE0 Pointer - 0x8FFFCE0', value: 78 },
  { label: 'FFFCF0 Pointer - 0x8FFFCF0', value: 79 },
  { label: 'FFFD00 Pointer - 0x8FFFD00', value: 80 },
  { label: 'FFFD10 Pointer - 0x8FFFD10', value: 81 },
  { label: 'FFFD20 Pointer - 0x8FFFD20', value: 82 },
  { label: 'FFFD30 Pointer - 0x8FFFD30', value: 83 },
  { label: 'FFFD40 Pointer - 0x8FFFD40', value: 84 },
  { label: 'FFFD50 Pointer - 0x8FFFD50', value: 85 },
  { label: 'FFFD60 Pointer - 0x8FFFD60', value: 86 },
  { label: 'FFFD70 Pointer - 0x8FFFD70', value: 87 },
  { label: 'FFFD80 Pointer - 0x8FFFD80', value: 88 },
  { label: 'FFFD90 Pointer - 0x8FFFD90', value: 89 },
  { label: 'FFFDA0 Pointer - 0x8FFFDA0', value: 90 },
  { label: 'FFFDB0 Pointer - 0x8FFFDB0', value: 91 },
  { label: 'FFFDC0 Pointer - 0x8FFFDC0', value: 92 },
  { label: 'FFFDD0 Pointer - 0x8FFFDD0', value: 93 },
  { label: 'FFFDE0 Pointer - 0x8FFFDE0', value: 94 },
  { label: 'FFFDF0 Pointer - 0x8FFFDF0', value: 95 },
  { label: 'FFFE00 Pointer - 0x8FFFE00', value: 96 },
  { label: 'FFFE10 Pointer - 0x8FFFE10', value: 97 },
  { label: 'FFFE20 Pointer - 0x8FFFE20', value: 98 },
  { label: 'FFFE30 Pointer - 0x8FFFE30', value: 99 },
  { label: 'FFFE40 Pointer - 0x8FFFE40', value: 100 },
  { label: 'FFFE50 Pointer - 0x8FFFE50', value: 101 },
  { label: 'FFFE60 Pointer - 0x8FFFE60', value: 102 },
  { label: 'FFFE70 Pointer - 0x8FFFE70', value: 103 },
  { label: 'FFFE80 Pointer - 0x8FFFE80', value: 104 },
  { label: 'FFFE90 Pointer - 0x8FFFE90', value: 105 },
  { label: 'FFFEA0 Pointer - 0x8FFFEA0', value: 106 },
  { label: 'FFFEB0 Pointer - 0x8FFFEB0', value: 107 },
  { label: 'FFFEC0 Pointer - 0x8FFFEC0', value: 108 },
  { label: 'FFFED0 Pointer - 0x8FFFED0', value: 109 },
  { label: 'FFFEE0 Pointer - 0x8FFFEE0', value: 110 },
  { label: 'FFFEF0 Pointer - 0x8FFFEF0', value: 111 },
];

export const AnimationTypes = [
  { label: 'All Swords/   Separator', value: 0x00 },
  { label: 'All Spears/   Iron Sword', value: 0x01 },
  { label: 'All Axes/   Thin Sword', value: 0x02 },
  { label: 'All Bows/   Steel Sword', value: 0x03 },
  { label: 'All Staves/   Silver Sword', value: 0x04 },
  { label: 'All Anima/   Iron Blade', value: 0x05 },
  { label: 'All Light/   Steel Blade', value: 0x06 },
  { label: 'All Dark/   Silver Blade', value: 0x07 },
  { label: 'Poison Sword', value: 0x08 },
  { label: 'Disarmed(required)/   Rapier', value: 0x09 },
  { label: 'Mani Katti', value: 0x0A },
  { label: 'Hero Sword', value: 0x0B },
  { label: 'Wo Dao', value: 0x0C },
  { label: 'Killer Sword', value: 0x0D },
  { label: 'Armour Killer', value: 0x0E },
  { label: 'Dragon Killer', value: 0x0F },
  { label: 'Light Sword', value: 0x10 },
  { label: 'Rune Sword', value: 0x11 },
  { label: 'Lancebuster', value: 0x12 },
  { label: 'Long Sword', value: 0x13 },
  { label: 'Iron Spear', value: 0x14 },
  { label: 'Thin Spear', value: 0x15 },
  { label: 'Steel Spear', value: 0x16 },
  { label: 'Silver Spear', value: 0x17 },
  { label: 'Poison Spear', value: 0x18 },
  { label: 'Hero Spear', value: 0x19 },
  { label: 'Killer Lance', value: 0x1A },
  { label: 'Horse Killer', value: 0x1B },
  { label: 'Javelin', value: 0x1C },
  { label: 'Slender Spear', value: 0x1D },
  { label: 'Axebuster', value: 0x1E },
  { label: 'Iron Axe', value: 0x1F },
  { label: 'Steel Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Poison Axe', value: 0x22 },
  { label: 'Hero Axe', value: 0x23 },
  { label: 'Killer Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Hammer', value: 0x26 },
  { label: 'Devil Axe', value: 0x27 },
  { label: 'Hand Axe', value: 0x28 },
  { label: 'Tomahawk', value: 0x29 },
  { label: 'Swordbuster', value: 0x2A },
  { label: 'Sword Killer', value: 0x2B },
  { label: 'Iron Bow', value: 0x2C },
  { label: 'Steel Bow', value: 0x2D },
  { label: 'Silver Bow', value: 0x2E },
  { label: 'Poison Bow', value: 0x2F },
  { label: 'Killer Bow', value: 0x30 },
  { label: 'Hero Bow', value: 0x31 },
  { label: 'Short Bow', value: 0x32 },
  { label: 'Longbow', value: 0x33 },
  { label: 'Ballista', value: 0x34 },
  { label: 'Iron Ballista', value: 0x35 },
  { label: 'Killer Ballista', value: 0x36 },
  { label: 'Fire', value: 0x37 },
  { label: 'Thunder', value: 0x38 },
  { label: 'Elfire', value: 0x39 },
  { label: 'Thunderstorm', value: 0x3A },
  { label: 'Fimbulvetr', value: 0x3B },
  { label: 'Forblaze', value: 0x3C },
  { label: 'Excalibur', value: 0x3D },
  { label: 'Lightning', value: 0x3E },
  { label: 'Shine', value: 0x3F },
  { label: 'Divine', value: 0x40 },
  { label: 'Purge', value: 0x41 },
  { label: 'Aura', value: 0x42 },
  { label: 'Luce', value: 0x43 },
  { label: 'Flux', value: 0x44 },
  { label: 'Luna', value: 0x45 },
  { label: 'Nosferatu', value: 0x46 },
  { label: 'Eclipse', value: 0x47 },
  { label: 'Fenrir', value: 0x48 },
  { label: 'Gespenst', value: 0x49 },
  { label: 'Dragon Axe', value: 0x59 },
  { label: 'Uber Spear', value: 0x77 },
  { label: 'Dragon Ring', value: 0x7F },
  { label: 'Emblem Sword', value: 0x80 },
  { label: 'Emblem Spear', value: 0x81 },
  { label: 'Emblem Axe', value: 0x82 },
  { label: 'Emblem Bow', value: 0x83 },
  { label: 'Durandal', value: 0x84 },
  { label: 'Armads', value: 0x85 },
  { label: 'Aureola', value: 0x86 },
  { label: 'Sol Katti', value: 0x8C },
  { label: 'Wolf Beil', value: 0x8D },
  { label: 'Ereshkigal', value: 0x8E },
  { label: 'Fire Dragon Stone', value: 0x8F },
  { label: 'Regal Blade', value: 0x90 },
  { label: 'Rex Hasta', value: 0x91 },
  { label: 'Basilikos', value: 0x92 },
  { label: 'Rienfleche', value: 0x93 },
  { label: 'Heavy Spear', value: 0x94 },
  { label: 'Short Spear', value: 0x95 },
  { label: 'Wind Sword', value: 0x99 },
];

export const WeaponAnimationType = [
  { label: 'Custom Animation for a Weapon', value: 0x00 },
  { label: 'All Weapons for a Weapon Type', value: 0x01 },
];

export const AnimationList = [
  { label: 'None (map animation)', value: 0x00 },
  { label: 'Eliwood', value: 0x01 },
  { label: 'Eliwood Disarmed', value: 0x02 },
  { label: 'Lord Knight Eliwood w/ Sword', value: 0x03 },
  { label: 'Lord Knight Eliwood w/ Durandal', value: 0x04 },
  { label: 'Lord Knight Eliwood w/ Spear', value: 0x05 },
  { label: 'Lord Knight Eliwood Disarmed', value: 0x06 },
  { label: 'Hector', value: 0x07 },
  { label: 'Hector w/ Hand Axe', value: 0x08 },
  { label: 'Hector Disarmed', value: 0x09 },
  { label: 'Great Lord Hector w/ Axe', value: 0x0A },
  { label: 'Great Lord Hector w/ Hand Axe', value: 0x0B },
  { label: 'Great Lord Hector w/ Armads', value: 0x0C },
  { label: 'Great Lord Hector w/ Sword', value: 0x0D },
  { label: 'Great Lord Hector Disarmed', value: 0x0E },
  { label: 'Lyn', value: 0x0F },
  { label: 'Lyn Disarmed', value: 0x10 },
  { label: 'Blade Lord Lyn w/ Sword', value: 0x11 },
  { label: 'Blade Lord Lyn w/ Sol Katti', value: 0x12 },
  { label: 'Blade Lord Lyn w/ Bow', value: 0x13 },
  { label: 'Blade Lord Lyn Disarmed', value: 0x14 },
  { label: 'Mountain Thief', value: 0x15 },
  { label: 'Mountain Thief w/ Hand Axe', value: 0x16 },
  { label: 'Mountain Thief Disarmed', value: 0x17 },
  { label: 'Pirate', value: 0x18 },
  { label: 'Pirate w/ Hand Axe', value: 0x19 },
  { label: 'Pirate Disarmed', value: 0x1A },
  { label: 'Hawkeye', value: 0x1B },
  { label: 'Hawkeye w/ Hand Axe', value: 0x1C },
  { label: 'Hawkeye Disarmed', value: 0x1D },
  { label: 'Fighter', value: 0x1E },
  { label: 'Fighter w/ Hand Axe', value: 0x1F },
  { label: 'Fighter Disarmed', value: 0x20 },
  { label: 'Warrior w/ Axe', value: 0x21 },
  { label: 'Warrior w/ Hand Axe', value: 0x22 },
  { label: 'Warrior w/ Bow', value: 0x23 },
  { label: 'Warrior Disarmed', value: 0x24 },
  { label: 'Archer', value: 0x25 },
  { label: 'Archer Disarmed', value: 0x26 },
  { label: 'Archer (F)', value: 0x27 },
  { label: 'Archer (F) Disarmed', value: 0x28 },
  { label: 'Sniper', value: 0x29 },
  { label: 'Sniper Disarmed', value: 0x2A },
  { label: 'Sniper (F)', value: 0x2B },
  { label: 'Sniper (F) Disarmed', value: 0x2C },
  { label: 'Mercenary', value: 0x2D },
  { label: 'Mercenary Disarmed', value: 0x2E },
  { label: 'Hero w/ Sword', value: 0x2F },
  { label: 'Hero w/ Axe', value: 0x30 },
  { label: 'Hero w/ Hand Axe', value: 0x31 },
  { label: 'Hero Disarmed', value: 0x32 },
  { label: 'Swordfighter', value: 0x33 },
  { label: 'Swordfighter Disarmed', value: 0x34 },
  { label: 'Swordmaster', value: 0x35 },
  { label: 'Swordmaster Disarmed', value: 0x36 },
  { label: 'Lloyd', value: 0x37 },
  { label: 'Lloyd Disarmed', value: 0x38 },
  { label: 'Swordmaster (F)', value: 0x39 },
  { label: 'Swordmaster (F) Disarmed', value: 0x3A },
  { label: 'Socialknight w/ Spear', value: 0x3B },
  { label: 'Socialknight w/ Sword', value: 0x3C },
  { label: 'Socialknight Disarmed', value: 0x3D },
  { label: 'Socialknight w/ Spear (again?)', value: 0x3E },
  { label: 'Assassin Legault', value: 0x3F },
  { label: 'Assassin Legault Disarmed', value: 0x40 },
  { label: 'Paladin w/ Axe', value: 0x41 },
  { label: 'Paladin w/ Hand Axe', value: 0x42 },
  { label: 'Paladin w/ Sword', value: 0x43 },
  { label: 'Paladin w/ Spear', value: 0x44 },
  { label: 'Paladin Disarmed', value: 0x45 },
  { label: 'Paladin w/ Axe', value: 0x46 },
  { label: 'Paladin w/ Hand Axe', value: 0x47 },
  { label: 'Paladin w/ Sword', value: 0x48 },
  { label: 'Paladin w/ Spear', value: 0x49 },
  { label: 'Paladin Disarmed', value: 0x4A },
  { label: 'Isadora w/ Axe', value: 0x4B },
  { label: 'Isadora w/ Hand Axe', value: 0x4C },
  { label: 'Isadora w/ Sword', value: 0x4D },
  { label: 'Isadora w/ Spear', value: 0x4E },
  { label: 'Isadora Disarmed', value: 0x4F },
  { label: 'Soldier', value: 0x50 },
  { label: 'Soldier Disarmed', value: 0x51 },
  { label: 'Armour Knight', value: 0x52 },
  { label: 'Armour Knight Disarmed', value: 0x53 },
  { label: 'General w/ Spear', value: 0x54 },
  { label: 'General w/ Axe', value: 0x55 },
  { label: 'General w/ Hand Axe', value: 0x56 },
  { label: 'General Disarmed', value: 0x57 },
  { label: 'Mage', value: 0x58 },
  { label: 'Nino', value: 0x59 },
  { label: 'Sage', value: 0x5A },
  { label: 'Sage w/ Staff', value: 0x5B },
  { label: 'Sage (F)', value: 0x5C },
  { label: 'Sage (F) w/ Staff', value: 0x5D },
  { label: 'Sage Nino', value: 0x5E },
  { label: 'Sage Nino w/ Staff', value: 0x5F },
  { label: 'Priest', value: 0x60 },
  { label: 'Priest Disarmed', value: 0x61 },
  { label: 'Serra', value: 0x62 },
  { label: 'Serra Disarmed', value: 0x63 },
  { label: 'Monk', value: 0x64 },
  { label: 'Bishop', value: 0x65 },
  { label: 'Bishop w/ Staff', value: 0x66 },
  { label: 'Bishop Serra', value: 0x67 },
  { label: 'Bishop Serra w/ Staff', value: 0x68 },
  { label: 'Shaman', value: 0x69 },
  { label: 'Druid', value: 0x6A },
  { label: 'Druid w/ Staff', value: 0x6B },
  { label: 'Dark Druid', value: 0x6C },
  { label: 'Dark Druid w/ Staff (messed up)', value: 0x6D },
  { label: 'Troubadour', value: 0x6E },
  { label: 'Troubadour Disarmed', value: 0x6F },
  { label: 'Valkyrie', value: 0x70 },
  { label: 'Valkyrie w/ Staff', value: 0x71 },
  { label: 'Athos', value: 0x72 },
  { label: 'Athos w/ Staff', value: 0x73 },
  { label: 'Nomad', value: 0x74 },
  { label: 'Nomad Disarmed', value: 0x75 },
  { label: 'Nomad Trooper w/ Sword', value: 0x76 },
  { label: 'Nomad Trooper w/ Bow', value: 0x77 },
  { label: 'Nomad Trooper Disarmed', value: 0x78 },
  { label: 'Thief', value: 0x79 },
  { label: 'Thief Disarmed', value: 0x7A },
  { label: 'Legault', value: 0x7B },
  { label: 'Legault Disarmed', value: 0x7C },
  { label: 'Leila', value: 0x7D },
  { label: 'Leila Disarmed', value: 0x7E },
  { label: 'Assassin', value: 0x7F },
  { label: 'Assassin Disarmed', value: 0x80 },
  { label: 'Pegasus Knight', value: 0x81 },
  { label: 'Pegasus Knight Disarmed', value: 0x82 },
  { label: 'Falcon Knight w/ Sword', value: 0x83 },
  { label: 'Falcon Knight w/ Spear', value: 0x84 },
  { label: 'Falcon Knight Disarmed', value: 0x85 },
  { label: 'Dragon Knight', value: 0x86 },
  { label: 'Dragon Knight Disarmed', value: 0x87 },
  { label: 'Dragon Master w/ Spear', value: 0x88 },
  { label: 'Dragon Master w/ Sword', value: 0x89 },
  { label: 'Dragon Master Disarmed', value: 0x8A },
  { label: 'Fire Dragon', value: 0x8B },
  { label: 'Archer on Ballista (unused, but still here from FE6)', value: 0x8C },
  { label: 'Dancer', value: 0x8D },
  { label: 'Bard', value: 0x8E },
  { label: 'Lucius', value: 0x8F },
  { label: 'Hero w/ Coat w/ Sword', value: 0x90 },
  { label: 'Hero w/ Coat w/ Axe', value: 0x91 },
  { label: 'Hero w/ Coat w/ Hand Axe', value: 0x92 },
  { label: 'Hero w/ Coat Disarmed', value: 0x93 },
  { label: 'Bishop Lucius', value: 0x94 },
  { label: 'Bishop Lucius w/ Staff', value: 0x95 },
  { label: 'Bishop Lucius Disarmed', value: 0x96 },
  { label: 'Bishop Disarmed', value: 0x97 },
  { label: 'Serra Disarmed', value: 0x98 },
  { label: 'Guy', value: 0x99 },
  { label: 'Guy Disarmed', value: 0x9A },
  { label: 'Swordmaster Guy', value: 0x9B },
  { label: 'Guy Disarmed', value: 0x9C },
  { label: 'Berserker', value: 0x9D },
  { label: 'Berserker w/ Hand Axe', value: 0x9E },
  { label: 'Berserker Disarmed', value: 0x9F },
  { label: 'Magic Seal', value: 0xA0 },
  { label: 'Tent', value: 0xA1 },
  { label: 'Transporter', value: 0xA2 },
];

export const AlwaysZero = [
  { label: '----------Always Zero----------', value: 0x00 },
];
