export const MovementTypes = [
  { label: '0xBE3888 - Def: Lord, Blade Lord, Hero, Swordmaster, Sniper', value: 0 },
  { label: '0xBE38C9 - Def: Mercenary, Myrmidon, Archer, Soldier, Dancer, Bard', value: 1 },
  { label: '0xBE390A - Def: Great Lord, Knight, General', value: 2 },
  { label: '0xBE394B - Def: Fighter, Warrior', value: 3 },
  { label: '0xBE398C - Def: Berserker', value: 4 },
  { label: '0xBE39CD - Def: Brigand', value: 5 },
  { label: '0xBE3A0E - Def: Pirate, Corsair', value: 6 },
  { label: '0xBE3A4F - Def: Thief, Assasin', value: 7 },
  { label: '0xBE3A90 - Def: Monk, Cleric, Bishop, Mage, Sage, Shaman, Druid, Archsage, Magic Seal, Dark Druid', value: 8 },
  { label: '0xBE3AD1 - Def: Civilian, Transporter, Child, Bramimond, Peer, Prince, Queen, Hung Leila', value: 9 },
  { label: '0xBE3B12 - Def: Cavalier, Troubadour', value: 10 },
  { label: '0xBE3B53 - Def: Knight Lord, Paladin, Valkyrie', value: 11 },
  { label: '0xBE3B94 - Def: Nomad', value: 12 },
  { label: '0xBE3BD5 - Def: Nomad Trooper', value: 13 },
  { label: '0xBE3C16 - Def: Pegasus Knight, Falco Knight, Wyvern Rider, Wyvern Lord', value: 14 },
  { label: '0xBE3C57 - Def: Fire Dragon, Ice Dragon', value: 15 },
  { label: '0xBE3C98 -', value: 16 },
  { label: '0xBE3CD9 - Def (RAIN): Lord, Blade Lord, Hero, Swordmaster, Sniper', value: 17 },
  { label: '0xBE3D1A - Def (RAIN): Mercenary, Myrmidon, Archer, Soldier, Dancer, Bard', value: 18 },
  { label: '0xBE3D5B - Def (RAIN): Great Lord, Knight, General', value: 19 },
  { label: '0xBE3D9C - Def (RAIN): Fighter, Warrior', value: 20 },
  { label: '0xBE3DDD - Def (RAIN): Berserker', value: 21 },
  { label: '0xBE3E1E - Def (RAIN): Brigand', value: 22 },
  { label: '0xBE3E5F - Def (RAIN): Pirate, Corsair', value: 23 },
  { label: '0xBE3EA0 - Def (RAIN): Thief, Assasin', value: 24 },
  { label: '0xBE3EE1 - Def (RAIN): Monk, Cleric, Bishop, Mage, Sage, Shaman, Druid, Archsage, Magic Seal, Dark Druid', value: 25 },
  { label: '0xBE3F22 - Def (RAIN): Civilian, Transporter, Child, Bramimond, Peer, Prince, Queen, Hung Leila', value: 26 },
  { label: '0xBE3F63 - Def (RAIN): Cavalier, Troubadour', value: 27 },
  { label: '0xBE3FA4 - Def (RAIN): Knight Lord, Paladin, Valkyrie', value: 28 },
  { label: '0xBE3FE5 - Def (RAIN): Nomad', value: 29 },
  { label: '0xBE4026 - Def (RAIN): Nomad Trooper', value: 30 },
  { label: '0xBE4067 - Def (RAIN): Pegasus Knight, Falco Knight, Wyvern Rider, Wyvern Lord', value: 31 },
  { label: '0xBE40A8 -', value: 32 },
  { label: '0xBE40E9 - Def (SNOW): Lord, Blade Lord, Hero, Swordmaster, Sniper', value: 33 },
  { label: '0xBE412A - Def (SNOW): Mercenary, Myrmidon, Archer, Soldier, Dancer, Bard', value: 34 },
  { label: '0xBE416B - Def (SNOW): Great Lord, Knight, General', value: 35 },
  { label: '0xBE41AC - Def (SNOW): Fighter, Warrior', value: 36 },
  { label: '0xBE41ED - Def (SNOW): Berserker', value: 37 },
  { label: '0xBE422E - Def (SNOW): Brigand', value: 38 },
  { label: '0xBE426F - Def (SNOW): Pirate, Corsair', value: 39 },
  { label: '0xBE42B0 - Def (SNOW): Thief, Assasin', value: 40 },
  { label: '0xBE42F1 - Def (SNOW): Monk, Cleric, Bishop, Mage, Sage, Shaman, Druid, Archsage, Magic Seal, Dark Druid', value: 41 },
  { label: '0xBE4332 - Def (SNOW): Civilian, Transporter, Child, Bramimond, Peer, Prince, Queen, Hung Leila', value: 42 },
  { label: '0xBE4373 - Def (SNOW): Cavalier, Troubadour', value: 43 },
  { label: '0xBE43B4 - Def (SNOW): Knight Lord, Paladin, Valkyrie', value: 44 },
  { label: '0xBE43F5 - Def (SNOW): Nomad', value: 45 },
  { label: '0xBE4436 - Def (SNOW): Nomad Trooper', value: 46 },
  { label: '0xBE4477 - Def (SNOW): Pegasus Knight, Falco Knight, Wyvern Rider, Wyvern Lord', value: 47 },
  { label: '0xBE44B8 -', value: 48 },
];

export default MovementTypes;
