export const Shops = [
  { label: '0x00 Shop 1', value: 0 },
  { label: '0x01 Shop 2', value: 1 },
  { label: '0x02 Shop 3', value: 2 },
  { label: '0x03 Shop 4', value: 3 },
  { label: '0x04 Shop 5', value: 4 },
  { label: '0x05 Shop 6', value: 5 },
  { label: '0x06 Shop 7', value: 6 },
  { label: '0x07 Shop 8', value: 7 },
  { label: '0x08 Shop 9', value: 8 },
  { label: '0x09 Shop 10', value: 9 },
  { label: '0x0A Shop 11', value: 10 },
  { label: '0x0B Shop 12', value: 11 },
  { label: '0x0C Shop 13', value: 12 },
  { label: '0x0D Shop 14', value: 13 },
  { label: '0x0E Shop 15', value: 14 },
  { label: '0x0F Shop 16', value: 15 },
  { label: '0x10 Shop 17', value: 16 },
  { label: '0x11 Shop 18', value: 17 },
  { label: '0x12 Shop 19', value: 18 },
  { label: '0x13 Shop 20', value: 19 },
  { label: '0x14 Shop 21', value: 20 },
  { label: '0x15 Shop 22', value: 21 },
  { label: '0x16 Shop 23', value: 22 },
  { label: '0x17 Shop 24', value: 23 },
  { label: '0x18 Shop 25', value: 24 },
  { label: '0x19 Shop 26', value: 25 },
  { label: '0x1A Shop 27', value: 26 },
  { label: '0x1B Shop 28', value: 27 },
  { label: '0x1C Shop 29', value: 28 },
  { label: '0x1D Shop 30', value: 29 },
  { label: '0x1E Shop 31', value: 30 },
  { label: '0x1F Shop 32', value: 31 },
  { label: '0x20 Shop 33', value: 32 },
  { label: '0x21 Shop 34', value: 33 },
  { label: '0x22 Shop 35', value: 34 },
  { label: '0x23 Shop 36', value: 35 },
  { label: '0x24 Shop 37', value: 36 },
  { label: '0x25 Shop 38', value: 37 },
  { label: '0x26 Shop 39', value: 38 },
];

export const items = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Steel Sword', value: 0x01 },
  { label: 'Silver Sword', value: 0x02 },
  { label: 'Rapier', value: 0x03 },
  { label: 'Killer Sword', value: 0x04 },
  { label: 'Devil Sword', value: 0x05 },
  { label: 'Broken Sword', value: 0x06 },
  { label: 'Master Sword', value: 0x07 },
  { label: 'Lady Sword', value: 0x08 },
  { label: 'Thunder Sword', value: 0x09 },
  { label: 'Miracle Sword', value: 0x0A },
  { label: 'Falchion', value: 0x0B },
  { label: 'Armor Killer', value: 0x0C },
  { label: 'Dragon Killer', value: 0x0D },
  { label: 'Sword Killer', value: 0x0E },
  { label: 'Iron Lance', value: 0x0F },
  { label: 'Steel Lance', value: 0x10 },
  { label: 'Silver Lance', value: 0x11 },
  { label: 'Knight Killer', value: 0x12 },
  { label: 'Hand Spear', value: 0x13 },
  { label: 'Broken Lance', value: 0x14 },
  { label: 'Killer Lance', value: 0x15 },
  { label: 'Thin Lance', value: 0x16 },
  { label: 'Gladius', value: 0x17 },
  { label: 'Iron Bow', value: 0x18 },
  { label: 'Broken Bow', value: 0x19 },
  { label: 'Steel Bow', value: 0x1A },
  { label: 'Silver Bow', value: 0x1B },
  { label: 'Killer Bow', value: 0x1C },
  { label: 'Partia', value: 0x1D },
  { label: 'Iron Axe', value: 0x1E },
  { label: 'Steel Axe', value: 0x1F },
  { label: 'Hand Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Devil Axe', value: 0x22 },
  { label: 'Broken Axe', value: 0x23 },
  { label: 'Thunderbolt', value: 0x24 },
  { label: 'Quick Rain', value: 0x25 },
  { label: 'Stone Hedge', value: 0x26 },
  { label: 'Fire Gun', value: 0x27 },
  { label: 'Elephant', value: 0x28 },
  { label: 'Fire Breath', value: 0x29 },
  { label: 'Ice Breath', value: 0x2A },
  { label: 'Dark Breath', value: 0x2B },
  { label: 'Mist Breath', value: 0x2C },
  { label: 'Fire', value: 0x2D },
  { label: 'Thunder', value: 0x2E },
  { label: 'Blizza', value: 0x2F },
  { label: 'Shaver', value: 0x30 },
  { label: 'Elfire', value: 0x31 },
  { label: 'Torron', value: 0x32 },
  { label: 'Volcannon', value: 0x33 },
  { label: 'Excalibur', value: 0x34 },
  { label: 'Aura', value: 0x35 },
  { label: 'Starlight', value: 0x36 },
  { label: 'Maph', value: 0x37 },
  { label: 'Durarm', value: 0x38 },
  { label: 'Rizziah', value: 0x39 },
  { label: 'Meteor', value: 0x3A },
  { label: 'Worm', value: 0x3B },
  { label: 'Earth Orb', value: 0x3C },
  { label: 'Shield of Seals', value: 0x3D },
  { label: 'Dark Orb', value: 0x3E },
  { label: 'Fire Emblem', value: 0x3F },
  { label: 'Live', value: 0x40 },
  { label: 'Recover', value: 0x41 },
  { label: 'Libro', value: 0x42 },
  { label: 'Relive', value: 0x43 },
  { label: 'Warp', value: 0x44 },
  { label: 'Magic Shield', value: 0x45 },
  { label: 'Hammerne', value: 0x46 },
  { label: 'Reserve', value: 0x47 },
  { label: 'Silence', value: 0x48 },
  { label: 'Rescue', value: 0x49 },
  { label: 'Oum', value: 0x4A },
  { label: 'Unlock', value: 0x4B },
  { label: 'Thief', value: 0x4C },
  { label: 'Watch', value: 0x4D },
  { label: 'Again', value: 0x4E },
  { label: 'Fire Dragon Stone', value: 0x4F },
  { label: 'Oum', value: 0x50 },
  { label: 'Ice Dragon Stone', value: 0x51 },
  { label: 'Flying Dragon Stone', value: 0x52 },
  { label: 'Earth Dragon Stone', value: 0x53 },
  { label: 'Dark Dragon Stone', value: 0x54 },
  { label: 'Divine Dragon Stone', value: 0x55 },
  { label: 'Demon Dragon Stone', value: 0x56 },
  { label: 'Vulnerary', value: 0x57 },
  { label: 'Door Key', value: 0x58 },
  { label: 'Silver Key', value: 0x59 },
  { label: 'Bridge Key', value: 0x5A },
  { label: 'Treasure Key', value: 0x5B },
  { label: 'Power Ring', value: 0x5C },
  { label: 'Shield Ring', value: 0x5D },
  { label: 'Secret Book', value: 0x5E },
  { label: 'Speed Ring', value: 0x5F },
  { label: 'Amulet', value: 0x60 },
  { label: 'Angel Robe', value: 0x61 },
  { label: 'Goddess Statue', value: 0x62 },
  { label: 'Manual', value: 0x63 },
  { label: 'Boots', value: 0x64 },
  { label: 'Pure Water', value: 0x65 },
  { label: 'Knight Medal', value: 0x66 },
  { label: 'Hero Proof', value: 0x67 },
  { label: 'Priest Ring', value: 0x68 },
  { label: 'Dragon Whip', value: 0x69 },
  { label: 'Orion Arrow', value: 0x6A },
  { label: 'Earth Orb', value: 0x6B },
  { label: 'Life Orb', value: 0x6C },
  { label: 'Aiote Shield', value: 0x6D },
  { label: 'Aquarius Orb', value: 0x6E },
  { label: 'Pisces Orb', value: 0x6F },
  { label: 'Aries Orb', value: 0x70 },
  { label: 'Taurus Orb', value: 0x71 },
  { label: 'Gemini Orb', value: 0x72 },
  { label: 'Cancer Orb', value: 0x73 },
  { label: 'Leo Orb', value: 0x74 },
  { label: 'Virgo Orb', value: 0x75 },
  { label: 'Libra Orb', value: 0x76 },
  { label: 'Scorpio Orb', value: 0x77 },
  { label: 'Sagittarius Orb', value: 0x78 },
  { label: 'Capricorn Orb', value: 0x79 },
  { label: 'Oum Fragment', value: 0x7A },
  { label: 'Silver Card', value: 0x7B },
  { label: 'Member Card', value: 0x7C },
  { label: 'Light Orb', value: 0x7D },
  { label: 'Star Orb', value: 0x7E },
  { label: 'End Byte', value: 0xFE },
  { label: 'Nothing', value: 0xFF },
];
