export const Pointers = [
  { label: 'Not used', value: 0 },
  { label: 'Object type', value: 1 },
  { label: 'Map Palette 1', value: 2 },
  { label: 'Tile Configuration', value: 3 },
  { label: 'Prologue Map', value: 4 },
  { label: 'Tile animations 1', value: 5 },
  { label: 'Prologue Map changes', value: 6 },
  { label: 'Prologue events', value: 7 },
  { label: 'Ch 1 Map', value: 8 },
  { label: 'Ch 1 map changes', value: 9 },
  { label: 'Ch 1 events', value: 10 },
  { label: 'Ch 2 map', value: 11 },
  { label: 'Ch 2 Tile changes', value: 12 },
  { label: 'Ch 2 events', value: 13 },
  { label: 'Object type 2', value: 14 },
  { label: 'Map palette 2', value: 15 },
  { label: 'Tile configuration 2', value: 16 },
  { label: 'Ch 3 map', value: 17 },
  { label: 'Tile animations 2', value: 18 },
  { label: 'Ch 3 map changes', value: 19 },
  { label: 'Ch 3 events', value: 20 },
  { label: 'Ch 4 Map', value: 21 },
  { label: 'Ch 4 Map changes', value: 22 },
  { label: 'Ch 4 events', value: 23 },
  { label: 'Object type 3', value: 24 },
  { label: 'Map palette 3', value: 25 },
  { label: 'Tile confihutation 3', value: 26 },
  { label: 'Ch 5x map', value: 27 },
  { label: 'Tile animations 3', value: 28 },
  { label: 'Ch 5x Map changes', value: 29 },
  { label: 'Ch 5x Events', value: 30 },
  { label: 'Ch 5 Map', value: 31 },
  { label: 'Ch 5 map changes', value: 32 },
  { label: 'Ch 5 event data', value: 33 },
  { label: 'Ch 6 map', value: 34 },
  { label: 'Ch 6 Map changes', value: 35 },
  { label: 'Ch 6 events', value: 36 },
  { label: 'Ch 7 map', value: 37 },
  { label: 'Ch 7 map changes', value: 38 },
  { label: 'Ch 7 event data', value: 39 },
  { label: 'Ch 8 map', value: 40 },
  { label: 'Ch 8 map changes', value: 41 },
  { label: 'Ch 8 event data', value: 42 },
  { label: 'Ch 9 Eir. map', value: 43 },
  { label: 'Ch 9 Eir. map changes', value: 44 },
  { label: 'Ch 9 Eir. Events', value: 45 },
  { label: 'Object type 4', value: 46 },
  { label: 'Map palette 4', value: 47 },
  { label: 'Tile configuration 4', value: 48 },
  { label: 'Ch 10 Eir. Map', value: 49 },
  { label: 'Ch 10 Eir. Map changes', value: 50 },
  { label: 'Ch 10 Eir. Events', value: 51 },
  { label: 'Map palette 5', value: 52 },
  { label: 'Ch 12 Eir. Map', value: 53 },
  { label: 'Ch 12 Eir. map changes', value: 54 },
  { label: 'Ch 12 Eir. event data', value: 55 },
  { label: 'Map palette 6', value: 56 },
  { label: 'Ch 13 Eir. Map', value: 57 },
  { label: 'Ch 13 Eir. Map changes', value: 58 },
  { label: 'Ch 13 Eir. Events (3B)', value: 59 },
  { label: 'Object type', value: 60 },
  { label: 'Map palette 7', value: 61 },
  { label: 'Tile configuration 5', value: 62 },
  { label: 'Ch 14 Eir. Map', value: 63 },
  { label: 'Ch 14 Eir. Map changes', value: 64 },
  { label: 'Ch 14 Eir. Events', value: 65 },
  { label: 'Object type 6', value: 66 },
  { label: 'Map palette 8', value: 67 },
  { label: 'Tile configuration 6', value: 68 },
  { label: 'Ch 15 map', value: 69 },
  { label: 'Ch 15 Map changes', value: 70 },
  { label: 'Ch 15 Eir. events', value: 71 },
  { label: 'Map palette 9', value: 72 },
  { label: 'Ch 16 Map', value: 73 },
  { label: 'Ch 16 Map changes', value: 74 },
  { label: 'Ch 16 Eir events', value: 75 },
  { label: 'Map palette 10', value: 76 },
  { label: 'Ch 17 Map', value: 77 },
  { label: 'Ch 17 Map changes', value: 78 },
  { label: 'Ch 17 Eir. Events', value: 79 },
  { label: 'Object type 7', value: 80 },
  { label: 'Map palette 11', value: 81 },
  { label: 'Tile configuration 7', value: 82 },
  { label: 'Ch 18 Map', value: 83 },
  { label: 'Tile animations 4', value: 84 },
  { label: 'Ch 18 Map changes', value: 85 },
  { label: 'Ch 18 Eir. Events', value: 86 },
  { label: 'Map palette 12', value: 87 },
  { label: 'Ch 19 Map', value: 88 },
  { label: 'Ch 19 Map changes', value: 89 },
  { label: 'Ch 19 Eir. Events', value: 90 },
  { label: 'Map palette 13', value: 91 },
  { label: 'Ch 20 Map', value: 92 },
  { label: 'Ch 20 Map changes', value: 93 },
  { label: 'Ch 20 Eir. Events', value: 94 },
  { label: 'Object type 8', value: 95 },
  { label: 'Map palette 14', value: 96 },
  { label: 'Tile configuration 8', value: 97 },
  { label: 'Final Chapter Map 1', value: 98 },
  { label: 'Final Chapter Map 1 changes', value: 99 },
  { label: 'Final Eir. events 1', value: 100 },
  { label: 'Final Chapter Map 2', value: 101 },
  { label: 'Final Chapter Map 2 changes', value: 102 },
  { label: 'Final Eirika events 2', value: 103 },
  { label: 'Map palette 15', value: 104 },
  { label: 'Ch 9 Eph map', value: 105 },
  { label: 'Ch 9 Eph Map changes', value: 106 },
  { label: 'Ch 9 events', value: 107 },
  { label: 'Object type 9', value: 108 },
  { label: 'Map palette 15', value: 109 },
  { label: 'Tile configuration 9', value: 110 },
  { label: 'Ch 10 Ephraim map', value: 111 },
  { label: 'Ch 10 Ephraim map changes', value: 112 },
  { label: 'Ch 10 Ephraim events', value: 113 },
  { label: 'Map palette 16', value: 114 },
  { label: 'Ch 11 Ephraim map', value: 115 },
  { label: 'Ch 11 Ephraim map changes', value: 116 },
  { label: 'Ch 11 Ephraim events', value: 117 },
  { label: 'Ch 13 Ephraim map', value: 118 },
  { label: 'Ch 13 Ephraim map changes', value: 119 },
  { label: 'Ch 13 Ephraim event data', value: 120 },
  { label: 'Object type 10', value: 121 },
  { label: 'Map palette 17', value: 122 },
  { label: 'Tile configuration 10', value: 123 },
  { label: 'Ch 14 Ephraim map', value: 124 },
  { label: 'Tile animations 5', value: 125 },
  { label: 'Ch 14 Ephraim map changes', value: 126 },
  { label: 'Ch 14 Ephraim event data', value: 127 },
  { label: 'Ch 15 Ephraim event data', value: 128 },
  { label: 'Ch 16 Ephraim event data', value: 129 },
  { label: 'Ch 17 Ephraim event data', value: 130 },
  { label: 'Ch 18 Ephraim event data', value: 131 },
  { label: 'Ch 19 Ephraim event data', value: 132 },
  { label: 'Ch 20 Ephraim event data', value: 133 },
  { label: 'Final Ephraim events 1', value: 134 },
  { label: 'Final Ephraim events 2', value: 135 },
  { label: 'Tower of Valni Object type', value: 136 },
  { label: 'Tower of Valni map palette', value: 137 },
  { label: 'Tower of Valni Tile configuration', value: 138 },
  { label: 'Tower of Valni 1 Map', value: 139 },
  { label: 'Tower of Valni 1 Map changes', value: 140 },
  { label: 'Tower of Valni 1 events', value: 141 },
  { label: 'Tower of Valni 2 map', value: 142 },
  { label: 'Tower of Valni 2 map changes', value: 143 },
  { label: 'Tower of Valni 2 events', value: 144 },
  { label: 'Tower of Valni 3 map', value: 145 },
  { label: 'Tower of Valni 3 map changes', value: 146 },
  { label: 'Tower of Valni 3 events', value: 147 },
  { label: 'Tower of Valni 4 map', value: 148 },
  { label: 'Tower of Valni 4 map changes', value: 149 },
  { label: 'Tower of Valni 4 events', value: 150 },
  { label: 'Tower of Valni 5 map', value: 151 },
  { label: 'Tower of Valni 5 map changes', value: 152 },
  { label: 'Tower of Valni 5 events', value: 153 },
  { label: 'Tower of Valni 6 map', value: 154 },
  { label: 'Tower of Valni 6 map changes', value: 155 },
  { label: 'Tower of Valni 6 events', value: 156 },
  { label: 'Tower of Valni 7 map', value: 157 },
  { label: 'Tower of Valni 7 map changes', value: 158 },
  { label: 'Tower of Valni 7 events', value: 159 },
  { label: 'Tower of Valni 8 map', value: 160 },
  { label: 'Tower of Valni 8 map changes', value: 161 },
  { label: 'Tower of Valni 8 events', value: 162 },
  { label: 'Lagdou ruins palette', value: 163 },
  { label: 'Lagdou ruins 1 Map', value: 164 },
  { label: 'Lagdou ruins 1 Map changes', value: 165 },
  { label: 'Lagdou ruins 1 Event', value: 166 },
  { label: 'Lagdou ruins 2 Map', value: 167 },
  { label: 'Lagdou ruins 2 Map changes', value: 168 },
  { label: 'Lagdou ruins 2 Event', value: 169 },
  { label: 'Lagdou ruins 3 Map', value: 170 },
  { label: 'Lagdou ruins 3 Map changes', value: 171 },
  { label: 'Lagdou ruins 3 Event', value: 172 },
  { label: 'Lagdou ruins 4 Map', value: 173 },
  { label: 'Lagdou ruins 4 Map changes', value: 174 },
  { label: 'Lagdou ruins 4 Event', value: 175 },
  { label: 'Lagdou ruins 5 Map', value: 176 },
  { label: 'Lagdou ruins 5 Map changes', value: 177 },
  { label: 'Lagdou ruins 5 Event', value: 178 },
  { label: 'Lagdou ruins 6 Map', value: 179 },
  { label: 'Lagdou ruins 6 Map changes', value: 180 },
  { label: 'Lagdou ruins 6 Event', value: 181 },
  { label: 'Lagdou ruins 7 Map', value: 182 },
  { label: 'Lagdou ruins 7 Map changes', value: 183 },
  { label: 'Lagdou ruins 7 Event', value: 184 },
  { label: 'Lagdou ruins 8 palette', value: 185 },
  { label: 'Lagdou ruins 8 Map', value: 186 },
  { label: 'Lagdou ruins 8 Map changes', value: 187 },
  { label: 'Lagdou ruins 8 Event', value: 188 },
  { label: 'Lagdou ruins 9 Map', value: 189 },
  { label: 'Lagdou ruins 9 Map changes', value: 190 },
  { label: 'Lagdou ruins 9 Event', value: 191 },
  { label: 'Lagdou ruins 10 Map', value: 192 },
  { label: 'Lagdou ruins 10 Map changes', value: 193 },
  { label: 'Lagdou ruins 10 Event', value: 194 },
  { label: 'Lords split map', value: 195 },
  { label: 'Lords split map changes', value: 196 },
  { label: 'Lords split events', value: 197 },
  { label: 'Melkaen Coast map', value: 198 },
  { label: 'Melkaen Coast map changes', value: 199 },
  { label: 'Melkaen Coast event', value: 200 },
  { label: 'Link arena map C9', value: 201 },
  { label: 'An interesting map...', value: 202 },
  { label: 'An interesting map events...', value: 203 },
  { label: 'Debug map', value: 204 },
  { label: 'Debug map events', value: 205 },
  { label: 'Map palette', value: 206 },
  { label: 'Ch 11 Eirika map', value: 207 },
  { label: 'Ch 11 Eirika map changes D0', value: 208 },
  { label: 'Ch 11 Eirika events', value: 209 },
  { label: 'Ch 11 Ephraim map', value: 210 },
  { label: 'Ch 11 Ephraim tile animations', value: 211 },
  { label: 'Ch 11 Ephraim map changes', value: 212 },
  { label: 'Ch 11 Ephraim events', value: 213 },
  { label: 'Grado castle map', value: 214 },
  { label: 'Renais castle map', value: 215 },
  { label: 'Caer Pelyn map', value: 216 },
  { label: 'Renais throne map', value: 217 },
  { label: 'Renais throne map changes', value: 218 },
  { label: 'Renais audience map', value: 219 },
  { label: 'Renval gate map', value: 220 },
  { label: 'Grado borders map', value: 221 },
  { label: 'Grado prison map', value: 222 },
  { label: 'Grado prison map changes', value: 223 },
  { label: 'Grado shrine map (past)', value: 224 },
  { label: 'Grado shrine map changes (past)', value: 225 },
  { label: 'Renais shrine map', value: 226 },
  { label: 'Renais shrine map changes', value: 227 },
  { label: 'Some path map', value: 228 },
  { label: 'Some building map', value: 229 },
  { label: 'Another shrine palette', value: 230 },
  { label: 'Another shrine map', value: 231 },
  { label: 'Another path map', value: 232 },
  { label: 'Grado shrine map (present)', value: 233 },
  { label: 'Ch 5 town palette (past)', value: 234 },
  { label: 'Ch 5 town map (past)', value: 235 },
];

export default Pointers;
