export const PromotionBranchList = [
  { label: '0x01 Ephraim Lord', value: 0 },
  { label: '0x02 Eirika Lord', value: 1 },
  { label: '0x03 Ephraim Master Lord', value: 2 },
  { label: '0x04 Eirika Master Lord', value: 3 },
  { label: '0x05 Social Knight', value: 4 },
  { label: '0x06 Social Knight (F)', value: 5 },
  { label: '0x07 Paladin', value: 6 },
  { label: '0x08 Paladin (F)', value: 7 },
  { label: '0x09 Armour Knight', value: 8 },
  { label: '0x0A Armour Knight (F)', value: 9 },
  { label: '0x0B General', value: 10 },
  { label: '0x0C General (F)', value: 11 },
  { label: '0x0D Thief', value: 12 },
  { label: '0x0E Mamkute', value: 13 },
  { label: '0x0F Mercenary', value: 14 },
  { label: '0x10 Mercenary (F)', value: 15 },
  { label: '0x11 Hero', value: 16 },
  { label: '0x12 Hero (F)', value: 17 },
  { label: '0x13 Swordfighter', value: 18 },
  { label: '0x14 Swordfighter (F)', value: 19 },
  { label: '0x15 Swordmaster', value: 20 },
  { label: '0x16 Swordmaster (F)', value: 21 },
  { label: '0x17 Assassin', value: 22 },
  { label: '0x18 Assassin (F)', value: 23 },
  { label: '0x19 Archer', value: 24 },
  { label: '0x1A Archer (F)', value: 25 },
  { label: '0x1B Sniper', value: 26 },
  { label: '0x1C Sniper (F)', value: 27 },
  { label: '0x1D Forrest Knight', value: 28 },
  { label: '0x1E Forrest Knight (F)', value: 29 },
  { label: '0x1F Dragon Knight', value: 30 },
  { label: '0x20 Dragon Knight (F)', value: 31 },
  { label: '0x21 Dragon Master', value: 32 },
  { label: '0x22 Dragon Master (F)', value: 33 },
  { label: '0x23 Wyvern Knight', value: 34 },
  { label: '0x24 Wyvern Knight (F)', value: 35 },
  { label: '0x25 Mage', value: 36 },
  { label: '0x26 Mage (F)', value: 37 },
  { label: '0x27 Sage', value: 38 },
  { label: '0x28 Sage (F)', value: 39 },
  { label: '0x29 Mage Knight', value: 40 },
  { label: '0x2A Mage Knight (F)', value: 41 },
  { label: '0x2B Bishop', value: 42 },
  { label: '0x2C Bishop (F)', value: 43 },
  { label: '0x2D Shaman', value: 44 },
  { label: '0x2E Shaman (F)', value: 45 },
  { label: '0x2F Druid', value: 46 },
  { label: '0x30 Druid (F)', value: 47 },
  { label: '0x31 Summoner', value: 48 },
  { label: '0x32 Summoner (F)', value: 49 },
  { label: '0x33 Rogue', value: 50 },
  { label: '0x34 Gorgon Egg', value: 51 },
  { label: '0x35 Great Knight', value: 52 },
  { label: '0x36 Great Knight (F)', value: 53 },
  { label: '0x37 Trainee Soldier (2)', value: 54 },
  { label: '0x38 Trainee Fighter (3)', value: 55 },
  { label: '0x39 Trainee Mage (3)', value: 56 },
  { label: '0x3A Trainee Soldier (3)', value: 57 },
  { label: '0x3B Mamkute', value: 58 },
  { label: '0x3C Mamkute (F)', value: 59 },
  { label: '0x3D Trainee Fighter (1)', value: 60 },
  { label: '0x3E Trainee Mage (1)', value: 61 },
  { label: '0x3F Fighter', value: 62 },
  { label: '0x40 Warrior', value: 63 },
  { label: '0x41 Mountain Thief', value: 64 },
  { label: '0x42 Pirate', value: 65 },
  { label: '0x43 Berserker', value: 66 },
  { label: '0x44 Monk', value: 67 },
  { label: '0x45 Priest', value: 68 },
  { label: '0x46 Bard', value: 69 },
  { label: '0x47 Trainee Soldier (1)', value: 70 },
  { label: '0x48 Pegasus Knight', value: 71 },
  { label: '0x49 Falcon Knight', value: 72 },
  { label: '0x4A Sister', value: 73 },
  { label: '0x4B Troubadour', value: 74 },
  { label: '0x4C Valkyrie', value: 75 },
  { label: '0x4D Dancer', value: 76 },
  { label: '0x4E Soldier', value: 77 },
  { label: '0x4F Necromancer', value: 78 },
  { label: '0x50 Fleet', value: 79 },
  { label: '0x51 Ghost Fighter', value: 80 },
  { label: '0x52 Zombie', value: 81 },
  { label: '0x53 Mummy', value: 82 },
  { label: '0x54 Skeleton', value: 83 },
  { label: '0x55 Skeleton (Bow)', value: 84 },
  { label: '0x56 Hellbone', value: 85 },
  { label: '0x57 Hellbone (Bow)', value: 86 },
  { label: '0x58 Bael', value: 87 },
  { label: '0x59 Elder Bael', value: 88 },
  { label: '0x5A Cyclops', value: 89 },
  { label: '0x5B Mauthedoog', value: 90 },
  { label: '0x5C Cerberus', value: 91 },
  { label: '0x5D Tarvos', value: 92 },
  { label: '0x5E Macdaire', value: 93 },
  { label: '0x5F Bigl', value: 94 },
  { label: '0x60 Arch Bigl', value: 95 },
  { label: '0x61 Gorgon', value: 96 },
  { label: '0x62 Gorgon Egg', value: 97 },
  { label: '0x63 Gargoyle', value: 98 },
  { label: '0x64 Death Gargoyle', value: 99 },
  { label: '0x65 Dragon Zombie', value: 100 },
  { label: '0x66 Demon King', value: 101 },
  { label: '0x67 Archer on Ballista', value: 102 },
  { label: '0x68 Archer on Iron Ballista', value: 103 },
  { label: '0x69 Archer on Killer Ballista', value: 104 },
  { label: '0x6A Ballista', value: 105 },
  { label: '0x6B Iron Ballista', value: 106 },
  { label: '0x6C Killer Ballista', value: 107 },
  { label: '0x6D Civilian', value: 108 },
  { label: '0x6E Civilian (F)', value: 109 },
  { label: '0x6F Civilian', value: 110 },
  { label: '0x70 Civilian (F)', value: 111 },
  { label: '0x71 Civilian', value: 112 },
  { label: '0x72 Civilian (F)', value: 113 },
  { label: '0x73 Peer', value: 114 },
  { label: '0x74 Queen', value: 115 },
  { label: '0x75 Prince', value: 116 },
  { label: '0x76 Queen', value: 117 },
  { label: '0x77 (empty)', value: 118 },
  { label: '0x78 Fallen Prince', value: 119 },
  { label: '0x79 Tent', value: 120 },
  { label: '0x7A Pontifex', value: 121 },
  { label: '0x7B Fallen Peer', value: 122 },
  { label: '0x7C Cyclops', value: 123 },
  { label: '0x7D Elder Bael', value: 124 },
  { label: '0x7E Trainee Fighter (2)', value: 125 },
  { label: '0x7F Trainee Mage (2)', value: 126 },
  { label: 'Entry 127', value: 127 },
];

export const ClassList = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Ephraim Lord', value: 0x01 },
  { label: 'Eirika Lord', value: 0x02 },
  { label: 'Ephraim Master Lord', value: 0x03 },
  { label: 'Eirika Master Lord', value: 0x04 },
  { label: 'Social Knight', value: 0x05 },
  { label: 'Social Knight (F)', value: 0x06 },
  { label: 'Paladin', value: 0x07 },
  { label: 'Paladin (F)', value: 0x08 },
  { label: 'Armour Knight', value: 0x09 },
  { label: 'Armour Knight (F)', value: 0x0A },
  { label: 'General', value: 0x0B },
  { label: 'General (F)', value: 0x0C },
  { label: 'Thief', value: 0x0D },
  { label: 'Mamkute', value: 0x0E },
  { label: 'Mercenary', value: 0x0F },
  { label: 'Mercenary (F)', value: 0x10 },
  { label: 'Hero', value: 0x11 },
  { label: 'Hero (F)', value: 0x12 },
  { label: 'Swordfighter', value: 0x13 },
  { label: 'Swordfighter (F)', value: 0x14 },
  { label: 'Swordmaster', value: 0x15 },
  { label: 'Swordmaster (F)', value: 0x16 },
  { label: 'Assassin', value: 0x17 },
  { label: 'Assassin (F)', value: 0x18 },
  { label: 'Archer', value: 0x19 },
  { label: 'Archer (F)', value: 0x1A },
  { label: 'Sniper', value: 0x1B },
  { label: 'Sniper (F)', value: 0x1C },
  { label: 'Forrest Knight', value: 0x1D },
  { label: 'Forrest Knight (F)', value: 0x1E },
  { label: 'Dragon Knight', value: 0x1F },
  { label: 'Dragon Knight (F)', value: 0x20 },
  { label: 'Dragon Master', value: 0x21 },
  { label: 'Dragon Master (F)', value: 0x22 },
  { label: 'Wyvern Knight', value: 0x23 },
  { label: 'Wyvern Knight (F)', value: 0x24 },
  { label: 'Mage', value: 0x25 },
  { label: 'Mage (F)', value: 0x26 },
  { label: 'Sage', value: 0x27 },
  { label: 'Sage (F)', value: 0x28 },
  { label: 'Mage Knight', value: 0x29 },
  { label: 'Mage Knight (F)', value: 0x2A },
  { label: 'Bishop', value: 0x2B },
  { label: 'Bishop (F)', value: 0x2C },
  { label: 'Shaman', value: 0x2D },
  { label: 'Shaman (F)', value: 0x2E },
  { label: 'Druid', value: 0x2F },
  { label: 'Druid (F)', value: 0x30 },
  { label: 'Summoner', value: 0x31 },
  { label: 'Summoner (F)', value: 0x32 },
  { label: 'Rogue', value: 0x33 },
  { label: 'Gorgon Egg', value: 0x34 },
  { label: 'Great Knight', value: 0x35 },
  { label: 'Great Knight (F)', value: 0x36 },
  { label: 'Trainee Soldier (2)', value: 0x37 },
  { label: 'Trainee Fighter (3)', value: 0x38 },
  { label: 'Trainee Mage (3)', value: 0x39 },
  { label: 'Trainee Soldier (3)', value: 0x3A },
  { label: 'Mamkute', value: 0x3B },
  { label: 'Mamkute (F)', value: 0x3C },
  { label: 'Trainee Fighter (1)', value: 0x3D },
  { label: 'Trainee Mage (1)', value: 0x3E },
  { label: 'Fighter', value: 0x3F },
  { label: 'Warrior', value: 0x40 },
  { label: 'Mountain Thief', value: 0x41 },
  { label: 'Pirate', value: 0x42 },
  { label: 'Berserker', value: 0x43 },
  { label: 'Monk', value: 0x44 },
  { label: 'Priest', value: 0x45 },
  { label: 'Bard', value: 0x46 },
  { label: 'Trainee Soldier (1)', value: 0x47 },
  { label: 'Pegasus Knight', value: 0x48 },
  { label: 'Falcon Knight', value: 0x49 },
  { label: 'Sister', value: 0x4A },
  { label: 'Troubadour', value: 0x4B },
  { label: 'Valkyrie', value: 0x4C },
  { label: 'Dancer', value: 0x4D },
  { label: 'Soldier', value: 0x4E },
  { label: 'Necromancer', value: 0x4F },
  { label: 'Fleet', value: 0x50 },
  { label: 'Ghost Fighter', value: 0x51 },
  { label: 'Zombie', value: 0x52 },
  { label: 'Mummy', value: 0x53 },
  { label: 'Skeleton', value: 0x54 },
  { label: 'Skeleton (Bow)', value: 0x55 },
  { label: 'Hellbone', value: 0x56 },
  { label: 'Hellbone (Bow)', value: 0x57 },
  { label: 'Bael', value: 0x58 },
  { label: 'Elder Bael', value: 0x59 },
  { label: 'Cyclops', value: 0x5A },
  { label: 'Mauthedoog', value: 0x5B },
  { label: 'Cerberus', value: 0x5C },
  { label: 'Tarvos', value: 0x5D },
  { label: 'Macdaire', value: 0x5E },
  { label: 'Bigl', value: 0x5F },
  { label: 'Arch Bigl', value: 0x60 },
  { label: 'Gorgon', value: 0x61 },
  { label: 'Gorgon Egg', value: 0x62 },
  { label: 'Gargoyle', value: 0x63 },
  { label: 'Death Gargoyle', value: 0x64 },
  { label: 'Dragon Zombie', value: 0x65 },
  { label: 'Demon King', value: 0x66 },
  { label: 'Archer on Ballista', value: 0x67 },
  { label: 'Archer on Iron Ballista', value: 0x68 },
  { label: 'Archer on Killer Ballista', value: 0x69 },
  { label: 'Ballista', value: 0x6A },
  { label: 'Iron Ballista', value: 0x6B },
  { label: 'Killer Ballista', value: 0x6C },
  { label: 'Civilian', value: 0x6D },
  { label: 'Civilian (F)', value: 0x6E },
  { label: 'Civilian', value: 0x6F },
  { label: 'Civilian (F)', value: 0x70 },
  { label: 'Civilian', value: 0x71 },
  { label: 'Civilian (F)', value: 0x72 },
  { label: 'Peer', value: 0x73 },
  { label: 'Queen', value: 0x74 },
  { label: 'Prince', value: 0x75 },
  { label: 'Queen', value: 0x76 },
  { label: '(empty)', value: 0x77 },
  { label: 'Fallen Prince', value: 0x78 },
  { label: 'Tent', value: 0x79 },
  { label: 'Pontifex', value: 0x7A },
  { label: 'Fallen Peer', value: 0x7B },
  { label: 'Cyclops', value: 0x7C },
  { label: 'Elder Bael', value: 0x7D },
  { label: 'Trainee Fighter (2)', value: 0x7E },
  { label: 'Trainee Mage (2)', value: 0x7F },
];
