export const BattleAnimationPointers = [
  { label: '0x8E60000', value: 0 },
  { label: '0x8E60010', value: 1 },
  { label: '0x8E60020', value: 2 },
  { label: '0x8E60030', value: 3 },
  { label: '0x8E60040', value: 4 },
  { label: '0x8E60050', value: 5 },
  { label: '0x8E60060', value: 6 },
  { label: '0x8E60070', value: 7 },
  { label: '0x8E60080', value: 8 },
  { label: '0x8E60090', value: 9 },
  { label: '0x8E600A0', value: 10 },
  { label: '0x8E600B0', value: 11 },
  { label: '0x8E600C0', value: 12 },
  { label: '0x8E600D0', value: 13 },
  { label: '0x8E600E0', value: 14 },
  { label: '0x8E600F0', value: 15 },
  { label: '0x8E60100', value: 16 },
  { label: '0x8E60110', value: 17 },
  { label: '0x8E60120', value: 18 },
  { label: '0x8E60130', value: 19 },
  { label: '0x8E60140', value: 20 },
  { label: '0x8E60150', value: 21 },
  { label: '0x8E60160', value: 22 },
  { label: '0x8E60170', value: 23 },
  { label: '0x8E60180', value: 24 },
  { label: '0x8E60190', value: 25 },
  { label: '0x8E601A0', value: 26 },
  { label: '0x8E601B0', value: 27 },
  { label: '0x8E601C0', value: 28 },
  { label: '0x8E601D0', value: 29 },
  { label: '0x8E601E0', value: 30 },
  { label: '0x8E601F0', value: 31 },
  { label: '0x8E60200', value: 32 },
  { label: '0x8E60210', value: 33 },
  { label: '0x8E60220', value: 34 },
  { label: '0x8E60230', value: 35 },
  { label: '0x8E60240', value: 36 },
  { label: '0x8E60250', value: 37 },
  { label: '0x8E60260', value: 38 },
  { label: '0x8E60270', value: 39 },
  { label: '0x8E60280', value: 40 },
  { label: '0x8E60290', value: 41 },
  { label: '0x8E602A0', value: 42 },
  { label: '0x8E602B0', value: 43 },
  { label: '0x8E602C0', value: 44 },
  { label: '0x8E602D0', value: 45 },
  { label: '0x8E602E0', value: 46 },
  { label: '0x8E602F0', value: 47 },
  { label: '0x8E60300', value: 48 },
  { label: '0x8E60310', value: 49 },
  { label: '0x8E60320', value: 50 },
  { label: '0x8E60330', value: 51 },
  { label: '0x8E60340', value: 52 },
  { label: '0x8E60350', value: 53 },
  { label: '0x8E60360', value: 54 },
  { label: '0x8E60370', value: 55 },
  { label: '0x8E60380', value: 56 },
  { label: '0x8E60390', value: 57 },
  { label: '0x8E603A0', value: 58 },
  { label: '0x8E603B0', value: 59 },
  { label: '0x8E603C0', value: 60 },
  { label: '0x8E603D0', value: 61 },
  { label: '0x8E603E0', value: 62 },
  { label: '0x8E603F0', value: 63 },
  { label: '0x8E60400', value: 64 },
  { label: '0x8E60410', value: 65 },
  { label: '0x8E60420', value: 66 },
  { label: '0x8E60430', value: 67 },
  { label: '0x8E60440', value: 68 },
  { label: '0x8E60450', value: 69 },
  { label: '0x8E60460', value: 70 },
  { label: '0x8E60470', value: 71 },
  { label: '0x8E60480', value: 72 },
  { label: '0x8E60490', value: 73 },
  { label: '0x8E604A0', value: 74 },
  { label: '0x8E604B0', value: 75 },
  { label: '0x8E604C0', value: 76 },
  { label: '0x8E604D0', value: 77 },
  { label: '0x8E604E0', value: 78 },
  { label: '0x8E604F0', value: 79 },
  { label: '0x8E60500', value: 80 },
  { label: '0x8E60510', value: 81 },
  { label: '0x8E60520', value: 82 },
  { label: '0x8E60530', value: 83 },
  { label: '0x8E60540', value: 84 },
  { label: '0x8E60550', value: 85 },
  { label: '0x8E60560', value: 86 },
  { label: '0x8E60570', value: 87 },
  { label: '0x8E60580', value: 88 },
  { label: '0x8E60590', value: 89 },
  { label: '0x8E605A0', value: 90 },
  { label: '0x8E605B0', value: 91 },
  { label: '0x8E605C0', value: 92 },
  { label: '0x8E605D0', value: 93 },
  { label: '0x8E605E0', value: 94 },
  { label: '0x8E605F0', value: 95 },
  { label: '0x8E60600', value: 96 },
  { label: '0x8E60610', value: 97 },
  { label: '0x8E60620', value: 98 },
  { label: '0x8E60630', value: 99 },
];

export const ItemList = [
  { label: 'All Swords/   Separator', value: 0x00 },
  { label: 'All Spears/   Iron Sword', value: 0x01 },
  { label: 'All Axes/   Thin Sword', value: 0x02 },
  { label: 'All Bows/   Steel Sword', value: 0x03 },
  { label: 'All Staves/   Silver Sword', value: 0x04 },
  { label: 'All Anima/   Iron Blade', value: 0x05 },
  { label: 'All Light/   Steel Blade', value: 0x06 },
  { label: 'All Dark/   Silver Blade', value: 0x07 },
  { label: 'Poison Sword', value: 0x08 },
  { label: 'Disarmed(required)/   Rapier', value: 0x09 },
  { label: 'Mani Katti (DUMMY)', value: 0x0A },
  { label: 'Hero Sword', value: 0x0B },
  { label: 'Shamshir', value: 0x0C },
  { label: 'Killer Sword', value: 0x0D },
  { label: 'Armour Killer', value: 0x0E },
  { label: 'Dragon Killer', value: 0x0F },
  { label: 'Light Sword', value: 0x10 },
  { label: 'Rune Sword', value: 0x11 },
  { label: 'Lancebuster', value: 0x12 },
  { label: 'Long Sword', value: 0x13 },
  { label: 'Iron Spear', value: 0x14 },
  { label: 'Thin Spear', value: 0x15 },
  { label: 'Steel Spear', value: 0x16 },
  { label: 'Silver Spear', value: 0x17 },
  { label: 'Poison Spear', value: 0x18 },
  { label: 'Hero Spear', value: 0x19 },
  { label: 'Killer Spear', value: 0x1A },
  { label: 'Horse Killer', value: 0x1B },
  { label: 'Javelin', value: 0x1C },
  { label: 'Slender Spear', value: 0x1D },
  { label: 'Axebuster', value: 0x1E },
  { label: 'Iron Axe', value: 0x1F },
  { label: 'Steel Axe', value: 0x20 },
  { label: 'Silver Axe', value: 0x21 },
  { label: 'Poison Axe', value: 0x22 },
  { label: 'Hero Axe', value: 0x23 },
  { label: 'Killer Axe', value: 0x24 },
  { label: 'Halberd', value: 0x25 },
  { label: 'Hammer', value: 0x26 },
  { label: 'Devil Axe', value: 0x27 },
  { label: 'Hand Axe', value: 0x28 },
  { label: 'Tomahawk', value: 0x29 },
  { label: 'Swordbuster', value: 0x2A },
  { label: 'Swordkiller', value: 0x2B },
  { label: 'Trainee Axe', value: 0x2C },
  { label: 'Iron Bow', value: 0x2D },
  { label: 'Steel Bow', value: 0x2E },
  { label: 'Silver Bow', value: 0x2F },
  { label: 'Poison Bow', value: 0x30 },
  { label: 'Killer Bow', value: 0x31 },
  { label: 'Hero Bow', value: 0x32 },
  { label: 'Short Bow', value: 0x33 },
  { label: 'Long Bow', value: 0x34 },
  { label: 'Iron Ballista', value: 0x35 },
  { label: 'Killer Ballista', value: 0x36 },
  { label: 'Ballista', value: 0x37 },
  { label: 'Fire', value: 0x38 },
  { label: 'Thunder', value: 0x39 },
  { label: 'Elfire', value: 0x3A },
  { label: 'Thunderstorm', value: 0x3B },
  { label: 'Fimbulvetr', value: 0x3C },
  { label: 'Forblaze (DUMMY)', value: 0x3D },
  { label: 'Excalibur', value: 0x3E },
  { label: 'Lightning', value: 0x3F },
  { label: 'Shine', value: 0x40 },
  { label: 'Divine', value: 0x41 },
  { label: 'Purge', value: 0x42 },
  { label: 'Aura', value: 0x43 },
  { label: 'Luce (DUMMY)', value: 0x44 },
  { label: 'Flux', value: 0x45 },
  { label: 'Luna', value: 0x46 },
  { label: 'Nosferatu', value: 0x47 },
  { label: 'Eclipse', value: 0x48 },
  { label: 'Fenrir', value: 0x49 },
  { label: 'Gleipnir', value: 0x4A },
  { label: 'Live', value: 0x4B },
  { label: 'Relive', value: 0x4C },
  { label: 'Recover', value: 0x4D },
  { label: 'Libro', value: 0x4E },
  { label: 'Reserve', value: 0x4F },
  { label: 'Rest', value: 0x50 },
  { label: 'Silence', value: 0x51 },
  { label: 'Sleep', value: 0x52 },
  { label: 'Berserk', value: 0x53 },
  { label: 'Warp', value: 0x54 },
  { label: 'Rescue', value: 0x55 },
  { label: 'Torch', value: 0x56 },
  { label: 'Hammerne', value: 0x57 },
  { label: 'Unlock', value: 0x58 },
  { label: 'Magic Shield', value: 0x59 },
  { label: 'Dragon Axe', value: 0x5A },
  { label: 'Angelic Robe', value: 0x5B },
  { label: 'Energy Ring', value: 0x5C },
  { label: 'Secret Book', value: 0x5D },
  { label: 'Speedwings', value: 0x5E },
  { label: 'Goddess Icon', value: 0x5F },
  { label: 'Dragonshield', value: 0x60 },
  { label: 'Talisman', value: 0x61 },
  { label: 'Boots', value: 0x62 },
  { label: 'Body Ring', value: 0x63 },
  { label: 'Hero\'s Proof', value: 0x64 },
  { label: 'Knight\'s Proof', value: 0x65 },
  { label: 'Orion\'s Bolt', value: 0x66 },
  { label: 'Elysian Whip', value: 0x67 },
  { label: 'Guiding Ring', value: 0x68 },
  { label: 'Chest Key', value: 0x69 },
  { label: 'Door Key', value: 0x6A },
  { label: 'Thief Key', value: 0x6B },
  { label: 'Vulnerary', value: 0x6C },
  { label: 'Elixir', value: 0x6D },
  { label: 'Holy Water', value: 0x6E },
  { label: 'Antidote', value: 0x6F },
  { label: 'Torch', value: 0x70 },
  { label: 'Free Shield', value: 0x71 },
  { label: 'Member Card', value: 0x72 },
  { label: 'Silver Card', value: 0x73 },
  { label: 'White Gem', value: 0x74 },
  { label: 'Blue Gem', value: 0x75 },
  { label: 'Red Gem', value: 0x76 },
  { label: '1G', value: 0x77 },
  { label: 'Reginleif', value: 0x78 },
  { label: 'Chest Key (5)', value: 0x79 },
  { label: 'Mine (DUMMY)', value: 0x7A },
  { label: 'Light Rune (DUMMY)', value: 0x7B },
  { label: 'Hopron Shield', value: 0x7C },
  { label: 'Filla\'s Might (DUMMY)', value: 0x7D },
  { label: 'Ninis\'s Grace (DUMMY)', value: 0x7E },
  { label: 'Thor\'s Ire (DUMMY)', value: 0x7F },
  { label: 'Set\'s Litany (DUMMY)', value: 0x80 },
  { label: 'Shadow Killer', value: 0x81 },
  { label: 'Bright Lance', value: 0x82 },
  { label: 'Fiend Cleaver', value: 0x83 },
  { label: 'Beacon Bow', value: 0x84 },
  { label: 'Sieglind', value: 0x85 },
  { label: 'Battle Axe', value: 0x86 },
  { label: 'Ivaldi', value: 0x87 },
  { label: 'Master Proof', value: 0x88 },
  { label: 'Metis\'s Tome', value: 0x89 },
  { label: 'Heaven Seal (DUMMY)', value: 0x8A },
  { label: 'Sharp Claw', value: 0x8B },
  { label: 'Latona', value: 0x8C },
  { label: 'Dragon Spear', value: 0x8D },
  { label: 'Vidofnir', value: 0x8E },
  { label: 'Naglfal', value: 0x8F },
  { label: 'Decaying Breath', value: 0x90 },
  { label: 'Audomra', value: 0x91 },
  { label: 'Siegmund', value: 0x92 },
  { label: 'Garm', value: 0x93 },
  { label: 'Nidhogg', value: 0x94 },
  { label: 'Heavy Spear', value: 0x95 },
  { label: 'Short Spear', value: 0x96 },
  { label: 'Conqueror\'s Proof', value: 0x97 },
  { label: 'Moon Bracelet', value: 0x98 },
  { label: 'Sun Bracelet', value: 0x99 },
  { label: '1G', value: 0x9A },
  { label: '5G', value: 0x9B },
  { label: '10G', value: 0x9C },
  { label: '50G', value: 0x9D },
  { label: '100G', value: 0x9E },
  { label: '3000G', value: 0x9F },
  { label: '5000G', value: 0xA0 },
  { label: 'Wind Sword', value: 0xA1 },
  { label: 'Vulnerary', value: 0xA2 },
  { label: 'Vulnerary (green note)', value: 0xA3 },
  { label: 'Vulnerary (red note)', value: 0xA4 },
  { label: 'Dance', value: 0xA5 },
  { label: 'Nightmare', value: 0xA6 },
  { label: 'Demon Shard', value: 0xA7 },
  { label: 'Demon Light', value: 0xA8 },
  { label: 'Ravager', value: 0xA9 },
  { label: 'Holy Dragon Stone', value: 0xAA },
  { label: 'Demon Surge', value: 0xAB },
  { label: 'Shadowshot', value: 0xAC },
  { label: 'Rotten Claw', value: 0xAD },
  { label: 'Fetid Claw', value: 0xAE },
  { label: 'Poison Claw', value: 0xAF },
  { label: 'Long Poison Claw', value: 0xB0 },
  { label: 'Fire Fang', value: 0xB1 },
  { label: 'Hell Fang', value: 0xB2 },
  { label: 'Evil Eye', value: 0xB3 },
  { label: 'Bloody Eye', value: 0xB4 },
  { label: 'Stone', value: 0xB5 },
  { label: 'Aircalibur', value: 0xB6 },
  { label: 'Juna Fruit', value: 0xB7 },
  { label: '150G', value: 0xB8 },
  { label: '200G', value: 0xB9 },
  { label: 'Black Gem', value: 0xBA },
  { label: 'Gold Gem', value: 0xBB },
  { label: '-', value: 0xBC },
  { label: '-', value: 0xBD },
  { label: '-', value: 0xBE },
  { label: '-', value: 0xBF },
  { label: '-', value: 0xC0 },
  { label: '-', value: 0xC1 },
  { label: '-', value: 0xC2 },
  { label: '-', value: 0xC3 },
  { label: '-', value: 0xC4 },
  { label: '-', value: 0xC5 },
  { label: '-', value: 0xC6 },
  { label: '-', value: 0xC7 },
  { label: '-', value: 0xC8 },
  { label: '-', value: 0xC9 },
  { label: '-', value: 0xCA },
  { label: '-', value: 0xCB },
  { label: '-', value: 0xCC },
  { label: '-', value: 0xCD },
  { label: '-', value: 0xCE },
  { label: '-', value: 0xCF },
  { label: '-', value: 0xD0 },
  { label: '-', value: 0xD1 },
  { label: '-', value: 0xD2 },
  { label: '-', value: 0xD3 },
  { label: '-', value: 0xD4 },
  { label: '-', value: 0xD5 },
  { label: '-', value: 0xD6 },
  { label: '-', value: 0xD7 },
  { label: '-', value: 0xD8 },
  { label: '-', value: 0xD9 },
  { label: '-', value: 0xDA },
  { label: '-', value: 0xDB },
  { label: '-', value: 0xDC },
  { label: '-', value: 0xDD },
  { label: '-', value: 0xDE },
  { label: '-', value: 0xDF },
  { label: '-', value: 0xE0 },
  { label: '-', value: 0xE1 },
  { label: '-', value: 0xE2 },
  { label: '-', value: 0xE3 },
  { label: '-', value: 0xE4 },
  { label: '-', value: 0xE5 },
  { label: '-', value: 0xE6 },
  { label: '-', value: 0xE7 },
  { label: '-', value: 0xE8 },
  { label: '-', value: 0xE9 },
  { label: '-', value: 0xEA },
  { label: '-', value: 0xEB },
  { label: '-', value: 0xEC },
  { label: '-', value: 0xED },
  { label: '-', value: 0xEE },
  { label: '-', value: 0xEF },
  { label: '-', value: 0xF0 },
  { label: '-', value: 0xF1 },
  { label: '-', value: 0xF2 },
  { label: '-', value: 0xF3 },
  { label: '-', value: 0xF4 },
  { label: '-', value: 0xF5 },
  { label: '-', value: 0xF6 },
  { label: '-', value: 0xF7 },
  { label: '-', value: 0xF8 },
  { label: '-', value: 0xF9 },
  { label: '-', value: 0xFA },
  { label: '-', value: 0xFB },
  { label: '-', value: 0xFC },
  { label: '-', value: 0xFD },
  { label: '-', value: 0xFE },
  { label: '-', value: 0xFF },
];

export const WeaponAnimationType = [
  { label: 'Custom Animation for a Weapon', value: 0x00 },
  { label: 'All Weapons for a Weapon Type', value: 0x01 },
];

export const AnimationList = [
  { label: 'None (map animation)', value: 0x00 },
  { label: 'Ephraim', value: 0x01 },
  { label: 'Ephraim Disarmed', value: 0x02 },
  { label: 'Eirika', value: 0x03 },
  { label: 'Eirika Disarmed', value: 0x04 },
  { label: 'Great Lord Ephraim', value: 0x05 },
  { label: 'Eirika', value: 0x06 },
  { label: 'Great Lord Ephraim Disarmed', value: 0x07 },
  { label: 'Great Lord Eirika', value: 0x08 },
  { label: 'Eirika', value: 0x09 },
  { label: 'Great Lord Eirika Disarmed', value: 0x0A },
  { label: 'Mercenary', value: 0x0B },
  { label: 'Mercenary Disarmed', value: 0x0C },
  { label: 'Hero w/ Sword', value: 0x0D },
  { label: 'Hero w/ Axe', value: 0x0E },
  { label: 'Hero w/ Hand Axe', value: 0x0F },
  { label: 'Hero Disarmed', value: 0x10 },
  { label: 'Swordfighter', value: 0x11 },
  { label: 'Swordfighter Disarmed', value: 0x12 },
  { label: 'Swordfighter (F)', value: 0x13 },
  { label: 'Swordfighter (F) Disarmed', value: 0x14 },
  { label: 'Swordmaster', value: 0x15 },
  { label: 'Swordmaster Disarmed', value: 0x16 },
  { label: 'Swordmaster (F)', value: 0x17 },
  { label: 'Swordmaster (F) Disarmed', value: 0x18 },
  { label: 'Fighter', value: 0x19 },
  { label: 'Fighter w/ Hand Axe', value: 0x1A },
  { label: 'Fighter Disarmed', value: 0x1B },
  { label: 'Warrior', value: 0x1C },
  { label: 'Warrior w/ Hand Axe', value: 0x1D },
  { label: 'Warrior w/ Bow', value: 0x1E },
  { label: 'Warrior Disarmed', value: 0x1F },
  { label: 'Mountain Thief', value: 0x20 },
  { label: 'Mountain Thief w/ Hand Axe', value: 0x21 },
  { label: 'Mountain Thief Disarmed', value: 0x22 },
  { label: 'Berserker', value: 0x23 },
  { label: 'Berserker w/ Hand Axe', value: 0x24 },
  { label: 'Berserker Disarmed', value: 0x25 },
  { label: 'Archer', value: 0x26 },
  { label: 'Archer Disarmed', value: 0x27 },
  { label: 'Archer (F)', value: 0x28 },
  { label: 'Archer (F) Disarmed', value: 0x29 },
  { label: 'Sniper', value: 0x2A },
  { label: 'Sniper Disarmed', value: 0x2B },
  { label: 'Sniper (F)', value: 0x2C },
  { label: 'Sniper (F) Disarmed', value: 0x2D },
  { label: 'Forrest Knight w/ Sword', value: 0x2E },
  { label: 'Forrest Knight w/ Bow', value: 0x2F },
  { label: 'Forrest Knight Disarmed', value: 0x30 },
  { label: 'Forrest Knight (F) w/ Sword', value: 0x31 },
  { label: 'Forrest Knight (F) w/ Bow', value: 0x32 },
  { label: 'Forrest Knight (F) Disarmed', value: 0x33 },
  { label: 'Socialknight w/ Sword', value: 0x34 },
  { label: 'Socialknight w/ Spear', value: 0x35 },
  { label: 'Socialknight Disarmed', value: 0x36 },
  { label: 'Socialknight (F)', value: 0x37 },
  { label: 'Socialknight (F)', value: 0x38 },
  { label: 'Socialknight (F) Disarmed', value: 0x39 },
  { label: 'Paladin w/ Sword', value: 0x3A },
  { label: 'Paladin w/ Spear', value: 0x3B },
  { label: 'Paladin Disarmed', value: 0x3C },
  { label: 'Paladin (F) w/ Sword', value: 0x3D },
  { label: 'Paladin (F) w/ Spear', value: 0x3E },
  { label: 'Paladin (F) Disarmed', value: 0x3F },
  { label: 'Armour Knight', value: 0x40 },
  { label: 'Armour Knight Disarmed', value: 0x41 },
  { label: 'Armour Knight (F)', value: 0x42 },
  { label: 'Armour Knight (F) Disarmed', value: 0x43 },
  { label: 'General w/ Sword', value: 0x44 },
  { label: 'General w/ Spear', value: 0x45 },
  { label: 'General w/ Axe', value: 0x46 },
  { label: 'General w/ Hand Axe', value: 0x47 },
  { label: 'General Disarmed', value: 0x48 },
  { label: 'General (F) w/ Sword', value: 0x49 },
  { label: 'General (F) w/ Spear', value: 0x4A },
  { label: 'General (F) w/ Axe', value: 0x4B },
  { label: 'General (F) w/ Hand Axe', value: 0x4C },
  { label: 'General (F) Disarmed', value: 0x4D },
  { label: 'Great Knight w/ Sword', value: 0x4E },
  { label: 'Great Knight w/ Spear', value: 0x4F },
  { label: 'Great Knight w/ Axe', value: 0x50 },
  { label: 'Great Knight w/ Hand AXe', value: 0x51 },
  { label: 'Great Knight Disarmed', value: 0x52 },
  { label: 'Great Knight (F) w/ Sword', value: 0x53 },
  { label: 'Great Knight (F) w/ Spear', value: 0x54 },
  { label: 'Great Knight (F) w/ Axe', value: 0x55 },
  { label: 'Great Knight (F) w/ Hand Axe', value: 0x56 },
  { label: 'Great Knight (F) Disarmed', value: 0x57 },
  { label: 'Dragon Knight', value: 0x58 },
  { label: 'Dragon Knight Disarmed', value: 0x59 },
  { label: 'Dragon Knight (F)', value: 0x5A },
  { label: 'Dragon Knight (F) Disarmed', value: 0x5B },
  { label: 'Dragon Master w/ Sword', value: 0x5C },
  { label: 'Dragon Master w/ Spear', value: 0x5D },
  { label: 'Dragon Master Disarmed', value: 0x5E },
  { label: 'Dragon Master (F) w/ Sword', value: 0x5F },
  { label: 'Dragon Master (F) w/ Spear', value: 0x60 },
  { label: 'Dragon Master (F) Disarmed', value: 0x61 },
  { label: 'Wyvern Knight', value: 0x62 },
  { label: 'Wyvern Knight Disarmed', value: 0x63 },
  { label: 'Wyvern Knight (F)', value: 0x64 },
  { label: 'Wyvern Knight Disarmed', value: 0x65 },
  { label: 'Pegasus Knight', value: 0x66 },
  { label: 'Pegasus Knight Disarmed', value: 0x67 },
  { label: 'Falcon Knight w/ Sword', value: 0x68 },
  { label: 'Falcon Knight w/ Spear', value: 0x69 },
  { label: 'Falcon Knight Disarmed', value: 0x6A },
  { label: 'Mage', value: 0x6B },
  { label: 'Mage (F)', value: 0x6C },
  { label: 'Sage', value: 0x6D },
  { label: 'Sage w/ Staff', value: 0x6E },
  { label: 'Sage (F)', value: 0x6F },
  { label: 'Sage (F) w/ Staff', value: 0x70 },
  { label: 'Mage Knight', value: 0x71 },
  { label: 'Mage Knight w/ Staff', value: 0x72 },
  { label: 'Mage Knight', value: 0x73 },
  { label: 'Mage Knight w/ Staff', value: 0x74 },
  { label: 'Shaman', value: 0x75 },
  { label: 'Shaman (F)', value: 0x76 },
  { label: 'Druid', value: 0x77 },
  { label: 'Druid w/ Staff', value: 0x78 },
  { label: 'Druid (F)', value: 0x79 },
  { label: 'Druid (F) w/ Staff', value: 0x7A },
  { label: 'Summoner', value: 0x7B },
  { label: 'Summoner w/ Staff', value: 0x7C },
  { label: 'Monk', value: 0x7D },
  { label: 'Priest Disarmed', value: 0x7E },
  { label: 'Priest', value: 0x7F },
  { label: 'Sister', value: 0x80 },
  { label: 'Bishop Disarmed', value: 0x81 },
  { label: 'Bishop', value: 0x82 },
  { label: 'Bishop (F)', value: 0x83 },
  { label: 'Bishop (F) w/ Staff', value: 0x84 },
  { label: 'Troubadour Disarmed', value: 0x85 },
  { label: 'Troubadour', value: 0x86 },
  { label: 'Valkyrie', value: 0x87 },
  { label: 'Valkyrie w/ Staff', value: 0x88 },
  { label: 'Thief', value: 0x89 },
  { label: 'Thief Disarmed', value: 0x8A },
  { label: 'Assassin', value: 0x8B },
  { label: 'Assassin Disarmed', value: 0x8C },
  { label: 'Assassin (F)', value: 0x8D },
  { label: 'Assassin (F) Disarmed', value: 0x8E },
  { label: 'Rogue', value: 0x8F },
  { label: 'Rogue Disarmed', value: 0x90 },
  { label: 'Dancer', value: 0x91 },
  { label: 'Trainee Fighter', value: 0x92 },
  { label: 'Trainee Fighter w/ Hand Axe', value: 0x93 },
  { label: 'Trainee Fighter Disarmed', value: 0x94 },
  { label: 'Trainee Mage', value: 0x95 },
  { label: 'Trainee Soldier', value: 0x96 },
  { label: 'Trainee Soldier Disarmed', value: 0x97 },
  { label: 'Soldier', value: 0x98 },
  { label: 'Soldier Disarmed', value: 0x99 },
  { label: 'Pirate', value: 0x9A },
  { label: 'Pirate w/ Hand Axe', value: 0x9B },
  { label: 'Pirate Disarmed', value: 0x9C },
  { label: 'Necromancer', value: 0x9D },
  { label: 'Necromancer w/ Staff', value: 0x9E },
  { label: 'Archer on Ballista (unused)', value: 0x9F },
  { label: 'Zombie', value: 0xA0 },
  { label: 'Mummy', value: 0xA1 },
  { label: 'Skeleton w/ Sword', value: 0xA2 },
  { label: 'Skeleton w/ Spear', value: 0xA3 },
  { label: 'Skeleton Disarmed', value: 0xA4 },
  { label: 'Skeleton w/ Bow', value: 0xA5 },
  { label: 'Skeleton Disarmed', value: 0xA6 },
  { label: 'Hellbone w/ Sword', value: 0xA7 },
  { label: 'Hellbone w/ Spear', value: 0xA8 },
  { label: 'Hellbone Disarmed', value: 0xA9 },
  { label: 'Hellbone w/ Bow', value: 0xAA },
  { label: 'Hellbone Disarmed', value: 0xAB },
  { label: 'Bael', value: 0xAC },
  { label: 'Elder Bael', value: 0xAD },
  { label: 'Cyclops', value: 0xAE },
  { label: 'Cyclops w/ Hand Axe', value: 0xAF },
  { label: 'Cyclops Disarmed', value: 0xB0 },
  { label: 'Mauthedoog', value: 0xB1 },
  { label: 'Cerberus', value: 0xB2 },
  { label: 'Tarvos', value: 0xB3 },
  { label: 'Tarvos w/ Hand Axe', value: 0xB4 },
  { label: 'Tarvos Disarmed', value: 0xB5 },
  { label: 'Macdaire w/ Axe', value: 0xB6 },
  { label: 'Macdaire w/ Hand Axe', value: 0xB7 },
  { label: 'Macdaire w/ Bow', value: 0xB8 },
  { label: 'Macdaire Disarmed', value: 0xB9 },
  { label: 'Bigl', value: 0xBA },
  { label: 'Arch Bigl', value: 0xBB },
  { label: 'Gorgon', value: 0xBC },
  { label: 'Gargoyle', value: 0xBD },
  { label: 'Gargoyle Disarmed', value: 0xBE },
  { label: 'Death Gargoyle', value: 0xBF },
  { label: 'Death Gargoyle Disarmed', value: 0xC0 },
  { label: 'Zombie Dragon', value: 0xC1 },
  { label: 'Demon King w/ Ravager', value: 0xC2 },
  { label: 'Demon King w/ Demon Light', value: 0xC3 },
  { label: 'Mamkute (F)', value: 0xC4 },
  { label: 'Myrra Disarmed', value: 0xC5 },
  { label: 'White Mamkute Disarmed', value: 0xC6 },
  { label: 'Myrra Disarmed', value: 0xC7 },
  { label: 'Sister Disarmed', value: 0xC8 },
  { label: 'Mamkute', value: 0xC9 },
  { label: '0xCA', value: 0xCA },
  { label: '0xCB', value: 0xCB },
  { label: '0xCC', value: 0xCC },
  { label: '0xCD', value: 0xCD },
  { label: '0xCE', value: 0xCE },
  { label: '0xCF', value: 0xCF },
  { label: '0xD0', value: 0xD0 },
  { label: '0xD1', value: 0xD1 },
  { label: '0xD2', value: 0xD2 },
  { label: '0xD3', value: 0xD3 },
  { label: '0xD4', value: 0xD4 },
  { label: '0xD5', value: 0xD5 },
  { label: '0xD6', value: 0xD6 },
  { label: '0xD7', value: 0xD7 },
  { label: '0xD8', value: 0xD8 },
  { label: '0xD9', value: 0xD9 },
  { label: '0xDA', value: 0xDA },
  { label: '0xDB', value: 0xDB },
  { label: '0xDC', value: 0xDC },
  { label: '0xDD', value: 0xDD },
  { label: '0xDE', value: 0xDE },
  { label: '0xDF', value: 0xDF },
  { label: '0xE0', value: 0xE0 },
  { label: '0xE1', value: 0xE1 },
  { label: '0xE2', value: 0xE2 },
  { label: '0xE3', value: 0xE3 },
  { label: '0xE4', value: 0xE4 },
  { label: '0xE5', value: 0xE5 },
  { label: '0xE6', value: 0xE6 },
  { label: '0xE7', value: 0xE7 },
  { label: '0xE8', value: 0xE8 },
  { label: '0xE9', value: 0xE9 },
  { label: '0xEA', value: 0xEA },
  { label: '0xEB', value: 0xEB },
  { label: '0xEC', value: 0xEC },
  { label: '0xED', value: 0xED },
  { label: '0xEE', value: 0xEE },
  { label: '0xEF', value: 0xEF },
  { label: '0xF0', value: 0xF0 },
  { label: '0xF1', value: 0xF1 },
  { label: '0xF2', value: 0xF2 },
  { label: '0xF3', value: 0xF3 },
  { label: '0xF4', value: 0xF4 },
  { label: '0xF5', value: 0xF5 },
  { label: '0xF6', value: 0xF6 },
  { label: '0xF7', value: 0xF7 },
  { label: '0xF8', value: 0xF8 },
  { label: '0xF9', value: 0xF9 },
  { label: '0xFA', value: 0xFA },
  { label: '0xFB', value: 0xFB },
  { label: '0xFC', value: 0xFC },
  { label: '0xFD', value: 0xFD },
  { label: '0xFE', value: 0xFE },
  { label: '0xFF', value: 0xFF },
];
