export const FE5ItemList = [
  { label: 'Iron Sword', value: 0 },
  { label: 'Steel Sword', value: 1 },
  { label: 'Silver Sword', value: 2 },
  { label: 'Thin Sword', value: 3 },
  { label: 'Iron Broadsword', value: 4 },
  { label: 'Killer Sword', value: 5 },
  { label: 'Poison Sword', value: 6 },
  { label: 'Berserk Sword', value: 7 },
  { label: 'Sleep Sword', value: 8 },
  { label: 'Beosword', value: 9 },
  { label: 'Holy Sword', value: 10 },
  { label: 'Loputous Sword', value: 11 },
  { label: 'Blagi Sword', value: 12 },
  { label: 'Light Sword', value: 13 },
  { label: 'Hero Sword', value: 14 },
  { label: 'King Sword', value: 15 },
  { label: 'Earth Sword', value: 16 },
  { label: 'Wind Sword', value: 17 },
  { label: 'Fire Sword', value: 18 },
  { label: 'Thunder Sword', value: 19 },
  { label: 'Elite Sword', value: 20 },
  { label: 'Armour Killer', value: 21 },
  { label: 'Rapier', value: 22 },
  { label: 'Short Sword', value: 23 },
  { label: 'Long Sword', value: 24 },
  { label: 'Great Sword', value: 25 },
  { label: 'Master Sword', value: 26 },
  { label: 'Darkness Sword', value: 27 },
  { label: 'Mareeta\'s Sword', value: 28 },
  { label: 'Broken Sword', value: 29 },
  { label: 'Iron Lance', value: 30 },
  { label: 'Steel Lance', value: 31 },
  { label: 'Silver Lance', value: 32 },
  { label: 'Thin Lance', value: 33 },
  { label: 'Poison Lance', value: 34 },
  { label: 'Dragon Lance', value: 35 },
  { label: 'Darkness Lance', value: 36 },
  { label: 'Hero Lance', value: 37 },
  { label: 'Short Lance', value: 38 },
  { label: 'Long Lance', value: 39 },
  { label: 'Great Lance', value: 40 },
  { label: 'Javelin', value: 41 },
  { label: 'Master Lance', value: 42 },
  { label: 'Knight Killer', value: 43 },
  { label: 'Killer Lance', value: 44 },
  { label: 'Gae Bolg', value: 45 },
  { label: 'Gungnir', value: 46 },
  { label: 'Broken Lance', value: 47 },
  { label: 'Iron Axe', value: 48 },
  { label: 'Poison Axe', value: 49 },
  { label: 'Steel Axe', value: 50 },
  { label: 'Silver Axe', value: 51 },
  { label: 'Hand Axe', value: 52 },
  { label: 'Hammer', value: 53 },
  { label: 'Killer Axe', value: 54 },
  { label: 'Pugi', value: 55 },
  { label: 'Hero Axe', value: 56 },
  { label: 'Devil Axe', value: 57 },
  { label: 'Battle Axe', value: 58 },
  { label: 'Poleaxe', value: 59 },
  { label: 'Master Axe', value: 60 },
  { label: 'Broken Axe', value: 61 },
  { label: 'Iron Bow', value: 62 },
  { label: 'Steel Bow', value: 63 },
  { label: 'Silver Bow', value: 64 },
  { label: 'Poison Bow', value: 65 },
  { label: 'Killer Bow', value: 66 },
  { label: 'Hero Bow', value: 67 },
  { label: 'Short Bow', value: 68 },
  { label: 'Long Bow', value: 69 },
  { label: 'Great Bow', value: 70 },
  { label: 'Master Bow', value: 71 },
  { label: 'Long Arch', value: 72 },
  { label: 'Iron Arch', value: 73 },
  { label: 'Killer Arch', value: 74 },
  { label: 'Poison Arch', value: 75 },
  { label: 'Broken Bow', value: 76 },
  { label: 'Fire', value: 77 },
  { label: 'Elfire', value: 78 },
  { label: 'Volcannon', value: 79 },
  { label: 'Falaflame', value: 80 },
  { label: 'Thunder', value: 81 },
  { label: 'Daim Thunder', value: 82 },
  { label: 'Tron', value: 83 },
  { label: 'Torhammer', value: 84 },
  { label: 'Wind', value: 85 },
  { label: 'Grafucalibur', value: 86 },
  { label: 'Tornado', value: 87 },
  { label: 'Holsety', value: 88 },
  { label: 'Lightning', value: 89 },
  { label: 'Rizziah', value: 90 },
  { label: 'Aura', value: 91 },
  { label: 'Yotsmungand', value: 92 },
  { label: 'Fenrir', value: 93 },
  { label: 'Hell', value: 94 },
  { label: 'Loputous', value: 95 },
  { label: 'Meteo', value: 96 },
  { label: 'Thunderstorm', value: 97 },
  { label: 'Blizzard', value: 98 },
  { label: 'Poison', value: 99 },
  { label: 'Stone', value: 100 },
  { label: 'Holsety(Unlimited)', value: 101 },
  { label: 'Broken Book', value: 102 },
  { label: 'Live', value: 103 },
  { label: 'Relive', value: 104 },
  { label: 'Recover', value: 105 },
  { label: 'Libro', value: 106 },
  { label: 'Reserve', value: 107 },
  { label: 'Rescue', value: 108 },
  { label: 'Warp', value: 109 },
  { label: 'Rest', value: 110 },
  { label: 'Silence', value: 111 },
  { label: 'Sleep', value: 112 },
  { label: 'Torch', value: 113 },
  { label: 'Return', value: 114 },
  { label: 'Repair', value: 115 },
  { label: 'Thief', value: 116 },
  { label: 'Watch', value: 117 },
  { label: 'Berserk', value: 118 },
  { label: 'Unlock', value: 119 },
  { label: 'Magic Shield', value: 120 },
  { label: 'Rewarp', value: 121 },
  { label: 'Cure', value: 122 },
  { label: 'Broken Staff', value: 123 },
  { label: 'Luck Ring', value: 124 },
  { label: 'Live Ring', value: 125 },
  { label: 'Speed Ring', value: 126 },
  { label: 'Magic Ring', value: 127 },
  { label: 'Power Ring', value: 128 },
  { label: 'Body Ring', value: 129 },
  { label: 'Shield Ring', value: 130 },
  { label: 'Skill Ring', value: 131 },
  { label: 'Leg Ring', value: 132 },
  { label: 'Knight Proof', value: 133 },
  { label: 'Master Proof', value: 134 },
  { label: 'Treasure Key', value: 135 },
  { label: 'Door Key', value: 136 },
  { label: 'Bridge Key', value: 137 },
  { label: 'Thief Key', value: 138 },
  { label: 'S Drink', value: 139 },
  { label: 'Medicine', value: 140 },
  { label: 'Holy Water', value: 141 },
  { label: 'Torch', value: 142 },
  { label: 'Antidote', value: 143 },
  { label: 'Member Card', value: 144 },
  { label: 'Odo Scroll', value: 145 },
  { label: 'Baldo Scroll', value: 146 },
  { label: 'Hezul Scroll', value: 147 },
  { label: 'Dain Scroll', value: 148 },
  { label: 'Noba Scroll', value: 149 },
  { label: 'Neir Scroll', value: 150 },
  { label: 'Ulir Scroll', value: 151 },
  { label: 'Tordo Scroll', value: 152 },
  { label: 'Fala Scroll', value: 153 },
  { label: 'Sety Scroll', value: 154 },
  { label: 'Blagi Scroll', value: 155 },
  { label: 'Heim Scroll', value: 156 },
  { label: 'Elite Manual', value: 157 },
  { label: 'Duel Manual', value: 158 },
  { label: 'Bargain Manual', value: 159 },
  { label: 'Ambush Manual', value: 160 },
  { label: 'Wrath Manual', value: 161 },
  { label: 'Continue Manual', value: 162 },
  { label: 'Prayer Manual', value: 163 },
  { label: 'Awareness Manual', value: 164 },
  { label: 'Sunlight Manual', value: 165 },
  { label: 'Moonlight Manual', value: 166 },
];

export const FE5ItemTypes = [
  { label: 'Sword', value: 0x00 },
  { label: 'Lance', value: 0x01 },
  { label: 'Axe', value: 0x02 },
  { label: 'Bow', value: 0x03 },
  { label: 'Staff', value: 0x04 },
  { label: 'Fire', value: 0x05 },
  { label: 'Thunder', value: 0x06 },
  { label: 'Wind', value: 0x07 },
  { label: 'Light', value: 0x08 },
  { label: 'Dark', value: 0x09 },
  { label: 'Item', value: 0x0B },
  { label: 'Fire Sword', value: 0x50 },
  { label: 'Thunder Sword', value: 0x60 },
  { label: 'Wind Sword', value: 0x70 },
  { label: 'Light Sword', value: 0x80 },
];

export const WeaponRange = [
  { label: '1~1', value: 0x11 },
  { label: '1~2', value: 0x21 },
  { label: '2~2', value: 0x22 },
  { label: '3~10', value: 0xA3 },
  { label: '3~15', value: 0xF3 },
  { label: 'Infinite (staves only)', value: 0xA1 },
];

export const FE5WeaponRank = [
  { label: '-', value: 0x0000 },
  { label: 'E', value: 0x0032 },
  { label: 'D', value: 0x0064 },
  { label: 'C', value: 0x0096 },
  { label: 'B', value: 0x00C8 },
  { label: 'A', value: 0x00FA },
  { label: '---->Custom Lock 1<----', value: 0xF560 },
  { label: '---->Custom Lock 2<----', value: 0xF570 },
  { label: '---->Custom Lock 3<----', value: 0xF580 },
  { label: '---->Custom Lock 4<----', value: 0xF590 },
  { label: '---->Custom Lock 5<----', value: 0xF5A0 },
  { label: '---->Custom Lock 6<----', value: 0xF5B0 },
  { label: '---->Custom Lock 7<----', value: 0xF5C0 },
  { label: '---->Custom Lock 8<----', value: 0xF5D0 },
  { label: '---->Custom Lock 9<----', value: 0xF5E0 },
  { label: '---->Custom Lock 10<----', value: 0xF5F0 },
  { label: '---->Custom Lock 11<----', value: 0xF600 },
  { label: '---->Custom Lock 12<----', value: 0xF610 },
  { label: '---->Custom Lock 13<----', value: 0xF620 },
  { label: '---->Custom Lock 14<----', value: 0xF630 },
  { label: '---->Custom Lock 15<----', value: 0xF640 },
  { label: '---->Custom Lock 16<----', value: 0xF650 },
  { label: 'Nanna', value: 0x99DA },
  { label: 'Asvel', value: 0x99DE },
  { label: 'Sara', value: 0x99EC },
  { label: 'Sety', value: 0x99F0 },
  { label: 'Nanna/Delmud/Fergus/Leaf', value: 0x99FA },
  { label: 'Leidrick/Ains', value: 0x9A64 },
  { label: 'Fergus/Delmud', value: 0x9A3A },
  { label: 'Olwen/Reinhardt', value: 0x9A52 },
  { label: 'Leaf', value: 0x9A00 },
  { label: 'Mareeta', value: 0x9A4E },
  { label: 'Althenna/Dean', value: 0x9A44 },
  { label: 'Finn', value: 0x9A40 },
  { label: 'Othin/(Berserker)', value: 0x9A04 },
  { label: 'Manster/Freege', value: 0x9A0E },
  { label: '(Iron Arch)/Freege', value: 0x9A22 },
  { label: 'Nobody', value: 0x9A1A },
  { label: 'Freege/Manster', value: 0x9A1C },
  { label: 'Nobody', value: 0x9A76 },
  { label: 'Ishtar', value: 0x9A0A },
  { label: 'Araphen/Loputo/Beldo', value: 0x9A6C },
  { label: 'Nobody', value: 0x9A76 },
  { label: 'Nobody', value: 0x9A78 },
  { label: 'Saphy', value: 0x9A36 },
  { label: 'Tina/Loputo', value: 0x9A28 },
  { label: 'Tina/Freege/Loputo', value: 0x9A2E },
];

export const FE5WeaponEffectiveness = [
  { label: 'None', value: 0x80AA },
  { label: '---->Custom Effectiveness 1<----', value: 0xF700 },
  { label: '---->Custom Effectiveness 2<----', value: 0xF710 },
  { label: '---->Custom Effectiveness 3<----', value: 0xF720 },
  { label: '---->Custom Effectiveness 4<----', value: 0xF730 },
  { label: '---->Custom Effectiveness 5<----', value: 0xF740 },
  { label: '---->Custom Effectiveness 6<----', value: 0xF750 },
  { label: '---->Custom Effectiveness 7<----', value: 0xF760 },
  { label: '---->Custom Effectiveness 8<----', value: 0xF770 },
  { label: '---->Custom Effectiveness 9<----', value: 0xF780 },
  { label: '---->Custom Effectiveness 10<----', value: 0xF790 },
  { label: '---->Custom Effectiveness 11<----', value: 0xF7A0 },
  { label: '---->Custom Effectiveness 12<----', value: 0xF7B0 },
  { label: '---->Custom Effectiveness 13<----', value: 0xF7C0 },
  { label: '---->Custom Effectiveness 14<----', value: 0xF7D0 },
  { label: '---->Custom Effectiveness 15<----', value: 0xF7E0 },
  { label: '---->Custom Effectiveness 16<----', value: 0xF7F0 },
  { label: 'Armours', value: 0x807A },
  { label: 'Dragons', value: 0x8082 },
  { label: 'Flying', value: 0x8086 },
  { label: 'Armours/Knights', value: 0x808F },
  { label: 'Knights', value: 0x8096 },
];

export const FE5StatBonuses = [
  { label: '-', value: 0x8000 },
  { label: '---->Custom Bonuses 1<----', value: 0xF660 },
  { label: '---->Custom Bonuses 2<----', value: 0xF670 },
  { label: '---->Custom Bonuses 3<----', value: 0xF680 },
  { label: '---->Custom Bonuses 4<----', value: 0xF690 },
  { label: '---->Custom Bonuses 5<----', value: 0xF6A0 },
  { label: '---->Custom Bonuses 6<----', value: 0xF6B0 },
  { label: '---->Custom Bonuses 7<----', value: 0xF6C0 },
  { label: '---->Custom Bonuses 8<----', value: 0xF6D0 },
  { label: '---->Custom Bonuses 9<----', value: 0xF6E0 },
  { label: '---->Custom Bonuses 10<----', value: 0xF6F0 },
  { label: '---->Custom Bonuses 11<----', value: 0xF700 },
  { label: '---->Custom Bonuses 12<----', value: 0xF710 },
  { label: '---->Custom Bonuses 13<----', value: 0xF720 },
  { label: '---->Custom Bonuses 14<----', value: 0xF730 },
  { label: '---->Custom Bonuses 15<----', value: 0xF740 },
  { label: '---->Custom Bonuses 16<----', value: 0xF750 },
  { label: '---->Custom Bonuses 17<----', value: 0xF770 },
  { label: '---->Custom Bonuses 18<----', value: 0xF780 },
  { label: '---->Custom Bonuses 19<----', value: 0xF790 },
  { label: '---->Custom Bonuses 20<----', value: 0xF7A0 },
  { label: '---->Custom Bonuses 21<----', value: 0xF7B0 },
  { label: '---->Custom Bonuses 22<----', value: 0xF7C0 },
  { label: '---->Custom Bonuses 23<----', value: 0xF7D0 },
  { label: '---->Custom Bonuses 24<----', value: 0xF7E0 },
  { label: '---->Custom Bonuses 25<----', value: 0xF7F0 },
  { label: '-', value: 0x8001 },
  { label: '-', value: 0x8002 },
  { label: '-', value: 0x8003 },
  { label: '-', value: 0x8004 },
  { label: '+10 LUK', value: 0x8005 },
  { label: '-', value: 0x8006 },
  { label: '+10 DEF', value: 0x8007 },
  { label: '+10 SPD', value: 0x8008 },
  { label: '+10 SKL', value: 0x8009 },
  { label: '+10 MGC', value: 0x800A },
  { label: '+10 STR', value: 0x800B },
  { label: '-', value: 0x800C },
  { label: '-', value: 0x800D },
  { label: '-', value: 0x800E },
  { label: '-', value: 0x800F },
  { label: '-', value: 0x8010 },
  { label: '-', value: 0x8011 },
  { label: '+10 LUK', value: 0x8012 },
  { label: '-', value: 0x8013 },
  { label: '+10 DEF', value: 0x8014 },
  { label: '+10 SPD', value: 0x8015 },
  { label: '+10 SKL', value: 0x8016 },
  { label: '+10 MGC, +5 LUK', value: 0x8017 },
  { label: '+10 STR', value: 0x8018 },
  { label: '+5 DEF', value: 0x8019 },
  { label: '+5 SPD', value: 0x801A },
  { label: '+5 SKL', value: 0x801B },
  { label: '+5 MGC', value: 0x801C },
  { label: '+5 STR, +5 LUK', value: 0x801D },
  { label: '-', value: 0x801E },
  { label: '+5 DEF', value: 0x801F },
  { label: '+5 SPD', value: 0x8020 },
  { label: '+5 SKL', value: 0x8021 },
  { label: '+5 MGC', value: 0x8022 },
  { label: '+5 STR', value: 0x8023 },
  { label: '-', value: 0x8024 },
  { label: '-', value: 0x8025 },
  { label: '+5 LUK', value: 0x8026 },
  { label: '-', value: 0x8027 },
  { label: '+5 DEF', value: 0x8028 },
  { label: '+5 SPD', value: 0x8029 },
  { label: '+5 SKL', value: 0x802A },
  { label: '+5 MGC', value: 0x802B },
  { label: '+5 STR', value: 0x802C },
  { label: '-', value: 0x802D },
  { label: '-', value: 0x802E },
  { label: '-', value: 0x802F },
  { label: '+5 LUK', value: 0x8030 },
  { label: '-', value: 0x8031 },
  { label: '+5 DEF', value: 0x8032 },
  { label: '+5 SPD', value: 0x8033 },
  { label: '+5 SKL', value: 0x8034 },
  { label: '+5 MGC, +20 LUK', value: 0x8035 },
  { label: '+5 STR', value: 0x8036 },
  { label: '+20 DEF', value: 0x8037 },
  { label: '+20 SPD', value: 0x8038 },
  { label: '+20 SKL', value: 0x8039 },
  { label: '+20 MGC', value: 0x803A },
  { label: '+20 STR', value: 0x803B },
  { label: '-', value: 0x803C },
  { label: '-', value: 0x803D },
  { label: '-', value: 0x803E },
  { label: '-', value: 0x803F },
  { label: '-', value: 0x8040 },
  { label: '-', value: 0x8041 },
  { label: '+10 LUK', value: 0x8042 },
  { label: '-', value: 0x8043 },
  { label: '+10 DEF', value: 0x8044 },
  { label: '+10 SPD', value: 0x8045 },
  { label: '+10 SKL, +20 LUK', value: 0x8046 },
  { label: '+10 MGC, +20 LUK', value: 0x8047 },
  { label: '+10 STR, +20 DEF', value: 0x8048 },
  { label: '+20 SPD, +20 DEF', value: 0x8049 },
  { label: '+20 SKL, +20 SPD', value: 0x804A },
  { label: '+20 MGC, +20 SKL', value: 0x804B },
  { label: '+20 STR, +20 MGC', value: 0x804C },
  { label: '+20 STR', value: 0x804D },
  { label: '-', value: 0x804E },
  { label: '-', value: 0x804F },
  { label: '-', value: 0x8050 },
  { label: '-', value: 0x8051 },
  { label: '-', value: 0x8052 },
  { label: '-', value: 0x8053 },
  { label: '-', value: 0x8054 },
  { label: '+20 LUK', value: 0x8055 },
  { label: '-', value: 0x8056 },
  { label: '+20 DEF', value: 0x8057 },
  { label: '+20 SPD', value: 0x8058 },
  { label: '+20 SKL', value: 0x8059 },
  { label: '+20 MGC', value: 0x805A },
  { label: '+20 STR', value: 0x805B },
  { label: '-', value: 0x805C },
  { label: '-', value: 0x805D },
  { label: '-', value: 0x805E },
  { label: '+20 LUK', value: 0x805F },
  { label: '-', value: 0x8060 },
  { label: '+20 DEF', value: 0x8061 },
  { label: '+20 SPD', value: 0x8062 },
  { label: '+20 SKL', value: 0x8063 },
  { label: '+20 MGC', value: 0x8064 },
  { label: '+20 STR', value: 0x8065 },
  { label: '-', value: 0x8066 },
  { label: '-', value: 0x8067 },
  { label: '+10 LUK', value: 0x8068 },
  { label: '-', value: 0x8069 },
  { label: '+10 DEF', value: 0x806A },
  { label: '+10 SPD', value: 0x806B },
  { label: '+10 SKL, +10 LUK', value: 0x806C },
  { label: '+10 MGC', value: 0x806D },
  { label: '+10 STR, +10 DEF', value: 0x806E },
  { label: '+10 SPD', value: 0x806F },
  { label: '+10 SKL', value: 0x8070 },
  { label: '+10 MGC', value: 0x8071 },
  { label: '+10 STR', value: 0x8072 },
  { label: '-', value: 0x8073 },
];

export const FE5ItemUseEffect = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Luck Ring effect', value: 0x02 },
  { label: 'Live Ring effect', value: 0x04 },
  { label: 'Speed Ring effect', value: 0x06 },
  { label: 'Magic Ring effect', value: 0x08 },
  { label: 'Power Ring effect', value: 0x0A },
  { label: 'Body Ring effect', value: 0x0C },
  { label: 'Shield Ring effect', value: 0x0E },
  { label: 'Skill Ring effect', value: 0x10 },
  { label: 'Leg Ring effect', value: 0x12 },
  { label: 'Knight Proof effect', value: 0x14 },
  { label: 'Master Proof effect', value: 0x16 },
  { label: 'Treasure Key effect', value: 0x18 },
  { label: 'Door Key effect', value: 0x1A },
  { label: 'Bridge Key effect', value: 0x1C },
  { label: 'Thief Key effect', value: 0x1E },
  { label: 'Medicine effect', value: 0x20 },
  { label: 'Holy Water effect', value: 0x22 },
  { label: 'Torch effect', value: 0x24 },
  { label: 'Antidote effect', value: 0x26 },
  { label: 'Elite Skill', value: 0x28 },
  { label: 'Duel Skill', value: 0x2A },
  { label: 'Bargain Skill', value: 0x2C },
  { label: 'Ambush Skill', value: 0x2E },
  { label: 'Wrath Skill', value: 0x30 },
  { label: 'Continue Skill', value: 0x32 },
  { label: 'Prayer Skill', value: 0x34 },
  { label: 'Awareness Skill', value: 0x36 },
  { label: 'Sunlight Skill', value: 0x38 },
  { label: 'Moonlight Skill', value: 0x3A },
  { label: 'Live Staff effect', value: 0x3C },
  { label: 'Relive Staff effect', value: 0x3E },
  { label: 'Recover Staff effect', value: 0x40 },
  { label: 'Libro Staff effect', value: 0x42 },
  { label: 'Reserve Staff effect', value: 0x44 },
  { label: 'Rescue Staff effect', value: 0x46 },
  { label: 'Warp Staff effect', value: 0x48 },
  { label: 'Rest Staff effect', value: 0x4A },
  { label: 'Silence Staff effect', value: 0x4C },
  { label: 'Sleep Staff effect', value: 0x4E },
  { label: 'Torch Staff effect', value: 0x50 },
  { label: 'Return Staff effect', value: 0x52 },
  { label: 'Repair Staff effect', value: 0x54 },
  { label: 'Thief Staff effect', value: 0x56 },
  { label: 'Watch Staff effect', value: 0x58 },
  { label: 'Berserk Staff effect', value: 0x5A },
  { label: 'Unlock Staff effect', value: 0x5C },
  { label: 'Magic Shield effect', value: 0x5E },
  { label: 'Rewarp effect', value: 0x60 },
  { label: 'S Drink effect', value: 0x66 },
  { label: 'Cure Staff effect', value: 0x68 },
];

export const FE5WeaponBladeEffect = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Poison', value: 0x02 },
  { label: 'Devil', value: 0x04 },
  { label: 'Steal HP', value: 0x06 },
  { label: 'Stone', value: 0x08 },
  { label: 'Hell', value: 0x0A },
  { label: 'Berserk', value: 0x0C },
  { label: 'Sleep', value: 0x0E },
];

export const FE5WeaponSkills1 = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Charisma', value: 0x02 },
  { label: '0x0A', value: 0x0A },
  { label: '0x12', value: 0x12 },
  { label: '0x82', value: 0x82 },
  { label: 'Prayer', value: 0x08 },
  { label: '0x18', value: 0x18 },
  { label: '0x88', value: 0x88 },
  { label: 'Wrath', value: 0x10 },
  { label: '0x90', value: 0x90 },
  { label: 'Awareness', value: 0x80 },
  { label: '0x1A', value: 0x1A },
  { label: '0x8A', value: 0x8A },
  { label: '0x92', value: 0x92 },
  { label: '0x98', value: 0x98 },
  { label: '0x9A', value: 0x9A },
];

export const FE5WeaponSkills2 = [
  { label: 'Nothing', value: 0x00 },
  { label: 'Ambush', value: 0x01 },
  { label: 'Elite', value: 0x10 },
  { label: '0x11', value: 0x11 },
  { label: '2x-Attack', value: 0x40 },
  { label: '0x41', value: 0x41 },
  { label: '0x50', value: 0x50 },
  { label: '0x51', value: 0x51 },
];

export const FE5WeaponCapabilities = [
  { label: 'Item', value: 0x00 },
  { label: 'Weapon', value: 0x04 },
  { label: 'Magic Weapon', value: 0x06 },
  { label: 'Magic', value: 0x0C },
  { label: 'Staff', value: 0x10 },
  { label: 'Infinite Use Item', value: 0x20 },
  { label: 'Infinite Use Weapon', value: 0x24 },
  { label: 'Infinite Use Magic Weapon', value: 0x26 },
  { label: 'Infinite Use Magic', value: 0x2C },
  { label: 'Infinite Use Staff', value: 0x30 },
  { label: 'Treasure Item', value: 0x40 },
  { label: 'Treasure Weapon', value: 0x44 },
  { label: 'Treasure Magic Weapon', value: 0x46 },
  { label: 'Treasure Magic', value: 0x4C },
  { label: 'Treasure Staff', value: 0x50 },
  { label: 'Infinite Use Treasure Item', value: 0x60 },
  { label: 'Infinite Use Treasure Weapon', value: 0x64 },
  { label: 'Infinite Use Treasure Magic Weapon', value: 0x66 },
  { label: 'Infinite Use Treasure Magic', value: 0x6C },
  { label: 'Infinite Use Treasure Staff', value: 0x70 },
  { label: 'Broken Item', value: 0xA0 },
  { label: 'Broken Weapon', value: 0xA4 },
];

export const FE5ItemIcons = [
  { label: 'Iron Sword', value: 0x00 },
  { label: 'Steel Sword', value: 0x01 },
  { label: 'Silver Sword', value: 0x02 },
  { label: 'Thin Sword', value: 0x03 },
  { label: 'Iron Broadsword', value: 0x04 },
  { label: 'Killer Sword', value: 0x05 },
  { label: 'Poison Sword', value: 0x06 },
  { label: 'Berserk Sword', value: 0x07 },
  { label: 'Sleep Sword', value: 0x08 },
  { label: 'Beosword', value: 0x09 },
  { label: 'Holy Sword', value: 0x0A },
  { label: 'Loputous Sword', value: 0x0B },
  { label: 'Blagi Sword', value: 0x0C },
  { label: 'Light Sword', value: 0x0D },
  { label: 'Hero Sword', value: 0x0E },
  { label: 'King Sword', value: 0x0F },
  { label: 'Earth Sword', value: 0x10 },
  { label: 'Wind Sword', value: 0x11 },
  { label: 'Fire Sword', value: 0x12 },
  { label: 'Thunder Sword', value: 0x13 },
  { label: 'Elite Sword', value: 0x14 },
  { label: 'Armour Killer', value: 0x15 },
  { label: 'Rapier', value: 0x16 },
  { label: 'Short Sword', value: 0x17 },
  { label: 'Long Sword', value: 0x18 },
  { label: 'Great Sword', value: 0x19 },
  { label: 'Master Sword', value: 0x1A },
  { label: 'Darkness Sword', value: 0x1B },
  { label: 'Mareeta\'s Sword', value: 0x1C },
  { label: 'Broken Sword', value: 0x1D },
  { label: 'Iron Lance', value: 0x1E },
  { label: 'Steel Lance', value: 0x1F },
  { label: 'Silver Lance', value: 0x20 },
  { label: 'Thin Lance', value: 0x21 },
  { label: 'Poison Lance', value: 0x22 },
  { label: 'Dragon Lance', value: 0x23 },
  { label: 'Darkness Lance', value: 0x24 },
  { label: 'Hero Lance', value: 0x25 },
  { label: 'Short Lance', value: 0x26 },
  { label: 'Long Lance', value: 0x27 },
  { label: 'Great Lance', value: 0x28 },
  { label: 'Javelin', value: 0x29 },
  { label: 'Master Lance', value: 0x2A },
  { label: 'Knight Killer', value: 0x2B },
  { label: 'Killer Lance', value: 0x2C },
  { label: 'Gae Bolg', value: 0x2D },
  { label: 'Gungnir', value: 0x2E },
  { label: 'Broken Lance', value: 0x2F },
  { label: 'Iron Axe', value: 0x30 },
  { label: 'Poison Axe', value: 0x31 },
  { label: 'Steel Axe', value: 0x32 },
  { label: 'Silver Axe', value: 0x33 },
  { label: 'Hand Axe', value: 0x34 },
  { label: 'Hammer', value: 0x35 },
  { label: 'Killer Axe', value: 0x36 },
  { label: 'Pugi', value: 0x37 },
  { label: 'Hero Axe', value: 0x38 },
  { label: 'Devil Axe', value: 0x39 },
  { label: 'Battle Axe', value: 0x3A },
  { label: 'Poleaxe', value: 0x3B },
  { label: 'Master Axe', value: 0x3C },
  { label: 'Broken Axe', value: 0x3D },
  { label: 'Iron Bow', value: 0x3E },
  { label: 'Steel Bow', value: 0x3F },
  { label: 'Silver Bow', value: 0x40 },
  { label: 'Poison Bow', value: 0x41 },
  { label: 'Killer Bow', value: 0x42 },
  { label: 'Hero Bow', value: 0x43 },
  { label: 'Short Bow', value: 0x44 },
  { label: 'Long Bow', value: 0x45 },
  { label: 'Great Bow', value: 0x46 },
  { label: 'Master Bow', value: 0x47 },
  { label: 'Long Arch', value: 0x48 },
  { label: 'Iron Arch', value: 0x49 },
  { label: 'Killer Arch', value: 0x4A },
  { label: 'Poison Arch', value: 0x4B },
  { label: 'Broken Bow', value: 0x4C },
  { label: 'Fire', value: 0x4D },
  { label: 'Elfire', value: 0x4E },
  { label: 'Volcannon', value: 0x4F },
  { label: 'Falaflame', value: 0x50 },
  { label: 'Thunder', value: 0x51 },
  { label: 'Daim Thunder', value: 0x52 },
  { label: 'Tron', value: 0x53 },
  { label: 'Torhammer', value: 0x54 },
  { label: 'Wind', value: 0x55 },
  { label: 'Grafucalibur', value: 0x56 },
  { label: 'Tornado', value: 0x57 },
  { label: 'Holsety', value: 0x58 },
  { label: 'Lightning', value: 0x59 },
  { label: 'Rizziah', value: 0x5A },
  { label: 'Aura', value: 0x5B },
  { label: 'Yotsmungand', value: 0x5C },
  { label: 'Fenrir', value: 0x5D },
  { label: 'Hell', value: 0x5E },
  { label: 'Loputous', value: 0x5F },
  { label: 'Meteo', value: 0x60 },
  { label: 'Thunderstorm', value: 0x61 },
  { label: 'Blizzard', value: 0x62 },
  { label: 'Poison', value: 0x63 },
  { label: 'Stone', value: 0x64 },
  { label: 'UNUSED (Stone)', value: 0x65 },
  { label: 'Broken Book', value: 0x66 },
  { label: 'Live', value: 0x67 },
  { label: 'Relive', value: 0x68 },
  { label: 'Recover', value: 0x69 },
  { label: 'Libro', value: 0x6A },
  { label: 'Reserve', value: 0x6B },
  { label: 'Rescue', value: 0x6C },
  { label: 'Warp', value: 0x6D },
  { label: 'Rest', value: 0x6E },
  { label: 'Silence', value: 0x6F },
  { label: 'Sleep', value: 0x70 },
  { label: 'Torch', value: 0x71 },
  { label: 'Return', value: 0x72 },
  { label: 'Repair', value: 0x73 },
  { label: 'Thief', value: 0x74 },
  { label: 'Watch', value: 0x75 },
  { label: 'Berserk', value: 0x76 },
  { label: 'Unlock', value: 0x77 },
  { label: 'Magic Shield', value: 0x78 },
  { label: 'Rewarp', value: 0x79 },
  { label: 'Cure', value: 0x7A },
  { label: 'Broken Staff', value: 0x7B },
  { label: 'Luck Ring', value: 0x7C },
  { label: 'Live Ring', value: 0x7D },
  { label: 'Speed Ring', value: 0x7E },
  { label: 'Magic Ring', value: 0x7F },
  { label: 'Power Ring', value: 0x80 },
  { label: 'Body Ring', value: 0x81 },
  { label: 'Shield Ring', value: 0x82 },
  { label: 'Skill Ring', value: 0x83 },
  { label: 'Leg Ring', value: 0x84 },
  { label: 'Knight Proof', value: 0x85 },
  { label: 'Master Proof', value: 0x86 },
  { label: 'Treasure Key', value: 0x87 },
  { label: 'Door Key', value: 0x88 },
  { label: 'Bridge Key', value: 0x89 },
  { label: 'Thief Key', value: 0x8A },
  { label: 'S Drink', value: 0x8B },
  { label: 'Medicine', value: 0x8C },
  { label: 'Holy Water', value: 0x8D },
  { label: 'Torch', value: 0x8E },
  { label: 'Antidote', value: 0x8F },
  { label: 'Member Card', value: 0x90 },
  { label: 'Odo Scroll', value: 0x91 },
  { label: 'Baldo Scroll', value: 0x92 },
  { label: 'Hezul Scroll', value: 0x93 },
  { label: 'Dain Scroll', value: 0x94 },
  { label: 'Noba Scroll', value: 0x95 },
  { label: 'Neir Scroll', value: 0x96 },
  { label: 'Ulir Scroll', value: 0x97 },
  { label: 'Tordo Scroll', value: 0x98 },
  { label: 'Fala Scroll', value: 0x99 },
  { label: 'Sety Scroll', value: 0x9A },
  { label: 'Blagi Scroll', value: 0x9B },
  { label: 'Heim Scroll', value: 0x9C },
  { label: 'Elite Manual', value: 0x9D },
  { label: 'Duel Manual', value: 0x9E },
  { label: 'Bargain Manual', value: 0x9F },
  { label: 'Ambush Manual', value: 0xA0 },
  { label: 'Wrath Manual', value: 0xA1 },
  { label: 'Continue Manual', value: 0xA2 },
  { label: 'Prayer Manual', value: 0xA3 },
  { label: 'Awareness Manual', value: 0xA4 },
  { label: 'Sunlight Manual', value: 0xA5 },
  { label: 'Moonlight Manual', value: 0xA6 },
];
